경북대 BE_이도훈 2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #100
Opened 2024-07-02 06:52 UTC by 2iedo

### 코드 구현 시 고민했던 점
- 처음 "카카오"가 포함된 이름을 막을 때에는 예외처리로 하려 했는데 BindingResult에 들어가지 않는 문제가 있어서 Pattern 어노테이션의 정규표현식을 수정해서 "카카오"가 포함된 이름을 막았는데, 예외처리로 했을 떄 BindingResult에 넣는 방법이 있나요??
- addProduct 메소드와 editProduct에서 파라미터에 Model이 없으니 제대로 작동하지 않던데, 일단 추가해서 작동이 되는건 확인했지만 이유를 잘 모르겠습니다...

2024-07-03 16:19 UTC, khj68 commented
- 처음 "카카오"가 포함된 이름을 막을 때에는 예외처리로 하려 했는데 BindingResult에 들어가지 않는 문제가 있어서 Pattern 어노테이션의 정규표현식을 수정해서 "카카오"가 포함된 이름을 막았는데, 예외처리로 했을 떄 BindingResult에 넣는 방법이 있나요??

- BindingResult를 활용하려면 Validator를 활용해야 합니다.
```
@Component
public class NameValidator implements Validator {

    @Override
    public boolean supports(Class<?> clazz) {
        return String.class.equals(clazz);
    }

    @Override
    public void validate(Object target, Errors errors) {
        String name = (String) target;
        if (name.contains("카카오")) {
            errors.rejectValue("name", "name.invalid", "이름에 '카카오'가 포함될 수 없습니다.");
        }
    }
}
```
이런 식의 validator를 통해 validate를 진행할 때 에러가 bindingResult에 들어가게 됩니다.

- addProduct 메소드와 editProduct에서 파라미터에 Model이 없으니 제대로 작동하지 않던데, 일단 추가해서 작동이 되는건 확인했지만 이유를 잘 모르겠습니다...

html 코드에서 form-data를 사용하시고 있기 때문입니다.
컨트롤러 메소드에 parameter 를 넣는 것으로는 스프링에서 request 에 해당하는 데이터를 인식할 수 없습니다.
따라서 해당 어노테이션을 통해 요청 객체를 받아주고 있는 것입니다.

2024-07-03 16:19 UTC, khj68 requested changes
고생 많으셨습니다.
validator를 사용하는 방안을 조금 더 고민해주시면 좋을 것 같습니다 :)

2024-07-03 16:19 UTC, khj68 commented on src/main/java/gift/Model/Product.java
> +                      @Pattern(regexp = "^(?!.*카카오)[a-zA-Z0-9가-힣 ()\\[\\]+\\-&/_]*$", message = "허용되지 않은 특수 기호((),[],+,-,&,/,_ 이외)가 있거나, '카카오'가 포함되어 있습니다.")
정규식을 사용한 방법도 좋지만, 다른 필드에도 재사용할 수 있도록 validator와 annotation을 이용하는 방법을 추천드리겠습니다.

2024-07-04 01:36 UTC, 2iedo commented on src/main/java/gift/Model/Product.java
> +                      @Pattern(regexp = "^(?!.*카카오)[a-zA-Z0-9가-힣 ()\\[\\]+\\-&/_]*$", message = "허용되지 않은 특수 기호((),[],+,-,&,/,_ 이외)가 있거나, '카카오'가 포함되어 있습니다.")
넵 감사합니다!

2024-07-05 05:55 UTC, khj68 approved these changes
리뷰 반영된 것 확인했습니다.
고생하셨습니다 :)

2024-07-05 05:55 UTC, khj68 commented on src/main/java/gift/Valid/NameValidator
> +public class NameValidator implements Validator {
validator를 잘 활용해주셨네요 :)

2024-07-05 05:55 UTC, merged