충남대 BE_이은경 2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #103
Opened 2024-07-02 07:34 UTC by pkyung

## 구현 과정
1. ValidPRoductName 어노테이션을 생성하여 각각의 경우에 따라 다른 에러 메시지를 출력하도록 하였습니다. 
2. controller에서 해당 에러를 ExceptionHandler로 받아 처리했습니다. 

## 과제 진행 사항
### 유효성 검사 및 예외 사항
- [x] 상품 이름은 공백 포함 15자까지 입력
- [x]  ( ), [ ], +, -, &, /, _ 외의 특수 문자 불가
- [x] '카카오' 가 포함된 문구는 담당 MD와 협의

2024-07-02 08:34 UTC, ksy90101 requested changes
2단계 고생많으셨습니다~
한번 기본 Validate 어노테이션을 학습해서 리팩토링 해보시면 좋을거 같아요!
언제든 질문이 있다면 DM주세요!

2024-07-02 08:34 UTC, ksy90101 commented on src/main/java/gift/validator/ProductNameValidator.java
> +        }
이부분은 @NotEmpty, @NotNull과 같은 기본 validate로 해결해볼수 있지 않을까요?

2024-07-02 08:34 UTC, ksy90101 commented on src/main/java/gift/validator/ProductNameValidator.java
> +            return false;
이 부분은 @Length로 해결해볼수 있지 않을까요?

2024-07-02 08:34 UTC, ksy90101 commented on src/main/java/gift/validator/ProductNameValidator.java
> +        }
이부분은 @Regex로 해결해볼수 있지 않을까요?

2024-07-02 08:34 UTC, ksy90101 commented on src/main/java/gift/ProductController.java
> +    }
ExcpetionHandler를 따로 클래스로 분리해서 관리해보면 어덜까요?

2024-07-03 06:10 UTC, ksy90101 requested changes
간단한 수정정도만 작성해봤습니다! 궁금한거 있으면 언제든 DM주세요!

2024-07-03 06:10 UTC, ksy90101 commented on src/main/java/gift/ProductController.java
> +    public ResponseEntity makeProduct(@RequestBody @Validated ProductRequestDto requestDto) {
Valid와 Validated의 차이를 알아보면 좋을거 같습니다.

https://velog.io/@tjdtn0219/%EC%8A%A4%ED%94%84%EB%A7%81Valid-vs-Validated

2024-07-03 06:10 UTC, ksy90101 commented on src/main/java/gift/ProductExceptionHandler.java
> +public class ProductExceptionHandler {
👍

2024-07-03 06:10 UTC, ksy90101 commented on src/main/java/gift/ProductExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
```suggestion
        return ResponseEntity.notFound().body(e.getMessage());
```
이렇게 적을수 있습니다~

2024-07-03 06:14 UTC, pkyung commented on src/main/java/gift/ProductExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
notfound가 body를 갖고 있지 않는 것 같습니다.

2024-07-03 06:16 UTC, ksy90101 commented on src/main/java/gift/ProductExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
앗 죄송해요 ㅠㅠ 다른 코드랑 헷갈렸네요.
지금처럼 작성하시면 됩니다!

2024-07-03 06:23 UTC, ksy90101 approved these changes
고생많으셨어요~ 다음 미션도 홧팅입니다!
언제든 궁금한게 있다면 디엠주세요!

2024-07-03 06:23 UTC, merged