충남대 BE_윤정훈 2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #108
Opened 2024-07-02 08:15 UTC by yunjunghun0116

제가 코드를 작성하면서 고민한 내용을 바탕으로 README.md에 저만의 RULE을 만들고, 그에 맞게 코드를 리팩토링 작업을 수행하면서 과제를 수행했습니다.
1주차 피드백에서도 있던 Repository에서 DB의 데이터를 바탕으로 엔티티로 변환하는 과정을 Service로 옮겼다가 Service 계층은 Entity와 DTO(Request, Response) 간의 변환작업을 수행하고, Repository는 DB에 접근하고, 받아온 데이터를 바탕으로 Repository에서 인스턴스를 만들어 반환하는 부분까지 Repository에게 책임을 맡겨도 괜찮은지 여쭤보고싶습니다.

과제 수행 과정
1. README.md 작성
2. 입력 검증을 하기 위한 RequestDto에게 다양한 조건을 주고, Controller에서 @Valid 를 통해 입력검증 책임을 부여
3. Controller계층의 테스트를 수행하기 위해 MockMVC를 사용

위와 같은 과정을 거쳐 1단계 과제를 수행했습니다.

2024-07-02 11:53 UTC, asebn1 requested changes
정훈님 안녕하세요~
1단계도 빠르게 구현해주셨군요 👏👏👏
코드 잘 작성해주셔서 리뷰하기 편했습니다
같이 고민해보면 좋을 부분 코멘트 남겼는데 확인해주세요 :)

2024-07-02 11:53 UTC, asebn1 commented on src/main/java/gift/controller/AdminController.java
> +import org.springframework.web.bind.annotation.RequestMapping;
해당 컨밴션 잘 지켜주시는군요 👍 👍 
추가로 [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) 규칙 중 **모든 소스 파일은 빈 줄로 끝나야 한다**는 컨밴션도 적용해주세요!
[링크](https://hstory0208.tistory.com/entry/IntelliJ-%ED%8C%8C%EC%9D%BC-%EB%81%9D%EC%97%90-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EA%B0%9C%ED%96%89-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0-No-newline-at-end-of-file) 보고 설정해보아요!

2024-07-02 11:53 UTC, asebn1 commented on src/main/java/gift/controller/ProductOptionController.java
>          return ResponseEntity.created(URI.create("/api/options/" + productOption.getId())).build();
`@Valid`를 적용해주었군요~ 
valid를 통해 요청값에 대해 검증을 하고 있는데요, 여기서 정훈님의 생각이 궁금해요 (편히 이야기해주세요 ㅎㅎ)
1. valid를 적용하면 service, domain 계층에서는 값 검증을 하지 않아도 될까요? 아니면 모두 해야할까요? 
2. 검증하는 곳이 많으면(dto, service, domain 등) 코드 관리가 어려워 지지 않을까요? 🤔

2024-07-02 11:53 UTC, asebn1 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +}
👍 👍

2024-07-02 11:53 UTC, asebn1 commented on src/main/java/gift/repository/ProductJDBCRepository.java
>      }
기존 Long 타입에서 Product를 반환하도록 변경되었네요.
어떤 이유일까요?

2024-07-02 11:53 UTC, asebn1 commented on src/main/java/gift/repository/ProductJDBCRepository.java
>      }
하나의 메서드에서 두 가지 일을 하고있어요 (DB저장, 객체 생성) 
아래 예시처럼 같이 메서드를 분리해볼까요?
```java
    public Product save(Product product) {
        Long id = insertAndReturnId(product);
        return createProductWithId(product, id);
    }
```

2024-07-02 11:53 UTC, asebn1 commented on src/main/java/gift/service/ProductService.java
> +        return repository.save(Product.from(productRequest));
같은 `ProductRequest`를 사용해서 내려주고있어요
그리고 `Service`계층에서 `Product`를 반환해주는건 어떻게 생각하시나요?

참고
- https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/
- https://umbum.dev/1206

2024-07-02 11:53 UTC, asebn1 commented on src/test/java/gift/controller/ProductControllerTest.java
> +                .content(objectMapper.writeValueAsString(new ProductRequest("상품1", -1000, "이미지 주소"))));
👍 👍

2024-07-02 11:53 UTC, asebn1 commented on src/main/java/gift/repository/ProductOptionJDBCRepository.java
>      }
발생할 수 있는 다른 에러는 없을까요?

2024-07-02 14:50 UTC, yunjunghun0116 commented on src/main/java/gift/controller/ProductOptionController.java
>          return ResponseEntity.created(URI.create("/api/options/" + productOption.getId())).build();
1. Domain 계층에서도 DTO와 일관되게 값에 대한 검증을 수행하여 데이터베이스에 저장되는 데이터에 대한 무결성을 보장해야할 것 같습니다. 또한 값에 대한 검증은 아니지만 비즈니스 로직과 관련해서 service 계층에서 추가적인 검증이 필요할 수 있다고 생각합니다.
예를 들어 카드 보유 잔액이 50000원인데 10000원짜리 상품을 10개를 구매한다고 하면, 일반적으로 valid를 통해 검증을 하기에는 힘들지만, service계층에서 카드 보유 잔액에 대한 조회를 마치고, 구매할 금액 이상의 잔액을 보유하고 있는 경우만 구매를 진행하도록 하는 로직의 경우 domain이나 controller 계층에서는 검증하기 힘든 로직에 대한 검증이 필요할 수 있다고 생각합니다.

2. dto와 domain의 경우 입력받는 값에 대한 검증이 수행되기 때문에 중복될 수 있고, 이 부분은 각각에 대해 어노테이션을 붙여 검증을 수행하기보다 아래 로직처럼 validation 유효성을 검사하는 기능을 수행하는 함수를 service계층에 위치시키고, DTO <-> Entity 과정에서 다시 한번 비즈니스 로직과 함께 유효성 검사를 수행해줌으로써 최대한 코드 중복으로 인한 관리의 어려움은 최소화 하되, 클라이언트와 Controller간, Controller와 Service간 데이터 변환작업 과정에서 유효성을 검사해 필요한 검사는 모두 수행할 수 있도록 하는게 좋을 수 있겠다고 생각합니다. 
```
private void productIdValidation(Product product) {
        if (products.getPrice() < 0){
            throw new PriceLessThanZeroException("금액은 0원보다 크거나 같아야 합니다.");
        }
        if (products.getName().length() > 15){
            throw new LengthExceededException("상품의 이름은 최대 15글자입니다.");
        }
        ...
}
```

2024-07-02 15:04 UTC, yunjunghun0116 commented on src/main/java/gift/repository/ProductJDBCRepository.java
>      }
> 기존 Long 타입에서 Product를 반환하도록 변경되었네요. 어떤 이유일까요?

DB에 접근하여 다양한 작업을 수행하고, DB에 저장된 데이터와 엔티티간 변환작업을 수행하는 계층은 Repository라고 생각합니다.
그렇기 때문에 기존에는 저장하고 그에 대한 결과만 반환했다면 그 결과를 바탕으로 엔티티로의 변환까지 수행하여 Service계층에 넘겨주기 위해서 이를 Long(저장에 대한 결과)타입에서 Product(저장에 대한 결과 엔티티)타입으로 변경하게 되었습니다.

2024-07-02 15:07 UTC, yunjunghun0116 commented on src/main/java/gift/repository/ProductJDBCRepository.java
>      }
> 하나의 메서드에서 두 가지 일을 하고있어요 (DB저장, 객체 생성) 아래 예시처럼 같이 메서드를 분리해볼까요?
> 
> ```java
>     public Product save(Product product) {
>         Long id = insertAndReturnId(product);
>         return createProductWithId(product, id);
>     }
> ```

감사합니다! 단일 책임에 대한 원칙에 대해 고민을 하고있었는데 메서드를 분리함으로써 해당 메소드가 많은 역할(책임)을 가지지 않도록 할 수 있겠네요!

2024-07-03 06:12 UTC, yunjunghun0116 commented on src/main/java/gift/repository/ProductOptionJDBCRepository.java
>      }
findById 메서드에서 발생할 수 있는 다른 에러는 없다고 생각합니다.

근거 1. 참조하고 있는 상품의 삭제 발생시 우선 상품 옵션에 대해 삭제를 진행한 후 상품을 삭제하기 때문에 삭제 작업시 외래키 제약조건에 위배되지 않기에 잘못된 product_id를 가리키지 않을것이라고 판단했습니다.
근거 2. id는 repository에서 만들어 주는것이 아닌, auto_increment 속성을 사용하기 때문에 id를 통해 접근하는 경우 존재하지 않거나 오직 하나의 데이터만 존재한다고 판단하여 IncorrectResultSizeDataAccessException 예외는 발생하지 않는다고 판단했습니다.

하지만 고민을 하던 도중 오히려 insert 부분에서 DataIntegrityViolationException 이 발생할 수 있다고 생각했습니다.
존재하지 않는 product_id 를 갖게 되면 외래키 제약조건에 위배되어 예외가 발생하며 이에 대한 예외 처리를 하기 위해 ForeignKeyConstraintViolationException 을 발생시키고, ExcepionHandler에서 이를 처리했습니다.

2024-07-03 06:22 UTC, yunjunghun0116 commented on src/main/java/gift/service/ProductService.java
> +        return repository.save(Product.from(productRequest));
Service계층에서 Product 라는 DB에 저장되어있는 객체의 모든 정보를 반환해주는건 옳지 않다고 생각합니다.
민감한 정보가 담겨있을 수 있기 때문에 클라이언트에게는 필요한 정보만을 담아 반환하는 ResponseDto 객체에 담아 반환해주는것이 옳다고 생각합니다.

2024-07-03 17:32 UTC, asebn1 commented on src/main/java/gift/controller/ProductOptionController.java
>          return ResponseEntity.created(URI.create("/api/options/" + productOption.getId())).build();
정훈님의 생각이 보여서 좋네요 ㅎㅎ 👍

2024-07-03 17:53 UTC, asebn1 approved these changes
정훈님 안녕하세요~
이번 과제도 빠르게 구현해주셨네요! 
코드에서도 점차 성장하시는게 보입니다 👍 
몇 가지 코멘트 남겨보았는데 확인 부탁드리고 1단계는 바로 머지하겠습니다!

추가로 확인사항 두 가지가 있어요.
먼저, 객체지향 생활체조원칙 4.한 줄에 점을 하나만 사용한다 부분 코드 전체적으로 확인해주세요.
그리고 @를 붙이고 감싸지 않으면 아래와 같이 해당 유저가 멘션이 됩니다 ㅎㅎㅎ 다음엔 감싸서 작성해주세요 (`@Valid` 부분이에요)

<img width="386" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/57438644/b5817709-cad8-407c-999a-d1e1dffca226">

2024-07-03 17:53 UTC, asebn1 commented on src/main/java/gift/service/ProductService.java
> +        return repository.save(Product.from(productRequest));
`ResponseDto`로 잘 구성하셨네요 👍 

`ProductRequest` 클래스는 어떨까요? `ProductRequest`를 `Controller`, `model` 계층 둘 다 의존하고 있어요.

2024-07-03 17:53 UTC, asebn1 commented on src/main/java/gift/controller/ProductController.java
>          var product = service.addProduct(productRequest);
`var`를 사용하는 곳이 있고 아닌곳이 있어요.
구조를 공통으로 맞추는건 어떨까요?

2024-07-03 17:53 UTC, asebn1 commented on src/main/java/gift/repository/ProductOptionRepository.java
> +    ProductOption save(ProductOption productOption);
줄 간견이 0줄, 1줄, 2줄로 다르게 되어있어요!
컨밴션을 맞춰보아요

2024-07-03 17:53 UTC, merged