경북대 BE_배규민 2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #110
Opened 2024-07-02 08:24 UTC by GyuminBae

* 2주차 1단계 과제 PR입니다!

2024-07-02 14:44 UTC, lsm7179 requested changes
규민님.
요구사항 확인 하고 다시 리뷰요청 보내주세요.😃
* "카카오"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있다.

2024-07-02 15:30 UTC, BGMSound commented
> 규민님. 요구사항 확인 하고 다시 리뷰요청 보내주세요.😃
> 
> * "카카오"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있다.

헉 온라인 클론코딩 강의 때 전달받았던 사항으론 "카카오" 문구가 포함되면 validation exception throw 하는 식으로 처리하라고 전달받았던 것 같아서 막았는데, 혹시 안에 기재되어있는 문구 문제일까요..?
문구는 수정해서 push했습니다!

2024-07-03 11:31 UTC, lsm7179 commented
> > 규민님. 요구사항 확인 하고 다시 리뷰요청 보내주세요.😃
> > 
> > * "카카오"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있다.
> 
> 헉 온라인 클론코딩 강의 때 전달받았던 사항으론 "카카오" 문구가 포함되면 validation exception throw 하는 식으로 처리하라고 전달받았던 것 같아서 막았는데, 혹시 안에 기재되어있는 문구 문제일까요..? 문구는 수정해서 push했습니다!

규민님. 안녕하세요.
제이슨이랑 내용 확인한결과 잘 처리해주신거 같아요~
제가 요구사항을 복잡하게 생각했습니다 :)

2024-07-03 12:08 UTC, lsm7179 approved these changes
규민님 요구사항 대로 잘 하신거 같아요.👍
merge 하겠습니다~!

코멘트 남긴 것들 한번 확인해보시고 궁금하신거 있으면 DM주세요~!

2024-07-03 12:08 UTC, lsm7179 commented on src/main/java/gift/advice/ErrorResponse.java
> +}
record 활용 좋습니다!

2024-07-03 12:08 UTC, lsm7179 commented on src/main/java/gift/core/exception/APIException.java
> +    }
APIException 를 통해서 잘 에러처리해주셨어요~!

2024-07-03 12:08 UTC, lsm7179 commented on src/main/java/gift/product/restapi/validator/NotContainingKaKao.java
> +}
custom validator 잘 만들어주셨습니다.

2024-07-03 12:08 UTC, lsm7179 commented on src/main/java/gift/product/restapi/dto/request/ProductCreateRequest.java
> +        @Pattern(regexp = "^[a-zA-Z0-9가-힣()\\[\\]+\\-&/_ ]*$", message = "특수문자는 ()[]+-&/_ 만 허용됩니다.")
👍

2024-07-03 12:08 UTC, lsm7179 commented on src/main/java/gift/product/restapi/ProductController.java
>  public class ProductController {
테스트코드를 통하여 request가 잘 막아지는지 검증해보면 좋을거 같아요.
지금은 로컬에서 서버를 실행 후 수동테스트를 진행중이지만 테스트 코드를 적용하면 빠르게 성공과 실패지점을 알 수 있어서 리팩토링,기능 수정, 추가할때 부담이 덜 합니다.
스프링에서는 테스트코드를 위해 많은 것들을 지원하니 한번 해보셨으면 좋겠네요~!

2024-07-03 12:08 UTC, lsm7179 commented on src/main/java/gift/product/restapi/ProductController.java
> +        productService.updateProduct(updatedProduct);
Product가 너무 빈약한 도메인 객체가 된거 같아요.
update를 Product 객체에서 해보는건 어떨까요?

예를 들어
```java
Product updateProduct = new Product(productUpdateRequest.name(), productUpdateRequest.price(), productUpdateRequest.imageUrl());
originalProduct.update(updateProduct);
```

이러면 수정에 대한 단위테스트도 만들수 있을거에요.

2024-07-03 12:08 UTC, merged