경북대 BE_이지호_2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #111
Opened 2024-07-02 09:45 UTC by GitJIHO

**코드 작성하면서 어려웠던 점**
---

- Validation을 활용하면서 예외 처리를 해보았는데 "카카오"가 포함된 경우를 처리하는 과정에서  Validation에 기본으로 포함되어있는 어노테이션 중 이를 처리하는게 없어 NoKakao라는 어노테이션을 만들어서 진행하였는데, 이 과정에서 인터페이스에 group 디폴트값과 payload 디폴트 메소드를 넣거나 Retetion Constraint 어노테이션이 잘 이해되지 않고 현재 제 수준에 비해 난이도가 높은 것 같습니다. 혹시 다른 방법으로 진행할 수 있는지 궁금합니다.

**코드 리뷰 시, 멘토님이 중점적으로 리뷰해주셨으면 하는 부분**
---

- GlobalExceptionHandler에서 같은 필드에 여러개의 오류가 있는 경우를 대비해 해시맵에 넣어 처리했는데, 적절한 방법인지 궁금합니다.
- 앞서 말씀드린것처럼, Validation기능을 활용하여 BindingResult에 오류 메세지들을 넣기 위해 NoKakao 어노테이션을 만들어 사용했는데, Product 클래스에서 getName메소드에 직접 카카오가 포함된 경우를 처리하는 exception을 만들어 볼까도 하였지만 개인적으로 문제가 요구하는 방향과 맞지 않는다고 생각하여 하지 않았습니다. 또한 이런경우 서버 사이드 랜더링을 구현할 때 카카오 포함과 관련된 오류 메세지를 @Valid를 이용하지 못하고 product 객체를 통해 직접 전달해야 한다고 생각했는데 혹시 다른 방법이 있는지 궁금합니다.

2024-07-02 10:28 UTC, GitJIHO commented
충돌을 잡지 않으면 리뷰요청에 문제가 생겨서 직접 해결했는데 직접 해결하는게 맞나요?

2024-07-02 15:34 UTC, sang5c requested changes
안녕하세요 지호님 빠르게 PR 올려주셨네요 🔥  
아쉽지만 컨벤션이 지켜지지 않아 request change를 드려요!  

다른 리뷰와 질문 주신 내용에 대해 답변을 달았으니 확인해주세요.

> 커스텀 어노테이션 대신 다른 방법으로 진행할 수 있는지?

@Pattern 어노테이션은 여러개 사용이 가능합니다!  
묶어서 @Pattern.List로 사용할 수도 있구요 (묶지 않아도 동일합니다)
https://www.baeldung.com/java-validation-list-annotations  

또 다른 방법으로는 컨트롤러 혹은 서비스에서 직접 값을 검사하는 방법도 있겠네요.

> GlobalExceptionHandler에서 같은 필드에 여러개의 오류가 있는 경우를 대비해 해시맵에 넣어 처리했는데, 적절한 방법인지 궁금합니다.

이 부분은 리뷰 남겼으니 확인해주세요 :) 

마지막 질문은 위에 답변드려서 생략했습니다.

2024-07-02 15:34 UTC, sang5c commented on src/main/java/gift/controller/ProductAdminController.java
> +        if(bindingResult.hasErrors()){
정렬하는 습관을 들여주세요!  
https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace

2024-07-02 15:34 UTC, sang5c commented on src/main/java/gift/controller/ProductAdminController.java
> +        if(bindingResult.hasErrors()){
컨벤션은 기본입니다 :)  
모든 코드에 대해 정렬과 import 정리를 수행해주세요.  
intellij 기준 명령어 `Reformat code` 와 `Optimize imports` 입니다.

2024-07-02 15:34 UTC, sang5c commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +            String errorMessage = error.getDefaultMessage();
fieldName과 errorMessage라는 필드를 갖는 객체를 반환하는 방식은 어떨까요?

2024-07-02 15:34 UTC, sang5c commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        MethodArgumentNotValidException ex) {
줄여쓰기를 지양해주세요!  
`규칙 5: 줄여 쓰지 않는다. (축약 금지)`

2024-07-02 15:34 UTC, sang5c commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        ex.getBindingResult().getAllErrors().forEach((error) -> {
`규칙 4: 한 줄에 점을 하나만 찍는다.`

2024-07-02 15:34 UTC, sang5c commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(RuntimeException.class)
RuntimeException은 Unchecked Exception의 최상위 클래스입니다.  
여기서 RuntimeException에 대해 잡게 되면 의도하지 않은 부분(잘못된 파라미터 전달 등)까지 모두 404 NOT FOUND 응답을 받게 돼요.  

혹시 처음 접하시는 개념이라면 간단히 넘어가셔도 좋습니다. 키워드만 기억해주세요 :) 
기존 코드에서 작성한 RuntimeException 대신 별도의 Exception 클래스를 정의하고 사용하는 방식도 있습니다.  
https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/

2024-07-03 05:13 UTC, GitJIHO commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(RuntimeException.class)
처음 접하는 개념이라 관련 정보 찾아보면서 이해해보겠습니다. 감사합니다!

2024-07-03 05:18 UTC, GitJIHO commented on src/main/java/gift/controller/ProductAdminController.java
> +        if(bindingResult.hasErrors()){
네 인텔리제이 설정에서도 추가했습니다!

2024-07-03 05:48 UTC, GitJIHO commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +            String errorMessage = error.getDefaultMessage();
넵 해당 필드를 갖는 ErrorDTO 클래스를 만들어 반환하도록 하였습니다

2024-07-03 05:49 UTC, GitJIHO commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        MethodArgumentNotValidException ex) {
축약을 안쓰면 메서드가 너무 길어져서 메서드를 일단 분리하고 축약이 필요한 부분에만 사용해보았습니다

2024-07-03 05:50 UTC, GitJIHO commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        ex.getBindingResult().getAllErrors().forEach((error) -> {
넵 수정했습니다!

2024-07-03 16:45 UTC, sang5c approved these changes
1단계 머지합니다! 👏👏  

마지막으로 읽어보시면 좋을만한 내용 남겼으니 확인해주세요!

2024-07-03 16:45 UTC, sang5c commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        List<ErrorDTO> fieldErrorDTOList = createErrorDTOList(exception);
👍👍 마지막으로 ProblemDetail 클래스에 대해 알아보시면 좋을 것 같아요.
강의 자료 중 "웹 API 설계" 페이지의 "에러 응답" 문서를 보시면 더욱 좋습니다!

https://luvstudy.tistory.com/220

2024-07-03 16:46 UTC, merged