부산대 BE_황수환_2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #114
Opened 2024-07-02 11:45 UTC by HSHwan

# 코드 구현하면서 생긴 질문

1. 웹서버를 올려서 클라이언트 관점으로 테스트해보면 포스트맨으로 테스트한 결과와 다른 경우가 종종 있습니다.
보통 캐시나 네트워크 문제로 인해 각각의 테스트 결과가 차이가 생기는 것 같은데 이러한 차이를 없애는 방향으로
수정하면 좋을지 아니면 서로 다른 영역으로 봐야 하는지 궁금합니다.

2. 테스트 코드에서 AssertJ와 JUnit을 번갈아 사용했는데, 통일성 있게 하나만 선택해서 사용할지
아니면 둘 다 사용하는 것이 좋을지 궁금합니다.

3. ProductRequest DTO를 jakarta.validation.constraints 어노테이션(NotEmpty, Pattern 등)으로 유효성 검사했는데, spring.validation의 Validator 인터페이스를 이용하는 것이 더 좋은 방법인지 궁금합니다.

2024-07-03 13:14 UTC, hocaron commented
수환님, 이번 작업에는 포함되어있지는 않지만 save 하는 부분에서 한번 더 조회하는 것 대신 키홀더에 있는 값으로 객체를 새로 만들어주는 방식으로 사용해볼 수 있을 것 같아요.

이 방법은 어떻게 생각하시는지 궁금해요💭

```java
    @Override
    public Product save(Product product) {
        String sql = "INSERT INTO product (name, price, image_url) VALUES(?, ?, ?)";
        GeneratedKeyHolder keyHolder = new GeneratedKeyHolder();

        jdbcTemplate.update(connection -> {
            PreparedStatement statement = connection.prepareStatement(sql, new String[]{"id"});
            statement.setString(1, product.getName());
            statement.setInt(2, product.getPrice());
            statement.setString(3, product.getImageUrl());
            return statement;
        }, keyHolder);

        // 삽입된 키를 가져와서 Product 객체에 설정
        return new Product(
            keyHolder.getKey().longValue(),
            product.getName(),
            product.getPrice(),
            product.getImageUrl()
        );
    }
```

2024-07-03 13:38 UTC, hocaron requested changes
1. 웹서버를 올려서 클라이언트 관점으로 테스트해보면 포스트맨으로 테스트한 결과와 다른 경우가 종종 있습니다.
보통 캐시나 네트워크 문제로 인해 각각의 테스트 결과가 차이가 생기는 것 같은데 이러한 차이를 없애는 방향으로 수정하면 좋을지 아니면 서로 다른 영역으로 봐야 하는지 궁금합니다.

테스트 결과의 차이를 최소화하는 방향이 더 좋습니다! 테스트 결과가 달랐던 케이스에 구체적으로 공유해주신다면 같이 고민해볼 수 있을 것 같아요😀

2. 테스트 코드에서 AssertJ와 JUnit을 번갈아 사용했는데, 통일성 있게 하나만 선택해서 사용할지
아니면 둘 다 사용하는 것이 좋을지 궁금합니다.

AssertJ와 JUnit을 번갈아 사용하시는 상황에서, 어떤 접근법이 더 나을지 생각하는 것은 좋은 고민입니다👍

코드의 일관성이 떨어질 수 있고, 가독성이 저하될 수 있다는 점에서 하나로 통일하여 사용하는 것이 더 좋다고 생각합니다! 수환님은 둘중에 어떤 것을 적용했을 때 코드가 읽기 편한지 궁금합니다.

3. ProductRequest DTO를 jakarta.validation.constraints 어노테이션(NotEmpty, Pattern 등)으로 유효성 검사했는데, spring.validation의 Validator 인터페이스를 이용하는 것이 더 좋은 방법인지 궁금합니다.

NotEmpty, Pattern, MIN, MAX 모두 개발자들이 많이 알고, 사용하는 validation 을 위한 어노테이션이기 때문에 위의 어노테이션으로 검증가능한 부분은 어노테이션으로 처리하는 것이 좋을 것 같습니다! 

Validator 인터페이스 사용시에 구현체 코드를 한번 더 확인해야하기 때문에, 커스텀한 검증이 아니라면 어노테이션으로 처리하는 것이 더 좋을 것 같습니다.

2024-07-03 13:38 UTC, hocaron commented on src/main/java/gift/validator/KakaoValidator.java
> +        }
빈문자열인지 validation 하는 메서드가 2개 인 것 같아요😀 @NotEmpty 외에 여기서도 validation 하는 이유가 있을까요?!

2024-07-03 13:38 UTC, hocaron commented on src/test/java/gift/api/ProductControllerTest.java
> +        when(productService.getProductById(productId)).thenThrow(exception);
실패하는 케이스에 대한 테스트도 작성해주셨네요👍

2024-07-03 13:38 UTC, hocaron commented on src/main/java/gift/validator/KakaoValidator.java
> +        return !value.contains("카카오");
카카오라는 문자열을 변수화하여 관리하면 코드의 의도를 더 명확하게 전달할 수 도 있을 것 같아요🤔

```java
private static final String INVALID_SUBSTRING = "카카오";
```

위에처럼 관리했을 때, 수환님 생각은 어떠신지 궁금해요!

2024-07-03 13:38 UTC, hocaron commented on src/main/java/gift/domain/Product.java
>      public Product(ProductRequest request) {
이 생성자는 사용이 되지 않는 것 같아서 제거해도 좋을 것 같아요😀

2024-07-03 13:38 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +    public Long updateProduct(Long id, ProductRequest request) throws NoSuchElementException {
해당 예외를 throw 하신 이유가 궁금해요!

예외 관련해서 읽어보기 좋은 [[Java] Checked Exception vs Unchecked Exception 정리](https://devlog-wjdrbs96.tistory.com/351)도 하나 공유드려요.

2024-07-03 13:38 UTC, hocaron commented on src/main/java/gift/dao/MemoryProductRepository.java
> +
코드 컨벤션이 일관성 있네요😎

2024-07-03 13:38 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +        getProductById(id); // 상품 존재 여부 확인
조회 후에 없으면 예외를 반환하고 있어서 메서드에 이런 행동을 담아도 좋을 것 같은데, 어떻게 생각하시는지 궁금해요!

```java
getProductByIdOrThrow
```

2024-07-03 13:38 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +        return productRepository.findAll().stream()
디미터의 법칙 `한 줄에 점을 하나만 찍는다`을 적용해보는 것은 어떨까요?!

2024-07-03 13:38 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +                .collect(Collectors.toList());
`.collect(Collectors.toList());` 와 `.toList();` 는 어떤 차이가 있을까요?!!😀

2024-07-03 13:45 UTC, hocaron commented
이건 제가 회사에서 리뷰 받은 후에 적용하는 방식이라 반영하지 않으셔도 됩니다😀

코멘트에 대한 답변에 9b7804e 수정된(리뷰 반영된) 커밋 코드를 함께 적으면 리뷰하는 입장에서 편하게 느끼시더라고요! 공유드려봅니당.

2024-07-03 14:52 UTC, HSHwan commented on src/main/java/gift/validator/KakaoValidator.java
> +        }
습관적으로 empty 체크를 하다보니 중복으로 validation 하게 되었던 것 같습니다.
[21cf392](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/114/commits/21cf392b31eab233277c974ceec20ac13ea66dfb) - 피드백 반영해서 수정했습니다!

2024-07-03 14:57 UTC, HSHwan commented on src/main/java/gift/validator/KakaoValidator.java
> +        return !value.contains("카카오");
나중에 문구를 수정할 때 변수로 편리하게 관리할 수도 있어 좋은 방법이라 생각합니다!
 [21cf392](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/114/commits/21cf392b31eab233277c974ceec20ac13ea66dfb) - 피드백 반영하여 해당 내용으로 수정했습니다.

2024-07-03 15:06 UTC, HSHwan commented on src/main/java/gift/domain/Product.java
>      public Product(ProductRequest request) {
상품 도메인 DTO 변환 리팩토링 이후에 미사용 생성자를 제거하는 것을 놓쳤던 것 같습니다.
[be2d4d1](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/114/commits/be2d4d116963a3976c6698c453fbe33295638a4c)  - 불필요한 내용이라 바로 수정했습니다!

2024-07-03 15:49 UTC, HSHwan commented on src/main/java/gift/application/ProductService.java
> +    public Long updateProduct(Long id, ProductRequest request) throws NoSuchElementException {
해당 예외가 발생할 수 있음을 알려주려는 의도로 throws를 사용했는데
unchecked exception의 특성을 알게 되니 throws를 잘못 사용하고 있다는 것을 깨달았습니다.
추가적으로 [throws는 언제 사용해야할까?](https://velog.io/@sangmin7648/throws%EB%8A%94-%EC%96%B8%EC%A0%9C-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C)를 통해 throws에 대해 이해할 수 있었습니다.
[2128af4](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/114/commits/2128af4ce8762e65c14dd24a33b068acab3ef575) - 피드백 내용 반영했습니다!

2024-07-03 15:57 UTC, HSHwan commented on src/main/java/gift/application/ProductService.java
> +        getProductById(id); // 상품 존재 여부 확인
지금의 메서드의 행동을 보면 조회 뿐만 아니라 unchecked 예외를 발생시키므로 해당 메서드에 추가적인 설명이
필요할 것 같습니다.
[2128af4](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/114/commits/2128af4ce8762e65c14dd24a33b068acab3ef575) - 바로 반영해도 될 내용이라 생각해 수정했습니다!

2024-07-03 16:00 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +    public Long updateProduct(Long id, ProductRequest request) throws NoSuchElementException {
좋은 내용 공유주셔서 감사합니다😎

2024-07-03 16:02 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +        getProductById(id); // 상품 존재 여부 확인
오홋! 그렇군요!

빠른 답변 감사드립니다. 저도 비슷한 이유로 throw를 붙이고 있어서 공유드려보았습니다.

2024-07-03 16:19 UTC, HSHwan commented on src/main/java/gift/application/ProductService.java
> +        return productRepository.findAll().stream()
한 줄에 두 메서드가 연결되어 있어서 읽기에 조금 불편한 감이 있는 것 같습니다.
[5bdbd59](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/114/commits/5bdbd59015a57dc134fac80f219e92a1f4242e6b) - 따로 나눠서 각 줄의 데이터 흐름을 확인하기 쉽게 수정했습니다!
그리고 디미터의 법칙에 대해 전혀 모르고 있었는데 알려주셔서 감사합니다!
오늘 [디미터의 법칙](https://mangkyu.tistory.com/147)에 대해 배우고 이번 과제에 적용해보겠습니다.

2024-07-03 16:43 UTC, HSHwan commented on src/main/java/gift/application/ProductService.java
> +                .collect(Collectors.toList());
두 메서드 모두 List를 반환합니다. 대신 전자는 수정 가능한 List를 반환하지만 후자는 수정 불가능한 List를 반환한다는 차이점이 있습니다.
지금 상황에서는 DB에서 가져온 데이터를 수정할 이유가 없으므로 수정 불가능한 List를 반환하도록 하는 것이 올바르다고 생각합니다.
[Collectors.toList() vs Stream.toList()](https://velog.io/@cieroyou/Stream%EC%9D%84-List%EB%A1%9C-%EB%B3%80%ED%99%98%ED%95%98%EB%8A%94-%EB%8B%A4%EC%96%91%ED%95%9C-%EB%B0%A9%EB%B2%95%EA%B3%BC-%EC%B0%A8%EC%9D%B4Collectors.toList-vs-Stream.toList)에서 간략히 두 메서드 간의 차이를 알 수 있었고,
[오라클 공식 문서](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html)에서 자세한 내용을 확인할 수 있었습니다.
[5bdbd59](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/114/commits/5bdbd59015a57dc134fac80f219e92a1f4242e6b) - 관련 자료들 다 확인한 후에 toList()로 수정했습니다.

2024-07-03 16:50 UTC, hocaron commented on src/main/java/gift/validator/KakaoValidator.java
> +        }
수환님 요부분은 @Kakao 어노테이션 혼자 사용했을때 npe 가 발생할 수 있어, isEmpty 를 채크해주신 것 같아요! 맞을까요?!!😀 npe 방지를 위한 좋은 방어입니다.

해당 어노테이션이 카카오라는 문자열이 포함되었는지 검증하는 역할을 하는거라면, isEmpty 인 경우, true 를 반환(검증 통과)하도록 하는 것은 어떻게 생각하실까요?!!

2024-07-03 16:53 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +                .collect(Collectors.toList());
문서 공유 감사합니다 👍

2024-07-03 17:23 UTC, HSHwan commented on src/main/java/gift/validator/KakaoValidator.java
> +        }
해당 문자열이 isEmpty이면 '카카오'가 절대 포함되지 않아 논리적으로 true를 반환하는 것이 맞다고 생각합니다.
현재 코드와 별개로 다른 코드에서 사용한다면 npe에 직면할 수 있으니 결국 isEmpty를 체크해야 할 것 같습니다.
[af2381d](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/114/commits/af2381d249ad22161e2e5a303952cdc6b8d370cf) - 생각 못했던 부분에서 피드백해주셔서 감사합니다!

2024-07-03 17:35 UTC, HSHwan commented
이번 주에도 피드백을 많이 해주셔서 감사합니다!
피드백 하나하나 확인하면서 제가 놓쳤던 부분이나 전혀 모르고 있었던 내용에 대해 언급해주셔서 덕분에 많이 알아 가는 것 같습니다.
그리고 질문에 대해 명쾌하게 답변해주셔서 안고 있었던 고민을 해결할 수 있었습니다.
Kakao 어노테이션 이름은 validation을 의미를 더해서 KakaoValidator로 변경했고, 해당 어노테이션에 대한 validator 이름 또한 KakaoConstraintValidator로 변경했습니다. - commit : [49b9b94](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/114/commits/49b9b94e0d120d74a6d377afe16c7e1cee64f774)

2024-07-03 17:46 UTC, HSHwan commented
> 수환님, 이번 작업에는 포함되어있지는 않지만 save 하는 부분에서 한번 더 조회하는 것 대신 키홀더에 있는 값으로 객체를 새로 만들어주는 방식으로 사용해볼 수 있을 것 같아요.
> 
> 이 방법은 어떻게 생각하시는지 궁금해요💭
> 
> ```java
>     @Override
>     public Product save(Product product) {
>         String sql = "INSERT INTO product (name, price, image_url) VALUES(?, ?, ?)";
>         GeneratedKeyHolder keyHolder = new GeneratedKeyHolder();
> 
>         jdbcTemplate.update(connection -> {
>             PreparedStatement statement = connection.prepareStatement(sql, new String[]{"id"});
>             statement.setString(1, product.getName());
>             statement.setInt(2, product.getPrice());
>             statement.setString(3, product.getImageUrl());
>             return statement;
>         }, keyHolder);
> 
>         // 삽입된 키를 가져와서 Product 객체에 설정
>         return new Product(
>             keyHolder.getKey().longValue(),
>             product.getName(),
>             product.getPrice(),
>             product.getImageUrl()
>         );
>     }
> ```

객체를 새로 만들어서 반환하는 방법으로 하면 상품을 조회하는 비용을 줄일 수 있으나
실제로 상품이 정상적으로 추가되었는지 확인된 것이 아니라서 고민됩니다.
이 경우에는 상품 추가에만 생각해야 하는지 궁금합니다.

2024-07-04 02:01 UTC, hocaron commented
아하!그런 고민이 되셨군요!

상품이 insert 되었지만, 정말 insert 가 된 건지 조회를 통해 확인이 필요할 것 같다고 말씀주신 것으로 이해했습니다! 제가 이해한 부분이 맞을까요?!😀

2024-07-04 02:08 UTC, HSHwan commented
> 아하!그런 고민이 되셨군요!
> 
> 상품이 insert 되었지만, 정말 insert 가 된 건지 조회를 통해 확인이 필요할 것 같다고 말씀주신 것으로 이해했습니다! 제가 이해한 부분이 맞을까요?!😀

넵 맞습니다. 상품 수정을 확인하는 과정을 생략하고 그저 insert에만 충실해야 되는지 궁금한 것입니다.

2024-07-04 03:12 UTC, hocaron commented
> 넵 맞습니다. 상품 수정을 확인하는 과정을 생략하고 그저 insert에만 충실해야 되는지 궁금한 것입니다. 계속 고민하다 보니 상품 수정을 확인하는 것이 기존 상품 수정 기능을 넘어서는 행위라 생각되어 피드백 내용 반영하는 것이 좋을 것 같습니다! - [b00bf4b](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/114/commits/b00bf4ba05d56deeb77b0b236231aa4a38f6c2c8)

GeneratedKeyHolder는 JDBC를 통해 데이터베이스에 새로운 레코드를 삽입할 때 데이터베이스를 통해서 채번된 키(예: auto_increment ID)를 저장하는 데 사용하기 때문에, `keyHolder.getKey().longValue()` 값이 존재하면 데이터베이스에 데이터가 정상적으로 insert 된 것이라고 생각해서 추가적인 쿼리가 필요없을 것이라고 저는 생각했는데요🤔
insert 하다가 제약조건 때문에 에러가 발생하면 `keyHolder.getKey().longValue()` 값이 생성되지 않을 것 같아서요!

`keyHolder.getKey()` 값이 null 이 아닌데, insert 도 제대로 되지 않는 케이스가 있는지 같이 고민해보면 좋을 것 같아요. 롤백이 되는 케이스나 등등... 제가 틀릴 수도 있는 부분이라 편하게 말씀 주시면 좋을 것 같습니다🙇‍♀️

2024-07-04 03:16 UTC, hocaron approved these changes
수환님 리뷰 반영해주시느라 고생 많으셨습니다🌟

도움되는 자료들 및 생각을 공유해주셔서 감사해요👍 
다음 단계에서 뵙기 위해 (GeneratedKeyHolder 마무리하자마자) 해당 PR 은 머지하겠습니다!

2024-07-04 03:32 UTC, HSHwan commented
> > 넵 맞습니다. 상품 수정을 확인하는 과정을 생략하고 그저 insert에만 충실해야 되는지 궁금한 것입니다. 계속 고민하다 보니 상품 수정을 확인하는 것이 기존 상품 수정 기능을 넘어서는 행위라 생각되어 피드백 내용 반영하는 것이 좋을 것 같습니다! - [b00bf4b](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/114/commits/b00bf4ba05d56deeb77b0b236231aa4a38f6c2c8)
> 
> GeneratedKeyHolder는 JDBC를 통해 데이터베이스에 새로운 레코드를 삽입할 때 데이터베이스를 통해서 채번된 키(예: auto_increment ID)를 저장하는 데 사용하기 때문에, `keyHolder.getKey().longValue()` 값이 존재하면 데이터베이스에 데이터가 정상적으로 insert 된 것이라고 생각해서 추가적인 쿼리가 필요없을 것이라고 저는 생각했는데요🤔 insert 하다가 제약조건 때문에 에러가 발생하면 `keyHolder.getKey().longValue()` 값이 생성되지 않을 것 같아서요!
> 
> `keyHolder.getKey()` 값이 null 이 아닌데, insert 도 제대로 되지 않는 케이스가 있는지 같이 고민해보면 좋을 것 같아요. 롤백이 되는 케이스나 등등... 제가 틀릴 수도 있는 부분이라 편하게 말씀 주시면 좋을 것 같습니다🙇‍♀️

keyHolder.getKey().longValue() 값 존재 여부로 insert 확인이 되는지는 몰랐군요!
GeneratedKeyHolder에 대해 자세히 알아봐야 할 것 같습니다.
자세한 설명 감사합니다! 덕분에 이해가 잘 된 것 같습니다.

2024-07-04 03:36 UTC, hocaron commented
> keyHolder.getKey().longValue() 값 존재 여부로 insert 확인이 되는지는 몰랐군요! GeneratedKeyHolder에 대해 자세히 알아봐야 할 것 같습니다. 자세한 설명 감사합니다! 덕분에 이해가 잘 된 것 같습니다.

좋은 자료 발견하시면 저도 공유해주세욧! 저도 엣지 케이스 찾아보겠습니다. 고생 많으셨습니다👍

2024-07-04 03:36 UTC, merged