전남대 BE_김보민_2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #122
Opened 2024-07-02 15:14 UTC by KBM05haruin30

### 코드 작성하면서 어려웠던 점
validation을 처음 사용해 봐서 참고 자료를 보면서 했습니다. 참고 자료로 못 찾은 내용들은 구글링을 통해 찾아서 사용하였습니다. 처음 사용하는 것이다 보니 헷갈리는 것들이 있었습니다. 또한, 중복된 로직을 제거하면서 제가 생각한 순서랑 다르게 흘러가는 느낌이 있었습니다.

### 궁금한 점
1. 중복된 로직을 사용하기 위해 새로 메서드를 만들어 코드를 작성했습니다. 하지만 제가 생각한 순서랑 다르게 흘러가는 것 같습니다. 상품을 추가할 때 가격에 숫자가 아닌 값만 넣으면 다른 곳에서는 예외 처리 메시지가 발생하지 않습니다.
![캡처 PNG1231](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/138747411/2c51a81d-573e-4e90-b65c-c1d35cded7d4)

2. 제가 작성한 코드는 클라이언트가 잘못된 값을 입력하면 입력하는 칸 밑에 예외 처리 메시지가 나옵니다. GlobalExceptionHandler에서 @ResponseStatus를 사용하여 예외 처리를 하면 400 Bad Request를 반환하도록 했습니다. 하지만 크롬에서 개발자 도구를 킨 다음 잘못된 값을 입력해보면 http status 400이 보이지 않고 200이 보입니다. 이렇게 보이는게 정상인지 궁금합니다. 만약 정상이라면 400은 어디서 확인할 수 있는지도 궁금합니다.

2024-07-04 17:32 UTC, Hongdonggeon reviewed
보민님 안녕하세요  
미션 진행하느라 수고하셨습니다! 
기본 요구사항에 대해서는 잘 구현하셨어요 👍
지금은 요구사항이 작고 간단해서 괜찮지만, 서비스 계층을 추가해서 검증 로직을 작성하는 것도 좋을 것 같아요! 
그리고 간단한 코멘트들  남겨놓았습니다! 반영하면서 궁금한 것 있으시면 질문주세요!

2024-07-04 17:32 UTC, Hongdonggeon commented on src/main/java/gift/Model/ProductDTO.java
> +public record ProductDTO(Long id,
화면에서 id 값을 받지 않고 있어서, Dto에 id 필드가 있을 필요가 없을 것 같아요!

2024-07-04 17:32 UTC, Hongdonggeon commented on src/main/java/gift/Controller/ProductConverter.java
> +    }
ProductConverter 객체도 좋지만, 요구사항이 많아지고 다루는 객체가 많아진다면 모든 객체에 대해 Converter를 만들긴 힘들거예요 
이 메서드는 ProductDto 클래스안에 만들어도 되지 않을까요?

2024-07-04 17:32 UTC, Hongdonggeon commented on src/main/java/gift/Model/ProductDTO.java
> +public record ProductDTO(Long id,
Dto 클래스가 모델 패키지 안에 있네요? Dto는 컨트롤러에서만 사용하는데 모델 패키지 보다 컨트롤러 패키지가 더 잘 어울리지 않을까요 ? 
Dto의 역할과 개념에 대해서 공부해보면 좋을 것 같고, 이번 기회에 Dto vs 도메인(모델) 에 대해 공부해봐도 좋을 것 같아요
참고할만한 자료도 공유드려요
https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/
https://tecoble.techcourse.co.kr/post/2021-05-16-dto-vs-vo-vs-entity/

2024-07-04 17:32 UTC, Hongdonggeon commented on src/main/java/gift/Controller/AdminController.java
> +    public String addProduct(@ModelAttribute @Valid ProductDTO productDTO, BindingResult result,
BindingResult 를 쓰셨네요!  BindingResult를 선언하지 않고 `@Valid`에서 발생한 예외를 GlobalExceptionHandler에서 처리하는 방법도 있었을텐데 BindingResult를 사용한 방법이 궁금합니다!

2024-07-04 17:32 UTC, Hongdonggeon commented on src/main/java/gift/Controller/AdminController.java
> +                model.addAttribute("priceError", "가격은 숫자만 입력 가능합니다.");
가격에 대한 예외 메시지만 이곳에서 처리한 이유가 있을까요?

2024-07-04 17:32 UTC, Hongdonggeon commented on src/main/java/gift/Model/Product.java
> +                      String imageUrl) {
모델에서 검증은 안해도될까요?

2024-07-04 17:33 UTC, Hongdonggeon requested changes
보민님 안녕하세요  
미션 진행하느라 수고하셨습니다! 
기본 요구사항에 대해서는 잘 구현하셨어요 👍
지금은 요구사항이 작고 간단해서 괜찮지만, 서비스 계층을 추가해서 검증 로직을 작성하는 것도 좋을 것 같아요! 
그리고 간단한 코멘트들  남겨놓았습니다! 반영하면서 궁금한 것 있으시면 질문주세요!

2024-07-04 17:38 UTC, KBM05haruin30 commented on src/main/java/gift/Model/ProductDTO.java
> +public record ProductDTO(Long id,
넵! Product에서 ProductDTO로 복사하면서 지우는 것을 깜빡 잊어버린 것 같습니다. 바로 수정하였습니다!

2024-07-04 17:40 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/AdminController.java
> +    public String addProduct(@ModelAttribute @Valid ProductDTO productDTO, BindingResult result,
1단계 과제에서 힌트로 주신 스프링 프레임워크 문서를 봤더니 Controller부분에서 BindingResult를 사용하여 사용해야 되는 줄 알고 사용했습니다. BindingResult를 선언하지 않고 예외를 처리하는 방법을 찾아서 수정해보도록 하겠습니다!

2024-07-04 17:42 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/AdminController.java
> +                model.addAttribute("priceError", "가격은 숫자만 입력 가능합니다.");
validation annotation으로 처리하고 싶었습니다. 그래서 @Pattern을 이용해서 처리를 해볼까 생각했지만 @Patttern은 String만 가능하다고 하여 따로 예외 메시지를 처리했습니다. 저는 ProductDTO에서 long price로 사용하였는데 이것을 String price로 바꾸고 따로 long price로 변경을 해도 문제가 없는지 궁금합니다.

2024-07-04 17:49 UTC, KBM05haruin30 commented on src/main/java/gift/Model/Product.java
> +                      String imageUrl) {
모델은 비즈니스 로직만 집중하고 DTO에서 검증을 하는 것이라 생각하고 나눴었습니다. 하지만 검색해서 찾아보니 둘 다 사용하는 것이 좋다고 나와있는 것을 확인했습니다. 모델에서도 검증을 하도록 수정하겠습니다! 하지만 궁금한 점이 있습니다. DTO랑 엔티티 둘 다 검증을 넣게 되면 코드가 복잡해지는건 아닌지 궁금합니다.

2024-07-04 18:11 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/ProductConverter.java
> +    }
record 클래스 안에 메서드를 작성할 수 없는 줄 알았었습니다. ProductDTO 클래스 안에 만들어보겠습니다!

2024-07-04 18:17 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/AdminController.java
> +                model.addAttribute("priceError", "가격은 숫자만 입력 가능합니다.");
위에서 record에 메서드를 추가할 수 있다는 것을 깨달았습니다. ProductDTO의 price를 String으로 변경한 후 @Pattern으로 숫자만 입력 받게 지정해주면 가격에 대한 예외 메시지만 따로 처리하지 않아도 될 것 같다는 생각이 들어서 그렇게 수정해보려고 합니다!

2024-07-04 18:33 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/AdminController.java
> +                model.addAttribute("priceError", "가격은 숫자만 입력 가능합니다.");
수정 완료 했습니다!

2024-07-04 19:06 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/AdminController.java
> +    public String addProduct(@ModelAttribute @Valid ProductDTO productDTO, BindingResult result,
그리고 저는 오류가 발생하면 현재 머무르고 있는 페이지에 값이 입력된 채로 가게 했습니다. AdminController에서 BindingResult를 선언하지 않고 예외를 GlobalExceptionHandler에서 처리하는 방법이 있다고 말씀해주셨는데 그럼 GlobalExceptionHandler에서도 BindingReuslt를 선언하지 않아도 되는 것인지 궁금합니다.

2024-07-04 19:08 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/ProductConverter.java
> +    }
수정 완료했습니다!

2024-07-05 01:38 UTC, KBM05haruin30 commented on src/main/java/gift/Model/ProductDTO.java
> +public record ProductDTO(Long id,
자료 공유 감사합니다! 읽어보니 도움이 된 것 같습니다. 그리고 DTO-Entity간의 변환 위치는 Service 레이어에서 하는 것이 타당한 것 같습니다. 바로 위의 코드 수정은 ProductDTO에 DTO와 Entity간의 변환 로직이 추가되어 있으므로 이를 제거하고 전송에만 더 집중할 수 있도록 만들고, Service 계층을 만들어야 할 것 같습니다. 추가로 DTO를 컨트롤러 패키지가 아닌 dto 패키지를 새로 만들어서 거기에 넣어도 되는지 궁금합니다.

2024-07-05 02:39 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/AdminController.java
> +    public String addProduct(@ModelAttribute @Valid ProductDTO productDTO, BindingResult result,
구글링을 통해 찾아보고 있는데 감이 안잡힙니다..

2024-07-07 05:08 UTC, Hongdonggeon commented on src/main/java/gift/Model/ProductDTO.java
> +public record ProductDTO(Long id,
여러 패키지에서 공유해야 하는 상황이면 보민님이 말하신 것 처럼 별도의 dto 패키지를 만들어서 넣어두는 것도 좋다고 생각하고요!
만약 서비스 계층까지만 사용되면, 해당 서비스 계층에 dto 패키지를 만드는 방법도 있다고 들었습니다!
고민해보시고 결정하시면 될 것 같습니다!

2024-07-07 07:14 UTC, Hongdonggeon commented on src/main/java/gift/Model/Product.java
> +                      String imageUrl) {
모델에 검증로직이 있다고 코드가 복잡해진다고 생각하지 않습니다!

2024-07-07 07:15 UTC, Hongdonggeon approved these changes
안녕하세요 보민님! 
미션 진행하느라 리뷰 반영하느라 수고많으셨습니다! 
열심히 학습하신 모습도 보기 좋습니다 
다음 미션도 화이팅입니다!

2024-07-07 07:21 UTC, Hongdonggeon commented on src/main/java/gift/Controller/AdminController.java
> +    public String addProduct(@ModelAttribute @Valid ProductDTO productDTO, BindingResult result,
GlobalExcetpionHandler에서는 BindingResult를 선언해야합니다! 
@Valid에서 예외가 발생하면 MethodArgumentNotValidException 클래스로 발생하게 될거예요
GlobalExceptionHandler에서 저 예외 클래스에 대해서 예외를 공통으로 처리하는 방법을 추천드린겁니다!!

```    
    @ExceptionHandler({MethodArgumentNotValidException.class})
    public ResponseEntity<ErrorResponse> handleInvalidRequest(final BindingResult bindingResult) {
        final List<FieldError> fieldErrors = bindingResult.getFieldErrors();
           ~~~~~
        return ResponseEntity.badRequest().body();
    }
```

2024-07-07 07:21 UTC, merged