경북대 BE_김민주 2주차 과제 (0단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #125
Opened 2024-07-02 15:51 UTC by minju26

리뷰 해주신 내용을 바탕으로 이전 과제의 코드를 수정해보았습니다.

1. 이전 과제 코드를 복사해오는 과정에서 local 저장소의 remote 저장소를 변경하여 pull 해오는 방식 사용했습니다.
2. file encoding 설정을 변경했습니다.
   - IntelliJ 설정 변경했을 땐, 깃허브에 업로드한 파일 내용은 계속해서 한글이 깨지는 이슈가 있었습니다.
   - .gitattribute 파일을 추가하여 한글 깨짐 문제를 해결할 수 있었습니다.
3. 초기 아이템 생성에 대하여, Service 클래스에서 하던 것을 data.sql (spring.sql.init.data-locations) 사용하는 것으로 수정했습니다. 
5. SimpleJdbcTemplate을 사용하려고 했으나, 최근엔 비슷하지만 NamedParameterJdbcTemplate 사용 경향이 있다고 하여 NamedParameterJdbcTemplate을 사용해서 쿼리를 수정했습니다.

뷰와 관련된 부분은 여유가 없어서 아직 리뷰해주신 내용을 반영하지 못했는데, 차근차근 수정해보겠습니다!

2024-07-03 17:09 UTC, gongdongho12 requested changes
현재는 백엔드 파트이다 보니 프론트는 기능 구현에만 초점을 둬도 괜찮기는 해요
다만 백엔드 부분에 시간을 다 쏟았을 때 기준에만 수정해 나가는 식으로요

고생많으셨습니다 💯

2024-07-03 17:09 UTC, gongdongho12 commented on src/main/java/gift/ProductDao.java
> +}
Dao인데 @Repository 를 달고 있네요
ProductRepository 같은 명칭은 어떠실까요?
DAO는 데이터 엑세스 오브젝트로 엔티티의 역할입니다

2024-07-03 17:09 UTC, gongdongho12 commented on src/main/java/gift/ProductManageController.java
> +    }
페이지 같은 Path들을 Path.java 같은곳에 static 상수로 선언해서 참조하면

"redirect:/api/manage/products" 이런 부분도 redirect 메서드 만들어서
`redirect(MANAGE_PRODUCTS)` 형식으로 쓸 수 있지 않을까요?

2024-07-03 17:09 UTC, gongdongho12 commented on src/main/java/gift/ProductService.java
> +    private static final String DELETE_SUCCESS_MSG = "상품 삭제 성공";
에러 메시지는 Path처럼 한곳에서 관리하는게 추후 에러 메시지가 많아졌을 때 관리가 용이하지 않을까요?

2024-07-03 17:09 UTC, gongdongho12 commented on src/main/resources/application.properties
> +# schema.sql, data.sql 위치 설정
UTF-8 👍🏼

2024-07-03 17:09 UTC, gongdongho12 commented on src/main/resources/db/data.sql
> +INSERT INTO products VALUES (8146027, '아이스 카페 아메리카노 T', 4500, 'https://st.kakaocdn.net/product/gift/product/20231010111814_9a667f9eccc943648797925498bdd8a3.jpg')
기능을 이해하고 바꿔보니 깔끔해지죠?

2024-07-03 17:09 UTC, gongdongho12 commented on src/main/java/gift/ProductDao.java
> +    }
NamedParameterJdbcTemplate 가 깔끔하긴 하죠 👍🏼

2024-07-04 01:15 UTC, minju26 commented on src/main/java/gift/ProductDao.java
> +}
Dao와 Repository의 개념을 정확하게 구분해서 생각하지 못했던 것 같아요..! 반영하겠습니다!!

2024-07-04 01:16 UTC, minju26 commented on src/main/java/gift/ProductManageController.java
> +    }
오호! 한번 해보겠습니다!

2024-07-04 16:36 UTC, gongdongho12 approved these changes

2024-07-04 16:36 UTC, merged