충남대 BE_이택_2주차 과제(step1)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #129
Opened 2024-07-02 18:38 UTC by LeeTaek2T

**궁금한점**
1. commit은 얼마나 해야할까요?(기능을 구현하면 commit  or 함수 한 개를 구현하면 commit 등) commit을 얼마나 해줘야하는지 아직 잘 모르겠습니다.

2024-07-03 05:24 UTC, ksy90101 requested changes
1단계 고생많으셧어요~
간단한 피드백을 남겼으니 피드백을 간단히 해결해보면 좋을거 같습니다.
궁금한게 있다면 언제든 DM주세요!

2024-07-03 05:24 UTC, ksy90101 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation' // Bean Validation 의존성 추가
주석은 제거해도 될거 같습니다~

2024-07-03 05:24 UTC, ksy90101 commented on src/main/java/gift/Product.java
> +  })
👍  기본 validate 어노테이션을 잘 쓰셨네요!

2024-07-03 05:24 UTC, ksy90101 commented on src/main/java/gift/ProductAdminController.java
> +    return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(message);
ExceptionHandler를 한번 따로 파일을 분리해서 책임 분리를 해보면 어떨까요?

2024-07-03 05:24 UTC, ksy90101 commented on src/main/java/gift/ProductAdminController.java
> +  public String updateProduct(@PathVariable Long id,@Valid @ModelAttribute Product product) throws MethodArgumentNotValidException {
throws를 해야 하는 이유가 있나요?
checkedException과 unCheckedException을 한번 학습해보시면 좋을거 같습니다!

2024-07-03 05:24 UTC, ksy90101 commented on src/test/java/gift/ProductControllerTest.java
>  @SpringJUnitConfig(classes = ProductDao.class)
한번 하는김에 Validate를 한 코드도 한번 테스트 코드를 작성해보면 어떨까요?
400에러가 발생하는 케이스를 테스트 코드 추가해보면 좋을거 같아요!

2024-07-03 06:12 UTC, ksy90101 commented
>commit은 얼마나 해야할까요?(기능을 구현하면 commit or 함수 한 개를 구현하면 commit 등) commit을 얼마나 해줘야하는지 아직 잘 모르겠습니다.
개인적으로 본인의 방식대로 하면 좋은데요. 둘다 정답이 있진 않습니다. 최대한 작은 단위가 좋으니 함수 한개 구현정도로 하면 어떨까 생각이 들어요! 저도 함수 하나 단위로 하는 편입니다. 왜냐하면 함수 단위가 가장 작은 기능의 단위라고 생각을 하고 있어서요.

> 제가 1주차 과제의 코드를 가져오기 위해, 현재 저장소의 upstream으로 1주차 원격 저장소를 두었습니다. 그리고 git pull을 하여 코드를 가져왔는데 이런 방식을 사용하니 1주차에 했던 commit 내용이 2주차에도 풀리퀘스트에 들어가있는 것을 알게 되었습니다. 이런 방식을 사용해도 괜찮을까요? 아니면 다른 좋은 방식이 있을까요?

네 괜찮습니다 ㅎㅎ 원래는 커밋이 보이면 안되는데, 작업하실때 leetae2t 브랜치에서 시작하시는걸 추천드려요. 그럼 안보일꺼에요!

2024-07-03 12:36 UTC, LeeTaek2T commented
**코드 리뷰 시 원하는 점**
이번 카테캠을 하며 많은 것을 경험하고 싶습니다. 
리뷰를 해주실 때 이런 방법도 있다는 키워드 같은 것을 많이 알려주시면 감사하겠습니다. 
따로 공부하여 적용해보겠습니다!

2024-07-04 00:54 UTC, ksy90101 approved these changes
고생많으셨어요!
리뷰를 남겼지만, 심화적인 내용이 좀 있어서 한번 보시고 적용을 선택해보셔도 될거 같습니다~
언제든 궁금한게 있다면 DM주세요!

2024-07-04 00:54 UTC, ksy90101 commented on src/main/java/gift/DTO/ProductDTO.java
> +  @Size(min=1, max=15,message = "가능한 글자 수는 1~15입니다.")
Null이 들어오면 어떻게 될까요?

2024-07-04 00:54 UTC, ksy90101 commented on src/main/java/gift/Controller/ProductController.java
>    }
좀더 심화적인 개념으로 이것도 ExceptionHandler를 해보시면 좋을거 같습니다~

2024-07-04 00:54 UTC, ksy90101 commented on src/main/java/gift/GlobalExceptionHandler.java
> +  @ExceptionHandler(MethodArgumentNotValidException.class)
👍

2024-07-04 00:54 UTC, ksy90101 commented on src/test/java/gift/ProductDTOControllerTest.java
> +  public void testDeleteProduct() {
1. DisplayName을 통해 테스트 이름을 지어보면 어떨까요?
2. 한번 FIRST 규칙을 공부해보시면 어떨까요? 
[참고링크](https://rutgo-letsgo.tistory.com/entry/FIRST-%EC%9B%90%EC%B9%99?category=967445)

여기서 FIRST 원칙을 위반한것처럼 보이는게 있습니다.
혹시 어떤건지 모르겠으면 DM주세요!

2024-07-04 00:54 UTC, ksy90101 commented
> 코드 리뷰 시 원하는 점
이번 카테캠을 하며 많은 것을 경험하고 싶습니다.
리뷰를 해주실 때 이런 방법도 있다는 키워드 같은 것을 많이 알려주시면 감사하겠습니다.
따로 공부하여 적용해보겠습니다!

네네!! 지금도 충분히 잘하고 계십니다! 훨씬 심화적인 내용들을 많이 다루고 계신대요~ 필요한 부분이 있다면 리뷰에 남길게요!
홧팅입니다!

2024-07-04 00:54 UTC, merged