충남대 BE_김민지_2주차 과제(step1)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #131
Opened 2024-07-02 19:26 UTC by alsswl

멘토링 때 말씀해주신대로 @controllerAdvice를 사용해보았습니다.
그리고 @Vaild를 사용하는 방식을 사용해 보았는데 responseEntity로 객체를 반환한 후에 이 리턴값을 어디에서 받는 건지 감이 잘 오지 않습니다. 원래는 String형식으로 html파일명을 리턴해서 화면은 전환하는 식으로 구현했었는데, Vaild를 사용하니까 엔티티를 리턴해야해서 화면을 어떤 것을 사용해서 띄워야하는지 잘 모르겠습니다.

2024-07-05 01:17 UTC, Hyeon9mak requested changes
안녕하세요 민지님! 1단계 과제 잘 진행해주셨습니다. 리뷰가 살짝 늦었네요 🙏 

>  responseEntity로 객체를 반환한 후에 이 리턴값을 어디에서 받는 건지 감이 잘 오지 않습니다.

요 고민과 관련된 코멘트 남겨드렸으니 확인해주세요.
그 외에도 간단한 코멘트 몇 가지 남겼으니 확인해주세요!

2024-07-05 01:17 UTC, Hyeon9mak commented on src/main/java/gift/controller/MenuController.java
> +        menuService.save(request.name(), request.price(), request.imageUrl());
페이지 응답을 담당하는 handler 와 response entity 응답을 담당하는 handler 를 명시적으로 분리해보는 것은 어떨까요?
민지님께서 고민하고 계시는 문제점을 하나의 handler 에서 해결하고자 하니까 너무 어렵게 생각되는거 같아요 😉

2024-07-05 01:17 UTC, Hyeon9mak commented on src/main/java/gift/domain/MenuRequest.java
> +        @Pattern(regexp = "^((?!카카오).)*$", message = "'카카오'가 포함된 상품명은 담당 MD와 협의해주세요")
현재 controller, repository 등 계층을 나누었는데, MenuRequest 가 홀로 모든 계층을 넘나들고 있어요.
"계층을 나누었다." == "계층별 유지보수 범위를 전파시키고 싶지 않다." 라고 볼 수 있는데,
http 요청을 전달하는 객체와, 우리의 비즈니스 로직을 수행할 객체를 분리해보는 건 어떨까요?

2024-07-05 01:17 UTC, Hyeon9mak commented on src/main/java/gift/exception/NoSuchElementExceptionHandler.java
> +@ControllerAdvice
`@ControllerAdvice` ` @RestControllerAdvice` 의 차이는 무엇일까요?

2024-07-05 01:17 UTC, Hyeon9mak commented on src/main/java/gift/exception/NoSuchElementExceptionHandler.java
> +        return ResponseEntity.badRequest().body(errors);
`MethodArgumentNotValidException` 외에도 여러가지 예외가 다양하게 발생할 수 있는데,
그것들은 모두 어떻게 처리해줄 수 있을까요?
예외마다 모든 handlr 를 만들긴 귀찮을텐데...

(hint: exception inheritence)

2024-07-05 01:19 UTC, Hyeon9mak commented on src/main/resources/db/schema.sql
> +                       imageUrl VARCHAR(2048)
필수값 여부로 NOT NULL 설정을 추가해주면 더욱 좋겠네요 😄

2024-07-06 13:06 UTC, alsswl commented on src/main/java/gift/controller/MenuController.java
> +        menuService.save(request.name(), request.price(), request.imageUrl());
제가 아직 분리에 대해 잘 몰라서 현재 페이지 응답을 하는 부분은 MenuController의 save메서드에, response entity를 담당하는 부분은 NoSuchElementException에 구현되어있어서 분리되어있다고 생각되는데 혹시 BindingResult부분 자체를 없애야 명확하게 분리되는건지 궁금합니다.

2024-07-06 14:29 UTC, Hyeon9mak commented on src/main/java/gift/controller/MenuController.java
> +        menuService.save(request.name(), request.price(), request.imageUrl());
현재 `save` 메서드가 서비스 로직과 페이지 응답 2가지 역할을 수행하고 있기 때문에 남겨드린 코멘트였어요!
`save` 메서드는 서비스 로직 수행 후 ReponseEntity 를 응답하고, 페이지를 응답하는 메서드(핸들러)를 명시적으로 만들어주시면 됩니다~

2024-07-06 18:00 UTC, alsswl commented on src/main/java/gift/domain/MenuRequest.java
> +        @Pattern(regexp = "^((?!카카오).)*$", message = "'카카오'가 포함된 상품명은 담당 MD와 협의해주세요")
넵 이 부분은 다른 사람들의 PR을 참고해보았습니다.
MenuController -> MenuService로 요청이 갈 때에는 MenuRequest를 사용하였고, Service에서 Repository로 갈 때에는 menu엔티티로 변환하였습니다.
또한 Repository에서 controller으로 데이터가 이동할 때에는 menu엔티티에서 menuResponse를 반환하였습니다.

2024-07-06 18:03 UTC, alsswl commented on src/main/java/gift/exception/NoSuchElementExceptionHandler.java
> +@ControllerAdvice
ControllerAdvice는 주로 view를 반환할 때 쓰이고, RestControllerAdvice은 주로 JSON형태로 반환할 때 쓰인다고 합니다.
제 코드에서 RestControllerAdvice를 썼음에도 오류가 나지 않았던 이유를 찾아봤는데 ResponseEntity로 반환하는 과정에서 자동으로 JSON으로 변환된다고 하였습니다!
하지만 제 코드의 가독성을 위해서는 RestControllerAdvice를 사용하는 것이 좋다고 생각되어 이 부분은 수정하였습니다!

2024-07-06 18:05 UTC, alsswl commented on src/main/java/gift/exception/NoSuchElementExceptionHandler.java
> +        return ResponseEntity.badRequest().body(errors);
해당 에러 말고도 다른 에러도 처리하기 위해서 EtcExcetpion 클래스를 만들었고 이 안에서 Exception.class를 사용하여 나머지 에러도 처리하도록 하였습니다! 혹시 제가 의도하신대로 구현한 것이 아니라면 피드백 부탁드립니다!

2024-07-06 18:06 UTC, alsswl commented on src/main/resources/db/schema.sql
> +                       imageUrl VARCHAR(2048)
네 추가하였습니다!

2024-07-07 02:29 UTC, Hyeon9mak approved these changes
안녕하세요 민지님,

코드 변경사항이 현재 branch 에 push 되지 않은 것 같은데요 😱 
이번에는 미션 진행을 위해 approve 하지만,
다음 단계부터는 진행중인 단계 PR 에 수정사항, commit 을 push 해주셔야합니다.

git 을 다루는 방법도 꼭 공부를 해보시면 좋겠네요 😄

2024-07-07 02:29 UTC, merged