경북대 BE_정성훈_2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #142
Opened 2024-07-03 05:01 UTC by zzoe2346

2024-07-04 14:43 UTC, sang5c requested changes
잘 작성해 주셨지만 요구사항을 만족하지 못해 Request Change를 드려요!  
어드민 페이지에서 유효성 검사 없이 허용되고 있으니 확인해주세요!  

> 강의자료와 검색을 이용해 응답 객체(ProblemDetail)를 만들어 보았는데, 부족한 부분이 없는지 궁금합니다.

부족한 부분은 없습니다 :)  
조금만 덧붙이자면,  
지금은 혼자 작성하는 코드이지만 회사 또는 팀 내 메시지에 대한 규칙을 잘 지키고, 클라이언트와 충분히 협의되었다면 어떤 메시지라도 충분히 좋은 메시지라고 생각합니다.

2024-07-04 14:43 UTC, sang5c commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +        problemDetail.setProperty("rejectedValue",e.getFieldError().getRejectedValue());
코드를 작성한 후 정렬하는 습관을 들여주세요!  
전체 코드에 대해 정렬을 수행해주세요.

```suggestion
        problemDetail.setProperty("rejectedValue", e.getFieldError().getRejectedValue());
```

2024-07-04 14:43 UTC, sang5c commented on src/main/java/gift/repository/ProductRepository.java
> +public class ProductRepository {
Repository가 등장했군요!  
Repository는 어떤 역할을 수행할까요?  
같이 접하게되는 Service는 없는데 Repository만 존재하는건 어떤 고민 배경이 있으셨나요? 🙂

2024-07-04 14:43 UTC, sang5c commented on src/main/java/gift/validation/ContainsOnlyAllowedSpecialCharacter.java
> +    String message() default "{gift.validation.ContainsOnlyAllowedSpecialCharacter.message}";
여기서 default 문자열은 언제 쓰이고 어떤 역할을하고 있을까요?

2024-07-04 14:43 UTC, sang5c commented on src/main/java/gift/dto/Product.java
> +    @ContainsOnlyAllowedSpecialCharacter(message = "상품 이름에 (, ), [, ], +, -, &, /, _ 와 같은 특수문자만 허용됩니다.")
Custom Validation 좋은 시도입니다 :)  

고민 한 번 해보셨으면 하는 포인트가 있어요!  
이미 존재하는 validation 방법은 사용할 수 없었을까요?  
직접 만들었을 땐 어떤 장점이 있을까요? 단점은 없을까요?

2024-07-04 14:43 UTC, sang5c commented on src/main/java/gift/validation/NotContainsKakao.java
> +    String message() default "{gift.validation.NotContainsKakao.message}";
이곳의 default는 어떤 의미를 나타내나요?

2024-07-04 14:43 UTC, sang5c commented on src/test/java/gift/controller/ProductNameValidateTest.java
> +    ObjectMapper objectMapper;
어떤 이유로 접근제어자가 private가 아니게 되었을까요?

2024-07-04 14:43 UTC, sang5c commented on src/test/java/gift/controller/ProductNameValidateTest.java
> +    @DisplayName("상품 이름이 15자 이하인 경우에 Created 상태반환")
테스트 작성 👍👍👍  

`경계값 테스트`라는 키워드에 대해 알아보셔도 좋을 것 같아요!  
아주 간단히 예를 들어 "15자 이하" 라는 조건일 때, 성공하는 케이스는 15자, 실패하는 케이스는 16자이기에 해당 값들에 초점을 맞춰 테스트하는 기법입니다.  
이 부분은 나중에 보셔도 좋습니다 :)

2024-07-04 14:43 UTC, sang5c commented on src/test/java/gift/controller/ProductNameValidateTest.java
> +                .andExpect(status().isCreated());
완전히 동일한 코드가 반복되는데 두 개로 나뉜 배경이 궁금합니다!

2024-07-04 14:43 UTC, sang5c commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +                .collect(Collectors.toList());
줄여서 작성 가능합니다.  

```suggestion
                .toList();
```

2024-07-04 14:43 UTC, sang5c commented on src/main/java/gift/controller/ProductRestController.java
>          return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
501 에러는 어떤 의미이고, 어떤 경우에 발생하나요?

2024-07-05 01:37 UTC, zzoe2346 commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +        problemDetail.setProperty("rejectedValue",e.getFieldError().getRejectedValue());
네 유의하겠습니다!

2024-07-05 01:59 UTC, zzoe2346 commented on src/main/java/gift/controller/ProductRestController.java
>          return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
> 출처: https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html
The recipient of the entity MUST NOT ignore any Content-* (e.g. Content-Range) headers that it does **not understand or implement** and **MUST return a 501 (Not Implemented) response** in such cases.

문서를 찾아보았는데 _**수신자가 이해를 못하거나 해당 기능이 구현이 안되어있을때**_ 반환하는 에러였습니다. 
현재 제 코드에서는 이해를 못한것도 아니고, 구현이 안된것도 아니니 부적절한 에러발생입니다!

맨 밑의 `return`까지 오는거는 서버에서 상품 수정, 상품 생성이 모두 실패한것이니 `INTERNAL_SERVER_ERROR(500)` 가 적절하다고 판단해 이걸로 리팩토링 진행하였습니다.

2024-07-05 02:00 UTC, zzoe2346 commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +                .collect(Collectors.toList());
감사합니다! 반영하겠습니다.

2024-07-05 02:10 UTC, zzoe2346 commented on src/test/java/gift/controller/ProductNameValidateTest.java
> +                .andExpect(status().isCreated());
이 당시 **오직 상품이름이 15자 이하일때 성공하는지**와 **오직 상품이름에 허용된 특수문자가 있을때 성공하는지**에 대해 따로 테스트 하고자 이렇게  만들었습니다.

생각해보니, 어차피 목적은 통과하는 값을 테스트하는건데 굳이 저렇게 중복된 코드를 사용하지말고 한 `@ParameterizedTest`의 `@ValueSource `에 중복된 테스트 코드에 들어가는 테스트값을 통합해 넣고 테스트 했으면 어땠을까 하는 생각이 듭니다. 테스트를 실행해보면 결과창에 각 값의 가/부 도 보여주니 뭐가 틀린건지도 확인 가능합니다.

2024-07-05 02:18 UTC, zzoe2346 commented on src/test/java/gift/controller/ProductNameValidateTest.java
> +    ObjectMapper objectMapper;
`ProductRepository productDB;`와 `ObjectMapper objectMapper;`에 접근제어가가 없는걸 말씀하시는걸로 이해하고 말씀드리겠습니다. 

테스트 코드 본문을 작성하는데 정신이 팔려 접근제어자까지는 신경 못 쓴거 같습니다. 테스트 코드가 발전할수록 이런 `private`가 없으면 다른 테스트코드에서 이를 사용할 수도있으니 앞으로 테스트 코드 작성할때는 신경써서 접근제어자를 작성하겠습니다.

2024-07-05 02:29 UTC, zzoe2346 commented on src/main/java/gift/dto/Product.java
> +    @ContainsOnlyAllowedSpecialCharacter(message = "상품 이름에 (, ), [, ], +, -, &, /, _ 와 같은 특수문자만 허용됩니다.")
`@Pattern`에 정규표현식을 이용해서 특정 단어, 문자가 들어가는 유효성 검사하는 방법이 있는걸 확인하였습니다.
`@Pattern`으로 어떻게 구현할지 공부해보겠습니다.
(Custom Validation을 만들기 전에 이런게 있는건 확인하였지만, 이번에 한번 애너테이션을 만들어보고 싶어 이렇게 진행해보았습니다)

**장점**
- java코드로 예외처리를 하니 정규표현식을 몰라도 됨
- 애너테이션의 명칭이 명확
- 좀더 정교한 예외처리가 가능

**단점**
- 동료 개발자와 협업하는거라면 만든 사람이 동료에게 직접설명 혹은 주석을 달거나, 동료 개발자가 직접 애너테이션을 분석해봐야하는 단점이 존재할거 같습니다.
- `@Pattern`같이 그냥 정규표현식과 메시지만 넣으면 끝나는것을 `annotation`, `validator` 까지 만드니 기존의 애너테이션을 사용하는것보다 자원이 들어가는 편입니다.

2024-07-05 02:36 UTC, zzoe2346 commented on src/main/java/gift/repository/ProductRepository.java
> +public class ProductRepository {
## Repository으로 변경 배경
다른 쿠키즈들의 코드와 이후의 과제 그리고 스프링에대해 공부해보니 컨트롤러, 서비스, 레포지토리로 나누어 조립?조합하며 코딩하는게 개발+유지보수에서 유리할거 같다는 생각이들었습니다. 

Repository는 DTO역할을 한다고 보았습니다. 이제 진행될 과제부터는 H2 DBMS와 상호작용은 이 Repository에 맡겨보려합니다.
이번 1단계 이후에 Service를 추가해 리팩토링할 예정입니다! 

제가 현재 이해한게 Controller에서 요청을 받고 Controller가 Service를 가져와서 조합해 비즈니스 로직을 처리하고 Service에서는 필요한 Repositroy를 가져와서 로직을 처리한다고 이해하고있습니다.

2024-07-05 03:04 UTC, zzoe2346 commented on src/main/java/gift/validation/ContainsOnlyAllowedSpecialCharacter.java
> +    String message() default "{gift.validation.ContainsOnlyAllowedSpecialCharacter.message}";
`@NotContainsKakao(message = "상품 이름에 카카오가 포함된 문구는 담당 MD와 협의한 경우에만 사용 가능합니다.")`이게아니라 `@NotContainsKakao`처럼 message를 지정하지 않을시 `default`로 전달되는 메세지입니다. 

처음에는 `String message() default "상품 이름에 카카오가 포함된 문구는 담당 MD와 협의한 경우에만 사용 가능합니다.";` 이렇게 만들었었는데, 기본으로 제공되는 `@Size`에 메세지 값을 넣는것을 `custom annotation` 과 통일시키고 싶어서(더 깔끔해 보였습니다) 기존의 유효성 검증 애너테이션의 defalut 메세지를 따라해보았습니다.

2024-07-05 03:10 UTC, zzoe2346 commented on src/main/java/gift/validation/NotContainsKakao.java
> +    String message() default "{gift.validation.NotContainsKakao.message}";
message를 따로 지정하지 않을시 기본(default)로 전달되는 메세지 입니다.

2024-07-05 17:32 UTC, sang5c approved these changes
1단계 머지합니다 👍👍

2024-07-05 17:32 UTC, sang5c commented on src/main/java/gift/validation/ContainsOnlyAllowedSpecialCharacter.java
> +    String message() default "{gift.validation.ContainsOnlyAllowedSpecialCharacter.message}";
`@Size`의 디폴트 메시지를 cmd + b(윈도우는 ctrl + b)로 따라가보시면 application.properties에 작성된 내용을 발견하실거에요 :)  
저 자체로 어떤 의미를 갖는게 아닌, 미리 정의된 값을 반환하는 형태입니다.
```
// ValidationMessages.properties
jakarta.validation.constraints.Size.message = size must be between {min} and {max}
```

2024-07-05 17:32 UTC, sang5c commented on src/main/java/gift/dto/Product.java
> +    @ContainsOnlyAllowedSpecialCharacter(message = "상품 이름에 (, ), [, ], +, -, &, /, _ 와 같은 특수문자만 허용됩니다.")
좋은 시도입니다~!

2024-07-05 17:32 UTC, sang5c commented on src/main/java/gift/repository/ProductRepository.java
> +public class ProductRepository {
💪💪 Repository와 DTO는 다른 개념입니다.  
DTO가 무엇인지, Repository가 무엇인지 정의해보는 것부터 시작해보시길 추천드려요.

2024-07-05 17:32 UTC, merged