강원대 BE_오승환 2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #147
Opened 2024-07-03 05:39 UTC by humpose

유효성 및 예외 처리 기능을 추가해보았습니다.
예외 발생 시 반환값이 달라서 굳이 @ExceptionHandler를 사용하지 않고 따로 메서드에서 예외를 처리하였습니다.

2024-07-03 13:46 UTC, pci2676 requested changes
리뷰를 남겨두었으니 확인 후 다시 PR 요청 부탁드립니다.

2024-07-03 13:46 UTC, pci2676 commented on src/main/java/gift/ProductValidator.java
> +package gift;
모든 클래스가 gift 바로 아래에 위치한 것 같습니다.

역할에 맞게 적절한 패키지로 분리해주세요. 🤔

2024-07-03 13:46 UTC, pci2676 commented on src/main/java/gift/ProductValidator.java
> +    }
Product의 name인 String에게 이 역할을 부여해 보면 좋을것 같습니다.

값 객체라는 개념을 활용하여 Product의 name을 값 객체로 만들고 테스트 코드를 함께 추가해주세요.

2024-07-03 13:46 UTC, pci2676 commented on src/main/java/gift/ProductValidator.java
> +    }
이렇게 생성한 validate는 Product를 생성할때마다 함께 항상 호출해줘야하는 문제가 있을것 같습니다.

2024-07-03 13:46 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    public String addProduct(@ModelAttribute Product product, Model model) {
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/10#discussion_r1660055834

2024-07-03 13:46 UTC, pci2676 commented on src/main/java/gift/ProductService.java
> +        ProductValidator.validate(product);
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/10#discussion_r1659805871

2024-07-03 13:46 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +            model.addAttribute("product", product);
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/10#discussion_r1660174672

2024-07-03 13:46 UTC, pci2676 commented on README.md
> +조건에 따른 유효성 검사를 수행하는 클래스
유효성 검증을 할 수 있는 다른 방법을 고민해보셨을까요?

2024-07-03 13:46 UTC, pci2676 commented on src/main/java/gift/ProductValidator.java
> +        }
이전 단계부터 이어져 오는 프로그래밍 수칙은 계속해서 지켜주셔야 합니다~!

depth를 줄일 수 있도록 개선해주세요!

2024-07-03 13:46 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +        }
> 예외 발생 시 반환값이 달라서 굳이 `@ExceptionHandler`를 사용하지 않고 따로 메서드에서 예외를 처리하였습니다.

안타깝게도 예외 발생 시 반환값이 다른 경우는 흔한 경우입니다.

따라서 이러한 경우에도 ExceptionHandler를 이용하여 에러를 핸들링 할 수 있도록 해주시는 것이 좋을것 같습니다.

custom exception을 만들어서 개선해주시면 좋을것 같습니다.

2024-07-04 04:00 UTC, humpose commented on src/main/java/gift/ProductValidator.java
> +        }
네 지적 감사합니다

2024-07-04 05:55 UTC, humpose commented on src/main/java/gift/ProductController.java
> +        }
수정하겠습니다.

2024-07-04 05:55 UTC, humpose commented on README.md
> +조건에 따른 유효성 검사를 수행하는 클래스
조언해주신 것처럼 product 객체에서 검증해보겠습니다

2024-07-04 05:55 UTC, humpose commented on src/main/java/gift/ProductValidator.java
> +package gift;
네. 수정하겠습니다.

2024-07-04 06:01 UTC, humpose commented on src/main/java/gift/ProductValidator.java
> +    }
예 알겠습니다.

2024-07-04 06:04 UTC, humpose commented on src/main/java/gift/ProductValidator.java
> +    }
네. 수정하겠습니다

2024-07-04 06:11 UTC, humpose commented
리뷰어님. 제가 많이 고민해보았는데, 도저히 왜 @ExceptionHandler가 작동하지 않는 이유를 모르겠습니다. 
console에서
jakarta.validation.ValidationException: 제품 이름은 최대 15자까지 입력 가능합니다.
라는 문구가 출력된 것으로 보아 예외는 잘 던져진 것 같은데, 왜 그런건지 도저히 모르겠습니다....

2024-07-04 07:52 UTC, humpose commented on src/main/java/gift/ProductController.java
> +    public String addProduct(@ModelAttribute Product product, Model model) {
어떻게 이걸 구현해야 할지 잘 모르겠습니다. ProductDTO클래스를 하나 새로 만들어서 기능을 분리해보려고 했는데 코드가 너무 복잡해지고 ProductDTO객체를 Product로 계속 바꿔서 저장해야 했습니다. 혹시 제가 잘못 이해한 것이라면 좀 더 힌트를 주실 수 있으신가요?

2024-07-04 15:00 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    public String addProduct(@ModelAttribute Product product, Model model) {
엇 맞습니다. 정확히 제 의도를 이해해주셨습니다!!

ProductDto를 따로 생성하시는게 좋습니다. 그렇지 않으면 단일책임원칙을 위반합니다.

계속해서 변경하는것은 불가피한 과정입니다~

2024-07-04 15:06 UTC, pci2676 approved these changes
다음 단계를 진행하며 이번 단계에 개선하지 못한 부분을 함께 개선해주세요~

2024-07-04 15:06 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
>          productRepository.add(product);
productRepository를 autowired를 이용하여 bean 주입을 해주셨는데 의도하신 부분일까요?

2024-07-04 15:06 UTC, pci2676 commented on src/main/java/gift/controller/ProductController.java
> +    public String addProduct(@Valid @ModelAttribute Product product, BindingResult bindingResult, Model model) {
답변을 남겨두었으니 다음단계에서 개선해주세요~

2024-07-04 15:06 UTC, pci2676 commented on src/main/java/gift/model/Product.java
>      private String name;
값 객체의 개념은 아래 키워드로 구글에 검색하면 많이 나오니 참고하여 개선해주세요.

`자바 값 객체`

2024-07-04 15:06 UTC, merged