전남대 BE_임강범 2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #149
Opened 2024-07-03 06:08 UTC by kangboom

## 과제 질문
1. 예외를 탐지하는 로직을 ExceptionService의 findNameException() 메서드 안에 작성하였습니다. 여기서 name 인풋에 관한 예외 (1. 길이 제한, 2. 특수 문자 제한, 3. "카카오" 글자 포함 여부)를 기능별로 각각 메서드를 만들기에는 너무 세부적인 것 같아 오히려 관리하기 힘들 것 같다고 생각했습니다. 그래서 한 메서드에서 모두 처리되도록 작성했는데, 메서드는 1개에 1개의 기능만 수행하도록 작성하는 게 좋다는 말을 떠올리게 되었습니다. 각각의 예외를 위해 1, 2, 3 별로 메서드를 따로 만드는 것이 좋을지, 아니면 현재처럼 한 메서드에서 처리하는 것이 더 좋은 선택일지 궁금합니다.

2024-07-03 14:19 UTC, soominsohn requested changes
안녕하세요 강범님! 리뷰어 앤지입니다. 이번 미션도 잘 해주셨네요 :thumb
작성해주신 코드에 대한 질문과 리뷰 남겼는데요,
특히 ExceptionService에 대한 리뷰는 꼭 반영해주시면 감사하겠습니다.
___
질문에 대한 답변
### 1
장, 단점을 모두 잘 적어주셨네요! 고민의 흔적이 잘 보입니다. 👍 
저도 강범님이 고민한 것처럼 메서드는 1개에 1개의 기능만 수행하도록 분리하는게 좋다고 생각합니다. 
분리하게 되면 메서드별로 검증 로직이 무엇을 하는지 명확히 할 수 있어 가독성이 좋아지고, 개별 검증 로직이 변경(예: 최대 자릿수가 15 -> 14로 변경)될 때 해당 메서드만 수정하면 됩니다.

2024-07-03 14:19 UTC, soominsohn commented on src/test/java/gift/ExceptionServiceTest.java
> +    }
예외를 throw하지 않는걸 테스트하고 싶으시군요! 
테스트에 junit을 사용하셨는데, 다음과 같은 함수를 사용하시면 예외가 발생하지 않는 상황을 테스트해보실 수 있습니다.
```suggestion
    @DisplayName("정상 동작 테스트")
    @Test
    public void testFindNameException_ValidName() {
        assertDoesNotThrow(() -> {
            exceptionService.findNameException(validName);
        });
    }
```

2024-07-03 14:19 UTC, soominsohn commented on src/test/java/gift/ExceptionServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertThrows;
이번 미션에서 테스트를 추가해 주셨군요! 아주 잘하셨습니다 👍 
자바 스프링을 사용하는 환경에서 많이 사용하는 테스트 라이브러리는 JUnit, AssertJ가 있는데요, 이번 미션에서는 JUnit을 사용해 주셨군요.
AssertJ에 대해서도 학습해보면 좋습니다.
참고: https://xxeol.tistory.com/12

2024-07-03 14:19 UTC, soominsohn commented on src/main/java/gift/controller/ViewController.java
> +    }
View까지 신경써주셨네요 ㅎㅎ 잘봤습니다 👍 
Response Status로 400 Bad Request를 잘 사용하셨군요! 다양한 Status중 400을 사용하신 이유가 궁금합니다 😄 
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/83059234/74d57cc5-6e1a-4f8b-9b14-6d5296798282)

2024-07-03 14:19 UTC, soominsohn commented on src/main/java/gift/ExceptionService.java
> +}
안녕하세요, 1단계 미션인 유효성 검증을 ExceptionService에서 수행하셨네요. 
아래 3가지 질문에 대해 학습해보시고, 개선해주시면 감사하겠습니다. 
보시고 질문이 있으시면 편하게 DM주세요 😄 

1. Service 레이어가 하는일이 무엇이라고 생각하시나요? @Service 어노테이션, Service 레이어에 대해 학습해보고 적절히 사용했는지 고민해보아요.

2. 또 ExceptionSerivce에서 유효성 검증이 이루어지고 있는데, 유효성 검증을 할 수 있는 곳은 여러 곳들이 있어요. 어디서 어떤 검증 방법을 할 수 있을까요? `Hint: dto, domain`

3. name에 대한 검증이 필요한 모든 곳에서 모두 ExceptionService의 findNameException 메서드를 호출해 코드의 중복이 발생하고 있습니다. 어떻게 하면 아래와 같은 호출을 하지않고 유효성 검증을 할 수 있을까요? `Hint: Product 객체` `exceptionService.findNameException(productDto.getName());`

2024-07-03 14:19 UTC, soominsohn commented on src/main/java/gift/NameException.java
> +}
RuntimeException을 상속받은 NameException을 만드셨군요 👍 
다음 글을 읽고 Java의 Exception에 대해 학습해보면 좋습니다 😄 

https://velog.io/@chlee4858/Java-Exception-%EB%B6%84%EB%A5%98-%EB%B0%8F-%EC%B2%98%EB%A6%AC%EB%B0%A9%EB%B2%95

2024-07-03 14:19 UTC, soominsohn commented on src/main/java/gift/controller/ProductController.java
> +        return new ResponseEntity<>(productRepository.findAll(), HttpStatus.OK);
이번 미션에서 ResponseEntity를 추가하셨군요!
ResponseEntity는 어떤 특징이 있을까요?

2024-07-03 14:19 UTC, soominsohn commented on src/main/java/gift/controller/ProductController.java
> +        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
ExceptionHandler 활용 👍 
Spring에서 예외를 처리하는 다른 어노테이션으로는 무엇이 있을까요?
지금은 에러 응답 내용으로 string만 보내고 있지만, 다른 정보가 필요할 수도 있고 응답 형식에 대한 정의가 필요할 수도 있습니다.
Spring의 ErrorResponse에 대해 학습해보시면 좋습니다 :)
https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-ann-rest-exceptions.html

2024-07-05 03:52 UTC, soominsohn approved these changes
안녕하세요 강범님!
질문 주셨던 내용 잘 반영해주셔서 고맙습니다.
수정해주신 코드에 대해 리뷰 달았는데요, 다음단계 진행하시면서 반영해주시길 바랍니다.
다음단계도 파이팅이에요 🦾

2024-07-05 03:52 UTC, soominsohn commented on src/main/java/gift/ProductService.java
> +    }
검증로직을 Product 객체의 메서드 안으로 옮기고, Service Layer에서 검증이 이루어지게 만들었네요. 👍 
그러나 Product의 검증을 `product.validate();`처럼 메서드를 호출하는게 아닌, Product의 생성자 안에서 호출해보면 어떨까요?
그렇게 되면 ProductService의 `create`, `update`메서드에서 매번 `product.validate();`을 중복으로 호출할 필요가 없을거에요. 코드에서 중복을 줄이는 것 또한 중요하답니다. 
질문해주셨던 내용 잘 반영해주신 것 같아 고맙습니다 💯

2024-07-05 03:52 UTC, soominsohn commented on src/main/java/gift/ProductService.java
> +        product.setImageUrl(productDto.getImageUrl());
지금 product의 settter method를 이용해 값을 업데이트 해주시고 있군요!
아래글을 읽고 setter를 지양해야 하는 이유와, 의미를 가진 메서드 이름을 사용해 업데이트 하도록 수정해볼까요?
https://colabear754.tistory.com/173

2024-07-05 03:52 UTC, soominsohn commented on src/main/java/gift/ProductService.java
> +    }
이미 생성자 주입으로 productReposiotry를 주입받고 있기 때문에 `@Autowired`를 중복으로 사용할 필요가 없어보입니다.
스프링의 의존성 주입(DI)에 대해 학습해보면 어떻게 수정해야할지 보일거에요.

2024-07-05 03:52 UTC, soominsohn commented on src/main/java/gift/Product.java
>      private Integer price;
price의 자료형으로 primitive type인 int형 대신 Wrapper type인 Integer를 사용하셨군요!
java의 `primitive type` vs `wrapper type`에 대해 학습해보고 어떤게 더 적절한 타입일지 고민해보아요.
https://www.slipp.net/questions/66

2024-07-05 03:52 UTC, soominsohn commented on src/main/java/gift/Product.java
> +    }
메서드 시그니처에 throws를 사용해 예외를 전파하고 계시네요. 
메서드 시그니처에 throws를 사용하면 해당 메서드 안에서 발생한 예외를 메서드를 호출한 상위 메서드로 전파하게 됩니다. 과연 필요할까요? 
예외 전파에 대해 공부해 보고 어떻게 개선할 수 있을지 고민해보면 좋을 것 같습니다 😊
또 java의 CheckedException vs UncheckedException의 차이에 대해 공부해보면 좋습니다.

https://www.nextree.co.kr/p3239/
https://hjw43ok.tistory.com/14

2024-07-05 03:53 UTC, merged

2024-07-06 13:52 UTC, kangboom commented on src/main/java/gift/controller/ViewController.java
> +    }
400 Bad Request는 클라이언트가 잘못된 요청을 했을 경우라고 알고 있어서 사용자에게 잘못된 입력 값이라는 것을 알려주기 위해 400을 사용했습니다!

2024-07-06 13:53 UTC, kangboom commented on src/main/java/gift/Product.java
>      private Integer price;
학습해보니 Wrapper 타입으로 사용하지 않아도 될 것 같아서 primitive 타입으로 수정하였습니다! 그냥 아무 생각 없이 Wrapper 타입을 사용했는데 이러한 작은 부분에서도 고민을 하는 게 필요하다는 것을 느꼈습니다. 감사합니다.

2024-07-06 13:53 UTC, kangboom commented on src/main/java/gift/Product.java
> +    }
step1 주제가 controller에서 ExceptionHandler를 통한 예외 처리여서 controller에게 예외를 넘겨주기 위해 throws를 사용하였습니다. 예외 전파에 대해서 공부해보니 UncheckedException은 호출한 곳까지 자동적으로 에러가 전파된다는 것을 알았고 굳이 throws를 해줄 필요도 없다는 것을 알았습니다. 일단은 throws를 다 삭제해주었는데 추가적인 개선사항에 대해서는 예외 처리에 대해서 더 공부한 뒤 다시 수정하겠습니다. 감사합니다.