경북대 BE_정수현 2주차 과제(step1)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #152
Opened 2024-07-03 06:19 UTC by suhyeon7497

1. ProductException에 관한 validation은 ProductRequestDto에서만 일어나는데, ProductException과 관련된 클래스들은 ProductRequestDto 근처에 존재하는 것이 좋을 것이라 생각됩니다. 멘토님은 어떻게 생각하시는지 알고 싶습니다.
2. 2주차 강의에서 검증이 어디서 이루어지는 것이 좋을 지에 대해 생각해보라고 하셨었는데 저는 입력값 검증은 바로 수정이 필요하기 때문에 controller에서 @valid 구문을 통해 이루어져야 한다고 생각하고, 비즈니스 검증에 대한 건 향후에 진행하는 것이 올바르다고 생각합니다. 멘토님은 어떻게 생각하시는지 궁금합니다.
3. 저는 ProductException의 종류를 enum타입 ErrorCode를 통해 분류하였습니다. 근데 다른 분의 코드를 보니 ProductException을 상속해서 Exception을 분류하시는 것을 보았는데, 어느 것이 더 효율적일지 궁금합니다. (Eexception 종류가 많아진다는 경우)
4. @ControllerAdvice 어노테이션이 붙은 class들이 많아지면 어떤 현상이 발생하는지 궁금합니다.
refactoring 할 부분이나 코드 컨벤션을 지키지 못한 부분이 있다면 알려주시면 감사합니다!

2024-07-03 17:13 UTC, sang5c requested changes
안녕하세요 수현님!  
컨벤션이 지켜지지 않은 코드가 너무 많아 request change를 드립니다.  
컨벤션은 사소하지만 가장 먼저 지켜야 하는 규칙입니다.  

천천히 구글 자바 스타일 가이드를 읽어보신 다음, 전체 코드에 대해 정렬(Reformat Code)과 임포트 정리(Optimize imports)를 수행하시고 다시 리뷰 요청을 진행해주세요!  
컨벤션은 작성하신 코드 전체에 대해 확인해주세요.

https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace

2024-07-03 17:13 UTC, sang5c commented on src/main/java/gift/Application.java
> +
두 줄 이상을 비우는 것은 권장되지 않습니다.  
https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace

2024-07-03 17:13 UTC, sang5c commented on src/main/java/gift/controller/AdminController.java
> +
https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace

2024-07-03 17:13 UTC, sang5c commented on src/main/java/gift/controller/AdminController.java
> +        if(bindingResult.hasErrors()) {
if 예약어 뒤에는 빈 칸이 권장됩니다.  
https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace

2024-07-03 17:13 UTC, sang5c commented on src/main/java/gift/controller/AdminController.java
> +        if(productValidator.hasKakaoWord(productRequestDto)){
if 뒤의 빈 칸, 여는 중괄호 뒤의 빈 칸이 권장됩니다.  
https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace

2024-07-04 01:24 UTC, suhyeon7497 commented on src/main/java/gift/controller/AdminController.java
> +        if(productValidator.hasKakaoWord(productRequestDto)){
넵!

2024-07-04 01:24 UTC, suhyeon7497 commented on src/main/java/gift/controller/AdminController.java
> +        if(bindingResult.hasErrors()) {
넵!

2024-07-04 01:25 UTC, suhyeon7497 commented on src/main/java/gift/controller/AdminController.java
> +
넵 죄송합니다 ㅠㅠ

2024-07-04 01:25 UTC, suhyeon7497 commented on src/main/java/gift/Application.java
> +
넵!

2024-07-04 16:50 UTC, sang5c requested changes
아쉽지만 `정확한 요구사항`을 만족하지 못해 다시 한 번 request change를 드려요!  
확인 되면 바로 merge 진행하겠습니다 💪  

---
> ProductException에 관한 validation은 ProductRequestDto에서만 일어나는데, ProductException과 관련된 클래스들은 ProductRequestDto 근처에 존재하는 것이 좋을 것이라 생각됩니다. 멘토님은 어떻게 생각하시는지 알고 싶습니다.

저는 ExceptionHandler가 아닌 다른 클래스에서 의존할 상황이 거의 없다고 느껴서 발생하는 곳에 가까이 두는 편이에요. 얼마 전까지는 Exception 클래스들을 별도의 패키지로 분리했었습니다. 

> 2주차 강의에서 검증이 어디서 이루어지는 것이 좋을 지에 대해 생각해보라고 하셨었는데 저는 입력값 검증은 바로 수정이 필요하기 때문에 controller에서 `@Valid` 구문을 통해 이루어져야 한다고 생각하고, 비즈니스 검증에 대한 건 향후에 진행하는 것이 올바르다고 생각합니다. 멘토님은 어떻게 생각하시는지 궁금합니다.  

저는 가장 먼저 요구사항을 충분히 만족("카카오"문구 불가)하고, 문제 상황에서 클라이언트에게 불가능함을 제대로 전달할 수 있는가를 따져볼 것 같습니다.

추가로 이런 고민이 듭니다.  
지금은 ProductRequestDto를 사용했지만 다른 DTO(다른 API)를 통해서 "카카오"가 전달되면 어떻게 해야할까? 까먹지 않고 입력값 검증을 제대로 수행했을까?

입력 값 검증은 비즈니스와 관련이 없을까요? 🤔  
작성해주신 코드에서 `@Pattern`을 사용하는 방식과 컨트롤러 내에서 비교하는 방식이 있는데
두 가지를 비교해보고, 각각은 어떤 장점과 단점이 있을지 고민 해보시면 좋겠네요 :) 

> 저는 ProductException의 종류를 enum타입 ErrorCode를 통해 분류하였습니다. 근데 다른 분의 코드를 보니 ProductException을 상속해서 Exception을 분류하시는 것을 보았는데, 어느 것이 더 효율적일지 궁금합니다. (Exception 종류가 많아진다는 경우 등등에서)  

내가 어떤 생각으로 이런 코드를 작성했는지가 먼저 필요합니다. 조건에 따라 조건을 만족하는 더 좋은 코드가 있을 순 있는데 잘못된 코드, 정답 코드가 없습니다.  

어떤 이유로 enum으로 만드셨는지, 어떤 효율을 고민하시는지 질문 배경을 조금 더 알려주시면 좋을 것 같아요.

> @ControllerAdvice 어노테이션이 붙은 class들이 많아지면 어떤 현상이 발생하는지 궁금합니다.

@ControllerAdvice는 주로 전역 예외 처리를 위해 사용되기에 많아질 일이 없을 것 같습니다.  
여러개가 존재해야하는 이유를 잘 모르겠고, 여러개라고 인지하기 어려울 것 같네요. 같은 역할을 수행하지만 서로 다른 클래스들에 쪼개져있어서 중복이나 우선순위를 따져가며 개발해야할 것 같습니다.  
정리하면 안티패턴으로 보입니다.  

제가 질문을 제대로 이해하지 못했으면 다시 알려주세요!  

> refactoring 할 부분이나 코드 컨벤션을 지키지 못한 부분이 있다면 알려주시면 감사합니다!  

리뷰 남겼으니 확인해주세요~

2024-07-04 16:50 UTC, sang5c commented on src/main/java/gift/controller/AdminController.java
>              .collect(Collectors.toList());
줄여서 한 번에 사용도 가능합니다 :) 
```suggestion
            .toList();
```

2024-07-04 16:50 UTC, sang5c commented on src/main/java/gift/exception/ProductErrorCode.java
> +    private ProductErrorCode(String message) {
enum의 생성자는 기본으로 private이고 접근제어자를 변경할 수 없기에 생략하는 편입니다.
```suggestion
   ProductErrorCode(String message) {
```

2024-07-04 16:50 UTC, sang5c commented on src/main/java/gift/exception/ProductErrorCode.java
> +    HAS_KAKAO_WORD("\"kakao\"가 포함된 문구는 담당자와 협의 후 사용할 수 있습니다.");
꼭 enum이어야 할까? 고민은 다시 한 번 해볼 필요가 있습니다 :)

2024-07-04 16:50 UTC, sang5c commented on src/main/java/gift/controller/validator/ProductValidator.java
> +        return productRequestDto.getName().contains("kakao");
사소하지만 중요한, 요구사항이 차이가 있습니다.  
`"카카오"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있다.`

2024-07-04 16:50 UTC, sang5c commented on src/main/java/gift/controller/AdminController.java
> +        }
반복적으로 등장하는 코드를 메서드로 분리해서 재사용해보면 어떨까요?

2024-07-04 16:50 UTC, sang5c commented on src/main/java/gift/exception/ProductException.java
> +    private String detailMessage;
사용되지 않는 값이네요!

2024-07-05 00:36 UTC, suhyeon7497 commented on src/main/java/gift/exception/ProductErrorCode.java
> +    HAS_KAKAO_WORD("\"kakao\"가 포함된 문구는 담당자와 협의 후 사용할 수 있습니다.");
저는 에러코드와 message를 지정해주어야 다른 개발자와 협업을 할 때 무슨 문제인 지 빠르게 인지할 수 있다고 생각해서 이런 방식으로 ErrorCode를 작성하였습니다. 그러면 다른 custom exception 발생하더라도 추가할 수 있다고 생각했습니다. 또한 매칭되는 message를 정의함으로써 front에게 정확한 이유를 알려주기위해 enum타입으로 작성하였습니다.
앞서 질문드렸던 enum과 exception을 상속하는것은 exception이 매우 많아질 경우 custom exception에 관한 enum이 많아질 것입니다. 그러면 오히려 가독성을 헤치는 것이 아닐까 하여 질문 드렸습니다.

2024-07-05 00:37 UTC, suhyeon7497 commented on src/main/java/gift/controller/validator/ProductValidator.java
> +        return productRequestDto.getName().contains("kakao");
넵 중요한 부분에서 실수를 하였습니다! 바로 수정하겠습니다!

2024-07-05 00:37 UTC, suhyeon7497 commented on src/main/java/gift/controller/AdminController.java
> +        }
넵!

2024-07-05 00:47 UTC, suhyeon7497 commented on src/main/java/gift/exception/ProductException.java
> +    private String detailMessage;
넵 제거하였습니다!

2024-07-05 00:51 UTC, suhyeon7497 commented
@Pattern문을 통해 검증을 진행하는 것은 사전에 잘못된 값이 필터링된다는 점에서 이점이 있다고 생각합니다. 단지 잘못된 값이 들어왔을 경우에는 개발자가 알 필요 없이 클라이언트만 값을 수정하면 되기때문에 사용했습니다.
exception을 통해 카카오라는 말을 검증하는 부분은 담당자와 협의하여야 한다는 요구사항이 있었습니다. Exception Handler를 통해 검증을 한다면 담당자에게 자동으로 연락이 가게하는 등의 추가적인 로직이 들어갈 수 있다고 생각을 해서 exception을 따로 만들어서 작성했었습니다.

2024-07-05 00:52 UTC, suhyeon7497 commented
새벽 2시에 힘드실 텐데 코드 리뷰 잘해주셔서 감사합니다..!

2024-07-05 16:46 UTC, sang5c approved these changes
1단계 고생 많으셨습니다 👏👏  

마지막으로 고민해보면 좋을 부분들 리뷰 남겼으니 확인해주세요!  

2단계 PR에서는 1단계 머지된 코드를 rebase를 통해 적용해보시면 좋을 것 같습니다.

2024-07-05 16:46 UTC, sang5c commented on src/main/java/gift/controller/ProductController.java
>              .collect(Collectors.toList());
여기도 toList()가 또 있네요!

2024-07-05 16:46 UTC, sang5c commented on src/main/java/gift/controller/validator/ProductValidator.java
> +        if(productRequestDto.getName().contains("카카오")){
전체 코드에 대해 정렬하는 습관을 들여보면 좋을 것 같아요 :)  
자동화된 도구들도 있습니다.

2024-07-05 16:46 UTC, sang5c commented on src/main/java/gift/controller/ProductController.java
> +        productValidator.validateKakaoWord(productRequestDto);
마지막으로, 지금 이 Validator는 어떤 역할을 하고있을까? 고민해보시면 좋을 것 같아요.  
순서상으로는 
1. dto를 받는다
2. entity를 만들기 전 값이 유효한지 검사한다.
3. dto를 entity로 만든다.

이런 상태입니다.  
Validator의 역할은 유효한 값을 가진 `Product`를 만들기 위함이고, 올바른 Product를 생성하는 것을 보장하려면 Product가 생성되는 시점, 즉 생성자 내에 위치하는게 가장 좋다고 생각합니다.

2024-07-05 16:46 UTC, sang5c commented on src/main/java/gift/exception/ProductErrorCode.java
> +    HAS_KAKAO_WORD("\"kakao\"가 포함된 문구는 담당자와 협의 후 사용할 수 있습니다.");
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/167#discussion_r1660151427

이 댓글을 다시 한 번 읽어주세요

2024-07-05 16:46 UTC, sang5c commented on src/main/java/gift/controller/dto/ProductRequestDto.java
> +    public Product toEntity() {
Product는 model 패키지에 위치해있지만, 메서드명은 toEntity()가 되었네요!  
둘은 어떤 차이가 있을까요?

2024-07-05 16:47 UTC, merged

2024-07-06 06:29 UTC, suhyeon7497 commented on src/main/java/gift/controller/ProductController.java
>              .collect(Collectors.toList());
2단계 PR하면서 바꿨습니다!

2024-07-06 06:31 UTC, suhyeon7497 commented on src/main/java/gift/controller/ProductController.java
> +        productValidator.validateKakaoWord(productRequestDto);
중복되는 부분을 제거할 수 있고, Product내부에 위치시키면 가까이 validate 코드가 있으니 보기도 편하겠네요!

2024-07-06 06:38 UTC, suhyeon7497 commented on src/main/java/gift/controller/dto/ProductRequestDto.java
> +    public Product toEntity() {
model과 entity의 차이를 말씀하시는건가요? 2주차 강의를 들었을때는 model이 service, controller 등등의 사이를 지나가는 객체들을 의미한다고 생각했습니다. 그래서 dataBase에 들어가는 entity또한 model이라고 생각했습니다. 저기서 Product도 Entity가 된다고 생각하고 작성하였습니다. 
 model과 entity, dto을 사람마다 다르게 얘기하는 것 같아서 명확히 알고 있지 못한 것 같습니다.

2024-07-06 06:44 UTC, suhyeon7497 commented on src/main/java/gift/controller/validator/ProductValidator.java
> +        if(productRequestDto.getName().contains("카카오")){
ctrl + alt + L (refactoring)과
ctrl + alt + O (optimizing imports)를 적극 사용하고 있습니다!