경북대 BE_윤재용 2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #154
Opened 2024-07-03 06:35 UTC by yooonwodyd

### 추가한 기능
- [ ] Validation
- [ ] DTO Test 코드 작성

궁금한 점
DTO와 Validation이 정상 작동하는지에 대한 테스트 코드를 처음 작성해봅니다. 올바르게 작성됐는지 스스로 판단하기 어렵습니다...!
감사합니다.

2024-07-03 16:10 UTC, khj68 requested changes
고생하셨습니다 :)

2024-07-03 16:10 UTC, khj68 commented on src/main/java/gift/contoller/AdminController.java
> +	private final ProductService productService;
생성자 주입을 하기 위해서 class 어노테이션에 @RequiredArgsConstructor 적용이 필요해보입니다.

2024-07-03 16:10 UTC, khj68 commented on src/main/java/gift/contoller/ProductController.java
> +	private final ProductService productService;
생성자 주입을 하기 위해서 class 어노테이션에 @RequiredArgsConstructor 적용이 필요해보입니다.

2024-07-03 16:10 UTC, khj68 commented on src/main/java/gift/dto/ProductRequestDto.java
> +		regexp = "^(?!.*카카오).*$",
정규식을 이용한 방식도 좋은데요.
이 제약조건이 다른 상품에도 공통적으로 쓰인다고 가정하여, validate 로직을 재사용할 수 있도록 고민해보는 것은 어떨까요?
annotation이나 validator 를 통해 분리함으로써 재활용할 수 있게 됩니다.

2024-07-03 16:10 UTC, khj68 commented on src/main/java/gift/dto/ProductRequestDto.java
> +	)
이 부분도 마찬가지로 분리해서 재사용할 수 있다면 좋을 것 같습니다.

2024-07-03 16:10 UTC, khj68 commented on src/main/java/gift/dto/ProductRequestDto.java
> -
이런 줄바꿈 부분들 잘 챙겨주세요 :)

2024-07-03 16:10 UTC, khj68 commented on src/main/java/gift/contoller/ProductController.java
> +	}
이 부분을 제거하고 @RequiredArgsConstructor를 활용하는 방법을 추천드려봅니다.

2024-07-03 16:10 UTC, khj68 commented on src/main/java/gift/repository/ProductRepositoryImpl.java
> +	}
이 부분을 제거하고 @RequiredArgsConstructor를 활용하는 방법을 추천드려봅니다.

2024-07-03 16:10 UTC, khj68 commented on src/main/java/gift/service/ProductService.java
> +	}
이 부분을 제거하고 @requiredargsconstructor를 활용하는 방법을 추천드려봅니다.

2024-07-03 16:10 UTC, khj68 commented on src/test/java/gift/dto/ProductRequestDtoTest.java
> +		assertEquals("Product name must be at most 15 characters long", violations.iterator().next().getMessage());
에러 메시지를 문자열로 넣게 되면, 추후 에러메시지를 수정할 때에 유지보수 영향도가 커지게 됩니다.
해당 메시지 역시 정의해 놓은 클래스에서 가져올 수 있는 방법이 없을지 고민해보시면 좋을 것 같습니다 :)

2024-07-03 16:11 UTC, khj68 commented
DTO와 Validation이 정상 작동하는지에 대한 테스트 코드를 처음 작성해봅니다. 올바르게 작성됐는지 스스로 판단하기 어렵습니다...!
감사합니다.
- 전반적으로 잘 작성해주셨습니다. 다만 메시지가 문자열로 그대로 들어간 부분은 추후 코드 수정 시 많은 영향범위를 가지게 될 수 있습니다. 이 부분을 어떻게 가져갈 수 있을지 고민해주시면 좋을 것 같습니다 :)

2024-07-05 07:35 UTC, yooonwodyd commented on src/main/java/gift/contoller/AdminController.java
> +	private final ProductService productService;
넵! 롬복으로 변경했습니다.

2024-07-05 07:36 UTC, yooonwodyd commented on src/main/java/gift/contoller/ProductController.java
> +	private final ProductService productService;
확인했습니다!

2024-07-05 07:37 UTC, yooonwodyd commented on src/main/java/gift/dto/ProductRequestDto.java
> +		regexp = "^(?!.*카카오).*$",
별도의 로직으로 변경했습니다.

> 정규식을 이용한 방식도 좋은데요. 이 제약조건이 다른 상품에도 공통적으로 쓰인다고 가정하여, validate 로직을 재사용할 수 있도록 고민해보는 것은 어떨까요? annotation이나 validator 를 통해 분리함으로써 재활용할 수 있게 됩니다.

넵! validate 로직을 별도의 어노테이션으로 분리했습니다.

2024-07-05 07:37 UTC, yooonwodyd commented on src/main/java/gift/dto/ProductRequestDto.java
> +	)
넵 감사합니다

2024-07-05 07:37 UTC, yooonwodyd commented on src/main/java/gift/contoller/ProductController.java
> +	}
> 이 부분을 제거하고 @requiredargsconstructor를 활용하는 방법을 추천드려봅니다.

넵 롬복을 통해 변경했습니다!

2024-07-05 07:39 UTC, yooonwodyd commented on src/test/java/gift/dto/ProductRequestDtoTest.java
> +		assertEquals("Product name must be at most 15 characters long", violations.iterator().next().getMessage());
> 에러 메시지를 문자열로 넣게 되면, 추후 에러메시지를 수정할 때에 유지보수 영향도가 커지게 됩니다. 해당 메시지 역시 정의해 놓은 클래스에서 가져올 수 있는 방법이 없을지 고민해보시면 좋을 것 같습니다 :)

ValidationMessage.enum 클래스를 통해 별도의 메세지로 분리했습니다. 감사합니다 : )

2024-07-05 08:00 UTC, yooonwodyd commented on src/main/java/gift/repository/ProductRepositoryImpl.java
> +	}
확인했습니다!

2024-07-05 08:00 UTC, yooonwodyd commented on src/main/java/gift/service/ProductService.java
> +	}
확인했습니다!

2024-07-05 09:44 UTC, khj68 requested changes
고생하셨습니다!
피드백을 잘 반영해주신 것을 확인했습니다.

2024-07-05 09:44 UTC, khj68 commented on src/main/java/gift/core/annotaions/NoKakaoValidator.java
> +public class NoKakaoValidator implements ConstraintValidator<NoKakao, String> {
validator 적용 좋습니다.

2024-07-05 09:44 UTC, khj68 commented on src/main/java/gift/core/authorization/interceptor/AuthorizationInterceptor.java
> +		request.setAttribute("USER", UserDetails.from(jwtProvider.getClaims(rawToken)));
권한 부여하는 과정 좋습니다.

2024-07-05 09:44 UTC, khj68 commented on src/main/java/gift/core/exception/ValidationMessage.java
> +public enum ValidationMessage {
메시지를 따로 관리하는 것 좋습니다.

2024-07-05 09:44 UTC, khj68 commented on src/main/java/gift/core/jwt/JwtProvider.java
> +	private static final long TOKEN_VALIDITY = 1000L * 60 * 60 * 24 * 7; // 7일
시간 계산 적용을 명시해둔 것 좋습니다.

2024-07-05 09:44 UTC, khj68 commented on src/main/java/gift/feat/product/dto/ProductRequestDto.java
> +	@NoKakao
아주 깔끔해졌네요.

2024-07-05 09:44 UTC, khj68 commented on src/main/java/gift/feat/product/dto/UserResponseDto.java
> +	// id,email,password,roll,wishList
이 주석은 지워도 될 것 같습니다 :)

2024-07-05 09:44 UTC, khj68 commented on src/main/java/gift/feat/user/controller/UserRestController.java
> +		return token;
패스워드를 검증하는 로직은 보이지 않는 것 같습니다.

2024-07-05 09:44 UTC, khj68 commented on src/test/java/gift/dto/ProductRequestDtoTest.java
> +		assertEquals("Product name contains invalid characters", violations.iterator().next().getMessage());
첫번째 파라미터와 같은 문자열로 비교하는 부분을, message 분리해주신 것으로 대체할 수 있지 않을까요?

2024-07-07 14:31 UTC, merged