전남대 BE_조설빈 2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #160
Opened 2024-07-03 07:05 UTC by seolbin96

- '카카오'라는 문구가 포함되면 단순히 담당 md와 협의 후 이용하라는 메세지를 반환하도록 했는데, 실제로 서비스를 개발하게 되면 담당 md와의 협의를 어떻게 처리해야 하는지 궁금합니다..!

- 상품 가격에 대해 @Min 어노테이션을 사용하여 0원 이하일 경우 "상품 가격은 0원 이상이어야 한다"는 메세지를 반환하도록 하려 했는데, 이 부분이 제대로 이루어지지 않았습니다. 과제에서 요구되었던 사항은 아니라 일단은 해당 코드를 삭제했는데 왜 제대로 작동하지 않았는지 잘 모르겠습니다.

2024-07-03 15:26 UTC, seungy0 commented
우선 질문주신 것부터 답변드리겠습니다.
### 질문1
> '카카오'라는 문구가 포함되면 단순히 담당 md와 협의 후 이용하라는 메세지를 반환하도록 했는데, 실제로 서비스를 개발하게 되면 담당 md와의 협의를 어떻게 처리해야 하는지 궁금합니다..!

실제 회사라고 상상해보면 회사에 MD, 개발자가 계실테고, 회사 외부에 판매자가 계시겠죠.
개발자는 판매자가 사용하는 API 또는 화면을 제공할테고, 판매자가 카카오라는 문구를 사용하면 에러창을 띄울것입니다.
이 에러창을 본 판매자는 담당 MD에게 카카오 문구 사용을 요청드려서 협의 과정이 있을 것이구요.

그러면 MD 분은 관리자 도구로 해당 판매자가 카카로라는 문구를 사용할 수 있게 처리해주거나 하실 것 같네요. 이 때 개발자의 도움이 필요하면 MD 분이 개발자에게 요청을 주시겠죠.
여기까지 제 상상이었구요. 회사마다 조금씩 다를 것 같습니다.
### 질문2
> 상품 가격에 대해 @min 어노테이션을 사용하여 0원 이하일 경우 "상품 가격은 0원 이상이어야 한다"는 메세지를 반환하도록 하려 했는데, 이 부분이 제대로 이루어지지 않았습니다. 과제에서 요구되었던 사항은 아니라 일단은 해당 코드를 삭제했는데 왜 제대로 작동하지 않았는지 잘 모르겠습니다.

이상하네요. 제가 @Min(1) 사용하니까 잘 되네요. bindingResult를 사용하셔서 안된다고 느끼실 수도 있어요.
어떻게 안되는지 상술해주시면 해결에 도움을 드릴 수 있습니다. 또는 멘토링 시간에 실시간으로 도와드릴 수 있습니다ㅎㅎ

2024-07-03 15:44 UTC, seungy0 requested changes
설빈님 고생하셨습니다~!!
몇가지 코멘트 남겨놓았습니다. 참고해주세요😊

2024-07-03 15:44 UTC, seungy0 commented on build.gradle
> +    providedCompile 'jakarta.platform:jakarta.jakartaee-web-api:8.0.0'
해당 부분은 필요없습니다. 29번 줄의 spring-boot-starter-validation를 사용하시면 됩니다.
Product 클래스 밸리데이션 때문에 이 의존성을 추가하신 건 알고 있습니다. 해당 부분에서 다시 설명드릴게요.

+) 잡다한 상식
오라클이 java를 소유하게 되면서 javax -> jakarta로 이름을 바꾸게 되었습니다. 이런 히스토리도 알고 계시면 좀 더 재밌게 공부하실 수 있습니다ㅎㅎ [참고글](https://www.baeldung.com/java-enterprise-evolution)

2024-07-03 15:44 UTC, seungy0 commented on src/main/java/gift/model/Product.java
> +import javax.validation.constraints.Size;
```suggestion
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
```
위에서 말씀드린대로 build.gradle에 jakarta 의존성 추가하실 필요없구요. 이렇게 변경하시면 잘 동작할 겁니다. spring-validation의 하위 의존성으로 포함되어 있기 때문입니다.

2024-07-03 15:44 UTC, seungy0 commented on build.gradle
> +    id 'war'
오잉 요건 어떤 의도로 하신건지 궁금합니다.

2024-07-03 15:44 UTC, seungy0 commented on src/main/java/gift/controller/ProductController.java
>          }
좋은 접근입니다. @Valid만 사용해도 밸리데이션은 잘 되는데, BindingResult를 사용해서 얻는 이점이 뭘까요?

2024-07-03 15:44 UTC, seungy0 commented on src/main/java/gift/controller/ProductController.java
> +        }
해당 코드는 죽은 코드입니다. 이 조건문 안으로 들어오는 경우가 없기 때문입니다.
name이 15보다 긴 경우 이미 41번 줄에서 return 하게 됩니다.

2024-07-03 15:44 UTC, seungy0 commented on src/main/java/gift/controller/ProductController.java
> +        }
요 부분도 Product 클래스의 Pattern 어노테이션과 중복입니다~

2024-07-03 15:44 UTC, seungy0 commented on src/main/java/gift/controller/ProductController.java
> +        }
없어도 되는 코드입니다~ 지워주세요.

2024-07-03 15:44 UTC, seungy0 commented on src/main/java/gift/controller/ProductController.java
> +        }
POST의 코드와 중복이 있으므로 private 메서드로 분리하는 것도 좋겠습니다.

이 부분도 어노테이션으로 처리 가능하긴하지만 비즈니스 로직과 연관된 밸리데이션이므로 서비스 레이어에서 밸리데이션해도 좋을 것 같습니다.

2024-07-03 15:44 UTC, seungy0 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
👍

2024-07-03 15:44 UTC, seungy0 commented on src/main/java/gift/controller/ProductController.java
> +import javax.validation.Valid;
```suggestion
import jakarta.validation.Valid;
```
이것도 변경하시면 됩니다.

2024-07-03 15:44 UTC, seungy0 commented on src/test/resources/http-requests/requests.http
테스트 코드 작성 좋습니다.
지금과 같은 방식도 물론 좋구요.
https://spring.io/guides/gs/testing-web
이런 방식의 테스트도 가능하다는 점 알고계시면 좋을 것 같습니다.

2024-07-04 05:52 UTC, seolbin96 commented
@valid를 사용했을 때 cannot resolve symbol 'validation' 에러가 계속 떠서 아래의 블로그를 참고했습니다!
https://0713k.tistory.com/56
그런데 멘토님께서 피드백 주신대로 수정하니 id 'war' 부분을 지워도 제대로 작동이 되네요..! 알려주셔서 감사합니다..!!

2024-07-04 15:46 UTC, seungy0 approved these changes
설빈님 고생하셨습니다~👍

2024-07-04 15:46 UTC, merged