경북대 BE_박한솔 2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #164
Opened 2024-07-03 07:31 UTC by pjhcsols

1. 상품 이름 유효성 검사 ProductRequestDTO, ProductController/AdminProductController 유효성 검증 기능 추가
길이 제한: 최대 15자
허용 특수 문자: ( ) [ ] + - & / _
"카카오" 포함 제한: 담당 MD와 협의가 필요

[a-zA-Z0-9가-힣()\[\]+\-&/_]*: 실제로 검사하고자 하는 패턴입니다.
a-zA-Z0-9: 영어 대소문자 및 숫자에 해당하는 문자들입니다.
가-힣: 한글 문자에 해당하는 범위입니다.
()\[\]+\-&/_: 특정 기호들을 나타내며, 이들은 그대로 매칭됩니다.
*: 0개 이상의 앞의 패턴들을 나타내는 수량자입니다.

2. 예외 처리 GlobalExceptionHandler, ProductValidationException, error.html
유효성 검사 실패 시 적절한 예외 메시지를 반환합니다.
예외 발생 시 전역 예외 처리 핸들러를 구현하여 통일된 방식으로 예외를 관리합니다.

2024-07-03 13:02 UTC, lsm7179 reviewed
한솔님.
1단계 고생하셨어요.👍
피드백을 남겼으니 피드백을 해결 해보면 좋을거 같습니다.🔥

2024-07-03 13:02 UTC, lsm7179 commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.ok(products);
ResponseEntity.ok 활용좋네요.👍

2024-07-03 13:02 UTC, lsm7179 commented on src/main/java/gift/controller/ProductController.java
>      @GetMapping("/get")
rest api 에 대해서 한번 고민해보면 좋을거 같아요.
회사마다 프로젝트마다 url 정책은 꼭 rest하게 진행하진 않지만 restapi가 어떤건지 무엇인지는 알고 계셨으면 좋겠네요. 😁
등록, 수정, 삭제 메서드도 같이 확인해주세요~

2024-07-03 13:02 UTC, lsm7179 commented on src/main/java/gift/domain/ProductRequestDTO.java
> +    }
음.. 이러면 새로운 기능이나 도메인이 생길때마다 매번 로직을 추가해야 합니다.🤔
spring validate를 이용해서 처리해보아요~

[Spring validate](https://www.baeldung.com/spring-boot-bean-validation)

2024-07-03 13:02 UTC, lsm7179 commented on src/main/java/gift/controller/admin/AdminProductController.java
> +                             @RequestPart MultipartFile imageFile) throws IOException {
프론트와 api통신을 할때 json으로 주고 받는 경우가 많습니다.
form 형식이 아닌 json통신을 이용한 RequestBody로 받아보세요.
RequestBody받으면 spring validate를 적용하기 더 수월해질거에요~!

2024-07-03 13:02 UTC, lsm7179 commented on src/main/java/gift/controller/admin/AdminProductController.java
> +        product.setImageUrl(imageUrl);
상품이 빈약한 도메인 객체가 된거 같아요.
업데이트는 상품에 역할로 보는게 어떨까요?
수정해달라고 상품객체에 던져보세요.😁
예를 들어서 `product.update(...)`

2024-07-03 13:02 UTC, lsm7179 commented on src/main/java/gift/controller/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
@ControllerAdvice와 @ExceptionHandler로 잘 처리해주셨네요. 👍

다만 RestControllerAdvice과 차이를 알고 계신가요?
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/RestControllerAdvice.html

2024-07-03 13:02 UTC, lsm7179 commented on src/main/resources/application.properties
>  #???????
해당주석은 없어도 될거 같네요.😅

2024-07-03 13:02 UTC, lsm7179 commented on src/main/java/gift/controller/admin/AdminProductController.java
> +                             @RequestPart MultipartFile imageFile) throws IOException {
피드백 반영해보시면서 MultipartFile를 제어하는게 어렵다면 이번 과제에서 빼주셔도 좋을거 같아요.

2024-07-03 13:03 UTC, lsm7179 requested changes
한솔님.
1단계 고생하셨어요.👍
피드백을 남겼으니 피드백을 해결 해보면 좋을거 같습니다.🔥

2024-07-03 14:53 UTC, pjhcsols commented on src/main/java/gift/controller/ProductController.java
>      @GetMapping("/get")
넵!! 인지하고있습니다. RESTful하게 변경하도록 하겠습니다!!

2024-07-03 18:05 UTC, pjhcsols commented on src/main/java/gift/domain/ProductRequestDTO.java
> +    }
기존 컨트롤러에서 이미지와 함께 상품 추가 및 업데이트 하는 로직으로 인해 @RequestParam으로 받을 수 밖에 없게 구성되어 있어서 사용을 하지 못하였습니다. 

따라서 @RequestBody @Valid를 사용하기 위해 멀티파트로 사용자 이미지 업로드 로직과 addProduct 로직을 분리하여 이미지 업로드 후 반환되는 base 64로 인코딩 된 URL을 클라이언트 측에서 받아서 

addProduct http 요청시에 @RequestBody @Valid ProductRequestDTO를 사용하여 이미지 파일이 아닌imageUrl을 함께 받도록 수정하였습니다.

수정시에도 이미지 수정 로직은 별개로 작성하였습니다.

2024-07-03 18:06 UTC, pjhcsols commented on src/main/java/gift/controller/admin/AdminProductController.java
> +                             @RequestPart MultipartFile imageFile) throws IOException {
넵 최대한 반영하여 멀티파트 제어까지 해보겠습니다!!!!

2024-07-03 18:09 UTC, pjhcsols commented on src/main/java/gift/controller/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
감사합니다 참고하겠습니다!!!

2024-07-03 18:23 UTC, pjhcsols commented on src/main/java/gift/controller/admin/AdminProductController.java
> +        product.setImageUrl(imageUrl);
넵 수정하였습니다!!!

2024-07-03 18:23 UTC, pjhcsols commented on src/main/java/gift/controller/admin/AdminProductController.java
> +        product.setImageUrl(imageUrl);
product.update(productRequestDTO);

2024-07-03 18:23 UTC, pjhcsols commented on src/main/java/gift/controller/admin/AdminProductController.java
> +        product.setImageUrl(imageUrl);
product.updateAdmin(productRequestDTO, imageUrl);

2024-07-03 18:28 UTC, pjhcsols commented
수정 완료하였습니다

2024-07-03 18:37 UTC, pjhcsols commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.ok(products);
감사합니다!

2024-07-03 18:37 UTC, pjhcsols commented on src/main/resources/application.properties
>  #???????
제거하였습니다!

2024-07-04 11:15 UTC, lsm7179 approved these changes
한솔님.
1단계 고생하셨어요.👍
머지하기 충분히 잘 해주신거 같아요.🔥

간단한 피드백도 드렸는데 다음 단계에서 같이 반영해보세요~!👍

2024-07-04 11:15 UTC, lsm7179 commented on src/main/java/gift/controller/ProductController.java
> +@Validated
@Validated 는 왜 넣었나요?

2024-07-04 11:15 UTC, lsm7179 commented on src/main/java/gift/domain/ProductRequestDTO.java
> +    @Pattern(regexp = "^[a-zA-Z0-9가-힣()\\[\\]+\\-&/_]*$", message = "상품 이름에 허용되지 않는 특수 문자가 포함되어 있습니다.")
spring vaildate를 잘 사용해주셨네요.

2024-07-04 11:15 UTC, lsm7179 commented on src/main/java/gift/validation/ApprovedByMDValidator.java
> +    }
md 인증 구현부를 만들어 주신거군요 😁

2024-07-04 11:15 UTC, lsm7179 commented on src/main/java/gift/domain/Product.java
> +    public void updateAdmin(ProductRequestDTO productRequestDTO, String imageUrl) {
👍
도메인에 로직이 잘 추가 되었지만 dto가 도메인을 침범했네요.
`update(Product updateProduct) {}`로 만들어서 dto가 도메인을 침범하지 않도록 해보세요~

2024-07-04 11:15 UTC, lsm7179 commented on src/main/java/gift/validation/ApprovedByMD.java
> +public @interface ApprovedByMD {
nit: ApprovedByMD 어노테이션명은 커스텀validate class처럼 느껴지지않네요.
NotBlank, NotNull 처럼 직관적인 어노테이션명을 고민해보세요.

2024-07-04 11:15 UTC, merged