전남대 BE_박준형 2주차 과제 (step1)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #170
Opened 2024-07-03 09:43 UTC by cliant

### 코드 작성하면서 어려웠던 부분

- 협의를 한 후에 결정한다. 라는 요구사항에 대해 고민했습니다. 협의를 한 후 카카오란 문구를 쓰게 되었다면 그 자격에 대한 증명을 어떻게 할 것인가 고민을 하다 답을 찾지 못하고 대신 2단계에 인증에 대한 과제에서 협의가 된 계정들은 카카오 문구를 사용할 수 있게 할 수 있게다는 생각을 했습니다. 

- 예외를 어떻게 처리할지 고민했던 것 같습니다. 입력창에 메세지를 띄워야되나 아니면 작성한 코드처럼 에러페이지를 띄워야되나 고민했습니다. 협의에 대한 요구사항을 후에 error_page에서 다룰 수도 있을 것 같아 우선 메세지를 띄우는 방식보단 에러 페이지를 띄우는 식으로 코드를 짰습니다. 

### 코드 리뷰 시, 멘토 님이 중점적으로 리뷰해줬으면 하는 부분

- 아이디 중복 검사를 추가하다보니 EmptyResultDataAccessException이 발생하여 이것을 ProductDao에 try-catch문으로 예외처리를 해줬는데 이를 코드의 일관성을 위해 GlobalExceptionHandler에서 처리해주는게 나은지 궁금합니다. 

- 협의가 필요하다.라는 부분을 예외처리하기 위해 InvalidNameException을 만들었는데 이러한 custom exception을 만드는게 효율성 측면에서 좋은 코드인지 궁금합니다.

2024-07-04 11:12 UTC, dc-choi reviewed
안녕하세요~ 2주차 과제 step1을 수행하시느라 수고하셨습니다!

자세한 내용은 코멘트에 남겨두었습니다~

준형님의 질문에 대한 답변을 하면서 마치도록 하겠습니다~!

> 협의를 한 후에 결정한다. 라는 요구사항에 대해 고민했습니다. 협의를 한 후 카카오란 문구를 쓰게 되었다면 그 자격에 대한 증명을 어떻게 할 것인가 고민을 하다 답을 찾지 못하고 대신 2단계에 인증에 대한 과제에서 협의가 된 계정들은 카카오 문구를 사용할 수 있게 할 수 있게다는 생각을 했습니다.

좋은 생각입니다. 그럼 협의가 된 계정은 어떻게 구분을 할까요?

> 예외를 어떻게 처리할지 고민했던 것 같습니다. 입력창에 메세지를 띄워야되나 아니면 작성한 코드처럼 에러페이지를 띄워야되나 고민했습니다. 협의에 대한 요구사항을 후에 error_page에서 다룰 수도 있을 것 같아 우선 메세지를 띄우는 방식보단 에러 페이지를 띄우는 식으로 코드를 짰습니다.

지금은 프론트엔드까지 전부 구현을 하고있지만 프론트엔드와 따로 구분이 되는 경우에는 에러 메시지만 던져주고 프론트엔드에서 에러 메시지를 사용자에 맞게 처리하기도 합니다~ 개인적으로 에러 메시지만 띄워주고 그 부분에 대한 처리만 따로 하는 것이 더 바람직하다고 생각합니다!

> 아이디 중복 검사를 추가하다보니 EmptyResultDataAccessException이 발생하여 이것을 ProductDao에 try-catch문으로 예외처리를 해줬는데 이를 코드의 일관성을 위해 GlobalExceptionHandler에서 처리해주는게 나은지 궁금합니다.

코멘트에서 언급하였습니다. 확인 부탁드립니다~!

> 협의가 필요하다.라는 부분을 예외처리하기 위해 InvalidNameException을 만들었는데 이러한 custom exception을 만드는게 효율성 측면에서 좋은 코드인지 궁금합니다.

이 부분도 마찬가지로 코멘트에서 언급하였습니다. 확인 부탁드립니다~!

2024-07-04 11:12 UTC, dc-choi commented on src/main/java/gift/InvalidNameException.java
> +public class InvalidNameException extends RuntimeException {
유효하지 않은 이름이라는 예외말고 다른 예외가 발생했을 경우에는 어떻게 처리가 되나요? 새로 예외를 만드실 생각인가요?

2024-07-04 11:12 UTC, dc-choi commented on src/main/java/gift/Product.java
> +    @Pattern(regexp = "^[a-zA-Z0-9 ()\\[\\]+\\-\\&\\/\\_가-힣]*$", message = "Name has invalid chracter")
이 부분에 예외가 발생한 경우 어떻게 처리되나요?

2024-07-04 11:12 UTC, dc-choi commented on src/main/java/gift/ProductDAO.java
>      public Product findOne(Long id){
try/catch로 catch 로직에서 null을 반환하기 보단 `Optional`을 사용하는건 어떨까요?

2024-07-05 03:17 UTC, dc-choi requested changes
안녕하세요~ 다시 PR 리뷰 요청을 확인하였습니다~!

자세한 내용은 코멘트에 남겨두었습니다~

준형님의 질문에 대한 답변을 다시 남겨드리겠습니다!

> 협의를 한 후에 결정한다. 라는 요구사항에 대해 고민했습니다. 협의를 한 후 카카오란 문구를 쓰게 되었다면 그 자격에 대한 증명을 어떻게 할 것인가 고민을 하다 답을 찾지 못하고 대신 2단계에 인증에 대한 과제에서 협의가 된 계정들은 카카오 문구를 사용할 수 있게 할 수 있게다는 생각을 했습니다.

좋은 생각입니다. 그럼 협의가 된 계정은 어떻게 구분을 할까요? Spring에서 이 부분은 어떻게 처리하는지에 대한 부분에 대해서 고민해보시는게 좋을거 같아요~

> 예외를 어떻게 처리할지 고민했던 것 같습니다. 입력창에 메세지를 띄워야되나 아니면 작성한 코드처럼 에러페이지를 띄워야되나 고민했습니다. 협의에 대한 요구사항을 후에 error_page에서 다룰 수도 있을 것 같아 우선 메세지를 띄우는 방식보단 에러 페이지를 띄우는 식으로 코드를 짰습니다.

지금은 프론트엔드까지 전부 구현을 하고있지만 프론트엔드와 따로 구분이 되는 경우에는 에러 메시지만 던져주고 프론트엔드에서 에러 메시지를 사용자에 맞게 처리하기도 합니다~ 개인적으로 에러 메시지만 띄워주고 그 부분에 대한 처리만 따로 하는 것이 더 바람직하다고 생각합니다!

> 아이디 중복 검사를 추가하다보니 EmptyResultDataAccessException이 발생하여 이것을 ProductDao에 try-catch문으로 예외처리를 해줬는데 이를 코드의 일관성을 위해 GlobalExceptionHandler에서 처리해주는게 나은지 궁금합니다.

`ProductDao`의 `findOne`부분 때문에 질문을 주신거 같아요~ 이 부분은 코멘트에서 말씀드렸던 `Optional`을 사용하고 `Service`단에서 GlobalExceptionHandler로 예외를 던지는게 좋다고 생각합니다~

> 협의가 필요하다.라는 부분을 예외처리하기 위해 InvalidNameException을 만들었는데 이러한 custom exception을 만드는게 효율성 측면에서 좋은 코드인지 궁금합니다.

코멘트에서 언급하였습니다. 확인 부탁드립니다~!

2024-07-05 03:17 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +    public String addProduct(@Valid @ModelAttribute Product product, BindingResult bindingResult, Model model) {
`Product`라는 record 하나로 DTO와 Entity의 역할을 전부 다 하고 있는 것으로 보입니다.

DTO, Entity가 각각 무엇이고 왜 둘을 나눠야 하는지에 대해서 고민해보셨으면 좋겠습니다!

2024-07-05 03:17 UTC, dc-choi commented on src/main/java/gift/exception/InvalidNameException.java
> +public class InvalidNameException extends RuntimeException {
유효하지 않은 이름이라는 예외에 대해서만 처리하는게 아니라 공통의 이름을 가진 예외로 네이밍을 변경하고

그 안에 메시지를 다르게 보내는 것에 대해서는 어떻게 생각하시나요?

2024-07-05 03:17 UTC, dc-choi commented on src/main/java/gift/domain/Product.java
> +    @Pattern(regexp = "^[a-zA-Z0-9 ()\\[\\]+\\-\\&\\/\\_가-힣]*$", message = "Name has invalid chracter")
이 부분에 예외가 발생한 경우 어떻게 처리되나요? 동작 원리에 대해서 설명해주실 수 있나요?

2024-07-05 03:17 UTC, dc-choi commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(InvalidNameException.class)
`InvalidNameException`이 발생되었을 때만 에러 페이지로 이동하는 이유를 알 수 있을까요?

2024-07-05 03:17 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +    public String updateProduct(@PathVariable Long id,@Valid @ModelAttribute Product updatedProduct, BindingResult bindingResult, Model model) {
`Product`라는 record 하나로 DTO와 Entity의 역할을 전부 다 하고 있는 것으로 보입니다.

DTO, Entity가 각각 무엇이고 왜 둘을 나눠야 하는지에 대해서 고민해보셨으면 좋겠습니다!

2024-07-05 03:17 UTC, dc-choi commented on src/main/java/gift/dao/ProductDao.java
> +    public Optional<Product> findOne(Long id){
피드백을 잘 반영해주셔서 감사합니다!

2024-07-05 03:17 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +        if (productOptional.isPresent()) {
`orElseThrow()`라는 메서드를 사용하면 더 간단하게 처리할 수 있는 부분으로 보입니다. 어떻게 생각하시나요?

2024-07-05 03:17 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +        if(productDao.findOne(product.id()) != null){
`Optional`을 사용하게 되면 이 부분에 대한 코드도 수정되어야 할 거 같습니다~ 확인 부탁드려요~

2024-07-05 03:17 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +        if(updatedProduct.name().contains("카카오")){
생성과 수정에서 같은 예외가 처리가 되는 것으로 보이는데 이 부분의 중복을 줄일 수 있다고 생각합니다. 어떻게 생각하시나요?

2024-07-05 07:06 UTC, cliant commented on src/main/java/gift/domain/Product.java
> +    @Pattern(regexp = "^[a-zA-Z0-9 ()\\[\\]+\\-\\&\\/\\_가-힣]*$", message = "Name has invalid chracter")
파라미터 앞에 @Valid 태그를 추가하면 어노테이션 적용된 객체에 대해 유효성 검사를 하고 실패하면 예외를 발생시킵니다. 에러 메세지를 form에 출력하기 위해
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/170/commits/123eef566250cbcff8fb17b967285017e46217a8
위와 같이 Map객체로 필드네임과 에러 메세지를 수정했는데 혹시 form 에러가 나타나지  않는데 이유에 대해 질문 드리고 싶습니다.

2024-07-05 07:08 UTC, cliant commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(InvalidNameException.class)
카카오 문구 사용에 대한 협의를 에러 페이지에서 추후에 표현할 수 있지 않을까 싶은 생각이었는데 다시 생각하니 불필요할 것 같아 삭제하였습니다.

2024-07-05 07:51 UTC, dc-choi commented on src/main/java/gift/domain/Product.java
> +    @Pattern(regexp = "^[a-zA-Z0-9 ()\\[\\]+\\-\\&\\/\\_가-힣]*$", message = "Name has invalid chracter")
커밋 메시지를 확인해봤는데 `e.getBindingResult().getFieldErrors().getFirst()`로 변경해보시겠어요?

그리고 `ResponseEntity`를 반환하여 HTTP Status Code에 대한 값도 설정해주시면 좋을 거 같아요~

2024-07-05 08:31 UTC, cliant commented on src/main/java/gift/domain/Product.java
> +    @Pattern(regexp = "^[a-zA-Z0-9 ()\\[\\]+\\-\\&\\/\\_가-힣]*$", message = "Name has invalid chracter")
`
@ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<Map<String, String>> handleValidationExceptions(MethodArgumentNotValidException e) {
        Map<String, String> errors = new HashMap<>();
        // e.getBindingResult().getFieldErrors().forEach(error -> {
        //     String fieldName = ((FieldError) error).getField();
        //     String errorMessage = error.getDefaultMessage();
        //     errors.put(fieldName, errorMessage);
        // });
        FieldError error = e.getBindingResult().getFieldErrors().getFirst();
        errors.put(error.getField(), error.getDefaultMessage());
        return new ResponseEntity<>(errors, HttpStatus.BAD_REQUEST);
    }
`
위와 같이 시도하여 유효성 검사를 통과지 못하게 할 수 있게 됐습니다.

2024-07-05 08:33 UTC, dc-choi commented on src/main/java/gift/domain/Product.java
> +    @Pattern(regexp = "^[a-zA-Z0-9 ()\\[\\]+\\-\\&\\/\\_가-힣]*$", message = "Name has invalid chracter")
너무 잘하셨습니다! 굿굿!

2024-07-05 08:41 UTC, dc-choi commented
추가적으로 코드를 보면서 말씀을 못드렸던 부분이 있는데 클라이언트로 반환되는 값 또한 DTO로 처리가 되어야 합니다~!

2024-07-05 08:42 UTC, cliant commented on src/main/java/gift/controller/ProductController.java
> +    public String updateProduct(@PathVariable Long id,@Valid @ModelAttribute Product updatedProduct, BindingResult bindingResult, Model model) {
Service 레이어를 추가하여 DB작업을 할 때 외에 데이터를 주고 받을 땐 ProductDto를 사용하도록 변경하였습니다.

2024-07-05 08:55 UTC, cliant commented on src/main/java/gift/exception/InvalidNameException.java
> +public class InvalidNameException extends RuntimeException {
카카오 문구에 대한 유효성 검사를 어노테이션으로 진행하게끔 하였기에 삭제하였습니다.

2024-07-05 08:57 UTC, dc-choi commented on src/main/java/gift/service/ProductService.java
> +    public List<Product> findAll(){
이 부분의 반환값도 DTO로 변경해주세요~

2024-07-05 09:05 UTC, cliant commented on src/main/java/gift/service/ProductService.java
> +    public List<Product> findAll(){
넵 반영하였습니다

2024-07-05 11:38 UTC, dc-choi approved these changes
준형님 step1 과제 진행하시느라 고생하셨습니다~!

바로 step2 과제 해주시면 될 거 같습니다~! 수고하셨습니다!

2024-07-05 11:38 UTC, merged