강원대 BE_이의찬 2주차 과제(step1)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #173
Opened 2024-07-03 13:22 UTC by ana-raka

# Step1 과제 수행한 결과입니다.
## 과제 진행 정리입니다.
- 1주차 과제로 주신 피드백을 일단 반영할 수 있는 부분 반영하였습니다. (아직 테스트 코드는 작성하지 못했습니다..)
- Step 1 을 진행하면서 큰 어려움은 없었는데 Validation을 사용하는 예시를 찾아보면 객체를 record가 아니라 그냥 class로 작성하던데 Record를 사용하지 않는게 더 범용적? 보편적인 경우인지 궁금합니다.
- 감사합니다 !

2024-07-03 13:50 UTC, pci2676 commented
> * Step 1 을 진행하면서 큰 어려움은 없었는데 Validation을 사용하는 예시를 찾아보면 객체를 record가 아니라 그냥 class로 작성하던데 Record를 사용하지 않는게 더 범용적? 보편적인 경우인지 궁금합니다.

아티클에서 사용하는 java 의 버전이 낮은경우 record를 사용할 수 없어서 그럴수 있습니다. 😄

2024-07-03 14:01 UTC, pci2676 requested changes
리뷰를 남겨두었으니 확인하신 뒤 개선하여 다시 PR 부탁드립니다. 😄

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/Product.java
> +package gift;
이 클래스는 다른 패키지에 위치하는게 더 좋을것 같습니다. :)

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +package gift;
이 클래스는 다른 패키지에 위치하는게 더 좋을것 같습니다. :)

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/ProductDao.java
> +package gift;
이 클래스는 다른 패키지에 위치하는게 더 좋을것 같습니다. :)

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    private MessageSource messageSource;
사용하지 않는 의존성은 제거해주세요~

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    private final ProductService productService;
controller에서 dao와 service를 모두 의존해야할 필요가 있을까요?

계층간 역할이 분명하도록 의존성을 정리해주시면 좋을것 같습니다. 😄

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +        productDao.insertProduct(product);
이러한 일련의 흐름은 controller가 아닌 다른 클래스에 위치하는게 더 좋을것 같습니다. 😄

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    }
Exception을 핸들링하는 ExceptionHandler는 다른 XXXMapping과 그 성격이 다른것 같습니다.

Controller가 아닌 별도의 클래스에서 관리해보면 좋을것 같습니다.

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +        return "Update Success";
이러한 응답을 하는 이유가 있을까요? 🤔

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/ProductDao.java
> +    }
이와 같은 부분은 sql 파일로 관리할 수 있으니 참고해주세요~

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/ProductDao.java
> +    public boolean checkProduct(long id) {
check 라는 네이밍은 boolean이라는 응답을 한다는 예상보다 void 형태로 exception을 throw하는데 더 많이 사용되는것으로 보입니다.

is-, can-, has-, exist- 등의 다른 이름은 어떨까요?

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +        return "Not enough stock";
응답으로 String 문자열을 내보내는데요 

받은 응답을 이용해서 정상적으로 처리가 됐는지 판단하기 너무 힘든 문자열인것 같습니다.

조금 더 명확한 응답을 반환하는것이 좋을것 같습니다.

2024-07-03 14:01 UTC, pci2676 commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
???라고 해두셨는데 이유가 있을까요?

혹시 해당 properties가 무슨 의미인지 알고 계실까요?

2024-07-03 14:01 UTC, pci2676 commented on src/main/java/gift/Product.java
> +                      int amount) { }
👍 

조금 더 발전시켜서

위와 같은 검증은 클라이언트로부터 받는 객체에서만 수행하고

도메인 기능을 수행하는 도메인 객체에서는 값 객체의 개념을 도입해보시면 좋을것 같습니다.

Product의 name인 String을 하나의 값 객체로 도출해보시면 될 것 같습니다.

2024-07-03 15:31 UTC, ana-raka commented on src/main/java/gift/Product.java
> +package gift;
수정하였습니다 !

2024-07-03 15:31 UTC, ana-raka commented on src/main/java/gift/ProductController.java
> +package gift;
수정하였습니다 !

2024-07-03 15:31 UTC, ana-raka commented on src/main/java/gift/ProductDao.java
> +package gift;
수정하였습니다 !

2024-07-03 15:33 UTC, ana-raka commented on src/main/java/gift/ProductController.java
> +    private MessageSource messageSource;
수정하였습니다 !

2024-07-03 15:58 UTC, ana-raka commented on src/main/java/gift/ProductController.java
> +    private final ProductService productService;
의존성을 분리하여 Service에서 Dao를 호출하도록 변경하였습니다 !

2024-07-03 16:05 UTC, ana-raka commented on src/main/java/gift/ProductController.java
> +        return "Update Success";
막연하게 성공하면 그에 대한 결과를 리턴해줘야 한다고 생각했던 것 같습니다. 생각해보니 void로 변경해도 전혀 무관한 것 같습니다. 수정하였습니다 !

2024-07-03 16:13 UTC, ana-raka commented on src/main/java/gift/ProductDao.java
> +    public boolean checkProduct(long id) {
boolean 값을 리턴하는 함수의 경우 is~ 와 같은 식으로 작명하라는 것을 알고있었는데 신경을 쓰지 못하고 작성한 것 같습니다. 함수의 목적에 맞게 isProductInDB() 로 변경하였습니다.

2024-07-03 16:15 UTC, ana-raka commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
학습하는 과정에서 이해가 필요하다고 생각한 부분에 대한 주석이 그대로 남은 것 같습니다.  H2 데이터베이스의 콘솔을 활성화하는 것으로 알고있습니다. 필요없는 주석은 삭제하도록 하겠습니다 !

2024-07-03 16:25 UTC, ana-raka commented on src/main/java/gift/ProductController.java
> +    }
exception 패키지를 생성 후 분리하여 관리하도록 수정하였습니다.

2024-07-03 16:55 UTC, ana-raka commented on src/main/java/gift/ProductDao.java
> +    }
변경하였습니다 !

2024-07-04 01:52 UTC, ana-raka commented on src/main/java/gift/service/ProductService.java
> +        return "Not enough stock";
수정하였습니다 !

2024-07-04 13:41 UTC, pci2676 commented
> * return "Purchase successful";
>   }
>   return "Not enough stock";
>   에 대한 리턴으로 문자열을 Purchase successful, Purchase failed 이렇게 변경하였는데 이렇게 변경한 문자열은 주신 피드백에 부합한지 궁금합니다. 어떤 식으로 값을 리턴하는게 더 명확한 방식인지 궁금합니다. (ex) 최대한 간결하게 작성한다, 단어로만 표시한다....)

문자열을 이용하여 메서드가 어떠한 결과를 만들어냈는지 표현하는 방식이 적절하지 않습니다. 😓 

당장 true/false와 비교만 해도 해당 메서드를 사용하는 측에서 문자열을 비교하는 작업과 비교했을때 boolean의 비교가 더 쉽지 않을까요?

2024-07-04 13:43 UTC, pci2676 commented
> * Dao 관리 시에 테이블 생성을 sql파일을 따로 생성하여 관리하였는데, DDL의 경우에만 sql 파일을 생성하는 것인지 궁금합니다.

보통의 경우 그렇습니다.

다만 모든 경우에 그렇다고 하기는 어려울것 같습니다~

애플리케이션이 기동하였을때 초기에 필요한 데이터가 있다면 dml 또한 sql 파일로 관리할 수 있을것 같습니다.

2024-07-04 13:44 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +        return "Update Success";
클라이언트 측에서는 http status 만으로도 충분히 성공과 실패에 대한 인지를 할 수 있을것 같습니다. 😄

2024-07-04 13:45 UTC, pci2676 commented on src/main/java/gift/ProductDao.java
> +    public boolean checkProduct(long id) {
DB 라는 것이 메서드 이름에 포함되는 것은 엄청 좋다고 볼 수 는 없습니다.

DB에 저장하던 부분이 file이 될지 다른 시스템에서 불러올지 데이터를 가져오는 부분은 쉽게 변경될 수 있는 부분이기 때문입니다.

2024-07-04 13:46 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +        return "Not enough stock";
다른 comment에 남긴것 처럼 boolean을 이용하여 표현할 수 도 있고

별도의 응답 객체를 생성, 활용하여 표현할 수 있습니다.

지금과 같이 문자열은 이 메서드를 사용하는 클라이언트에서 사용하기에는 그리 적절하지 않은 형태입니다~

2024-07-04 13:47 UTC, pci2676 commented
> * 마지막 피드백은 제가 아직 학습이 부족하여 반영하지 못했습니다.. Step 2 진행하면서 반영하도록 하겠습니다.

네~ 이 부분은 step2에서 먼저 반영하여 commit으로 남겨주시면 좋을것 같습니다. 🤠

2024-07-04 13:58 UTC, pci2676 approved these changes
리뷰를 남겨두었으니 step2를 진행할때 함께 반영해주세요.

리뷰를 반영하기 어려운 부분이 있다면 멘토링을 신청해주세요!  
멘토링 일정이 맞지 않는다면 DM 주시면 일정을 조율할 수 있으니 참고해주세요.

2024-07-04 13:58 UTC, pci2676 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<String> addNewProduct(@Valid @RequestBody Product product) {
이전 단계부터 여러번 언급한 부분인데요.

Product를 요청 응답 객체와 데이터를 저장하는 데이터 모델 두가지 역할로 사용하고 있습니다.

이 부분은 step2에서 서로 다른 클래스로 역할을 나누어 구현해주세요.

2024-07-04 13:58 UTC, pci2676 commented on src/main/java/gift/controller/ProductController.java
> +        if ("Add successful".equals(result)) {
이 부분도 마찬가지로 Add successful과 같은 단어보다 booean이 해당 메서드를 사용하는 측에서 더 사용하기 쉬울것 같습니다.

문자열에 조금이라도 오타가 있다면 의도치 않는 응답을 할 수 있는 위험이 큽니다.

2024-07-04 13:58 UTC, pci2676 commented on src/main/resources/sql/createProductTable.sql
> +);
제 의도와는 조금 다르게 구현이 된것 같습니다~

google에 아래 키워드로 검색해보신 뒤 schema.sql을 만들어서 활용해보시면 좋을것 같습니다.

`spring schema.sql`

2024-07-04 13:58 UTC, pci2676 commented on src/main/java/gift/controller/ProductController.java
> +    @PutMapping("/{id}")
path variable을 사용하고 있지 않는것 같네요! 😢

2024-07-04 13:59 UTC, merged

2024-07-04 13:59 UTC, pci2676 commented
> * 파일 구조에 대해 찾아보면서 구조를 나누려하였는데 명확한 정답이 없는 느낌이었습니다. 혹시 제가 작성한 파일 구조가 올바른 구조인가요? 어떤 식으로 파일 구조를 구성하는게 좋은 방식인지 궁금합니다.

어떤 파일을 말씀하시는걸까요?

2024-07-05 03:34 UTC, ana-raka commented on src/main/java/gift/Product.java
> +                      int amount) { }
수정하였습니다 !

2024-07-05 03:34 UTC, ana-raka commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<String> addNewProduct(@Valid @RequestBody Product product) {
수정하였습니다 !

2024-07-05 03:42 UTC, ana-raka commented on src/main/java/gift/controller/ProductController.java
> +        if ("Add successful".equals(result)) {
수정하였습니다 ! 피드백 감사합니다. 넓게 생각하지 못한 것 같습니다

2024-07-05 03:47 UTC, ana-raka commented on src/main/java/gift/controller/ProductController.java
> +    @PutMapping("/{id}")
수정하였습니다 !

2024-07-05 04:16 UTC, ana-raka commented on src/main/resources/sql/createProductTable.sql
> +);
수정하였습니다 ! 감사합니다.