강원대 BE_김송목 2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #176
Opened 2024-07-03 13:54 UTC by kimsongmok

Postman에서는 잘 반환하는데 localhost에 보일방법을 잘 모르겠습니다.

2024-07-04 01:39 UTC, jaymarystella requested changes
안녕하세요 송목님.
머지가 좀 이상하게된거같은데 수정해주시거나 다시 PR보내주실수있으실까요?
이후에 다시 확인해볼게요

2024-07-04 01:39 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +  public ResponseEntity<Product> updateProduct(@PathVariable Long id, @Valid @RequestBody Product product) {
컨트롤러 내 로직들을 정의해주신 서비스내부로 정리해주세요. 컨트롤러는 얇게 유지하는게 좋습니다.

2024-07-04 01:39 UTC, jaymarystella commented on src/test/java/gift/ProductServiceTest.java
> -  private ProductRepository productRepository;
service가 왜 diff에 안잡힐까요? 브랜치머지가 조금 이상하게된거같아요.

2024-07-04 01:39 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
> +    if (name.contains("카카오")) {
setter 보다는 생성시 한번에 검증하면 어떨까요?

2024-07-04 01:39 UTC, jaymarystella commented
> Postman에서는 잘 반환하는데 localhost에 보일방법을 잘 모르겠습니다.

부연설명 좀 더 부탁드려요. 화면이 안나온다는 말씀이실까요?

2024-07-04 01:44 UTC, kimsongmok commented
네! 화면에 안나옵니다..!

2024-07-04 12:07 UTC, jaymarystella commented
<img width="1377" alt="스크린샷 2024-07-04 오후 9 07 08" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/151337670/37bc502d-ac2b-4f74-a35c-d7eae7a3b62c">
나오는거같은데요, 어느부분인지 부연설명을 좀 부탁드려요

2024-07-04 12:42 UTC, jaymarystella requested changes
안녕하세요 송목님.
안된다고 하셨던 부분은 제가 실행한 결과 남겨두었구요,
몇 가지 코멘트 남겨두었습니다. 구조관련해서 고쳐보시는게 의미가 있을거같아요.

2024-07-04 12:42 UTC, jaymarystella commented on src/main/java/gift/controller/ProductViewController.java
> +    }
exceptionHandler를 정의해주신부분에서 처리가 되면 더 좋을거같아요.

2024-07-04 12:42 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
>  @Entity
아직 JPA를 사용하는 미션은 아닌데 JdbcTemplate으로 고치시는걸 권고드려요

2024-07-04 12:43 UTC, jaymarystella commented
첫번째 남겨드린 피드백까지 같이 반영부탁드려요~

2024-07-04 12:54 UTC, kimsongmok commented
리뷰 감사합니다 멘토님 제가 말씀드린 화면이 표시 안된다 부분은 카카오를 썼을때, 혹은 허용되지 않은 특수 기호를 썼을때 문제가 되는 것을 postman에서는 반환을 잘 해주는데, localhost상에서는 그걸 썼을때, 제 코드 의도는 "상품 이름에 '카카오'를 포함하려면 담당 MD와 협의가 필요합니다." 이런 문구가 화면에 표시 되길원했는데, 잘 안되더라구요..! 혹시 이게 원래 구현이 안되나 해서요!

2024-07-04 13:05 UTC, kimsongmok commented
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/51540711/c65d4fe1-c0dc-4649-8e24-3a265b850fbc)
이렇게 치면
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/51540711/ae7220c1-7728-48de-b13d-e3c55986068b)
이렇게 나옵니다.
물론 에러를 유도한건 맞지만, 제가 의도한건 저 문구가 나오는거였습니다..!

2024-07-05 08:16 UTC, jaymarystella approved these changes
안녕하세요 송목님.
이거 다음단계때 꼭 반영해서 제출해주세요.

2024-07-05 08:16 UTC, merged