전남대 BE_박귷현 2주차 과제(step1)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #180
Opened 2024-07-03 14:43 UTC by pinkbeenyeti

2024-07-05 12:25 UTC, dc-choi requested changes
안녕하세요 규현님~ PR 리뷰를 확인하였습니다~

자세한 내용은 코멘트에 남겨두었습니다~! 확인 부탁드립니다.

질문을 남겨주셨는데 그에 대한 답변을 드리도록 하겠습니다!

> 계층의 분리가 올바르게 된 것인지 궁금합니다. 기존의 코드에서 제가 부족했던 점이 무엇이었는 지 생각을 해보니 컨트롤러에서 너무 많은 기능을 수행하고 있다고 느껴 각 기능 별로 분리하는 것에 초점을 맞추었습니다. 이전의 코드는 시간 부족으로 이번 과제처럼 아직 분리하지는 못했지만 빠른 시일 내에 할 예정입니다.

각 레이어의 역할이 무엇인지 고민해보시고 학습해주세요. 이 부분에 대한 내용은 코멘트에도 작성하였습니다!!

> 통일성 이전의 코드는 특히 클라이언트로 데이터를 보내는 방식이 너무 통일성이 없다고 생각했습니다. 이번에 일관성을 지키기 위해 노력했는데 잘 된 것인지 궁금합니다.

DTO를 나누는 기준에 대해서 고민을 해볼 필요가 있어보입니다. 각 EndPoint마다 DTO를 따로 둘 것이냐 하나의 ProductDTO를 두고 Product에 대한 요청은 전부 ProductDTO로 둘 것인지에 대한 고민이 필요해보입니다.

어려웠던 점에 대해서도 남겨주셨는데 그에 대한 답도 드리겠습니다!

> Basic 인증의 적용이 어려웠습니다. Basic 인증이 원활하지 않아 db에서 값을 가져 와 직접 비교하는 식으로 구현하였습니다.

어떤 부분에서 DB에서 값을 가져와 직접 비교하는지 코드로 찾을 수 없었습니다. Spring Security에 대해 좀 더 학습하실 필요가 있어보이십니다.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/controller/LoginController.java
> +@RequestMapping("/login")
step2 과제에서 요구하는 URL 주소로 다시 매핑시켜주세요.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/controller/RegisterController.java
> +@RequestMapping("/register")
step2 과제에서 요구하는 URL 주소로 다시 매핑시켜주세요.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +public class ProductController {
`Controller` 레이어의 역할에 대해서 고민해주세요. 지금은 모든 로직이 전부 `Controller`에 있습니다.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/controller/LoginController.java
> +        if (!userExists) {
에러처리에 대한 고민이 부족해보입니다. 스프링에서 예외처리를 어떻게 하는가에 대한 고민이 필요해보입니다.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/controller/LoginController.java
> +        if(validLogin) {
마찬가지로 에러처리에 대한 고민이 부족해보입니다. 스프링에서 예외처리를 어떻게 하는가에 대한 고민이 필요해보입니다.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/controller/RegisterController.java
> +        if (userExists) {
마찬가지로 에러처리에 대한 고민이 부족해보입니다. 스프링에서 예외처리를 어떻게 하는가에 대한 고민이 필요해보입니다.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/dto/ProductDTO.java
> +                         @Pattern(
이 부분에서 예외가 발생하면 어떤 예외 객체가 생성되나요?

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/exceptions/GlobalExceptionHandler.java
> +@ControllerAdvice
`@ControllerAdvice`란 무엇인가요?

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/exceptions/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
`GlobalExceptionHandler`로 모든 예외를 처리한다면 다른 로직에서 이 부분을 호출하기 위해서 어떻게 처리해야하는지에 대한 고민이 필요해보입니다.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/service/UserService.java
> +                .setSubject(user.email())
회원의 권한에 대한 부분이 누락되어 보입니다. 회원의 권한을 생각해주세요.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/service/UserService.java
> +        String secretKey = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
`secretKey`는 원칙적으로 노출이 되면 안됩니다. JWT를 생성하고 암호화하는 Key라서 유출되는 경우 보안에 위험합니다. 참고하세요.

2024-07-05 12:25 UTC, dc-choi commented on src/main/resources/schema.sql
> +CREATE TABLE USERS (
회원의 권한에 대한 부분이 누락되어 보입니다. 회원의 권한을 생각해주세요.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +        List<Product> products = getProducts();
DTO에 대한 고민이 필요해보입니다. 힌트를 드리자면 일반적으로 Request와 Response에 대한 DTO를 따로따로 선언합니다.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/exceptions/KakaoContainException.java
> +public class KakaoContainException extends RuntimeException{
이 객체는 카카오라는 이름을 사용했을 경우에만 예외 처리가 가능해보이는 네이밍입니다. 좀 더 포괄적인 이름으로 변경해주시고 그 안의 메시지에서 어떤 오류를 발생시키는지에 대한 처리가 필요해보입니다.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/repository/UserRepository.java
> +        Integer count = jdbcTemplate.queryForObject(sql, new Object[]{email}, Integer.class);
`queryForObject()`에서 0이나 1을 초과하는 행을 반환하게 되면 Exception을 발생시킵니다. try/catch로 감싸는게 필요해보입니다.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/service/AuthService.java
> +        UserDTO realUser = userRepository.selectUser(userDTO.email());
DTO와 Entity에 대한 고민이 필요해보입니다. DTO와 Entity의 변환은 어디서 이루어져야 한다고 생각하나요?

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/repository/UserRepository.java
> +    public Optional<Integer> countUsers(String email) {
`Optional`을 사용하려는 시도는 좋았습니다!

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/exceptions/GlobalExceptionHandler.java
> +        ex.getBindingResult().getAllErrors().forEach(error -> {
이 부분에서 첫번째 오류메세지를 꺼내서 사용할 수 있습니다. 조금 더 고민해주세요.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/controller/LoginController.java
> +    private final String emailErrorMessage = "존재하지 않는 이메일입니다.";
에러 메세지는 공통으로도 사용할 수 있어서 따로 객체를 만들어서 빼두는 걸 추천드립니다.

2024-07-05 12:25 UTC, dc-choi commented on src/main/java/gift/controller/RegisterController.java
> +    private final String erroeMessage = "이미 가입한 이메일입니다.";
에러 메세지는 공통으로도 사용할 수 있어서 따로 객체를 만들어서 빼두는 걸 추천드립니다.

2024-07-05 12:27 UTC, dc-choi commented on src/main/java/gift/repository/UserRepository.java
> +        Integer count = jdbcTemplate.queryForObject(userCountSql, new Object[]{email}, Integer.class);
`queryForObject()`에서 0이나 1을 초과하는 행을 반환하게 되면 Exception을 발생시킵니다. try/catch로 감싸는게 필요해보입니다.

2024-07-05 15:08 UTC, pinkbeenyeti commented on src/main/java/gift/controller/LoginController.java
> +@RequestMapping("/login")
@RequestMapping("/members/login")
위와 같이 완료했습니다!

2024-07-05 15:08 UTC, pinkbeenyeti commented on src/main/java/gift/controller/RegisterController.java
> +@RequestMapping("/register")
@RequestMapping("/members/register")
위와 같이 완료 했습니다!

2024-07-05 15:10 UTC, pinkbeenyeti commented on src/main/java/gift/repository/UserRepository.java
> +    public Optional<Integer> countUsers(String email) {
감사합니다!

2024-07-05 15:29 UTC, pinkbeenyeti commented on src/main/java/gift/controller/LoginController.java
> +    private final String emailErrorMessage = "존재하지 않는 이메일입니다.";
package gift.common;

public class ErrorMessage {
    private ErrorMessage(){}

    public static final String emailAlreadyExists = "이미 가입한 이메일입니다.";
    public static final String emailInvalid = "존재하지 않는 이메일입니다.";
    public static final String passwordInvalid = "잘못된 비밀번호입니다.";

}

위와 같이 객체를 따로 만들고 공통으로 사용할 수 있도록 static으로 지정하였습니다. 또한 생성자의 접근 제어자를 private으로 할당하여  외부에서 인스턴스를 만들지 않고 사용하도록 강제하였습니다!

2024-07-05 15:29 UTC, pinkbeenyeti commented on src/main/java/gift/controller/RegisterController.java
> +    private final String erroeMessage = "이미 가입한 이메일입니다.";
위와 같습니다! 감사합니다!

2024-07-05 15:31 UTC, pinkbeenyeti commented on src/main/java/gift/service/AuthService.java
> +        UserDTO realUser = userRepository.selectUser(userDTO.email());
아하 서비스에서 변환을 하는 것이 아닌 레포지토리에서 직접 변환을 하고 있습니다. 수정하겠습니다!

2024-07-05 15:56 UTC, pinkbeenyeti commented on src/main/java/gift/dto/ProductDTO.java
> +                         @Pattern(
MethodArgumentNotValidException이 생성되는 것으로 알고 있습니다!

2024-07-05 15:59 UTC, pinkbeenyeti commented on src/main/java/gift/exceptions/GlobalExceptionHandler.java
> +@ControllerAdvice
SPRING에서 제공하는 애플리케이션 내 모든 컨트롤러에서 발생하는 예외를 처리하게 해주는 기능이라고 알고 있습니다!

2024-07-05 16:32 UTC, pinkbeenyeti commented on src/main/java/gift/service/UserService.java
> +        String secretKey = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
application.properties에 jwt.secretKey=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
이라는 속성을 추가하고

@Value("${jwt.secretKey}")
 private String secretKey;

@Value를 사용하여 appication.properties에 있는 jwt.secretKey에 있는 값을 가져와 변수 secretKey에 할당하는 식으로 구현해 보았습니다!

2024-07-06 15:19 UTC, pinkbeenyeti commented on src/main/resources/schema.sql
> +CREATE TABLE USERS (
```
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
    role VARCHAR(50) NOT NULL,
    CHECK (role IN ('user', 'admin', 'collaborator'))
);
```
회원의 역할을 추가하기 위해 role이라는 colum을 추가하고 일반 사용자, 관리자, 관리자에게 권한 허가를 받은 협력자로 역할을 구분하기 위해 제한을 두었습니다!

2024-07-06 15:29 UTC, pinkbeenyeti commented on src/main/java/gift/exceptions/KakaoContainException.java
> +public class KakaoContainException extends RuntimeException{
```
package gift.exceptions;

public class InvalidNameException extends RuntimeException{
    public InvalidNameException(String message) {
        super(message);
    }
}
```

위와 같이 유효하지 않은 이름일 경우 예외를 출력하는 클래스임을 나타내도록 변경하였습니다!

2024-07-06 15:53 UTC, pinkbeenyeti commented on src/main/java/gift/service/UserService.java
> +                .setSubject(user.email())
```
    public TokenDTO makeToken(UserDTO userDTO) {
        String accessToken = Jwts.builder()
                .setSubject(userDTO.email())
                .claim("role", "user")
                .signWith(Keys.hmacShaKeyFor(secretKey.getBytes()))
                .compact();

        return new TokenDTO(accessToken);
    
```
claim 메서드를 통해 role이라는 키에 user이라는 값을 넣어 회원의 권한이 user에만 있도록 설정했습니다!

2024-07-06 15:55 UTC, pinkbeenyeti commented on src/main/java/gift/exceptions/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
@ControllerAdvice를 통해 SPRING에서 제공하는 애플리케이션 내 모든 컨트롤러에서 발생하는 예외를 처리하게 되므로 컨트롤러에서 발생하는 예외에 대한 처리 메서드를 추가하면 될까요?

2024-07-06 17:00 UTC, pinkbeenyeti commented on src/main/java/gift/controller/ProductController.java
> +public class ProductController {
user와 마찬가지로 컨트롤러, 레포지토리, 서비스로 분리하여 구현하였습니다!

2024-07-06 17:41 UTC, pinkbeenyeti commented on src/main/java/gift/controller/LoginController.java
> +        if (!userExists) {
다음과 같이 변경해 보았습니다!

```
@PostMapping
    public ResponseEntity<?> loginUser(@Valid @RequestBody UserDTO userDTO) {
        authService.redundantUser("login", userDTO);
        authService.comparePassword(userDTO);

        return new ResponseEntity<>(authService.makeToken(userDTO), HttpStatus.OK);
    }
```

```
public void redundantUser(String state, UserDTO userDTO) {
        boolean userExists = userRepository.countUsers(userDTO.email()).orElse(0) > 0;

        if (state.equals("login") & !userExists) {
            throw new InvalidUserException(ErrorMessage.emailNotExists);
        }

        if (state.equals("regist") & userExists) {
            throw new InvalidUserException(ErrorMessage.emailAlreadyExists);
        }
    }
```

2024-07-06 17:42 UTC, pinkbeenyeti commented on src/main/java/gift/controller/LoginController.java
> +        if(validLogin) {
위와 마찬가지로 변경하였습니다!

```
public void comparePassword(UserDTO userDTO) {
        User realUser = userRepository.selectUser(userDTO.email());
        if(!realUser.getPassword().equals(userDTO.password())) {
            throw new InvalidUserException(ErrorMessage.passwordInvalid);
        }
    }
```

2024-07-06 17:42 UTC, pinkbeenyeti commented on src/main/java/gift/controller/RegisterController.java
> +        if (userExists) {
변경하였습니다!

```
@PostMapping
    public ResponseEntity<?> registUser(@Valid @RequestBody UserDTO userDTO) {
        authService.redundantUser("regist", userDTO);

        userService.createUser(userDTO);
        TokenDTO token = authService.makeToken(userDTO);
        return new ResponseEntity<>(token, HttpStatus.OK);
    }
```

2024-07-06 17:45 UTC, pinkbeenyeti commented on src/main/java/gift/controller/ProductController.java
> +        List<Product> products = getProducts();
ProductService 계층을 통해 DTO를 받을 수 있도록 하였습니다!

```
    @GetMapping
    public String getAllProducts(Model model) {
        ProductsDTO products = productService.getAllProducts();
        model.addAttribute("products", products);
        retu
```rn "manage";
    }

ProductsDTO 객체입니다.
```
public record ProductsDTO(List<Product> productDTOList) {
}
```

2024-07-06 18:22 UTC, pinkbeenyeti commented on src/main/java/gift/exceptions/GlobalExceptionHandler.java
> +        ex.getBindingResult().getAllErrors().forEach(error -> {
```
 @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<Map<String, String>> handleInvalidNameExceptions(MethodArgumentNotValidException ex) {
        Map<String, String> error = new HashMap<>();

        String errorMessage = ex.getBindingResult()
                .getAllErrors()
                .get(0)
                .getDefaultMessage();

        error.put("message", errorMessage);
        return new ResponseEntity<>(error, HttpStatus.BAD_REQUEST);
    }
```

첫 번째 객체를 가져와 ObjectError 타입의 메서드인 getDefaultMessage()를 사용하여 원하던 에러 메시지를 가져와 응답하는 식으로 변경하였습니다!

2024-07-06 18:25 UTC, pinkbeenyeti commented on src/main/java/gift/repository/UserRepository.java
> +        Integer count = jdbcTemplate.queryForObject(sql, new Object[]{email}, Integer.class);
```
public Optional<Integer> countUsers(String email) {
        try {
            Integer count = jdbcTemplate.queryForObject(userCountSql, new Object[]{email}, Integer.class);
            return Optional.ofNullable(count);
        } catch (EmptyResultDataAccessException e) {
            return Optional.of(0);
        } catch (IncorrectResultSizeDataAccessException e) {
            return Optional.empty();
        }
    }
```

수정하였습니다!

2024-07-07 05:46 UTC, pinkbeenyeti commented on src/main/java/gift/controller/ProductController.java
> +        List<Product> products = getProducts();
또한 제가 이해한 것이 맞는 지 궁금합니다. 예를 들어 ProductRequestDTO와 ProductResponseDTO로 나누는 이유는 요청을 받을 때는 각 필드에 대한 검증이 필요하지만 응답을 할 때는 DB에서 받아오므로 검증을 굳이 할 필요가 없어 사용하는 것인 지 여쭤보고 싶습니다!

2024-07-08 01:54 UTC, dc-choi requested changes
규현님~! 정말 고생하셨어요... 전주랑 다른 사람이 코딩한 수준으로 완전 열심히 하셨네요...

코멘트 달아주신 부분은 아래 하단 코멘트에 적어두었습니다~!

그 부분만 수정되면 바로 승인하도록 할게요~!

2024-07-08 01:54 UTC, dc-choi commented on src/main/java/gift/annotation/LoginUserArgumentResolver.java
> +        return parameter.hasParameterAnnotation(LoginUser.class) && parameter.getParameterType().equals(User.class);
`parameter.getParameterType().equals(User.class)`를 아래처럼 변경해주세요.

`User.class.isAssignableFrom(parameter.getParameterType())`

2024-07-08 01:54 UTC, dc-choi commented on src/main/java/gift/exceptions/InvalidNameException.java
> +public class InvalidNameException extends RuntimeException{
`InvalidNameException`, `InvalidUserException`, `UserNotFoundException`을 공통의 객체를 사용해서 처리하는건 어떻게 생각하시나요?

`CustomException`으로 처리를 하고 그 안에 메시지로 구분을 하는 것이 유지보수성에 더 좋아보입니다~!

물론 이건 나중에 하셔도 됩니다.

2024-07-08 03:09 UTC, pinkbeenyeti commented on src/main/java/gift/annotation/LoginUserArgumentResolver.java
> +        return parameter.hasParameterAnnotation(LoginUser.class) && parameter.getParameterType().equals(User.class);
변경 완료했습니다!

2024-07-08 03:20 UTC, dc-choi approved these changes
규현님~! step3까지 과제 구현하시느라 고생하셨습니다~!

수고하셨습니다! 3주차도 파이팅~!

2024-07-08 03:20 UTC, merged

2024-07-08 03:20 UTC, pinkbeenyeti commented on src/main/java/gift/exceptions/InvalidNameException.java
> +public class InvalidNameException extends RuntimeException{
예외 상황이 많아질 수록 예외 객체가 많아지고, GlobalHandler에서 처리해야 할 예외 객체 또한 많아지기 때문에 그러한 편이 유지보수성에 좋을 것 같습니다! 한 가지 질문사항이 있습니다.

` CustomException`으로 처리를 하고 그 안에 메시지로 구분을 할 때 메시지마다 보내려는 HTTP 상태 코드가 다른 상황인데 GlobalHandler가 이 메시지에 대한 구분을 어떻게 하면 좋을까요?

2024-07-08 03:23 UTC, dc-choi commented on src/main/java/gift/exceptions/InvalidNameException.java
> +public class InvalidNameException extends RuntimeException{
예외가 발생할 때 HTTP status 값을 보내줘서 `GlobalHandler`가 그 값을 처리하는 방식이면 될 거 같습니다~!

2024-07-08 06:06 UTC, pinkbeenyeti commented on src/main/java/gift/exceptions/InvalidNameException.java
> +public class InvalidNameException extends RuntimeException{
아하! 이해했습니다 감사합니다!