경북대 BE_안재민 2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #182
Opened 2024-07-03 15:00 UTC by dkswoals

## 2주차 1단계 PR 요청 드립니다! 
### 코드 리뷰 시, 멘토님이 중점적으로 리뷰해주셨으면 하는 부분
- 전체적인 코드 피드백 부탁드리겠습니다!

2024-07-04 14:01 UTC, leaf-upper requested changes
재민님 2주차 1단계 코드 고생 많으셨습니다.
코드를 너무 잘작성하셔서 별다른 수정할만한 부분이 안보이지만
몇가지 코멘트를 드렸습니다. 
확인해보시고 반영할만한 부분은 반영해주시고, 리뷰요청 주시면
Approve후 머지드리겠습니다.

2024-07-04 14:01 UTC, leaf-upper commented on src/main/java/wishlist/controller/ItemController.java
> +    public String getItemList(Model model) {
이건 참고하시면 좋을것 같아서 말씀드릴게요~
ViewName을 String을 통해 반환해도 되지만, ModelAndView을 통해서 반환도 가능합니다!
편하신 방식으로 코드 작성 부탁드려요

2024-07-04 14:01 UTC, leaf-upper commented on src/main/java/wishlist/controller/ItemController.java
> +            response.setStatus(HttpStatus.BAD_REQUEST.value());
RestControllerAdvice도 있지만, ControllerAdvice도 있어요~
ControllerAdvice는 예외상황에서 JSON이 아닌 View를 반환하기 용이합니다

2024-07-04 14:01 UTC, leaf-upper commented on src/main/java/wishlist/model/ItemForm.java
> +    @Pattern(regexp = "^(?!.*카카오).*$", message = "\"카카오\"가 포함된 문구는 담당 MD와 협의한 경우에만 사용 가능합니다.")
👍 👍  정규표현식 너무 잘작성해주셨네요~

2024-07-04 14:01 UTC, leaf-upper commented on src/test/java/wishlist/intergrationTest/ExceptionTest.java
> +    @CsvSource({
👍👍 테스트코드 너무 좋네요

2024-07-04 14:01 UTC, leaf-upper commented on src/main/java/wishlist/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(new ErrorResponseDTO(errorCode, errors), errorCode.getStatus());
요 handleException은 외부에서 호출할게 아니라면 private 접근제어가 좋을것 같아요

2024-07-04 14:01 UTC, leaf-upper commented on src/main/java/wishlist/controller/ItemController.java
> +    public String getUpdateForm(@PathVariable Long id, Model model) {
id도 기본적인 Validation을 해보는건 어떨까요? 
NotNull, 1이상 등등 여러가지 Validation을 해볼수 있을것 같아요~

2024-07-04 14:01 UTC, leaf-upper commented on src/main/java/wishlist/service/ItemService.java
> +    public List<Item> getList() {
findItem()은 ItemDto를 반환하고, getList()는 List<Item>을 반환하네요~
한가지로 통일하는건 어떨까요?
Java8의 함수형 기능인 stream을 이용해서 List<Item>을 List<ItemDTO>로 변경하여 반환해보는건 어떠세요?

2024-07-04 14:01 UTC, leaf-upper commented on src/main/java/wishlist/controller/ItemController.java
> +        HttpServletResponse response) {
ModelAndView를 사용하시면 HttpStatus도 설정할수있어요~

2024-07-04 15:18 UTC, dkswoals commented on src/main/java/wishlist/controller/ItemController.java
> +            response.setStatus(HttpStatus.BAD_REQUEST.value());
반영하였습니다!

2024-07-04 15:18 UTC, dkswoals commented on src/main/java/wishlist/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(new ErrorResponseDTO(errorCode, errors), errorCode.getStatus());
반영하였습니다!

2024-07-04 15:19 UTC, dkswoals commented on src/main/java/wishlist/service/ItemService.java
> +    public List<Item> getList() {
헉 간과하고 있었네요 감사합니다,,
반영하였습니다!!

2024-07-04 15:24 UTC, dkswoals commented on src/main/java/wishlist/controller/ItemController.java
> +    public String getItemList(Model model) {
하나 또 배우게 되네요 감사합니다!

2024-07-04 15:35 UTC, dkswoals commented
늦은 시간에도 좋은 피드백 너무 감사드립니다!!
## 궁금한 점
사실 전체적으로 주신 피드백처럼 Item 추가 및 수정 입력 유효성 검사 처리 후
검사 실패 시 입력 페이지 재 반환을 전역 처리기에서 처리하려 했으나
다음 단계인 step2에서 회원 가입 페이지 유효성 검사 실패 시에도 동일한 예외가 발생하여 동일 핸들러에서 처리됩니다...
각각 반환 되어야 할 View의 정보를 넘길 수 있는 좋은 방법이 있을까요?
 
 
```
 @ExceptionHandler(MethodArgumentNotValidException.class)
    public String handleMethodArgumentNotValidException(
        MethodArgumentNotValidException e) {
        return "create"; 
    }
```

2024-07-05 07:59 UTC, leaf-upper approved these changes
재민님 1단계 고생 많으셨습니다 
질문 주신거에 대한 답변은 저도 생각해보고 답변 드릴게요 ㅎ
2단계 진행 부탁드립니다!

2024-07-05 07:59 UTC, merged