부산대 BE_이풍헌 2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #197
Opened 2024-07-04 01:55 UTC by Awhn

#135  피드백 내용을 반영하여 0단계 코드를 수정하고, 유효성 검사를 수행하는 기능을 추가하였습니다.

2024-07-04 12:48 UTC, jaymarystella requested changes
안녕하세요 승환님.
2단계 구현하느라 고생많으셨어요.
몇 가지 코멘트 남겼는데 확인부탁드릴게요.

2024-07-04 12:48 UTC, jaymarystella commented on src/main/java/gift/AdminController.java
> +    @GetMapping("/del/{id}")
GetMapping과 더불어서 다른 애노테이션이 어떤것들이 있는지 살펴보시면 좋을거같습니다.

2024-07-04 12:48 UTC, jaymarystella commented on src/main/java/gift/AdminController.java
> +    @GetMapping("/del/{id}")
url path에 대해서도 어떻게 지으면 좋을지 여러 자료들을 찾아보심을 추천드립니다.

2024-07-04 12:48 UTC, jaymarystella commented on src/main/java/gift/AdminController.java
> +    @GetMapping("/edit/{id}")
이 부분도 마찬가지구요.

2024-07-04 12:48 UTC, jaymarystella commented on src/main/java/gift/ProductController.java
> +    }
컨트롤러마다 중복되는 처리를 어떻게 공통화하면 좋을까요?

2024-07-04 13:13 UTC, Awhn commented on src/main/java/gift/AdminController.java
> +    @GetMapping("/del/{id}")
HTML 폼에서 지원되는 메소드가 get과 post 밖에 없다고 생각하여서 위와 같이 작성하였습니다. 자료를 찾아보니 원하는 메소드로 변환할 수 있어, Delete의 경우 @DeleteMapping으로 값을 처리할 수 있게 변경하였습니다. 또한 URL 경로도 메소드가 명시된 경우 위 처럼 추가적인 동작을 명시하는 것을 불필요한 거 같아 삭제하였습니다.
https://stackoverflow.com/questions/24256051/delete-or-put-methods-in-thymeleaf

2024-07-04 13:13 UTC, Awhn commented on src/main/java/gift/AdminController.java
> +    @GetMapping("/edit/{id}")
현재 관리자 페이지에서 수정 버튼을 클릭한 경우, 해당 아이템의 수정 페이지를 보여주고 페이지 상의 폼에서 값을 입력 받아 수정하는 방법으로 구현하였습니다. 수정하는 버튼이 현재는 Post로 구현되어 있어서, 위와 같은 방법으로 PutMapping으로 변경하였습니다.
AJAX 없이 단순한 HTML 폼 기능만을 이용하여서 구현하고자 했는데, 다른 방법은 뭐가 있을까요?

2024-07-04 13:23 UTC, Awhn commented on src/main/java/gift/ProductController.java
> +    }
@ControllerAdvice 클래스를 만들어서 중복을 최소화 하였습니다.

2024-07-05 14:38 UTC, jaymarystella commented on src/main/java/gift/AdminController.java
> +    @GetMapping("/edit/{id}")
음 ajax가 필수요구사항이 아니면 어쩔수없네요. 개인적으로 뷰까지 그려주면서 응답을 내려주는 경우는 요새는거의 못본거같긴합니다.

2024-07-05 14:38 UTC, jaymarystella commented on src/main/java/gift/ProductController.java
> +    }
잘 찾아주셨습니다.

2024-07-05 14:38 UTC, jaymarystella approved these changes
안녕하세요 승환님.
리뷰 반영 잘 해주셨습니다.
다음 단계에서 뵙겠습니다.

2024-07-05 14:38 UTC, merged