부산대 BE 진서현 2주차 step2 PR 요청
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #198
Opened 2024-07-04 02:17 UTC by jinseohyun1228

READEME. md에 고민 내용을 담았습니다...

현재 로직이 복잡하고, 에러페이지를 따로 만들어야하는 등의 문제가 많습니다... 

리퀘스트 객체에 유효성 검사를 하도록 로직을 변경할 까 했지만, 제 고민을 공유하고 멘토님의 답변을 듣는 것이 더 도움이 될 것 같아 요청을 보냅니다..!!

감사합니다~!

2024-07-04 11:57 UTC, hocaron commented on src/main/java/gift/main/dto/ProductDto.java
> +@Data
@Data 어노테이션을 사용하신 이유가 궁금합니다💭

2024-07-04 11:59 UTC, hocaron commented on src/main/java/gift/main/error/ProductNameValidator.java
> +        if (name.isBlank() || name.length() > 15) {
빈문자열인 경우에 에러 메시지를 분리해도 좋을 것 같아요!

2024-07-04 12:11 UTC, hocaron commented on src/main/java/gift/main/repository/ProductDao.java
>                  "id BIGINT PRIMARY KEY," +
현재는 DB 에서 생성한 값이 아닌 키를 직접 생성해서 넣어주는 방식을 사용하고 있는데, 이유가 궁금합니다💭

2024-07-04 12:15 UTC, hocaron commented on src/main/java/gift/main/error/ProductError.java
> +public class ProductError extends IllegalArgumentException {
커스텀한 에러 좋습니다👍

해당 에러는 언제 발생하는 걸까요?!

2024-07-04 12:40 UTC, hocaron requested changes
서현님, 안녕하세요! 2주차 리뷰어 호선우에요.

같이 작업하는 사람으로서 궁금한 부분이 생겨 코멘트를 남겼습니다. 남은 목요일도 화이팅입니다💪💪💪

1.코드 컨벤션이 다른 부분이 있어서 인텔리제이의 Reformat 을 사용하여 정리할 수 있을 것 같아요.
2. 테스트 코드가 없어서 페이지에 들어가서 직접 기능 구현을 통해서만 결과를 볼 수 있어요🥲 테스트 코드와 Rest API 를 구현해보는 것은 어떨지 의견이 궁금해요.

2024-07-04 12:40 UTC, hocaron commented on src/main/java/gift/main/service/ProductService.java
> +    public void addProduct(@Valid ProductDto validProduct) {
요청값이 잘못된 부분은 요청이 들어오는 Controller 클래스에서 해도 좋을 것 같은데, 어떻게 생각하실까요?!😀

2024-07-04 12:40 UTC, hocaron commented on src/test/java/gift/main/handler/ProductValidatorTest.java
> +class ProductValidatorTest {
테스트 코드가 현재 없는 상태라 추가되면 좋을 것 같습니다.

2024-07-04 12:40 UTC, hocaron commented on src/main/java/gift/main/service/ProductService.java
> +            throw new IllegalArgumentException("해당 id는 없습니다.");
validation 좋습니다👍 해당 로직이 반복해서 사용되고 있어 공통 메서드로 분리해볼 수도 있겠네요!

2024-07-04 12:40 UTC, hocaron commented on src/main/java/gift/main/error/GlobalExceptionHandler.java
> +    }
에러 처리가 동일한 것 같은데, 핸들러를 분리한 이유가 궁금합니다.

2024-07-04 12:40 UTC, hocaron commented on README.md
> +멘토님은 어떻게 생각하시는지 궁금합니다..!!
입력값에 대한 validation 의 위치를 많이 고민하신 것 같아요. 저는 Controller 가 적절한다고 생각하는데 이유는 다음과 같습니다.

1.	입력 검증 책임 분리: 컨트롤러는 클라이언트로부터 받은 요청을 처리하는 첫 번째 레이어입니다. 입력 데이터를 검증하는 것은 이 레이어의 중요한 책임 중 하나입니다. 이를 통해 잘못된 데이터가 서비스 레이어에 도달하는 것을 방지할 수 있습니다.
2.	간결한 서비스 레이어 유지: 서비스 레이어는 비즈니스 로직을 처리하는 곳입니다. 입력 데이터 검증을 컨트롤러에서 처리하면, 서비스 레이어는 순수하게 비즈니스 로직에만 집중할 수 있어 코드가 간결해집니다.
3.	즉각적인 오류 응답: 잘못된 입력 데이터를 즉시 감지하고 클라이언트에 빠르게 피드백을 줄 수 있습니다. 컨트롤러에서 @Valid를 사용하면, 입력 데이터가 유효하지 않을 경우 적절한 응답(예: 400 Bad Request)을 즉시 반환할 수 있습니다.
4.	표준화된 입력 검증: Spring Framework에서는 @Valid와 같은 애노테이션을 이용해 입력 검증을 표준화된 방식으로 처리할 수 있습니다. 이는 컨트롤러 레이어에서 일관된 검증 로직을 적용하는 데 유리합니다.

2024-07-04 12:40 UTC, hocaron commented on src/main/java/gift/main/controller/AdminController.java
> +        return "product";
모든 Controller 의 결과로 product 문자열이 반환되는 것 같아요. 해당 문자열을 반환하는 이유가 궁금합니다.

2024-07-04 13:23 UTC, hocaron commented on src/main/java/gift/main/dto/ProductDto.java
> +    public ProductDto(ProductRequest productRequest) {
DTO 분리 좋습니다👍

2024-07-04 16:50 UTC, jinseohyun1228 commented on src/main/java/gift/main/dto/ProductDto.java
> +@Data
ModelAttribute어노테이션 적용이 되는지 궁금해서 썼다가 못지운 것 같습니다...앞으로는 확인 잘 하겠습니다!

2024-07-04 16:51 UTC, jinseohyun1228 commented on src/main/java/gift/main/error/ProductNameValidator.java
> +        if (name.isBlank() || name.length() > 15) {
넵! 반영했습니다!
저도 동일하게 생각합니다!

2024-07-04 16:52 UTC, jinseohyun1228 commented on src/main/java/gift/main/repository/ProductDao.java
>                  "id BIGINT PRIMARY KEY," +
앞선 단계에서 직접 전략 방법을 사용하고 있었고, 그 로직을 JDBC로 변경하다보니 데이터베이스의 전략을 선택할 생각은 미처 못한 것 같습니다. 반영했습니다!

2024-07-04 16:54 UTC, jinseohyun1228 commented on src/main/java/gift/main/error/ProductError.java
> +public class ProductError extends IllegalArgumentException {
ConstraintValidator에서 사용하고 싶었는데, 더 알아보니까 ConstraintValidator는 ConstraintValidatorContext 를 이용해서 에러를 반환하는게 적절하다고 해서, 사용하지 못했습니다..!

2024-07-04 17:00 UTC, jinseohyun1228 commented on src/test/java/gift/main/handler/ProductValidatorTest.java
> +class ProductValidatorTest {
넵! 
주말중으로 최대한 빨리 구현해보겠습니다.. !! 당장하고 싶기는 한데... step2과 step3구현이 내일 6시까지라서 테스트 코드는 주말중으로 하겠씁니다!

2024-07-05 03:14 UTC, hocaron commented on src/test/java/gift/main/handler/ProductValidatorTest.java
> +class ProductValidatorTest {
앗 마감기한이 있군요😢 화이팅 입니다💪

2024-07-05 04:02 UTC, hocaron commented on src/main/java/gift/main/repository/ProductDao.java
>                  "id BIGINT PRIMARY KEY," +
아핫! 현재는 단일 서버로 테스트하는 환경이고, AtonimicLong 을 통해 id 를 생성하고 있어서 다른 서버와 PK가 겹칠일이 없지만 추후에 오토스케링이 되는 환경에서 AtonimicLong 을 통해 id 를 생성하는 방식으로 가면 동일한 키가 발생할 수 있을 것 같아서 질문 드리게되었습니다😀

서현님은 이부분에 대해 어떻게 생각하실까요?!

2024-07-05 14:12 UTC, hocaron commented
서현님, 다음 step 에서 PR 이어나가겠습니다👍 해당 PR 은 머지하고, 리뷰 반영해야할 부분이 있다면 다음 PR 에서 반영부탁드릴게요!
코멘트에 대한 서현님의 생각은 공유해주시면 좋을 것 같습니다.

고생 많으셨습니다💪

2024-07-05 14:12 UTC, merged

2024-07-05 15:42 UTC, jinseohyun1228 commented on src/main/java/gift/main/error/GlobalExceptionHandler.java
> +    }
처음에는 에러마다 각각 다르게 구현하는 것이 맞다고 생각했습니다.

커스텀 에러도 처음에는 사용하려고 했었고, 각 상황에 맞는 에러 메시지나 구조가 있을 것으로 예상했습니다.
ex) id 입력시 오류-> 입력을 받는 컨트롤러 구조에 따라 적절히 헨들링...
하지만 실제로 구현하다보니까 발생하는 예외의 위치나, 종류를 기억하는 것은... 무리다..
표준화가 필요하다..
라고 생각이 들어 로직을 동일하게 처리했습니다.

그러다보니 하나로 묶을 수 있을텐데, 이렇게 처리하게 되었네요..!! 해당 내용 주말안으로 반영하겠습니다! 
step3에서 반영하겠습니다!!

2024-07-05 15:52 UTC, jinseohyun1228 commented on README.md
> +멘토님은 어떻게 생각하시는지 궁금합니다..!!
>입력 검증 책임 분리: 컨트롤러는 클라이언트로부터 받은 요청을 처리하는 첫 번째 레이어입니다. 입력 데이터를 검증하는 것은 이 레이어의 중요한 책임 중 하나입니다. 이를 통해 잘못된 데이터가 서비스 레이어에 도달하는 것을 방지할 수 있습니다.

저는 컨트롤러의 역할 중에 입력 데이터 검증이 있다고 생각 못했습니다.... 제가 잘못생각하고 있었던 부분을 알게되어서 너무 후련합니다... 컨트롤러 의 역할에 대해서 추가 공부를 하겠습니다.!


> 간결한 서비스 레이어 유지: 서비스 레이어는 비즈니스 로직을 처리하는 곳입니다. 입력 데이터 검증을 컨트롤러에서 처리하면, 서비스 레이어는 순수하게 비즈니스 로직에만 집중할 수 있어 코드가 간결해집니다.
즉각적인 오류 응답: 잘못된 입력 데이터를 즉시 감지하고 클라이언트에 빠르게 피드백을 줄 수 있습니다. 컨트롤러에서 @Valid를 사용하면, 입력 데이터가 유효하지 않을 경우 적절한 응답(예: 400 Bad Request)을 즉시 반환할 수 있습니다.

즉시 반환을 하는 것이 좋을 것 같습니다. 서비스 단 내부에 유효하지 않은 객체가 들어오는 것도 고민하면 좋았겠다는 생각이 듭니다..!! 

> 표준화된 입력 검증: Spring Framework에서는 @Valid와 같은 애노테이션을 이용해 입력 검증을 표준화된 방식으로 처리할 수 있습니다. 이는 컨트롤러 레이어에서 일관된 검증 로직을 적용하는 데 유리합니다.

사실 구현할때는 느끼지 못했는데 이후 단계에서 사용해보니까 정말 편리하다는 것을 알게되었습니다. 편리하다는 것말고도, 직접 구현하는 것이 아니라 믿음직한 제공..어노테이션을 쓰니까 더 안정성이 높아질 것 같구요!!

처음에는  "유효성 검증하는 곳이 잘 안보여서 안좋은거아니야?!,"  "왜 굳이 파라미터에서 받지? 너무 한계가 많은데?" 라고 생각했는데, 컨트롤러의 책임중 하나가 입력감 검증이라는 것을 아니 모든게 이해가 되고 납득이 됩니다!!

감사합니다!!

2024-07-05 16:02 UTC, hocaron commented on src/main/java/gift/main/error/GlobalExceptionHandler.java
> +    }
표준화가 필요할 것 같다는 생각의 시작이 좋네요👍 다음 스텝에서 확인하겠습니다!

2024-07-05 16:05 UTC, hocaron commented on README.md
> +멘토님은 어떻게 생각하시는지 궁금합니다..!!
정답은 없는 부분이라 편하게 들어주시면 좋을 것 같아요.

물론 저의 생각일 수도 있지만, 비즈니스 로직에 크게 관여하지 않는 잘못된 값들이 서비스 로직까지 침투할 필요가 있을까 에 대한 고민이  있습니다🤔 서비스 로직은 비즈니스 로직에 집중하여 응집도를 높일 수 있도록 요청을 받는 첫번째 계층인 Controller 에서 유효성 검증을 해보면 좋을 것 같다는 생각이 듭니다😀

2024-07-05 16:06 UTC, jinseohyun1228 commented on src/test/java/gift/main/handler/ProductValidatorTest.java
> +class ProductValidatorTest {
하핳 오히려 열심히 하게 되니 좋습니다~! 감사합니다.

2024-07-05 16:15 UTC, jinseohyun1228 commented
테스트 코드,,, 멘토님이 그동안 엄청 곤란하셨을 것 같다는 생각이 듭니다ㅏ...
최대한 빨리 반영하겠습니다. 

멘토링을 통해 이 코드가 나만 보는 게 아니구나.!! 나도 나름의 협업(?)중이구나!라고 느꼈습니다 .

앞으로는 더 누군가 본다는 생각으로..!! 👁️ 고민하면서 짜겠습니다 ㅎㅎ (눈 이모티콘이 무섭네요ㅜㅜ)

따라서 테스트 코드 얼른 짜도록 하겠습니다.. (첫번쨰로!!)

2024-07-05 16:17 UTC, jinseohyun1228 commented on src/main/java/gift/main/service/ProductService.java
> +    public void addProduct(@Valid ProductDto validProduct) {
핫 아래에서 변경해보았습니다!! 감사합니다.
제가 아직 깃이나 개발문화에 익숙하지 않아서,,, 코멘트를 안달거나,,, 하는 부분이 있습니다. 
얼른 적응을 해서 좋은 멘티가 되도록 하겠습니다~!

여기 코멘트 안달아서 죄송해요..!

2024-07-05 16:20 UTC, jinseohyun1228 commented on README.md
> +멘토님은 어떻게 생각하시는지 궁금합니다..!!
유효성 검사에도 비즈니스 로직에 가까운 부분과 그렇지 않은 부분이 있다는 점... 이 좋은 것 같습니다.
서비스 계층도 서비스 계층만의 할일인 비즈니스 로직이 있으니까요!

컨트롤러는 요청만받고 응답만 준다는 제 생각이 조금 아쉬웠다~라고 생각합니다 ㅎㅎ 

자세히 답변해주셔서 감사합니다.

2024-07-05 17:54 UTC, jinseohyun1228 commented on src/main/java/gift/main/repository/ProductDao.java
>                  "id BIGINT PRIMARY KEY," +
## 

오토스케일링은 제가 잘 몰라서 공부하고 답변을 다는 데 시간이 좀 걸렸습니다..!!

**`AtonimicLong` 를 사용 이유**

- 멀티 스레드 환경에서 안전하다고 해, 안전한 방법이라고 생각했기 때문입니다.

이유 :  여러 대의 서버에서 동작하는 상황을 생각하지 못했습니다.

제가 찾아본 내용입니다.

> **오토 스케일링**
> 
> - 클라우딩 컴퓨터의 기술 중 하나로 CPU, 사용자, 트레픽등에 따라 자원을 자동으로 할당해주는 기술이다.
> 
> **오토스케일링이 클라우딩 컴퓨팅의 핵심 기술인 이유** 
> 
> - 비용과 물리적인 한계로 많은 자원을 사용하기 어려운 상황에
>  클라우딩 컴퓨터로 물리적, 하드웨어적 한계잆이 많은 자원을 사용할 수 있다.

따라서 클라우딩 컴퓨팅으로 프로젝트를 돌린다면, 여러 서버에서 돌아갈 수 있고, 따라서 직접 키를 발급하는 것은 동일한 키가 발급될 수 있다는 문제점이 생길 것 같습니다.

***그런데 DB에 위임하면 이 문제가 해결되는지 더 궁금증이 생겼습니다…*** 

***-*** DB 도 동일하게 클라우딩 환경에서 돌아가기도 하니까요!!

검색를 통해, 클라우딩 환경에서 사용할 수있는   DB 기본키 전략이 있다는 것을 알게 되었습니다.

이런 DB의키전략을 사용한다면, 클라우딩 컴퓨팅 환경이나 멀티스레드 환경에서도 제약없이 사용할 수 있으니 좋을 것 같습니다!! 

---

클라우딩 컴퓨팅 환경은 제가 생각하지 못했던 부분입니다. 아마 이런 부분이 멘토님의 조언이 필요한 부분 같습니다. 제가 혼자 고민하는 것은 아쉬운 점이 많네요..!!

오토스케일링 검색으로 다양한 DB 키 발급 전략까지 공부하게 되어서 뿌듯하기도 하고 기쁩니다. 채빈이나 healthcheck등 리뷰를 통해 새로 알게 되는 개념과 용어들이 많아서 앞으로도 더 많이 배우고 싶습니다..ㅎㅎ

감사합니다!!

데이터 베이스 테이블 생성 코멘트도 얼른 달겠습니다.

2024-07-05 18:04 UTC, jinseohyun1228 commented on src/main/java/gift/main/service/ProductService.java
> +            throw new IllegalArgumentException("해당 id는 없습니다.");
넵 반영하겠습니다! 보통 이렇게 한 클래스에서 공통로직이 몇번 정도 반복되어야 메서드를 만드나요?