경북대 BE_박준석 2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #199
Opened 2024-07-04 02:21 UTC by Lucerna00

1주 차 이후의 변경 사항으로는 잘못된 상품 id로 GET할 시 사용자 정의 예외가 발생하도록 하였습니다. 그리고 validation 적용과 상품 추가를 할 시 200 OK 대신 201 Created를 반환하도록 하였습니다.

validation을 위한 정규표현식 작성과 getBindingResult와 stream으로 여러 개의 에러를 출력해 보는 과정이 어려웠습니다.

2024-07-04 16:53 UTC, gongdongho12 requested changes
가장 빠르게 올려주시는군요 🏃🏼

2024-07-04 16:53 UTC, gongdongho12 commented on src/main/java/gift/dto/ProductDTO.java
> +    @Pattern(regexp = "^[ㄱ-ㅎㅏ-ㅣ가-힣a-zA-Z0-9 ()\\[\\]+\\-&/_]*$", message = "특수 문자는 ( ), [ ], +, -, &, /, _ 만 가능합니다.")
특수 문자 말고도 한자 같은것도 사용 불가능한데 한글 숫자 영문대소문자도 메시지에 표현해주면 어떨까요?

2024-07-04 16:53 UTC, gongdongho12 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
에러 관리 편해졌죠?

2024-07-04 16:53 UTC, gongdongho12 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
근데 이 클래스는 controller에 있는게 나중에 컨트롤러 작업할 때, 에러 추가하기 용이하지 않을까요?
코드가 많아졌을 때를 대비해서요

이부분은 다른 레포들 찾아보면서 주로 어떤 패키지에 있는지 한번 훑어보면서 학습해보시면 좋을 것 같습니다

2024-07-04 16:53 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        repository.getProduct(id);
개별 오류가 메서드로 들어가서 깔끔하네요 👍🏼

2024-07-04 16:53 UTC, gongdongho12 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        problemDetail.setProperties(new HashMap<>(reasons));
이 방식이 나쁘지는 않은데 ProblemDetail의 detail 프로퍼티에 프론트에서 간단하게 alert 제공할 기본적인 멘트정도는 넣어주는게 좋지 않을까요?

2024-07-04 16:53 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.created(URI.create("/api/product" + addedProductDTO.id())).body(addedProductDTO);
created 사용 👍🏼 
그래도 가독성이 안좋아 질 수 있는데요 url 유틸같은거 만들어서 활용하면 어떨까요?

지금도 보시면 이 주소는 사실 `/api/products/${id}` 로 가야하지 않나요?
`/api/product/${id}` 가 아니라요

2024-07-04 16:53 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<ProductDTO> updateProduct(@PathVariable("id") long id, @Valid @RequestBody ProductDTO productDTO) {
이미ProductDTO 안에 id가 있는데 id를 중복해서 사용하는 감이 없지않아 있는 것 같아요
이부분 한번 고민해보시면 좋을 것 같아요

Put 말고도 Delete 에도 동일합니다

2024-07-04 18:14 UTC, Lucerna00 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
확실히 ControllerAdvice를 써보니 여러 에러를 한 번에 관리할 수 있다는 점이 좋았습니다.

handler 클래스 위치는 그 당시에도 많이 고민하였는데,
예외 처리와 관련되다 보니 보통 exception 패키지에 두는 것 같았습니다.
그러면 혹시 exception 패키지 내에 사용자 정의 예외를 모아두는 패키지를 만드는 것도 괜찮을까요?

2024-07-04 18:14 UTC, Lucerna00 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        problemDetail.setProperties(new HashMap<>(reasons));
수정하였습니다!

2024-07-04 18:19 UTC, Lucerna00 commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.created(URI.create("/api/product" + addedProductDTO.id())).body(addedProductDTO);
path와 DTO의 id로 url이 형성되므로 유틸을 따로 만들어도 전체적인 코드 길이가 크게 변하지 않을 것이라고 생각하였습니다.
그래서 일단 코드를 나누어 보았습니다.
```
String url = "/api/products/" + addedProductDTO.id();
return ResponseEntity.created(URI.create(url)).body(addedProductDTO);
```

2024-07-04 18:25 UTC, Lucerna00 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<ProductDTO> updateProduct(@PathVariable("id") long id, @Valid @RequestBody ProductDTO productDTO) {
상품의 id는 AUTO_INCREMENT라 관리자 페이지에선 이름, 가격, 사진 url만 입력하도록 하였습니다.
그래서 controller 단에서의 DTO에는 아직 상품 id가 없는 상태입니다.
1주 차 때의 피드백으로 service 단에서 PathVariable를 이용하여 완전체인 DTO를 만들어 처리하였는데, 이 과정을 controller에서 수행하면 될까요?

2024-07-05 18:31 UTC, gongdongho12 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
저는 공통요소중 상수, Exception 등을 한 패키지에 몰아두는걸 선호하긴 합니다
그런데 이런부분은 개발팀의 컨벤션이나 본인의 성향차이라 본인이 왜 여기다 둬야하는지 고민해보시면 좋을 것 같아요!

2024-07-05 18:32 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.created(URI.create("/api/product" + addedProductDTO.id())).body(addedProductDTO);
그게아니라 "/api/products" 자체를 BASE_PATH = "/api/product" 형식으로 상단에 선언하고 사용한다던가 등으로요

2024-07-05 18:33 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<ProductDTO> updateProduct(@PathVariable("id") long id, @Valid @RequestBody ProductDTO productDTO) {
아닙니다 내부 서비스 넘기는 파라미터에서 처리되면 충분하네요 👍🏼

2024-07-06 10:47 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.created(URI.create("/api/product" + addedProductDTO.id())).body(addedProductDTO);
제가 util이라고 말해서 헷갈리셨을 것 같네요 죄송합니다
변수로 클래스 상단에 이 클래스의 basePath에 대한 선언에 관한 이야기 입니다

2024-07-06 11:00 UTC, Lucerna00 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
네, 과제를 진행하며 advice와 exception 패키지에 대해 고민해 보겠습니다.

2024-07-06 11:01 UTC, Lucerna00 commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.created(URI.create("/api/product" + addedProductDTO.id())).body(addedProductDTO);
제가 유틸 클래스로만 생각하였던 것 같습니다.
말씀하신 대로 BASE_PATH 상수를 만들어 수정하였습니다.

2024-07-07 16:03 UTC, merged