경북대 BE_우현서 2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #200
Opened 2024-07-04 02:24 UTC by wndlthsk

안녕하세요, 멘토님!

1. GlobalExceptionHandler에 대해 깊게 이해가 안된 거 같아 제대로 작성했는지 모르겠습니다..! 또 강의 예시에서 ResponseEntity로 리턴하고 있고 검색해보니 ResponseEntity를 사용하는 예시가 많았는데 저도 수정하는 것이 더 좋을지 궁금합니다.
2. 오류 처리를 하면서 상품 추가 화면을 따로 분리하였습니다

2024-07-04 14:06 UTC, leaf-upper commented on src/main/java/gift/ProductAdminController.java
> +    public String addProduct(@Valid @ModelAttribute Product product) {
Product는 도메인 객체라서, 데이터를 바로 바인딩 받기 보다는
별도 Dto객체를 만들어서, 이를 변환하여 저장하는게 좋을것 같아요~!

ex) 
1. ProductRegisterRequestDto로 받아서 이를 Product로 변환.
2. ProductService에서 이를 저장.

2024-07-04 14:11 UTC, leaf-upper requested changes
안녕하세요 현서님~
Validation코드 및 관련 요구사항은 잘 작성해주신것 같아요
다만 계층별로 코드를 약간 분리해주시면 좋을것 같아요!
코멘트를 드렸는데 혹시 더 궁금하신 사항있으시면 답글 부탁드릴게요!

1. GlobalExceptionHandler에 대해 깊게 이해가 안된 거 같아 제대로 작성했는지 모르겠습니다..! 또 강의 예시에서 ResponseEntity로 리턴하고 있고 검색해보니 ResponseEntity를 사용하는 예시가 많았는데 저도 수정하는 것이 더 좋을지 궁금합니다.

GlobalExceptionHandler는 예외 계층을 만들어서 해당 계층에서 예외에 대해 일관화된 응답을 주기위해서 사용되어요.
만약 이런게 없다면 API별로 예외를 try~catch에서 응답을 만드는 식으로 코드를 작성해야할거에요

GlobalExceptionHandler에서 현재 작성해주신건 Validation 오류가 있을때 특정 form을 반환하는 코드인것 같아요. 이렇게 작성하셔도 문제는 없지만 전체적으로 사용되는 만큼 특정 view의 이름을 반환하는 로직은 확장성에 어려움을 겪을수 있을것 같습니다!

2024-07-04 14:11 UTC, leaf-upper commented on src/main/java/gift/ProductAdminController.java
> +    public String addProduct(@Valid @ModelAttribute Product product) {
Product는 도메인 객체라서, 데이터를 바로 바인딩 받기 보다는
별도 Dto객체를 만들어서, 이를 변환하여 저장하는게 좋을것 같아요~!

ex)

ProductRegisterRequestDto로 받아서 이를 Product로 변환.
ProductService에서 이를 저장.

2024-07-04 14:11 UTC, leaf-upper commented on src/main/java/gift/GlobalExceptionHandler.java
> +        String errorMessage = result.getFieldErrors().stream()
Java8 Stream기능은 정말 잘 사용해주셨네요 👍 👍

2024-07-04 14:11 UTC, leaf-upper commented on src/main/java/gift/GlobalExceptionHandler.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
혹시 모를 예외상황에 대비하기 위해 Exception 처리를 담당하는 메서드는 한개 있으면 좋을것 같아요~

ex)
@ExceptionHandler(Exception.class)
public String handleException(Exception e) {
}

2024-07-04 14:11 UTC, leaf-upper commented on src/main/java/gift/GlobalExceptionHandler.java
> +        return (referer != null && referer.contains("/update")) ? "product-form" : "add-product";
혹시 이 코드는 어떤 목적에서 이렇게 작성된걸지 여쭤봐도 될까요?

2024-07-04 14:28 UTC, wndlthsk commented on src/main/java/gift/GlobalExceptionHandler.java
> +        return (referer != null && referer.contains("/update")) ? "product-form" : "add-product";
@leaf-upper 추가 화면과 수정 화면이 달라서 오류가 생긴 경우에도 각각 화면으로 돌아가도록 하려고 했습니다!

2024-07-04 14:42 UTC, leaf-upper commented on src/main/java/gift/GlobalExceptionHandler.java
> +        return (referer != null && referer.contains("/update")) ? "product-form" : "add-product";
@wndlthsk 
현서님 제가 의미전달을 약간 부족하게 한것 같아요 ㅠ view를 반환하는게 확장성에 좋지 않다는건 아니였어요! 특정 view의 이름(product-form, add-product)를 일반적인 예외에서 잡아서 처리하는게 확장성에 좋지 않을것 같다는 의미였습니다 ㅎㅎ..
음 이렇게 생각해보면 좋을것 같아요 . 
MethodArgumentNotValidException은 되게 일반적인 예외인것 같아요 많은곳에서 사용될것 같은데
만약에 앞으로 폼이 더 많이 생긴다고 가정해보면, 정해진곳으로 돌아가기 위해서, 위 코드를 폼이 추가될때마다 작성해야할꺼에요~
이렇게 작성하기보다는 다른방식으로 원래폼으로 돌아갈수있는 방식이 있지 않을까요? 아니면 error view를 내려주는것도 좋은 선택이 될것 같아요!

2024-07-06 06:11 UTC, leaf-upper requested changes
현서님 2단계 고생많으셨습니다.
몇가지 코멘트와 질문을 남겨 드렸는데 확인해보시고 답변 주시면 좋을것 같아요~!
조금더 화이팅해봅시다!

2024-07-06 06:11 UTC, leaf-upper commented on src/main/java/gift/controller/MemberController.java
> +    public ResponseEntity<Object> register(@RequestBody Member memberDTO) {
1. Object 타입보단 명시적으로 String을 반환해주시면 좋을것 같아요~
2. Member에 대한 Validation은 필요가 없을까요?
3. 계층별로 DTO를 나눠서 코드를 작성하면 이후에 더 가독성이나 유지보수측면에서 좋을것 같아요!

2024-07-06 06:11 UTC, leaf-upper commented on src/main/java/gift/service/MemberService.java
> +//        if (memberDao.findByEmail(email) != null) {
회원가입하는데 필요한 정보가 늘어갈수록 해당 메서드의 파라미터 개수도 많아지겠네요
개선할수있을까요?

2024-07-06 06:11 UTC, leaf-upper commented on src/main/java/gift/service/MemberService.java
> +//        if (memberDao.findByEmail(email) != null) {
email에 대한 중복체크가 주석으로 작성되어있는것 같아요~ 왜 주석처리가 되었을까요?

2024-07-06 06:11 UTC, leaf-upper commented on src/main/java/gift/service/MemberService.java
> +    private String generateJwtToken(Member member) {
요런 재사용 할 수 있는  상수는 클래스 private 변수의 static final로 선언해주셔서 사용해주시면 좋을것 같아요!

2024-07-06 06:11 UTC, leaf-upper commented on src/main/java/gift/controller/MemberController.java
> +public class MemberController {
회원등록은 폼 형식으로 등록하시지 않으시고
REST API를 사용하셨네요~
RestController vs Controller의 차이점이 뭘까요?
어떤 방식이 더 좋은것 같으신지, 개발하기 편하신지에 대한 의견이 있을까요?

2024-07-06 06:11 UTC, leaf-upper commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(Exception.class)
메서드 이름은 동사로 시작하는게 좋을것 같습니다!.

2024-07-06 06:11 UTC, leaf-upper commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(Exception.class)
작성된 코드를 보니 ControllerAdvice보다는 RestControllerAdvice가 좀더 적합해보여요.
ControllerAdvice vs RestControllerAdvice
각 두개의 차이점이 뭘까요?

2024-07-06 06:11 UTC, leaf-upper commented on src/main/java/gift/service/ProductService.java
> +    public Long addProduct(ProductRegisterRequestDto productDto){
Member랑은 다르게 여기서는 Dto로 분리가 되어있네요~
코드 잘 작성해주셨습니다. 👍 
다른부분도 비슷하게 작성해주시면 좋을것 같아요

2024-07-06 08:16 UTC, wndlthsk commented on src/main/java/gift/service/MemberService.java
> +//        if (memberDao.findByEmail(email) != null) {
@leaf-upper Member 로 변경하고 주석처리 해제하는 걸 잊어서 .. 수정하겠습니다!

2024-07-06 08:19 UTC, wndlthsk commented on src/main/java/gift/controller/MemberController.java
> +public class MemberController {
@leaf-upper RestController는 json, Controller는 뷰를 반환한다고 알고 있습니다! 요구사항에  json으로 주고 받는 걸로 돼있어서 이렇게 했습니다.!

2024-07-06 08:26 UTC, wndlthsk commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(Exception.class)
@leaf-upper ControllerAdvice는 리턴 값의 뷰를 찾고 RestControllerAdvice는 리턴값을 json 으로 주는 걸로 이해하고 있습니다. step1에서는 뷰로 반환했어서 수정이 안된 거 같습니다

2024-07-07 07:37 UTC, leaf-upper commented on src/main/java/gift/config/WebConfig.java
> +    private JwtInterceptor jwtInterceptor;
Autowired보다는 생성자 기반 빈주입을 받는건 어떨까요?

2024-07-07 07:49 UTC, leaf-upper requested changes
안녕하세요 현서님
2단계 3단계 작성 고생 많으셨습니다~!
몇가지 더 코멘트를 남겨드렸어요 확인부탁드려요~!

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/config/WebConfig.java
> +    private JwtInterceptor jwtInterceptor;
Autowired보다는 생성자 기반 빈주입을 받는건 어떨까요?

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/controller/MemberController.java
> +    public ResponseEntity<String> register(@Valid @RequestBody MemberDto memberDTO) {
"회원가입 성공" 보다는 회원가입된 유저의 ID, Email등의 정보를 내려주는것도 좋을것 같아요~!

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/controller/ProductAdminController.java
> +        productService.addProduct(productDto);
👍👍

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/controller/WishController.java
> +    private WishDao wishDao;
이쪽도 생성자 기반으로 빈주입을 받아주시면 좋을것 같아요.
생성자를 기반으로 빈주입을 받으면, 내부 변수의 상태를 final로 관리하실 수 있습니다.

멤버변수를 final로 관리했을때 장점이 뭘까요?

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/dto/MemberDto.java
> +    private String password;
👍 👍

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/dto/ProductRegisterRequestDto.java
> +    private String name;
👍

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/interceptor/JwtInterceptor.java
> +            System.out.println("헤더 없어");
로그를 찍고 싶으실때는 표준입출력 방식의 로그보다는, Logger를 사용하셔서 찍을수 있어요.
Slf4j를 알아보시면 좋을것 같습니다

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/interceptor/JwtInterceptor.java
> +            response.getWriter().write("Authorization header가 없음.");
여기서 예외를 던져서 GlobalExceptionHandler에서 공통으로 처리할 수 있지 않을까요?

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/repository/WishDao.java
> +public class WishDao {
👍 Dao코드는 정말 깔끔하게 잘 작성해주셨네요

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/interceptor/JwtInterceptor.java
> +        final String token = header.substring(7);
7이라는 숫자는 너무 휴리스틱 한것 같아요. 다른방법으로 토큰을 조회할 수 있지 않을까요?

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/interceptor/JwtInterceptor.java
> +        request.setAttribute("claims", claims);
클레임 정보를 전부 Attribute에 넣기보다는 필요한 정보만 넣는게 좋을것 같아요

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/resolver/LoginMemberArgumentResolver.java
> +//        String header = webRequest.getHeader("Authorization");
사용하지 않는 주석 코드는 제거해주시면 좋을것 같아요!

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/util/JwtUtil.java
> +    private static String secretKey = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
secretKey에도 final 붙여볼수있지 않을까요?

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/util/JwtUtil.java
> +@Component
Util 클래스라면 꼭 스프링 빈으로 만들필요가 없을것 같아요~!

2024-07-07 07:49 UTC, leaf-upper commented on src/main/java/gift/util/JwtUtil.java
> +    public boolean validateToken(String token) {
이 메서드도 static으로 사용할 수 있지 않을까요?

2024-07-07 08:38 UTC, wndlthsk commented on src/main/java/gift/controller/WishController.java
> +    private WishDao wishDao;
@leaf-upper 객체가 생성된 후 변경되지 않아 더 안전합니다!

2024-07-07 10:07 UTC, leaf-upper commented on src/main/java/gift/controller/WishController.java
> +    private WishDao wishDao;
@wndlthsk 
네 맞아요~ final을 쓰면 객체에 대한 레퍼런스가 변경되지 않기 때문에 안전합니다.
단순 코드 실수부터, 안정성, 동시성 등등 여러부분에 대해서 장점이 있기때문에 final을 사용할 수 있는 경우 꼭 final을 사용해주세요~

2024-07-07 10:08 UTC, leaf-upper approved these changes
2주차 고생많으셨습니다 현서님~!
Approve 드릴게요 👍

2024-07-07 10:08 UTC, merged