강원대 BE_박지희 2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #205
Opened 2024-07-04 04:12 UTC by peacefullyquietly

2024-07-04 13:01 UTC, jaymarystella requested changes
안녕하세요 지희님
2단계 미션 고생하셨습니다.
코멘트 간단한것들 남겨두었는데 확인 후 의견 및 반영부탁드릴게요.

2024-07-04 13:01 UTC, jaymarystella commented on src/main/java/gift/controller/AdminController.java
> +    public ModelAndView addProduct(@ModelAttribute @Valid Product product, BindingResult bindingResult) {
> 과제 제출 후 해당 어노테이션은 요즘 잘 사용하지 않는 것이 트랜드라는 글을 보았습니다. 개발 트랜드는 웬만하면 따르는 것이 좋은가요?

어디서보신걸까요? 

일단은 Model로 처리로 가능하니 해당 방식으로 한번 수정해보시는것도 좋을듯하네요. 그리고 공식문서에서 권고가 된게 맞다면 따르는것이 좋습니다. 정말 필요가 없게되면 최신버전에서는 점차 없어지겠죠. 
개발트렌드라는게 정의하기 나름인데 저는 오피셜문서에의 권고사항은 따르는편이고 특정집단에서의 단순유행은 그렇게 비중은 두지 않습니다. 무조건 좋다 나쁘다는 한쪽으로 이야기하기힘드네요.

2024-07-04 13:01 UTC, jaymarystella commented on src/main/java/gift/controller/AdminController.java
> +        ModelAndView mav = new ModelAndView("create");
이것저것 사용해보시는것은 좋다고생각합니다.
ResponseEntity를 사용해보는것도 추천드립니다.

2024-07-04 13:01 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
> +    @Pattern(regexp = "^(?!.*카카오).*$", message = "'카카오'가 포함된 문구는 담당 MD와 협의 후 사용 바랍니다.")
다른 필드들은 검증이 필요없을까요?

2024-07-04 13:12 UTC, peacefullyquietly commented on src/main/java/gift/model/Product.java
> +    @Pattern(regexp = "^(?!.*카카오).*$", message = "'카카오'가 포함된 문구는 담당 MD와 협의 후 사용 바랍니다.")
수정해보겠습니다

2024-07-05 04:33 UTC, peacefullyquietly commented on src/main/java/gift/controller/AdminController.java
> +    public ModelAndView addProduct(@ModelAttribute @Valid Product product, BindingResult bindingResult) {
감사합니다!

2024-07-05 15:04 UTC, jaymarystella approved these changes
안녕하세요 지희님.
1단계는 이만 머지할게요. 부족한 부분은 2단계때 같이 남겨주시면 될거같아요.
고생하셨습니다.

2024-07-05 15:04 UTC, merged