충남대 BE_이은경 2주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #212
Opened 2024-07-04 06:12 UTC by pkyung

## 과제 진행
### 인증
- [x] 사용자 도메인 설계
- [x] 사용자 회원 가입 api
- [x] 사용자 로그인 - accessToken

2024-07-04 09:01 UTC, ksy90101 requested changes
2단계도 고생 많으셨습니다~
간단한 피드백을 남겼으니 확인해주시면 감사하겠습니다~
궁금한게 있다면 언제든 DM주세요!

2024-07-04 09:01 UTC, ksy90101 commented on src/main/java/gift/controller/LoginController.java
> +    @PostMapping("/token")
Login/token이 아니라 login이 어울리는 URL일거 같아요~

2024-07-04 09:01 UTC, ksy90101 commented on src/main/java/gift/controller/UserController.java
> +    @PostMapping("/user")
REST API규칙에선 리소스명을 복수로 씁니다.
users라고 쓰는게 더 어울릴거 같아요!

2024-07-04 09:01 UTC, ksy90101 commented on src/main/java/gift/controller/LoginController.java
> +@RequestMapping("/login")
여기도 실제 api일꺼 같으니 api를 붙이면 어덜까요?

2024-07-04 09:01 UTC, ksy90101 commented on src/main/java/gift/controller/LoginController.java
> +public class LoginController {
차후 Logout과 같은게 생긴다면 또 컨트롤러를 만들어야 할거 같아요.
좀더 응집도를 가지기 위해서 AuthController라고 인증에 대한 액션들을 모아둔다는 의미로 이름을 지어보면 어떨까요?

2024-07-04 09:01 UTC, ksy90101 commented on src/main/java/gift/dto/UserRequestDto.java
> +public class UserRequestDto {
Reqeust라고 쓸때는 DTO를 굳이 쓸필요는 없다고 생각해요.
Request라는것으로 DTO라는것을 의미하고 잇다고 생각합니다.

2024-07-04 09:01 UTC, ksy90101 commented on src/main/java/gift/exception/ProductExceptionHandler.java
> +public class ProductExceptionHandler {
👍

2024-07-04 09:01 UTC, ksy90101 commented on src/main/java/gift/jwt/JwtUtil.java
> +    private static final Key SECRET_KEY = Keys.hmacShaKeyFor("secret-key-secret-key-secret-key-secret-key".getBytes());
해당 키는 중요한 보안상 정보일 확률이 높습니다.

따라서 application.yml에 넣는 편인데요.

한번 @value에 대해서 알아보시면 좋을거 같습니다.

https://rutgo-letsgo.tistory.com/entry/Value%EC%99%80-ConfigurationProperties%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%B4-yaml-%ED%8C%8C%EC%9D%BC-%EB%A7%A4%ED%95%91%ED%95%98%EA%B8%B0

참고 링크 전달드려요!

2024-07-04 09:01 UTC, ksy90101 commented on src/main/java/gift/jwt/JwtUtil.java
> +                .setExpiration(new Date(System.currentTimeMillis() + 1000 * 60 * 60 * 10))
1000 * 60 * 60 * 10

해당 부분을 상수로 뺴서 의미를 전달하면 어떨까요?

2024-07-04 09:01 UTC, ksy90101 commented on src/main/java/gift/model/Product.java
> +    @NotEmpty(message = "상품 이름이 옳지 않습니다.")
MotEmpty가 Length랑 중복이지 않을까요?
한번 테스트 해보시면 좋을거 같아요.

이걸 빼도 빈값이 들어왔을때 문제가 안되는지요~

2024-07-04 09:01 UTC, ksy90101 commented on src/main/java/gift/service/LoginService.java
> +        if (user == null || !user.getPassword().equals(requestDto.getPassword())) {
user.getPassword().equals(requestDto.getPassword())
이런부분들은 도메인에게 직접 메시지를 던지는게 좋습니다.

user.matchPasswrod와 같은 메서드를 만들어 보면 어떨까요?

2024-07-04 09:01 UTC, ksy90101 commented on src/main/resources/schema.sql
> +    email VARCHAR(255) PRIMARY KEY,
email을 PK로 하신 이유가 따로 있나요?

2024-07-04 13:26 UTC, pkyung commented on src/main/java/gift/controller/LoginController.java
> +    @PostMapping("/token")
앗 요구사항에서 login/token으로 요청이 들어와서 이렇게 했습니다.

2024-07-04 13:56 UTC, pkyung commented on src/main/resources/schema.sql
> +    email VARCHAR(255) PRIMARY KEY,
email이 유일한 정보라고 생각했고, jwt 토큰을 생성할 때도 loginId인 email로 만들어서 pk로 지정했습니다.

2024-07-05 01:54 UTC, ksy90101 commented on src/main/java/gift/controller/LoginController.java
> +    @PostMapping("/token")
요구사항을 다시 한번 보시면 좋을거 같습니다~!
좀더 RESTful하게 URL을 작성해보시면 좋을거 같아요!

2024-07-05 02:01 UTC, ksy90101 requested changes
고생하셨습니다~
좀더 심화적인 내용들을 작성해봤어요!
한번 고민해보시고 궁금한게 있다면 언제든 DM주세요!

2024-07-05 02:01 UTC, ksy90101 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity putProduct(@RequestBody @Valid ProductRequest requestDto) {
변수명도 같이 변경하면 어떨까요?

2024-07-05 02:01 UTC, ksy90101 commented on src/main/java/gift/dto/LoginRequest.java
> +    private String email;
Email에 대한 Validate를 해보면 어떨까요?
잘못된 Email 형식이 들어온다면요~
1단계에서 Validate를 배웠으니 쉽게 가능할거라고 생각이 들어요!

2024-07-05 02:01 UTC, ksy90101 commented on src/main/java/gift/exception/UserAlreadyExistsException.java
> +public class UserAlreadyExistsException extends RuntimeException {
차후 excpetion이 많아 진다면 보기가 어려울거 같기도 해요.
패키지 구조를 한번 도메인별대로 가져가면 어떨까요?
user와 product를 패키지를 만들어서 관리하는거죠.
차후 그러면 찾기도 편할거 같아요~

2024-07-05 02:01 UTC, ksy90101 commented on src/main/java/gift/jwt/JwtUtil.java
> +    @Value("${jwt.secret-key}")
👍

2024-07-05 02:01 UTC, ksy90101 commented on src/main/resources/schema.sql
> +    email VARCHAR(255) PRIMARY KEY,
https://stackoverflow.com/questions/3804108/use-email-address-as-primary-key

한번 이글을 읽고 다시 한번 고민해보시면 좋을거 같습니다~

2024-07-05 02:01 UTC, ksy90101 commented on src/main/java/gift/service/AuthService.java
> +        if (user.getPassword().equals(inputPassword)) {
어.. 이런말씀이 아니라 user 객체에 메서드를 만들라는 이야기였어요~
도메인 로직으로요!

2024-07-05 02:01 UTC, ksy90101 commented on src/main/java/gift/repository/UserDao.java
> +    public User findByEmail(String email) {
한번 심화적인 내용으로 Optional을 써보면 어떨까요?
좀더 안정적인 코드가 될거 같기도 해요~

2024-07-05 02:43 UTC, ksy90101 requested changes
남긴 추가 리뷰 확인해주세요~

2024-07-05 03:14 UTC, ksy90101 approved these changes
2단계도 고생 많으셨습니다~
간단한 피드백을 남기긴 했는데 3단계에서 같이 고민해보시면 좋을거 같습니다~
언제든 질문이 있다면 DM주세요!

2024-07-05 03:14 UTC, ksy90101 commented on src/main/resources/schema.sql
> +    email VARCHAR(255) ,
이메일은 중복이 되면 안되도록 해둔거 같아요~
제약사항에서도 unique index를 써면 어떨가요!?

2024-07-05 03:14 UTC, ksy90101 commented on src/main/java/gift/model/User.java
> +        return false;
```suggestion
    return this.password.equals(password)
```
이런식으로 already return해도 될거 같아요!

2024-07-05 03:14 UTC, merged