부산대 BE_원윤서 2주차 과제 (Step2)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #216
Opened 2024-07-04 06:51 UTC by yoonsu0325

안녕하세요 멘토님 과제 step2 구현했습니다!
1. 현재 뷰를 모두 구현해두긴 했는데, API만 만들어도 되는건지 궁금합니다. 기능 요구사항에는 로그인 후 ResponseEntity를 반환해야하는데, 저는 로그인 한 뒤 메인 뷰로 리다이렉트되도록 해두어서... 그냥 뷰를 사용하지 않는 방향으로 고쳐야 할 지 모르겠습니다.

2024-07-04 14:48 UTC, yoo-jaein requested changes
step2 고생 많으셨습니다!
커밋 단위도 깔끔하고 리드미도 잘 작성해주셔서 이해하기 좋았어요.

step2와 별개로 ```System.out.println()```를 사용해서 로그를 출력하는 부분이 있는데요.
해당 코드를 지우거나, System.out.println() 대신 ```SLF4J```와 ```Logback``` 같은 로깅 프레임워크를 사용하는 것을 권장합니다.
프레임워크를 사용하면 이런 장점이 있습니다.
1. 로그 레벨 지정 가능 (DEBUG, INFO, WARN, ERROR 등..)
2. 로그 출력 형식을 바꾸거나 로그를 파일로 내보내는 등 다양한 커스텀 가능
3. println보다 성능이 좋음

### 질문
현재 뷰를 모두 구현해두긴 했는데, API만 만들어도 되는건지 궁금합니다. 기능 요구사항에는 로그인 후 ResponseEntity를 반환해야하는데, 저는 로그인 한 뒤 메인 뷰로 리다이렉트되도록 해두어서... 그냥 뷰를 사용하지 않는 방향으로 고쳐야 할 지 모르겠습니다.

### 답변
이번 주 과제의 주요 목적은 Restful API 구현이기 때문에, 뷰가 아닌 API 구현으로 수정 부탁드립니다! :)
만약 웹 페이지도 구현하고 싶다면 2단계 선택 과제인 회원을 조회, 추가, 수정, 삭제할 수 있는 관리자 화면을 만드시면 될 것 같아요!

2024-07-04 14:48 UTC, yoo-jaein commented on src/main/java/gift/user/JWTService.java
> +public class JWTService {
```JWTService```로 분리해서 토큰 생성 로직을 구현한 점이 좋네요! 👍

2024-07-04 14:48 UTC, yoo-jaein commented on src/main/java/gift/user/UserController.java
> +    private final JWTService jwtService;
여기 사이에 한 줄 띄워주시면 보기 깔끔할 것 같아요!

2024-07-04 14:48 UTC, yoo-jaein commented on src/main/java/gift/user/UserRepository.java
> +    private SimpleJdbcInsert simpleJdbcInsert;
여기도 한 줄 띄워주세요!

2024-07-04 14:48 UTC, yoo-jaein commented on src/main/resources/schema.sql
> +CREATE TABLE USERS (
유저 테이블도 잘 만들어주셨습니다!

2024-07-04 14:48 UTC, yoo-jaein commented on src/main/java/gift/user/UserService.java
> +//import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
여기 주석은 지워주세요!

2024-07-04 14:48 UTC, yoo-jaein commented on src/main/java/gift/user/UserRepository.java
> +            user = null;
사용자를 찾지 못했을 때 null을 반환하는 대신 적절한 예외를 던지는 방법도 있습니다.
```java
public User getUserByEmail(String email) {
    return userRepository.findByEmail(email)
        .orElseThrow(() -> new UserNotFoundException("User not found with email: " + email));
}
```

2024-07-05 07:01 UTC, yoonsu0325 commented
피드백 주신 부분 반영했습니다!
로그인과 회원가입부분은 API로 변경했고, 예외처리도 ControllerAdvice를 사용하는 방향으로 변경했습니다.
중간에 custom exception을 만드려다가 그냥 원래 있던 exception을 쓰기로 해서 최종 코드에는 없습니닷
또 JWT 토큰이 유효한 토큰인지 인증하는 로직 추가했습니다!

2024-07-05 09:29 UTC, yoo-jaein approved these changes
리뷰 반영하면서 코드 수정을 많이 하셨을 것 같은데 고생 많으셨습니다!!
step2 머지하겠습니다 :)

2024-07-05 09:29 UTC, merged