전남대 BE_박민규 2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #218
Opened 2024-07-04 07:07 UTC by ps9319

# 질문 
1. 정규표현식을 잘 몰라서 그냥 맨날 검색해서 찾아보면서 하는데 정규표현식을 외워야할까요??
2. valid를 사용했을 때 두 가지 검증에 실패했을 때 둘 중 하나의 예외가 랜덤으로 터지게 되는데 순서를 정해줄 방법이 있는지 궁금합니다!
ex) 
```
@Size(max = 15, message = "최대 15자까지 입력할 수 있습니다.")
@Pattern(regexp = "^(?!.*카카오)[a-zA-Z0-9()\\[\\]+\\-&/_]*$", message = "특수문자는 (), [], +, -, &, /, _ 만 가능합니다\n\"카카오\"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있습니다\"")
```
위와 같을 때 16자 이상이면서 (), [], +, -, &, /, _ 를 제외한 입력이 들어왔을 때 어떨 때는 Size에서 예외를 터트리고, 어떨 때는 Pattern에서 예외를 터트리더라구요. 그래서 Size에 대한 검증을 먼저 한 뒤, Pattern에 대한 검증을 하게 만드는 방법이 있는지 궁금합니다.
찾아봤더니 validated를 사용하고 인터페이스를 추가한 뒤, group을 추가하면 된다는데 이 과정은 복잡해보여서 혹시 다른 방법이 있는지 궁금합니다.
3. 추가 질문 :
```
@Pattern(regexp = "[a-zA-Z0-9()\\[\\]+\\-&/_]*$", message = "특수문자는 (), [], +, -, &, /, _ 만 가능합니다")
@Pattern(regexp = "^(?!.*카카오).*\n", message = "\"카카오\"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있습니다")
```
위와 비슷한 맥락의 질문입니다!
name 입력값에 카카오 라는 단어가 들어갔을 때에는 "\"카카오\"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있습니다"의 메세지를 띄우고, (), [], +, -, &, /, _ 를 제외한 특수문자가 들어갔을 때는 "특수문자는 (), [], +, -, &, /, _ 만 가능합니다"라는 메세지를 띄우고 싶었는데, 두 조건 중 하나가 일치하지 않았을 때 "특수문자는 (), [], +, -, &, /, _ 만 가능합니다"와 "\"카카오\"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있습니다"가 랜덤으로 에러 메세지로 나오더라구요... 카카오라는 단어가 들어갔을 때는 카카오 관련 에러 메세지를 띄워야하는데 특수문자 관련 에러 메세지가 뜰 때도 있어서 어떻게 해야할지 몰라서 그냥 두 조건을 합쳐 버렸는데 다른 방법이 있는지 궁금합니다 ㅠㅠ

2024-07-04 12:29 UTC, dc-choi reviewed
안녕하세요~ 민규님~

2주차 step1 진행하시느라 고생하셨습니다~

자세한 내용은 코멘트에 남겼습니다. 확인 부탁드립니다~

질문에 대한 답변을 드려보도록 하겠습니다~ 추가 질문이 있다면 언제든 편하게 말씀해주세요~

> 정규표현식을 잘 몰라서 그냥 맨날 검색해서 찾아보면서 하는데 정규표현식을 외워야할까요??

일일히 하나하나 다 외울 필요는 없고 그때그때 찾아보면서 하면 됩니다. 어떻게 동작하는지 원리만 이해하면 금방 알아볼 수 있습니다! (반복하다보면 자연스럽게 외워집니다.)

> 2, 3번 질문

비슷한 맥락에서의 질문이라고 생각하는데요. 이 부분에 대한 저의 생각을 코멘트에 적어보았습니다~ 확인 부탁드려요!

수고하셨습니다!

2024-07-04 12:29 UTC, dc-choi commented on src/main/java/gift/dto/requestDTO/ProductRequestDTO.java
> +    @NotBlank
`@NotBlank`와 `@NotEmpty`의 차이점을 알고 있으신가요?

2024-07-04 12:29 UTC, dc-choi commented on src/main/java/gift/dto/requestDTO/ProductRequestDTO.java
> +    @Pattern(regexp = "^(?!.*카카오)[a-zA-Z0-9()\\[\\]+\\-&/_]*$", message = "특수문자는 (), [], +, -, &, /, _ 만 가능합니다\n\"카카오\"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있습니다\"")
이 경우에는 특수문자, 카카오 둘 중 하나만 오류가 발생한 경우 찾아내기 어려워 보입니다.

커스텀 Validator를 사용해서 구현한다면 2, 3번에 대한 질문도 자연스럽게 해결할 것으로 보입니다!

참고할만한 블로그 보내드립니다~
https://mangkyu.tistory.com/206

2024-07-04 12:29 UTC, dc-choi commented on src/main/java/gift/dto/common/ApiResponse.java
> +public class ApiResponse<B> extends ResponseEntity<B> {
`ResponseEntity`를 한번 더 감싸신 이유가 있으신가요?

2024-07-04 12:29 UTC, dc-choi commented on src/main/java/gift/dto/common/ApiResponseGenerator.java
> +    public static ApiResponse<ApiResponseBody.SuccessBody<Void>> success(HttpStatus status, String message){
success()를 사용하는 부분이 없는데 혹시 필요한 부분이 있을까요?

2024-07-04 12:29 UTC, dc-choi commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
`MethodArgumentNotValidException`란 무엇이고 다른 예외는 무엇이 있을까요?

2024-07-04 12:29 UTC, dc-choi commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +@RestControllerAdvice
`@RestControllerAdvice`란 무엇인가요?

2024-07-04 12:29 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Long> addProduct(@Valid @RequestBody ProductRequestDTO productPostRequestDTO){
DTO에 대해서 고민이 필요할 것으로 보이는데 DTO란 무엇이고 어떻게 나누는 것이 좋아보이시나요?

2024-07-04 12:29 UTC, dc-choi commented on src/main/java/gift/dto/common/ApiResponseBody.java
> +public class ApiResponseBody {
`ApiResponseBody`의 경우 어떤 이유때문에 생성하였는지 궁금합니다.

`SuccessBody<D>`의 `private D data;`와 `FailureBody`의 `private String code;`의 차이점도 궁금해요!

2024-07-05 03:18 UTC, dc-choi requested changes
안녕하세요~ 민규님~ 알림이 가지않아 다시 작성해서 보내드립니다~

2주차 step1 진행하시느라 고생하셨습니다~

자세한 내용은 위 코멘트에 남겼습니다. 확인 부탁드립니다~

질문에 대한 답변을 드려보도록 하겠습니다~ 추가 질문이 있다면 언제든 편하게 말씀해주세요~

> 정규표현식을 잘 몰라서 그냥 맨날 검색해서 찾아보면서 하는데 정규표현식을 외워야할까요??

일일히 하나하나 다 외울 필요는 없고 그때그때 찾아보면서 하면 됩니다. 어떻게 동작하는지 원리만 이해하면 금방 알아볼 수 있습니다! (반복하다보면 자연스럽게 외워집니다.)

> 2, 3번 질문

비슷한 맥락에서의 질문이라고 생각하는데요. 이 부분에 대한 저의 생각을 코멘트에 적어보았습니다~ 확인 부탁드려요!

수고하셨습니다!

2024-07-05 04:24 UTC, ps9319 commented on src/main/java/gift/dto/requestDTO/ProductRequestDTO.java
> +    @NotBlank
넵 price에도 @NotBlank를 달았다가 오류가 나서 찾아보았었습니다.
- NotNull는 Null 값만을 체크하고,
- NotEmpty는 Null와 “”를 체크하고,
- NotBlank는 Null, “”, 공백을 포함한 빈 값을 체크합니다

2024-07-05 04:27 UTC, ps9319 commented on src/main/java/gift/dto/common/ApiResponseGenerator.java
> +    public static ApiResponse<ApiResponseBody.SuccessBody<Void>> success(HttpStatus status, String message){
나중에 혹시나 프론트와 통신할 일이 있을 때 쓰일 수 있을 것 같다고 생각해서 fail을 만든 김에 만들어놓았습니다!

2024-07-05 04:28 UTC, ps9319 commented on src/main/java/gift/dto/requestDTO/ProductRequestDTO.java
> +    @Pattern(regexp = "^(?!.*카카오)[a-zA-Z0-9()\\[\\]+\\-&/_]*$", message = "특수문자는 (), [], +, -, &, /, _ 만 가능합니다\n\"카카오\"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있습니다\"")
넵 보고 공부해서 구현해보겠습니다!

2024-07-05 04:51 UTC, ps9319 commented on src/main/java/gift/dto/common/ApiResponseBody.java
> +public class ApiResponseBody {
SuccessBody와 FailureBody를 한 곳에서 관리하고 싶어서 만들었습니다.
D data는 https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/218#discussion_r1666262080 와 같이 get요청했을 때 반환해줄 데이터를 보내주려고 해놓았고, code는 에러 코드를 보내주려고 만들었습니다. 
프론트와 통신할 때, message로도 어떤 에러인지 알 수 있지만 message는 언제나 바뀔 수 있어서("비밀번호가 옳지 않습니다", "비밀번호가 틀립니다." 등등..), 프론트가 구분할 때에는 message가 아니라 code로 해당 에러가 무슨 에러인지 구별할 수 있게 code도 보내주려고 했습니다.

2024-07-05 04:58 UTC, ps9319 commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +@RestControllerAdvice
전역적으로 예외를 처리할 수 있는 어노테이션입니다.
ControllerAdvice와 다른 점은 restcontroller와 controller와 다른 점과 마찬가지로 controlleradvice는 리턴값을 기준으로 view를 찾습니다.

2024-07-05 05:02 UTC, ps9319 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Long> addProduct(@Valid @RequestBody ProductRequestDTO productPostRequestDTO){
클라이언트와 서버가 데이터를 주고 받을 때 사용하는 객체입니다.
view를 기준으로 dto를 만드는 것 같습니다.
이번 에제에서 id 값은 수정할 수 없게 만든 것처럼 product에는 id가 있지만 사용자가 입력할 수 없으므로, productdto에는 id가 없습니다.

2024-07-05 05:13 UTC, dc-choi commented on src/main/java/gift/dto/requestDTO/ProductRequestDTO.java
> +    @Pattern(regexp = "^(?!.*카카오)[a-zA-Z0-9()\\[\\]+\\-&/_]*$", message = "특수문자는 (), [], +, -, &, /, _ 만 가능합니다\n\"카카오\"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있습니다\"")
하시다가 너무 시간을 많이 사용한다고 판단되시면 DM 주세요~! 자세히 같이 알아봐요~!

2024-07-05 05:23 UTC, ps9319 commented on src/main/java/gift/dto/common/ApiResponse.java
> +public class ApiResponse<B> extends ResponseEntity<B> {
음 사실 ResponseEntity를 커스텀한 것이니 상속해야겠다! 하고 썼었는데, 멘토님 말씀을 듣고 찾아보니 별로 쓰이지도 않는 것 같더라구요. 쓰지 않는 것이 좋을까요??

2024-07-05 05:40 UTC, dc-choi commented on src/main/java/gift/dto/common/ApiResponse.java
> +public class ApiResponse<B> extends ResponseEntity<B> {
네 추가적인 구현이 따로 없어보여서 딱히 의미가 없는거 같다고 생각이 들어서요! 수정해주시면 감사하겠습니다!

2024-07-05 05:44 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Long> addProduct(@Valid @RequestBody ProductRequestDTO productPostRequestDTO){
제가 생각하는 DTO에 대한 고민은 다음과 같아요.

1.  DTO의 변환은 어떤 계층에서 진행이 될까?
2. ProductDTO를 하나만 두거나 각각의 EndPoint마다 DTO를 하나씩 두는 것 중 어떻게 해야할까?
3. EndPoint마다 DTO를 두면 DTO가 너무 많아지는데 이것은 어떻게 관리해야 할까?

이런 고민을 하는거 같아요~ 같이 고민해봐요~

2024-07-05 07:41 UTC, ps9319 commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
Valid를 통과하지 못했을 때 발생하는 예외입니다!

또 표준 예외중 하나로 아래와 같은 예외가 있습니다.
illegalargumentexception : 메서드에 잘못된 인자가 넘어왔을 때 발생하는 예외

2024-07-05 07:43 UTC, dc-choi approved these changes
민규님 step1 과제 진행하시느라 고생하셨습니다~!

바로 step2 과제 해주시면 될 거 같습니다~! 수고하셨습니다!

2024-07-05 07:43 UTC, merged