충남대 BE_이동현 2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #219
Opened 2024-07-04 07:09 UTC by Thornappl2

2024-07-04 09:05 UTC, ksy90101 requested changes
1단계 고생 많으셨습니다~
간단한 피드백을 남겼으니 확인해보시면 좋을거 같습니다!
궁금한게 있다면 언제든 DM주세요!

2024-07-04 09:05 UTC, ksy90101 commented on src/main/java/gift/controller/ProductController.java
>      @PostMapping("/saveProduct")
여기도 굳이 save라는 이름을 쓸 필요 없어보입니다.

HTTP Method가 행위를 의미하거든요.

한번 HTTP Method에 대해서 공부해보시면 좋을거 같습니다~

2024-07-04 09:05 UTC, ksy90101 commented on src/main/java/gift/controller/ProductController.java
>      @GetMapping("/showFormForUpdate/{id}")
여기도 위에    @GetMapping("/products/new") 와 같은 방식으로 이름을 변경해보세요!

2024-07-04 09:05 UTC, ksy90101 commented on src/main/java/gift/controller/ProductController.java
> +    public String showFormForUpdate(@PathVariable long id, Model model) {
이때 long과 Long의 차이는 무엇일까요?

2024-07-04 09:05 UTC, ksy90101 commented on src/main/java/gift/model/Product.java
>      private int price;
boxedType에서 @NotNull이 의미가 있을까요?

2024-07-04 09:05 UTC, ksy90101 commented on src/main/java/gift/model/Product.java
>      private String imageUrl;
url에도 validate를 해보셨으니 URL 형식에 대해서도 한번 validate해보면 어떨까요?

2024-07-04 09:05 UTC, ksy90101 commented on src/main/java/gift/validation/ValidProductNameValidator.java
> +        return true;
지금 custom validate을 잘 만들어주셨는데요~
혹시 이부분을 기본 존재하는 어노테이션을 쓰는게 더 좋지 않을까요?

NotNull, Pattern, NotEmpty, Length를 쓰면 이렇게 복잡하게 안하고도 가능할거 같습니다!~

2024-07-04 13:38 UTC, Thornappl2 commented on src/main/java/gift/controller/ProductController.java
> +    public String showFormForUpdate(@PathVariable long id, Model model) {
long은 기본값이 0인 원시 타입, Long은 기본값이 null인 래퍼 클래스이기에, id는 0부터 시작하기에 long을 사용하는 것이 유리하다 생각했습니다

2024-07-04 13:38 UTC, Thornappl2 commented on src/main/java/gift/controller/ProductController.java
>      @PostMapping("/saveProduct")
넵 여러 가지 공부 후 메서드 이름들과 매핑 주소를 수정해보았습니다.

2024-07-08 01:44 UTC, Thornappl2 commented on src/main/java/gift/validation/ValidProductNameValidator.java
> +        return true;
수정 완료했습니다.

2024-07-08 01:46 UTC, Thornappl2 commented on src/main/java/gift/model/Product.java
>      private String imageUrl;
완료했습니다

2024-07-08 04:34 UTC, ksy90101 approved these changes
고생하셨습니다~ 2주차 2단계~3단계 PR이 이미 열렸으니 거기서 더 이야기 나눠요!

2024-07-08 04:34 UTC, ksy90101 commented on src/main/java/gift/validation/ValidProductNameValidator.java
> +            return false;
이부분도 정규표현식으로 충분히 가능할거 같아요~

2024-07-08 04:34 UTC, merged