전남대 BE_안재영_2주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #231
Opened 2024-07-04 09:41 UTC by ajy9851

요구사항대로 어떻게든 굴러가도록 만들긴 했는데 스프링에 대한 이해도가 너무 낮다보니 상당히 어려웠습니다...
회원가입 이후 DB에 저장된 email과 password가 api/login/token으로 들어오면 access-token을 응답합니다.

2024-07-04 12:00 UTC, gunom requested changes
안녕하세요 재영님~ 2단계 수고하셨습니다. 이제 막 배우기 시작하는 단계라 어려우실 수 있어요. 그래도 큰 틀에서는 잘 따라가고 계시니 이대로 열심히 공부하시면 좋을 듯 싶습니다! 몇 가지 리뷰 남겼으니 반영부탁드리고, 이해안되시는 부분있으면 리뷰나 멘토링 신청해주세요 👍 

Dto에 대해 한번 설명드리면 좋을 것 같아서 리뷰 남깁니다.
보통 Controller, Service, Repository별로 각각의 Dto를 사용하곤 합니다.
Controller에서는 Request와 Response에 대한 Dto를,
Service에서는 온전히 비즈니스 로직으로 사용가능한 Dto를 사용하여 Controller에 넘겨줍니다. 이를 통해 데이터베이스에서 직접적으로 다루는 데이터(Product)가 클라이언트에 노출되는 것을 막을 수 있습니다.
Dto를 사용함으로 불필요한 정보 노출을 줄이고 데이터를 보호하며, 책임 또한 분리할 수 있습니다! 추가로 공부해보시면 좋을 것 같아요!

2024-07-04 12:00 UTC, gunom commented on src/main/java/gift/controller/UserController.java
> +    public ResponseEntity<Void> register(@RequestBody UserRequestDTO userRequest) {
Dto는 그냥 UserRequestDto로 써도 됩니다 :)

2024-07-04 12:00 UTC, gunom commented on src/main/java/gift/controller/UserController.java
> +        Map<String, String> response = new HashMap<>();
accesstoken을 들고 있는 LoginResponse를 만들어 보는 건 어떨까요?

2024-07-04 12:00 UTC, gunom commented on src/main/java/gift/service/UserService.java
> +        User user = new User(userRequest.getEmail(), userRequest.getPassword());
이미 있는 유저인지 검증해보면 어떨까요? email을 기반으로 User가 존재하는 경우 DuplicateException을 내리면 더 좋은 기능이 될 거 같아요~

2024-07-04 12:00 UTC, gunom commented on src/main/java/gift/service/UserService.java
> +            return null;
이 부분도 null로 반환하지말고 Exception을 반환하면 어떨까요?

2024-07-04 12:00 UTC, gunom commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Object> createProduct(@Valid @RequestBody Product product) {
Object가 아닌 ProductDto의 리스트를 내리면 좋을 것 같아요~

2024-07-04 15:16 UTC, ajy9851 commented
최대한 지적해주신 부분 적용시켜보려고 했습니다! 감사합니다 ㅠㅠ

2024-07-06 09:04 UTC, gunom approved these changes

2024-07-06 09:04 UTC, merged