충남대 BE_김유겸 2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #245
Opened 2024-07-04 12:31 UTC by rladbrua0207

2024-07-05 01:53 UTC, Hyeon9mak requested changes
안녕하세요 유겸님~ 1단계 잘 진행해주셨어요.
테스트 코드를 단단히 잘 작성해주신 것도 인상적이네요~
질문주신 내용을 포함해서 몇 가지 간단한 코멘트 남겼으니 확인해주세요~

2024-07-05 01:53 UTC, Hyeon9mak commented on src/main/java/gift/exception/ApplicationException.java
> +    }
오호, 별도로 커스텀 exception 을 만드신 이유가 궁금해요~!

2024-07-05 01:53 UTC, Hyeon9mak commented on src/main/java/gift/exception/ExceptionControllerAdvice.java
> +    }
서비스를 운영하다보면 2개의 exception 외에도 여러가지 exception 이 발생할 수 있을텐데요,
그것들은 모두 어떻게 관리해줄수 있을까요?
모두에 대한 handler 를 만들어야만 할까요? 😱 
(hint: exception inheritance)

2024-07-05 01:53 UTC, Hyeon9mak commented on src/main/java/gift/product/presentation/request/ProductCreateRequest.java
>          Integer price,
특수문자, 허용되지 않는 문자의 경우 상품이름에 사용되지 않는 것이 보편적이므로 presentation 에서 표현해줄 수 있죠!
그러나 15자 제한, 카카오 prefix 는 유겸님이 만드시는 서비스만의 특성, 비즈니스 정책이라고 볼 수 있겠어요.
이것들은 presetation 대신 domain 계층에서 다루는 것이 어떨까요? 🤔 
동료 개발자가 비즈니스 정책 변경에 따라 코드를 수정하고자 할 때 더욱 빠르게 코드를 찾아내지 않을까요?

2024-07-05 01:53 UTC, Hyeon9mak commented on src/test/java/gift/product/presentation/ProductControllerTest.java
> +
> @Mockbean을 통해 repository의존성을 주입받으면 Mock객체로 실제 데이터베이스에 접근하는것이 아니라고 알고있습니다.

> 하지만 제 코드에서 Repository를 @MockBean으로 했을때엔 repository로 값을 조회하면 조회가 안되고 @Autowired로 할 경우에만 조회가 됩니다.

> 테스트코드에서 데이터를 삽입할때에도 mockMvc라는 mock객체를 통해 삽입하는데 왜 @Autowired로 했을때만 값이 조회하는지 이해가 안돼 질문드립니다!

어떤게 궁금하셔서 질문주신건지 한참 고민해보았는데, 아마도 `@MockBean` 의 컨셉에 대해 질문을 주신 것 같아요.
제가 이해한게 맞다면 유겸님께선 "`@MockBean` 을 사용할 경우, `ProductRepository` 를 대신 만들어주는데 왜 데이터 조회는 안될까요?" 라고 질문주신거 같아요.

아래가 실제 `@Autowired` 를 사용했을 때 `ProductRepository` 의 내부이고,

<img width="872" alt="SCR-20240705-jupe" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/37354145/28060306-f656-49cb-bbe9-45f973b8673f">

아래가 실제 `@MockBean` 를 사용했을 때 `ProductRepository` 의 내부입니다.

<img width="753" alt="SCR-20240705-jutv" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/37354145/da3ae8a8-c65e-442f-a635-1ec54fee27d0">

`@MockBean` 을 사용할 경우 `ProductRepository` 를 대신 구현해주는게 아니라,
`ProductRepository` 처럼 생긴 껍데기를 가져올 뿐이라 조회가 불가능하다고 볼 수 있겠네요.
(제가 잘못 이해했다면 조금 더 자세히 설명 부탁드려요 🙏 )

2024-07-05 01:53 UTC, Hyeon9mak commented on src/test/java/gift/product/presentation/ProductControllerTest.java
> +    void 이름에카카오포함시_상품생성시_잘못된요청응답반환() throws Exception {
테스트 코드를 엄청 꼼꼼히 작성해주셨네요~
혹시 테스트 코드 작성이 힘들진 않으셨나요?!
비즈니스 정책 관련 로직을 domain 객체로 분리하면 테스트 코드 작성이 한결 가벼워지실거라 기대됩니다 😄

2024-07-05 02:04 UTC, rladbrua0207 commented on src/main/java/gift/exception/ApplicationException.java
> +    }
> 오호, 별도로 커스텀 exception 을 만드신 이유가 궁금해요~!

우선 ControllerAdvice에서 ApplicationException의 자식 exception들을 별도로 관리하기 위함이 있구요.

프로젝트중 다양한 예외를 네이밍해 좀 더 코드를 이해하기 쉽게 하도록 하기위함입니다!

2024-07-05 02:05 UTC, rladbrua0207 commented on src/main/java/gift/exception/ExceptionControllerAdvice.java
> +    }
ApplicationException을 상속받아 다른exception에 대해서도 관리를 할 수 있다고 생각합니다!

2024-07-05 02:09 UTC, rladbrua0207 commented on src/main/java/gift/product/presentation/request/ProductCreateRequest.java
>          Integer price,
단순하게 request로 들어온 값에대해 presentation에서 예외처리를 해준다고 생각했는데 저의 서비스만의 특성이니까 분리를 해야겠군요! 

감사합니다!

2024-07-05 02:50 UTC, rladbrua0207 commented on src/test/java/gift/product/presentation/ProductControllerTest.java
> +    void 이름에카카오포함시_상품생성시_잘못된요청응답반환() throws Exception {
감사합니다 수정하겠습니다!

2024-07-05 03:04 UTC, rladbrua0207 commented on src/test/java/gift/product/presentation/ProductControllerTest.java
> +
제가 잘 이해하지 못해 설명도 빈약했던거같습니다..!

mockBean으로 등록돼있는 reposiory는 같은 테스트 메서드 안에서는 데이터베이스에 값이 들어간거로 인식하는것인줄 알았습니다!

하지만 그렇다고하더라도 mockMvc도 같은 Mock객체라고 생각하였는데 mockMvc를통해 값을 repository에 넣었을때 mockBean으로 등록된 repository로는 조회가 안되고, autowired로 등록된 repository로는 조회가 되는것을 확인했습니다.

mock객체는 단순히 껍데기를 가져온다고 한다면 mockMVC를 통해 값을 넣었을경우에도 autowired로 등록된 repository로 조회가 되지 않아야한다고 생각했습니다.

다음은 테스트가 통과한 코드 예제입니다.
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/48901587/cc7dfdfd-cd2f-4adb-98de-f98a0dd5192d)


추후에 찾아보니 mockMvc는 실제 컨트롤러와 상호작용을 하기때문이라는 사실을 알았습니다.

2024-07-06 03:14 UTC, Hyeon9mak approved these changes
안녕하세요 유겸님~ 1단계 피드백 잘 반영해주셨어요.
다음 단계 진행에 참고하실만한 코멘트 남겼습니다.
다음 단계에서 만나요~

2024-07-06 03:14 UTC, Hyeon9mak commented on src/main/java/gift/exception/ExceptionControllerAdvice.java
> +    }
ApplicationException 보다 상위 예외가 발생하면 어떤 일이 생기나요?

2024-07-06 03:14 UTC, Hyeon9mak commented on src/main/java/gift/product/domain/Product.java
> +    }
😉 👍 
이 검증은 꼭 별도 메서드로 호출하지 않고, product 의 생성자를 통해서도 진행해줄 수 있겠네요!
(관련한 테스트 코드도 추가되면 더 좋겠네요~)

2024-07-06 03:14 UTC, Hyeon9mak commented on src/test/java/gift/product/presentation/ProductControllerTest.java
> +
mock mvc 는 말 그대로 spring mvc 영역을 mocking 한 것이기 때문에, handler(controller)와는 별개죠.
handler(controller)의 동작을 테스트하기 위해 탄생했습니다.

HTTP 클라이언트의 요청을 모방하고 테스트하는데,
spring application 전체를 실행시키기 않아도 되어 속도가 빠르다... 그래서 사용한다...
정도로 지금은 이해하시면 좋을거 같네요 😄

2024-07-06 03:14 UTC, merged

2024-07-06 04:09 UTC, rladbrua0207 commented on src/main/java/gift/exception/ExceptionControllerAdvice.java
> +    }
ExceptionHandler에 의해 필터링되지않을거 같습니다.

2024-07-06 04:09 UTC, rladbrua0207 commented on src/test/java/gift/product/presentation/ProductControllerTest.java
> +
감사합니다!

2024-07-06 04:09 UTC, rladbrua0207 commented on src/main/java/gift/product/domain/Product.java
> +    }
네 알겠습니다!