충남대 BE_박서현 2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #247
Opened 2024-07-04 13:09 UTC by sseooh

2024-07-04 15:18 UTC, jjongwa requested changes
안녕하세요 디노입니다~! 🦖 1단계 잘 구현해 주셨어요!

`"카카오"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있다. (이를 클라이언트에게 적절히 알리기 `

아직 요구사항을 만족하지 못하는 부분이 있어 리뷰 반영 후 다시 요청 보내주세요~!

2024-07-04 15:18 UTC, jjongwa commented on src/main/java/gift/controller/ProductController.java
> +    public String getProducts(Model model) {
반환 타입에 ResponseEntity를 사용해 볼까요?

2024-07-04 15:18 UTC, jjongwa commented on src/main/java/gift/service/ProductService.java
> +    }
지난 1주차에 남긴 리뷰와 같은데요..!

지금 서현님이 구현해 주신 구조에서는 서비스 계층이 필요할까요?
어떤 로직을 서비스 계층이 담당하는게 좋을까요?

2024-07-04 15:18 UTC, jjongwa commented on src/main/java/gift/dto/Product.java
> +
이 부분도 지난 리뷰와 같습니다! 
Product를 dto라고 생각한 이유를 설명해 주세요~!

그리고 setter를 다 열어놓으면 어떤 장단점이 존재할까요?

2024-07-04 15:18 UTC, jjongwa commented on src/test/java/gift/ProductControllerTest.java
> +    }
```suggestion
    sampleProduct = new Product(null, "아이스 카페 아메리카노 T", 4500L,
                "https://st.kakaocdn.net/product/gift/product/20231010111814_9a667f9eccc943648797925498bdd8a3.jpg");
        productService.addProduct(sampleProduct);
```

이런 방식으로 사용할 수도 있을 것 같은데요.!
굳이 setter를 사용한 이유가 있을까요?

+ beforeEach는 테스트 메서드의 수만큼 해당 작업을 반복하게 되는데요, sampleProduct를 매번 새로 만들 필요는 없을 것 같아요!

2024-07-04 15:18 UTC, jjongwa commented on src/test/java/gift/ProductControllerTest.java
> +    }
상품 수정 테스트가 성공하지 않고 있습니다! 
다시 확인 부탁드려요~!

2024-07-04 15:18 UTC, jjongwa commented on src/test/java/gift/ProductControllerTest.java
> +                    products.forEach(System.out::println); // 디버깅을 위해 출력
디버깅을 위해서라면 print보단 log를 남기는 편이 더 좋습니다!

print와 logging의 차이를 검색해 보면 좋을 것 같아요!

2024-07-04 15:18 UTC, jjongwa commented on src/test/java/gift/ProductControllerTest.java
> +
MockMvc를 사용하셨군요!

서현님이 느끼셨을 때 mocking으로 테스트를 작성했을 때의 장점은 무엇인가요? 어떠한 기준으로 mocking과 real 테스트 사용을 정하는 편이신가요?

2024-07-04 15:18 UTC, jjongwa commented on src/main/java/gift/service/ProductService.java
> +
생성자가 하나밖에 없을 때는 `@Autowired` 어노테이션을 붙이지 않아도 의존성 주입이 가능합니다~!

2024-07-04 15:18 UTC, jjongwa commented on src/main/java/gift/dto/Product.java
> +    private String name;
상품 이름에 '카카오'가 들어가는 경우 클라이언트에게 알려야 하는 로직이 존재하지 않네요~!

2024-07-04 16:50 UTC, sseooh commented on src/main/java/gift/controller/ProductController.java
> +    public String getProducts(Model model) {
html 코드를 연결하면서 반환 타입을 ResponseEntity에서 현재 코드로 변경하였는데, 만약 다시 ResponseEntity로 변경한다면 사용자 화면과 연결하는 부분은 따로 분리하여 구현해야 하는 건가요?

2024-07-04 17:00 UTC, sseooh commented on src/main/java/gift/service/ProductService.java
> +    }
리뷰 남겨주신 내용 읽어보고 서비스 계층의 역할에 대해 좀 더 공부해봤습니다..!

DAO는 SQL 하나를 보내고 결과를 받는 단일 데이터 접근 로직인데, 실제 비즈니스 로직에서는 여러 번의 DB 접근이 필요하고, 병렬식으로 동시접근하여 데이터를 가져와야 하기도 합니다. 그렇기 때문에 하나의 서비스는 여러 DAO를 묶어서 트랜잭션을 관리하기도 합니다. 즉 Service는 이 트랜잭션의 단위가 될 수 있습니다. 현재 코드에서는 DAO 계층과 거의 일대일로 매핑이 되고 있어서, 말씀해주신 것처럼 서비스 계층이 필요하지 않은 것 같아 코드를 수정했습니다!

2024-07-04 17:02 UTC, sseooh commented on src/test/java/gift/ProductControllerTest.java
> +    }
setter를 평소에 자주 써서 편한대로 작성하게 된 것 같습니다 😅

피드백 주신 내용처럼 코드 수정했습니다!

2024-07-04 17:15 UTC, sseooh commented on src/main/java/gift/dto/Product.java
> +
DB와 다른 계층 간 데이터를 교환할 때 사용되며 특별한 로직이 없고, getter/setter 메서드만 갖고 있는게 DTO라고 생각했습니다..! + 생성자에서 값 할당

💡 setter를 다 열어놓을 때의 장단점

<장점>
- 객체의 상태를 동적으로 수정 가능, 쉽게 업데이트 할 수 있는 유연성
- setter 메서드를 통해서 데이터를 바인딩하는 외부 라이브러리와의 호환성..?

<단점>
- 객체 상태가 예상치 못한 방식으로 수정될 수 있음
- 따라서 객체의 일관성 유지가 어려움

-> 사용하지 않는 setter는 삭제했습니다!

2024-07-04 17:21 UTC, sseooh commented on src/test/java/gift/ProductControllerTest.java
> +
HTTP 요청 및 응답에 대한 테스트 코드를 작성해보는 것이 이번이 처음이라 다른 분들이 많이 사용하신 MockMvc를 사용해봤습니다!
mocking으로 테스트를 할 때의 장점은, 가짜 객체를 만들어서 테스트를 진행하기 때문에 테스트의 격리성을 유지할 수 있고, 외부 의존성에 영향을 받지 않아 테스트 환경이 안정적인 것이라고 생각합니다

2024-07-05 16:43 UTC, jjongwa commented on src/main/java/gift/controller/ProductController.java
> +    public String getProducts(Model model) {
음 그런 방법도 있을 것 같구 ViewResolver를 따로 만드는 방법도 있겠지만 이번 미션의 주제는 아닌 것 같아 그냥 넘어갈께요!

2024-07-05 17:02 UTC, merged