경북대 BE_신성민 2주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #250
Opened 2024-07-04 13:25 UTC by anaconda77

안녕하세요 경북대 BE 신성민 학생입니다. 2주차 과제 step2 제출드립니다.

## 과제 수행 중에 궁금했던 점

2024-07-05 10:48 UTC, lsm7179 commented
> 안녕하세요 경북대 BE 신성민 학생입니다. 2주차 과제 step2/step3 제출드립니다.
> 
> ## 과제 수행 중에 궁금했던 점
>   컨트롤러에서 DAO를 호출하여 유저 정보를 가져온 후 Request에 포함된 아이디&패스워드와 서로 일치하는지를 비교하는 작업을 합니다.
>   `Member loginedMember = memberDao.getMemberByEmail(loginRequest.email()); if(!loginedMember.login(loginRequest.email(), loginRequest.password())) { throw new LoginErrorException(); }`
>   이렇게 되면 메소드를 호출할 때 파라미터로 유저의 아이디와 패스워드를 넘겨주게 되는데, 가장 바깥 영역인 컨트롤러단에서 유저 개인 정보를 파라미터로 넘겨주는게 좋은 방식은 아닌 것 같다는 생각이 듭니다..

좋은 고민입니다.
Service 계층을 이용해서 제어해주면 어떨까요?

>   아직은 Service 계층이 도입되지 않아서 비즈니스 로직을 호출하기 위해서는 어쩔 수 없이 이러한 과정을 수행해야되는 것 같은데, 좀 더 나은 방안이 있을까요?

Service계층을 도입하면 좋을거 같습니다~!

> * 회원가입/로그인 시 jwt 토큰을 생성해서 응답 헤더에 넣어주는 작업을 현재 컨트롤러에서 하고 있는데, 해당 작업이 컨트롤러의 역할과 책임에 맞지 않다는 생각이 듭니다.
>   따라서 해당 작업을 수행해줄 별도의 객체가 있어야된다는 생각이 드는데, 찾아보니 Spring Security에서는 SuccessHandler라는 것을 통해 로그인 관련 로직을 처리하는 것 같습니다.
>   그러나 이번 과제에서는 Spring Security 없이 jwt 인증 시스템 구현을 요구하셨기 때문에, 해당 핸들러를 사용하지는 못합니다.
>   현재 시점에선 컨트롤러에서 직접 토큰 생성 작업을 수행하게 하는 것이 최선일까요? 아님 다른 방법이 있는지 궁금합니다.

Token생성 서비스 계층으로 생성로직을 넘겨주면 좋을거 같아요. ControllerAdvice, Filter, interceptor 등을 활용하면 더 좋을거 같습니다~

2024-07-05 10:48 UTC, lsm7179 requested changes
성민님 2단계3단계 잘 해주셨어요.
요구사항은 잘 충족했으나 몇가지만 고치면 좋을거 같아서 반영해보시고 다시 리뷰요청해주세요~

2024-07-05 10:48 UTC, lsm7179 commented on .gitignore
> +application.properties
프로퍼티를 숨기고 싶다면 
`git Submodules` 도 있습니다~
https://git-scm.com/book/en/v2/Git-Tools-Submodules
https://devocean.sk.com/blog/techBoardDetail.do?ID=165172&boardType=techBlog

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/auth/AuthInterceptor.java
> +        }
👍

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/auth/JwtTokenProvider.java
> +            .signWith(HS512, secretKey)
'signWith(io.jsonwebtoken.SignatureAlgorithm, java.lang.String)' is deprecated 

deprecated되었네요.
수정이 필요해보여요~

2024-07-05 10:48 UTC, lsm7179 commented on README.md
> +### 유저 인증을 통한 기능 사용 권한 검증
요구사항과 구현방법을 상세히 설명해주셨네요~👍💯

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/auth/JwtTokenProvider.java
> +                .setSigningKey(secretKey)
.parser().setSigningKey도
deprecated되었네요.
수정이 필요해보여요~

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/config/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer {
잘 설정해주었지만 webconfig가 많아질수록 해당 클래스명으로 어떤 작업을 하는지 추측하기 어려울거 같아요.
loginWebConfig 처럼 로그인 관련된 작업을 하는 클래스다 라고 명명하면 어떨까요?

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/controller/LoginController.java
> +
회원가입하면 자동으로 로그인까지 구현해주셨군요.

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/auth/JwtTokenProvider.java
> +    public boolean isExpired(String token) {
사용하지 않는 코드는 지워주세요~

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/controller/LoginController.java
> +        }
service계층이 있었으면 좋겠습니다.
컨트롤러가 이 모든 행위를 담당해야될까요?
서비스에서 로그인 시도해봐 라고 호출해보세요~

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/controller/LoginController.java
> +        Member joinedMember = memberDao.insertMember(member);
service계층이 있었으면 좋겠습니다.
컨트롤러가 이 모든 행위를 담당해야될까요?
서비스에서 회원가입 해봐 라고 호출해보세요~

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/response/ProductResponse.java
> +public record ProductResponse(Long id, String name, int price, String imageUrl) {
👍

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/controller/ProductViewController.java
> +        updatedProduct.update(form.getName(), form.getPrice(), form.getImageUrl());
도메인객체로 넘겨서 잘해주셨네요~ loginController에서 말했던 거처럼 Service계층에서 책임을 가질수있게 해보세요~👍

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/controller/WishListApiController.java
> +            .toList();
클라이언트에서 ProductResponse를 받을때 빈값이라도 내려주는것이 좋습니다.
왜 그런지 생각해보세요~

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/exception/MemberExceptionHandler.java
> +    }
👍

2024-07-05 10:48 UTC, lsm7179 commented on src/main/java/gift/model/Product.java
> +
👍

2024-07-05 14:18 UTC, anaconda77 commented on src/main/java/gift/controller/WishListApiController.java
> +            .toList();
프론트에서 조회 결과를 리스트로 받아오게 설계하기 때문에, 결과가 없더라도 빈 리스트 구조를 유지하는게 통일성이 맞을 것 같습니다..!

2024-07-05 14:45 UTC, anaconda77 commented on .gitignore
> +application.properties
아하 이런것도 있군요..프로젝트에서 보안상 민감한 파일들은 프라이빗 리포지토리에서 따로 관리하면 될 것 같네요!

2024-07-06 06:43 UTC, lsm7179 approved these changes
성민님
수고하셨습니다.
요구사항 잘 구현해주셨어요.👍
머지하겠습니다~

궁금하거나 어려운거 있으시면 편하게 DM 주세요.

2024-07-06 06:43 UTC, lsm7179 commented on src/main/java/gift/auth/JwtTokenProvider.java
> +        }
문자와 숫자가 어떤 뜻인지 알기 어려울수있어요.
상수로 만들어서 해보세요~

2024-07-06 06:43 UTC, lsm7179 commented on src/main/java/gift/service/MemberService.java
> +public class MemberService {
👍 서비스 계층을 만드셨네요.

2024-07-06 06:43 UTC, lsm7179 commented on src/main/java/gift/controller/WishListApiController.java
> +        }
wishlist가 이미 빈값인데 새로 빈 리스트를 생성해서 내려주는 이유가 있나요?

2024-07-06 06:43 UTC, merged

2024-07-06 07:02 UTC, anaconda77 commented on src/main/java/gift/controller/WishListApiController.java
> +        }
앗 기본적인 실수를 했네요ㅜ피드백 주신 부분 다음주차에 수정해서 올려놓도록 하겠습니다!