부산대 BE_박혜연 2주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #255
Opened 2024-07-04 15:26 UTC by hyyyh0x

2024-07-05 11:34 UTC, yoo-jaein requested changes
step2 고생하셨어요! :)
리뷰 코멘트 확인 부탁드립니다~

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/auth/AuthController.java
> +    @Autowired
이번 과제에서 대부분 ```@Autowired```를 필드 주입으로 사용하셨네요!

이 방식은 권장되지 않는 방식이라, 필드 주입 대신 생성자 주입을 사용하는 것으로 바꿔볼까요?
생성자 주입을 쓰는 이유는 다음 글을 읽어봐주세요~
- https://velog.io/@think2wice/Spring-의존성-주입DI에-대하여

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/auth/AuthService.java
> +    public AuthService(CustomUserDetailsService userDetailsService, PasswordEncoder passwordEncoder, JwtUtil jwtUtil) {
생성자 주입! 👍

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/WebController.java
> +public class WebController {
이 컨트롤러는 유저 회원가입과 로그인을 담당하고 있군요.
Restful API로 구현하셨으니 컨트롤러 이름도 적절히 바꿔볼까요?

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/WebController.java
> +            return ResponseEntity.status(HttpStatus.CREATED).build();
과제 요구사항대로 회원가입 성공시 200 OK를 반환해야 합니다!
```http
HTTP/1.1 200
Content-Type: application/json

{
    "token": ""
}
```

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/WebController.java
> +            return ResponseEntity.ok().body(Collections.singletonMap("accessToken", token));
현재 로그인 성공시 이렇게 응답하고 있는데
```json
{
    "accessToken": ""
}
```
요구사항대로 token이라는 이름으로 응답해줘야 합니다!
```json
{
    "token": ""
}
```

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/auth/AuthService.java
> +    public AuthService(CustomUserDetailsService userDetailsService, PasswordEncoder passwordEncoder, JwtUtil jwtUtil) {
생성자 주입 👍

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/WebController.java
> +    private UserService userService;
이번 과제에 여러 부분에서 필드 주입 방법을 사용하셨네요!
이는 권장되지 않는 방식입니다.

필드 주입 대신 생성자 주입을 사용하는 것이 좋습니다.
그 이유는 아래 링크를 참고해주세요!
- https://velog.io/@think2wice/Spring-의존성-주입DI에-대하여

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/auth/JwtUtil.java
> +    @Value("${jwt.expiration}")
환경 변수에서 키를 가져오도록 한 부분도 좋고, 만료 시간을 설정한 부분도 좋네요! 👍

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/auth/AuthService.java
> +        return null;
인증 실패시 null을 반환하는데, 대신 특정 예외를 Throw 하는 것이 의미상 더 적합할 것 같아요!

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/auth/CustomUserDetailsService.java
> +            return null;
여기도 null보다는 UsernameNotFoundException을 반환하는 것이 적합해보입니다.

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/auth/CustomUserDetailsService.java
> +            userDao.selectUser(email).getEmail(),
selectUser를 여러 번 호출하고 있군요!
효율을 높이기 위해 한 번만 호출하고 결과를 변수에 저장해서 재사용하는 코드로 수정해볼까요?

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/auth/CustomUserDetailsService.java
> +        String storedPassword = userDao.selectUser(email).getPassword();
여기 storedPassword 변수를 선언했지만 사용하는 곳이 없네요..

2024-07-05 11:34 UTC, yoo-jaein commented on src/main/java/gift/WebController.java
> +    @ResponseBody
이 컨트롤러에는 이미 ```@RestController```가 붙어있으니 ```@ResponseBody```는 제거해도 됩니다!

조금 더 부연설명을 드리자면...

```@ResponseBody```는 메서드의 반환값이 HTTP 응답의 바디에 직접 쓰여지게 해줍니다.

```@RestController```는 ```@Controller```와 ```@ResponseBody```를 결합한 컨트롤러이기 때문에 ```@RestController```가 붙은 클래스의 모든 메서드는 자동으로 ```@ResponseBody```의 기능을 가집니다.

실제로 ```@RestController``` 코드를 보면 다음과 같이 생겼어요.
```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Controller
@ResponseBody // 여기 !
public @interface RestController {
    @AliasFor(annotation = Controller.class)
    String value() default "";
}
```

2024-07-05 13:58 UTC, hyyyh0x commented
spring security를 사용하니 step3에서 로그인 페이지만 뜨는 오류를 해결하지 못해서 아예 사용하지 않는 방향으로 바꿨습니다. 피드백도 해주셨는데 정말 죄송합니다ㅜ

2024-07-05 16:20 UTC, yoo-jaein requested changes
step2 & step3 고생 많으셨습니다 :)
꼼꼼한 로깅이 인상깊었어요!

코드는 더 적합한 방법이 떠오르신다면 언제든지 다 갈아 엎으셔도 됩니다 ㅎㅎ
리뷰 코멘트 확인 부탁드립니다!

2024-07-05 16:20 UTC, deactivated-user commented on src/main/java/gift/UserApiController.java
> +    private static final Logger logger = Logger.getLogger(UserApiController.class.getName());
로깅 👍

2024-07-05 16:20 UTC, deactivated-user commented on src/main/java/gift/UserApiController.java
> +package gift;
UserApiController도 gift.user 패키지로 옮기는게 의미상 더 적절할 것 같습니다

2024-07-05 16:20 UTC, deactivated-user commented on src/main/java/gift/wishlist/WishList.java
> +    public void setName(int num){
이 메서드는 이름이 setNum 이어야겠네요

2024-07-05 16:20 UTC, deactivated-user commented on src/main/java/gift/wishlist/WishListController.java
> +        }
토큰 검증 로직이 반복되고 있네요. 중복 코드를 줄여볼 수 있을까요?
```java
        if (!email.equals(tokenEmail)) {
            logger.warning("Forbidden access attempt with mismatched email: " + email);
            return ResponseEntity.status(HttpStatus.FORBIDDEN).body("잘못된 토큰 접근입니다."); // Forbidden
        }
```

2024-07-05 16:20 UTC, deactivated-user commented on src/main/java/gift/wishlist/WishListController.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body("잘못된 토큰 접근입니다.");
에러 메시지가 약간 어색한 것 같아요~
위시 리스트 항목을 찾을 수 없습니다. 정도면 어떨까요?

2024-07-05 16:20 UTC, yoo-jaein commented on src/main/java/gift/wishlist/WishListDTO.java
> +    public void setId(Long id) {
파라미터 타입이 래퍼 클래스(Long)네요. 기본 타입인 long으로 통일하는 것이 좋습니다!

기본 타입 (Primitive Types):
- 예: int, long, float, double, boolean, char 등
- Java에서 가장 기본적인 데이터 타입입니다.
- null 값을 가질 수 없습니다.
- 메모리를 적게 사용하고 연산 속도가 빠릅니다.

래퍼 클래스 (Wrapper Classes):
- 예: Integer, Long, Float, Double, Boolean, Character 등
- 기본 타입을 객체로 감싼 클래스입니다.
- 객체이므로 null 값을 가질 수 있습니다.
- 추가적인 메서드와 기능을 제공합니다. (예: Integer.parseInt())
- 컬렉션에서 사용할 수 있습니다. (제네릭스와 함께 사용)

래퍼 클래스는 기본 타입보다 더 많은 메모리를 사용합니다.
그래서 단순 값 저장이나 계산에는 기본 타입을 사용하는 것이 효율적입니다.
자바의 오토박싱과 언박싱 기능으로 두 타입 간 변환이 자동으로 이루어지지만, 과도한 사용은 성능에 영향을 줄 수 있습니다.

2024-07-05 16:20 UTC, yoo-jaein commented on src/main/java/gift/wishlist/WishListDTO.java
> +    public void setNum(Integer num) {
여기도 파라미터 타입이 래퍼 클래스네요

2024-07-05 16:20 UTC, yoo-jaein commented on src/main/java/gift/UserApiController.java
> +                return ResponseEntity.status(HttpStatus.FORBIDDEN).body("토큰 생성 실패");
토큰 생성이 실패했으니 UNAUTHORIZED가 더 어울릴 것 같아요!

401 UNAUTHORIZED
- 인증되지 않음
- 클라이언트가 인증되지 않았거나, 유효하지 않은 인증 정보를 제공했을 때 사용합니다.
- 예: 만료된 인증 토큰을 사용할 때, 잘못된 비밀번호로 로그인을 시도할 때

403 FORBIDDEN
- 금지됨
- 클라이언트가 인증되었지만, 요청한 리소스에 대한 접근 권한이 없을 때 사용합니다.
- 예: 일반 사용자가 관리자 전용 페이지에 접근을 시도할 때

추가로 401은 인증(authentication) 문제, 403은 권한(authorization) 문제에요.
인증과 권한의 차이는 한 번 읽어보시면 좋을 것 같아요.
- https://ittrue.tistory.com/246

2024-07-05 16:20 UTC, yoo-jaein commented on README.md
> +1. security 관련된 것 전부 삭제(step3를 진행하는데에 어려움을 느낌) 및 수정
초기 설정이 꽤 복잡한데 고생 많으셨습니다 ㅠ.ㅠ

Spring security는 기본적으로 모든 엔드포인트를 보호하기 때문에, 로그인 페이지로 계속 리다이렉트되었을 거에요.
기본 로그인 화면을 제거하려면 해당 설정을 비활성화하는 추가 config들이 필요합니다.

- https://velog.io/@joranegs92/Spring-security-로그인-화면-없애기-hlm5elgz 참고

2024-07-05 16:20 UTC, yoo-jaein commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS product(
👏

2024-07-06 14:02 UTC, yoo-jaein approved these changes
2주차 step3 머지하겠습니다! :)

과제하다가 궁금한 점이나 이해가 안되는 부분이 있다면 편하게 메시지 주세요~

2024-07-06 14:02 UTC, merged