충남대 BE_이택 2주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #259
Opened 2024-07-04 15:57 UTC by LeeTaek2T

**궁금한점**
강의 자료만으로 이해가 잘 되지않아 구글링을 통해 여러가지 자료들을 봤습니다.
그런데 SecurityConfig, Authentication, SecurityFilterChain, UserDetails 등 모두 처음보는 내용이었고,
로직이 어떻게 돌아가는지 이해가 되지 않았습니다.
실제로는 jwt로그인을 구현할 때, 방금 언급한 함수, 클래스들을 사용하는지와 만약 사용한다면 어디부터 접근하면 좋은지 궁금합니다.

2024-07-05 02:10 UTC, ksy90101 requested changes
2단계도 고생많으셨습니다~
간단한 피드백을 남겼으니 참고해주세요!
궁금한게 있다면 언제든 DM주세요!

2024-07-05 02:10 UTC, ksy90101 commented on build.gradle
> +//    implementation 'org.springframework.boot:spring-boot-starter-security'
해당 부분은 제거하셔도 될거 같습니다~

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/Controller/LoginController.java
> +  @PostMapping("/login/token")
좀더 RESTful하게 작성해보면 어떨까요?
굳이 token이라는게 필요할까요?
login으로만 충분하지 않을가요?

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/Controller/LoginController.java
> +    @RequestHeader("pw") String pw) {
인자를 Header로 받으신 이유가 있나요?

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/Controller/LoginController.java
> +    System.out.println(userInfo);
로그는 제거해주시면 좋을거 같습니다.

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/DTO/LoginDto.java
> +public class LoginDto {
굳이 DTO에 setter가 필요할까요?
생성자로 DTO를 쓰는법을 공부해보시면 좋을거 같습니다~

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/DTO/LoginDto.java
> +  private String email;
한번 Email형식에 대해서 validate를 해보면 어떨까요?
1단계에서 해보셨기 때문에 충분히 가능할꺼라고 생각해요!

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/DTO/LoginDto.java
> +  private String pw;
축약어를 쓰기보단 풀네임을 쓰는게 훨씬더 이해하기 좋습니다 ㅠㅠ

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/DTO/ProductDto.java
> +
```suggestion
package gift.DTO;
```

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/Repository/LoginDao.java
> +  }
Login이라는 단어보단 이 쿼리가 의미하는 바를 생각해보세요.
email을 가지고 조회하는게 아닐까요?

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/Repository/LoginDao.java
> +public class LoginDao {
Dao는 도메인, 데이터베이스 테이블을 기반으로 응집도를 높입니다.

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/Service/JwtService.java
> +  private String key = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
key는 오픈되면 안좋기 떄문에 https://rutgo-letsgo.tistory.com/entry/Value%EC%99%80-ConfigurationProperties%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%B4-yaml-%ED%8C%8C%EC%9D%BC-%EB%A7%A4%ED%95%91%ED%95%98%EA%B8%B0

한번 이글을 참고해서 @value를 사용해보면 어떨까요?

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/Service/JwtService.java
> +      .claim("pw", loginDto.getPw())
JWT에 password를 넣으면 보안상 과연 문제 없을까요?

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/Service/LoginService.java
> +    return ResponseEntity.status(403).build();
status를 이미 정의되어 있는 상수를 쓰면 어떨까요?

2024-07-05 02:10 UTC, ksy90101 commented on src/main/java/gift/Service/LoginService.java
> +  public ResponseEntity<JwtToken> UserLogin(String email, String pw) {
Service는 HTTP와 같은 통신과 연관되어 있으면 안됩니다.
단순히 비지니스 로직을 처리하기 위해 존재하는 계층입니다.
통신 응답, 요청부분은 Controller에서 처리해야 합니다

다른 통신방식으로 변경한다고 했을때 Service는 변동이 없어야 한다. 라고 생각하시면 좋을거에요.

2024-07-05 02:10 UTC, ksy90101 commented on src/main/resources/schema.sql
> +                      email VARCHAR(255) PRIMARY KEY,
email을 PK로 하신 이유가 있나요?

2024-07-05 02:10 UTC, ksy90101 commented on src/test/java/gift/productDtoControllerTest.java
> +    productController.addProduct(productDto2);
굳이 컨트롤러를 사용하면 더 느립니다.
차라리 Dao를 사용해서 하는게 좋아요!

2024-07-05 05:35 UTC, LeeTaek2T commented on src/main/java/gift/Controller/LoginController.java
> +    @RequestHeader("pw") String pw) {
강의자료에서 헤더에 구현하라는 말이 있었던 것 같은데 제가 착각한 것 같습니다.
인자를 Body로 바꾸어 다시 구현하였습니다

2024-07-05 06:19 UTC, LeeTaek2T commented on src/main/java/gift/Repository/LoginDao.java
> +public class LoginDao {
Dao는 데이터 베이스 테이블 관리, Repsitory는 데이터 베이스에 객체 관리에 있어 차이가 있다고 알고 있습니다.

>Dao는 도메인, 데이터베이스 테이블을 기반으로 응집도를 높입니다.
이렇게 리뷰를 남겨주신 이유가 Dao와 Repository를 구별해서 쓰면 좋겠다라는 의미로 피드백을 남겨주신걸까요?
아니면 다른 이유가 있을까요?

2024-07-05 06:27 UTC, ksy90101 commented on src/main/java/gift/Repository/LoginDao.java
> +public class LoginDao {
아뇨.
지금은 어떤 행위에 기반으로 응집도를 높인거 아닐까요?
Login이라는게 데이터 베이스 테이블일까요?
그렇다면 이런식으로 DAO가 작성되는게 맞을까요?

이러한 흐름으로 고민해보라는 이야기였습니다~

2024-07-05 06:42 UTC, LeeTaek2T commented on src/main/resources/schema.sql
> +                      email VARCHAR(255) PRIMARY KEY,
따로 id를 두지 않기 위해 email을 PRIMARY KEY로 뒀습니다.

2024-07-05 06:49 UTC, ksy90101 commented on src/main/resources/schema.sql
> +                      email VARCHAR(255) PRIMARY KEY,
https://stackoverflow.com/questions/3804108/use-email-address-as-primary-key
한번 이글을 읽고 한번더 고민해보시면 어떨까요?

2024-07-05 07:20 UTC, LeeTaek2T commented on src/main/resources/schema.sql
> +                      email VARCHAR(255) PRIMARY KEY,
이런 이유가 있었군요..
알려주셔서 감사합니다!!

2024-07-05 07:31 UTC, ksy90101 requested changes
지금 시기에 formmatting을 하고 가는게 좋을거 같아서 한번더 리뷰 확인해주시면 좋을거 같습니다~
언제든 질문이 있다면 DM주세요!

2024-07-05 07:31 UTC, ksy90101 commented on src/main/java/gift/Controller/LoginController.java
> +@RequestMapping("/api/user")
RESTful AP에서는 리소스는 복수로 쓰는 편입니다.

2024-07-05 07:31 UTC, ksy90101 commented on src/main/java/gift/Controller/LoginController.java
> +    this.jwtService=jwtService;
intellij 자동정렬 기능을 쓰시면 좋을거 같아요.

https://penthegom.tistory.com/47

2024-07-05 07:31 UTC, ksy90101 commented on src/main/java/gift/Controller/LoginController.java
> +    LoginDto loginDto = loginService.UserLogin(email, password);
여기에 userInfo를 넘기면 되는게 아닐까요?
이렇게 인자를 넘긴 이유가 있나요?

2024-07-05 07:31 UTC, ksy90101 commented on src/main/java/gift/Controller/LoginController.java
> +    JwtToken jwtToken;
이게 이렇게 정의되어야 할 필요가 없어 보여요~

2024-07-05 07:31 UTC, ksy90101 commented on src/main/java/gift/DTO/JwtToken.java
> +  }
setter없이 생성자로만 할 방법을 찾아보시면 어떨까요?

2024-07-05 07:31 UTC, ksy90101 commented on src/main/java/gift/GlobalExceptionHandler.java
> +    return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Product not found");
Proejct가 아닌 User가 Not Found일때도 동일한 에러가 뜰꺼 같은데 그렇게 된 경우 에러 메시지가 알맞을까요?

2024-07-05 07:31 UTC, ksy90101 commented on src/main/java/gift/Repository/UserDao.java
> +  }
다른곳에서는 create라고 하지 않았나요?
굳이 service, dao, controller 모두다 이름을 맞출 필요는 없습니다!

2024-07-05 07:31 UTC, ksy90101 commented on src/main/resources/schema.sql
> +                       email VARCHAR(255),
unique index를 찾아보시면 어떨까요?
그럼 email 중복을 피할수 있을거 같습니다~

2024-07-05 08:43 UTC, ksy90101 requested changes
리뷰 반영이 안되었습니다 ㅠㅠ

2024-07-05 08:52 UTC, LeeTaek2T commented on src/main/java/gift/DTO/JwtToken.java
> +  }
setter를 삭제시켰는데 뭔가 복구되면서 setter가 다시 들어간 것 같습니다.ㅠㅠ
setter없이 생성자로만 작동되도록 변경했습니다!

2024-07-05 08:59 UTC, LeeTaek2T commented on src/main/java/gift/Controller/LoginController.java
> +@RequestMapping("/api/user")
리소스를 복수로 쓰는 편인지 몰랐었습니다! 수정하겠습니다!!

2024-07-05 08:59 UTC, LeeTaek2T commented on src/main/java/gift/Controller/LoginController.java
> +    this.jwtService=jwtService;
오.. 코드 다 쓸 때마다 자동정렬 기능을 써야겠네요

2024-07-05 09:01 UTC, LeeTaek2T commented on src/main/java/gift/Controller/LoginController.java
> +    LoginDto loginDto = loginService.UserLogin(email, password);
email과 password 2가지만 있으면 해당 메서드를 실행시킬 수 있으므로 인자로 2개를 넣어줬었는데
다시 생각해보니 userinfo를 넘겨주는게 더 좋은 것 같습니다.

2024-07-05 09:02 UTC, LeeTaek2T commented on src/main/java/gift/Controller/LoginController.java
> +    JwtToken jwtToken;
intellij에서 경고문으로 떠서 수정을 했었는데, 지금 다시 삭제해보니 경고문이 안뜨고 제대로 작동이 되네요.
반영하겠습니다!

2024-07-05 09:27 UTC, LeeTaek2T commented on src/main/java/gift/GlobalExceptionHandler.java
> +    return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Product not found");
에러메시지를 Product와 User일 때 모두 포함할 수 있게 변경하였습니다.

**궁금한점**
오류메시지만 Product, User모두 포함할 수 있게 변경하는게 나은지, 아니면 Product에 대한 예외처리, User에 대한 예외처리 따로 따로 클래스를 만드는게 좋은지 궁금합니다!

2024-07-05 09:27 UTC, LeeTaek2T commented on src/main/java/gift/Repository/UserDao.java
> +  }
네! 알겠습니다

2024-07-05 10:19 UTC, LeeTaek2T commented on src/main/resources/schema.sql
> +                       email VARCHAR(255),
네!! 거기에다가 password도 비워지면 안되는 값이라 생각하여 Not Null을 붙여 수정하였습니다

2024-07-05 10:20 UTC, LeeTaek2T commented
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/137752192/3202f3f9-1910-442c-9e38-0757146121da)
이 부분은 intellij에서 오류가 발생하여 고치다가 계속 commit이 되었습니다. 마지막에 제대로 바꾸어놓았습니다!

2024-07-06 01:29 UTC, ksy90101 approved these changes
2단계도 고생 많으셨어요~
추가 리뷰를 남기긴 했지만 아직 3단계가 남아있기 떄문에 3단계에서 진행해보시면 좋을거 같습니다!
언제든 궁금한게 있다면 DM주세요!

2024-07-06 01:29 UTC, ksy90101 commented on src/main/java/gift/Controller/LoginController.java
> +      JwtToken jwtToken = jwtService.createAccessToken(userDto);
토큰 발급을 userLogin의 메서드에서 해보면 어떨까요?

2024-07-06 01:29 UTC, ksy90101 commented on src/main/java/gift/Controller/LoginController.java
> +    return ResponseEntity.status(HttpStatus.FORBIDDEN).build();
Service에서 에러를 발생시킨다면 Exception Handler에서 에러 처리가 가능할거 같습니다.

2024-07-06 01:29 UTC, ksy90101 commented on src/main/java/gift/Controller/LoginController.java
> +    UserDto userDto = loginService.UserLogin(userInfo);
메서드명은 카멜케이스입니다.ㅣ
```suggestion
    UserDto userDto = loginService.userLogin(userInfo);
```

2024-07-06 01:29 UTC, ksy90101 commented on src/main/java/gift/DTO/UserDto.java
> +  @NotEmpty(message = "Email을 필수입니다.")
NotEmpty와 NotBlank의 차이를 찾아보시면 어떨까요?

2024-07-06 01:29 UTC, merged

2024-07-07 01:50 UTC, LeeTaek2T commented on src/main/java/gift/Controller/LoginController.java
> +    UserDto userDto = loginService.UserLogin(userInfo);
네! 수정하였습니다. 그리고 모든 함수 다 확인하여 카멜케이스 적용하였습니다

2024-07-07 01:51 UTC, LeeTaek2T commented on src/main/java/gift/DTO/UserDto.java
> +  @NotEmpty(message = "Email을 필수입니다.")
네! 확인했습니다

2024-07-07 03:02 UTC, LeeTaek2T commented on src/main/java/gift/Controller/LoginController.java
> +      JwtToken jwtToken = jwtService.createAccessToken(userDto);
네! 알겠습니다. Controller보단 Service에서 토큰 발급이 더 잘 어울리는 것 같습니다

2024-07-07 03:15 UTC, LeeTaek2T commented on src/main/java/gift/Controller/LoginController.java
> +    return ResponseEntity.status(HttpStatus.FORBIDDEN).build();
네! 반영해보겠습니다