경북대 BE_김민주 2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #262
Opened 2024-07-04 16:22 UTC by minju26

- 말씀해주신 fetch API를 사용해서 바꿔보려고 했는데, 아래의 어려움이 있어서 바꾸지 못했습니다.
(아래 경우는 상품 목록을 표시하는 페이지에 대한 것).   
   - Controller에서는 html 파일을 return합니다.   
   - html 파일과 js 파일을 따로 작성했는데, 페이지가 표시는 되지만 js파일의 try-catch에서 에러가 잡힙니다.
   - 에러의 이유는 받아오는 값이 Json이 아니라서 발생하는 것 같았는데..
    html 파일을 리턴하지 않고 상품 객체 리스트를 반환하면 페이지가 보이지 않고, 
    html 파일을 리턴하면 json이 아니라서 오류가 발생합니다. 
   어떻게 해결해야 하는지 모르겠습니다.
   ```
    @GetMapping
    public String retrieveProduct(Model model) {
        model.addAttribute("products", productService.getProduct());
        return MANAGE_PRODUCT_PAGE;
    }   
    ```
   ```
   document.addEventListener('DOMContentLoaded', async function() {
    try {
        const response = await fetch('/api/manage/products');
        console.log(response)
        if (!response.ok) {
            throw new Error('상품 목록을 불러오기 실패');
        }
        const products = await response.json();
        displayProducts(products);
    } catch (error) {
        console.error('catch error', error);
    }
  });
   ```
   `에러로그` **products.js:10 catch error: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON**
- step0 브랜치로부터 step1 브랜치 만들었습니다.

2024-07-05 16:25 UTC, gongdongho12 requested changes
이번에 원래 되던게 안되서 고민이 많으셨을 것 같아요
프로젝트 진행하시면서 파고드는 것도 좋은데 다른 단추가 잘못 들어간 경우에는 질문주시는 것도 좋을 것 같습니다

고생하셨습니다 👍🏼

2024-07-05 16:25 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductManageController.java
> +    }
@Controller는 thymeleaf 형식의 템플릿을 리턴할 때 사용하시구
@RestController는 API를 리턴할 떄 사용해주시면 말씀주신 문제를 해결하실 수 있을거에요

2024-07-05 16:25 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductManageController.java
> +    }
@minju26 path가 api로 시작하면 RestController page로 시작하면 Controller와 같은 룰을 뒤면 위에처럼 api path인데 혼용해서 쓰는 문제는 해소하실 수 있을 것 같습니다

이부분은 고민해보시구 정리해서 이 PR에 반영해 주세요

2024-07-05 16:25 UTC, gongdongho12 commented on src/main/java/gift/exception/ProductNameException.java
> +    }
궁금한게 이게 ProductNameException일 필요는 없고
ErrorCodeException으로 두고 ErrorCode를 Exception으로 변환해주는 Wrapper 클래스 정도로 보는게 맞는 방향성 아닐까요?

ProductName의 특성이 없어 보여서요

2024-07-05 16:25 UTC, gongdongho12 commented on src/main/java/gift/exception/ProductNameExceptionResponse.java
> +    }
ProductNameException랑 차이가 어떤 용도일까요? throw가 안되는 것 제외하고는 형태가 유사해서요
의도가 궁금합니다

2024-07-05 16:25 UTC, gongdongho12 commented on src/main/java/gift/exception/ErrorCode.java
> +    KAKAO_CONTAIN_ERROR(400, HttpStatus.BAD_REQUEST, KAKAO_CONTAIN_ERROR_MSG);
에러코드를 enum으로 한눈에 들어오게 잘 정리해 주셨어요 👍🏼

2024-07-05 16:25 UTC, gongdongho12 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
이걸 추가했는데 ProductNameValidationUtil를 사용해주고 계시네요
Validation 방법이 여러개 있는데 한번 다시 찾아서 통일해보면 좋을 것 같습니다

2024-07-06 13:13 UTC, minju26 commented on src/main/java/gift/controller/ProductManageController.java
> +    }
오호! 넵 한번 해보겠습니다

2024-07-06 13:15 UTC, minju26 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
엇.. 추가해두고 사용은 안했네요
방법들 찾아보고 통일해보도록 하겠습니다!

2024-07-06 13:43 UTC, minju26 commented on src/main/java/gift/exception/ProductNameExceptionResponse.java
> +    }
음 ProductNameException은 Exception 차제를 나타내려고 정의했고, ProductNameExceptionResponse는 Exception이 발생했을 때 정보를 담아서 전달하는 목적으로 사용하려고 정의했습니다..!

2024-07-06 13:57 UTC, minju26 commented on src/main/java/gift/exception/ProductNameException.java
> +    }
네 그러네요..! 방향성을 그렇게 잡으면 다른 에러도 처리할 수 있겠어요!

2024-07-07 15:44 UTC, gongdongho12 commented
@minju26 제가 머지순서를 잘못했을 수 있는데 conflict 한번 체크부탁드려요 🙏🏼

2024-07-07 15:49 UTC, minju26 commented
> [gongdongho12](/gongdongho12)

step3이 step1 브랜치로 부터 만들고, step1 수정 사항을 머지해둬서 이 pr은 그냥 닫아도 괜찮을 것 같습니다!
감사합니다 👍

2024-07-07 15:50 UTC, closed without merging