충남대 BE_이경빈 2주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #263
Opened 2024-07-04 16:38 UTC by cussle

안녕하세요:) 2주차 과제 - step2 리뷰 요청 드립니다.

로그인 기능을 구현해본 경험이 거의 없기도 하고, 몇 번 해본 것도 세션을 통한 로그인이었습니다. JWT도 처음 사용해봤는데.. '이게 맞나?' 생각하며 구현한 게 대부분이라 JWT 위주로 봐주시면 감사하겠습니다..!

이번에도 몇 가지 질문이 있는데요,

1. 과제 설명 페이지에 'Authorization 헤더가 유효하지 않거나 토큰이 유효하지 않은 경우 401 Unauthorized를 반환한다.' 라고 되어있는데, 현제 단계에서 401을 반환하는 경우가 있을까요? 아직 회원가입과 로그인밖에 구현이 안 된 상태인데, 이 두 기능은 모두 새로운 토큰을 생성해서 401 반환이 필요 없다고 생각했습니다. (추후 바로 사용할 수 있도록 구현은 해두었습니다.)

2. 지금은 이메일이 잘못되었으면 이메일이 잘못되었다고 알려주고, 비밀번호가 잘못되었으면 비밀번호가 잘못되었다고 알려주는 등 예외가 발생하는 이유를 자세히 알려주고 있습니다. 실제 웹 서비스에서는 이런식으로 자세한 이유를 알려주지 않는 것 같습니다. 예외 상황을 숨기는 건 프론트엔드의 영역인지, 서버에서 처음부터 자세한 정보를 제공하지 않는 것인지 궁금합니다..!

추가로 회원 이메일, 비밀번호에 임의 규칙으로 유효성 검사를 진행하였고,

``` bash
    compileOnly 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
```

과제 설명 페이지에는 위와 같은 dependency를 사용하면 된다고 적혀있었는데, 정보도 너무 적고 공식 문서를 따라해봐도 오류가 잦아서 버전을 0.11.5로 낮춰 사용했습니다..!

``` bash
implementation 'io.jsonwebtoken:jjwt-api:0.11.5'  
implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'  
implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'
```

2024-07-05 14:18 UTC, asebn1 requested changes
경빈님 안녕하세요~ 이번에 3단계까지 빠르게 구현해주셨네요 ✈️
커밋단위가 잘 나뉘어져 있어서 리뷰하기 편했습니다 :)
테스트코드도 꼼꼼히 작성해주고 계시네요!

먼저 질문주신 내용 답변드려요
> 과제 설명 페이지에 'Authorization 헤더가 유효하지 않거나 토큰이 유효하지 않은 경우 401 Unauthorized를 반환한다.' 라고 되어있는데, 현제 단계에서 401을 반환하는 경우가 있을까요? 아직 회원가입과 로그인밖에 구현이 안 된 상태인데, 이 두 기능은 모두 새로운 토큰을 생성해서 401 반환이 필요 없다고 생각했습니다. (추후 바로 사용할 수 있도록 구현은 해두었습니다.)

저도 토큰 검증이 필요한 시점에 401 반환할 상황이 있다고 생각됩니다.

> 지금은 이메일이 잘못되었으면 이메일이 잘못되었다고 알려주고, 비밀번호가 잘못되었으면 비밀번호가 잘못되었다고 알려주는 등 예외가 발생하는 이유를 자세히 알려주고 있습니다. 실제 웹 서비스에서는 이런식으로 자세한 이유를 알려주지 않는 것 같습니다. 예외 상황을 숨기는 건 프론트엔드의 영역인지, 서버에서 처음부터 자세한 정보를 제공하지 않는 것인지 궁금합니다..!

정확히 알고 계시네요! 취약점보안을 위해서 사전에 방지하고 있어요. 이메일이 틀리든 패스워드가 틀리든 서버에서는 일관된 형식의 에러 응답을 제공하도록 하는걸 권장합니다.

추가로 repository 계층에 인터페이스를 적용해보는 건 어떨까요? 이를 적용했을 때 어떤장점이 있을까요? 🤔

2024-07-05 14:18 UTC, asebn1 commented on README.md
> +
이번에도 요구사항을 잘 작성해주셨군요~ 👍

2024-07-05 14:18 UTC, asebn1 commented on src/main/resources/schema.sql
> +);
email에 `unique`도 고려할 수 있을 것 같아요 ㅎㅎ
해당 제약사항 추가 시 어떤 장점이 있을까요?

2024-07-05 14:18 UTC, asebn1 commented on src/main/java/gift/dto/member/MemberRequestDTO.java
> +) { }
Request, Response로 잘 구분되어서 이제 네이밍에 `DTO`가 빠져도 될 것 같아요

2024-07-05 14:18 UTC, asebn1 commented on src/main/java/gift/util/JWTUtil.java
> +    private static final long EXPIRATION_TIME = 30 * 60 * 1000;
키 값을 하드코딩으로 관리해도 괜찮을까요?

2024-07-05 14:18 UTC, asebn1 commented on src/main/java/gift/util/Constants.java
>  }
`Constants`에서 도메인에 관련된 상수를 관리해주고있어요.
경빈님이 실제로 코딩하실 때 이점이 있다고 느끼셨나요?

2024-07-05 14:18 UTC, asebn1 commented on src/main/java/gift/controller/WishController.java
> +    }
비즈니스 로직이 controller에 있네요.
개선할 수 없을까요?

2024-07-05 14:18 UTC, asebn1 commented on src/main/java/gift/controller/WishController.java
> +    }
`HttpServletRequest`로 받으면 항상 `memberId`로 변환하는 메서드를 `controller`에서 호출할 것 같아요.
`controller`에서는 `HttpServletRequest` 대신 정보를 바로 받도록 개선할 수 있을 것 같아요.
인터셉터나 필터를 사용해서 개선해볼까요? 어떤 걸 선택해서 사용할지 고민도 해보아요 ㅎㅎ

2024-07-05 14:18 UTC, asebn1 commented on src/main/java/gift/service/WishService.java
> +
`WishService`에서 `ProductService`대신 `ProductRepository`를 의존한 이유가 궁금해요!

2024-07-05 15:27 UTC, asebn1 requested changes

2024-07-05 15:27 UTC, asebn1 commented on src/main/java/gift/controller/WishController.java
> +    }
`controller`에서 `HttpServletRequest`가 아닌 다른것으로 개선할 수 있을까요? 🤔

2024-07-06 06:57 UTC, cussle commented on src/main/java/gift/dto/member/MemberRequestDTO.java
> +) { }
MemberRequest, MemberResponse 등으로 네이밍 수정하였습니다!

2024-07-06 07:12 UTC, cussle commented on src/main/resources/schema.sql
> +);
id라는 고유한 PK를 설정하여 `UNIQUE` 사용을 생각하지 못했던 것 같습니다..!

``` SQL
-- 회원(MEMBERS) 스키마  
CREATE TABLE IF NOT EXISTS members (  
    id BIGINT AUTO_INCREMENT PRIMARY KEY,  
    email VARCHAR(255) NOT NULL UNIQUE,  
    password VARCHAR(255) NOT NULL  
);
```
위와 같이 코드를 수정하였습니다.

`UNIQUE` 제약 조건을 사용함으로써 동일한 이메일 주소를 가진 중복된 회원이 테이블에 삽입되는 것을 방지할 수 있습니다.

중복된 값이 허용되지 않고, email 열의 각각의 값이 고유하므로, 데이터의 일관성을 유지할 수 있습니다.

중복된 이메일 주소가 없기 때문에 로그인 기능의 신뢰성을 높일 수 있고, 특정 회원을 이메일 주소로 확실하게 식별할 수 있으므로 데이터 관리에도 용이하다는 장점이 생기게 될 것 같습니다!

2024-07-07 16:12 UTC, cussle commented on src/main/java/gift/util/JWTUtil.java
> +    private static final long EXPIRATION_TIME = 30 * 60 * 1000;
기존엔 JWTUtil.java 클래스에서 키 값을 직접 사용했으나, 이런 방식은 소스코드가 유출될 경우 키도 함께 노출되어 보안 위협이 크다고 합니다.

이에 대한 대안으로 환경 변수나 설정 파일을 통해 키 값을 관리하는 것이 좋다는 것을 알게 되었고, 스프링 부트에서는 `application.properties`를 통해 외부로 분리할 수 있다고 해서 리팩토링을 진행했습니다!

application.properties 파일에 키 값과 만료 시간을 추가했습니다. `@Component` 어노테이션을 통해 빈을 정의하고, `@Value` 어노테이션을 통해 프로퍼티 파일 값을 필드에 주입했으며, `@PostConstruct` 어노테이션을 통해 빈이 생성된 후 초기화 작업을 진행했습니다.

---

한 가지 의문이 있는데, `application.properties`에 적는 것과 `JWTUtil.java`에 적는 것의 차이를 크게 느끼지 못하겠습니다..! 둘 다 코드베이스 내에 키 값을 저장하는 것으로 위의 리팩토링 과정도 결국 하드코딩 형태인건 변하지 않는 것 같은데, 이러한 방식을 많이 사용하는 것 같았습니다.

실제 서비스를 배포하면 설정 파일 관리와 소스 코드는 각각 관리되기 때문인가요?

2024-07-07 16:18 UTC, cussle commented on src/main/java/gift/util/Constants.java
>  }
네! 특히 입력된 아이디로 상품을 찾을 수 없는 경우의 예외를 처리하는 경우가 잦았는데, 예외 메시지를 상수로 관리함으로써 오타나 문장 형식을 신경쓰지 않아도 돼서 편했습니다.

메시지의 수정이 필요한 경우에도 `Constants`만 수정해주면 되고, 일관성을 유지할 수 있어서 좋았습니다. 또한 코드 가독성 향상에도 도움이 된다고 생각합니다..!!

2024-07-07 16:30 UTC, cussle commented on src/main/java/gift/controller/WishController.java
> +    }
헉.. 레이어 분리에 나름 집중하고 있다고 생각했는데 놓친 것 같습니다. `WishService`로 `getMemberIdFromRequest` 메서드를 이동하였습니다!

2024-07-07 16:43 UTC, cussle commented on src/main/java/gift/service/WishService.java
> +
앗.. 미션을 수행할 때 단순히 "ID로 상품을 찾아야 한다."라는 생각에 바로 리포지토리 클래스부터 살폈던 것 같습니다.

고민해보니 `ProductRepository`에 의존하는 것 보다, `ProductService`에 의존하는 것이 더 합리적인 것 같다는 생각을 하게 되었습니다.

`ProductService`에서 상품과 관련된 비즈니스 로직을 처리하기 때문에, 제품의 존재 여부를 확인하는 로직은 ProductService가 담당하는 것이 적절한 것 같습니다!

2024-07-07 16:46 UTC, asebn1 commented on src/main/java/gift/util/JWTUtil.java
> +    private static final long EXPIRATION_TIME = 30 * 60 * 1000;
> 한 가지 의문이 있는데, application.properties에 적는 것과 JWTUtil.java에 적는 것의 차이를 크게 느끼지 못하겠습니다..! 둘 다 코드베이스 내에 키 값을 저장하는 것으로 위의 리팩토링 과정도 결국 하드코딩 형태인건 변하지 않는 것 같은데, 이러한 방식을 많이 사용하는 것 같았습니다. 
실제 서비스를 배포하면 설정 파일 관리와 소스 코드는 각각 관리되기 때문인가요?

그런 케이스도 있고 아닌 케이스도 있습니다. 
`properties`로 관리했을 때 먼저 떠오르는 장점은 환경변수 값을 phase 별로 관리할 수 있을 것 같고(이 부분이 큰 것 같아요), 관리해야할 환경변수가 많을 때도 관리하기 좋을 것 같아요.

2024-07-07 16:50 UTC, asebn1 approved these changes
경빈님 안녕하세요~
이번주 과제 마감이 일요일이라 우선 현재까지 리팩토링 진행하신 것으로 머지 진행하겠습니다 :)
나머지 부분은 다음 주차에 함께 반영해주세요!
이번 단계도 수고 많으셨습니다~

2024-07-07 16:51 UTC, merged