충남대 BE_김민지 2주차 과제(2단계,3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #267
Opened 2024-07-04 17:19 UTC by alsswl

jwt 토큰을 헤더에 넣는것과 바디에 넣는 것의 기준에 대해서 어떻게 생각하시는지 궁금합니다.
그리고 엔티티와 dto 사용에 대해서 찾아봤을 때 관점마다 말이 달라서 우선 이해한대로 구현하긴 했는데 더 좋은 방법이 있으면 피드백 부탁드립니다!

2024-07-07 06:44 UTC, Hyeon9mak requested changes
안녕하세요 민지님, 3단계 잘 진행해주셨어요.
다음 주차부터는 각 단계별로 꼭 나누어서 진행을 해주시면 더 좋겠네요.

dto 와 엔티티에 관련해서는 어떤 자료들을 참고하신걸까요?
링크를 첨부해주시면 같이 보면서 여러가지 의견을 나눠볼 수 있을거 같아요.
현재는 어떤 의도로 dto 를 분리해주신 것인지 가늠이 안가서, 우선 다른 것들에 집중한 코멘트 먼저 남겼습니다.
궁금하신 점 질문 남겨주세요~

2024-07-07 06:44 UTC, Hyeon9mak commented on src/main/java/gift/controller/MemberController.java
> +    }
> jwt 토큰을 헤더에 넣는것과 바디에 넣는 것의 기준에 대해서 어떻게 생각하시는지 궁금합니다.

구현 방식은 자유지만, 보편적으로 사용되는 방식들이 있습니다. 저희는 이걸 통신규약이라고 말하죠.
통신규약에 따르면 보안상 이점을 더욱 누리기 위해 header 에 담는 것을 권장합니다.

HTTPS 를 통해 전송되는 헤더는 암호화되어 전송됩니다.
Authorization 헤더를 중간에 가로채더라도 볼 수 없습니다.

2024-07-07 06:44 UTC, Hyeon9mak commented on src/main/java/gift/controller/MemberController.java
> +    @PostMapping("/changePasswd")
passwd 라는 축약어를 사용하신 이유가 있을까요?

2024-07-07 06:44 UTC, Hyeon9mak commented on src/main/java/gift/controller/MemberController.java
> +        }
일련의 과정은 memberService 의 login 메서드 내부에서 행해줄 수 있을 것 같은데, 어떻게 생각하시나요?
controller 계층은 http 를 다루기에만 집중하는게 좋을거 같아요.

2024-07-07 06:44 UTC, Hyeon9mak commented on src/main/java/gift/controller/MenuController.java
> +    }
음... 이전 단계에서도 말씀드렸었는데, model 을 응답하는 API 와 요청을 수행하는 API 를 분리하지 않으시는 이유가 있을까요?

2024-07-07 06:44 UTC, Hyeon9mak commented on src/main/java/gift/controller/WishListController.java
> +
접근제한자를 명세해주면 더욱 좋겠네요.

2024-07-07 06:44 UTC, Hyeon9mak commented on src/main/java/gift/domain/MenuRequest.java
> +}
https://hyeon9mak.github.io/github-no-newline-at-a-end-of-file/

2024-07-07 06:44 UTC, Hyeon9mak commented on src/main/java/gift/exception/EtcExceptionHandler.java
> +@ControllerAdvice
요기는 `@RestControllerAdvice` 가 아닌 `@ControllerAdvice` 를 선택한 이유가 있을까요?

2024-07-07 06:44 UTC, Hyeon9mak commented on src/main/java/gift/repository/MemberRepository.java
> +    }
요청 dto 를 응답하는게 의도된 사항 맞을까요?

2024-07-07 06:44 UTC, Hyeon9mak commented on src/main/resources/db/schema.sql
> +                          menuId INT,
여러가지 NOT NULL 을 챙겨줄 부분이 많아보이네요!

2024-07-07 07:21 UTC, alsswl commented on src/main/java/gift/controller/MemberController.java
> +    }
아하 그럼 기존에 하던 방식대로 계속 해야겠네요! 감사합니다

2024-07-07 07:21 UTC, alsswl commented on src/main/java/gift/controller/MemberController.java
> +    @PostMapping("/changePasswd")
password하면 너무 길어서 줄였는데 가독성에 문제가 생길 수 있을 것 같네요! 수정하겠습니다

2024-07-07 07:31 UTC, alsswl commented on src/main/java/gift/controller/MemberController.java
> +        }
아하 제가 계층의 역할에 대해서 잘 몰랐던 것 같네요 이 부분은 더 알아보고 수정하겠습니다 : )

2024-07-07 09:23 UTC, alsswl commented on src/main/java/gift/controller/MenuController.java
> +    }
컨트롤러는 무조건 하나여야한다고 생각했던 것 같습니다🥲 조원분들과 이야기해서 이해한대로 수정해보았습니다!

2024-07-07 09:24 UTC, alsswl commented on src/main/java/gift/controller/WishListController.java
> +
네 추가했습니다!

2024-07-07 09:27 UTC, alsswl commented on src/main/java/gift/domain/MenuRequest.java
> +}
와 처음 안 사실입니다! 인텔리제이에서 해당 설정 추가했습니다😀

2024-07-07 14:07 UTC, alsswl commented on src/main/java/gift/exception/EtcExceptionHandler.java
> +@ControllerAdvice
실수로 그런 것 같습니다 수정했습니다!

2024-07-07 14:12 UTC, alsswl commented on src/main/java/gift/repository/MemberRepository.java
> +    }
응답 dto를 응답하는 것으로 수정했습니다!

2024-07-07 14:14 UTC, alsswl commented on src/main/resources/db/schema.sql
> +                          menuId INT,
넵 수정했습니다!

2024-07-07 23:45 UTC, Hyeon9mak requested changes
안녕하세요 민지님! 2~3단계 진행 고생하셨어요!
학습을 위해 최대한 다양한 코멘트 남겨두었습니다.
모두 반영하지 않으셔도 되니, 천천히 살펴보시면서 하나씩 알아보시면 좋을거 같아요.
궁금하신 점 얼마든지 질문 남겨주세요.

2024-07-07 23:45 UTC, Hyeon9mak commented on build.gradle
> +    //compileOnly "org.springframework.boot:spring-boot-starter-security"
불필요해진 주석은 제거!

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/controller/MemberController.java
> +    JwtService jwtService;
아이고~ 여기도 접근제한자가 누락된거 같아요!

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/controller/MemberController.java
> +    }
`register`  와 `join` 으로 용어가 갈린 것 같네요!
요런 사소한 포인트로 동료 개발자들의 생산성에 차이가 생기니 잘 챙겨주시면 좋습니다.

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/controller/MemberController.java
> +        return ResponseEntity.status(HttpStatus.FORBIDDEN).body("findPassword is not allowed");
change password 와 find password 는 현재 지원하지 않는 기능일까요?

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/controller/MenuController.java
이제 view controller 를 명시적으로 분리해주셨으니, 이것들이 사용자 요청을 수행하기보단
명시적으로 정적 페이지만 응답하도록 변경해주면 더 좋겠네요!

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/controller/MenuRestController.java
> +@RequestMapping("/menu")
(사소하지만) `menu` 대신 `menus` 라는 복수형 표현을 이용하는 건 어떨까요?
RESTful 한 API 를 작성할 땐 `/members/{id}`, `/menus/{id}` 와 같은 방식으로 자원에 접근하게 되는데
"멤버들 중 id 가 {id} 인 멤버", "메뉴들 중 id 가 {id} 인 메뉴" 라는 느낌을 표현해주기 위함이에요!

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/controller/MenuRestController.java
> +    ) {
- `BindingResult` 를 사용해주신 이유가 있을까요?
- `@RequestBody` 와 `@ModelAttribute` 의 차이는 무엇일까요?

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/controller/MenuRestController.java
> +    }
update 에 잘 어울리는 HTTP method 가 있었던거 같아요 🤔

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/controller/WishListController.java
> +    ){
마찬가지로 read, delete 에 잘 어울리는 HTTP method 가 있었던거 같아요~!

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/domain/Member.java
> +    }
record 를 활용해보아도 좋겠네요 😄 
https://www.baeldung.com/java-record-keyword

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/repository/MemberRepository.java
> +    };
👍 반복 사용되는 mapping 동작을 멤버변수로 할당해주셨군요

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/repository/MemberRepository.java
> +
개행이~ 이런 사소한 가독성이~ 동료 개발자들의 생산성에~ (궁시렁 궁시렁..)

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/repository/WishListRepository.java
> +}
intellij 옵션을 설정해주셨으므로 저장버튼 한번씩 눌러주시면 자동으로 마지막 한 줄이 추가됩니다 ㅎㅎ

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/service/JwtService.java
> +
토큰을 발급할 때 발급일자와 만료일을 추가해주는 것도 좋겠네요! (Jwt builder 에 관련 체이닝 메서드가 있습니다.)
만료일자가 없으면 무한히 사용 가능한 토큰이 되어버려요!

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/service/JwtService.java
> +
토큰이 없다면 null 대신 바로 예외를 던져도 좋을거 같아요.

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/service/MemberService.java
> +    }
http, response 를 다루는 영역은 service 대신 controller 가 다뤄주는게 좋겠네요.
service 에서는 jwt 토큰을 발급한 후 그걸 반환해주는 걸로 충분할거 같아요!

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/java/gift/service/MemberService.java
> +    }
회원가입시에 jwt 토큰을 꼭 발급한 이유는 어떤 것일까요?

2024-07-07 23:45 UTC, Hyeon9mak commented on src/main/resources/db/schema.sql
> +);
😉 👍 
사용자 이메일(id) 가 유일한 구분점이라면 PK 혹은 UK 임을 명세해주면 더 좋겠네요~

2024-07-08 06:13 UTC, alsswl commented on src/main/java/gift/controller/MemberController.java
> +    JwtService jwtService;
넵 접근제한자 빠진 곳 모두 수정했습니다!

2024-07-08 06:19 UTC, alsswl commented on src/main/java/gift/controller/MemberController.java
> +        return ResponseEntity.status(HttpStatus.FORBIDDEN).body("findPassword is not allowed");
잘못된 로그인, 비밀번호 찾기, 비밀번호 변경 요청은 [403 Forbidden](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/403)을 반환한다.
이런 요구사항이 있어서 위와 같이 구현하였습니다!

2024-07-08 06:22 UTC, alsswl commented on src/main/java/gift/controller/MenuController.java
혹시 model.attribute도 사용자 요청을 수행하는 과정에 포함되는 것일까요??

2024-07-08 06:26 UTC, alsswl commented on src/main/java/gift/controller/MenuRestController.java
> +@RequestMapping("/menu")
네 수정했습니다! wishList는 url로 id값을 받지 않고 토큰으로 접근하고자 하는 아이디를 찾는데 그럼 wishList로 해야하는지 wishLists로 해야하는지 고민입니다. 제 생각은 우선 메서드들을 보니까 거의 wishlist 하나의 객체를 다뤄서 wishlist로 해야하는 것 같은데 멘토님의 의견이 궁금합니다😀

2024-07-08 06:59 UTC, alsswl commented on src/main/java/gift/controller/MenuRestController.java
> +    ) {
BindingResult를 사용한 이유는 Vaild하는 과정에서 오류가 발생했는지 확인하고, 만약 발생했다면 bindingResult를 통해 에러메세지를 가져오기 위함이었습니다!
두 어노테이션 모두 클라이언트 측에서 보낸 데이터를 java 코드에서 사용할 수 있는 오브젝트로 만들어주는 공통점이 있습니다.
@RequestBody는 요청 본문의 내용을 java 객체로 변환하여 setter가 없어도 되지만, @ModelAttribute는 java객체로 매핑하여 setter가 필요합니다.
엇 근데 record인 menuRequest에 setter가 없는데 왜 잘 동작했는지는 모르겠습니다. 이 부분은 구글링을 해도 잘 나오지 않습니다🥲

2024-07-08 10:00 UTC, alsswl commented on src/main/java/gift/controller/MenuRestController.java
> +    }
이전에 View를 반환할 때에는 put이랑 delete가 안된다고 해서 이렇게 했었는데 바꾸겠습니다!

2024-07-08 12:29 UTC, alsswl commented on src/main/java/gift/service/MemberService.java
> +    }
회원가입 하자마자 프로젝트를 진행할 수 있도록 하고, 테스트하기에 용이하게 하기 위해서 그런 것 같습니다!

2024-07-08 14:12 UTC, Hyeon9mak approved these changes
안녕하세요 민지님! 피드백 잘 반영해주셨습니다 👍 
나머지 사항들은 3주차 과제를 진행하면서 변경해도 좋을거 같아요.

제가 타임리프 관련한 이해도가 떨어져서 혼란을 드렸던거 같아요 🙏 
3주차부터는 더욱 집중해서 코멘트 남겨드리겠습니다.

3주차 과제에서 만나요~

2024-07-08 14:12 UTC, Hyeon9mak commented on src/main/java/gift/controller/WishListController.java
> +    private final JwtService jwtService;
> wishlist 하나의 객체를 다뤄서 wishlist로 해야하는 것 같은데 멘토님의 의견이 궁금합니다😀

언제 단건, 다건을 다룰지 모르므로 자원은 가능하면 복수명을 추천합니다!

2024-07-08 14:12 UTC, Hyeon9mak commented on src/main/java/gift/controller/WishListController.java
> +            @RequestHeader("Authorization") String token,
create, read, delete 모두 HTTP method 로 표현되므로 생략해도 좋을거 같아요 😉

2024-07-08 14:12 UTC, Hyeon9mak commented on src/main/java/gift/controller/MenuRestController.java
> +    ) {
라이브 코딩으로 확인 완료!
`@ModelAttribute` 에 값을 바인딩하는 구현체에서
default constructor 가 있으면 setter 를 사용,
없다면 setter 대신 constructor 를 활용함!

2024-07-08 14:12 UTC, merged