부산대 BE_황수환 2주차 과제 (2단계 ~ 3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #268
Opened 2024-07-04 17:29 UTC by HSHwan

고생많으십니다. 2, 3단계 과제 리뷰 부탁드립니다!
## 코드 작성하면서 느낀 점
로그인 기능을 거의 처음 구현하다 보니 어떻게 개발해나가야 할지 고민이 정말 많았습니다.
회원 테이블 구축을 시작으로 쉬지 않고 코드를 짜다보니 전체적인 구도가 이러지도 저러지도
못한 것 같은 느낌이 계속 들었던 것 같습니다.  
토큰 생성을 위해 JWT를 어찌저찌 배운 것 말고는 제대로 이해하지 못해서 혹시 잘못된 부분이 있다면
피드백을 자세하게 해주시면 감사하겠습니다!

## 코드 작성하면서 생긴 질문
1. 인증 관련해서 중복된 예외를 많이 생성하는 것 같아 예외 문자열 상수를 모아 놓은 ErrorMessage를 만드는 것이 좋을지 궁금합니다.

2. 스프링 시큐리티를 사용하지 않고 인증 기능을 구현해봤는데, 실제 스프링 시큐리티를 사용하는 것과 실질적인 차이가 있는지 궁금합니다.

2024-07-05 15:38 UTC, hocaron requested changes
수환님, 안녕하세요!

걱정을 많이 해주셨던 부분과는 다르게 구현 잘 해주셨습니다💯 같이 작업하는 입장에서 코멘트를 드린 부분이 있는데 확인 부탁드릴게요!

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/auth/security/JwtFilter.java
> +        String authHeader = request.getHeader("Authorization");
문자열이라 다른 분이 작업하다가 틀릴 가능성이 있어서 HttpHeaders.AUTHORIZATION 를 사용해도 좋을 것 같아요😎

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/auth/security/JwtFilter.java
> +        if (!authHeader.startsWith("Bearer ")) {
이 부분도 상수로 관리함으로써 실수로 문자열을 잘못 입력하는 것을 방지할 수 있을 것 같아요!

```suggestion
public static final String BEARER_PREFIX = "Bearer ";

        if (!authHeader.startsWith(BEARER_PREFIX)) {
```

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/auth/security/JwtFilter.java
> +            response.sendError(HttpStatus.FORBIDDEN.value(), "인증에 실패하였습니다.");
UNAUTHORIZED 대신 FORBIDDEN 을 사용한 이유가 궁금해요💭

fyi; https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
fyi; https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/auth/security/JwtFilter.java
> +        String token = authHeader.substring(7);
7이라는 숫자가 Bearer 를 제외한 의미를 가질 수 있게 상수로 정의하는 것은 어떨지 궁금해요💭

```suggestion
        private static final String BEARER_PREFIX = "Bearer ";
        private static final int BEARER_PREFIX_LENGTH = BEARER_PREFIX.length();
        
        String token = authHeader.substring(BEARER_PREFIX_LENGTH);
```

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/auth/security/JwtUtil.java
> +    private Long jwtExpirationInMs;
property 로 환경별로 관리할 수 있어서 너무 좋습니다👍

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/auth/security/JwtFilter.java
> +        } catch (Exception exception) {
이 에러는 언제 발생하는 에러인지 궁금합니다😀

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/config/FilterConfig.java
> +        registrationBean.addUrlPatterns("/members/*");
/members/ path 만 api/로 시작하는 prefix 가 없는 이유가 궁금해요💭

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/config/WebMvcConfig.java
> +        resolvers.add(loginMemberArgumentResolver);
리졸버로 구현하셨군요👍

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/member/validator/LoginMemberArgumentResolver.java
> +            Long memberId = (Long) webRequest.getAttribute("memberId", NativeWebRequest.SCOPE_REQUEST);
memberId 를 상수로 관리해도 좋을 것 같아요! attribute 값이 한쪽에서만 변경되는 것을 방지할 수 있을 것 같은데, 수환님은 어떻게 생각하시나요?!

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/product/api/ProductController.java
> +    @CrossOrigin
해당 API 에만 @CrossOrigin 이 추가된 이유가 궁금해요💭

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/wishlist/dao/WishesDao.java
> +                return null;
반환값이 null 인 경우에 npe 가 발생할 수 있을 것 같아요! 어떻게 개선하면 좋을까요?😀

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/member/application/MemberService.java
> +    public void registerUser(MemberDto user) {
member 와 user 가 회원이라는 같은 의미를 갖는 단어로 사용되고 있는 것 같아서, 하나로 통일해도 좋을 것 같아요!

2024-07-05 15:38 UTC, hocaron commented on src/main/java/gift/member/application/MemberService.java
> +        memberDao.save(MemberMapper.toEntity(user));
save 를 통해서 DataIntegrityViolationException 가 발생했을 때, 이메일 데이터를 중복 검증 하는 로직도 좋지만, email 필드를 기준으로 동일한 이메일이 있는지 확인하는 작없이 먼저 수행 되어도 좋을 것 같아요!

데이터 중복 검증을 데이터베이스 레이어에서 수행하고 있는 것 같고, DataIntegrityViolationException 이 제약조건 위반으로 발생하는 에러로 이메일 중복 외에도 발생할 가능성이 있을 것 같은 생각이 드는 것 같아요. 수환님은 어떻게 생각하시나요?!

2024-07-05 15:42 UTC, hocaron commented
1. 인증 관련해서 중복된 예외를 많이 생성하는 것 같아 예외 문자열 상수를 모아 놓은 ErrorMessage를 만드는 것이 좋을지 궁금합니다.

좋은 질문이라고 생각해요! 문자열 상수를 모아놓은 클래스도 좋고, 해당 타입 안정성을 챙길 수 있다는 점에서 enum 클래스도 좋을 것 같아요.

2. 스프링 시큐리티를 사용하지 않고 인증 기능을 구현해봤는데, 실제 스프링 시큐리티를 사용하는 것과 실질적인 차이가 있는지 궁금합니다.

스프링 시큐리티를 사용하면 이미 보안적으로 검증된 모듈을 재사용할 수 있다는 점과 OAuth2, OpenID 와 통합이 용이하다는 장점이 있을 것 같아요. 

하지만 요즘에는 인증 서버가 따로 구축되어있고, 해당 서버에서 인증 정보 검증을 모두 마친 후에 커스텀 헤더등으로 넘겨주면서 다른 서비스에서는 해당 헤더 값을 사용하는 방식을 많이 사용해요. 인증 서버에서만 인증 과정을 거치면 되고, JWT 가 아닌 커스텀한 토큰 값을 사용하는 경우도 있어 Spring Security 말고 직접 구현을 많이 하고 있습니다!

2024-07-06 05:40 UTC, HSHwan commented on src/main/java/gift/auth/security/JwtFilter.java
> +        String authHeader = request.getHeader("Authorization");
스프링에서 HTTP 메시지 헤더를 모아놓은 HttpHeaders가 있었군요!
바로 적용해보도록 하겠습니다.

2024-07-06 05:51 UTC, HSHwan commented on src/main/java/gift/auth/security/JwtFilter.java
> +        String token = authHeader.substring(7);
값을 상수로 정의해서 의미 부여하는 게 확실히 가독성을 높이는 것 같아 좋은 방법이라 생각합니다!
코드를 싹 훑어보면서 리팩토링해보겠습니다.

2024-07-06 05:53 UTC, HSHwan commented on src/main/java/gift/auth/security/JwtFilter.java
> +        if (!authHeader.startsWith("Bearer ")) {
해당 문자열과 문자열 길이 모두 상수로 정의해놓겠습니다!

2024-07-06 06:08 UTC, HSHwan commented on src/main/java/gift/auth/security/JwtFilter.java
> +            response.sendError(HttpStatus.FORBIDDEN.value(), "인증에 실패하였습니다.");
UNAUTHORIZED와 FORBIDDEN의 차이를 제대로 이해하지 못한 상태에서 짰던 코드인 것 같습니다.
지금 확인해보니 AUTHORIZATION의 필드 형식이 틀리니까 UNAUTHORIZED에 해당되니 바로 수정하도록 하겠습니다.
참고할만한 좋은 자료 알려주셔서 감사합니다!

2024-07-06 06:13 UTC, HSHwan commented on src/main/java/gift/auth/security/JwtFilter.java
> +        } catch (Exception exception) {
extractId 메서드에서 발생하는 AuthenticationFailedException입니다.
그런데 어떤 exception인지 확인이 제대로 안되는 것 같아 에러 타입을 수정하겠습니다.

2024-07-06 06:17 UTC, HSHwan commented on src/main/java/gift/member/application/MemberService.java
> +    public void registerUser(MemberDto user) {
member 이전에 user로 해놓아서 생긴 문제인 것 같습니다.
member 하나로 통일해놓겠습니다!

2024-07-06 06:19 UTC, hocaron commented on src/main/java/gift/auth/security/JwtFilter.java
> +        } catch (Exception exception) {
아핫! 그렇군요👍 확인 감사합니다!

2024-07-06 06:54 UTC, HSHwan commented on src/main/java/gift/config/FilterConfig.java
> +        registrationBean.addUrlPatterns("/members/*");
회원 부분만 해놓고 api 부분은 추가 못했던 것 같습니다.
바로 추가해놓겠습니다!

2024-07-06 07:07 UTC, hocaron commented
수환님, 요청 전후처리시에 인터셉터, 필터, AOP 중에 어디가 적절한지 고민을 많이 하게 되는 것 같아요!

심심할 때 보기 스택오버플로우 링크 공유드립니다!
https://stackoverflow.com/questions/35856454/difference-between-interceptor-and-filter-in-spring-mvc

2024-07-06 07:08 UTC, HSHwan commented on src/main/java/gift/auth/security/JwtFilter.java
> +        } catch (Exception exception) {
예외 타입 수정하였습니다! - [1bf2b40](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/268/commits/1bf2b40e426bc3d97702dfd843b25adb1930bf0d)

2024-07-06 08:05 UTC, HSHwan commented on src/main/java/gift/member/application/MemberService.java
> +        memberDao.save(MemberMapper.toEntity(user));
DAO의 예외 처리를 서비스 레이어로 옮겨서 하는 게 좋을 것 같습니다!
그 외에도 수정해야 할 내용이 있어서 합쳐서 리팩토링하겠습니다!

2024-07-06 08:05 UTC, HSHwan commented on src/main/java/gift/member/application/MemberService.java
> +    public void registerUser(MemberDto user) {
피드백 반영하였습니다! - [0aad1e1](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/268/commits/0aad1e15b2b77d5a0c758fafed1e685cb8a72cd3)

2024-07-06 08:05 UTC, HSHwan commented on src/main/java/gift/member/application/MemberService.java
> +        memberDao.save(MemberMapper.toEntity(user));
리팩토링 내용입니다! - [0aad1e1](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/268/commits/0aad1e15b2b77d5a0c758fafed1e685cb8a72cd3)

2024-07-06 08:09 UTC, HSHwan commented on src/main/java/gift/config/FilterConfig.java
> +        registrationBean.addUrlPatterns("/members/*");
피드백 내용말고도 상품 API 인증 내용 추가하였습니다! - [1bf2b40](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/268/commits/1bf2b40e426bc3d97702dfd843b25adb1930bf0d)

2024-07-06 08:09 UTC, hocaron commented on src/main/java/gift/member/application/MemberService.java
> +        memberDao.save(MemberMapper.toEntity(user));
레이어의 역할 분리 및 DB 에서 채번한 값을 사용하게 되어 좋습니다@

2024-07-06 08:27 UTC, HSHwan commented on src/main/java/gift/member/validator/LoginMemberArgumentResolver.java
> +            Long memberId = (Long) webRequest.getAttribute("memberId", NativeWebRequest.SCOPE_REQUEST);
좋은 방법이라 생각합니다!
그런데 JwtFilter가 전처리한 request를 사용하는 거라 JwtFilter의 REQUEST_ATTRIBUTE_NAME을 사용하는 것은 어떻게 생각하는지 궁금합니다!
```
// JwtFilter.java
// 수정 전
private static final String REQUEST_ATTRIBUTE_NAME = "memberId";
// 수정 후
public static final String REQUEST_ATTRIBUTE_NAME = "memberId";
```

2024-07-06 08:46 UTC, hocaron commented on src/main/java/gift/member/validator/LoginMemberArgumentResolver.java
> +            Long memberId = (Long) webRequest.getAttribute("memberId", NativeWebRequest.SCOPE_REQUEST);
말씀주신 것처럼 해당 필드를 관리하는 주체(클래스)에서 가져오는 것이 좋을 것 같습니다👍

2024-07-06 08:49 UTC, HSHwan commented on src/main/java/gift/product/api/ProductController.java
> +    @CrossOrigin
CORS 문제가 해결되는지 확인하려고 먼저 상품 API에 어노테이션을 추가했습니다.
이후에 관리자 화면, 로그인 등 여러 API에 적용해보려고 하는데
클래스 전체를 범위로 할지, 각각의 메서드 별로 할지 고민이 됩니다.

2024-07-06 08:55 UTC, HSHwan commented on src/main/java/gift/member/validator/LoginMemberArgumentResolver.java
> +            Long memberId = (Long) webRequest.getAttribute("memberId", NativeWebRequest.SCOPE_REQUEST);
피드백 내용 반영했습니다! - [ea45424](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/268/commits/ea4542403df866c08a36021c01179d658c337ebf)

2024-07-06 09:11 UTC, hocaron commented on src/main/java/gift/product/api/ProductController.java
> +    @CrossOrigin
보안이 중요한 관리자 화면이나 로그인 API 등은 메서드별로 CORS 정책을 설정하여 필요에 따라 제한을 두는 고민 좋은 것 같아요👍
수환님께서 고민 후에 적절하게 적용해주시면 좋을 것 같아요!

은근 요 개념이 뭔지 질문 들어왔을 때, 정확히 대답을 못하는 경우가 있어서 적용하고 질문 들어왔을 때 어떻게 답변 드리면 좋을지 고민해봐도 좋을 것 같습니다👍

2024-07-06 09:22 UTC, HSHwan commented on src/main/java/gift/wishlist/dao/WishesDao.java
> +                return null;
null을 반환하는 대신 SQLException을 throw하면 될 것 같습니다.
그런데 findWishlistOfMember 메서드를 ProductDao의 findAll 메서드처럼 수정하려고 해서
개선 사항을 적용 못할 것 같습니다!

2024-07-06 09:35 UTC, hocaron commented on src/main/java/gift/wishlist/dao/WishesDao.java
> +                return null;
현재 product 테이블 스키미가 아래와 같아서 리팩토링해주신 방향대로 해도 좋을 것 같습니다! 따로 null 을 반환하여 npe 를 발생할 수 있는 가능성을 높일 수 있을 것 같아서 질문 드리게되었습니다! 만약 image_url 도 not null 이어야 한다면 DB 컬럼 설정에 추가해도 좋을 것 같아요!😀

```
CREATE TABLE product (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(15) NOT NULL,
    price INT NOT NULL CHECK (price >= 0),
    image_url VARCHAR(255)
);
```

2024-07-06 09:37 UTC, hocaron approved these changes
수환님, 2주차 과제 수행하시느라 고생 많으셨습니다💪
코드 퀄리티가 점점 높아지는 것 같습니다! 코드 작성하시면서 고민하셨던 부분 공유해주셔서 감사합니다.

코멘트에 대한 부분이 모두 해결되어서 PR 은 머지하겠습니다.
고민이나 궁금한 부분은 코멘트나 DM 주시면 확인하겠습니다🫡

2024-07-06 09:38 UTC, merged