전남대 BE_김수랑 2주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #269
Opened 2024-07-04 18:13 UTC by rdme0

### 궁금한점
제가 Jwt 증명 부분에서 코드를
```java
    private static final String secret = "secret key";
    private static final JwtParser jwtParser = Jwts.parser().setSigningKey(secret);
// ....
    public static Boolean validateToken(String token) {
        try {
            jwtParser.parseClaimsJws(token); // 서명 검증
        } catch (JwtException e) {
            return false;
        }
        return true;
    }
```

저는 이런식으로 파라미터를 토큰 하나만으로 구현을 했는데  
다른 방법도 있는 것 같아서 찾아보니  
`public static Boolean validateToken()` 의 파라미터를 token 말고도 유저의 다른 정보들 까지 (예 : UserDTO의 email) 세팅해놓고 토큰을 디코드 해서 나온 값과 실제 값과 대조해서 무결성을 검증하는 방법 (예 : 토큰의 페이로드의 이메일 부분과 UserDTO의 email 값이 같은지 등 )도 있어서 제가 구현한 방법이 올바른 코드인지 궁금합니다.

2024-07-07 10:49 UTC, Hongdonggeon requested changes
안녕하세요 수랑님 전체적으로 잘 구현해주셨습니다! 
간단한 커멘트 남겨놓았으니 반영하시면서 궁금한 것 있으시면 DM 주세요! 
수고하셨습니다~

2024-07-07 10:49 UTC, Hongdonggeon commented on src/main/java/gift/config/UserDatabaseProperties.java
> +public class UserDatabaseProperties {
이 클래스는 사용하지 않는 것 같네요!

2024-07-07 10:49 UTC, Hongdonggeon commented on src/main/java/gift/util/JwtUtil.java
> +    private static final String secret = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
시크릿키를 공개적으로 올려도될까요? yml로 따로 관리하는게 좋을 것 같아요

2024-07-07 10:49 UTC, Hongdonggeon commented on src/main/resources/application.properties
> +spring.h2.console.user.enabled=true
user와 product 데이터베이스를 따로 관리하시네요. 
데이터베이스는 하나로만 관리하고 테이블로 구분할수도 있었을 것 같은데 분리한 이유가 있을까요?

2024-07-07 10:49 UTC, Hongdonggeon commented on src/main/java/gift/service/WishListService.java
> +            throw new BadRequestException("올바르지 않은 JSON 입니다.");
메시지가 더 유저 친화적이면 좋을 것 같아요

2024-07-07 10:49 UTC, Hongdonggeon commented on src/main/java/gift/service/WishListService.java
> +    private final UserService userService;
사용하지 않는 필드가 있네요

2024-07-07 10:49 UTC, Hongdonggeon commented on src/main/java/gift/service/ParameterValidator.java
> +    private final UserDao userDao;
사용하지 않는 필드가 있네요

2024-07-07 10:49 UTC, Hongdonggeon commented on src/main/java/gift/entity/WishList.java
> +        if (index == -1) {
존재하지 않은 경우에 index가 -1이죠? 
리스트의 contains 메서드를 사용한게 더 코드가 직관적으로 다가올 것 같아요!
```
products.contains(product)

2024-07-07 11:01 UTC, Hongdonggeon commented
- 새로고침 했을 때 로그인 풀리는 이슈
제가 수랑님 어플리케이션 확인해봤을때는 새로고침해도 로그인이 안풀리더라구요,,? 혹시 해결하신걸까요

- 토큰은 남아있지만 사용자가 삭제된 경우에는 현재 토큰은 의미 없어지는 값이 되게 되고, 회원가입을 다시 해야하지 않을까요? 토큰 검증에 성공했지만 회원이 존재하지 않는 경우에 회원가입 화면으로 보내는 것도 방법일 수 있을 것 같아요

2024-07-07 14:12 UTC, rdme0 commented
- 다른 페이지에서는 괜찮은데  
http://localhost:8080/api/products/wishes  
장바구니에서만 새로고침을 하면 `401 UNAUTHORIZED`가 뜹니다 ㅠㅠ 제가 원인을 추측하기로는 로그인 자체는 풀리지가 않는데 브라우저 버튼으로 새로고침 하는 순간에는 로그인은 되어있지만 토큰을 서버로 보낼 수가 없어서 생기는 버그 같습니다

- 두 번째 질문은 @rdme0
[✨ feat: 회원이 아닐 때 회원가입 창으로 보내도록 기능 추가](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/269/commits/7fa7ae0e255da9bce1a6a1f1bb1c30ea8c46b07b)
[7fa7ae0](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/269/commits/7fa7ae0e255da9bce1a6a1f1bb1c30ea8c46b07b)
이렇게 해결 하였습니다!  

이 밖에도 리뷰어님의 피드백을 반영하였고, Step 1때 피드백도 (https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/153) 반영하였는데  
만약 DTO에서만 유효성 검사를 한다면 만약 협업 시에는 다른 사람의 실수에 의해서 잘못된 데이터가 들어올 수 있기 때문에 유효성 검사를 (DTO-Controller) + (DAO - 도메인) 이렇게 2중으로 하게 리팩터링 하였습니다!  
  
저는 검증의 역할을 만약 DTO만 하게 된다면 만약 유효하지 않는 데이터가 왔을 때 컨트롤러에서 바로 catch하면 되어서 도메인 검사보다 더 효율적이라고 생각하지만, 개발자의 실수로 controller보다 더 깊은 곳에서 잘못된 DTO의 조작이 일어날 경우 잘못된 데이터가 DB에 들어갈 수 있다는 리스크가 있다고 생각해서 효율성은 높아지지만, 리스크는 좀 있다고 생각하고  
만약 도메인에서만 하게 된다면 앞의 반대로 효율성은 낮아지지만 상대적으로 로우 리스크라고 생각합니다.  
따라서 이중으로 유효성 검사를 하게 된다면 한번 하는 것 보다 안정성이 더 높아지고 효율성도 챙길 수 있다고 생각해서 이렇게 이중으로 리팩터링 하였습니다.  

또한, Jwt secret key를 제가 yml을 쓸 줄 몰라서 properties 파일로 분리 시켰고 git ignore 하였습니다!

2024-07-08 15:58 UTC, Hongdonggeon commented
일단 확인해봤을 때 수랑님이 의심한 것처럼 새로고침할 때 요청값에 토큰이 포함되지 않은 것 같습니다. 일단 저도 원인이 뭔지 한번 같이 찾아볼게요! 

- 정상적으로 토큰이 헤더에 포함된 경우
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/67885363/6447e44d-5f5a-4b94-a4bc-7b1aaa597aa0)

![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/67885363/da9d8580-64a5-4954-8ee3-4bc3bdf1c042)

- 새로고침했을 때 헤더에 미포함
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/67885363/e0067d07-5e0c-4806-8ead-152bb0bfc56d)

![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/67885363/047e6885-9219-4fb0-a47f-d5efec9b6347)

- 브라우저에 토큰 살아있음
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/67885363/6e228a5e-58eb-4033-8f77-12ada92564b9)

2024-07-08 16:02 UTC, Hongdonggeon approved these changes
안녕하세요 수랑님! 
리뷰 반영하시느라 수고 많으셨습니다! 
열심히 학습하신 덕분에 성장하는 모습이 보여 보기 좋네요 :) 
현재 새로고침할 때 토큰이 넘어가지 않는 버그는 확인했고요 저도 원인 파악하는데로 코멘트 드리도록 하겠습니다! 원인 파악은 했으니 수랑님도 해결 방법 찾아보시면 도움이 많이 될 것 같습니다! 
미션 진행하느라 수고하셨어요 머지할게요~

2024-07-08 16:02 UTC, merged