전남대 BE_서영우 2주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #272
Opened 2024-07-04 19:13 UTC by westzeroright

안녕하세요 코치님!! 좋은 아침입니다☀️

이번 주는 다른 공부에 집중하느라 과제 제출이 조금 늦었네요ㅜㅜ
바쁘시겠지만 1,2 단계 코드리뷰 부탁드립니다!

아직 많이 부족한 과제이지만 3단계 과제 진행하면서 패키지 구조 설정과 조금씩 디테일한 부분을 추가하도록 하겠습니다.

감사합니다!! 오늘도 화이팅하세요~

2024-07-06 15:37 UTC, pkeugine requested changes
안녕하세요 영우님!
분명 리뷰요청을 주셨는데 제 리뷰 리스트에 이 PR 이 올라오질 않아서 이제 확인했네요 🤔 

남겨놓은 코멘트는 답변을 달아주시거나, step 3 를 리팩토링하면서 적용해보시면 될 것 같아요.
step 1 PR 을 올리기 전에 step 3 까지 미리 작업해주신다고 했는데,
빨리 작업하는 것은 좋지만 리뷰를 반영하고 리팩토링하는 과정도 중요한 것 같아요.
그러니 리뷰를 남기면 그 리뷰와 관련된 변경사항은 해당 단계나 다음 단계에 포함해보죠.
PR 이 많다보니 이전에 남겼던 리뷰를 모두 트래킹하며 확인하는게 꽤 어렵거든요 ㅠ

그건 그거고! 프로젝트 잘 만들어주셨습니다!
바로 머지하고 싶지만, 현재 conflict 가 있어서 그러지 못하고 있어요.
이 부분 해결해주시면 머지하도록 하겠습니다. :)

2024-07-06 15:37 UTC, pkeugine commented on README.md
> +# spring-gift-wishlist
이전 단계에서 git 과 커밋에 대한 리뷰를 남겼었죠? 답변도 확인했어요 👍 
학습하고 개선하려는 모습이 정말 보기 좋습니다!

조금 더 구체적인 리뷰를 남겨보자면
미리 작업하시다보니 pr 과 머지하려는 브랜치 간의 충돌(conflict) 가 발생하는 것 같아요.
squash merge 를 하기 때문에 이런 일이 발생하고 있는데,
이를 방지하기 위해 rebase 를 학습해보시면 될 것 같습니다 :)

리뷰를 하는 과정에서도 이전 단계의 코드가 해당 단계와 섞여있다보니 리뷰할 때 약간 어려움이 있어요!
이는 제가 리뷰할 때 힘든것도 있지만,
업무를 진행할 때 팀원들끼리 리뷰하는 상황에서도 git 커밋을 잘 관리하면 상호 리뷰할 때 도움이 많이 될거예요.
거의 필수 지식이니 꼭 잘 학습해보면 좋을 것 같네요!

2024-07-06 15:37 UTC, pkeugine commented on src/main/java/gift/JwtTokenUtil.java
> +            .setExpiration(exp)
<img width="1015" alt="Screenshot 2024-07-07 at 12 01 33 AM" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/48251668/0ffab331-45ba-4ef3-9106-28e725ef8c58">

`Keys.secretKeyFor()`, `setSubject()`, `setIssueAt()`, `setExpiration()` 등의 메서드는 deprecated 되었어요. `SignatureAlgorithm` 도 그렇구요. 참고한 문서나 코드 외에도 이런 부분을 확인해보며 api 를 사용해보면 좋을 것 같네요!

2024-07-06 15:37 UTC, pkeugine commented on src/main/java/gift/JwtTokenUtil.java
> +        Date now = new Date(nowMillis);
시간과 날짜를 나타낼 때 사용하는 클래스는 꽤 다양한데요, `Date` 외에도 `LocalDateTime`, `LocalDate`, `LocalTime` 같은 클래스도 있어요. 이들이 어떤 차이가 있는지 보고, 다른 것을 사용해야겠다 싶으면 바꿔봐도 좋을 것 같아요.

해당 클래스 파일을 열어보면 주석으로 그 클래스에 대한 설명이 굉장히 자세하게 적혀있어요.
그리고 그걸 만든 사람들이 쓴 내용이라 그 어느 블로그보다 정확하구요!
그러니 그 내용을 읽어보면 도움이 될 겁니다 :)

2024-07-06 15:37 UTC, pkeugine commented on src/main/java/gift/JwtTokenUtil.java
> +        long expMillis = nowMillis + 3600000;
주석을 지우고 3600000 이라는 값을 상수로 나타내보면 어떨까요?
[이런 숫자를 magic number 라고 하는데요](https://stackoverflow.com/questions/47882/what-are-magic-numbers-and-why-do-some-consider-them-bad), 코드로 이 값이 무엇을 나타내는지 나타내보도록 하죠!

2024-07-06 15:37 UTC, pkeugine commented on src/main/java/gift/Member.java
> +    }
setter 를 없애는 방향으로 리팩토링 해보아요!

2024-07-06 15:37 UTC, pkeugine commented on src/main/java/gift/MemberController.java
> +            String token = jwtTokenUtil.generateToken(member.getEmail());
```suggestion
            String token = JwtTokenUtil.generateToken(member.getEmail());
```

`JwtTokenUtil` 클래스는 이름에서 나타내주셨듯  utility 클래스이기 때문에 bean 으로 관리할 필요도 없고,
객체를 만들어서 사용하지 않아도 돼요.
그러니 빈으로 등록하지 말고 사용해보면 어떨까요? 제가 제시한 부분 말고 다른 부분도 약간 변경해야할 것 같네요!

* 빈으로 등록하지 않기
* `MemberController` 에 주입해주는 부분을 제거하기

이 두가지를 해보시면 됩니다!

2024-07-06 15:37 UTC, pkeugine commented on src/main/java/gift/MemberController.java
> +        }
`GlobalExceptionHandler` 에서 처리해볼 수도 있지 않을까요?
예외처리에 대한 책임을 한 곳에 모아주는거죠 :)

2024-07-06 15:37 UTC, pkeugine commented on src/main/java/gift/MemberController.java
> +    public ResponseEntity<?> registerMember(@RequestBody Member member) {
`?` 는 무엇이고, 왜 여기서 사용될까요?

2024-07-06 15:37 UTC, pkeugine commented on src/main/java/gift/MemberController.java
> +        Optional<Member> existMember = memberDao.findMember(member);
슬슬 layered architecture 를 도입해보면 어떨까요?
DAO 를 controller 에서 직접적으로 사용하지 않고, 중간 계층을 두는거죠!
그렇게 된다면 `service` 라는 개념을 사용하시게 될 것 같네요!

2024-07-06 15:37 UTC, pkeugine commented on src/main/java/gift/MemberDao.java
> +    private JdbcClient jdbcClient;
`JdbcClient` 말고 `JdbcTemplate` 이라는 것이 있는데, 이것을 사용해보는 것을 추천드려요.
둘이 어떤 차이가 있는지 알아보면 좋겠네요.

아 그리고 필드 주입 방식을 사용해주고 계신데, 이 방식말고 다른 방식으로 어떤 것이 있는지 한 번 알아보도록 하죠!
(이미 다른 방식을 사용하고 계십니다.)
그리고 그 방식들의 차이 역시 함께 알아보아요! 알아볼게... 참 많죠? ㅎㅎ 😅

2024-07-06 15:37 UTC, pkeugine commented on src/main/java/gift/MemberController.java
> +@RequestMapping("/member")
url 에서는 보통 리소스를 어떻게 표기할까요?
restful api 에 대해 한 번 확인해보시는 것을 추천드려요.
내용이 조금 많아서 한 번에 모든 것을 다 확인하거나 적용할 필요는 없고,
[지금 단계에서 확인해보면 좋을 내용](https://restfulapi.net/resource-naming/)을 링크로 남겨볼게요!

2024-07-07 15:04 UTC, westzeroright commented on src/main/java/gift/MemberController.java
> +            String token = jwtTokenUtil.generateToken(member.getEmail());
멘토님 덕분에 유틸리티 클래스에 대해서 다시 한번 이해하고 넘어갈 수 있었습니다:)구체적인 제시 감사합니다!

2024-07-07 15:10 UTC, westzeroright commented on README.md
> +# spring-gift-wishlist
알아보았을 때 rebase는 머지할 브랜치의 커밋을 그대로 옮겨 오고, squash는 머지할 브랜치의 커밋을 하나의 커밋으로 합치는 것으로 이해했습니다.

아직 잘 모르겠는 부분이 있는데 조금 더 과제를 하면서 나중에 질문 드리겠습니다..!

2024-07-08 05:42 UTC, westzeroright commented on src/main/java/gift/MemberController.java
> +    public ResponseEntity<?> registerMember(@RequestBody Member member) {
자바 제네릭에서 T는 타입을 대신 명시하는데 특정 범위로 사용하고 싶고 그 특정 범위가 모든 타입이 가능하도록 할 때 ?를 사용합니다. 해당 메서드에서 두 타입을 반환하므로 반환타입을 특정 짓지 않기 위해서 사용하였습니다.

2024-07-09 17:03 UTC, westzeroright commented on src/main/java/gift/JwtTokenUtil.java
> +            .setExpiration(exp)
반영했습니다!

2024-07-09 17:03 UTC, westzeroright commented on src/main/java/gift/JwtTokenUtil.java
> +        Date now = new Date(nowMillis);
✅

2024-07-09 17:03 UTC, westzeroright commented on src/main/java/gift/JwtTokenUtil.java
> +        long expMillis = nowMillis + 3600000;
반영했습니다!

2024-07-09 17:03 UTC, westzeroright commented on src/main/java/gift/Member.java
> +    }
반영했습니다!

2024-07-09 17:03 UTC, westzeroright commented on src/main/java/gift/MemberController.java
> +            String token = jwtTokenUtil.generateToken(member.getEmail());
반영했습니다!

2024-07-09 17:03 UTC, westzeroright commented on src/main/java/gift/MemberController.java
> +        }
반영했습니다!

2024-07-09 17:04 UTC, westzeroright commented on src/main/java/gift/MemberController.java
> +        Optional<Member> existMember = memberDao.findMember(member);
반영했습니다!

2024-07-09 17:04 UTC, westzeroright commented on src/main/java/gift/MemberDao.java
> +    private JdbcClient jdbcClient;
반영했습니다!

2024-07-09 17:04 UTC, westzeroright commented on src/main/java/gift/MemberController.java
> +@RequestMapping("/member")
반영했습니다!

2024-07-10 13:31 UTC, pkeugine approved these changes
다음 미션 진행 중이라 이만 머지하도록 하겠습니다.

2024-07-10 13:31 UTC, merged