전남대 BE_모아림 2주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #277
Opened 2024-07-04 22:21 UTC by ariimo

Dto와 Entity의 따로 두는 이유를 공부한 후 그 목적을 지키려고 노력했습니다만, 결과적으로는 그냥 Dto와 Entity를 따로 두기만 한 상태인 것 같아 고민이 많습니다. 따로 두었다는 것 자체만으로 유지보수성이나 불필요한 데이터 전송을 막는 Dto의 장점이 존재한다고 할 수 있는 걸까요..?

2024-07-05 03:42 UTC, dc-choi requested changes
안녕하세요~ 아림님~

2주차 step1 진행하시느라 고생하셨습니다~

자세한 내용은 코멘트에 남겼습니다. 확인 부탁드립니다~

질문에 대한 답변을 드려보도록 하겠습니다~ 추가 질문이 있다면 언제든 편하게 말씀해주세요~

> Dto와 Entity의 따로 두는 이유를 공부한 후 그 목적을 지키려고 노력했습니다만, 결과적으로는 그냥 Dto와 Entity를 따로 두기만 한 상태인 것 같아 고민이 많습니다. 따로 두었다는 것 자체만으로 유지보수성이나 불필요한 데이터 전송을 막는 Dto의 장점이 존재한다고 할 수 있는 걸까요..?

이 부분에 대한 답으로는 현재 당장은 시스템이 작아서 지금 당장은 와닿지 않겠지만 추가적으로 유지보수할 EndPoint(API)가 많아진다면 어려움이 있습니다. 

`Entity`의 변경 하나로 모든 EndPoint가 변경되지 않고 각 EndPoint마다 DTO를 두어 API에 맞는 응답을 유지시켜주는 것이 유지보수성에 좋습니다.

`DTO`란 무엇이고 `Entity`가 무엇인지에 대한 고민을 조금 더 해보시기 바랍니다.

`DTO`에 대해서 고민해볼 수 있는 링크 몇가지 드리겠습니다.

https://velog.io/@aidenshin/DTO%EC%97%90-%EA%B4%80%ED%95%9C-%EA%B3%A0%EC%B0%B0

https://velog.io/@p4rksh/Spring-Boot%EC%97%90%EC%84%9C-%EA%B9%94%EB%81%94%ED%95%98%EA%B2%8C-DTO-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0

2024-07-05 03:42 UTC, dc-choi commented on src/main/java/gift/service/ProductService.java
> +        validationService.checkValid(product);
검증하는 로직이 `Service`단에 있는게 올바른가요? `Service`와 `Controller`의 목적과 맞지 않아 보입니다. 검증은 `Controller`의 역할이라고 생각되긴 합니다.

2024-07-05 03:42 UTC, dc-choi commented on src/main/java/gift/Product.java
> +    @Pattern(regexp = "^(?!.*카카오).*$", message = "'카카오'가 포함된 문구는 담당 MD와 협의한 경우에만 사용 가능합니다")
마찬가지로 `Entity`에서 예외를 처리하지 않고 `DTO`에서 처리하는 게 좋아보입니다. `Entity`와 `DTO`의 역할에 대해서 좀 더 고민해주세요!

2024-07-05 03:42 UTC, dc-choi commented on src/main/java/gift/ProductDto.java
> +
특별히 `\n`이 두번 들어간 이유가 있나요? 없다면 수정해주시면 감사하겠습니다~!

2024-07-05 03:42 UTC, dc-choi commented on src/main/java/gift/controller/PageController.java
> +
특별히 `\n`이 두번 들어간 이유가 있나요? 없다면 수정해주시면 감사하겠습니다~!

2024-07-05 03:42 UTC, dc-choi commented on src/main/java/gift/service/ValidationService.java
> +public class ValidationService {
Controller에서 예외를 처리하게 된다면 특별히 이 클래스가 필요한지에 대한 고민도 필요해보입니다!

2024-07-05 04:25 UTC, ariimo commented on src/main/java/gift/ProductDto.java
> +
수정했습니다!!

2024-07-05 04:26 UTC, ariimo commented on src/main/java/gift/controller/PageController.java
> +
수정했습니다!

2024-07-05 04:52 UTC, ariimo commented
안녕하세요 멘토님!! 
멘토님의 조언을 듣고 유효성 검사 위치를 Product에서 ProductDto로 수정하였습니다!

수정을 진행하며 궁금한 점이 생겼는데, 제가 참고했던 책에서는 '도메인 지식이라고 할 수 있는 유효성에 대한 검사는 도메인(Entity) 객체가 하는 것이 적절하고, 그 외의 도메인 지식과 무관하게 데이터 그 자체가 유효한지 아닌지를 검사할 때는 Dto 가 적절하다'라는 기준이 적혀있었습니다. '상품 이름의 길이는 확실히 도메인 지식이 아닐까?'라는 생각(+이왕 넣는 거 모두 Entity에 넣자!)과 함께 Entity에서 예외를 처리하게 되었습니다. 
이 책에서는 위와 같은 기준을 제시한 이유가 도메인 지식을 밖으로 빠져나가게 하지 않기 위해서라고 했는데, 혹시 강사님께서 생각하시는 '**예외처리를 DTO에서 해야 하는 이유**'를 알려주시면 저의 개발 실력 향상에 정말 큰 도움이 될 것 같습니다..!! 🥲

2024-07-05 04:59 UTC, ariimo commented
또한, 강사님이 남겨주신 Entity와 Dto 자료를 읽고 ModelMapper 라이브러리를 통한 변환 방법을 알게되었습니다. 혹시 이는 step3까지의 과정을 진행한 뒤 수정해도 될까요??

2024-07-05 05:56 UTC, dc-choi commented
아림님 너무 좋은 질문 주셔서 감사합니다!

저 역시도 부족하지만 제가 아는 선에서 답을 드려보려고 합니다.

> 안녕하세요 멘토님!! 멘토님의 조언을 듣고 유효성 검사 위치를 Product에서 ProductDto로 수정하였습니다! 수정을 진행하며 궁금한 점이 생겼는데, 제가 참고했던 책에서는 '도메인 지식이라고 할 수 있는 유효성에 대한 검사는 도메인(Entity) 객체가 하는 것이 적절하고, 그 외의 도메인 지식과 무관하게 데이터 그 자체가 유효한지 아닌지를 검사할 때는 Dto 가 적절하다'라는 기준이 적혀있었습니다.

이 부분은 도메인 모델 패턴에 나오는 이야기를 차용해서 말씀을 드리려고 합니다.

우리가 도메인이라고 부를 수 있는 부분은 Product를 전제로 하였을 때는 재고 감소 같은 현실에서 일어나는 일에 대한 내용입니다.

아마 책에서는 이 부분에 대한 이야기를 하는 것으로 보입니다! 재고 감소를 예를 들어 설명드리자면 재고가 0인 경우 감소되면 안되기 떄문에 이에 대한 예외처리가 필요하게 됩니다.

다음 코드의 예시를 보시면 이해가 더 편하실 거에요. 편의상 의사코드로 설명을 드리는 점 양해 부탁드려요!

```java
Public ProductEntity {
    private Long Stock;

    public Long minusStock() {
        // 재고가 0일 경우 예외처리
        // 재고 감소
    }
}
```

> '상품 이름의 길이는 확실히 도메인 지식이 아닐까?'라는 생각(+이왕 넣는 거 모두 Entity에 넣자!)과 함께 Entity에서 예외를 처리하게 되었습니다. 이 책에서는 위와 같은 기준을 제시한 이유가 도메인 지식을 밖으로 빠져나가게 하지 않기 위해서라고 했는데, 혹시 강사님께서 생각하시는 '예외처리를 DTO에서 해야 하는 이유'를 알려주시면 저의 개발 실력 향상에 정말 큰 도움이 될 것 같습니다..!! 🥲

위에서 설명드린대로 상품 이름의 길이나 상품의 이름이 null인 경우, "", " "인 경우는 데이터 그 자체가 유효한지에 대한 검사라고 생각합니다. 그래서 그 기준에 따라 DTO에서 예외처리를 하는 것으로 가이드를 드렸어요~!

2024-07-05 05:58 UTC, dc-choi commented
> 또한, 강사님이 남겨주신 Entity와 Dto 자료를 읽고 ModelMapper 라이브러리를 통한 변환 방법을 알게되었습니다. 혹시 이는 step3까지의 과정을 진행한 뒤 수정해도 될까요??

네 얼마든지 상관없습니다~! 왜 사용하는지에 대한 이유가 합당하다면 상관없습니다! 혹시 어떤 이유때문에 사용하려고 하시는지 알 수 있을까요?

2024-07-05 05:58 UTC, dc-choi commented
> 안녕하세요 멘토님!! 멘토님의 조언을 듣고 유효성 검사 위치를 Product에서 ProductDto로 수정하였습니다!
> 
> 수정을 진행하며 궁금한 점이 생겼는데, 제가 참고했던 책에서는 '도메인 지식이라고 할 수 있는 유효성에 대한 검사는 도메인(Entity) 객체가 하는 것이 적절하고, 그 외의 도메인 지식과 무관하게 데이터 그 자체가 유효한지 아닌지를 검사할 때는 Dto 가 적절하다'라는 기준이 적혀있었습니다. '상품 이름의 길이는 확실히 도메인 지식이 아닐까?'라는 생각(+이왕 넣는 거 모두 Entity에 넣자!)과 함께 Entity에서 예외를 처리하게 되었습니다. 이 책에서는 위와 같은 기준을 제시한 이유가 도메인 지식을 밖으로 빠져나가게 하지 않기 위해서라고 했는데, 혹시 강사님께서 생각하시는 '**예외처리를 DTO에서 해야 하는 이유**'를 알려주시면 저의 개발 실력 향상에 정말 큰 도움이 될 것 같습니다..!! 🥲

2024-07-05 08:38 UTC, ariimo commented
> > 또한, 강사님이 남겨주신 Entity와 Dto 자료를 읽고 ModelMapper 라이브러리를 통한 변환 방법을 알게되었습니다. 혹시 이는 step3까지의 과정을 진행한 뒤 수정해도 될까요??
> 
> 네 얼마든지 상관없습니다~! 왜 사용하는지에 대한 이유가 합당하다면 상관없습니다! 혹시 어떤 이유때문에 사용하려고 하시는지 알 수 있을까요?

멘토님께서 해당 링크를 보내주신 이유가 ModelMapper 라이브러리 사용을 권장하시는 줄 알고 여쭸봤던 질문입니다..!

2024-07-05 08:56 UTC, ariimo commented
시간이 부족하여 step2 브랜치를 따로 생성하지 못했습니다ㅠㅠ. 항상 감사드립니다!!

2024-07-05 12:46 UTC, dc-choi requested changes
아림님~ Step2도 확인하였습니다~!

자세한 내용은 코멘트에 남겨드렸어요~! 확인 부탁드려요~!

2024-07-05 12:46 UTC, dc-choi commented on src/main/java/gift/GlobalExceptionHandler.java
> +    @ExceptionHandler(Exception.class)
기타 예외처리를 따로 처리하는 부분은 좋은거 같네요!

2024-07-05 12:46 UTC, dc-choi commented on src/main/java/gift/JWTUtil.java
> +            .claim("email", email)
회원의 권한에 대한 부분이 작성되지 않았습니다. 회원에 권한에 따라 API 접근을 막을 수 있습니다. 이 부분 다시 확인 부탁드립니다.

2024-07-05 12:46 UTC, dc-choi commented on src/main/java/gift/Application.java
> +        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS members(email VARCHAR(255), password VARCHAR(255))");
회원의 권한에 대한 부분이 작성되지 않았습니다. 이 부분 다시 확인 부탁드립니다.

2024-07-05 12:46 UTC, dc-choi commented on src/main/java/gift/classes/Exceptions/RegisteringEmailIsAlreadyExists.java
> +public class RegisteringEmailIsAlreadyExists extends Exception {
이 부분은 크게 두가지 문제가 있다고 생각합니다.

1. `GlobalExceptionHandler`에서 따로 예외가 처리되지 않습니다. 그러면 Exception으로 빠지게 되는데 이떄 HTTP Status Code가 500번대 입니다. 이는 Server Error로써 현재 상태와 맞지 않는 문제가 있습니다.
2. 이메일로 이미 회원가입을 한 경우에만 예외를 생각하신 거 같습니다. 하나의 객체 안에서 메시지를 통해서 어떤 오류가 발생하였는지 확인할 수 있는 객체로 이름을 변경하였으면 좋겠습니다.

2024-07-05 12:46 UTC, dc-choi commented on src/main/java/gift/classes/Exceptions/RegisteringEmailIsAlreadyExists.java
> +public class RegisteringEmailIsAlreadyExists extends Exception {
이 부분은 크게 두가지 문제가 있다고 생각합니다.

1. `GlobalExceptionHandler`에서 따로 예외가 처리되지 않습니다. 그러면 Exception으로 빠지게 되는데 이떄 HTTP Status Code가 500번대 입니다. 이는 Server Error로써 현재 상태와 맞지 않는 문제가 있습니다.
2. 이메일로 이미 회원가입을 한 경우에만 예외를 생각하신 거 같습니다. 하나의 객체 안에서 메시지를 통해서 어떤 오류가 발생하였는지 확인할 수 있는 객체로 이름을 변경하였으면 좋겠습니다.

2024-07-05 12:46 UTC, dc-choi commented on src/main/java/gift/controller/MemberController.java
> +        catch(RegisteringEmailIsAlreadyExists e) {
`Controller`에서 따로따로 예외처리에 대한 로직을 검증할지 `GlobalExceptionHandler`에서 전역으로 예외 처리를 할지에 대한 고민이 필요해보입니다.

2024-07-05 12:46 UTC, dc-choi commented on src/main/java/gift/controller/MemberController.java
> +    public ResponseEntity<?> login(@RequestBody MemberDto memberDto) {
email과 password가 null인 경우는 어떻게 처리되나요? 이 부분에 대한 예외처리가 필요해보입니다.

2024-07-05 12:46 UTC, dc-choi commented on src/main/java/gift/controller/MemberController.java
> +        return ResponseEntity.ok().body(new SecureRequestStateDTO(
`SecureRequestStateDTO`와 `RequestStateDTO`의 차이점이 무엇인가요?

2024-07-05 12:46 UTC, dc-choi commented on src/main/java/gift/repositories/MemberRepository.java
> +        List<Member> queried = jdbcTemplate.query("SELECT * FROM members where email=" + email + " limit 1", (resultSet, rowNum) ->
password에 대한 부분은 따로 검증하지 않나요? password가 일치하는지에 대한 부분도 필요해보입니다.

2024-07-05 12:46 UTC, dc-choi commented on src/main/java/gift/repositories/MemberRepository.java
> +                resultSet.getString("password")
password를 로직에서 따로 사용하지 않는데 가져오는 이유가 있으신가요?

2024-07-05 23:29 UTC, ariimo commented on src/main/java/gift/GlobalExceptionHandler.java
> +    @ExceptionHandler(Exception.class)
감사합니다!!

2024-07-06 06:42 UTC, ariimo commented on src/main/java/gift/controller/MemberController.java
> +        catch(RegisteringEmailIsAlreadyExists e) {
안녕하세요 멘토님. 제가 아직 예외처리 관련 지식과 경험이 부족하여 문제 해결이 안되는 것 같습니다. 

해당 오류를 GlobalExceptionHandler에서 전역으로 예외처리 하도록 코드 추가해도, controller의 memberService.register(memberDto); 부분에서 '처리되지 않은 예외: gift.classes.Exceptions.EmailAlreadyExistsException'라는 오류가 발생하여 try catch 를 작성해야만 합니다..ㅠㅠ 
이 경우 어떻게 해결해야 하나요..?

2024-07-06 06:55 UTC, ariimo commented on src/main/java/gift/controller/MemberController.java
> +        catch(RegisteringEmailIsAlreadyExists e) {
멘토님 해당 오류를 
`package gift.classes.Exceptions;

public class EmailAlreadyExistsException extends RuntimeException {
    public EmailAlreadyExistsException() {
        super("Email is already exist.");
    }
}
`
와 같이 수정하여 해결했습니다!!!!

2024-07-06 07:00 UTC, ariimo commented on src/main/java/gift/controller/MemberController.java
> +    public ResponseEntity<?> login(@RequestBody MemberDto memberDto) {
email과 password가 null인 경우, DB검사 결과가 null로 반환될 것이고 service 에서 
`if (existingMember == null) {
            throw new NoSuchElementException("Email is not exist. ");
        }`코드를 작성하여 예외처리를 하도록 하였습니다!! 이걸로는 불충분할까요..??

2024-07-06 07:02 UTC, ariimo commented on src/main/java/gift/repositories/MemberRepository.java
> +        List<Member> queried = jdbcTemplate.query("SELECT * FROM members where email=" + email + " limit 1", (resultSet, rowNum) ->
email과 password를 모두 가지고 검증하도록 수정하였습니다 :)

2024-07-06 07:59 UTC, ariimo commented on src/main/java/gift/classes/Exceptions/RegisteringEmailIsAlreadyExists.java
> +public class RegisteringEmailIsAlreadyExists extends Exception {
멘토님이 말씀하신 '하나의 객체 안에서 메시지를 통해서 어떤 오류가 발생하였는지 확인할 수 있는 객체로 이름을 변경하였으면 좋겠습니다.'부분이 어떤 의미인지 이해가 잘 안됩니다ㅠㅠ

해당 객체 이름을 EmailAlreadyExistsException로 변경하였는데, 멘토님께서 요구하신 사항을 충족했다고 봐도 되는 걸까요??

2024-07-06 08:07 UTC, ariimo commented on src/main/java/gift/controller/MemberController.java
> +        return ResponseEntity.ok().body(new SecureRequestStateDTO(
웹서버에서 다시 응답을 줄 때 사용하기 위해서 RequestStateDTO를 만들었습니다. 
SecureRequestStateDTO의 경우 RequestStateDTO 상속한 클래스로 로그인이 성공했을 경우에 토큰을 넘기도록 합니다!!

2024-07-06 16:24 UTC, ariimo commented on src/main/java/gift/Application.java
> +        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS members(email VARCHAR(255), password VARCHAR(255))");
member의 멤버변수로 memberId와 role을 추가하였습니다:)

2024-07-06 16:42 UTC, ariimo commented
멘토님, 제가 merge가 안 된 상태에서 step3를 진행중입니다. 혹시 이 브랜치에서 step3까지 완료해도 될까요??

2024-07-07 03:51 UTC, dc-choi commented
> 멘토님, 제가 merge가 안 된 상태에서 step3를 진행중입니다. 혹시 이 브랜치에서 step3까지 완료해도 될까요??

네 그렇게 해주셔도 될 거 같습니다~! 다음부터는 따로따로 해주세요~!

2024-07-07 05:02 UTC, ariimo commented
안녕하세요 멘토님! 
제가 개발 경험이 많지 않아, 구축까지 꽤 오랜 시간이 걸렸습니다..ㅠㅠ 다음주 과제부터는 조금 더 빨리 각 step을 완료하도록 노력하겠습니다..! 

마지막으로 step3를 진행하며 들었던 의문 몇 가지를 여쭤보고 싶습니다. 

1. Controller 나 Service에서 받는 매개변수는 어떻게 결정하시나요?? 
'password를 로직에서 따로 사용하지 않는데 가져오는 이유가 있으신가요?'라는 리뷰를 보고 각 파라미터로 전달되는 값은 꼭 해당 함수에서 쓰여야 하나?? 라는 의문이 들게 되었습니다. 이렇게 되면 상당히 많은 DTO가 만들어져야 할 것 같다는 생각이 듭니다.

2. 지금까지 만든 많은 class들을 어떤 방식으로 나누시나요?? 
각각의 class들을 각 주제 (Member, Wish, Product) 에 맞춰 나누는 것과 기능 (Controller, Service, Repository 등)에 맞춰 나누는 것 (혹은 이 외의 방법) 중 어떤 방법을 선호하시는지 여쭤보고 싶습니다. 

개발을 이제 막 하나하나 배워가고 있어 멘토님의 많은 지적과 가르침이 필요합니다. 항상 감사드립니다!!

2024-07-07 05:04 UTC, ariimo commented
> > 멘토님, 제가 merge가 안 된 상태에서 step3를 진행중입니다. 혹시 이 브랜치에서 step3까지 완료해도 될까요??
> 
> 네 그렇게 해주셔도 될 거 같습니다~! 다음부터는 따로따로 해주세요~!
넵 감사합니다..!!

2024-07-07 13:42 UTC, dc-choi commented on src/main/java/gift/controller/MemberController.java
> +    public ResponseEntity<?> login(@RequestBody MemberDto memberDto) {
예외처리는 이정도면 충분해보입니다!

2024-07-07 13:43 UTC, dc-choi commented on src/main/java/gift/classes/Exceptions/RegisteringEmailIsAlreadyExists.java
> +public class RegisteringEmailIsAlreadyExists extends Exception {
음... `CustomException` 이런식으로 네이밍을 변경하고 그 안에 메시지로 예외를 구분하는 방식을 말씀드렸었던거였습니다!

2024-07-07 14:05 UTC, dc-choi requested changes
안녕하세요 아림님~ step2와 step3에 대한 내용에 대해 전반적으로 리뷰를 남겨드렸습니다~!

자세한 내용은 하단 세부 코멘트를 확인해주세요~!

그리고 아림님이 코멘트를 남겨주신 부분에 대한 답을 해드리겠습니다!!

> Controller 나 Service에서 받는 매개변수는 어떻게 결정하시나요?? 'password를 로직에서 따로 사용하지 않는데 가져오는 이유가 있으신가요?'라는 리뷰를 보고 각 파라미터로 전달되는 값은 꼭 해당 함수에서 쓰여야 하나?? 라는 의문이 들게 되었습니다. 이렇게 되면 상당히 많은 DTO가 만들어져야 할 것 같다는 생각이 듭니다.

이 부분은 로직에서 불 필요한 부분은 굳이 가져올 필요가 없음을 말씀드리려고 그렇게 말씀을 드렸었어요. DTO를 어떻게 설정하는지에 대한 고민이 조금 더 필요해보입니다!

저는 개인적으로 각 EndPoint 마다 DTO를 따로 두는게 맞다고 생각하는 타입입니다~!

> 지금까지 만든 많은 class들을 어떤 방식으로 나누시나요?? 각각의 class들을 각 주제 (Member, Wish, Product) 에 맞춰 나누는 것과 기능 (Controller, Service, Repository 등)에 맞춰 나누는 것 (혹은 이 외의 방법) 중 어떤 방법을 선호하시는지 여쭤보고 싶습니다.

이 부분은 도메인(Member, Wish, Product) 별로 나누는게 추후 유지보수에 더 편하다는 느낌을 받았어요.

위 두 코멘트에 대한 어느정도 참고 자료를 드리려고 합니다... 그냥 참고용으로만 사용해주세요.
https://github.com/dc-choi/http-chunked

> 제가 개발 경험이 많지 않아, 구축까지 꽤 오랜 시간이 걸렸습니다..ㅠㅠ 다음주 과제부터는 조금 더 빨리 각 step을 완료하도록 노력하겠습니다..!

마지막으로 드리는 말씀으로는... 과제 구현하시느라 고생하셨고! 다음주도 파이팅입니다~!

2024-07-07 14:05 UTC, dc-choi commented on src/main/java/gift/controller/WishController.java
> +    @PostMapping("/add")
RESTful API가 아닌거 같습니다. 행위는 이미 POST라는 HTTP Method로 구분이 되는데 /add로 추가적으로 구분하면 원칙에 어긋납니다.

RESTful API에 대해서 다시 고민해주세요.

2024-07-07 14:05 UTC, dc-choi commented on src/main/java/gift/controller/WishController.java
> +    @GetMapping("/delete")
RESTful API가 아닌거 같습니다. 이 경우는 DELETE라는 HTTP Method로 구분을 해줘야 합니다.

RESTful API에 대해서 다시 고민해주세요.

2024-07-07 14:05 UTC, dc-choi commented on src/main/java/gift/services/WishService.java
> +        Wish wish = new Wish(wishDto.getMemberId(), wishDto.getProductId(), null);
`productName`에 해당하는 부분은 null로 처리하는 이유가 무엇인가요?

사용하지 않는 값이라면 필요가 없어보입니다.

2024-07-07 14:05 UTC, dc-choi commented on src/main/java/gift/MemberDto.java
> +@JsonInclude(JsonInclude.Include.NON_NULL)
`@JsonInclude`은 무슨 의미를 가지고 있나요?

2024-07-07 14:05 UTC, dc-choi commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +        String token = request.getHeader("Authorization");
WishList의 경우 `Bearer` 방식으로 토큰 인증을 진행하는데 `Bearer` 방식으로 인증을 처리하는 부분이 누락된거 같습니다.

확인 부탁드려요~

2024-07-07 14:05 UTC, dc-choi commented on src/main/java/gift/WebConfig.java
> +    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> resolvers) {
`@LoginMember`가 적용되지 않은 다른 API에서는 어떻게 동작하는지 궁금합니다~!

설명해주실 수 있으신가요?

2024-07-08 09:50 UTC, ariimo commented on src/main/java/gift/controller/WishController.java
> +    @PostMapping("/add")
RESTful API에 대해 학습하였고 URI에는 자원이 표현되어야 한다는 것을 알게되었습니다.  @PostMapping으로 수정하였습니다!

2024-07-08 09:51 UTC, ariimo commented on src/main/java/gift/controller/WishController.java
> +    @GetMapping("/delete")
@DeleteMapping 으로 수정하였습니다!

2024-07-08 09:51 UTC, ariimo commented on src/main/java/gift/services/WishService.java
> +        Wish wish = new Wish(wishDto.getMemberId(), wishDto.getProductId(), null);
RequestWishDto를 생성하여 null처리를 하지 않아도 되도록 만들었습니다.

2024-07-08 12:46 UTC, ariimo commented on src/main/java/gift/MemberDto.java
> +@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonInclude은 객체를 JSON으로 직렬화할 때 사용하는 어노테이션입니다. 다양한 옵션을 통해 포함 여부를 결정할 수 있습니다. 

자료를 찾던 중 발견한 어노테이션입니다. '한번 넣어볼까'하는 마음에 추가했었습니다...ㅎㅎ

2024-07-08 12:49 UTC, ariimo commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +        String token = request.getHeader("Authorization");
해당 코드를 다시 점검하여 토큰 인증관련 오류를 수정했습니다. 혹시 멘토님께서 의도하신 바가 수정된 코드에 반영되었을까요..? 아니라면, Bearer 방식으로 인증을 처리한다는 게 어떤 의미인지 조금 더 상세히 알려주시면 큰 도움이 될 것 같습니다.

2024-07-08 12:56 UTC, ariimo commented on src/main/java/gift/WebConfig.java
> +    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> resolvers) {
음 @LoginMember 어노테이션이 없는 경우는 (현재 저의 코드 상에서) 인증 과정이 필요하지 않는 API입니다. 따라서, 토큰 없이 값을 요청하고 받을 수 있습니다. (LoginMemberArgumentResolver 또한 사용하지 않게 됩니다)

2024-07-08 13:14 UTC, ariimo commented
> 음... `CustomException` 이런식으로 네이밍을 변경하고 그 안에 메시지로 예외를 구분하는 방식을 말씀드렸었던거였습니다!

이때 주신 리뷰를 참고하여 AuthException을 만들어보았습니다! 확실히 같은 주제의 예외를 더 간단하게(clean하게) 처리할 수 있었습니다. (몸소 배워야 깨닫는...)

제가 Spring을 처음 다루다보니 코드 작성과 오류 파악에 시간이 오래걸리는 것 같습니다. 더욱 노력하겠습니다..! 
또한, 멘토님의 코드리뷰 덕분에 '왜?'라는 질문과 '이래서 쓰는구나!'라는 저만의 경험이 하나하나 쌓여갑니다. 더 많은 지적 부탁드리겠습니다. 오늘도 감사합니다!!

2024-07-08 14:42 UTC, dc-choi commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +        String token = request.getHeader("Authorization");
맨 처음부분에서 `Bearer`로 시작하는데 그 부분에 대한 검증 로직이 없는거 같습니다.

2024-07-08 14:54 UTC, ariimo commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +        String token = request.getHeader("Authorization");
`@Override
    public MemberDto resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) throws Exception {

        HttpServletRequest request = (HttpServletRequest) webRequest.getNativeRequest();
        String auth = request.getHeader("authorization");
        if (auth == null)
            throw new AuthException("Authorization header is missing");

        String[] splitted = auth.split(" ");
        if (splitted.length < 2)
            throw new AuthException("Invalid token format");

        if (!splitted[0].equals("bearer"))
            throw new AuthException("Invalid token type");
        String token = splitted[1];

        return memberService.getLoginUser(token);


    }`
    //혹시 여기서 오타났던 부분 말씀하셨던 거라면 수정했습니다..!

2024-07-08 15:31 UTC, dc-choi commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +        String token = request.getHeader("Authorization");
`bearer` 부분에서 앞 부분이 대문자일 경우에만 로직이 통과될 것으로 보입니다~!

이거만 수정되면 승인하도록 할게요!

2024-07-09 00:49 UTC, ariimo commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +        String token = request.getHeader("Authorization");
앋....ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ PostMan으로 직접 테스트하다보니 발견을 못했었네요...
수정 완료했습니다!

2024-07-09 01:45 UTC, dc-choi approved these changes
아림님~ step3까지 진행하시느라 고생하셨습니다~!

오늘도 파이팅! 수고하셨습니다!

2024-07-09 01:45 UTC, merged