강원대 BE_이세진 2주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #289
Opened 2024-07-05 05:14 UTC by ez23re

멘토님 매번 피드백 상세히 달아주셔서 감사합니다. 1단계에서 리뷰 받은 부분 같이 고쳐나가고 있습니다.
다만, 2단계 로그인 기능 구현이 어려워서 view(html) api 연결까지는 못했습니다.
또 다시 pr 충돌이 생겨 수정드리고 리뷰 요청드리겠습니다. 자꾸 충돌이 생기는데 하지 말아야 할 행동이 있을까요?
그 외 전반적인 리뷰 부탁드립니다.

2024-07-05 15:18 UTC, pci2676 commented
> ** 새 브랜치로 넘겨올때 또 pr 충돌이 생겨 해결했습니다. 자꾸 충돌이 생기는데 하지 말아야 할 행동이 있을까요?

음~ 새로운 브랜치를 만들 때 origin에 있는 branch를 한번 pull해와서 병합시켜야 할것 같은 느낌이네요~!

2024-07-05 15:19 UTC, pci2676 commented
> 2단계를 늦게 제출해서 3단계는 구현한 부분까지만 일단 같이 커밋합니다.
> 다 작성하지 못해서 제대로 작성한 뒤 최종 다시 PR 드리곘습니다.

일요일까지 해도 된다고 하는것 같아요~ 너무 촉박하게 생각하지 않으셔도 될 것 같습니다 😄

2024-07-05 15:28 UTC, pci2676 requested changes
리뷰를 남겨두었으니 확인해주세요.

리뷰가 이해되지 않으면 멘토링 신청부탁드려요~

2024-07-05 15:28 UTC, pci2676 commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
혹시 implementation와 compile only, runtime only등이 어떠한 기능을 하는지 아실까요?

알아 두시면 나중에 도움이 되니 시간 괜찮으실때 공부해보시면 좋을것 같습니다 😄

2024-07-05 15:28 UTC, pci2676 commented on src/main/java/gift/controller/MemberController.java
> +        }
로그인 처리시 nullable한 Member 객체를 반환하지 말고 특정 exception을 발생시켜 보면 좋을것 같습니다.

그리고 특정 exception을 error handler에서 처리하고 401로 응답을 한다면 controller가 이러한 행위를 하지 않아도 될 것 같아요~

2024-07-05 15:28 UTC, pci2676 commented on src/main/java/gift/controller/MemberController.java
> +    }
MemberService에서 로그인 응답 값으로 위 토큰을 반환하는건 어떨까요?

2024-07-05 15:28 UTC, pci2676 commented on src/main/java/gift/controller/WishListController.java
> +}
컨트롤러가 비어있군요 🤔

2024-07-05 15:28 UTC, pci2676 commented on src/main/java/gift/entity/Member.java
> +    }
setter는 제거해주세요~! 생성자를 통해 한번만 주입해주시고

특정 값을 변경해야 한다면 별도의 도메인 로직을 추가해주시는게 좋을것 같습니다.

ex. `member.update(xxx);`

2024-07-05 15:28 UTC, pci2676 commented on src/main/java/gift/entity/WishList.java
> +}
비어있군요..!

2024-07-05 15:28 UTC, pci2676 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +
static 클래스로 정의해두지말고 별도의 클래스 파일에 단독으로 관리하는게 좋을것 같습니다.

2024-07-05 15:28 UTC, pci2676 commented on src/main/java/gift/repository/MemberRepository.java
> +             PreparedStatement stmt = conn.prepareStatement(SQL_INSERT_MEMBER)) {
직접 커넥션을 활용하지 말고 spring에서 제공하는 DB를 작업을 편하게 할 수 있는 클래스를 활용해볼까요?

아래 키워드로 검색해보세요~

`spring data jdbc`

2024-07-05 15:28 UTC, pci2676 commented on src/main/java/gift/repository/MemberRepository.java
> +                member.setPassword(rs.getString("password"));
setter를 사용하지 말아주세요~

2024-07-05 15:28 UTC, pci2676 commented on src/main/java/gift/service/MemberService.java
> +        if (member != null && passwordEncoder.matches(password, member.getPassword())) {
Member가 password를 알고 있다면 Member에게 메세지를 던져서 이 행위를 확인해달라고 물어보는것이 도메인 로직입니다.

변경해보세요~

2024-07-05 15:28 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +    }
`@Autowired`가 필수인가요?

2024-07-05 15:28 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +    }
이 기능은 값 객체의 개념을 이제는 적용해주세요!!!!!

2024-07-05 16:50 UTC, ez23re commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
네 학습일지에 작성하여 학습하겠습니다.

2024-07-05 16:52 UTC, ez23re commented on src/main/java/gift/controller/MemberController.java
> +        }
넵 서비스에서 로그인 실패 시 null 반환말고 특정 예외를 반환하도록 수정해보겠습니다.

2024-07-05 16:55 UTC, ez23re commented on src/main/java/gift/controller/MemberController.java
> +    }
서비스 계층에서 로그인 로직을 모두 처리하고 컨트롤러에는 응답을 주고 받는 것으로만 구현하라고 하신 거죠? 그렇게 수정해보겠습니다.

2024-07-05 17:02 UTC, ez23re commented on src/main/java/gift/controller/WishListController.java
> +}
죄송합니다. 우선 제출이라도 해야 하는 줄 알고 구현해야 할 것 같은 위시리스트 관련 mvc 클래스들만 일단 커밋했습니다. 3단계 진행 후 다시 pr 드리겠습니다.

2024-07-05 17:06 UTC, ez23re commented on src/main/java/gift/entity/Member.java
> +    }
넵 수정하겠습니다. setter 가 객체 상태 변경할 때 편해서 자꾸 쓰게 되는데 정보 은닉 문제 때문에 지양하는 것이 좋은가요?

2024-07-05 17:06 UTC, ez23re commented on src/main/java/gift/entity/WishList.java
> +}
죄송합니다. 우선 제출이라도 해야 하는 줄 알고 구현해야 할 것 같은 위시리스트 관련 mvc 클래스들만 일단 커밋했습니다. 3단계 진행 후 다시 pr 드리겠습니다.

2024-07-05 17:07 UTC, ez23re commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +
넵 KakaoProductException 클래스를 따로 만들겠습니다.

2024-07-05 17:25 UTC, ez23re commented on src/main/java/gift/repository/MemberRepository.java
> +             PreparedStatement stmt = conn.prepareStatement(SQL_INSERT_MEMBER)) {
넵 JDBC, JPA 등을 이용하여 DB 연결 수정하겠습니다.

2024-07-05 17:25 UTC, ez23re commented on src/main/java/gift/repository/MemberRepository.java
> +                member.setPassword(rs.getString("password"));
네 생성자를 따로 만들겠습니다.

2024-07-05 17:27 UTC, ez23re commented on src/main/java/gift/service/MemberService.java
> +        if (member != null && passwordEncoder.matches(password, member.getPassword())) {
그러면 멤버로 로그인 로직을 옮겨야 하나요?

2024-07-05 17:29 UTC, ez23re commented on src/main/java/gift/service/ProductService.java
> +    }
고민해보고 학습일지에 공부한 내용 작성하겠습니다.

2024-07-05 17:32 UTC, ez23re commented on src/main/java/gift/service/ProductService.java
> +    }
앗 넵 따로 객체 클래스 만들겠습니다.

2024-07-06 00:24 UTC, pci2676 commented on src/main/java/gift/entity/Member.java
> +    }
데이터의 추상화를 깬다는 문제점이 있고

일관적이지 않은 데이터 변화가 가능하다는 단점이 있습니다.

사용하지 말아주세요!

2024-07-06 00:25 UTC, pci2676 commented on src/main/java/gift/repository/MemberRepository.java
> +             PreparedStatement stmt = conn.prepareStatement(SQL_INSERT_MEMBER)) {
Jpa는 사용하지 않으셔도 됩니다~

2024-07-06 00:25 UTC, pci2676 commented on src/main/java/gift/service/MemberService.java
> +        if (member != null && passwordEncoder.matches(password, member.getPassword())) {
로그인 로직이라기 보다 패스워드를 비교하는 행위정도일것 같네요~ 로그인 로직이라고 표현하는 기능은 그 범위가 너무 커서요~

2024-07-06 00:26 UTC, pci2676 commented on src/main/java/gift/service/MemberService.java
> +        if (member != null && passwordEncoder.matches(password, member.getPassword())) {
로그인에 필요한 행위라고 할 수 있겠네요

2024-07-06 00:26 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +    }
고민해보시고 답변 주세요~

2024-07-07 09:07 UTC, pci2676 commented
> 여기에 적어도 될까요? 아니면 리뷰 답글에 다시 달겠습니다.

지금처럼 적어주시면 좋을것 같습니다. 😄

2024-07-07 09:08 UTC, pci2676 commented
> Q. `@Autowired`가 필수인가요? A. 우선, 제가 찾아보고 정리한 `@Autowired`는 그 이름에서 알 수 있듯이 자동으로 의존성을 주입 해주는 어노테이션 입니다. `@Autowired` 을 이용하면 설정자 메서드를 이용하지 않고도 스프링 프레임워크가 설정 파일을 통해 설정자 메서드 대신 속성을 주입 해줍니다. 결국 개발자가 수동으로 의존성 주입을 해주지 않아도 스프링이 필요한 객체를 자동으로 필요한 객체를 자동으로 주입해주어 편리하게 사용할 수 있게 해줍니다. 그래서 생성자 주입, 설정자 주입 등에 다른 방법으로 객체 속성을 사용할 수 있게 했다면 굳이 사용하지 않아도 될 것 같습니다.
> 
> 이렇게 이해한게 맞나요?

다른 방식에대해서도 잘 알아봐 주신것 같습니다~

조금 더 첨언을 드리자면 장단점에 대해 잘 알고 계시면 좋을것 같습니다!

2024-07-07 09:11 UTC, pci2676 commented
> 1. 새로운 단계 기능을 만들고 그러는 과정에서 오류 및 수정사항이 많아져 클래스가 무한증식 하는 느낌이 있습니다. 이렇게 무지성으로 클래스를 늘려도 괜찮나요? 그렇다고 하나의 클래스에 너무 많은 로직을 집어넣는 것도 옳지 않은 거죠?

클래스가 많아지는 것은 당연한 수순으로 볼 수 있을것 같습니다~ 말씀하신 것 처럼 하나의 클래스에 너무 많은 로직(책임)이 위치한다면 이는 곳 SRP(단일 책임 원칙)을 위배할 수 있다라는 신호로 볼 수 도 있습니다.

다만 불필요하게 클래스가 나누어지지 않았는가에 대해서도 함께 주의를 기울여주시면 좋을것 같습니다.

지금의 경우 PR을 올리시면 제가 코드를 확인하면서 클래스가 불필요하게 나누어져 있거나, 반대로 클래스가 나누어져야 할 필요성이 있다고 보이면 말씀을 드리니 이를 확인해주시고 경험을 쌓아보시면 좋을것 같습니다!

2024-07-07 09:12 UTC, pci2676 commented
> 2\. 커밋 메시지 작성할 때 refactor 랑 fix 가 헷갈리는데 메시지를 명확히 한다면 둘을 구분하지 않아도 될까요?

저는 그래도 괜찮다고 생각합니다~ 사실 저는 그렇게 header가 중요한가 싶어요~

2024-07-07 09:13 UTC, pci2676 commented
> 3\. 금일 제이슨님께서 보내주신 영상처럼 미숙한 상태에서 클린코드를 지향하고 기능을 쉽게 쓸 수 있는 어노테이션 등을 모두 사용하려다보니 과제 수행 일정이 더욱 느려지는 것 같습니다. 남들처럼 그런 유용한 기능을 다 사용 못해도 일단 리뷰 요청 드리고 피드백을 통해 수정해나가야 하는지, 아니면 그래도 일단 혼자 찾아보고 최대한 사용해보는게 좋을지 혼란스럽습니다. 조언부탁드립니다.

가능하면 찾아보시되 끝내 적용하지 못하셨다면 어디까지 알아보았는지 어떠한 부분에서 막혔는지를 함께 알려주시면 제가 도움을 드릴 수 있을것 같습니다~!

추가로 "이렇게 쓰는게 맞나?" 라는 생각이 든다면 일단 적용해보신 다음 PR을 생성하고 comment로 코드에 별도로 남겨주시면 제가 함께 보기 더 좋을것 같습니다. 지금은 학습하는 과정이니 이것저것 해보고싶은대로 마음껏 해보시는것이 더 중요할것 같습니다~!

2024-07-07 09:14 UTC, pci2676 commented on src/main/java/gift/controller/MemberController.java
> +    }
맞습니다~

2024-07-07 09:30 UTC, pci2676 approved these changes
답변과 리뷰를 남겨두었으니 확인해주시고 다음 주차부터 함께 고려하여 작성해주세요.

merge 하겠습니다.

2024-07-07 09:30 UTC, pci2676 commented on src/main/java/gift/controller/MemberController.java
> +        }
service에서 login 처리를 시도하고 실패시 exception을 발생시키는 것이 더 자연스러울 것 같아보입니다~

controller에서는 응답받은 객체를 이용한 별도의 작업이 없는것이 가장 좋습니다~

2024-07-07 09:30 UTC, pci2676 commented on src/main/java/gift/controller/MemberController.java
> +    }
지금 이렇게 사용하시면 사실 생성자 주입이 되기 때문에 `@Autowired`가 불필요합니다~!

2024-07-07 09:30 UTC, pci2676 commented on src/main/java/gift/service/MemberService.java
> +    }
제거해도 될 것 같네요!

2024-07-07 09:30 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +    }
1. 반환해야할 값이 생성된 이후 아무런 부가적인 행동이 필요하지 않다면 아래와 같이 바로 반환하는 것이 좋습니다.
```java
    return Jwts.builder()
                .setSubject(member.email()) // 이메일을 토큰 주제로 설정
                .signWith(SignatureAlgorithm.HS256, "myToken-key") // 알고리즘과 키 설정
                .compact();
```

2. ProductService는 상품에 대한 서비스로 보이는데 여기서 token을 다루는것은 어색해보입니다. token만을 다루는 별도의 서비스가 도출되는게 더 자연스러울 것 같습니다. :)

2024-07-07 09:30 UTC, pci2676 commented on src/main/java/gift/entity/Member.java
> +    }
이와 같은 사용하지 않는 setter성 메서드는 제거해주세요~

2024-07-07 09:30 UTC, pci2676 commented on src/main/java/gift/entity/WishList.java
> +    private List<Product> products = new ArrayList<>();
final을 붙이는게 좋을것 같습니다!

2024-07-07 09:30 UTC, pci2676 commented on src/main/java/gift/entity/Product.java
> +    // 생성자 - id를 포함하여 초기화
생성자를 두개 생성할때 생성자가 다른 생성자를 참조하는 방법을 시도해보시면 좋을것 같습니다~!

2024-07-07 09:30 UTC, pci2676 commented on src/main/java/gift/controller/MemberController.java
> +        return ResponseEntity.ok(response);
로그인 뒤 생성된 토큰을 이용한 검증은 구현되지 않은것 같네요. 😢

2024-07-07 09:30 UTC, pci2676 commented on src/main/java/gift/controller/MemberController.java
> +        return ResponseEntity.ok(response);
아마 강의시간에 들으셨을것도 같은데 이번에는 HandlerMethodArgumentResolver 에 대해 알아보시면 좋을것 같습니다~

2024-07-07 09:32 UTC, merged