경북대 BE_김은선 2주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #296
Opened 2024-07-05 05:48 UTC by eunsoni

유효성 검증 및 예외처리 기능 구현입니다

2024-07-06 10:45 UTC, gongdongho12 requested changes
> 빌드 오류가 생겼다가 괜찮아졌다 하는 것은 어떤 이유인지 알 수 있을까요?

에러코드도 없고 아무 정보 없이는 저도 알기 어렵습니다
본인 환경에서만 문제인지 타 PC에서도 동일한지 그리고 에러메시지 포함해서 주시면 좋을 것 같습니다

전체적으로 Validation이 없는데 gradle implements에 등록이 되어있는 상태라 코드가 요구사항을 만족하지 않는 것 같습니다
README 적어주신 것처럼 요구사항인데 완성되지 않은 상태로 올려주신 것 같습니다

프로젝트에서 중요한 요소든 관점마다 다르지만, 요구사항은 이 프로젝트에서 달성해야 하는 미션 같은 부분이다 보니 관련해서 테스트도 작성주시면 좋을 것 같습니다

그리고 맨 윗 부분처럼 `빌드 오류가 생겼다가 괜찮아졌다 하는 것` 등으로 시간 소요가 많이 되었을 것 같아요 <- 이런 부분 생기면 멘토링 요청주시거나 BE 질문방에 올려주시는 것도 방법일 것 같습니다

많이 막히셨을건데도 이렇게 PR 올려주시구 고생하셨습니다 😄

2024-07-06 10:45 UTC, gongdongho12 commented on build.gradle
> +    implementation 'org.springframework.security:spring-security-crypto'
다른분들과 다르게 spring-security-crypto 사용해주셨네요

2024-07-06 10:45 UTC, gongdongho12 commented on src/main/java/gift/GlobalExceptionHandler.java
> +        System.out.println("테스트 카카오");
이 로깅은 무슨 용도일까요?

2024-07-06 10:45 UTC, gongdongho12 commented on src/main/java/gift/KakaoNameException.java
> +public class KakaoNameException extends RuntimeException {
모든 코드가 패키지 정리 없이 상단에 노출되어있는데
exception이라는 패키지 하위에 정리하면 어떨까요? 다른 서비스들도 서비스 따로 컨트롤러 따로 등으로 정리하던가 도메인인 (멤버, 프러덕트, 위시 등으로) 정리해보면 좋을 것 같습니다
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/1717874/21f09afd-e92d-4540-b4de-db9a7139a32a)

2024-07-06 10:45 UTC, gongdongho12 commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +            String token = authorizationHeader.substring(7);
여기서 7이라는 숫자는 `Bearer `인데 상수로 등록해서 이 문자열의 length로 7을 대체하는게 이해하는데 용이하지 않을까요?

2024-07-06 10:45 UTC, gongdongho12 commented on src/main/java/gift/MemberController.java
> +            model.addAttribute("message", "잘못된 이메일 또는 비밀번호입니다.");
이런 부분은 validation인데 컨트롤러에서 validation 하는 상황이에요
Validation 을 상속하던가 @Valid 어노테이션을 참조해서 적용하는 방향으로 코드를 깔끔하게 바꾸면 좋을 것 같아요

2024-07-06 10:45 UTC, gongdongho12 commented on src/main/java/gift/ProductController.java
> +        }
결과에 에러가 있으면 throw를 시켜서 자동으로 ControllerAdvice로 리다이렉트 되는 방식이 어떠신가요?

2024-07-06 10:45 UTC, gongdongho12 commented on src/main/java/gift/ProductService.java
> +        }
이 부분도 여기에 Validation을 처리해줄 필요가 없지않을까요?
Exception을 다시 Exception으로 바꾸고 계신데, 기존에 throw한 exception으로는 controllerAdvice로 처리할 수 없을까요?

2024-07-06 10:45 UTC, gongdongho12 commented on src/main/java/gift/WebConfig.java
> +    }
리졸버 사용 확인했습니다 👍🏼

2024-07-06 10:45 UTC, gongdongho12 commented on src/main/java/gift/WishService.java
> +        }
없을때에 대한 처리를 서비스인 `getProductById` 메서드에서 해서 throw하면 매번 체크를 따로 안해줘도 되지 않을까요?

2024-07-06 10:45 UTC, gongdongho12 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
각 데이터 클래스들에 validation이 없는데 이부분은 추가만 하고 사용 안하신거 아닐까요?

2024-07-06 10:45 UTC, gongdongho12 commented on README.md
> +* ( ), [ ], +, -, &, /, _ 외 특수 문자 사용 불가
상품 이름 글자수와 특수문자 제외처리 로직이 빠져있는 것 같습니다

2024-07-06 10:45 UTC, gongdongho12 commented on src/main/resources/templates/wish.html
> +            }
실패 조건이, 로그인이 풀렸다거나 삭제 아이템이 이미 지워졌다던가 할 수 있는데 에러메시지를 구체화 하면 좋을 것 같습니다

2024-08-04 15:33 UTC, eunsoni commented on build.gradle
> +    implementation 'org.springframework.security:spring-security-crypto'
이 부분 제이슨님과 질의응답 이후에 삭제했었습니다!

2024-08-04 15:35 UTC, eunsoni commented on src/main/java/gift/GlobalExceptionHandler.java
> +        System.out.println("테스트 카카오");
상품명에 카카오 문구가 들어가면 예외처리합니다

2024-08-04 15:35 UTC, eunsoni commented on src/main/java/gift/KakaoNameException.java
> +public class KakaoNameException extends RuntimeException {
현재 반영된 피드백인 것 같습니다!

2024-08-04 15:37 UTC, eunsoni commented on README.md
> +* ( ), [ ], +, -, &, /, _ 외 특수 문자 사용 불가
이 부분도 반영된 피드백인 것 같습니다!

2024-08-04 15:41 UTC, eunsoni commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
현재는 사용되고 있습니다!
productController, ProductDto 등

2024-08-04 15:48 UTC, eunsoni commented on src/main/java/gift/WishService.java
> +        }
반영된 피드백 입니다!

2024-08-04 15:57 UTC, eunsoni commented on src/main/java/gift/ProductService.java
> +        }
현재는 kakaoNameException이 사라지고 엔터티에서 validation합니다

2024-08-04 15:59 UTC, eunsoni commented on src/main/java/gift/ProductController.java
> +        }
현재는 사라진 부분이고 다른 에러발생 상황에서는 ControllerAdvice를 사용하고 있습니다

2024-08-04 16:13 UTC, eunsoni commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +            String token = authorizationHeader.substring(7);
넵 적용했습니다!

2024-08-04 16:16 UTC, eunsoni commented on src/main/java/gift/MemberController.java
> +            model.addAttribute("message", "잘못된 이메일 또는 비밀번호입니다.");
이 부분 서비스에서 처리하도록 업데이트되어 있습니다

2024-08-04 16:29 UTC, eunsoni commented on src/main/resources/templates/wish.html
> +            }
넵 반영하였습니다!

2024-08-04 16:33 UTC, eunsoni commented
안녕하세요 @gongdongho12 멘토님,

저번 강의 때 제이슨님께서 
next-step에서 과제현황에서 머지되지 않은 pr을 확인한 후 
멘토님과 소통해서 피드백 반영 후 머지해주실 수 있는지 문의드려보라는 공지를 들었습니다

많이 늦었지만 리뷰요청드려도 될까요?
리뷰는 모두 반영하고 코멘트 남겨두었습니다!!

2024-08-05 14:37 UTC, gongdongho12 approved these changes
반영된 내용 전부 확인했습니다!

고생하셨습니다

2024-08-05 14:37 UTC, merged