충남대 BE_정현서 2주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #300
Opened 2024-07-05 06:03 UTC by hynseoj

안녕하세요 멘토님!
2단계 과제 제출합니다.

말씀하셨던대로 ProductDto에서 price에 대한 `@NotNull` 검증은 유효하지 않아 제거했습니다!
int 타입이라 null이 들어올 수 없는데 놓쳤습니다. 실제로 가격을 입력하지 않았을 때 null이 아니라 "" empty string으로 타입 에러가 발생하는 것 확인했습니다.

그리고 이후 과제를 진행하면서 화면을 계속 구현하는데 시간적 한계가 있을 것 같아 ProductRestContoller를 만들어보았습니다.

시간 상 포스트맨으로 일부 시나리오만 테스트 해보았고 테스트 코드를 아직 작성하지 못한 내용이 있는데 나중에 보충해보겠습니다..

감사합니다!!

2024-07-05 08:36 UTC, ksy90101 requested changes
2단계 고생많으셨어요~
간단한 피드백을 남겼으니 확인해주세요!
언제든 질문이 있다면 DM주세요!

2024-07-05 08:36 UTC, ksy90101 commented on src/main/java/gift/auth/jwt/JwtProvider.java
> +    private String key = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
해당 부분은 보안적으로 숨겨야 하는 값이라고 생각해요.
https://rutgo-letsgo.tistory.com/entry/Value%EC%99%80-ConfigurationProperties%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%B4-yaml-%ED%8C%8C%EC%9D%BC-%EB%A7%A4%ED%95%91%ED%95%98%EA%B8%B0
해당 글을 참고해서 @value 어노테이션을 한번 써보며 어떨까요?

2024-07-05 08:36 UTC, ksy90101 commented on src/main/java/gift/domain/product/controller/ProductRestController.java
> +    }
이 메서드는 뭔가요...?

2024-07-05 08:36 UTC, ksy90101 commented on src/main/java/gift/domain/user/controller/UserRestController.java
> +        }
catch를 하지 말고. 1단계에서 배운 ExcpetionHandler를 쓰면 어떨까요?

2024-07-05 08:36 UTC, ksy90101 commented on src/main/java/gift/domain/user/service/UserService.java
> +        }
orElseThrow를 통해 메서드 체이닝을 하면 어떨까요?

2024-07-05 08:36 UTC, ksy90101 commented on src/main/java/gift/domain/user/service/UserService.java
> +        if (!user.get().getPassword().equals(userLoginDto.password())) {
디미터의 법칙을 위반한거 같아요.
이런 로직은 user 도메인 로직으로 두면 좋을거 같아요~
메시지를 던져서 처리하는거죠!

2024-07-05 08:36 UTC, ksy90101 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
이 에러가 과연 FORBIDDEN 에러가 맞을까요?

2024-07-05 08:36 UTC, ksy90101 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
해당 표준예외가 어디에 많이 쓰이는지 찾아보시면 어떨까요?

2024-07-05 08:36 UTC, ksy90101 commented on src/main/resources/messages.properties
> +error.invalid.token.Expired=\uB9CC\uB8CC\uB41C \uD1A0\uD070\uC785\uB2C8\uB2E4.
이 부분을 한글로 할 방법은 없을까요?

2024-07-05 08:43 UTC, hynseoj commented on src/main/java/gift/domain/product/controller/ProductRestController.java
> +    }
사용자의 role을 확인하지 않고 모두 상품 생성이 가능하게 하던 기존 코드입니다.

> 401 Unauthorized 클라이언트 오류 상태 응답 코드는 해당 리소스에 유효한 인증 자격 증명이 없기 때문에 요청이 적용되지 않았음을 나타냅니다.

role에 따라 Unauthorized 오류를 반환하는 것을 확인해보고 싶어서 새로 메서드를 구현하고 기존 메서드의 `@PostMapping` 부분만 주석처리해두었습니다..!

2024-07-05 08:44 UTC, hynseoj commented on src/main/java/gift/domain/user/controller/UserRestController.java
> +        }
이 부분은 글로벌 예외 처리에서 상속을 이용하도록 수정하고 catch에서 커스텀 예외를 던지도록 수정하였습니다! 나중에 step3에서 한 번 더 확인부탁드립니다~!

2024-07-05 08:44 UTC, hynseoj commented on src/main/java/gift/domain/user/service/UserService.java
> +        }
아하 좋습니다. 수정하겠습니다!

2024-07-05 08:53 UTC, hynseoj commented on src/main/java/gift/domain/user/service/UserService.java
> +        if (!user.get().getPassword().equals(userLoginDto.password())) {
코드를 구현하면서 서비스와 도메인 로직을 구분하려는 생각을 잘 안 하게 되는 것 같습니다.
인식시켜주셔서 감사합니다. 앞으로 신경써서 해보겠습니다!

2024-07-05 09:00 UTC, hynseoj commented on src/main/resources/messages.properties
> +error.invalid.token.Expired=\uB9CC\uB8CC\uB41C \uD1A0\uD070\uC785\uB2C8\uB2E4.
앗 .git 인코딩 설정도 변경해보았는데 해결이 안됐네요.. 다른 방법 찾아서 수정해보겠습니다!

2024-07-05 09:04 UTC, hynseoj commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
요구사항을 잘못 이해한 것 같습니다... Unauthorized 에러도 잘못 사용한 것 같아 함께 수정하겠습니다!!

2024-07-05 09:13 UTC, hynseoj commented
피드백 반영하여 step3에서 한 번에 리뷰요청드리겠습니다!

2024-07-06 03:40 UTC, ksy90101 commented on src/main/java/gift/domain/product/controller/ProductRestController.java
> +    }
그럼 해당 코드는 지워도 되는거ㅜ아닌가요?

2024-07-06 03:42 UTC, ksy90101 approved these changes
고생하셨어요!
3단계 홧팅입니다!

2024-07-06 03:42 UTC, ksy90101 commented on src/main/java/gift/domain/product/controller/ProductRestController.java
> +        if (product.isEmpty()) {
이건 예외를 던져서 예외처리로 하는게 좋을거 같아요.

2024-07-06 03:42 UTC, merged