충남대 BE_송민주 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #306
Opened 2024-07-05 06:24 UTC by mingjuu

step3 느낀점 :  UI를 통해 결과를 확인하고 싶어 html 파일을 만들었었는데, 괄호 하나를 누락하여 delete 기능이 작동하지 않았습니다. 그 과정에서 logging도 해보고 단계별 로그도 찍어보면서 문제 원인을 파악하려 노력했습니다. 그동안 기능을 구현하려고만 노력했지, 원인을 찾기위해 로그를 이렇게 많이 남겨본 적은 처음이었는데, 당시엔 속상했지만 얻는건 많았던 것 같습니다.!

2024-07-05 15:31 UTC, asebn1 requested changes
민주님 안녕하세요~ 
3단계까지 한번에 구현해주셨네요 👍 
다만 1주차에 리뷰드린 내용중에 반영이 안된부분이 꽤 있는 것 같아요 (개선할 부분이 많이 보여요ㅠ)
제가 남긴 코멘트에도 답변 부탁드릴게요!
마무리까지 달려보아요 화이팅!! 🔥🔥

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/config/DatabaseConfig.java
> +    }
해당 설정이 빈을 통한 `DataSource`도 있고, `application.properties`에도 있네요
두 곳 다 관리되고 있어서 하나의 방법으로 관리하도록 수정해주세요~
또 각각 어떤 장단점이 있을까요?

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/config/DatabaseInitializer.java
> +        System.out.println("Table kakaoProduct created successfully");
`System.out.println` 사용은 주의해주세요!
- https://systemdata.tistory.com/21

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/config/DatabaseInitializer.java
> +                "email VARCHAR(255) NOT NULL, " +
`email`에 `unique` 제약도 추가할 수 있을 것 같아요
추가하면 어떤 이점이 있을까요?

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/config/DatabaseInitializer.java
> +                "image_url VARCHAR(255))";
스키마를 관리해서 사용해볼까요?

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/domain/Member.java
> +    }
`setter`가 아직 domain 계층에 전체적으로 있네요~  수정해봅시다!
- https://limdingdong.tistory.com/15

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/repository/ProductRepository.java
> +    }
1. `save` 가 두 가지 동작을 수행하고 있어요. 기능을 분리해볼까요?
2. else 예약어를 사용하고 있어요! 제거해봅시다 (https://limdingdong.tistory.com/8)

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/repository/MemberRepository.java
> +
불필요한 빈 줄은 제거해주세요! 맨 마지막 개행은 한줄만 적용합니다~
- https://google.github.io/styleguide/javaguide.html

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/repository/MemberRepository.java
> +    }
Optional을 사용해주고 있네요. 
1. Optional의 어떤 장단점이 있을까요?
2. `ProductRepository`의 `findById`는 `Optional`을 사용하고 있지 않네요. 일관성을 유지해주세요!
3. 에러가 발생했을 때 `Optional.empty()`를 넘겨주고 있네요. 이유가 있을까요?

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/repository/WishRepository.java
> +    public List<Wish> findByMemberId(Long memberId) {
한 줄 줄바꿈만 적용해주세요. (전체 코드 다 확인해주세요)

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/service/MemberService.java
> +                .setExpiration(new Date(System.currentTimeMillis() + 3600000)) // 1 hour
1시간에 대한 값을 상수로 관리해봅시다!

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/controller/ProductController.java
> +    }
`ProductController`는 `Repository`를 의존하고 있네요 🤔

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/controller/ProductController.java
> +        }
전체적으로 Controller 계층에서 도메인을 request로 사용하고 있어요
DTO를 적용해볼까요?

참고
- https://umbum.dev/1206/
- https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/repository/WishRepository.java
> +    }
`Repository` 계층에서 비즈니스 로직을 수행하고 있어요. 😱
`Service` 계층과 `Repository` 계층의 역할은 무엇일까요? 
수정해봅시다!

2024-07-05 15:31 UTC, asebn1 commented on src/test/java/gift/controller/WishControllerTest.java
> +import static org.mockito.Mockito.*;
현재 [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)를 기반으로 하고 있습니다.
No wildcard imports 부분 참고해주세요~

아래 링크로 설정 적용해보아요!
- https://www.baeldung.com/intellij-disable-wildcard-import

2024-07-05 15:31 UTC, asebn1 commented on src/main/java/gift/service/MemberService.java
> +//    @Value("${jwt.secret}")
사용하지 않는 주석은 제거해주세요~

2024-07-06 05:29 UTC, mingjuu commented on src/main/java/gift/config/DatabaseConfig.java
> +    }
넵! 반영하여 수정하겠습니다!
주신 질문에 대해 찾아보니, 아래와 같이 정리할 수 있었습니다.

Java 코드로 DataSource 설정 :  컴파일 시점에 형식 검사를 받을 수 있어 잘못된 설정을 미리 방지할 수 있으나, 설정을 변경할 때마다 코드를 수정하고 재컴파일해야하는 단점이 존재.

application.properties 파일로 DataSource 설정 : 코드 수정 없이 설정 파일만 수정할 수 있으나 복잡한 로직이나 조건부 설정을 구현하기 어려움.

2024-07-06 05:30 UTC, mingjuu commented on src/main/java/gift/config/DatabaseInitializer.java
> +        System.out.println("Table kakaoProduct created successfully");
넵 감사합니다!

2024-07-06 05:33 UTC, mingjuu commented on src/main/java/gift/config/DatabaseInitializer.java
> +                "email VARCHAR(255) NOT NULL, " +
동일한 이메일 주소를 가진 중복 레코드가 생기는 것을 방지할 수 있을 것 같습니다!

2024-07-06 05:45 UTC, mingjuu commented on src/main/java/gift/config/DatabaseInitializer.java
> +                "image_url VARCHAR(255))";
넵 알겠습니다!

2024-07-06 05:51 UTC, mingjuu commented on src/main/java/gift/domain/Member.java
> +    }
그동안 setter를 사용하는 방식으로 데이터값을 정해줘왔습니다. 그래서 피드백 주신 것 처럼 setter를 사용하지 않고 프로젝트를 완성하려면, 어떻게 코드를 짜야하는지 공부를 해야할 것 같습니다
해당 피드백은 전반적인 피드백은 먼저 수행한 후, 리팩토링 할 때 반영해도 괜찮을까요? 시간이 조금 걸릴 것 같습니다!

2024-07-06 05:51 UTC, mingjuu commented on src/main/java/gift/service/MemberService.java
> +//    @Value("${jwt.secret}")
넵 알겠습니다!

2024-07-06 05:53 UTC, mingjuu commented on src/test/java/gift/controller/WishControllerTest.java
> +import static org.mockito.Mockito.*;
넵 알겠습니다! 감사합니다

2024-07-06 06:02 UTC, mingjuu commented on src/main/java/gift/repository/WishRepository.java
> +    }
넵 알겠습니다! 수정후 다시 커밋하도록 하겠습니다

2024-07-06 06:08 UTC, mingjuu commented on src/main/java/gift/controller/ProductController.java
> +    }
넵 알겠습니다!

2024-07-06 06:09 UTC, mingjuu commented on src/main/java/gift/repository/ProductRepository.java
> +    }
넵 알겠습니다!

2024-07-06 06:09 UTC, mingjuu commented on src/main/java/gift/repository/MemberRepository.java
> +
넵 알겠습니당

2024-07-06 06:10 UTC, mingjuu commented on src/main/java/gift/repository/WishRepository.java
> +    public List<Wish> findByMemberId(Long memberId) {
넵 알겠습니다!

2024-07-06 06:17 UTC, mingjuu commented on src/main/java/gift/repository/WishRepository.java
> +    }
비즈니스 로직을 분리해보겠습니다! 


Service 계층: 비즈니스 로직을 처리하고 관리하는 역할
Repository 계층: DB에 SQL을 날리는 역할, 저장 장치와의 접근 담당
인 것 같습니다

2024-07-06 06:18 UTC, mingjuu commented on src/main/java/gift/repository/MemberRepository.java
> +    }
1. Optional을 통해 null값을 그대로 보내지 않을 수 있다고 알고 있습니다 findByid 역시 옵셔널을 감싸 반환하도록 하겠습니다!
2. 옙 알겠습니다!
4. 만약 DB에서 예외가 발생할 경우를 다루기 위해 Optional.empty()를 사용했습니다

2024-07-06 06:24 UTC, mingjuu commented on src/main/java/gift/service/MemberService.java
> +                .setExpiration(new Date(System.currentTimeMillis() + 3600000)) // 1 hour
넵 수정하겠습니다

2024-07-06 06:33 UTC, mingjuu commented on src/main/java/gift/controller/ProductController.java
> +    }
1주차 과제 결과물 부분인 것 같습니다!
-> 단순한 데이터 CRUD 작업을 하고 있다는 점과, MVC 패턴을 고려하며 짜다 보니 Service 계층을 두지 않았습니다. 혹시 어떤 프로젝트를 구성할 때, 반드시 Service 계층을 도입하는 것이 조금더 바람직한 구조일까요?

2024-07-06 06:45 UTC, mingjuu commented on src/main/java/gift/controller/ProductController.java
> +        }
넵 적용하여 다시 커밋드리겠습니다!

2024-07-07 16:22 UTC, asebn1 commented on src/main/java/gift/domain/Member.java
> +    }
네 다음에 함께 개선해주세요 :)

2024-07-07 16:23 UTC, asebn1 commented on src/main/java/gift/repository/MemberRepository.java
> +    }
DB에서 예외가 발생할 경우에 `Optional.empty()`를 넘겨주는 방식이 괜찮을까요? 🤔

2024-07-07 16:28 UTC, asebn1 commented on src/main/java/gift/controller/ProductController.java
> +    }
`Service` 계층이 존재하는 구조이기 때문에 말씀드린 내용이었어요.
하나의 모듈에서 구현되는 프로젝트이기에 전체 코드 컨밴션을 맞춰주세요
(예시로, A Controller는 Service를 의존하고 B Controller는 Repository를 의존하는 것이 괜찮을까요?)

2024-07-07 16:31 UTC, asebn1 approved these changes
민주님 안녕하세요~
3단계 피드백 반영 확인했습니다. 이번 미션은 이만 머지할게요.
피드백 반영 후에 새로운 Comment로 피드백 반영 완료되었다고 작성해주세요~ (아직 개발을 진행중이신지 알 수가 없습니다 🥲)
추가로 말씀주신 코멘트에 답변 드렸습니다. 확인해주세요 👍 
다음미션도 화이팅!!

2024-07-07 16:31 UTC, merged

2024-07-08 01:05 UTC, mingjuu commented on src/main/java/gift/controller/ProductController.java
> +    }
아하 이해했습니다! 전체적인 구조를 동일하게 유지하는게 더 좋을 것 같습니다