부산대 BE_정진택 2주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #312
Opened 2024-07-05 06:47 UTC by jjt4515

1. 토큰 처리를 맞게 했는지 궁금합니다!
2. 401 Unauthorized와 403 Forbidden를 에러 상황에 맞게 잘 구분했는지 궁금합니다!

2024-07-05 15:54 UTC, hocaron requested changes
진택님, 안녕하세요!

예외처리가 적절하고, 가독성이 좋네요👍
같이 작업하는 입장에서 궁금한 부분이 생겨 코멘트를 드린 부분이 있는데 확인 부탁드릴게요!

2024-07-05 15:54 UTC, hocaron commented on src/main/java/gift/controller/MemberController.java
> +    }
응답값을 inner class 로 정의하신 이유가 궁금합니다💭

2024-07-05 15:54 UTC, hocaron commented on src/main/java/gift/service/MemberService.java
> +                .setSubject(member.getEmail())
subject 로 이메일을 사용하신 이유가 궁금해요💭

2024-07-05 15:54 UTC, hocaron commented on src/main/java/gift/domain/Member.java
> +    private String secretKey;
회원마다 secretKey 가 다른 이유가 있는지 궁금해요💭

2024-07-05 15:54 UTC, hocaron commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
해당 에러들은 내부 로직이 동일한 것 같아요! 메시지와 status 를 가지고 있는 클래스를 만들어서 공통화해볼 수도 있을 것 같은데, 진택님은 어떻게 생각하시나요?😀

2024-07-05 15:54 UTC, hocaron commented on src/main/java/gift/service/MemberService.java
> +        if (!memberRequest.getPassword().equals(member.getPassword())) {
비밀번호 검증 굿입니다👍

2024-07-05 15:54 UTC, hocaron commented on src/main/java/gift/service/ProductService.java
> +        }
save 를 통해서 DataIntegrityViolationException 가 발생했을 때, 이메일 데이터를 중복 검증 하는 로직도 좋지만, email 필드를 기준으로 동일한 이메일이 있는지 확인하는 작없이 먼저 수행 되어도 좋을 것 같아요!

데이터 중복 검증을 데이터베이스 레이어에서 수행하고 있는 것 같고, DataIntegrityViolationException 이 제약조건 위반으로 발생하는 에러로 이메일 중복 외에도 발생할 가능성이 있을 것 같은 생각이 드는 것 같아요. 진택님은 어떻게 생각하시나요?!

2024-07-05 15:54 UTC, hocaron commented on src/main/java/gift/service/MemberService.java
> +        }
이미 등록된 이메일인 경우 AccessDeniedException(FORBIDDEN)을 반환하고 있는 것 같아요. 인증이 완료되었지만, 권한이 없는 경우(인증으 완료되었으나 인가가 되지 않음) 에 해당 에러를 반환하는데 이 상황에서는 적절하지 않은 것 같아요!

MDN 에서 다른 적절한 예외를 공부해보는 것도 좋을 것 같습니다😀

fyi; https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

2024-07-05 15:58 UTC, hocaron commented
1. 토큰 처리를 맞게 했는지 궁금합니다!
네, 생성하는 부분은 잘 처리해주신 것 같아요. 다만 위치가 MemberService 가 적절한지는 고민이 되어요. MemberSerice 하면 이메일 검증 / 회원 정보 조회 등 다양한 역할이 생길 수도 있을 것 같은데 이 클래스에서 토큰을 생성하는게 적절한지 고민해보면 좋을 것 같습니다👍

2. 401 Unauthorized와 403 Forbidden를 에러 상황에 맞게 잘 구분했는지 궁금합니다!
401 Unauthorized 는 적절하게 잘 사용해주셨네요💯 403 은 참고하면 좋을 것 같은 문서가 있어서 공유드렸습니다! 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

2024-07-06 14:22 UTC, hocaron commented
진택님, 안녕하세요👋

3단계 진행을 위해 이 PR 은 머지하고, 다음 PR 에서 이어나가겠습니다😀 반영이 필요한 부분은 3단계에서 부탁드릴게요👍

2024-07-06 14:22 UTC, merged

2024-07-06 14:26 UTC, jjt4515 commented
> 진택님, 안녕하세요👋
> 
> 3단계 진행을 위해 이 PR 은 머지하고, 다음 PR 에서 이어나가겠습니다😀 반영이 필요한 부분은 3단계에서 부탁드릴게요👍

네 감사합니다! 내일 열심히 해보겠습니다!!

2024-07-07 15:02 UTC, jjt4515 commented on src/main/java/gift/controller/MemberController.java
> +    }
MemberController내에서만 사용할 것 같아 inner class로 정의하였습니다! 느낌상 밖으로 빼두는게 더 좋을것 같기도 합니다..

2024-07-08 06:59 UTC, jjt4515 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
오 알겠습니다 !!

2024-07-08 10:26 UTC, jjt4515 commented on src/main/java/gift/service/MemberService.java
> +                .setSubject(member.getEmail())
이메일도 중복되지 않기에 이메일로 작성하였습니다!

2024-07-08 10:26 UTC, jjt4515 commented on src/main/java/gift/domain/Member.java
> +    private String secretKey;
이건 제가 착각을 해서,, secretKey가 일관되게 다시 수정하였습니다!

2024-07-08 16:44 UTC, jjt4515 commented on src/main/java/gift/service/MemberService.java
> +        }
넵 감사합니다!