충남대_BE 신성희 2주차 과제(step 1)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #318
Opened 2024-07-05 06:57 UTC by Shsin9797

궁금한 사항 : 
1. 예외처리시, 콘솔창에 메세지 뜨게 하려면 어떻게 고쳐야 하는지 궁금합니다.( 제가 본 자료대로 하니까 안되더라구요..)

2024-07-05 11:14 UTC, asebn1 requested changes
성희님 안녕하세요
멘토링에서 말씀드린부분위주로 1단계 PR 리뷰 드릴게요~
PR 충돌나는 부분 확인 부탁드려요 :)

2024-07-06 09:53 UTC, Shsin9797 commented
2주차 1단계까지 코드구현 완료했습니다!!

2024-07-06 10:26 UTC, asebn1 approved these changes
우선 멘토링 때 말씀드린 내용 위주로 구현 잘 해주셨네요~
지금 step2, step3 구현이 밀려있어 우선 빠르게 기능 구현을 목표로 나아가볼게요
(구현 마감이 일요일까지입니다 ㅠ)
step1을 빠르게 머지 드릴게요 🔥🔥🔥

2024-07-06 10:26 UTC, asebn1 commented on src/main/java/gift/Application.java
>      }
불필요한 줄바꿈이 있어요. (전체 코드 다 확인해주세요)
- 메서드 구현 사이엔 한 줄 줄바꿈만 적용해주세요. 
- 불필요한 빈 줄은 제거해주세요! 맨 마지막 개행은 한줄만 적용합니다~  (https://google.github.io/styleguide/javaguide.html)

2024-07-06 10:26 UTC, asebn1 commented on src/main/java/gift/controller/JdbcProductController.java
> +//    }
사용하지 않는 주석은 제거해주세요~

2024-07-06 10:26 UTC, asebn1 commented on src/main/java/gift/controller/JdbcProductController.java
>      }
`Product`가 아닌 dto로 반환하도록 개선할 수 있을 것 같아요.
dto 사용이 어떤 개선점이 있을까요?

2024-07-06 10:26 UTC, asebn1 commented on src/test/jdbc/jdbc-update-proudct-by-id.http
> +}
rest api를 직접 매번 호출하지 않고 테스트코드를 작성해볼 수 있을 것 같아요

2024-07-06 10:26 UTC, merged

2024-07-06 10:33 UTC, Shsin9797 commented
넵 감사합니다 멘토님!!!

2024-07-08 16:12 UTC, Shsin9797 commented on src/main/java/gift/controller/JdbcProductController.java
>      }
DTO(Data Transfer Object) 사용시 장점을 정리해 보았습니다!! 

1. 데이터 캡슐화 : 클라언트에게 필요한 데이터만 제공해서 불필요한 정보 노출을 방지할 수 있고, 민감한 정보를 숨기고 보안 강화 가능 

2. 유연성 : 클라이언트 요구사항에 맞는 데이터 구조 제공 가능 , api 버전 관리가 쉬워짐 

3. 성능최적화 : 필요한 데이터만 전송해서 네트워크 트래픽을 줄일 수 있음, 특정용도에 맞는 쿼리 최적화가 가능 

4. 계층간 분리 : 프레젠테이션 계층과 비즈니스 로직 계층을 명확히 분리할 수 있음. 내부 도메인 모델의 변경이 외부 API 에 영향을 미치지 않도록 할 수 있음. 

5. 검증 및 변환 로직 추가 : DTO에 특정 검증 로직을 추가하여 데이터 무결성을 보장할 수 있고, 복잡한 객체 변환 로직을 DTO 클래스에 캡슐화 할 수 있음 

 * 캡슐화(Encapsulation) : 객체지향 프로그래밍의 핵심원칙, 데이터와 데이터를 처리하는 메서드를 하나의 단위로 묶는것을 의미. 
 * 캡슐화의 특징과 목적 : 데이터 은닉(private), 접근제어(getter,setter), 정보은닉(객체 구현세부사항 숨기고 필요한 인터페이스만 노출) ,모듈화, 유연성과 재사용성 
 
 * DTO 컨텍스트에서 캡슐화 방법 : 필드를 private으로 선언 &  필요한 경우에만 getter 와 setter 메서드 제공 & 데이터 변환이나 유효성 검사 로직을 DTO 내부에 포함시킴 

6. 데이터 통합 : 여러 엔티티나 여러 테이블의 데이터를 하나의 DTO로 통합하여 제공 가능

7. 등등

2024-07-09 03:07 UTC, Shsin9797 commented on src/main/java/gift/controller/JdbcProductController.java
>      }
Repository : 엔티티 생성, 반환 
Service, Controller : DTO 생성, 반환

2024-07-09 12:14 UTC, Shsin9797 commented on src/test/jdbc/jdbc-update-proudct-by-id.http
> +}
넵 @SpringBootTest 이용해서 테스트 코드 작성해보겠습니다!! (공부중)