충남대 BE_이은경 2주차 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #321
Opened 2024-07-05 07:00 UTC by pkyung

## 과제 진행
### 위시 리스트
- [x] 위시 리스트 도메인 설계
- [x] 위시 리스트 상품 추가
- [x] 위시 리스트 상품 목록 조회
- [x] 위시 리스트 상품 삭제

2024-07-05 07:14 UTC, ksy90101 requested changes
빠르게 3단계 해주셨네요!
고생 많으셨습니다~
간단한 피드백 남겼으니 한번 확인해주세요~
언제든 궁금한게 있다면 DM주세요!

2024-07-05 07:14 UTC, ksy90101 commented on src/main/java/gift/config/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer {
👍

2024-07-05 07:14 UTC, ksy90101 commented on src/main/java/gift/dto/WishRequest.java
> +    private Long productId;
여기도 validate를 해보면 좋을거 같아요~
습관이 중요한거 같습니다!

2024-07-05 07:14 UTC, ksy90101 commented on src/main/java/gift/exception/wish/WishExceptionHandler.java
> +    }
이제 슬슬 중복이 생기는거 같아요.
이렇게 모든 모델마다 NotFoundException을 만든다면 계속 중복코드가 생기지 않을까요?

2024-07-05 07:14 UTC, ksy90101 commented on src/main/java/gift/exception/wish/WishExceptionHandler.java
> +    }
이것도 중복같아요
혹시 이런경우 어떻게 해결할수 있을지 고민해보면 어떨까요?
이건 좀 범용적인 예외가 아닐까요?

2024-07-05 07:14 UTC, ksy90101 commented on src/main/java/gift/model/Wish.java
> +    private String userEmail;
왜 userEmail을 넣어두었나요~?
user_id를 넣어도 되지 않을까요?

2024-07-05 07:14 UTC, ksy90101 commented on src/main/java/gift/repository/WishDao.java
> +                "WHERE w.userEmail = ?";
이렇게 되었을때 user_id가 있는 의미가 별로 없을거 같아요!

2024-07-05 07:14 UTC, ksy90101 commented on src/main/java/gift/resolver/LoginUserArgumentResolver.java
> +        String token = authorizationHeader.substring(7);
7이라는 단어는 무엇인지 저는 알기가 어려운데요
어떤 의미로 썼는지 상수로 나타내면 어떨까요?

2024-07-05 07:14 UTC, ksy90101 commented on src/main/java/gift/service/WishService.java
> +public class WishService {
```suggestion
import java.util.List;

@Service
public class WishService {
```

개행 하나도 의미전달의 의미가 있습니다. 이러한 부분들을 생각해보시면 좋을거 같아요~

2024-07-05 07:14 UTC, ksy90101 commented on src/main/java/gift/service/WishService.java
> +    }
```suggestion
    }
    
    public List<Product> getAllWishProductsByUser(String email) {
        return wishDao.findAll(email);
    }
```

2024-07-05 07:14 UTC, ksy90101 commented on src/main/java/gift/controller/WishController.java
> +    public ResponseEntity makeWish(@RequestBody WishRequest request, @LoginUser User user) {
user를 넘기는 방법도 있엇을텐데, email만 넘긴 이유가 있을까요!?

2024-07-05 08:42 UTC, ksy90101 requested changes
리뷰 반영 고생하셨어요~
간단한 피드백을 남겼습니다!
마지막으로 한번만 더 확인해보시죠!

2024-07-05 08:42 UTC, ksy90101 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
제가 이야기한것이 하나로 다 합치라는 의미는 아니였어요..
공통 예외는 공통으로.

각 컨트롤러의 예외는 각 컨트롤러 핸들러에 넣으면 어떨까 라는 생각이였습니다 ㅎㅎ

2024-07-05 08:42 UTC, ksy90101 commented on src/main/java/gift/resolver/LoginUserArgumentResolver.java
> +        String token = authorizationHeader.substring(BEARER_LENGTH);
7이 그런 의미라면

"Bearer "를 상수화하고, length를 쓰면 어떨까요?
위의 Bearer이 변경되면 또 여기도 신경ㄹ써야 하는데 한번에 변경되지 않을까요?

2024-07-05 08:42 UTC, ksy90101 commented on src/main/java/gift/model/LoginUser.java
> +public @interface LoginUser {
👍

2024-07-05 08:42 UTC, ksy90101 commented on src/main/java/gift/dto/WishRequest.java
> +public class WishRequest {
좀더 심화적인 내용으로 Java17을 쓰니 record를 공부해서 한번 적용해보면 어떨까요?

2024-07-05 08:42 UTC, ksy90101 commented on src/main/java/gift/dto/WishRequest.java
> +    private Long productId;
여기 리뷰 반영안되었습니다!

2024-07-05 12:49 UTC, pkyung commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
생각해보니 UserException이나 ProductException에서 같은 status를 반환할 것 같아서 합친 것인데 혹시 어떤 기준으로 공통이라는 것을 찾아야 하나요??

2024-07-06 01:31 UTC, ksy90101 approved these changes
고생하셨습니다~
이만 머지할게요!
언제든 궁금한게 있다면 DM주세요!

2024-07-06 01:31 UTC, ksy90101 commented on src/main/java/gift/controller/UserController.java
> +    public ResponseEntity<User> getUserById(@PathVariable("id") Long id) {
PathVariable의 value인 id는 위의 이름과 동일하다면 없애도 될거 같습니다~

2024-07-06 01:31 UTC, ksy90101 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
지금 처럼 해도 되고, 각 컨트롤러에만 사용하는 에러는 해당 컨트롤러의 Handler를 통해 응집도를 높혀보자는 의미였어요.

NotFound같은 경우엔 거의다 로직이 비슷할거 같아요.

그런 경우 NotFoundException을 만들고 처리하긴 합니다 ㅎㅎ

굳이 예외를 다 만들필요가 없다고 생각이 들어서요!

그런 의미였어요~

2024-07-06 01:32 UTC, merged