충남대 BE_박상우 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #323
Opened 2024-07-05 07:12 UTC by pswaao88

https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/233 2단계 pr입니다

제가 프론트엔드에 대한 지식은 없고 스프링을 처음 다루다보니 구글링과 여러 시행착오를 통해
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/66404498/46b2520d-c9c2-49ad-907d-5f0bb044f46a)

  사진과 같이 토큰 생성 후에 token.html파일로 전달하여 local storage에 저장해 GET /api/wish 요청을 보내도록 코드를 구성했습니다. 
  이렇게 진행을 하니 GET /api/wish 요청만 가고 /api/login/check에서 넘어가지 않아 자바스크립트로  코드를 추가해 /api/wish로 넘어가게 했습니다. 또한  인터셉트를 확인 결과 GET /api/wish , add 와 delete과정에서 의미가 없는 null값이 전달 됐습니다. 
지금의 방법으로는 인증이 되지 않더라도 위시리스트에 접근이 가능합니다. 어떠한 방법을 이용해야 생성한 토큰을 클라이언트에게 전달하고 전달 받은 토큰을 서버에게 요청을 할 수 있는지 궁금합니다. 지금의 방법에서는 어떻게 바꿔야 할지 감이오지 않아 질문 드립니다!

2024-07-07 10:01 UTC, Hyeon9mak requested changes
안녕하세요 상우님, 3단계까지 잘 진행해주셨습니다.

> 어떠한 방법을 이용해야 생성한 토큰을 클라이언트에게 전달하고 전달 받은 토큰을 서버에게 요청을 할 수 있는지 궁금합니다.

사실 정적 페이지를 응답하는 API 와 사용자의 요청을 수행하는 API 를 분리하도록 말씀드리는 이유는
이와 같은 요청들을 더욱 편하게 소화하기 위함인데요,
정적 페이지 응답 API 와 사용자 요청수행 API 가 완벽하게 분리되어 있다면
사용자 요청수행(로그인, 사용자 체크) API 에서 response header 에 token 을 담아 응답하는 것으로
쉽게 구현이 가능하지요~!!
우선 분리부터 시작해보시면 좋겠습니다!

우선 몇 가지 간단한 코멘트 남겼는데요,
다음 리뷰 요청때는 jwt 에 집중해서 코멘트 드리도록 하겠습니다.
궁금하신 점 얼마든지 질문 남겨주세요.

2024-07-07 10:01 UTC, Hyeon9mak commented on src/main/java/gift/Controller/MemberController.java
>      }
이전에도 비슷한 코멘트를 남겼던 것 같은데, 사용자의 요청을 수행하는 API 와, 정적 페이지를 반환하는 API 를 분리하는 것은 어떨까요?
정적 페이지를 요청하는 HTTP method 는 대게 GET 일텐데,
현재 POST 요청에도 정적 페이지를 반환하고 있어요. 이 부분이 부자연스럽게 느껴지네요.

2024-07-07 10:01 UTC, Hyeon9mak commented on src/main/java/gift/Controller/WIshListController.java
> +public class WIshListController {
오타!

2024-07-07 10:01 UTC, Hyeon9mak commented on src/main/java/gift/Controller/WIshListController.java
> +    private final UserService userService;
컨트롤러 명칭은 WishListController 인데, WIshlist 말고도 다루는게 많네요? 🤔 
정말로 WishListController 가 맞나요?

2024-07-07 10:01 UTC, Hyeon9mak commented on src/main/java/gift/Controller/WIshListController.java
> +        }
이메일을 system out print 문으로 로컬에 찍은 이유가 있을까요?

2024-07-07 10:01 UTC, Hyeon9mak commented on src/main/java/gift/Controller/WIshListController.java
> +    }
어떤 걸 하고 싶었던 API 일까요?

2024-07-07 10:01 UTC, Hyeon9mak commented on src/main/java/gift/Exception/ProductExceptionHandler.java
>      }
다시 변경한 이유가 있을까요?

2024-07-07 10:01 UTC, Hyeon9mak commented on src/main/java/gift/Repository/UserRepository.java
> +    private final RowMapper<String> rowMapper = new BeanPropertyRowMapper<>(String.class);
필드 멤버는 생성자보다 위에 두는게 컨벤션이죠~

2024-07-07 10:01 UTC, Hyeon9mak commented on src/main/java/gift/Repository/UserRepository.java
> +    }
없으면 어떤 일이 생기나요?

2024-07-07 10:01 UTC, Hyeon9mak commented on src/main/java/gift/Service/WebMvcConfig.java
> +        System.out.println("");
👀

2024-07-07 10:01 UTC, Hyeon9mak commented on src/main/java/gift/Service/WebMvcConfig.java
> +    }
`/api/wish/**` 와 같은 패턴으로도 등록이 가능해요!

2024-07-08 00:26 UTC, pswaao88 commented on src/main/java/gift/Service/WebMvcConfig.java
> +    }
위와 같은 형태로 변경했습니다!

2024-07-08 00:27 UTC, pswaao88 commented on src/main/java/gift/Service/WebMvcConfig.java
> +        System.out.println("");
계속 push하는데 파일이 꼬여서 남은 것 같습니다 지웠습니다

2024-07-08 00:28 UTC, pswaao88 commented on src/main/java/gift/Repository/UserRepository.java
> +    private final RowMapper<String> rowMapper = new BeanPropertyRowMapper<>(String.class);
정신이 없어서 지나쳤던거 같습니다 고쳤습니다!

2024-07-08 00:29 UTC, pswaao88 commented on src/main/java/gift/Exception/ProductExceptionHandler.java
>      }
코드가 꼬여서 이전 코드가 다시 push 된거 같습니다 고쳤습니다

2024-07-08 00:32 UTC, pswaao88 commented on src/main/java/gift/Controller/WIshListController.java
> +public class WIshListController {
오타 수정했습니다

2024-07-08 00:50 UTC, pswaao88 commented on src/main/java/gift/Repository/UserRepository.java
> +    }
없으면 EmptyResultDataAccessException 에러가 발생합니다. Userservice에서 try catch문으로 에러를 잡으려 했습니다

2024-07-08 00:52 UTC, pswaao88 commented on src/main/java/gift/Controller/WIshListController.java
> +        }
원래의 email로 값이 잘넘어오는지 확인하기 위해서 로컬에서 확인을 했었습니다. 미처 지우지 못한거 같습니다

2024-07-08 00:55 UTC, pswaao88 commented on src/main/java/gift/Controller/WIshListController.java
> +    }
제가 처음에 고안했던 코드가 제대로 작동하지 않아서 다른 방법으로 인증을 처리하려고 추가했던 것 같습니다.
지금 다시 보니 필요가 없을 거 같아서 삭제했습니다!

2024-07-08 03:08 UTC, pswaao88 commented on src/main/java/gift/Controller/MemberController.java
>      }
우선 postMapping 과 getMapping에 대해서 분리를 진행을 하였습니다! 그 후 user에 관한것들이 필요없다고 생각이 돼서 제거를 한 뒤 member를 이용을 하는 것으로 변경을 진행하였습니다. 
추가적으로 궁금한것이 생겼습니다.
기존에는 html파일로 토큰을 넘겨서 local storage에 저장하는 방식으로 진행을 하였는데 respone header에 토큰을 담기 위해서라면 return ResponseEntity.status(HttpStatus.OK)
                .headers(headers)
                .body("Bearer Token received: " + bearerToken);
                이와 같은 방식으로 리턴을 하면 되는건지 궁금합니다!
                또한 이런 방식을 진행하면 어떻게 다시 토큰을 넘겨야할지 잘 모르겠습니다

2024-07-08 03:09 UTC, pswaao88 commented on src/main/java/gift/Controller/WIshListController.java
> +    private final UserService userService;
위시리스트 컨트롤러지만 위시리스트를 다루기 위해서 product등이 필요하다고 생각해서 진행을 했습니다. 어떤 형식으로 변경을 해야하는 지 잘모르겠습니다.

2024-07-08 14:07 UTC, Hyeon9mak approved these changes
안녕하세요 상우님~ 피드백 잘 반영해주셨어요.
3주차 과제 진행에 도움되실만한 jwt 관련 코멘트 몇 가지 남겼습니다.
참고하여 3주차 과제 진행해주시면 좋을거 같아요 😉 👍 

2주차 과제 고생 많으셨습니다!
3주차 과제에서 만나요~

2024-07-08 14:07 UTC, Hyeon9mak commented on src/main/java/gift/Controller/MemberController.java
> +    }
> local storage에 저장을 하여 GET요청을 할 필요가 없다고 생각을 해 location.href = '/api/wish' 로 주소 이동을 하였습니다. 이러한 접근 방법이 올바른 방법인지 궁금합니다.

클라이언트단 까지 고려하여 고민해주신 점은 훌륭하다고 생각해요!
그러나 그것이 API 의 형상에 영향을 주는 것은 X 입니다.
API 는 클라이언트가 누구던 간 항상 stateless 하게 자신의 상태, 행동을 표현할 수 있어야해요.
localStorage 는 브라우저의 공간이고, 브라우저가 그걸 보존하던 아니건 신경써줄 필요가 없습니다.

... 만 현재는 개인이 작은 프로젝트를 진행중이므로 여러가지 시도를 해보셔도 좋을거 같아요 😉

2024-07-08 14:07 UTC, Hyeon9mak commented on src/main/java/gift/Controller/MemberController.java
> +    }
> button의 타입이 submit이 아니어서 발생한다고 알아내어 submit으로 교체를 해도 그대로 나옵니다 어떤 이유인지 궁금합니다!

button 태그가 form 태그 내부에 속해야 새로고침이 발생합니다! 😉

2024-07-08 14:07 UTC, Hyeon9mak commented on src/main/java/gift/Controller/WishListController.java
> +
> 위시리스트 컨트롤러지만 위시리스트를 다루기 위해서 product등이 필요하다고 생각해서 진행을 했습니다. 어떤 형식으로 변경을 해야하는 지 잘모르겠습니다.

제가 너무 추상적으로 코멘트를 남겼군요 🙏 
WishlistService 내부에서 product, member 를 다루는 건 어떤가하는 코멘트였습니다.
product 와 member 를 다루는 것 까지를 wishlist 라는 하나의 동작으로 볼 수도 있을거 같아서요 😉

2024-07-08 14:07 UTC, Hyeon9mak commented on src/main/java/gift/Controller/WishListController.java
> +
> 이메일이 일치하지 않으면 Exception을 throw해서 에러페이지를 띄울려고 했는데 의도대로 되지 않아서 에러페이지를 따로 만들려고 했습니다. 다른 방법이 있는지 궁금합니다

wishlist service 내부에서 이메일을 검사하고, 일치하지 않으면 runtime 하위 exception 을 하나 던져주는건 어떨까요?

exception handler 가 이를 catch 하여 자동으로 처리해주겠네요 😉

2024-07-08 14:07 UTC, Hyeon9mak commented on src/main/java/gift/Service/AuthorizationExtractor.java
> +    public static final String ACCESS_TOKEN_TYPE = AuthorizationExtractor.class.getSimpleName() + ".ACCESS_TOKEN_TYPE";// 무슨역할 인지 모르니 공부
내부에서만 사용되는 값이라면 private static final 로 선언해줄 수 있겠네요 😉

2024-07-08 14:07 UTC, Hyeon9mak commented on src/main/java/gift/Service/AuthorizationExtractor.java
> +        return Strings.EMPTY;
jwt 토큰 추출에 실패한다면 exception 을 던지는건 어떨까요?

2024-07-08 14:07 UTC, Hyeon9mak commented on src/main/java/gift/Service/BearerAuthInterceptor.java
> +        String token = authExtractor.extract(request, "Bearer");//토큰 추출
`Bearer` 로 추출한다는 사실도 authExtractor 내부로 숨겨줄 수 있겠어요!
interceptor 는 handler(controller) 에게 요청을 넘기기 전에 무언가 동작한다는 사실만 표현해주는 걸로 충분하죠~

2024-07-08 14:07 UTC, Hyeon9mak commented on src/main/java/gift/Service/BearerAuthInterceptor.java
> +        }
비어있다면 true?!

2024-07-08 14:08 UTC, merged

2024-07-08 16:53 UTC, pswaao88 commented on src/main/java/gift/Service/AuthorizationExtractor.java
> +    public static final String ACCESS_TOKEN_TYPE = AuthorizationExtractor.class.getSimpleName() + ".ACCESS_TOKEN_TYPE";// 무슨역할 인지 모르니 공부
고쳤습니다!

2024-07-08 16:54 UTC, pswaao88 commented on src/main/java/gift/Service/BearerAuthInterceptor.java
> +        }
false가 올바른거 같아 false로 고쳤습니다!

2024-07-08 16:55 UTC, pswaao88 commented on src/main/java/gift/Service/BearerAuthInterceptor.java
> +        String token = authExtractor.extract(request, "Bearer");//토큰 추출
authExtractor 내부로 숨겨준다는게 어떤 의미인지 모르겠습니다!

2024-07-08 16:56 UTC, pswaao88 commented on src/main/java/gift/Service/AuthorizationExtractor.java
> +        return Strings.EMPTY;
일단 추가적인 예외를 생성하는 것이 시간이 걸릴거 같아 IllegelArgumentException으로 던졌습니다

2024-07-08 16:56 UTC, pswaao88 commented on src/main/java/gift/Controller/MemberController.java
> +    }
이해됐습니다!