경북대 BE_도기헌_2주차 과제 (0단계, 1단계, 2단계, 3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #328
Opened 2024-07-05 07:18 UTC by Dockerel

# 0단계
1. 상품 관리 코드 이동
2. 1주차 리뷰 바탕으로 코드 수정
- [x] dto, dao 구분
- [x] 생성자 주입 Autowired 생략
- [x] db initialization 개선
- [x] getmapping optimize
- [x] controllerAdvice 사용
- [x] dao의 생성자에서 id 필드 제거
- [x] db name 컬럼 사이즈 초과 테스트 추가
- [x] js에서 사용된 주소를 공통 변수로 분리
## 질문 사항
Optional로 개선해 보는 것을 추천해주셨는데 findById 메서드의 반환값을 Optional<ProductDAO>로 변경하고 리팩터링을 실시하다보니 점점 코드가 산으로 가는 것 같아 Optional을 적용하지 못하였습니다. NullPointerException을 방지하지 위해 Optional을 사용한다는 것은 이해하였습니다. 그런데 제가 작성한 코드의 경우 null이 나올만한 케이스를 다 분기로 잡아 처리해주고 있는데 혹시 Optional을 사용하는 다른 이유가 있는지 궁금합니다.
# 1단계
## 코드 작성시 어려웠던 점
1단계는 대체적으로 괜찮았습니다. Validation에 대해 코드가 전반적으로 적절하게 작성되었는지만 봐주시면 될 것 같습니다.
# 2단계
## 코드 작성시 어려웠던 점
처음에 개념을 잘못 잡고 과제를 시작하여 코드를 총 3번 엎었습니다. 마지막으로 제가 이해한 단계는 서버측에서 username(email), password를 검증하여 jwt 토큰(accessToken)을 발행해줍니다. 클라이언트는 해당 토큰을 브라우저에 저장하고 매 요청마다 Authorization 필드에 토큰을 담아 보냅니다. 그러면 서버는 해당 토큰을 바탕으로 유효한 토큰이면 해당 요청을 처리합니다. &larr; 이렇게 개념을 잡고 과제를 수행하였습니다. 하지만 이렇게 쌩으로 짜보는건 처음이라 프로그래밍 패턴도 엉망이 된 것 같고 코드를 작성하면서도 너무 헷갈렸습니다.
# 3단계
## 코드 작성시 어려웠던 점
Authorization 으로 받은 토큰을 어떻게 서버측에서 받아낼지 고민을 많이 했습니다. nodejs에서는 구현하기 쉬웠던 middleware을 spring에서는 어떻게 구현할지 고민을 하다 filter로 middleware을 구현해보기로 하였습니다. 혹시 spring에서 middleware을 구현할 때 제가 사용한 방법을 사용하는지 혹은 다른 더 나은 방식이 존재하는지 알고 싶습니다.

항상 코드 리뷰해주셔서 감사합니다 ☺️

2024-07-05 18:29 UTC, gongdongho12 requested changes
> Optional을 사용하는 다른 이유?

애초에 이 값이 null이 들어올 수 있는 부분을 인지했는데 그냥 클래스 A랑 Optional<A>가 있으면 별도로 이 클래스가 null인지 체크하지 않더라도 실제 null이 들어오는 객체라 조심해서 써라는 의미입니다

> 제가 작성한 코드의 경우 null이 나올만한 케이스를 다 분기로 잡아 처리해주고 있는데

null이 없는 실제 상황에만 일반 클래스 타입으로 쓰고 null이 나오는 경우를 레포지토리에서 Optional로 정의하고 orElseThrow 등으로 일반 타입으로 바꿔주면서 exception을 걸어주면 그걸로 리턴되는 경우엔 null이 나오지 않는다고 확실하게 인식할 수 있겠죠?

특히 본인이 작성하지 않은 코드면 이 값이 null인지 아닌지에 대해 확신하기 어려운데 그 부분에 명시적으로 null이 들어갈 수 있다에 대한 표현이 있으면 같이 작업하는 개발자도 손쉽게 파악할 수 있는 장점이 있습니다

> spring에서 middleware을 구현할 때 제가 사용한 방법을 사용하는지?

매 유저 사용 코드에 아래처럼 사용해 주셨는데요
`String email = (String) request.getAttribute("email");`
스프링 시큐리티에선 jwt claim을 바로 파라미터로 받을 수 있어요
관련해서 한번 시큐리티 프로젝트의 로그인 이후 처리 로직에 찾아보시면 좋은 결과를 얻으실 수 있을거에요
화이팅입니다

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/java/gift/filter/JwtFilter.java
> +            String token = authorizationHeader.substring(7);
(Bearer + " ") 의 길이 = 7을 위에처럼 작성했는데 저 두 값을 상수로 받고, 그 상수의 길이 느낌으로 정의하면 깔끔하지 않을까요?

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/java/gift/model/User.java
> +    }
이부분 로깅의 용도나 디버깅 용도일 것 같은데
실제 클래스명인 User로 적어두는게 좋지 않을까요? 아니면 이 클래스명도 변경해서 일치시켜 주거나요

컨벤션이 맞지 않는것 같아요

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/java/gift/model/User.java
> +    private String password;
적합한 제약조건 👍🏼 

그런데 SQL 스키마에는 255까지 해둔 이유가 있을까요?

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/java/gift/repository/JdbcProductRepository.java
> +        return product;
이런식으로 새 객체를 넣을거면 파라미터를 받을게 아니라 직접 메서드 내부에서 넣어주는 편이 좋지 않을까요?

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/java/gift/model/ProductDAO.java
> +    }
DAO라고 썼지만 DAO의 역할을 할 수 있는 객체일까요?

Product라고 쓰고 ProductRequest 정도가 있다가 아닌지 한번 고민해보면 좋을 것 같습니다

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/java/gift/filter/JwtFilter.java
> +        filterChain.doFilter(servletRequest, servletResponse);
이 필터의 동작이 어려웠으면 이 로직의 claim 부분에 대한 테스트를 필수적으로 작성하셨어야 할 것 같아요

그러면 코드의 안정성도 검증해 나가실 수 있지 않을까요?

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/java/gift/controller/WishlistController.java
> +    }
매번 String email = (String) request.getAttribute("email"); 이부분이 보이는데
개선할 방향을 시큐리티 사용방법 학습하시면서 업데이트 하시면 좋을 것 같아요

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/java/gift/filter/JwtFilter.java
> +        filterChain.doFilter(servletRequest, servletResponse);
**테스트는 항상 복잡한 부분, 비지니스 로직 처럼 중요한 부분에 작성**합니다
그런데 상품의 레포지토리 말고는 테스트가 없네요... 😢

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/resources/templates/login.html
> +        });
fetch도 사용해보셨군요 👍🏼

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/java/gift/controller/UserController.java
> +@RequestMapping("/api")
유저 컨트롤러인데 `/api/user` 등으로 표기하지 않아도 괜찮을까요?

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/resources/static/js/gotoPage.js
> +addButton.addEventListener("click", gotoAdd);
js도 점점 쉽게 사용해 나가시는 모습 👍🏼

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/resources/sql/schema.sql
> +    email     varchar(255),
밸리데이션으로 사이즈도 지정했으면 줄일 수 있는 부분은 같이 줄여가면 좋을 것 같아요

+) 그리고 테스트하실떄 한글이랑 영문 각각 사이즈 체크해보면 좋을 것 같아요

2024-07-05 18:29 UTC, gongdongho12 commented on src/main/java/gift/util/Vars.java
> +}
이것도 properties에 넣는건 어떠실까요?
바뀌지 않는 값이니까요

2024-07-07 03:45 UTC, Dockerel commented on src/main/java/gift/filter/JwtFilter.java
> +            String token = authorizationHeader.substring(7);
아하 넵 "Bearer " 부분은 상수로 빼서 처리하고 authrizationHeader==null 인 경우에 분기로 미리 처리하여 개선해보았습니다!

2024-07-07 03:45 UTC, Dockerel commented on src/main/java/gift/model/User.java
> +    }
넵넵 UserDTO라는 명칭이 필요없을 것 같아 User로 바꾼뒤 컨벤션에 맞게 변경하였습니다!

2024-07-07 03:47 UTC, Dockerel commented on src/main/java/gift/model/User.java
> +    private String password;
스키마를 먼저 정의해서 까먹고 놔둔것 같습니다 ㅎㅎ.. 제약조건에 맞게 수정완료하였습니다!

2024-07-07 03:49 UTC, Dockerel commented on src/main/java/gift/repository/JdbcProductRepository.java
> +        return product;
말씀해주신대로 바꾸면 더 깔끔해질 것 같습니다. id를 파라미터로 받는 생성자를 추가하여 리팩토링 해보았습니다!

2024-07-07 03:51 UTC, Dockerel commented on src/main/java/gift/model/ProductDAO.java
> +    }
찾아보니 제가 DAO에 대해 잘못 알고 있던 것 같습니다. 찾아보니 직접 DB에 접근하여 data를 삽입, 삭제, 조회 등 조작할 수 있는 기능을 수행한다고 하였는데 그렇다면 현재 제 코드에서 repository의 객체들이 DAO의 역할을 하는 것일까요? 그렇다면 repository에 정의되어 있는 것들이 원래는 DAO로써 정의되어야 했을지 궁금합니다!

2024-07-07 04:06 UTC, Dockerel commented on src/main/java/gift/filter/JwtFilter.java
> +        filterChain.doFilter(servletRequest, servletResponse);
말씀해주신대로 테스트들이 부족한 것 같아 filter와 validation 등 여러 테스트를 작성해보았습니다. 그런데 filter의 테스트를 위해 처음엔 최대한 Junit으로 해보려 했는데 도저히 방법을 찾지 못하여 mockito를 살짝 공부하여 authorization 필드에 accessToken을 첨부하여 get 요청을 날리는 방식으로 테스트 해보았습니다. 혹시 junit으로도 해당 테스트를 구현할 수 있을까요?

2024-07-07 04:07 UTC, Dockerel commented on src/main/java/gift/controller/WishlistController.java
> +    }
아하 넵! 시큐리티 공부하면서 개선해보겠습니다! 🫡

2024-07-07 04:08 UTC, Dockerel commented on src/main/resources/templates/login.html
> +        });
넵~👍

2024-07-07 04:09 UTC, Dockerel commented on src/main/java/gift/controller/UserController.java
> +@RequestMapping("/api")
말씀해 주신대로 /api/user 로 표기하는게 더 일관성이 있어 보여 그렇게 수정하였습니다!

2024-07-07 04:10 UTC, Dockerel commented on src/main/resources/static/js/gotoPage.js
> +addButton.addEventListener("click", gotoAdd);
감사합니다 😊

2024-07-07 04:12 UTC, Dockerel commented on src/main/resources/sql/schema.sql
> +    email     varchar(255),
넵 해당 길이들에 대해 수정 완료하였습니다. 그런데 길이 테스트 시 한글이랑 영문 모두 사이즈가 차이가 없었는데 혹시 제가 놓친 부분이 있었을까요?
```
@Test
    public void save_nameLongerThan15Char_eng() {
        //given
        String wrongName = "a".repeat(16);
        ProductDTO product = new ProductDTO(wrongName, 123, "www.test.com");

        //when
        Set<ConstraintViolation<ProductDTO>> violations = validator.validate(product);

        //then
        Assertions.assertThat(violations).isNotEmpty();
    }

    @Test
    public void save_nameLongerThan15Char_kor() {
        //given
        String wrongName = "가나다라마바사아자차카타파하호우";
        ProductDTO product = new ProductDTO(wrongName, 123, "www.test.com");

        //when
        Set<ConstraintViolation<ProductDTO>> violations = validator.validate(product);

        //then
        Assertions.assertThat(violations).isNotEmpty();
    }
```

2024-07-07 09:02 UTC, Dockerel commented on src/main/java/gift/util/Vars.java
> +}
secretKey와 위에서 말씀하신 tokenPrefix("Bearer ") 모두 properties에 넣어 적용하였습니다!

2024-07-07 10:30 UTC, gongdongho12 commented on src/main/resources/sql/schema.sql
> +    email     varchar(255),
아닙니다 DB중에 다른 경우가 있더라구요!
H2 사용에는 문제 없을 것 같습니다 👍🏼

2024-07-07 15:57 UTC, gongdongho12 commented on src/main/java/gift/model/ProductDAO.java
> +    }
DAO는 JPA가 적용되고 의미가 생길 것 같습니다
현재 단계에서는 DTO 개념으로만 사용되고 있습니다

2024-07-07 15:58 UTC, gongdongho12 approved these changes

2024-07-07 15:58 UTC, merged