경북대_BE 신형진 step0
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #33
Opened 2024-07-01 06:09 UTC by hjinshin

2024-07-01 12:59 UTC, leaf-upper requested changes
안녕하세요 형진님.
1주차에 이어서 2주차도 잘부탁드려요~
스프링에 대해서 이미 많이 알고계신분인것 같아요.
몇가지 코멘트를 드렸는데 코멘트 주시거나, 코드를 수정해주시면 Step0는 어프로브 드겠습니다.
Step0 고생하셨습니다~

2024-07-01 12:59 UTC, leaf-upper commented on src/main/java/gift/config/WebConfig.java
> +        return new HiddenHttpMethodFilter();
해당 필터에 대한 간략한 설명해주시면 좋을것 같아요~

2024-07-01 12:59 UTC, leaf-upper commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
validation 의존성을 추가해주셨는데요~
해당 의존성에 대한 간략한 설명 해주시면 좋을것 같아요~

2024-07-01 12:59 UTC, leaf-upper commented on src/main/resources/db/schema.sql
> +create table product(
not null 과 같은 제약조건은 필요 없으실까요?

2024-07-01 12:59 UTC, leaf-upper commented on src/main/java/gift/controller/ProductController.java
> +public class ProductController {
RestController와 Controller는 패키지를 분리시켜두면 좋을것 같아요~

2024-07-01 12:59 UTC, leaf-upper commented on src/main/java/gift/controller/AdminController.java
> +    @DeleteMapping("/admin/product/{id}")
다른 URL과 동일한 컨벤션을 가져가면 좋을것 같아요~ "/"를 다른곳에도 다 붙이거나, 해당 메서드에서 지우는건 어떠세요?

2024-07-01 12:59 UTC, leaf-upper commented on src/main/java/gift/model/ProductDao.java
> +@Component
Component보다는 Repository가 좀더 표현하기 좋은 애너테이션일것 같아요~

2024-07-01 12:59 UTC, leaf-upper commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Void> createProduct(@RequestBody ProductRequest request) {
ProductRequest에 대해서는 Validation 코드가 없는것 같은데, 
의존성도 추가해두셨으니 한번 사용해보면 어떨까요?

2024-07-02 08:07 UTC, hjinshin commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
validation 의존성은 유효성 검사에 필요한 어노테이션을 사용하기 위해 추가하였습니다.

2024-07-02 08:07 UTC, hjinshin commented on src/main/java/gift/config/WebConfig.java
> +        return new HiddenHttpMethodFilter();
해당 필터는 client의 form에서 오는 http의 hidden method를 필터링하기 위한 필터입니다.
html의 form 태그는 기본적으로 POST, GET 메서드로만 제출이 가능하기 때문에 form에서 DELETE, PUT 요청을 보내기 위해서는 <input type=“hidden”> 에 method 속성으로 지정해주어야 합니다.
이 요청을 받은 서버가 이 input 태그의 hidden 타입의 method 속성을 확인하기 위해서 HiddenHttpMethodFilter()를 사용했습니다.

2024-07-02 08:22 UTC, hjinshin commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Void> createProduct(@RequestBody ProductRequest request) {
ProductRequest에 대한 Validation 코드는 다음 step1 에서 제출하도록 하겠습니다!

2024-07-02 14:25 UTC, leaf-upper approved these changes
고생하셨습니다~ 형진님
다음단계 진행 부탁드립니다!

2024-07-02 14:25 UTC, merged