경북대 BE_권도윤 2주차 과제 (1 ~3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #330
Opened 2024-07-05 07:19 UTC by doyooon

2024-07-05 16:42 UTC, MangKyu requested changes
wishlist와 관련된 기능이 보이지가 않네요! 해당 부분 보완 부탁드리겠습니다!

2024-07-05 16:42 UTC, MangKyu commented on build.gradle
> +    runtimeOnly "io.jsonwebtoken:jjwt-gson:${JJWT_VERSION}"
아래 2개의 의존성은 어떠한 이유로 추가된 것일까요~?

2024-07-05 16:42 UTC, MangKyu commented on src/main/java/gift/Product.java
> +    @Pattern(regexp = "^((?!카카오).)*$", message = "\"카카오\"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있습니다.")
제약 조건은 크게 2종류로 나눌 수 있는데요~
- 입력 데이터에 따른 유효성
- 비즈니스 정책에 따른 유효성

위의 코드 기준으로는 데이터 유효성과 비즈니스 정책이 혼합되어 있는 것 같습니다ㅎㅎ
참고로 입력 데이터 부분은 애노테이션으로 처리하고, 비즈니스 정책에 대한 부분은 비즈니스 관련 클래스(Product)에 드러나는 것이 좋은 설계인 것 같습니다 ㅎㅎ 비즈니서 정책과 관련된 부분은 코드로 드러내어 우리의 정책을 쉽게 파악할 수 있어야 합니다!

2024-07-05 16:42 UTC, MangKyu commented on src/main/java/gift/ProductController.java
> +    @DeleteMapping("/delete/{id}")
적절한 HttpMethod로 변경해주는 부분 좋네요! 👍

2024-07-05 16:42 UTC, MangKyu commented on src/main/java/gift/user/UserController.java
> +    @Autowired
생성자 주입을 활용하면 어떨까요~? 생성자 주입의 장점에 대해서는 [해당 포스팅](https://mangkyu.tistory.com/125) 참고 부탁드립니다!

2024-07-08 05:24 UTC, doyooon commented on build.gradle
> +    runtimeOnly "io.jsonwebtoken:jjwt-gson:${JJWT_VERSION}"
[https://github.com/jwtk/jjwt?tab=readme-ov-file#gradle](url)
이 부분을 보고 추가 했는데 구체적인 이유는 알아보지 않고 추가했습니다..ㅠㅠ 왜 사용하는지 모르겠습니다..

2024-07-08 09:21 UTC, doyooon commented on build.gradle
> +    runtimeOnly "io.jsonwebtoken:jjwt-gson:${JJWT_VERSION}"
그리고 jwt 토큰 기능을 현재 공부중에 있습니다! Filter가 제대로 동작하지 않아 계속 commit은 못하는 상태인데 빠른 시일내로 완성해서 커밋해보도록 하겠습니다!

2024-07-09 12:33 UTC, merged