부산대 BE_진서현_2주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #332
Opened 2024-07-05 07:32 UTC by jinseohyun1228

1. 인터셉터를 이용해서 (로그인,홈,회원가입)이외의 요청에서 헤더에 담긴 jwt를 검증하고 세션에 넣었습니다.
2.  검증 성공시 홈창으로 리다이렉트하려햇는데 과제  요구사항이랑 달라져 주석처리 했습니다.

2024-07-05 16:57 UTC, hocaron requested changes
서현님, 안녕하세요!

REST API 모두 만들어주셨네요💯 같이 작업하는 입장에서 궁금한 부분이 생겨 코멘트를 드린 부분이 있는데 확인 부탁드릴게요!

2024-07-05 16:57 UTC, hocaron commented on src/main/java/gift/main/controller/AdminController.java
> +    @GetMapping("/product/list")
RESTful 하게 list 대신 id 를 적지 않는 것으로 대체할 수 있을 것 같습니다😀
```suggestion
    @GetMapping("/product")

```

fyi; [RESTful API 관련 문서](https://meetup.nhncloud.com/posts/92)

2024-07-05 16:57 UTC, hocaron commented on src/main/java/gift/main/controller/AdminController.java
> +    }
단순 궁금증입니다😀 반환값을 Map 으로 하는 이유가 있을까요?!

2024-07-05 16:57 UTC, hocaron commented on src/main/java/gift/main/global/GlobalExceptionHandler.java
> +        System.out.println("e.getMessage() = " + e.getMessage());
로깅을 위한 프린트 좋습니다👍

2024-07-05 16:57 UTC, hocaron commented on src/main/java/gift/main/global/GlobalExceptionHandler.java
> +                .body(responseBody);
내부 로직이 반복되고 있어서, errorMessage 및 statusCode 를 가지고 있는 enum 클래스를 생성하여 예외처리를 하는 것도 좋아보입니다👍

2024-07-05 16:57 UTC, hocaron commented on src/main/java/gift/main/global/validator/IsValidName.java
> +public @interface IsValidName {
네이밍 좋습니다👍

2024-07-05 16:57 UTC, hocaron commented on src/main/java/gift/main/repository/ProductDao.java
> +        createProductTable();
테이블 생성 로직이 스프링 빈 생성 로직과 함께 있는 이유가 있을까요?!😀
아래 설정을 통해 생성해볼수도 있을 것 같아요.

``
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
```

2024-07-05 16:57 UTC, hocaron commented on src/main/java/gift/main/service/MemberService.java
> +    public String joinUser(UserJoinRequest userJoinRequest) {
Uesr, Member 모두 회원을 의미하는 단어로 사용되는 것 같아요! 통일해도 좋을 것 같습니다👍

2024-07-05 16:57 UTC, hocaron commented on src/main/java/gift/main/service/MemberService.java
> +            throw new UserException("해당 이메일주소는 존재하지 않습니다.");
사소하지만, 이메일과 비밀번호가 틀린 경우 에러가 달라서 악의적인 사용자가 랜덤으로 데이터를 돌려보고 값을 유추하기 쉬운 것 같아요. 좀더 모호한 에러메시지를 사용해보는 것도 좋을 것 같아요😀

2024-07-05 16:57 UTC, hocaron commented on src/main/java/gift/main/util/AuthUtil.java
> +    public AuthUtil(@Value("${spring.jwt.secret}") String secret) {
property 로 관리하는 방식 좋습니다! 환경별로 값을 관리할 수 있겠군요?!!

2024-07-05 16:58 UTC, hocaron commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        String password = request.getHeader("password");
헤더에 email, password 가 들어오는 이유가 궁금합니다💭

2024-07-05 16:59 UTC, hocaron commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
인증을 구현할 때, 인터셉터와 필터에서 구현하는 방식을 생각해볼 수 있을 것 같아요. 필터 대신 인터셉터를 선택하신 이유가 궁금해요.(단순 궁금증입니다)

2024-07-05 17:03 UTC, jinseohyun1228 commented on src/main/java/gift/main/controller/AdminController.java
> +    @GetMapping("/product/list")
넵 제가 이 부분 공부하고 다시 코멘트 달겠습니다!

2024-07-05 17:05 UTC, jinseohyun1228 commented on src/main/java/gift/main/repository/ProductDao.java
> +        createProductTable();
헉 이부분 제가 지금 공부하고 있는데요..!!
앞서서 리뷰 달아주신 것을 보았으나, 일단 구현에 앞서 반영하고 있지 못했습니다... 
이외의 방법으로는 어떻게 생성하는지 몰라서 못한게 큽니다..!! 

바로 알려주셔서 감사합니다.. 하지만 제가 조금만 더 공부해보고 반영하도록 하겠습니다!

2024-07-05 17:07 UTC, jinseohyun1228 commented on src/main/java/gift/main/service/MemberService.java
> +    public String joinUser(UserJoinRequest userJoinRequest) {
넵!! 반영하겠습니다!

2024-07-05 17:09 UTC, jinseohyun1228 commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
라이브 강의에서 인터셉트에 대해서 더 많이 설명해주셨고,  저도 인터셉터는 한번도 써본적이 없어서 한번 사용해보고 싶었습니다!

2024-07-05 17:11 UTC, jinseohyun1228 commented on src/main/java/gift/main/global/GlobalExceptionHandler.java
> +                .body(responseBody);
아..!! 생각하지 못했습니다!! 좋은 것 같습니다 그런데 혹시 제가 잘 이해한게 맞는지 궁금한데요,,!

>errorMessage 및 statusCode 를 가지고 있는 enum 클래스를 생성

각 상황에 맞는 enum 클래스를 미리 생성해놓고, 에러메시지를 enum 클래스로 대체하라는 말씀맞나요??

2024-07-05 17:11 UTC, jinseohyun1228 commented on src/main/java/gift/main/global/validator/IsValidName.java
> +public @interface IsValidName {
감사합니다..ㅎㅎ!!

2024-07-05 17:14 UTC, jinseohyun1228 commented on src/main/java/gift/main/util/AuthUtil.java
> +    public AuthUtil(@Value("${spring.jwt.secret}") String secret) {
넵..! 그리고 환경변수 적용을 개인적으로 좋아합니다!!
제가 오타를 잘 못보고, 잘 내기도 하는데, 프로퍼티로 두면 관리도 쉽고, 확인하기에 편해서 선호합니다..ㅎ 
~~그리고 조금 멋있는 방식이라고도 생각합니다..ㅎ~~

2024-07-05 17:19 UTC, jinseohyun1228 commented on src/main/java/gift/main/controller/AdminController.java
> +    }
ajax에서 물건 리스트 조회 부분에서 키값으로 접근해 객체리스트를 가져오고 있습니다.
큰 이유는 없고,,, 제가 이 방법만을 알고 있어서... 입니다. 

혹시 좋은 방법을 알게 된다면 반영하겠습니다. ..!! 

```
 success: function (response) {
                    var products = response.products;
                    var html = '';
                    products.forEach(function (product) {
```

2024-07-05 17:27 UTC, jinseohyun1228 commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        String password = request.getHeader("password");
제가 JWT동작 방식을 처음에 잘못 이해한 것 같습니다..!

제가 이해한 jwt 동작원리: 
사용자 : (토큰 , 아이디, 비밀번호 ) -> 서버 
서버 : 받은 아이디와 비밀번호로 토큰 다시 만들어보기 : 동일하면 검증 성공

>실제 동작원리 :  
>1. jwt 열어보기 
>2. jwt 내부 서명과 서버가 가진 시크릿키로 토큰 다시 만들기 : 동일하면 검증성공


제가 잘 모르고, 인증을 위해서 줘야겠다고 생각했습니다. 막상 코드를 쓰고 나서는 필요가없어진걸 알았음에도 지우지 않고 있었습니다.

이유 ) 별문제 없을 것이라고 생각함
- 실제 : 올바른 토큰 을 가져도 이메일과 비밀번호가 없으면 인증에 실패하는 오류 발생
- 또한, 저는 협업중!이기 때문에 이유없는 코드가 있으면 리뷰어나 동료에게 혼란을 줄 수 있다는 걸 명시하고 이 부분 고치도록 하겟습니다1!

2024-07-05 17:33 UTC, jinseohyun1228 commented on src/main/java/gift/main/service/MemberService.java
> +            throw new UserException("해당 이메일주소는 존재하지 않습니다.");
헉..! 사실 나름 의도한 부분이었습니다... 
개인적으로 비밀번호와 이메일을 입력시 자주 틀려 틀린 지점을 알려주는 메시지가 좋다고 느꼇습니다.
반대로 모호한 메시지는 무성의하다고 느ㄱ꼈는데, 실제로는 보안을 위한 의도된 메시지였다는 걸 새로 알았습니다..!!

사용자를 생각했을떄도 보안이 우선인 것이 좋을 것 같습니다 ㅎㅎ

코멘트 안남겨주셨다면 저는 모호한 메시지보다 확실한 메시지가 좋다고만 생각햇을 것 같습니다.
자세히 리뷰 남겨주셔서 제가 또 신경쓸점을 알게되네요! 감사합니다ㅎㅎ

이메일과 아이디가 비슷한 유저들이 많을 것 같아 이 경우에는 메시지가 모호한 것이 좋을 것 같습니다.
반대로 인스타처럼 이미 아이디가 다 공개된 서비스에서는 보안을 위한 다른 방법을 생각해야할 같습니다!!

2024-07-06 06:49 UTC, hocaron commented on src/main/java/gift/main/controller/AdminController.java
> +    }
현재 방법에서는 products 라는 키 값으로 가져오고 있는 것 같아요. 지금 상태는 API 응답이 view 단에 보여주기 위해 맞추어져있다는 느낌이 들기도 합니다🤔

```java
    @GetMapping("/product/list")
    public ResponseEntity<List<Product>> getProducts() {
        List<Product> products = productService.getProducts();
        return ResponseEntity.ok(products);
    }
```
위의 처럼 응답값을 list 로 반환 후에 ajax 에서 response 값을 그대로 활용하면 예상대로 동작할 것 같은데 어떻게 생각하실까요?!

```javascript
 success: function (response) {
                    var products = response;
```

2024-07-06 06:52 UTC, hocaron commented on src/main/java/gift/main/global/GlobalExceptionHandler.java
> +                .body(responseBody);
넵 맞습니다! enum 클래스로 정의해두면, 핸들러쪽에서 반복되는 로직을 줄일 수 있을 것 같은데요! 그러기 위해서는 현재 커스텀한 예외를 어떻게 리팩토링하면 좋을지 고민해봐도 좋을 것 같아요😀

아래처럼 사용하는 것은 어떤지 서현님의 생각이 궁금해요!

```java
public enum ErrorCode {
    INVALID_INPUT_VALUE("C001", HttpStatus.BAD_REQUEST, "요청 값이 잘못되었습니다."),
    ;

    private final String code;
    private final HttpStatus httpStatus;
    private final String [message;](url)
```

2024-07-06 07:04 UTC, hocaron commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
아하 그렇군요! 요청 전처림 및 후처리가 필요할 때마다 구현을 필터 / 인터셉터 / AOP 등 어디가 제일 적절할지 고민이 많이 되는 것 같아요.

심심하실 때, 읽어보기 좋은 자료를 공유드립니다!
https://www.baeldung.com/spring-mvc-handlerinterceptor-vs-filter#key-differences-and-use-cases

2024-07-06 12:08 UTC, jinseohyun1228 commented
충돌 해결했습니다!

2024-07-06 12:10 UTC, hocaron commented
빨리 확인해주셔서 감사합니다👍

오늘 피드백 같이 확인할 수 있는 부분까지 마무리하고, 다음 pr에서 이어가겠습니다😀

2024-07-06 13:31 UTC, jinseohyun1228 commented
헉 넵! 사실 제가 주말에는 아르바이트를 하고 있어 시간을 많이 못썼습니다... 최대한 빠르게 공부하겠습니다 감사합니다.
오늘 질의응답에 올라온 질문에 멘토님과 멘토링 시간에 얻는 생각들로 나름 답변도 달아봤습니다..!!
멘토님덕분에 저도 고민 정리하고 공유할수도 있어서 뿌듯했습니다 ㅎㅎ

2024-07-06 14:19 UTC, merged

2024-07-06 15:59 UTC, jinseohyun1228 commented on src/main/java/gift/main/service/MemberService.java
> +    public String joinUser(UserJoinRequest userJoinRequest) {
반영했습니다! !

2024-07-07 00:48 UTC, jinseohyun1228 commented on src/main/java/gift/main/global/GlobalExceptionHandler.java
> +                .body(responseBody);
처음에는 왜 enum을 추천해주시는지 어려었는데, 제가 잘못생각했다는 것을 알게되었습니다.

```
(내가 생각한 것)
이메일을 잘못 적용했을때 이메일에러메시지 enum
public enum 이메일 {
	에러코드("401"),
	에러메시지("이메일이 틀렸습니다.")
}

--이런식으로 enum 클래스 엄청 많이 두기--

(실제)
public enum 에러코드 {
	잘못된_이메일("상태코드","에러메시지")
	잘못된_상품명("상태코드","에러메시지")
	...
}
```

- 바로 에러메시지 자체를 하나의 객체화하기 위해서다.
(enum은 상수가 아니다. 하나의 객체다. (실제로 힙메모리에 저장된다.)

### Enum의 장점

1. 타입 비교가 가능헤 IDE의 도움을 받을 수 있다.
2. 개발자의 실수로 인한 다른 값이 동일하게 처리될 확률을 줄여준다.
    
    `한달의 첫번째날` 과 `일주일의 첫번째 날`을 동일하게 판단하는 경우
    
3. 리팩토링 변경 범위가 최소화된다.

## Enum으로 에러메시지를 작성한다면!

1. 에러 메시지를 한 곳에서 수정이 가능하다.
2. 객체 타입이기 때문에 좀 더 많은 IDE의 지원을 받을 수 있다.
    
    현재 내가 에러 메시지를 보고 찾아가려면…^^ 검색해서 가야한다는 치명적인 단점;;ㅋㅋ
    
3. enum은 객체&싱글턴으로 간단하고 안전하게 동일한지 검사할 수 있다.
    
    ```java
    만약 내가 특정 상황에서 반환하는 에러메시지가 A인지 검사하고 싶다면?
    
    <문자열로 직접 메시지를 넣은 경우>
    - 상황을 만든다.
    - 에러메시지를 구현한 곳에 찾아..찾아..찾아..가서 복사해서 직접 검사
    -> 오타 대마왕인 나에게는 실제로는 잘 동작하지만, 에러 검사시 틀린 값을 내는 등의 불안요소가 커진다.
    
    <enum 으로 에러메시지로 구현한 경우>
    - 상황을 만든다.
    - enum클래스.발생객체 == 로 검사하면 된다.
    

    ```
    
4. 결국 **관리가 편한 상황**을 만들어준다.


이후 변경을 적용하고 테스트 코드를 작성해봤습니다.
테스트 코드를 enum을 활용해서 하는 방향도 생각해보겠습니다!

2024-07-08 07:01 UTC, jinseohyun1228 commented on src/main/java/gift/main/repository/ProductDao.java
> +        createProductTable();
## 테이블 생성을 하는 세가지 방법

### **1. 빈 생성시 초기화로직을 통해서 (현재 내 방법)**

- 단순하게 객체를만들 때, 초기화를 할 수 있다.

**단점** 

1. **테이블 생성시간에 따라 빈 생성이 지연되고 어플리케이션 시작 시간이 늦어진다.** 
    
     어떤 방법이든 어플리케이션 시작시 테이블을 생성하는 점에서 동일하지만, *****스크립트를 활용한 테이블 생성은 병렬적으로 이뤄지기 때문에* 시간이 단축될 수 있다.
    
     초기화를 통한 테이블 생성은, 빈이 초기화될 때마다 순차적으로 데이터 베이스 작업을 수행하기 때문에 시간이 늦어질 수 있다.
    
2. **테이블 생성 시점에 데이터 베이스가 준비 되지 않을 수도 있다.** 
    
    비 생성 순서에 따라 순차적으로 실행되기 때문에,**생성 순서에 영향을 받는다.**
    

### **2. `@PostConstruct` 어노테이션 사용**

특정 빈이 초기화 된 이후에 테이블을 생성하는 방법이다.

### **3. `script`파일을 사용하는 방법**

spring boot는 데이터 베이스 초기 설정을 위해 기본적으로 `scricpt` 을 사용할 수 있다.

빈 초기화내에서 테이블생성과 동일하게 어플리케이션 시작에 초기화되는 것은 맞지만 스프링 부트는 script 파일을 병렬적으로 계산하고 있어 시간이 많이 단축될 수 잇다.

**초기 설정 방법)**

```python
spring.sql.init.mode=always  //embedded, never
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
```

**장점)**

> 애플리케이션 시작 시간 단축: 테이블 생성이 느리면 빈 생성이 지연될 수 있습니다. 초기화 로직을 별도로 실행하면 애플리케이션 시작 시간을 단축할 수 있습니다.
> 
- 스크립트를 통한 테이블 생성은 병렬처리가 가능하지만, 빈 생성은 순서대로 어려워지고 시간이 걸리기 때문에 애플 시작 시간이 늘어난다.

### 그래도 이해가 잘 안가는 점

빈 초기화에서 의존성과, 테스트시의 어려움에 대해서 잘 이해가 가지 않습니다.

> 의존성 감소: 빈 생성자에 테이블 생성 로직을 포함하면, 빈 생성 시점에 데이터베이스와의 의존성이 생깁니다. 이는 **불필요한 결합**을 초래할 수 있습니다.
> 

빈 생성은 생성 순서에 따라 순차적으로 실행되기 때문에, 데이터 베이스가 준비되지 않은 상황일 경우 예기치 못한 예외를 만든다든지의 문제가 있습니다.

하지만 데이터베이스와 테이블이 의존성을 가지는 것이 문제가 되는지 잘 이해가 되지 않습니다.

의존성이 문제가 되는 상황은, 높은 의존성으로 변경이 힘들어지는 것일텐데,클래스와 데이터 베이스는 애초에 높은 연관성을 가질 수 밖에 없는 것아닌가요???

따라서 유지 보수가 어렵다는 단점에 대해서도 이해가 잘 가지 않습니다.

> 테스트 용이성: 분리하면 각 컴포넌트를 독립적으로 테스트할 수 있습니다. 데이터베이스 초기화 로직이 빈 생성자에 있으면, 테스트 시점에 데이터베이스에 접근해야 하므로 테스트가 복잡해질 수 있습니다.
> 

그러나 레파지토리를 테스트 하기 위해서는 무조건 테이블이 필요하지 않나요? 실제로 이번 step3에서 레파지토리 관련 테스트를 위해 JDBC 빈을 주입받고 테이블을 생성했습니다. 

해당 단점은 레파지토리 로직이 필요없는 테스트의 경우에 해당되는 것인가요? 예를 들어서 가짜 객체를 이용해 컨트롤러단의 입력값을 검사하는 테스트가 있을 것 같습니다.

2024-07-08 07:03 UTC, jinseohyun1228 commented on src/main/java/gift/main/repository/ProductDao.java
> +        createProductTable();
테이블 생성에 관련해서 공부를 해보았는데 왜 강한 결합과 테스트 용이성에서 문제가 생기는 지 궁금합니다..!!

테스트용이성은 컨트롤러 입력단 테스트의 경우만을 이야기한다면 이해와 납득이 가지만, 


강한 결합이 정말로 문제가 되는 것인지는 모르겠습니다...

제가 혹시 놓친 부분이나 더 공부해야하는 부분이 있다면 말씀해주시면 감사하겠습니다..!!

로직 반영은 이 부분이 이해가 간후에 해도 될까요..??!!

2024-07-08 07:35 UTC, jinseohyun1228 commented on src/main/java/gift/main/controller/AdminController.java
> +    @GetMapping("/product/list")
반영했습니다!

2024-07-08 09:11 UTC, jinseohyun1228 commented on src/main/java/gift/main/controller/AdminController.java
> +    }
반영 하겠습니다!

2024-07-08 09:12 UTC, jinseohyun1228 commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        String password = request.getHeader("password");
반영했습니다!

2024-07-08 09:12 UTC, jinseohyun1228 commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
헉 공유 감사드립니다 감사합니다 읽어보겠습니다!

2024-07-08 09:12 UTC, jinseohyun1228 commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
필터 / 인터셉터 / AOP 의 각 적절한 타이밍에 대해서 저도 고민을 더 해보겠습니다.

2024-07-08 09:16 UTC, jinseohyun1228 commented on src/main/java/gift/main/controller/AdminController.java
> +    }
반영했습니다!

2024-07-08 17:30 UTC, hocaron commented on src/main/java/gift/main/repository/ProductDao.java
> +        createProductTable();
1. 강한 결합이 정말로 문제가 되는 것인지는 모르겠습니다...

빈이 생성될 때 데이터베이스와 연결하여 테이블을 생성해야 하기 때문에, 데이터베이스가 정상적으로 작동하지 않으면 애플리케이션이 시작되지 않거나 예외가 발생할 수 있을 것 같아요.  물론 스크립트 또한 애플리케이션이 뜨면서 동작하는 부분이지만, 옵션을 통해 이미 테이블이 만들어져있다면 테이블 생성을 시도하지 않도록 하는 옵션을 통해 제어하는데 유연성이 생길 것 같습니다!

강결합이 문제가 되는 부분에 대해서 고민해봤어요. 현재는 애플리케이션에서 DDL 을 통해 데이터베이스 스키마를 변경하고 있는 환경이어서 데이터베이스와 애플리케이션 간에 의존성이 높아질 수 밖에 없지만 저는 이런 의존성을 끊어내야한다고 생각하는데요! 그 이유는 보통 서비스에서 어플리케이션에 붙는 테이블이 20개 이상이 되는 경우에, 테이블 생성 또는 업데이트 로직이 실패하는 등의 이유로 하나의 문제가 다른 20개의 테이블에 수행되는 로직에 까지 영향을 줘서 장애(?)가 전파된다는 느낌도 있어요.

현재는 사이드 프로젝트라서 DDL 권한이 있지만, 현업에서는 DDL 권한이 없는 경우가 많아서(개발자의 실수로 인해 DB 테이블 스키마가 변경되면 절대 안 되기 때문에🥲) 스키마 스크립트를 DBA 분들께 생성요청하고, 애플리케이션에서는 테이블 생성이나 업데이트 로직없이 바로 애플리케이션 실행하는데 필요한 빈을 생성하는 작업부터 시작해요. 이런 프로세스 고려했을 때도, ProductDao 빈 생성 로직 내부 보다는 외부에서 생성했을 때 추후에 분리하기에 비교적 쉬울 것 같습니다. 클래스 내부 로직을 변경하는 것 없이, yml 파일의 옵션만 지우면 되니까요!

```
spring.sql.init.mode=always  // 주석처리
```

저는 지금 프로젝트가 요구사항대로 잘 동작하면서, 저의 코멘트가 납득이 가지 않는다면 서현님께서 꼭 반영을 하지 않으셔도 된다고 생각해요💡 편하게 생각 공유해주시면 좋을 것 같습니다😎 엄청 열심히 고민하신 티가 납니다👍

2024-07-09 07:36 UTC, jinseohyun1228 commented on src/main/java/gift/main/repository/ProductDao.java
> +        createProductTable();
아 실무에서는 DDL권한이 없는 경우와 업데이트를 위한 빌드에서 해당 문제가 생길수 있다는 것은 처음알았습니다!!

재생성하지 않는 옵션과 스크립트를 이용한 테이블 생성을 하면 의존성이 해결될 수 있을 것 같습니다.

특히 업데이트 부분에 대해서는 제가 고민하기 힘든 부분이라 많이 도움이 되었습니다 ㅎㅎ

실제 프로젝트에서는 DBA분들이 있다는 것도 처음알았구요..!! 해당 부분 이해했습니다 

스크립트로 테이블 생성하는 부분 반영했습니다!