부산대 BE_강수민 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #334
Opened 2024-07-05 07:37 UTC by wvssm

## 리뷰 받고 싶은 내용 - 2단계
1. jwt 검증에서 발생한 exception을 일반적으로 어떻게 처리하는지 궁금합니다.
저는 interceptor 쪽에서 catch하여 오류 문구를 json으로 반환했습니다.
하지만 헤더에 authorization token을 넣는 것은 프론트쪽에서 진행하기 때문에 front 쪽에 안내를 전달해야 할 것 같은데 일반적으로는 어떻게 처리하는 지 궁금합니다.

2. save나 update 동작을 수행했을 때, 성공 메시지를 전달하고자 ErrorResponse dto를 사용하는 것은 옳은 방법인지 궁금합니다. 저는 dto이름이 의도와 맞지 않다고 생각하여 저는 내부가 똑같은 message 필드를 가진 CommonResponse 클래스를 만들었습니다. 하지만 코드 중복이 일어나는 거 같아 이보다 나은 방법이 있는지 궁금합니다.

## 리뷰 받고 싶은 내용 - 3단계
1. WishService의 일부분 코드입니다. Wish 설계를 Product를 말고 ProductId를 필드로 사용했습니다. 따라서 위시리스트 조회 시, 각 위시 상품마다 productRepository를 조회하여 상품정보를 가져와야 합니다.  이러한 코드는 복잡도가 높아서 좋지 않은 것 같은데 객체 참조를 포함하도록 설계를 바꾸는 것이 좀 더 나은지 궁금합니다.

```
public List<WishResponseDto> findByUserEmail(String userEmail){
        User user = validateUser(userEmail);
        return wishRepository.findByUserId(user.getId())
                .orElseThrow(() -> new WishNotFoundException(NOT_FOUND_WISH_MESSAGE))
                .stream()
                .map(this::convertToWishDto)
                .collect(Collectors.toList());
    }

private WishResponseDto convertToWishDto(Wish wish) {
        Product product = productRepository.findById(wish.getProductId())
                .orElseThrow(() -> new ProductNotFoundException(NOT_FOUND_PRODUCT_BY_NAME_MESSAGE));
        return new WishResponseDto(
                wish.getId(),
                wish.getProductId(),
                product.getName(),
                product.getPrice(),
                product.getImageUrl(),
                wish.getQuantity()
        );
    }
```

바쁜 시간 와중에 정성스런 리뷰와 피드백 해주셔서 정말 감사합니다. 남은 하루도 좋은 하루 되세요 😄

2024-07-06 08:12 UTC, jadie0319 requested changes
2주차 미션 하시느라 고생 하셨습니다!
코멘트 드린 부분 있으니 확인 부탁드릴게요!
궁금하신점 있으시면 코멘트 달아주세요!

2024-07-06 08:12 UTC, jadie0319 commented on src/main/java/gift/controller/WishController.java
> +@RequestMapping("/wishes")
url 에 /api 추가와 클래스 이름에 Rest 를 붙이면 어떨까요?
productRestController 와 통일성을 유지하기 위해서요

2024-07-06 08:12 UTC, jadie0319 commented on README.md
>  ### 구현할 기능 목록
2단계에서 구현한 코드가 files Changed 탭에 나오지 않아 리뷰가 안되네요 ㅠ
대신 여기에 정리해서 적을게요!

UserController#registerUser()
- 메서드 응답값에 빈 토큰을 반환해주고 있어요. 꼭 해줘야 할까요? ResponseEntity.created() 메서드 사용해보면 어떨까요? 
- register 단어가 꼭 필요할까요?

2024-07-06 08:12 UTC, jadie0319 commented on src/main/java/gift/controller/WishController.java
> +    }
인터셉터를 통해 토큰 검증 잘 하셨어요!
토큰에 대한 검증은 인터셉터를 통해 했으니 컨트롤러에서 token 제거해도 돼요. email 또한 토큰이 아닌 withRequest 에 있는 email 을 사용하면 jwtUtil 에 대한 의존성도 제거 할 수 있겠네요! 인터셉터를 통해 중복 코드를 많이 제거 할 수 있고 관심사를 분리할 수 있게 되어 좋네요 :)

추가로 3단계 강의 맨 아래에 있는 HandlerMethodArgumentResolver 를 사용하면 wishService 의 validateUser 로직도 제거 할 수 있고 WishService 에서 userRepository 에 대한 의존성도 제거할 수 있을 것 같은데 어떻게 생각하시나요??

2024-07-06 08:12 UTC, jadie0319 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(WishNotFoundException.class)
Exception 별로 잘 처리하셨어요!

2024-07-06 08:12 UTC, jadie0319 commented on src/main/java/gift/repository/WishRepository.java
> +public interface WishRepository {
인터페이스 설계 좋습니다 :)

2024-07-06 08:12 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +    private final String NOT_FOUND_WISH_MESSAGE = "위시가 존재하지 않습니다.";
코드가 더 커졌을 때 모든 Exception 메시지를 여기에 선언하면 어지러울 것 같아요. 에러 메시지만 따로 저장하면 어떨까요?

2024-07-06 08:12 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +        User user = validateUser(userEmail);
validateUser 메서드가 정말로 validate(검증) 하는 기능일까요?

그리고 유저를 DB 로부터 조회하는 로직이 위시리스트를 다루는 WishService 에 있어야 할까요? UserService 에 유저 검증 메서드 구현 후 그 메서드를 호출하는건 어떨까요?

WishService 에서 직접 userRepository 에 대한 의존성을 가져야 하는지도 생각해보시면 좋을 것 같아요! :) userService 를 통해 조회하는 것은 어떨지도 고민해보시구요  궁금하신 점 있으시면 말씀해주세요~~!

2024-07-06 08:12 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +    public WishService(WishRepository wishRepository, UserRepository userRepository, ProductRepository productRepository) {
필요한 데이터를 얻기 위해 다른 도메인의 Repository 를 직접 의존하는게 맞을지도 고민해보시면 좋을 것 같아요

2024-07-06 08:12 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +        return wishRepository.findByUserId(user.getId())
예외처리, stream api 사용 GOOD ! 💯

2024-07-06 08:12 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +    private WishResponseDto convertToWishDto(Wish wish) {
메서드 명만 보면 Wish 를 WishResponseDto 로 변경하는 것처럼 보이지만 
실제론 상품을 조회하는 로직이 있어요. 분리해보면 어떨까요?

2024-07-06 10:24 UTC, jadie0319 commented
안녕하세요 수민님! 2단계 과제 정말 잘 수행하셨어요! 
조금 고민해볼만한 주제를 피드백으로 달아놓은게 있어요! 한번 고민해보시고 궁금한 점 있으시면 말씀해주세요! :)
2단계에서 드리지 못한 피드백도 함께 적어놨으니 참고해서 반영해주세요!

### 2단계 질문 1

오류 문구 json 으로 잘 반환하셨어요! 일반적으로 오류 문구는 JSON 으로 전달하는 경우가 많습니다. 

헤더에 토큰을 넣는 작업은 프론트 일수도 있고 우리가 만든 API 를 호출하는 다른 서버 일수도 있어요. 여기서는 “사용자” 라고 지칭할게요.

사용자는 API 를 호출하기 위해 필요한 것을 요청하고

API 개발자는 사용자에게 필요한 것을 제공하죠. 기본적으로 API 호출에 필요한 요청값과 호출시 받게될 응답값을 제공해야 하고, 필요하다면 토큰을 얻기 위한 방법도 제공해야 해요. 

토큰을 얻는 API를 만들어 API 문서에 적어놓거나, 보안 이슈가 없는 가까운 회사 내부 팀이라면 토큰을 직접 생성하는 방법을 알려주기도 합니다. 또는 사내 공통 라이브러리에 토큰 생성 코드를 넣어놓고, 그 라이브러리를 통해서만 토큰을 얻게 하는 경우도 있어요.


### 2단계 질문 2

save나 update 동작을 수행했을 때, 성공 메시지를 전달하고자 ErrorResponse dto를 사용하는 것은 옳은 방법인지 궁금합니다. 저는 dto이름이 의도와 맞지 않다고 생각하여 저는 내부가 똑같은 message 필드를 가진 CommonResponse 클래스를 만들었습니다. 하지만 코드 중복이 일어나는 거 같아 이보다 나은 방법이 있는지 궁금합니다.

지금 PR 버전에서는 ErrorResponse 는 exceptionHandler 에서만 사용되고 CommonResponse 클래스가 없어 어떤 질문이었는지 의도를 잘 이해 못하겠습니다 ㅠ

그런데 errorResponse 를 사용하는 부분 중에 `handleMethodArgumentNotValid` 만 List<String> 을 반환하네요. 예외가 발생했을 때의 반환값은 통일해주는게 좋아요. 사용자 입장에서는 응답에 실패했을 때 String 으로 올거라 예상하고 코드를 짜놨는데 갑자기 List 가 오면 당황할 수도 있다고 생각해요.

### 3 단계 질문 1 

정말 좋은 질문이고 다양한 영역을 공부하시면서 마주하시게 될 주제이기도 합니다. 그래서 저도 쉽게 설명하기 어려운 부분이네요. 오히려 일단 역으로 질문을 드려보고 싶어요. 이 질문만 따로 복붙해서 고민해보시고 아래 글을 봐주시는게 좋을 것 같아요.

- Wish 에 Product 객체가 있는 것과 ProductId 가 있는 것의 차이가 뭘까요?
- 왜 ProductId 를 사용하면 좋지 않다고 느끼신거에요?

Wish 가 ProductId 를 가질때와 Product 를 가질 때 상황을 상상해 봅시다.

조회 측면

Product를 사용하든 ProductId를 사용하든 repository 구현에 따라 두 테이블을 조인할수도 있고 조인 안 할수도 있어요. 사용하는데 크게 차이가 없어보여요. 

Product 객체를 사용할 때 두 테이블을 조인해서 함께 조회해야 하나 , 각자 조회해야 선택해야 하는 고민 정도가 생깁니다. 이건 성능에 대한 고민이기도 하겠네요.

```
Product 객체 사용
- wishes 테이블과 products 테이블을 조인해서 함께 조회 하거나
Wish, Product 를 각각 조회 후 Wish 에 Product 객체를 추가
- 필요한 값만 추출해서 Response 객체를 만들어 컨트롤러로 반환

ProductId 사용
- Wish, Product 를 각각 조회
- 필요한 값만 추출해서 Response 객체를 만들어 컨트롤러로 반환
```

생성이나 변경할 때를 상상해볼까요? 

```
Wish 생성

Product 객체 사용
- Wish 를 생성할 때 Product 객체가 필요 없음. id만 있으면 됨.
- Wish 와 Product 가 함께 생성될 일도 없음.

ProductId 사용
- Wish 를 생성할 때 productId 만 있으면 됨.

Wish 변경

Product 객체 사용
- Wish 를 변경할 때 Product 객체로의 접근이 허용됨
- Wish 조회 후 변경을 하는데 Product 객체로의 접근까지 허용해야 할까요?
 → 아니요. Product 의 객체까지 접근하게 된다면 Product 도 함께 변경해버릴
  가능성이 생겨요.
  그리고 이런 가능성이 문제를 유발하는 시작이 되기도 해서 조심히 사용해야 해요.

ProductId 사용
- Wish 정보를 변경하거나 productId 만 변경 가능
```

정리하자면

Product 객체를 사용할 때

- wishes, products 테이블을 조인해 한번에 조회했을 때, 객체를 사용하면 좀 더 기능 구현이 쉬울 수 있다는 장점이 있음.
- 하지만 조회 측면에서는 성능에 대한 고려를 하게 만듬
- 변경시엔 Product 객체를 탐색해 Product 의 값을 변경할 위험이 있음
- Wish 가 Product 를 의존하게 되기 때문에 의존 결합도를 높여서 Wish 의 변경을 어렵게 만들 수 있음

개인적으로 생각하기에 객체 사용이 장점도 있지만 단점들이 더 크게 와닿아서 ID 참조를 더 선호하는 편입니다. 처음 설명하는 내용이다보니 설명이 어려웠네요… 어려우시거나 궁금하신 부분 있으시면 편하게 말씀해주세요!

2024-07-07 15:04 UTC, merged

2024-07-08 05:38 UTC, wvssm commented on src/main/java/gift/controller/WishController.java
> +@RequestMapping("/wishes")
넵! 통일성을 위해서 수정하겠습니다

2024-07-08 05:43 UTC, wvssm commented on README.md
>  ### 구현할 기능 목록
빈 토큰 반환 필요가 없어보입니다. ResponseEntity.created()라고 수정하겠습니다!
register라는 단어는 미션에서 api path가 주어져서 그대로 구현했습니다
register라는 단어가 꼭 필요하지 않다고 생각합니다!

2024-07-08 15:25 UTC, wvssm commented on src/main/java/gift/controller/WishController.java
> +    }
HandlerMethodArgumentResolver를 써본 경험이 없지만 한 번 적용해보겠습니다!
토큰에 대한 검증 코드도 controller에서 삭제하겠습니다!

2024-07-08 15:26 UTC, wvssm commented on src/main/java/gift/service/WishService.java
> +    private final String NOT_FOUND_WISH_MESSAGE = "위시가 존재하지 않습니다.";
Exception Message가 많아지면 말씀대로 코드가 깔끔하지 않을 것 같습니다!
따로 저장하도록 하겠습니다!

2024-07-08 15:28 UTC, wvssm commented on src/main/java/gift/service/WishService.java
> +    private WishResponseDto convertToWishDto(Wish wish) {
함수가 하나의 기능만 할 수 있도록 분리해보겠습니다!

2024-07-08 16:26 UTC, wvssm commented on src/main/java/gift/service/WishService.java
> +        User user = validateUser(userEmail);
## validateUser
validateUser가 정말 검증을 하는 기능은 아닌 것 같습니다.
데이터베이스에서 사용자를 조회하는 동작에 가깝기 때문에 findUserByEmail이 더 적절한 이름인 것 같습니다! 해당 이름으로 수정하겠습니다.

## WishService와 userRepository의 관계
추가로 조사해본 결과 WishService에서 직접 userRepository에 대한 의존성을 가지는 것은 좋지 않은 것 같습니다.

먼저 각 클래스는 하나의 책임만 가져야한다는 단일 책임 원칙에 어긋나기 때문입니다.  
또한 WishService가 사용자 관련 로직을 처리할 필요가 없을뿐더러, 관심사가 분리되어야 하기 때문입니다.

현재 HandlerMethodArgumentResolver에서 UserService를 통해 사용자를 조회하도록 수정하였습니다. 
Service는 Repository만 주입받을 수 있다는 잘못된 생각을 가지고 있었는데 새롭게 생각할 수 있는 계기가 되었습니다. 감사합니다😄

2024-07-08 16:34 UTC, wvssm commented on src/main/java/gift/service/WishService.java
> +    public WishService(WishRepository wishRepository, UserRepository userRepository, ProductRepository productRepository) {
다른 도메인의 Repository를 직접 의존하는건 좋은 선택이 아닌 것 같습니다.

서비스가 여러 도메인의 레포지토리에 직접 접근하면 서비스의 책임이 명확하지 않게 되고, 하나의 서비스가 너무 많은 역할을 가지기 때문입니다. 또한 도메인 내의 레포지토리 변경이 해당 도메인 뿐만 아니라 그 레포지토리를 사용하는 다른 서비스에도 영향을 미칠 수 있기 때문에 변경 관리가 어려워지기 때문입니다.

서비스를 통해 간접적으로 데이터를 들고오는게 좀 더 나은 방법인 것 같습니다!