전남대 BE_안재영_2주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #335
Opened 2024-07-05 07:41 UTC by ajy9851

저 빼고 모든 그룹원들이 JWT를 사용해서 저도 적용시켜보려고 노력했습니다.
하하 정말 스스로 부족함을 많이 느꼈던 한 주입니다. 좋은 주말 보내시고 하루 마무리 잘 하세요 코치님!

2024-07-06 09:23 UTC, gunom requested changes
안녕하세요 재영님! 3단계 수고하셨습니다. 고민이 많이 보인 코드였네요!
몇가지 리뷰 남겼으니 반영해주시고 혹시 궁금하신 부분 있으면 리뷰로 남겨주세요~

2024-07-06 09:23 UTC, gunom commented on src/main/java/gift/model/User.java
> +    private String email;
user와 wishList의 테이블을 만든다면, 1주차 과제의 product와 같이 id를 넣어주면 좋을 것 같습니다!
데이터는 식별자가 필요하니까요. email만으로도 식별이 불가능한 것은 아니지만, DB들의 특성 상 index를 위해선 id를 가지고 있으면 좋습니다!

2024-07-06 09:23 UTC, gunom commented on src/main/java/gift/model/WishList.java
> +    private String userEmail;
wishList도 고유한 id를 가지면 좋을 것 같아요. 현재는 (userEmail+productId)로 복합 키로 식별되고 있는데 id를 추가하면 명확한 식별자가 생겨서 데이터 관점에서 좋을 것 같네요

2024-07-06 09:23 UTC, gunom commented on src/main/java/gift/service/UserService.java
> +    public User findByToken(String token) {
이부분도 일전에 말씀드린 Product와 같이 Dto로 바꿔서 반환하면 좋을 것 같아요! entity가 클라이언트까지 노출될 필요는 없을 것 같습니다.

2024-07-06 09:23 UTC, gunom commented on src/main/java/gift/config/LoginMemberArgumentResolver.java
> +        String token = webRequest.getHeader("Authorization").substring(7);
만약 요청에 Authorization 헤더가 존재하지 않는다면 예외 처리가 어떻게 될까요?

2024-07-06 09:23 UTC, gunom commented on src/main/java/gift/service/UserService.java
> +            .orElseThrow(() -> new IllegalArgumentException("유효하지 않은 토큰입니다."));
UserService에서 email이 존재하지 않는다면 유효하지 않는 토큰이라고 판단하는게 맞을까요? 유효하지 않는 토큰인지 판단 여부는 UserService의 책임이 아닌 거 같습니다!

2024-07-06 09:23 UTC, gunom commented on src/main/java/gift/service/WishListService.java
> +        WishList wishList = wishListRepository.findByUserEmailAndProductId(userRequestDTO.getEmail(), productId)
이 부분도 wishList가 id를 들고 있는다면 parameter를 불필요하게 많이 받을 필요 없겠죠?

2024-07-06 09:23 UTC, gunom commented on src/main/java/gift/config/LoginMemberArgumentResolver.java
> +public class LoginMemberArgumentResolver implements HandlerMethodArgumentResolver {
Resolver로 구현해주셨군요! Resolver 사용좋습니다! 시간이 되신다면 interceptor와의 차이도 살펴보시면 좋을 거 같아요!

2024-07-07 15:01 UTC, gunom commented
@ajy9851  충돌 해결해주시면 감사하겠습니다~

2024-07-09 05:41 UTC, ajy9851 commented
지적해주신 부분 고치고 충돌 해결했습니다! 감사합니다:)

2024-07-15 11:41 UTC, gunom approved these changes

2024-07-15 11:41 UTC, merged