경북대 BE_한영진 2주차 과제 (2단계, 3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #336
Opened 2024-07-05 07:43 UTC by yjhannn

### Step1 관련 피드백 반영
- README 파일에 체크하면서 기능 개발을 했습니다
- ProductRestController의 else를 삭제했습니다
- 예외 처리 로직에서 Map이 아닌 List로 구현하여 오류 조건 동시에 만족할 때 모든 오류 내역이 뜰 수 있도록 수정했습니다. 멘토님이 잘 설명해주셔서 무슨 말인지 바로 이해한 것 같습니다!
- 그리고 컨트롤러 분리는 주말에 시간내어 한번 해보겠습니다. 다음 주차 과제에 반영하여 올리겠습니다!!

### Step2 관련 질문
- 우선 Jwt를 사용해본적이 없어 엄청 구글링도 하고 여기 저기 많이 찾아보면서 했는데 이런 식의 흐름으로 진행하면 되는지 궁금합니다!
- 그리고 UserRepository를 구현하였는데 이거도 인터페이스가 있으면 좋을지 궁금합니다!
- 예외 처리 로직(회원 가입 및 로그인 관련)을  따로 분리해서 구현하는게 깔끔하겠죠?

### Step3
- 위시리스트에 상품을 추가, 삭제 , 수량 변경을 구현하고자 했습니다
- 인텔리제이의 generated-requested.http를 이용하여 Http의 요청, 응답을 테스트했는데 잘 작동하지 않았습니다.. 혹시 왜 이런건지 알 수 있을까요?

2024-07-06 11:19 UTC, jadie0319 approved these changes
2주차 미션 진행하시느라 고생하셨습니다!
코멘트 남겨놨으니 확인 후 반영해주세요!

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/annotation/LoginMember.java
> +public @interface LoginMember {
어노테이션 생성 좋습니다! 👍

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/resolver/LoginMemberArgumentResolver.java
> +public class LoginMemberArgumentResolver implements HandlerMethodArgumentResolver {
HandlerMethodArgumentResolver 구현 좋습니다!
token 인증 로직은 여기서 다 해결할 수 있겠네요!

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/controller/AuthController.java
> +        userService.save(user);
User 생성 로직을 UserService 에서 하면 어떨까요?
컨트롤러는 서비스로부터 받은 데이터를 사용자에게 반환해주는 역할만 하면 됩니다.
그리고 set 메서드 사용보단 생성자 메서드를 사용해보시면 어떨까요?

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/controller/AuthController.java
> +        String jwt = jwtUtil.generateToken(user.getEmail());
미사용 로직은 삭제해주시는게 좋습니다 :)

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/controller/AuthController.java
> +    public ResponseEntity<?> createToken(@RequestBody AuthenticationRequest authenticationRequest) {
현재 메서드 명은 토큰을 만드는 역할만 하는 메서드를 나타내는 것 같아요. 다른 이름으로 변경해보면 어떨까요?

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/controller/AuthController.java
> +        }
1.user 검증 로직은 userService 에서 진행하면 어떨까요?
user 의 패스워드가 틀릴시 예외를 발생시키고 ExceptionHandler 에서 처리할 수 있을 것 같아요 :)

2.user.getPassword() 하여 패스워드를 조회하고 api 요청으로 받은 password 를 비교하고 있어요. user.validatePassword(authenticationRequest.getPassword()) 이런 식으로 user 에게 위임하는 코드는 어떠신가요?

3.401 을 직접 코딩해놓으면 오타가 발생할 가능성이 있을 것 같아요.
HttpStatus.UNAUTHORIZED 와 같은 클래스를 사용하면 어떨까요?

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/controller/ProductRestController.java
>              return new ResponseEntity<>(product, HttpStatus.OK);
서비스에서 상품이 없을 경우 예외를 발생시키고 ExceptionHandler 를 통해 처리하는건 어떻게 생각하시나요?
컨트롤러에서 상품의 존재 유무를 판단하지 않아도 될 것 같아요

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/controller/ProductRestController.java
>          if (product != null) {
{ 괄호 때문에 컴파일 에러가 나서 프로그램 실행이 안되네요...ㅠ

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/controller/ProductRestController.java
상품 생성 API 의 요청객체도 dto 를 만들수 있을것 같아요!

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/domain/LoginMember.java
> +public class LoginMember {
Member 와 User 간 어떤 차이가 있는지 궁금해요 :)

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/domain/LoginMember.java
> +public class LoginMember {
LoginMember 어노테이션과 클래스 이름이 같아서
다른 클래스에서 이 클래스를 사용시 gift.domain 이 붙어서 가독성이 떨어져요 ㅠ
다른 이름으로 변경해보면 어떨까요?

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/controller/WishListController.java
> +public class WishListController {
@LoginMember 통해 회원 인증 로직을 잘 분리하셨네요 💯 
JwtUtil 의존성은 삭제해도 될 것 같아요~!

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/domain/User.java
> +    @NotBlank(message = "이메일은 필수로 입력하셔야 합니다.")
유효성 검증 로직 좋습니다 :)

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/controller/AuthController.java
> +    public ResponseEntity registerUser(@RequestBody RegisterRequest request) {
회원 가입 기능이 정상적으로 동작하지 않습니다.
토큰 생성 로직을 확인해보셔야 하고
userRepository 의 update 문 파라미터를 추가해줘야 합니다.

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/controller/AuthController.java
> +    public ResponseEntity<?> createToken(@RequestBody AuthenticationRequest authenticationRequest) {
DTO 사용 좋습니다 !

2024-07-06 11:19 UTC, jadie0319 commented on src/main/java/gift/filter/JwtFilter.java
인증 로직을 HandlerArgumentResolver 에 구현 하셨으니 이건 삭제하셔도 될 것 같네요 :)

2024-07-06 11:21 UTC, jadie0319 requested changes
2주차 미션하시느라 고생하셨습니다!
몇가지 코멘트 드렸으니 확인 부탁드려요!
질문 주셨던 것은 코멘트에 남겨놓겠습니다!

2024-07-06 11:40 UTC, jadie0319 commented
안녕하세요 영진님!

2주차 미션하시느라 고생 하셨습니다. 몇가지 코멘트 남겨놨으니 확인 부탁드려요! 질문주셨던 것 답변 드리겠습니다.

2주차 질문

### 우선 Jwt를 사용해본적이 없어 엄청 구글링도 하고 여기 저기 많이 찾아보면서 했는데 이런 식의 흐름으로 진행하면 되는지 궁금합니다!

넵 JWT 토큰 사용 잘 사용하셨습니다.  다만 토큰을 생성하는 로직에 문제가 있어 잘 생성이 안되더라고요. 기존 `jsonwebtoken` 의존성 삭제하고 아래 의존성 추가 후 기존 토큰 생성 로직을 수정하니 잘 됐습니다!

```
의존성 추가
implementation 'javax.xml.bind:jaxb-api:2.3.1'
implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.1'
implementation 'io.jsonwebtoken:jjwt:0.9.1'

코드 변경
SignatureAlgorithm.HS512
```

회원 가입 로직이 잘 안되는 이유는 코멘트로 남겨놨으니 확인 부탁드려요!

### 그리고 UserRepository를 구현하였는데 이거도 인터페이스가 있으면 좋을지 궁금합니다!

보통 Respository 는 인터페이스를 만드는 경우가 많습니다. DB 에 연결하고 쿼리를 실행하는 로직을 인터페이스로 감추기 위해서 입니다. 

서비스 에서는 인터페이스에만 의존하면 되고 인터페이스를 통해서 원하는 데이터를 받기만 하면 되지 실제 DB 실행로직에 대해 알 필요 없습니다.

 그리고 만약 DB 가 바뀌거나 DB 실행 로직이 바뀌는 일이 발생했을 때, 서비스가 구현체를 직접 의존하고 있으면 구현체의 변경이 서비스 까지도 영향이 가게 됩니다. 하지만 인터페이스를 사용하면 구현체의 변경이 서비스 까지 영향이 가지 않게 됩니다!

이러한 이유로 보통 Repository 인터페이스를 만들게 됩니다.

### 예외 처리 로직(회원 가입 및 로그인 관련)을 따로 분리해서 구현하는게 깔끔하겠죠?

따로 분리해서 구현하는게 좋을 것 같아요!

로그인 메서드에서 회원의 비밀번호가 틀렸을 경우를 예로 들어 볼게요.

회원의 비밀번호가 틀리면 예외를 발생 시키고, 그 예외는 GlobalExceptionHandler 에서 처리하는 식으로 구현해보시면 될 것 같아요.

3주차 질문

### 인텔리제이의 generated-requested.http를 이용하여 Http의 요청, 응답을 테스트했는데 잘 작동하지 않았습니다.. 혹시 왜 이런건지 알 수 있을까요?

혹시 어떤 에러 메시지가 나왔는지 알 수 있을까요? 아니면 어떤식으로 실행하셨는지 알 수 있을까요?

저는 영진님 프로젝트에서 잘 실행 됐습니다. 어플리케이션을 실행가능한 상태로 바꾸고요 ㅎ 처음 영진님 프로젝트를 받았을 땐 프로젝트 실행이 안되기 때문에 http 테스트도 안됐을 겁니다.

- 어플리케이션 실행
- 실행하려는 API 왼쪽 스프링 마크 클릭
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/10750614/87fe42fd-71ac-4d90-8714-d1e36b7b6c28)
- http 테스트가 생김
- 녹색화살표 클릭하니 잘 실행됐습니다
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/10750614/61cc14b6-bf4d-445d-88d6-b4777181b180)

2024-07-06 12:50 UTC, jadie0319 commented on src/main/java/gift/controller/AuthController.java
> +    @PostMapping("/register")
register 라는 url 이 꼭 포함되어야 할까요?

2024-07-07 05:30 UTC, yjhannn commented
안녕하세요 멘토님! 우선 꼼꼼하게 리뷰해주셔서 감사합니다~~!! 피드백 내용 바탕으로 코드 내용을 변경해보았습니다
1. register 관련 오류 수정을 했습니다.
2. 불필요한 컨트롤러 내 코드를 서비스로 옮겼습니다.
3. 예외처리를 컨트롤러가 아닌 서비스에서 하도록 변경했습니다!
다시 리뷰 요청 드립니다~!!

2024-07-07 10:17 UTC, jadie0319 approved these changes
2주차 미션 하시느라 고생 많으셨습니다!
몇가지 코멘트 남겼습니다. 확인해보시고 3주차 미션때 반영해주세요!
3주차도 화이팅 해봅시다! 
궁금하신 부분이나 얘기하고 싶은게 있으시다면 편하게 DM 주세요!

2024-07-07 10:17 UTC, jadie0319 commented on src/main/java/gift/controller/AuthController.java
> +        }
여기서 catch 하면 ExceptionHandler 까지 얘외가 전달 안될 것 같아요.
controller 의 try catch 문을 제거해도 되지 않을까요?

2024-07-07 10:17 UTC, jadie0319 commented on src/main/java/gift/controller/AuthController.java
> +    }
컨트롤러 코드가 훨씬 깔끔해졌네요! 👍

2024-07-07 10:17 UTC, jadie0319 commented on src/main/java/gift/config/WebConfig.java
> +    public WebConfig(LoginMemberArgumentResolver loginMemberArgumentResolver) {
ArgumentResolver 사용 좋습니다 👍

2024-07-07 10:17 UTC, jadie0319 commented on src/main/java/gift/controller/AuthController.java
> +    public ResponseEntity<?> loginUser(@RequestBody AuthenticationRequest authenticationRequest) {
dto 사용 좋습니다! 메서드 명도 뭘 하는지 한눈에 알수 있어 좋네요!

2024-07-07 10:17 UTC, jadie0319 commented on src/main/java/gift/controller/WishListController.java
> +@RequestMapping("/api/wish")
api 에서 resource 를 지칭할땐 보통 복수를 많이 사용합니다

2024-07-07 10:17 UTC, merged