부산대 BE_진서현_2주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #338
Opened 2024-07-05 07:44 UTC by jinseohyun1228

1. 화면은 구현하지 않고, 과제의 요구사항만 구현했습니다.
2. 위시리스트의 기능은 모든 role에서 가능할 것 같아 별도의 로직을 두지 않고 세션에서 회원정보만 가져왔습니다.
3. 위시리스트의 엔티티에 유저 id, 상품 id만 넣어놨는데, 실제로 구현을 하다보니, 위시리스트 목록에서 상품정보가 뜨지 않는다는 불편점이 잇었습니다.
      -  위시리스트프로덕트엔티티에 기본적인 상품 정보를 넣는게 좋을까요? 위시리스트 목록 구현시 다른 DB에 접근할 필요가없어 간단할 것 같습니다. 그러나 가격의 경우에 특히 변동이 작을텐데, 객체의 안정성이 깨질 것 같아 위험할 것 같습니다.
      - 프로덕트의 id를 가지고 프로덕트Dao에서 처리하는게 좋을까요?
      
  4. 구현중에 생긴 궁금증인데 jwt에 ID를 넣어도 될까요?
  jwt는 열어볼 수 있으니까 password는 넣지 않았습니다.  그리고 세션리스로 토큰을 사용시 강점 중 하나가 DB 접근이 줄어 성능향상이라 생각이 되어 id를 포함했습니다.  id 값을 파라미터로 넘겨서 사용하는 곳이 많지만, 권한 인증을 인터셉터에서 하니까 id를 아는건 보안상 괜찮을 것 같다고 판단했습니다. 괜찮을까요?

2024-07-06 15:43 UTC, hocaron requested changes
서현님, 안녕하세요! 3단계를 함께 진행할 호선우에요.

클라이언트가 보낸 토큰을 복호화하여 사용하는 부분까지 구현이 잘 되어있네요👍

함께 작업하면서 반영하면 좋을 것 같은 코멘트를 남겼는데, 확인 부탁드립니다🙇‍♀️

2024-07-06 15:43 UTC, hocaron commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        if (authorization == null || !authorization.startsWith("Bearer ")) {
문자열이라 다른 분이 작업하다가 틀릴 가능성이 있어서 HttpHeaders.AUTHORIZATION 를 사용해도 좋을 것 같아요😎

Bearer 도 상수화하면 좋을 것 같아요!

2024-07-06 15:43 UTC, hocaron commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        UserVo sessionUser = new UserVo(
UserVo 사용 좋습니다👍

2024-07-06 15:43 UTC, hocaron commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        session.setAttribute("user",sessionUser);
user 가 다른 곳에서도 많이 사용되고 있네요😀 해당 값을 상수화하여 코드의 유지보수성을 높일 수 있을 것 같아요!

2024-07-06 15:43 UTC, hocaron commented on src/main/java/gift/main/controller/WishProductController.java
> +        UserVo seesionUser = (UserVo) session.getAttribute("user");
해당 로직이 반복되어서 사용하고 있네요😎

어떻게 반복되는 로직을 한곳에서 관리하도록 하기위해 어떤 방법을 사용할 수 있을까요?!

2024-07-06 15:43 UTC, hocaron commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        String email = request.getHeader("email");
헤더에 이메일이 필드가 존재하는 이유가 궁금해요💭

2024-07-06 15:43 UTC, hocaron commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +            throw new TokenException("헤더에 이메일,비밀번호,토큰을 넣어주세요.");
현재 메시지와 실제 validation 하는 필드가 상이한 부분이 있어요. 에러 메시지 변경이 되면 좋을 것 같아요👍

2024-07-06 15:44 UTC, hocaron commented
서현님 [2단계](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/332) 에서 반영이 필요하다고 생각되는 부분 반영 부탁드릴게요. 그 과정에서 고민되는 부분 공유주시면 같이 고민해볼 수 있을 것 같아요😀

3단계도 화이팅입니다💪💪💪

2024-07-06 16:04 UTC, hocaron commented
1. 화면은 구현하지 않고, 과제의 요구사항만 구현했습니다.
REST API 구현이 되어있어서 해당 구현사항으로 확인하였습니다👍

2. 위시리스트프로덕트엔티티에 기본적인 상품 정보를 넣는게 좋을까요? 위시리스트 목록 구현시 다른 DB에 접근할 필요가없어 간단할 것 같습니다. 그러나 가격의 경우에 특히 변동이 작을텐데, 객체의 안정성이 깨질 것 같아 위험할 것 같습니다.
프로덕트의 id를 가지고 프로덕트Dao에서 처리하는게 좋을까요?

좋은 고민입니다👍 다른 도메인의 데이터이기 때문에 비정규화하여 상품 정보를 위시리스트에서 관리하여 DB 접근을 줄일 수 있지만, 해당 데이터가 불변값이 아니기 때문에 고민이 된다고 이해했어요! 

트레이드 오프가 있을 것 같아요. 지금처럼 정규화가 된 상태에서는 JOIN 또는 추가적인 쿼리가 발생하지만 제일 최신의 상품 데이터를 제공할 수 있고, 비정규화가 되면 DB 성능은 전자보다 좋지만 상품의 데이터는 제일 최신의 데이터가 아닐 가능성이 생기니까요. 

위시 리스트에 담긴 상품의 가격 데이터는 변동도 있고 또한 고객에게 조회 당시에 정확한 가격을 알려주어야 하는게 더 우선되어야 한다고 생각하는데, 서현님은 어떻게 생각하시는지 궁금해요!

3. 구현중에 생긴 궁금증인데 jwt에 ID를 넣어도 될까요?
jwt는 열어볼 수 있으니까 password는 넣지 않았습니다. 그리고 세션리스로 토큰을 사용시 강점 중 하나가 DB 접근이 줄어 성능향상이라 생각이 되어 id를 포함했습니다. id 값을 파라미터로 넘겨서 사용하는 곳이 많지만, 권한 인증을 인터셉터에서 하니까 id를 아는건 보안상 괜찮을 것 같다고 판단했습니다. 괜찮을까요?

연속적으로 증가하는 ID 값을 토큰 페이로드에 추가하는 경우에 이슈가 생길 수 있는 부분은 다음과 같아요.

	1.	사용자 정보 추출: 대량의 사용자 데이터 수집: 악의적인 사용자가 연속된 ID를 이용해 시스템에서 대량의 사용자 데이터를 수집할 수 있습니다. 예를 들어, /user/1, /user/2, /user/3 등과 같이 연속된 ID로 API 요청을 보내면, 많은 사용자의 프로필 정보, 활동 내역 등을 추출할 수 있습니다.
	2.	자동화된 공격: 스크립트 공격: 공격자는 스크립트를 작성하여 연속된 ID를 사용해 자동으로 시스템의 사용자 데이터를 수집하거나, 특정 동작을 수행하는 요청을 보낼 수 있습니다. 이는 시스템 자원을 소모시키고, 서비스 거부(DoS) 공격으로 이어질 수 있습니다.
	3.	프라이버시 침해: 특정 사용자 타겟팅: 특정 사용자를 타겟으로 삼아 연속된 ID를 사용해 그 사람의 활동 내역이나 개인정보를 집중적으로 탐색할 수 있습니다. 예를 들어, /user/123이 특정 사용자를 나타낸다면, 그 사용자의 모든 활동을 추적할 수 있습니다.
	4.	권한 오남용: 수정 및 삭제 권한 남용: 만약 시스템이 ID를 통해 데이터 수정이나 삭제 권한을 부여한다면, 연속된 ID를 사용해 다른 사용자의 데이터를 수정하거나 삭제하는 공격이 가능합니다. 예를 들어, /user/123/delete와 같은 요청을 연속된 ID에 대해 시도할 수 있습니다.
	5.	보안 취약점 악용: 예측 가능한 취약점 발견: 공격자가 연속된 ID를 통해 시스템의 보안 취약점을 발견하고 이를 악용할 수 있습니다. 예를 들어, 특정 ID 범위 내에서만 발생하는 취약점을 찾아내고 이를 대량으로 악용할 수 있습니다.

하지만 현재 토큰없이 접근하여 사용자 정보를 확인하는 API 가 열려있지 않아 위의 이슈는 해당되지 않을 것 같아요😀

만약 토큰없이 접근가능한 API 가 존재해야한다면 ID 난수화(UUID), 추가 인증 수단을 제공함으로써 보안을 강화할 수 있을 것 같네요!
서현님은 어떻게 생각하실까요?!

2024-07-07 00:49 UTC, jinseohyun1228 commented
제가 에러 메시지를 enum으로 구현후 변경해습니다

처음에는 왜 enum을 추천해주시는지 어려었는데, 제가 잘못생각했다는 것을 알게되었습니다.

(내가 생각한 것)
이메일을 잘못 적용했을때 이메일에러메시지 enum
public enum 이메일 {
	에러코드("401"),
	에러메시지("이메일이 틀렸습니다.")
}

--이런식으로 enum 클래스 엄청 많이 두기--

(실제)
public enum 에러코드 {
	잘못된_이메일("상태코드","에러메시지")
	잘못된_상품명("상태코드","에러메시지")
	...
}
바로 에러메시지 자체를 하나의 객체화하기 위해서다.
(enum은 상수가 아니다. 하나의 객체다. (실제로 힙메모리에 저장된다.)
Enum의 장점
타입 비교가 가능헤 IDE의 도움을 받을 수 있다.

개발자의 실수로 인한 다른 값이 동일하게 처리될 확률을 줄여준다.

한달의 첫번째날 과 일주일의 첫번째 날을 동일하게 판단하는 경우

리팩토링 변경 범위가 최소화된다.

Enum으로 에러메시지를 작성한다면!
에러 메시지를 한 곳에서 수정이 가능하다.

객체 타입이기 때문에 좀 더 많은 IDE의 지원을 받을 수 있다.

현재 내가 에러 메시지를 보고 찾아가려면…^^ 검색해서 가야한다는 치명적인 단점;;ㅋㅋ

enum은 객체&싱글턴으로 간단하고 안전하게 동일한지 검사할 수 있다.

만약 내가 특정 상황에서 반환하는 에러메시지가 A인지 검사하고 싶다면?

<문자열로 직접 메시지를 넣은 경우>
- 상황을 만든다.
- 에러메시지를 구현한 곳에 찾아..찾아..찾아..가서 복사해서 직접 검사
-> 오타 대마왕인 나에게는 실제로는 잘 동작하지만, 에러 검사시 틀린 값을 내는 등의 불안요소가 커진다.

<enum 으로 에러메시지로 구현한 경우>
- 상황을 만든다.
- enum클래스.발생객체 == 로 검사하면 된다.
결국 관리가 편한 상황을 만들어준다.

이후 변경을 적용하고 테스트 코드를 작성해봤습니다.
테스트 코드를 enum을 활용해서 하는 방향도 생각해보겠습니다!

2024-07-07 07:00 UTC, hocaron commented
> 제가 에러 메시지를 enum으로 구현후 변경해습니다
> 
> 처음에는 왜 enum을 추천해주시는지 어려었는데, 제가 잘못생각했다는 것을 알게되었습니다.
> 
> (내가 생각한 것) 이메일을 잘못 적용했을때 이메일에러메시지 enum public enum 이메일 { 에러코드("401"), 에러메시지("이메일이 틀렸습니다.") }
> 
> --이런식으로 enum 클래스 엄청 많이 두기--
> 
> (실제) public enum 에러코드 { 잘못된_이메일("상태코드","에러메시지") 잘못된_상품명("상태코드","에러메시지") ... } 바로 에러메시지 자체를 하나의 객체화하기 위해서다. (enum은 상수가 아니다. 하나의 객체다. (실제로 힙메모리에 저장된다.) Enum의 장점 타입 비교가 가능헤 IDE의 도움을 받을 수 있다.
> 
> 개발자의 실수로 인한 다른 값이 동일하게 처리될 확률을 줄여준다.
> 
> 한달의 첫번째날 과 일주일의 첫번째 날을 동일하게 판단하는 경우
> 
> 리팩토링 변경 범위가 최소화된다.
> 
> Enum으로 에러메시지를 작성한다면! 에러 메시지를 한 곳에서 수정이 가능하다.
> 
> 객체 타입이기 때문에 좀 더 많은 IDE의 지원을 받을 수 있다.
> 
> 현재 내가 에러 메시지를 보고 찾아가려면…^^ 검색해서 가야한다는 치명적인 단점;;ㅋㅋ
> 
> enum은 객체&싱글턴으로 간단하고 안전하게 동일한지 검사할 수 있다.
> 
> 만약 내가 특정 상황에서 반환하는 에러메시지가 A인지 검사하고 싶다면?
> 
> <문자열로 직접 메시지를 넣은 경우>
> 
> * 상황을 만든다.
> * 에러메시지를 구현한 곳에 찾아..찾아..찾아..가서 복사해서 직접 검사
>   -> 오타 대마왕인 나에게는 실제로는 잘 동작하지만, 에러 검사시 틀린 값을 내는 등의 불안요소가 커진다.
> 
> <enum 으로 에러메시지로 구현한 경우>
> 
> * 상황을 만든다.
> * enum클래스.발생객체 == 로 검사하면 된다.
>   결국 관리가 편한 상황을 만들어준다.
> 
> 이후 변경을 적용하고 테스트 코드를 작성해봤습니다. 테스트 코드를 enum을 활용해서 하는 방향도 생각해보겠습니다!

저도 서현님께서 공유주신 부분과 동일한 이유로 enum 사용이 더 용이하다고 생각하고 있습니다👍👍👍
고민 엄청 깊게 해주셨군요😎

2024-07-08 09:17 UTC, jinseohyun1228 commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +            throw new TokenException("헤더에 이메일,비밀번호,토큰을 넣어주세요.");
반영했습니다!

2024-07-08 09:17 UTC, jinseohyun1228 commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        if (authorization == null || !authorization.startsWith("Bearer ")) {
반영했습니다!

2024-07-08 09:17 UTC, jinseohyun1228 commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        UserVo sessionUser = new UserVo(
감사합니다!

2024-07-08 09:18 UTC, jinseohyun1228 commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        session.setAttribute("user",sessionUser);
여기에서도 enum을 쓸 수 있을 것 같습니다 enum으로 반영하겠습니다!

2024-07-08 09:19 UTC, jinseohyun1228 commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        String email = request.getHeader("email");
jwt 동작 원리를 오해해서 넣어놨던 것 같습니다! 필요없는 부분이라 생각되어 삭제하였습니다!

2024-07-08 10:00 UTC, jinseohyun1228 commented on src/main/java/gift/main/interceptor/AuthInterceptor.java
> +        session.setAttribute("user",sessionUser);
반영하였습니다!

2024-07-09 07:14 UTC, jinseohyun1228 commented on src/main/java/gift/main/controller/WishProductController.java
> +        UserVo seesionUser = (UserVo) session.getAttribute("user");
이 부분 고민하다가 `Argument Resolver` & `Annotation`을 사용했습니다.

첫번째 . 기존 `AuthUtil`을 `JwtUtil`로 이름을 바꾸고  `AuthUtil`에서 스태틱 메서드로 선언해서 사용
이렇게 변경을 해도 wishlistController에서 거의 모든 메서드에서 해당 호출을 해야해서 중복로직이 많이 개선이 되는 것 같지 않다고 느꼈습니다.

따라서 @postconstruct 처럼 뭔가 어노테이션으로 주입해줄 수 있는게 있을 것 같고 관련 자료를 찾아보다가 
Resolver가 있다는 것을 알게되어 적용하였습니다!!

현재는 SessionUserArgumentResolver & @SessionUser 조합으로 세션에서 user객체를 꺼내 주입받는 형식으로 사용하고 있습니다!

2024-07-09 07:17 UTC, jinseohyun1228 commented
> 2. 위시리스트프로덕트엔티티에 기본적인 상품 정보를 넣는게 좋을까요? 위시리스트 목록 구현시 다른 DB에 접근할 필요가없어 간단할 것 같습니다. 그러나 가격의 경우에 특히 변동이 작을텐데, 객체의 안정성이 깨질 것 같아 위험할 것 같습니다.
>    프로덕트의 id를 가지고 프로덕트Dao에서 처리하는게 좋을까요?
> 
> 좋은 고민입니다👍 다른 도메인의 데이터이기 때문에 비정규화하여 상품 정보를 위시리스트에서 관리하여 DB 접근을 줄일 수 있지만, 해당 데이터가 불변값이 아니기 때문에 고민이 된다고 이해했어요!
> 
> 두가지 방식에 트레이드 오프가 있을 것 같아요. 지금처럼 정규화가 된 상태에서는 JOIN 또는 추가적인 쿼리가 발생하지만 제일 최신의 상품 데이터를 제공할 수 있고, 비정규화가 되면 DB 성능은 전자보다 좋지만 상품의 데이터는 제일 최신의 데이터가 아닐 가능성이 생기니까요.
> 
> 위시 리스트에 담긴 상품의 가격 데이터는 변동도 있고 또한 고객에게 조회 당시에 정확한 가격을 알려주어야 하는게 더 우선되어야 한다고 생각하는데, 서현님은 어떻게 생각하시는지 궁금해요!
> 
> [이 부분은 지금 필요없는 부분입니다😀 읽어보지 않으셔도 좋아요.] 만약 성능 최적화가 필요하여 비정규화가 필요하다면 카트카 같은 이벤트 스트리밍 플랫폼을 활용하여 상품 데이터 변경 시에 위시리스트 내에 있는 상품 데이터에도 반영이 되도록 처리할 수 있을 것 같아요.

저도 정확한 가격이 훨씬 중요할 것 같다는 생각이 들었습니다!
카트카에 대해서도 여유가 날때 공부해보도록 하겠습니다 ㅎㅎ 

이런 고민사항이 있을때 어떤 것이 더 중요할지 따져보고 결정하면 좋을 것 같다는 생각이 들었습니다!

2024-07-09 07:22 UTC, jinseohyun1228 commented
> 3. 구현중에 생긴 궁금증인데 jwt에 ID를 넣어도 될까요?
>    jwt는 열어볼 수 있으니까 password는 넣지 않았습니다. 그리고 세션리스로 토큰을 사용시 강점 중 하나가 DB 접근이 줄어 성능향상이라 생각이 되어 id를 포함했습니다. id 값을 파라미터로 넘겨서 사용하는 곳이 많지만, 권한 인증을 인터셉터에서 하니까 id를 아는건 보안상 괜찮을 것 같다고 판단했습니다. 괜찮을까요?
> 
> 연속적으로 증가하는 ID 값을 토큰 페이로드에 추가하는 경우에 이슈가 생길 수 있는 부분은 다음과 같아요.
> 
> ```
> 1.	사용자 정보 추출: 대량의 사용자 데이터 수집: 악의적인 사용자가 연속된 ID를 이용해 시스템에서 대량의 사용자 데이터를 수집할 수 있습니다. 예를 들어, /user/1, /user/2, /user/3 등과 같이 연속된 ID로 API 요청을 보내면, 많은 사용자의 프로필 정보, 활동 내역 등을 추출할 수 있습니다.
> 2.	자동화된 공격: 스크립트 공격: 공격자는 스크립트를 작성하여 연속된 ID를 사용해 자동으로 시스템의 사용자 데이터를 수집하거나, 특정 동작을 수행하는 요청을 보낼 수 있습니다. 이는 시스템 자원을 소모시키고, 서비스 거부(DoS) 공격으로 이어질 수 있습니다.
> 3.	프라이버시 침해: 특정 사용자 타겟팅: 특정 사용자를 타겟으로 삼아 연속된 ID를 사용해 그 사람의 활동 내역이나 개인정보를 집중적으로 탐색할 수 있습니다. 예를 들어, /user/123이 특정 사용자를 나타낸다면, 그 사용자의 모든 활동을 추적할 수 있습니다.
> 4.	권한 오남용: 수정 및 삭제 권한 남용: 만약 시스템이 ID를 통해 데이터 수정이나 삭제 권한을 부여한다면, 연속된 ID를 사용해 다른 사용자의 데이터를 수정하거나 삭제하는 공격이 가능합니다. 예를 들어, /user/123/delete와 같은 요청을 연속된 ID에 대해 시도할 수 있습니다.
> 5.	보안 취약점 악용: 예측 가능한 취약점 발견: 공격자가 연속된 ID를 통해 시스템의 보안 취약점을 발견하고 이를 악용할 수 있습니다. 예를 들어, 특정 ID 범위 내에서만 발생하는 취약점을 찾아내고 이를 대량으로 악용할 수 있습니다.
> ```
> 
> 하지만 현재 토큰없이 접근하여 사용자 정보를 확인하는 API 가 열려있지 않아 위의 이슈는 해당되지 않을 것 같아요😀
> 
> 만약 토큰없이 접근가능한 API 가 존재해야한다면 ID 난수화(UUID), 추가 인증 수단을 제공함으로써 보안을 강화할 수 있을 것 같네요! 서현님은 어떻게 생각하실까요?!

헉 저는 id가 사실 보안적으로 뭐등록을 하거나, 삭제를 하는등의 위험으로만 생각했던 것 같습니다. 멘토님이 말씀해주셨던 것 처럼, 인증이 필요하기 때문에 괜찮을 것이라고 생각했습니다.

그러나 보안에 대해서는 자동화된 공격이나 보안 취약점 악용등 고민해야할 것들이 더 많네요...

UUID를 도입하는 편이 좋을 것 같습니다.
또한 별도의 추가인증 수단은 무엇이 있을지 고민해봐야할 것 같습니다!!

답변 감사합니다!!

2024-07-09 07:59 UTC, merged

2024-07-09 08:00 UTC, hocaron reviewed
서현님 2주차 진행해주시느라고 고생 많으셨습니다👍👍👍

피드백 드릴 때마다 엄청 깊게 고민해주시는게 보여서, 감사하고 뿌듯합니다! 3주차도 화이팅입니다!

2024-07-11 04:33 UTC, jinseohyun1228 commented
헉!! 감사합니다 저도 새로운 내용 많이 알게되어서 감사하고 즐겁습니다 ㅎㅎ 감사합니다.