경북대 BE_김영인 2주차 과제(0 ~ 3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #342
Opened 2024-07-05 07:52 UTC by Youngini

Security 관련한 내용을 여전히 모르겠어서 일단 구현할 수 있는 곳까지 구현을 하였습니다. 
하지만 아직 부족한 부분도 많고 리팩토링 할 부분도 있기 때문에 주말에 리팩토링을 진행해서 코드를 수정해야할 것 같습니다. 
리팩토링을 진행하고 피드백 받은 부분과 비교하며 리팩토링을 잘 했는지, 어떤 부분이 아직 부족한지 알고 싶습니다.

2024-07-05 16:47 UTC, gongdongho12 requested changes
3단계까지 고생많으셨습니다
리팩토링도 겸하느라 고민하셨을 것 같아요

작업하시면서 고민이 되었던 부분들을 PR 올리시구 코드부분 드래그해서 남겨주셔도 좋고 DM주셔도 좋으니 언제든 편하게 요청주세요 💪🏼

2024-07-05 16:47 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +        }
나중에 상품 말고도 리뷰도 없을 수 있는데요
그러면 이런건 ControllerAdvice같은걸 사용해서 getAllProducts 나 getAllReviews 등에서 없으면 throw NoContentException 주고 저 값으로 리턴하게 하면 공통화 할 수 있지 않을까요?

2024-07-05 16:47 UTC, gongdongho12 commented on src/main/java/gift/dto/CreateProductDto.java
> +    String imageUrl;
맨위의 이름만 NotBlank 적어주셨는데요

어짜피 @Valid 사용하는 상태라면 Reference 클래스는 전부 Null이 들어갈 수 있으므로 필수값일 price나 description 그리고 imageUrl 등에도 @NotBlank 같은거 넣어주는것도 좋지 않을까요?

특히 Integer는 음수가 될 수 있는데 지금 금액이 음수가 될 수 없는것도 같이요

요구사항 관점 있지만, 실제로 코딩하면서 **이러면 더 깔끔해 지겠다 같은 관점**도 키워보시면 좋을 것 같습니다

2024-07-05 16:47 UTC, gongdongho12 commented on src/main/java/gift/dto/MemberResponseDto.java
> +    }
get / set 메서드를 해준 Dto가 있고 아닌 객체가 있더라구요
단순히 리턴 용도로 사용해주는 용도라면 Dto보다는 Response 객체로 따로 관리해보면 어떨까요?
dto는 실제 데이터들을 옮기기 위한 객체인데 Response, Request, Dto의 용도들이 뒤죽박죽 섞여 있는 느낌이에요

특히 Reponse도 있고 ResponseDto도 있는데 관련 컨벤션을 정하고 공통화해주는게 좋지 않을까요?

2024-07-05 16:47 UTC, gongdongho12 commented on src/main/java/gift/dto/UpdateProductDto.java
> +    String imageUrl;
이친구도 위와 동일하죠?

(적용해보라는건 아니구) 만약 같이 사용하는 부분이 겹친다면 상속도 고려해볼 수 있을 것 같아요

2024-07-05 16:47 UTC, gongdongho12 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        }
메시지로 비교하지 말고 메시지를 리턴하면 되지 않을까요? 어짜피 그걸로 비교할거면 있으면 그걸로 리턴하고 메시지가 없을 때 다른거로 리턴하면 될 것 같아서요

2024-07-05 16:47 UTC, gongdongho12 commented on src/main/java/gift/service/MemberService.java
> +    }
이러면 진짜 무조건 Member로 리턴되서 편리하고 에러시 ContollerAdice에서 처리되겠죠?

2024-07-05 16:47 UTC, gongdongho12 commented on src/main/java/gift/validation/JwtTokenProvider.java
> +                .setExpiration(new Date(System.currentTimeMillis() + 86400000)) // 토큰 유효기간 1일
이 유효기간도 ONE_DAY_MILLS = 86400000 같이 적어두면 위에 secret_key 처럼 따로 주석 적지 않더라도 쉽게 이해할 수 있지 않을까요?

2024-07-05 16:47 UTC, gongdongho12 commented on src/main/java/gift/validation/ProductValidation.java
> +    }
Validation 클래스를 직접 구현하면 생각보다 작성할 부분이 많은데요
특정 객체에 Validation 클래스를 상속해서 구현하는 방법도 사용해보면 좋을 것 같습니다

시도해보는 방향은 좋았어요 😄

2024-07-05 16:47 UTC, gongdongho12 commented on src/main/resources/application.properties
> +# DB ??
UTF-8 설정이 재대로 되지 않은 것 같아요 😢

2024-07-07 15:45 UTC, gongdongho12 commented
@Youngini 이거 레포지토리 main으로 잡혀있는데 괜찮을까요?

2024-07-07 15:51 UTC, gongdongho12 requested changes
월요일에 추가로 확인해 주세요

2024-07-07 15:51 UTC, gongdongho12 commented on src/main/java/gift/controller/MemberController.java
> +public class MemberController {
api로 사용하는 controller면 `/api/members` 처럼 path 지정해보는게 어떨까요?

2024-07-07 15:51 UTC, gongdongho12 commented on src/main/java/gift/controller/MemberController.java
> +    }
JWT 처리를 별도 시큐리티 서비스 등에서 처리해줘야 하는데 컨트롤러 단에서 진행하고 있네요 😢

2024-07-08 12:38 UTC, Youngini commented
코치님께서 정리해 주신 부분을 다시 리팩토링해봤고 3단계 부분도 덜된 부분 다시 완료 하였습니다.

여전히 Security 부분이 어려워서 제대로 한건지는 잘 모르겠지만, 일단 최대한 이해한 곳 까지 진행해봤습니다!

2024-07-08 12:39 UTC, Youngini commented on src/main/java/gift/dto/CreateProductDto.java
> +    String imageUrl;
해당 내용은 피드백 반영하여 수정하였습니다! 감사합니다

2024-07-08 12:40 UTC, Youngini commented on src/main/java/gift/dto/MemberResponseDto.java
> +    }
Response, Request, Dto에 대한 기준을 제대로 잡지 않아서 발생한 문제인 것같습니다.
다음부터는 기능 목록 구성 단계에서 이런것도 설계하고 구현해보는 것을 연습해보겠습니다!

2024-07-08 12:41 UTC, Youngini commented on src/main/java/gift/validation/JwtTokenProvider.java
> +                .setExpiration(new Date(System.currentTimeMillis() + 86400000)) // 토큰 유효기간 1일
필요한 주석만 달도록 해보겠습니다!

2024-07-08 12:42 UTC, Youngini commented on src/main/resources/application.properties
> +# DB ??
application과 WebConfig로 해당 부분을 수정해봤는데 이렇게 하는게 맞을까?

2024-07-08 12:43 UTC, Youngini commented on src/main/java/gift/controller/MemberController.java
> +public class MemberController {
헤당 부분들도 다 수정하였습니다. 새로운 controller를 사용할 때도, api로 사용하는 경우는 api/를 추가하였습니다.

Controller가 api가 아니었던 적이 없어서 혹시 api가 아닌 경우에 대해서 힌트를 주실 수 있을까요? ㅠㅠ

2024-07-08 12:43 UTC, Youngini commented on src/main/java/gift/controller/MemberController.java
> +    }
관련 내용 Security로 옮겨서 수정했습니다! 감사합니다

2024-07-08 13:39 UTC, gongdongho12 approved these changes
기존에 Resolver로직 오류는 해결된거라고 생각하면 될까요?

2024-07-08 13:39 UTC, gongdongho12 commented on src/main/java/gift/controller/MemberController.java
> +        }
아직 인증 처리를 여러 서비스들을 컨트롤러에서 하고 있어요
비지니스 로직은 서비스 내부로 정리해보면 어떨까요?

2024-07-08 13:39 UTC, gongdongho12 commented on src/main/java/gift/dto/CreateProductDto.java
> +    String imageUrl;
Validation 👍🏼

2024-07-08 13:39 UTC, gongdongho12 commented on src/main/resources/application.properties
> +spring.mandatory-file-encoding=UTF-8
추후 또 발생하면 IDE 설정을 보면 좋을 것 같습니다

2024-07-08 13:39 UTC, gongdongho12 commented on src/main/java/gift/service/CustomUserDetailsService.java
> +}
이번 강의에선 SpringSecurity가 필수가 아니에요
단순히 인증 인가 그리고 Resolver를 컴포넌트 계층단위로 구분하는 부분입니다!

2024-07-08 13:40 UTC, merged

2024-07-09 05:39 UTC, Youngini commented on src/main/java/gift/controller/MemberController.java
> +        }
관련 내용 정리해서 다시 push 했습니다!

2024-07-09 07:05 UTC, Youngini commented
토큰을 변환해서 id값을 받아오고 싶은데 parserBuilder에서 계속 오류가 발생해서 저것을 사용하지 않고 어떻게 구현하는 것이 좋을지 잘 모르겠습니다.

2024-07-09 15:23 UTC, gongdongho12 commented
@Youngini 토큰을 파서빌더 없이 파싱하기가 더 어려울거에요!
IDE에서 오류일까요? 아니면 실행과정중에 오류실까요?