전남대 BE_박민규 2주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #343
Opened 2024-07-05 07:56 UTC by ps9319

2024-07-06 05:41 UTC, dc-choi requested changes
안녕하세요 민규님~! step2 과제하시느라 고생하셨습니다~!

자세한 내용은 코멘트에 남겨드렸습니다. 확인 부탁드릴게요~!

민규님이 남겨주신 코멘트에도 답변을 드리도록 하겠습니다!!!

> DTO의 변환은 어떤 계층에서 진행이 될까?: 고민해보고 찾아본 결과, 어느 계층에서든 상관은 없지만 일관성을 가지고(어떤 것은 service에서 dto->entity, 어떤 것은 controller에서 변환하지 않는다.) 의존성을 줄이는 방향으로 해야할 것 같습니다. 저는 서비스 계층에서 하는 것이 더 어울린다고 생각해서 서비스 계층에서 하고 있습니다.

저도 현재 시스템에서는 서비스에서 변환을 하고 있습니다. 어느정도 찾아보고 스스로 고민한 흔적이 보이네요! 찾아보시느라 고생하셨습니다!

> ProductDTO를 하나만 두거나 각각의 EndPoint마다 DTO를 하나씩 두는 것 중 어떻게 해야할까?: request와 response가 같은 형태이면 ProductDTO와 같이 사용해도 되고, 제가 만든 requestDTO와 responseDTO의 형태가 다르면 따로 만들어야 된다고 생각합니다.

> EndPoint마다 DTO를 두면 DTO가 너무 많아지는데 이것은 어떻게 관리해야 할까?: 음 패키지를 도메인별로 두고 각 도메인패키지 안에 dto 패키지를 두고 따로 관리하는 것을 생각했습니다. 다른 방법이 있을까 궁금해요! EndPoint마다 DTO를 두어야 하는 것은 분명한 것 같은데 다른 방법이 있을까요??

두 코멘트로 미루어 보았을 떄에는 민규님은 각각의 EndPoint마다 DTO를 하나씩 두는 것으로 고민을 하신거 같네요.

저 역시도 무분별하게 나누는 것은 별로 좋아하지 않아서 특별하게 다르지 않은 이상 request와 response의 값이 같다면 나누지 않을 거 같습니다.

하지만 그런 일은 많이 없더라고요... ㅎㅎ

전 DTO를 관리할 때 Inner Class를 활용해서 DTO Class의 개수가 너무 많아지는 것을 방지하려고 했습니다.

> step3가 끝나면 리팩토링 할 것

네 기다리고 있겠습니다! 파이팅!!! 과제하시느라 수고하셨습니다~!

2024-07-06 05:41 UTC, dc-choi commented on src/main/java/gift/auth/JwtTokenGenerator.java
> +public class JwtTokenGenerator {
`JwtTokenGenerator`이라는 네이밍보다는 JWT를 사용한다는 더 포괄적인 이름이 되었으면 좋겠어요.

나중에 토큰에 대한 조작을 하는 일이 생길텐데 그 경우에 토큰을 생성하기만 하는 객체의 이름처럼 보일 수도 있다고 생각했어요~!

2024-07-06 05:41 UTC, dc-choi commented on src/main/java/gift/auth/JwtTokenGenerator.java
> +        claims.put("role", role);
회원의 권한을 처리하는 부분을 누락하지 않고 잘 구현하신거 같아서 좋네요~!

2024-07-06 05:41 UTC, dc-choi commented on src/main/java/gift/controller/AuthController.java
> +@RequestMapping("/api")
요구사항에서 요구하는 URL 주소로 변경해주세요~!

2024-07-06 05:41 UTC, dc-choi commented on src/main/java/gift/controller/AuthController.java
> +    @PostMapping("/sign-up")
요구사항에서 요구하는 URL 주소로 변경해주세요~!

2024-07-06 05:41 UTC, dc-choi commented on src/main/java/gift/controller/UserController.java
> +public class UserController {
`UserController`에는 다른 로직이 없는거 같은데 어떤 이유에서 생성하셨나요?

2024-07-06 05:41 UTC, dc-choi commented on src/main/java/gift/domain/Role.java
> +public enum Role {
회원의 권한을 ENUM으로 관리하는 것은 좋은거 같습니다~!

2024-07-06 05:41 UTC, dc-choi commented on src/main/java/gift/dto/requestDTO/UserRequestDTO.java
> +    public static User toEntity(UserRequestDTO userRequestDTO) {
개인적으로 이 메서드는 저도 잘 활용하는 방식입니다. 좋은 거 같습니다! 굿굿!

2024-07-06 05:41 UTC, dc-choi commented on src/main/java/gift/service/AuthService.java
> +        String token = jwtTokenGenerator.createToken(userRequestDTO.email(), Role.USER.name());
지금은 회원의 권한이 전부 USER로 처리가 되는데 나중에 관리자로 가입을 시키려면 어떻게 해야할까요?

2024-07-06 05:41 UTC, dc-choi commented on src/main/java/gift/service/AuthService.java
> +        User user = userService.findByEmail(userRequestDTO);
DB에서 email과 password를 같이 조회해서 그 객체가 없다면 회원의 정보가 일치하지 않습니다. 라는 메시지를 보내는 것은 어떻게 생각하시나요?

ID, password에서 각각 어떤 부분이 틀렸다라고 직접적으로 보내주기보다는 로그인이 왜 실패했는지 대략적인 이유만 보내야 한다고 생각합니다.

보안적으로는 위 방식이 올바르다고 생각하는데 민규님의 생각은 어떠신지 궁금합니다!

2024-07-06 05:41 UTC, dc-choi commented on src/main/java/gift/service/AuthService.java
> +        userService.join(userRequestDTO);
저는 개인적으로 service에서 다른 service를 참조하는걸 좋아하지는 않습니다.

순환참조가 발생할 수 있고 직접 경험해봐서 그렇습니다... ㅎㅎ

2024-07-06 05:41 UTC, dc-choi commented on src/main/java/gift/service/AuthService.java
> +        String token = jwtTokenGenerator.createToken(userRequestDTO.email(), user.getRole());
`userRequestDTO`와 `user`에서 각각 email, role을 가져오는데 이 부분은 user에서 가져오는게 맞다고 생각합니다.

2024-07-06 05:41 UTC, dc-choi commented on src/main/resources/schema.sql
> +    email varchar(255),
데이터베이스에도 회원의 권한이 추가되었으면 좋겠다는 생각이 있습니다~!

2024-07-06 06:12 UTC, ps9319 commented on src/main/java/gift/auth/JwtTokenGenerator.java
> +public class JwtTokenGenerator {
아하 토큰을 디코딩하는 것을 생각하지 못하고 메서드 이름을 지었던 것 같습니다. 수정하겠습니다!

2024-07-06 06:12 UTC, ps9319 commented on src/main/java/gift/auth/JwtTokenGenerator.java
> +        claims.put("role", role);
감사합니다!

2024-07-06 06:18 UTC, ps9319 commented on src/main/java/gift/controller/AuthController.java
> +@RequestMapping("/api")
헉 이부분을 못 봤습니다! 수정하겠습니다.

2024-07-06 06:18 UTC, ps9319 commented on src/main/java/gift/controller/AuthController.java
> +    @PostMapping("/sign-up")
넵!

2024-07-06 06:21 UTC, ps9319 commented on src/main/java/gift/controller/UserController.java
> +public class UserController {
User를 찾을 때나 회원탈퇴 등의 기능이 생길 수도 있다고 생각해서 아직 구현을 하진 않고 만들어 놓기만 해놓았습니다!

2024-07-06 06:21 UTC, ps9319 commented on src/main/java/gift/domain/Role.java
> +public enum Role {
감사합니다!!

2024-07-06 06:21 UTC, ps9319 commented on src/main/java/gift/dto/requestDTO/UserRequestDTO.java
> +    public static User toEntity(UserRequestDTO userRequestDTO) {
우왕 감사합니다 헤헤

2024-07-06 06:22 UTC, ps9319 commented on src/main/java/gift/service/AuthService.java
> +        String token = jwtTokenGenerator.createToken(userRequestDTO.email(), Role.USER.name());
나중에 회원의 권한을 관리자로 변경하는 api를 만들어야 할 것 같습니다!

2024-07-06 06:28 UTC, ps9319 commented on src/main/java/gift/service/AuthService.java
> +        User user = userService.findByEmail(userRequestDTO);
네 저도 그게 맞는 것 같습니다 ㅠㅠ
악의적인 사용자가 아무 아이디와 아무 비밀번호를 입력했을 때 "비밀번호가 일치하지 않습니다"라는 메세지는 '아이디는 존재한다' 라는 것을 간접적으로 나타내는 것 같아서 수정하겠습니다!

2024-07-06 06:30 UTC, ps9319 commented on src/main/java/gift/service/AuthService.java
> +        userService.join(userRequestDTO);
아핫.. 이 부분도 controller에서 UserService를 참조하는 것으로 빼보겠습니다

2024-07-06 06:31 UTC, ps9319 commented on src/main/java/gift/service/AuthService.java
> +        String token = jwtTokenGenerator.createToken(userRequestDTO.email(), user.getRole());
앗 그러네요... userRequest로 user를 찾아놓고 userRequestDTO에서 가져오다니 ㅠㅠㅠ
수정하겠습니다

2024-07-06 06:31 UTC, ps9319 commented on src/main/resources/schema.sql
> +    email varchar(255),
아! 제가 나중에 권한 부분을 알아차려서 디비에는 반영하지 못한 것 같습니다 수정하겠습니다 감사합니다!

2024-07-06 11:50 UTC, dc-choi commented on src/main/java/gift/service/AuthService.java
> +        String token = jwtTokenGenerator.createToken(userRequestDTO.email(), Role.USER.name());
음... `Role.USER.name()`라는 상수로 받지 않고 사용자의 입력값에 따라 권한이 달라지도록 하는 방법이 더 좋을거 같습니다!

2024-07-06 11:55 UTC, dc-choi commented on src/main/java/gift/service/AuthService.java
> +        User user = userService.findByEmail(userRequestDTO);
위에서 말씀하신 두 방법을 구분지어야 하는 경우가 아니라면 에러코드도 구분해줄 필요가 없어보입니다~!

만약 두가지 케이스에 대해서 처리를 해줘야 하는 상황이 생긴다면 그때 에러코드와 메시지를 따로 처리하는게 맞다고 생각합니다~!

2024-07-06 12:15 UTC, dc-choi requested changes
민규님~ 아래 코멘트에 자세한 내역 남겨두었습니다~

아래 내역만 수정된다면 큰 문제는 없어보입니다~!

2024-07-06 12:15 UTC, dc-choi commented on src/main/java/gift/service/AuthService.java
> +        String token = jwtUtil.createToken(userRequestDTO.email(), Role.USER.name());
위에서 언급드린거처럼 `Role.USER.name()`로 처리하지 않고 요청값으로 처리되면 더 좋을거 같습니다!

2024-07-06 12:15 UTC, dc-choi commented on src/main/java/gift/controller/AuthController.java
> +    public ResponseEntity<UserResponseDTO> signUp(@RequestBody UserRequestDTO userRequestDTO){
이 부분의 예외처리도 추가되었으면 좋겠습니다~

2024-07-06 12:15 UTC, dc-choi commented on src/main/java/gift/controller/AuthController.java
> +    public ResponseEntity<UserResponseDTO> login(@RequestBody UserRequestDTO userRequestDTO){
이 부분의 예외처리도 추가되었으면 좋겠습니다~

2024-07-06 12:21 UTC, ps9319 commented on src/main/java/gift/service/AuthService.java
> +        String token = jwtTokenGenerator.createToken(userRequestDTO.email(), Role.USER.name());
넵 수정하겠습니다!

2024-07-06 12:30 UTC, ps9319 commented on src/main/java/gift/service/AuthService.java
> +        String token = jwtUtil.createToken(userRequestDTO.email(), Role.USER.name());
넵 반영했습니다!

2024-07-06 12:56 UTC, ps9319 commented on src/main/java/gift/controller/AuthController.java
> +    public ResponseEntity<UserResponseDTO> signUp(@RequestBody UserRequestDTO userRequestDTO){
수정했습니다!

2024-07-06 12:57 UTC, ps9319 commented on src/main/java/gift/controller/AuthController.java
> +    public ResponseEntity<UserResponseDTO> login(@RequestBody UserRequestDTO userRequestDTO){
수정했습니다!

2024-07-07 03:47 UTC, dc-choi approved these changes
민규님~! step2 과제 진행하시느라 고생하셨습니다~! merge 하도록 하겠습니다!

2024-07-07 03:47 UTC, merged