강원대 BE_이강욱_2주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #345
Opened 2024-07-05 07:59 UTC by kanguk01

# Step2 피드백 반영 중 의문점

## 의문점 정리

### **그러면 Price, ImageUrl도 값 객체로?**

의문을 가졌었는데 일단 name은 패턴, 길이, 허용되는 문자 등의 여러 규칙이 있는 복잡한 값이기 때문에 값 객체로 한 것인데 

가격과 이미지는 그정도 복잡한 규칙이 없기 때문에 그냥 클래스 내에서 진행하도록 했습니다.

제가 생각한게 맞는 것인가요?

### 예외 httpstatus 처리 관련

```java
INVALID_NAME_SIZE("상품 이름은 15자 이하여야합니다. (공백포함)", HttpStatus.BAD_REQUEST),
INVALID_NAME_PATTERN("( ), [ ], +, -, &, /, _ 외 특수문자는 사용 불가능합니다.", HttpStatus.BAD_REQUEST),
KAKAO_NAME_NOT_ALLOWED("상품 이름에 '카카오'가 포함되어 있습니다. 담당 MD와 협의해 주세요.", HttpStatus.BAD_REQUEST),
PRODUCT_NOT_FOUND("해당 상품이 존재하지 않습니다.", HttpStatus.NOT_FOUND),
EMAIL_ALREADY_EXISTS("해당 이메일이 이미 존재합니다.", HttpStatus.BAD_REQUEST),
INVALID_CREDENTIALS("이메일 또는 비밀번호가 잘못되었습니다.", HttpStatus.FORBIDDEN),
USER_NOT_FOUND("해당 사용자가 존재하지 않습니다.", HttpStatus.NOT_FOUND),
INVALID_TOKEN("유효하지 않은 토큰입니다.", HttpStatus.UNAUTHORIZED),
UNAUTHORIZED_REQUEST("유효한 인증 자격 증명이 없습니다.", HttpStatus.UNAUTHORIZED),
INVALID_PRICE("가격은 음수일 수 없습니다.", HttpStatus.BAD_REQUEST),
INVALID_IMAGE_URL("이미지 URL은 null이거나 빈 문자열일 수 없습니다.", HttpStatus.BAD_REQUEST);
```

피드백에서는 handler에서 status를 정하라고 하셨는데, 그것보다는 errorcode 자체에서 이렇게 정하는 것이 더 좋은 방법인 것 같아서 이렇게 했는데 어떤가요?

핸들러에서 하려니 초반 값을 주입하는 것이 약간 나이스해 보이지가 않아서요…

### @ResponseStatus 관련

```java
@DeleteMapping("/{id}")
@ResponseStatus(HttpStatus.NO_CONTENT)
public void deleteUser(@PathVariable Long id) {
    userService.deleteUser(id);
}
```

이렇게 바꿀 수 있는 것 같은데… 

다른 컨트롤러 메소드들에서는 다 `ResponseEntity`를 쓰는데 이것만 바꾸는게 맞나? 

전체적으로 `ResponseEntity` 가 필요 없다는 말씀이신가요?

저번 피드백에서 말씀주셨던 `ResultResponse` 을 적용해서 아에 한번에 다 통일시키는 것은 어떻게 생각하시나요? 이 부분은 시간 날 때 한번에 적용해 볼 예정입니다!

### User

> user에게 메세지를 던져보면 좋을것 같네요!
> 

이 말이 Product처럼 비밀번호 검증을 엔티티에서 하라는 말씀이신건가요? 제가 이해한 게 맞는지 궁금합니다. 

그 전 Product에서 받았던 피드백 총 반영하여 User도 반영해 보았는데, 잘 한건지 궁금합니다!

### 토큰 서비스 (못함)

```java
compileOnly 'io.jsonwebtoken:jjwt-api:0.12.6'
runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
```

최신 버전으로 바꾸니까…

```java
public String generateToken(String email) {
        return Jwts.builder()
                .setSubject(email)
                .setIssuedAt(new Date())
                .setExpiration(new Date(System.currentTimeMillis() + 86400000)) // 1 day expiration
                .signWith(secretKey)
                .compact();
    }
```

얘네가 deprecated 되어있다.. 수정하자 

JJWT 0.12.5 최신 버전을 이용하면 deprecated가 되는 것을 확인했는데, 최신에 업데이트가 됐는지 정보가 많이 안보이고 직접 하기에 너무 어려움을 느껴서 일단 그대로 두었습니다.. 

기존 버전에서는 deprecated 되었다고 뜨지는 않는데.. 계속 찾아봤는데 시간낭비를 너무 많이 해서 일단 두겠습니다.. ㅠㅠ

---

# Step3 
도저히 진행되지 않아 일단 PR 올리고 질문드립니다 ㅠㅠ 
일단 위시리스트 자체의 api는 모두 구현을 하고 인증 및 사용자 정보를 검증하는 부분을 진행중이였습니다.

![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/85006156/22c8124e-4ab3-4e3c-89a7-1a3e031e49b8)
현재 JWT까지 잘 발급&검증 하는 것 같은데 
위시리스트 추가를 하면 User 객체에 다 null이 들어가면서 user 객체 생성될 때 검증하는 곳에서 막혀버립니다...
LoginMemberArgumentResolver 도 제가 보기에는 별 문제가 있어 보이지는 않는데 이 부분에서 막혀서 더이상 진행할 수가 없었습니다...
 한번 봐주시고 제가 이상하게 한 부분이 있다면 알려주시면 감사하겠습니다..!

늘 감사드립니다 멘토님.. 항상 고생 많으십니디!🥹

2024-07-05 15:30 UTC, pci2676 commented
> ### **그러면 Price, ImageUrl도 값 객체로?**
> 의문을 가졌었는데 일단 name은 패턴, 길이, 허용되는 문자 등의 여러 규칙이 있는 복잡한 값이기 때문에 값 객체로 한 것인데
> 
> 가격과 이미지는 그정도 복잡한 규칙이 없기 때문에 그냥 클래스 내에서 진행하도록 했습니다.
> 
> 제가 생각한게 맞는 것인가요?

해당 값들이 별도의 도메인 로직을 단독으로 수행해야한다면 값 객체로 표현하는게 충분히 값어치 있을것 같습니다~!

2024-07-05 15:33 UTC, pci2676 commented
> ### 예외 httpstatus 처리 관련
> ```java
> INVALID_NAME_SIZE("상품 이름은 15자 이하여야합니다. (공백포함)", HttpStatus.BAD_REQUEST),
> INVALID_NAME_PATTERN("( ), [ ], +, -, &, /, _ 외 특수문자는 사용 불가능합니다.", HttpStatus.BAD_REQUEST),
> KAKAO_NAME_NOT_ALLOWED("상품 이름에 '카카오'가 포함되어 있습니다. 담당 MD와 협의해 주세요.", HttpStatus.BAD_REQUEST),
> PRODUCT_NOT_FOUND("해당 상품이 존재하지 않습니다.", HttpStatus.NOT_FOUND),
> EMAIL_ALREADY_EXISTS("해당 이메일이 이미 존재합니다.", HttpStatus.BAD_REQUEST),
> INVALID_CREDENTIALS("이메일 또는 비밀번호가 잘못되었습니다.", HttpStatus.FORBIDDEN),
> USER_NOT_FOUND("해당 사용자가 존재하지 않습니다.", HttpStatus.NOT_FOUND),
> INVALID_TOKEN("유효하지 않은 토큰입니다.", HttpStatus.UNAUTHORIZED),
> UNAUTHORIZED_REQUEST("유효한 인증 자격 증명이 없습니다.", HttpStatus.UNAUTHORIZED),
> INVALID_PRICE("가격은 음수일 수 없습니다.", HttpStatus.BAD_REQUEST),
> INVALID_IMAGE_URL("이미지 URL은 null이거나 빈 문자열일 수 없습니다.", HttpStatus.BAD_REQUEST);
> ```
> 
> 피드백에서는 handler에서 status를 정하라고 하셨는데, 그것보다는 errorcode 자체에서 이렇게 정하는 것이 더 좋은 방법인 것 같아서 이렇게 했는데 어떤가요?
> 
> 핸들러에서 하려니 초반 값을 주입하는 것이 약간 나이스해 보이지가 않아서요…

이 애플리케이션이 http기반으로 움직이기 때문에 지금은 그리 큰 문제가 되지 않을것 같아요

사실 다른 환경이라해도 이 값을 가지고 있다고해서 문제가 발생하는건 아닐 수 있고요!

다만, http응답을 하는 환경이 아니라면 위와 같은 값을 굳이 알아야 하는가에 대한 의문이 생길수 있습니다.

http 응답을 하지 않아야 하는 환경에서 새로운 error code를 정의해야한다면 그러한 의문은 더욱 증폭될 수 있겠네요.

그러한 의미에서 http status 를 이렇게 exception레벨에서 관리하는게 맞을지에 대한 의문이 드는것 같습니다~!

그런데 지금은 일단 이렇게 해도 괜찮을것 같습니다~ 이 부분은 나중에 천천히 고려해보셔도 좋을것 같아요~

2024-07-05 15:34 UTC, pci2676 commented
> ### @ResponseStatus 관련
> ```java
> @DeleteMapping("/{id}")
> @ResponseStatus(HttpStatus.NO_CONTENT)
> public void deleteUser(@PathVariable Long id) {
>     userService.deleteUser(id);
> }
> ```
> 
> 이렇게 바꿀 수 있는 것 같은데…
> 
> 다른 컨트롤러 메소드들에서는 다 `ResponseEntity`를 쓰는데 이것만 바꾸는게 맞나?
> 
> 전체적으로 `ResponseEntity` 가 필요 없다는 말씀이신가요?
> 
> 저번 피드백에서 말씀주셨던 `ResultResponse` 을 적용해서 아에 한번에 다 통일시키는 것은 어떻게 생각하시나요? 이 부분은 시간 날 때 한번에 적용해 볼 예정입니다!

오 보통 아무런 정의를 하지 않으면 200 OK 응답이 나가고 필요에 따라 별도의 코드로 응답이 필요하면 저렇게 정의하곤 합니다!

저번에 저는 ResultResponse를 모든 API가 동일한 응답 포맷으로 사용하는것이 좋다고 말씀드린 것 이었는데 뭔가 오해가 있었던것 같네요~!

2024-07-05 15:35 UTC, pci2676 commented
> ### User
> > user에게 메세지를 던져보면 좋을것 같네요!
> 
> 이 말이 Product처럼 비밀번호 검증을 엔티티에서 하라는 말씀이신건가요? 제가 이해한 게 맞는지 궁금합니다.
> 
> 그 전 Product에서 받았던 피드백 총 반영하여 User도 반영해 보았는데, 잘 한건지 궁금합니다!

맞습니다~! 잘 해주신것 같네요!

2024-07-05 15:36 UTC, pci2676 commented
> ### 토큰 서비스 (못함)
> ```java
> compileOnly 'io.jsonwebtoken:jjwt-api:0.12.6'
> runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
> runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
> ```
> 
> 최신 버전으로 바꾸니까…
> 
> ```java
> public String generateToken(String email) {
>         return Jwts.builder()
>                 .setSubject(email)
>                 .setIssuedAt(new Date())
>                 .setExpiration(new Date(System.currentTimeMillis() + 86400000)) // 1 day expiration
>                 .signWith(secretKey)
>                 .compact();
>     }
> ```
> 
> 얘네가 deprecated 되어있다.. 수정하자
> 
> JJWT 0.12.5 최신 버전을 이용하면 deprecated가 되는 것을 확인했는데, 최신에 업데이트가 됐는지 정보가 많이 안보이고 직접 하기에 너무 어려움을 느껴서 일단 그대로 두었습니다..
> 
> 기존 버전에서는 deprecated 되었다고 뜨지는 않는데.. 계속 찾아봤는데 시간낭비를 너무 많이 해서 일단 두겠습니다.. ㅠㅠ

이전에 말씀드린 것처럼 이러한 부분을 잘 정리해서 기술 블로그에 올리면 좋을것 같아요!

심지어 다른 블로그에는 자료가 더 없다면 더 값어치 있지 않을까요?

시간이 나실때 해보셔요~

2024-07-05 16:05 UTC, pci2676 requested changes
잘 구현해주셨네요~

리뷰를 남겨두었으니 확인후 개선해주세요~

일요일까지 해주시면 되니 4단계를 포함시켜주셔도 좋습니다~(선택이니 안하셔도 상관 없어요~)

2024-07-05 16:05 UTC, pci2676 commented on src/main/java/gift/config/WebConfig.java
> +    }
잘 해주신것 같아요~! 👍 

다른 방법으로는 커스텀 애너테이션을 만들고 해당 애너테이션이 달려있는 controller method에 한해 interceptor가 동작하도록 하는 방식도 있습니다. 

이러한 방식은 비단 로그인에만 사용되는 방식은 아니니 나중에 한번 찾아보세요~

spring aop 에 대해 알아보시면 도움이 될 것 같네요~

지금은 스프링에 대한 깊이가 없어 힘들 수 있지만 차차 알아가시면 되니 너무 조급하게 생각하지마세요~

2024-07-05 16:05 UTC, pci2676 commented on src/main/java/gift/config/WebConfig.java
> +    private TokenService tokenService;
Autowired를 사용하지말고 생성자 주입을 해주시는게 더 좋을것 같습니다~

2024-07-05 16:05 UTC, pci2676 commented on src/main/java/gift/resolver/LoginMemberArgumentResolver.java
> +    }
잘해주셨습니다~!!!

authorizationHeader또한 뭔가 많은 작업을 해야하는것으로 보이는데요~

String을 가지고 지지고 볶는 행위를 Resolver에 모두 노출시키기 보다 별도의 객체를 생성하여 그 책임을 할당시켜보면 어떨까요?

2024-07-05 16:05 UTC, pci2676 commented on src/main/java/gift/service/TokenService.java
> +            System.out.println("Extracted claims: " + claims);
system out은 입출력에 따른 비용이 크니 logger를 이용하여 로그를 남겨보면 좋을것 같습니다!

2024-07-05 16:05 UTC, pci2676 commented on src/main/java/gift/service/TokenService.java
> +            System.out.println("Extracted claims: " + claims);
다른 부분도 함께 찾아서 적용해주세요~!

2024-07-05 16:05 UTC, pci2676 commented on src/main/java/gift/entity/Product.java
>      }
Product를 비롯해 다른 도메인 객체들이 가지고 있는 도메인 로직을 단위 테스트로 작성해주시면 더욱 좋을것 같습니다. 😄

2024-07-05 16:05 UTC, pci2676 commented on src/main/java/gift/service/WishService.java
> +                .filter(p -> p.id.equals(wish.productId))
wish의 productId가 동일한지 물어보는 것도 메세지를 던지는 형태로 변경할 수 있을것 같네요~

2024-07-05 16:05 UTC, pci2676 commented on src/main/java/gift/entity/Wish.java
> +    }
비단 Wish 뿐 아니라 다른 객체들도 새롭게 생성하는 경우에는 id를 null로 명시적 주입을 해주고 있는데요

두개의 생성자를 만들어서 생성자 체이닝을 활용하면 조금 더 간결하게 표현할 수 있으니 참고해주세요~!

```java
class A {
  private final String value;
  
  public A(Long id, String value) {
    this.id = id;
    this.value = value;
  }

  public A(String value) {
    this(null, value)
  }

}
```

2024-07-05 16:06 UTC, pci2676 commented on src/main/java/gift/entity/User.java
> +    }
👍

2024-07-07 08:52 UTC, kanguk01 commented on src/main/java/gift/config/WebConfig.java
> +    }
너무나도 깊고 깊은 스프링의 세계... 추후에 한번 공부해보겠습니다..!

2024-07-07 08:54 UTC, kanguk01 commented on src/main/java/gift/config/WebConfig.java
> +    private TokenService tokenService;
너무 무지성으로 짰네요..... 수정하겠습니다.,!

2024-07-07 08:58 UTC, kanguk01 commented on src/main/java/gift/service/TokenService.java
> +            System.out.println("Extracted claims: " + claims);
아이고 너무 급하게 디버깅해보느라 일차원적인 방법을 사용했네요..! 이부분 또한 수정하겠습니다...!

2024-07-07 08:59 UTC, kanguk01 commented on src/main/java/gift/entity/Product.java
>      }
구현에 너무 급급하느라 테스트를 잊었습니다..ㅠ 작성하도록 하겠습니다!

2024-07-07 08:59 UTC, kanguk01 commented on src/main/java/gift/service/WishService.java
> +                .filter(p -> p.id.equals(wish.productId))
확인했습니다!

2024-07-07 09:00 UTC, kanguk01 commented on src/main/java/gift/entity/Wish.java
> +    }
오 좋은 방법 감사합니다!@!

2024-07-07 09:38 UTC, kanguk01 commented on src/main/java/gift/resolver/LoginMemberArgumentResolver.java
> +    }
수정하겠습니다!!

2024-07-07 10:45 UTC, kanguk01 commented
수정하였습니다.!
http://localhost:8080/swagger-ui/index.html
swagger로 적용하였습니다!!

2024-07-07 13:09 UTC, pci2676 commented
> 수정하였습니다.! http://localhost:8080/swagger-ui/index.html swagger도 적용하였습니다!!
> 
> ### 의문점
> > _wish의 productId가 동일한지 물어보는 것도 메세지를 던지는 형태로 변경할 수 있을것 같네요~_
> 
> 이게 제가 이해한게 맞는지 궁금하네요.. 엔티티 내에서 유효성 검증을 처리하는 식으로 바꾸라는 말씀이 맞으신가요? 저번 피드백에도 이와 같이 진행했었는데 맞는지 궁금합니다..!

네 맞습니다~!

> 
> ```java
> implementation 'org.slf4j:slf4j-api:1.7.32'
> implementation 'org.slf4j:slf4j-simple:1.7.32'
> ```
> 
> 로깅을 적용하라고 하셨는데, 찾아보니 `SLF4J` 가 나오더라고요 혹시 이걸 말씀하시는게 맞을까요?
> 
> 기존 System out은 에러를 수정하느라 임시로 추가했다가 미처 못 지운 부분이였습니다… ㅠㅠ

네 저 의존성도 좋습니다~! 여러가지 로그용 의존성이 많으니 나중에 이와 관련해서도 공부해보시면 좋을것 같습니다~!

2024-07-07 13:15 UTC, pci2676 approved these changes
4단계 까지 잘 적용해주셨네요!

merge 하겠습니다. 수고하셨습니다!

2024-07-07 13:15 UTC, pci2676 commented on src/main/java/gift/config/SwaggerConfig.java
> +}
4단계로 스웨거를 도입해주셨군요? 👍 

스웨거도 좋은 도구이지만 RestDoc 또한 양대산맥을 이루는 도구이니 알아두시면 좋을것 같습니다.

2024-07-07 13:15 UTC, pci2676 commented on src/main/java/gift/entity/Wish.java
> +    public Wish(Long id, Long userId, Long productId, ProductService productService) {
오.. entity에 service의 의존성이 침투한것 같네요 😢 

의존성의 방향은 언제나 바깥에서 안으로 향하도록 해주세요~

ex. controller -> service

2024-07-07 13:15 UTC, pci2676 commented on src/test/java/gift/service/UserServiceTest.java
> +    @Mock
Mock을 이용한 테스트를 수행하면 mock을 한 대상이 실제로 반환할 수 없는 결과를 반환할 수 있도록 설정하면서

올바르지 않은 테스트가 수행될 수 있습니다.

그래서 가능하면 mock을 사용하지 않는것이 좋습니다.

물론 사용해도 되는 경우가 있는데 이 부분은 설명하기에는 너무 많은 시간이 들것 같아서 

책 '단위 테스트'를 읽어보면 상세한 설명이 있으니 추천드립니다. 😄

2024-07-07 13:15 UTC, merged

2024-07-07 13:17 UTC, kanguk01 commented on src/main/java/gift/config/SwaggerConfig.java
> +}
감사합니다! 한번 학습해보도록 하겠습니다!

2024-07-07 13:19 UTC, kanguk01 commented on src/main/java/gift/entity/Wish.java
> +    public Wish(Long id, Long userId, Long productId, ProductService productService) {
아 이게뭐야 ㅠ 너무 다른것만 보고 수정하다가 어이없는 코드를 짜버렸네요 ㅠ 다음에 바로 수정하도록 하겠습니닷...

2024-07-07 13:20 UTC, kanguk01 commented on src/test/java/gift/service/UserServiceTest.java
> +    @Mock
헉 전혀 생각도 못한 부분입니다.. 관련 내용 학습해보고 수정해보도록 하겠습니다..!