경북대 BE_주보경 2주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #346
Opened 2024-07-05 08:05 UTC by jupyter471

과제 제출을 위해 2단계 pr를 따로 보냅니다. 죄송합니다.

jwt 관련 코드가 생성되면서 패키지를 어떻게 구성해야하는지 헷갈립니다.

2024-07-07 12:28 UTC, sang5c requested changes
2주차도 고생 많으셨습니다.  

회원 가입 기능이 빠져있어서 request change를 드려요!  
이부분 확인해서 추가해주시면 머지하겠습니다. :)  

> jwt와 인증 관련 코드 파일들이 생기면서 패키지를 어떻게 나누어야하는지 헷갈립니다. 패키지들이 점점 늘고 있는데 이게 맞나라는 의문이 드네요 

어떤 이유로 이게 맞나라는 생각이 드시나요? 패키지를 나누는 것은 정리정돈이기에 코드를 보는 사람(나 혹은 동료)들끼리 협의되고 읽기 편하기만 하면 상관없습니다.  
저는 좋다고 느꼈습니다

> 피드백 주신 것 관련하여 성공일 때도 String 말고 JSON 형식으로 반환하게 코드 수정하였습니다. 멘토님의 의도가 맞게 구현되었는지 피드백 부탁드립니다.  

맞습니다 :) 

> DTO를 작성하면서 인텔리제이에서는 class 말고 record로 전환하라고 하는데 시간이 지나도 값이 변수 값이 변하지 않을 거라는 확신이 있다면 record를 쓰면 되는 것일까요?

DTO는 값을 전달하기 위한 객체입니다.  
전달이 목적이기에 중간에 값을 변경하지 않고, 받는쪽에서 데이터를 읽기 위해 getter가 필요합니다.  
이러한 특성이랑 record가 잘 어울린다고 생각해요.

2024-07-07 12:28 UTC, sang5c commented on src/main/java/gift/controller/MemberController.java
> +@RequestMapping("/api/users")
URL은 /api/users인데 내부에서 Member라고 호칭하고 있네요. 하나로 맞춰보면 어떨까요?

2024-07-07 12:28 UTC, sang5c commented on src/main/java/gift/domain/member/Member.java
> +    public Member(String email, String name, String password, int role) {
생성자가 사용되지 않네요! 추가로 아래 getter/setter 메서드들도 사용되지 않는 걸로 보이는데 정리해주세요!

2024-07-07 12:28 UTC, sang5c commented on src/main/java/gift/service/WishService.java
> +        if (productRepository.isNotValidProductId(request.getProductId())) {
33번 라인은 Exist고 여긴 Valid네요! 어떤 차이가 있나요?

2024-07-07 12:28 UTC, sang5c commented on src/main/java/gift/domain/wish/WishRepository.java
> +    public ArrayList<Wish> getAllWishes(Long memberId) {
구체 타입을 반환하기보다는 List 인터페이스를 반환하면 어떨까요?

2024-07-07 12:28 UTC, sang5c commented on src/main/java/gift/domain/wish/WishRepository.java
> +            return quantities.getFirst(); // 이미 존재하는 상품의 경우 현재 수량을 반환
주석이 필요한 코드라면, 주석 없이 코드로 풀어볼 방법을 고민해보면 좋을 것 같아요.  
현재 메서드명은 존재하는지 확인해서 boolean을 반환할 것 같은데, 실제 내부 구현은 수량을 반환하고 있습니다.

2024-07-07 12:28 UTC, sang5c commented on src/main/java/gift/authentication/LoginMemberArgumentResolver.java
> +        //return parameter.getParameterAnnotations(Member.class); -> 오류
무의미한 주석은 제거해주세요~

2024-07-07 13:21 UTC, sang5c commented
지금 바로 수정하지 않으셔도 되니 완료되시면 리뷰 요청 눌러주세요~

2024-07-07 14:23 UTC, jupyter471 commented on src/main/java/gift/service/WishService.java
> +        if (productRepository.isNotValidProductId(request.getProductId())) {
다시보니 모두 valid로 통일하는 것이 맞는 것 같습니다! 없는 유저와 상품 정보를 요청하는 것 자체가 유효하지 않은 요청인 것 같습니다!

2024-07-07 14:24 UTC, jupyter471 commented on src/main/java/gift/domain/wish/WishRepository.java
> +            return quantities.getFirst(); // 이미 존재하는 상품의 경우 현재 수량을 반환
헉 짚어주셔서 감사합니다! 네이밍에도 신경 쓰겠습니다!

2024-07-07 14:26 UTC, jupyter471 commented on src/main/java/gift/domain/wish/WishRepository.java
> +    public ArrayList<Wish> getAllWishes(Long memberId) {
아 확장성을 고려하면 List 인터페이스 타입으로 반환하는 것이 좋겠네요!!

2024-07-08 14:00 UTC, sang5c approved these changes
2주차 과제 고생 많으셨습니다 👏  

마지막 리뷰 하나 더 남겼으니 확인해주시고 3주차도 파이팅입니다~!

2024-07-08 14:00 UTC, sang5c commented on src/main/java/gift/domain/member/MemberRepository.java
> +    }
저는 Repository가 "존재한다"를 나타내고, 이를 기반으로 서비스에서 "유효하다"를 판단해야 한다고 생각해요 :)  
값에 따라 상태를 판단하는 것은 비즈니스 로직이라고 생각합니다.

2024-07-08 14:01 UTC, merged