충남대 BE_배민수 2주차 과제 (2단계 ~ 3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #349
Opened 2024-07-05 08:10 UTC by minsu-cnu

이번에도 postman으로 대부분의 테스트를 진행했습니다. 추후 mock에 대해 공부하고 테스트 코드를 작성하고자 계획하고 있습니다!

과제가 금요일 18시까지 제출인데, 시간 상 2단계, 3단계의 리뷰 및 반영 과정을 따로 거치기에는 촉박하다고 판단되어서 2단계와 3단계를 하나의 PR로 드리게 되었습니다. 이 점 멘토님께 양해 말씀 드립니다..!

2단계, 3단계를 진행하면서 궁금한 점이 몇 가지 있는데 질문드리고 싶습니다!

<br/>
<hr/>
<br/>

![erd](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/104720635/fa2838d7-3a3b-4a7c-a1ee-1081020479ac)

1. ERD를 설계하면서, 회원 테이블에서 이메일은 일반적으로 변경될 수도 있다는 생각이 들어서, pk로 두기 애매한 것 같아 인조키를 pk로 두었습니다.

그런데 막상 회원 식별은 이메일로도 다 되어서 인조키를 쓸 일이 없었고, 이러한 방식이 당장은 어떤 문제가 있을지 잘 모르겠습니다. 이런 설계가 추후 어떤 문제점이 발생할 여지가 있을지 멘토님의 의견이 궁금합니다!

<br/>
<br/>

2. 관리자 페이지에서도 관리자 계정에 대한 인증&인가 로직을 도입하였습니다. 그런데 관리자 페이지 자체가, 클라이언트를 백엔드 역할인 제가 만드는 셈인데, 그러다보니 관리자 페이지에서 직접 매번 요청마다 헤더에 토큰을 담아보내야하고, 리다이렉트도 서버에서 시켜주어야해서 많이 번거로웠습니다.
 
게다가 액세스 토큰을 로컬 스토리지에 담아두는 방식으로 구현했는데, 원래라면 탈취의 위험을 경감시키기 위해 클라이언트단에서 자체적으로 상태 관리 등을 통해 리액트 등의 런타임에서 액세스 토큰을 갖고 있는다던지 할 수 있을텐데, 이번 과제에서는 그럴 수가 없으니 로컬 스토리지 저장 방식을 채택했습니다.

보통 이런 식으로 관리자 페이지 로그인 기능을 구현하시는지, 아니면 다른 좋은 방법이 있는지 궁금합니다!

<br/>
<br/>

3. 이건 질문은 아니지만... 개인적으로 이번 과제가 꽤나 어려웠어서 객체 지향적인 구현과 코드 효율성을 고려하지 못하고, 과제 마감 기한에 맞추기 위해 급하게 구현했다보니 코드가 많이 지저분합니다. 주말동안 리팩토링을 해볼 계획인데, 관련하여 조언 주시면 감사드리겠습니다!

2024-07-05 17:54 UTC, jjongwa requested changes
2, 3단계도 잘 구현해 주셨어요~! 👏👏

주말동안 리펙토링과 테스트 부분 보강한다고 하셔서 간단한 리뷰 정도 남겼습니다!

질문 주신 부분에 대한 답을 하자면..
Member의 PK를 회원 고유번호로 지정한건 아주 잘 선택해 주셨어요!
민수님이 말씀하신대로 이메일은 추후 변경될 여지가 있을 수도 있구요,
PK는 결국 각 데이터를 **고유하게 분별**할 수 있고, 그러면서 **빠르게** 찾을 수 있어야 하는게 포인트입니다!
만약 이메일같은 긴 문자열로 키를 설정한다면 조회할 때 상대적으로 시간이 많이 걸리겠죠?
DB의 인덱스에 대해서 공부해 보시면 바로 감이 올거예요!

주말동안 리팩토링 진행하면서 추가적으로 궁금한게 생기면 뭐든 질문 남겨주세요~!

2024-07-05 17:54 UTC, jjongwa commented on src/main/java/gift/product/controller/AdminController.java
> +@RequestMapping("/admin")
여기는 `@Controller`를 사용헀네요!
`@RestController`와 `@Controller`의 차이점은 무엇일까요?

2024-07-05 17:54 UTC, jjongwa commented on src/main/java/gift/product/controller/AdminController.java
>      }
email 정보는 쓰이지 않는 것 같은데 LoginMember 객체를 만들어 repository까지 전달하는 이유가 있나요?
LoginMember는 어떤 역할을 의도한건지 궁금하네요.!

2024-07-05 17:54 UTC, jjongwa commented on src/main/java/gift/product/controller/AdminController.java
> +    public ResponseEntity<?> loginSuccess(@RequestParam("accessToken") JwtResponse jwtResponse, HttpServletResponse response) {
와일드카드 타입을 넣는 것보단 Void를 넣는 방법도 있습니다~!
```suggestion
    public ResponseEntity<Void> loginSuccess(@RequestParam("accessToken") JwtResponse jwtResponse, HttpServletResponse response) {
```

2024-07-05 17:54 UTC, jjongwa commented on src/main/java/gift/product/controller/ProductController.java
>          return ResponseEntity.ok().build();
지금 현재 구성으로 보았을 때
input으로 받은 id에 해당하는 상품이 없거나,
해당하는 상품이 있는데 로그인한 사람의 상품이 아닐 때에도 동일하게 OK 응답을 보낼 것 같네요.! 
각 상황별 예외 처리를 추가해 보는건 어떨까요?

2024-07-05 17:54 UTC, jjongwa commented on src/main/java/gift/product/dto/AdminProductDto.java
> +}
목적에 따른 Dto 분리 👍

2024-07-05 17:54 UTC, jjongwa commented on src/main/java/gift/product/model/Member.java
> +}
```
public class Member {
    private final Long memberId;
    private final String email;
    private final String password;

    public Member(String email, String password) {
        this.memberId = null;
        this.email = email;
        this.password = password;
    }

    public Member(Long memberId, String email, String password) {
        this.memberId = memberId;
        this.email = email;
        this.password = password;
    }

    public Long getMemberId() {
        return memberId;
    }

    public String getEmail() {
        return email;
    }

    public String getPassword() {
        return password;
    }
}
```

model 패키지에 있는 친구들은 이렇게 필드를 final를 붙여본 다음 전체적인 로직이 동작하게 리팩토링 해보면 조금 더 객체지향적인 코드를 만들 수 있을 거에요! 필수까진 아니지만 추천드립니다~!

2024-07-05 17:54 UTC, jjongwa commented on src/main/java/gift/product/repository/AuthRepository.java
> +    }
부정의 부정을 쓰다 보면 헷갈릴 수 있어요! 리팩토링 해볼까요?

2024-07-05 17:54 UTC, jjongwa commented on src/main/java/gift/product/repository/ProductRepository.java
>              }
`SimpleJdbcInsert`도 한번 학습해 보고 사용해 볼까요?

2024-07-06 12:50 UTC, minsu-cnu commented on src/main/java/gift/product/controller/AdminController.java
> +@RequestMapping("/admin")
@Controller는 메소드가 뷰를 반환할 때 사용하는 어노테이션으로 알고있습니다.
@RestController는 @Controller와 @ResponseBody의 조합으로, 모든 메소드가 뷰가 아닌 어떤 객체를 반환해야할 때 사용하는 것으로 알고 있습니다.

원래는 @Controller에다가 필요한 메소드에만 @ResponseBody를 붙여서 사용하다가, RESTful API에 해당하는 컨트롤러에는 편리하게 활용할 수 있게끔 하기 위해 @RestController가 나온 것으로 알고 있습니다.

2024-07-06 12:51 UTC, minsu-cnu commented on src/main/java/gift/product/controller/AdminController.java
>      }
LoginMember는 사용자가 서버에 어떤 자원에 대한 DB CRUD를 요청했을 때, 해당 요청을 보낸 회원의 정보를 레포지토리 계층까지 보냄으로써, 다른 회원 것은 건드리지 않고 해당 회원에 대한 위시리스트 상품만을 조작하게 하기 위한 dto입니다.

그런데 조언 주신 것을 보고 확인해보았는데, 현재 비즈니스 로직에서는 이메일이 중복되는 경우가 없다고 가정했기 때문에 회원을 식별하는데에는 id도 가능하고 이메일도 가능한 상황입니다.

그래서 id나 이메일 둘 중 하나만 dto로 보내도 되고, 말씀 주신 대로 성능 측면에서 좀 더 나은 id를 보내는게 맞는 것 같습니다. 다행히 현재 로직은 id를 보내고 있는데, 문제는 불필요한 이메일 값도 같이 보내고 있습니다. 이 부분은 리뷰 반영하여 제거하겠습니다!

2024-07-06 12:51 UTC, minsu-cnu commented on src/main/java/gift/product/controller/AdminController.java
> +    public ResponseEntity<?> loginSuccess(@RequestParam("accessToken") JwtResponse jwtResponse, HttpServletResponse response) {
조언 감사합니다! 반영하겠습니다.

2024-07-06 12:51 UTC, minsu-cnu commented on src/main/java/gift/product/controller/ProductController.java
>          return ResponseEntity.ok().build();
input으로 받은 id에 해당하는 상품이 없는 경우, 또는 해당하는 상품이 존재하지만 로그인 한 사람의 상품이 아닌 경우 모두 레포지토리의 findById를 활용하여 유효성 검증을 할 수 있다고 판단하여, 해당 검증 및 예외 처리를 조회, 수정, 삭제 기능에 대해 추가해보았습니다.

예외 발생 시, 특정 상품이 다른 사용자의 위시리스트에 있다는 것을 숨기기 위해 상태코드를 404로 하였습니다. 또한 같은 이유로 상태 메시지도, 상품이 있지만 다른 사용자의 것일 경우에 똑같이 상품이 없다는 에러 메시지를 응답하도록 구현했습니다.

2024-07-06 12:51 UTC, minsu-cnu commented on src/main/java/gift/product/dto/AdminProductDto.java
> +}
감사합니다!

2024-07-06 12:52 UTC, minsu-cnu commented on src/main/java/gift/product/model/Member.java
> +}
해당 부분 반영하고, 추가로 생성자 체이닝을 적용해보았습니다!

2024-07-06 12:52 UTC, minsu-cnu commented on src/main/java/gift/product/repository/AuthRepository.java
> +    }
해당 부분 반영하여, 긍정으로 변경하였는데 변수 할당 후 단순 리턴하고 있는 구조가 되어서, 리턴문에 표현식을 모두 담도록 리팩토링을 하였습니다.

2024-07-06 12:52 UTC, minsu-cnu commented on src/main/java/gift/product/repository/ProductRepository.java
>              }
말씀해주신 SimpleJdbcInsert를 활용하여, 기존에 KeyHolder와 PreparedStatementCreator를 활용하던 복잡한 save 메소드 로직을 간단한 구조로 리팩토링할 수 있었습니다. 또한 AuthRepository의 registerMember도 SimpleJdbcInsert를 활용하여 간단하게 리팩토링해보았습니다.

2024-07-06 16:15 UTC, jjongwa commented on src/main/java/gift/product/model/Member.java
> +}
오 아주 좋습니다! 👍👍

2024-07-06 16:19 UTC, jjongwa approved these changes
리뷰 반영 잘 해주셨어요!  
지난 1주차보다 고민의 흔적이 물씬 드러나는 코드였습니다~! 💯 

이번 주차 미션은 이만 머지하겠습니다! 남은 주말 푹 쉬고 3주차에서 만나요~!

2024-07-06 16:19 UTC, merged