충남대 BE_이동현 2주차 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #350
Opened 2024-07-05 08:11 UTC by Thornappl2

- deprecated된 메서드 및 기능들이 많아, 이를 수정하는 것이 너무 오래 걸렸습니다.
- 공식 문서를 참조해가며 코드를 짜 보았지만, 토큰 관련 기능 구현에서 오류가 너무 많이 발생했습니다.
- 1단계 피드백을 최대한 반영하였지만, 마감 시간이 촉박하여 급하게 2단계를 진행하였습니다.

2024-07-06 01:52 UTC, ksy90101 requested changes
안녕하세요~
이번 미션의 목표는 시큐리티 없이 인증/인가를 구현해보는게 큰 목표입니다.
한번 시큐리티를 제거하고 인증/인가를 구현해보시면 어떨까요?
해당 변경사항이 클거 같으니, 이것만 리뷰를 남기고 차후 다시 한번 더 볼게요~
홧팅입니다!

2024-07-06 01:52 UTC, ksy90101 commented on build.gradle
> +    //implementation 'org.springframework.security:spring-security-config:5.6.0' // 2-2
주석은 제거해도 될거 같습니다.

2024-07-06 01:52 UTC, ksy90101 commented on src/main/java/gift/config/SecurityConfig.java
> +@EnableWebSecurity
이번 미션의 목표는 시큐리티 없이 인증/인가를 구현해보는게 큰 목표입니다.
한번 시큐리티를 제거하고 인증/인가를 구현해보시면 어떨까요?

2024-07-07 13:37 UTC, Thornappl2 commented on src/main/java/gift/config/SecurityConfig.java
> +@EnableWebSecurity
넵 제거하고 다시 구현해보겠습니다.

2024-07-07 13:37 UTC, Thornappl2 commented on build.gradle
> +    //implementation 'org.springframework.security:spring-security-config:5.6.0' // 2-2
확인했습니다!

2024-07-09 03:34 UTC, Thornappl2 commented
현재 코드의 많은 수정이 있었으나, 회원가입 및 로그인 기능에서 403, 500 등의 에러가 자꾸 발생합니다.
많은 수정을 거쳤으나, 에러가 해결되지 않아 코드 리뷰를 부탁드립니다.

2024-07-09 05:46 UTC, Thornappl2 commented
resolver 추가 후 여러 가지 수정을 통해 해결하였습니다.
원인은 application.properties에 등록해두었던 시크릿 키의 길이가 512바이트보다 짧은 것이 문제였습니다.
따라서, 시크릿 키의 길이를 늘려주어 해결하였습니다.

2024-07-09 14:52 UTC, ksy90101 requested changes
JPA는 3주차 미션입니다.
2주차미션은 JPA를 제거하고 요청주시면 좋을거 같아요 ㅠㅠ
홧팅입니다.

2024-07-09 14:52 UTC, ksy90101 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
jpa는 3주차에 사용하니 제거하는게 좋을거 같습니다.

2024-07-09 14:52 UTC, ksy90101 commented on src/main/java/gift/model/Member.java
> +public class Member {
JPA 제거해주세요 ㅠㅠ
각 주차의 단계별 요구사항을 순차적으로 하면 좋을거 같습니다 ㅠㅠ
귀찮겠지만 제거하고 리뷰 요청 부탁드려요!!

2024-07-09 16:52 UTC, Thornappl2 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
네..알겠습니다..!

2024-07-09 16:53 UTC, Thornappl2 commented on src/main/java/gift/model/Member.java
> +public class Member {
네 알겠습니다...

2024-07-11 00:42 UTC, ksy90101 requested changes
간단한 피드백을 남겼으니 한번 확인해주세요~
궁금한게 있다면 언제든 DM주세요!

2024-07-11 00:42 UTC, ksy90101 commented on build.gradle
> +    //implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
주석은 제거해주세요!

2024-07-11 00:42 UTC, ksy90101 commented on src/main/java/gift/config/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer {
👍

2024-07-11 00:42 UTC, ksy90101 commented on src/main/java/gift/controller/MemberController.java
> +            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
ExceptionHandler를 구현해서 처리해보면 어떨까요?

2024-07-11 00:42 UTC, ksy90101 commented on src/main/java/gift/controller/MemberController.java
> +            return ResponseEntity.ok().body("{\"token\":\"" + token + "\"}");
DTO를ㅇ 만들어서 처리하는게 맞지 않을까요?

2024-07-11 00:42 UTC, ksy90101 commented on src/main/java/gift/controller/ProductController.java
> +@RequestMapping("/products")
한번 여기서도 REST API로 만들어야 하는 영역은 REST API로 만들어보시겠어요?

즉, 페이지를 보여주기 위한것은 Controller, Page 내부에서 REST하게 처리할것은 아래 wish처럼 RESTController를 쓰는거죠.

2024-07-11 00:42 UTC, ksy90101 commented on src/main/java/gift/controller/WishController.java
> +        wish.setMemberId(member.getId());
도메인 로직을 처리하는것은 Service에서 하는게 좋을거 같아요.

2024-07-11 00:42 UTC, ksy90101 commented on src/main/java/gift/model/Member.java
> +public class Member {
Setter가 필요할지 고민해보시겠어요?
Setter를 제거할수 있는 방법이 어떤게 있을지 고민해보시면 좋을거 같아요

2024-07-11 00:42 UTC, ksy90101 commented on src/main/java/gift/model/Wish.java
> +    private String productName;
ProejctName으로 해당 Product를 알수 있는건가요?
Product 객체에서 그렇다면 ProductName이 변경되버리면 어떻게 되나요?

2024-07-11 00:42 UTC, ksy90101 commented on src/main/java/gift/repository/MemberRepository.java
> +        member.setPassword(rs.getString("password"));
생성자를 쓰면 setter가 필요 없습니다!

2024-07-11 00:42 UTC, ksy90101 commented on src/main/java/gift/util/JwtUtil.java
> +            throw new IllegalArgumentException("The secret key must be at least 512 bits for HS512 algorithm.");
secret key는 우리가 제어하는것이기 때문에 굳이 에러가 필요할까요?

2024-07-11 01:10 UTC, Thornappl2 commented on src/main/java/gift/util/JwtUtil.java
> +            throw new IllegalArgumentException("The secret key must be at least 512 bits for HS512 algorithm.");
저번에 오랫동안 해결하지 못했던 오류가 secretKey의 길이가 짧아 생기는 문제였기에, 확인하고자 넣었었습니다.
삭제하겠습니다.

2024-07-11 01:32 UTC, Thornappl2 commented on src/main/java/gift/repository/MemberRepository.java
> +        member.setPassword(rs.getString("password"));
넵

2024-07-11 01:43 UTC, Thornappl2 commented on src/main/java/gift/model/Member.java
> +public class Member {
확인했습니다

2024-07-11 01:58 UTC, Thornappl2 commented on src/main/java/gift/model/Wish.java
> +    private String productName;
ProductId로 수정하였습니다.

2024-07-11 06:11 UTC, Thornappl2 commented on src/main/java/gift/controller/WishController.java
> +        wish.setMemberId(member.getId());
수정했습니다.

2024-07-11 07:17 UTC, Thornappl2 commented on src/main/java/gift/controller/MemberController.java
> +            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
수정했습니다.

2024-07-11 07:17 UTC, Thornappl2 commented on src/main/java/gift/controller/MemberController.java
> +            return ResponseEntity.ok().body("{\"token\":\"" + token + "\"}");
확인했습니다.

2024-07-11 07:19 UTC, Thornappl2 commented on src/main/java/gift/controller/ProductController.java
> +@RequestMapping("/products")
확인했습니다.

2024-07-11 07:51 UTC, ksy90101 approved these changes
이거때문에 계속 3주차가 밀릴거 같아 일단 머지할게요~
이정도면 충분히 잘 수정해주신거 같네요!
3주차에서도 뵐께요!

고생하셨습니다!!

2024-07-11 07:51 UTC, merged