충남대 BE_정현서 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #353
Opened 2024-07-05 08:27 UTC by hynseoj

아직 진행 중입니다... 폼 제출을 위해 먼저 PR 생성합니다.........................

2024-07-06 01:35 UTC, ksy90101 requested changes
2단계가 머지된 뒤에 리뷰 남길게요!
2단계의 코드들이 아직 많이 남아 있어서 리뷰하는데 조금 어렵네요.
2단계 진행을 먼저 해주시면 좋을거 같습니다~
2단계 완료되면 해당 3단계 미션 리뷰 요청주세요!

2024-07-06 05:52 UTC, ksy90101 requested changes
전체적으로 공통 로직들을 잘 묶어주셨네요 👍 
간단한 피드백을 남겼으니 확인해주시면 좋을거 같습니다.
언제든 질문이 있다면 DM주세요!

2024-07-06 05:52 UTC, ksy90101 commented on src/main/java/gift/config/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer {
👍

2024-07-06 05:52 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/controller/WishlistRestController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(wishlistService.readAll(user));
```suggestion
        return ResponseEntity.ok(wishlistService.readAll(user));
```
이 부분은 이렇게 써도 똑같습니다!

2024-07-06 05:52 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/controller/WishlistRestController.java
> +        return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
```suggestion
        return ResponseEntity.noContent();
```
여기도요!

2024-07-06 05:52 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/dto/WishItemDto.java
> +    Long userId,
인증인가로 인해 해당 userId를 알수 있는데 WishItem에 userId를 넣는게 어떤 이점이 있을까요>?

2024-07-06 05:52 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/entity/WishItem.java
> +    Product product;
이렇게 되면, 실제 WishItem을 SQL 쿼리로 찾아올때 이건 null 아닌가요?

2024-07-06 05:52 UTC, ksy90101 commented on src/main/resources/db/h2/schema.sql
> +      UNIQUE (user_id, product_id)
👍

2024-07-06 05:52 UTC, ksy90101 commented on src/main/java/gift/util/LoginUserArgumentResolver.java
> +        if ((splitField.length != 2) || (!splitField[0].equals("Bearer"))) {
2라는 것이 어떤 의미인지 알기거 어려운거 같아요.
아울러 "Bearer"도 어떤 의미인지요.

이런 경우 상수를 통해 의미전달을 하면 좋을거 같습니다.

2024-07-07 11:40 UTC, hynseoj commented on src/main/java/gift/domain/wishlist/dto/WishItemDto.java
> +    Long userId,
말씀하신대로 인증을 사용하면 userId를 전달할 필요가 없을 것 같습니다!

2024-07-07 11:49 UTC, hynseoj commented on src/main/java/gift/domain/wishlist/entity/WishItem.java
> +    Product product;
넵 그래서 쿼리와 별도로 객체를 가져와서 생성해주고 있습니다.
`WishlistDao`에서 user는 인증 정보를 통해 넣어주고, product는 쿼리로 찾은 product_id를 이용해 `ProductDao`의 `findById` 메서드로 객체를 가져와 WishItem을 생성하고 있습니다!

2024-07-07 11:50 UTC, hynseoj commented on src/main/java/gift/util/LoginUserArgumentResolver.java
> +        if ((splitField.length != 2) || (!splitField[0].equals("Bearer"))) {
네 반영하겠습니다!

2024-07-07 12:10 UTC, hynseoj commented on src/main/java/gift/domain/wishlist/controller/WishlistRestController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(wishlistService.readAll(user));
두 방식 중 어느 것을 사용해도 상관없을까요? 선호하시는 방식이 있는지 궁금합니다!

2024-07-08 05:39 UTC, hynseoj commented
피드백 주신 부분 수정하고 테스트 코드 조금 작성해보았습니다.
아직 테스트 코드 작성하는 게 익숙하지 않아서 부족한 부분이 많은 것 같아 앞으로 과제 진행하면서 더 구조적으로 수정해보려고 합니다...!

2024-07-08 05:41 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/controller/WishlistRestController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(wishlistService.readAll(user));
네 저는 제안드린 방식이 가능하면 최대한 제안드린 방식을 쓰는편이에요.
인자보다 메서드가 훨씬더 보기가 좋아서요 ㅎㅎ

이건 취향차이일거 같습니다~

2024-07-08 05:46 UTC, ksy90101 approved these changes
2주차 미션 고생 많으셨어요.
간단한 피드백을 더 남기긴 했지만 3주차 미션전에 한번 확인해보시면 좋을거 같습니다~
3주차 홧팅입니다!

2024-07-08 05:46 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/dao/WishlistDao.java
> +                return wishItemDto.toWishItem(user, product);
Join을 쓴다면 한번에 찾아올수 있지 않을까요?

2024-07-08 05:46 UTC, ksy90101 commented on src/test/java/gift/domain/user/controller/UserRestControllerTest.java
> +    void login() throws Exception {
어떤건 DisplayName으로 설명되어 있고 어떤건 설명이 안되어 있네요.

DisplayName을 쓰지 않는다면 메서드명이라도 테스트 케이스의 의미를 전달하면 좋을거 같습니다.

2024-07-08 05:46 UTC, ksy90101 commented on src/test/java/gift/domain/user/controller/UserRestControllerTest.java
> +        String user = "{ \"name\": \"testUser3\", \"email\": \"test3@test.com\", \"password\": \"test123\" }";
https://subray.tistory.com/m/170

이런식으로 ObjectMapper를 쓰면 실제 객체 DTO를 통해 쉽게 테스트가 가능하기도 합니다~

2024-07-08 05:46 UTC, ksy90101 commented on src/main/java/gift/domain/user/service/UserService.java
>          return jwtProvider.generateToken(user);
(질문)
signUp일떄도 토큰을 리턴하는 이유가 있나요?

서비스가 회원가입을 완료하면 바로. 로그인이 되는 형식인가요?

2024-07-08 05:46 UTC, merged

2024-07-08 05:49 UTC, hynseoj commented on src/main/java/gift/domain/wishlist/dao/WishlistDao.java
> +                return wishItemDto.toWishItem(user, product);
아하 맞습니다! 3주차 미션 진행하면서 수정해보겠습니다!

2024-07-08 05:49 UTC, hynseoj commented on src/test/java/gift/domain/user/controller/UserRestControllerTest.java
> +    void login() throws Exception {
넵!!

2024-07-08 05:50 UTC, hynseoj commented on src/main/java/gift/domain/user/service/UserService.java
>          return jwtProvider.generateToken(user);
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/90139789/d9554381-2f38-4491-8684-18f8d737af44)

문서의 응답이 토큰을 리턴하는 형태이길래 저도 생각을 해보았는데, 말씀하신 것처럼 바로 로그인이 되는 형식이라고 판단했습니다!