부산대 BE_김동현 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #357
Opened 2024-07-05 08:33 UTC by donghyun5434

2024-07-06 12:44 UTC, jadie0319 requested changes
2주차 미션하시느라 고생하셨습니다!
몇가지 코멘트 남겨놨으니 확인 부탁드려요!

2024-07-06 12:44 UTC, jadie0319 commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +        ErrorResponse errorResponse = new ErrorResponse(combinedErrorMessage);
ExceptionHandler 에서 ErrorResponse 를 사용해  응답값을 통일하게 전달해주는 것 좋네요! :)

2024-07-06 12:44 UTC, jadie0319 commented on src/main/java/gift/controller/UserController.java
> +    public ResponseEntity<UserResponseDto> registerUser(@RequestBody UserRequestDto requestDto){
dto 사용 좋습니다.

2024-07-06 12:44 UTC, jadie0319 commented on src/main/java/gift/dto/UserRequestDto.java
> +    public User toEntity(){
dto 를 entity 로 변경하는 로직이 dto 에 있는게 적절할까요?
아니면 entity 에 있는게 적절할까요??

2024-07-06 12:44 UTC, jadie0319 commented on src/main/java/gift/repository/UserRepository.java
> +public interface UserRepository {
인터페이스 설계 좋습니다! :)

2024-07-06 12:44 UTC, jadie0319 commented on src/main/java/gift/controller/GlobalExceptionHandler.java
controller 패키지와는 어울리지 않은 것 같아요. 다른 패키지로 이동시켜볼까요?

2024-07-06 12:44 UTC, jadie0319 commented on src/main/java/gift/service/UserService.java
> +    public boolean authenticate(String email,String password){
반환값을 사용하지 않으니 반환 타입을 변경하는게 어떨까요?

2024-07-06 12:44 UTC, jadie0319 commented on src/main/java/gift/service/JwtProvider.java
> +public class JwtProvider {
토큰 생성 하는 로직 잘 구현하셨습니다.

2024-07-06 12:44 UTC, jadie0319 commented on src/main/java/gift/service/ProductService.java
> +    }
상품이 없을 때 예외처리 로직이 필요할 것 같아요 :)

2024-07-06 12:51 UTC, jadie0319 commented on src/main/java/gift/controller/UserController.java
> +    @PostMapping("/register")
register 라는 단어가 꼭 필요할까요??

2024-07-07 07:08 UTC, donghyun5434 commented on src/main/java/gift/controller/GlobalExceptionHandler.java
exception으로 옮겼습니다!

2024-07-07 07:08 UTC, donghyun5434 commented on src/main/java/gift/service/UserService.java
> +    public boolean authenticate(String email,String password){
void로 변경하였습니다.

2024-07-07 09:44 UTC, jadie0319 reviewed
3단계 코멘트 입니다!
피드백 확인 부탁드려요!

2024-07-07 09:44 UTC, jadie0319 commented on src/main/java/gift/controller/WishController.java
> +    public ResponseEntity<List<WishResponseDto>> WishList(@RequestHeader("Authorization") String fullToken){
메서드 명은 보통 소문자로 시작합니다

2024-07-07 09:44 UTC, jadie0319 commented on src/main/java/gift/controller/WishController.java
> +    @PatchMapping("/{productId}")
PatchMapping 을 사용하신 이유가 있으신가요?

2024-07-07 09:44 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +        User user = userRepository.findByEmail(userEmail).get();
아래와 같이 orElseThrow 해줘도 될 것  같아요!

2024-07-07 09:44 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +        User user = userRepository.findByEmail(userEmail)
userRepostiory.findByEmail() 메서드가 중복으로 많이 쓰이고 있어요. 메서드 분리를 통해 코드 중복을 제거해볼까요?

2024-07-07 09:44 UTC, jadie0319 commented on src/main/java/gift/repository/WishRepository.java
> +public interface WishRepository {
인터페이스 생성 잘 하셨습니다 :)

2024-07-07 09:44 UTC, jadie0319 commented on src/main/java/gift/service/ProductService.java
> +    public ProductService(@Qualifier("productRepositoryImpl") ProductRepository productRepository){
Autowired 와 Qualifier 제거 하셔도 될 것 같아요 :)

2024-07-07 09:44 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +            .orElseThrow(()->new UserNotFoundException("해당 email을 가진 user가 존재하지 않습니다."));
상수는 변수로 빼주면 어떨까요?
또는 enum 이나 class 로 분리해보는 것도 고민해보시면 좋을 것 같아요 :)

2024-07-07 09:44 UTC, jadie0319 commented on src/main/java/gift/controller/WishController.java
> +    @DeleteMapping("/{productId}")
위시리스트 생성이나 삭제시 productId 를 pathVariable 로 받아야 할까요?

2024-07-07 10:21 UTC, donghyun5434 commented on src/main/java/gift/controller/WishController.java
> +    public ResponseEntity<List<WishResponseDto>> WishList(@RequestHeader("Authorization") String fullToken){
수정했습니다!

2024-07-07 10:24 UTC, donghyun5434 commented on src/main/java/gift/controller/WishController.java
> +    @PatchMapping("/{productId}")
REST 원리를 따르기 위하여 사용했습니다.
자원에 대한 행위를 http method로 나타낸다고 알고있습니다.
리소스 일부를 업데이트하기 위해서 patch 메서드를 사용하였습니다!

2024-07-07 10:25 UTC, donghyun5434 commented on src/main/java/gift/service/WishService.java
> +        User user = userRepository.findByEmail(userEmail).get();
시간이 없어서 에러 처리를 미처 마무리하지 못 했는데 orElseThrow를 사용하여 마무리하겠습니다!!

2024-07-07 10:25 UTC, donghyun5434 commented on src/main/java/gift/service/WishService.java
> +        User user = userRepository.findByEmail(userEmail)
넵!!

2024-07-07 10:25 UTC, donghyun5434 commented on src/main/java/gift/repository/WishRepository.java
> +public interface WishRepository {
감사합니당

2024-07-07 10:25 UTC, donghyun5434 commented on src/main/java/gift/service/ProductService.java
> +    public ProductService(@Qualifier("productRepositoryImpl") ProductRepository productRepository){
넵!

2024-07-07 10:32 UTC, donghyun5434 commented on src/main/java/gift/service/WishService.java
> +            .orElseThrow(()->new UserNotFoundException("해당 email을 가진 user가 존재하지 않습니다."));
변수로 바꿨습니당

2024-07-07 10:34 UTC, donghyun5434 commented on src/main/java/gift/controller/WishController.java
> +    @DeleteMapping("/{productId}")
body로 받아서 DTO로 역직렬화하는 방법도 가능할 것 같습니다

2024-07-07 22:16 UTC, jadie0319 approved these changes
2주차 미션하시느라 고생하셨습니다!
3주차 미션을 위해 머지하겠습니다!.
코멘트 드린건 3주차 미션에 반영해주세요. 3주차도 화이팅 하세요!

2024-07-07 22:16 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +    private final String NOT_FOUND_USER_BY_EMAIL_MESSAGE = "해당 email을 가진 user가 존재하지 않습니다";
변수로 분리하니 한눈에 보여 좋네요.
다른 클래스에서도 공통으로 쓰이는 변수라면 enum 이나 메시지만 저장하는 클래스로 분리해도 좋을 것 같아요 :)

2024-07-07 22:17 UTC, merged