충남대 BE_박서현 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #360
Opened 2024-07-05 08:34 UTC by sseooh

2024-07-05 16:52 UTC, jjongwa requested changes
현재 0, 1, 2, 3 단계의 커밋이 모두 포함되어 있어요!

먼저 1단계 PR에서 confilct를 해결하고 2, 3 단계의 커밋은 여기 3단계 PR로 모아서 다시 리뷰 요청해 주세요~!

2024-07-06 16:14 UTC, jjongwa requested changes
2, 3단계까지 잘 구현해 주셨어요! 👍👍 

간단한 리뷰 정도만 남겼고, 전체적으로 사용하지 않는 클래스/메서드와 지난 단계에서 드렸던 리뷰 사항들에 대한 정리가 필요할 것 같아요~! 
주말에도 고생 많으십니다! 조금만 더 힘내봐요!!

2024-07-06 16:14 UTC, jjongwa commented on src/main/java/gift/controller/WishController.java
> +
생성자 주입을 사용하는걸 권장해 드립니다~!

2024-07-06 16:14 UTC, jjongwa commented on src/main/java/gift/controller/WishController.java
> +    }
Controller에서 해당 구문을 catch하지 않는 방식은 어떻게 생각하시나요?

만약 해당 Controller에서 호출하는 Service method에서 여러 가지의 예외를 던지는 상황이 발생한다면 Controller에서 이를 각각 다른 Exception으로 catch해야 할까요?
(틀렸다는게 아닙니다~! 서현님의 생각을 그대로 말해주세요!)

2024-07-06 16:14 UTC, jjongwa commented on src/main/java/gift/controller/WishController.java
> +    }
반환할 contents가 없다면 와일드카드 대신 Void를 사용하는 방법도 있습니다!
```suggestion
    public ResponseEntity<Void> removeWish(@PathVariable Long wishId, @LoginMember Member member) {
        wishService.removeWish(wishId);
        return ResponseEntity.noContent().build();
    }
```

2024-07-06 16:14 UTC, jjongwa commented on src/main/java/gift/dao/MemberDAO.java
> +    private RowMapper<Member> memberRowMapper() {
이런 식으로 줄여볼 수도 있겠네요.!
```suggestion
private RowMapper<Member> memberRowMapper() {
        return (rs, rowNum) -> new Member(
                rs.getLong("id"),
                rs.getString("email"),
                rs.getString("password")
        );
    }```

2024-07-06 16:14 UTC, jjongwa commented on src/main/java/gift/domain/Product.java
> +
setter가 다시 생겼네요.! 
현재 구조상으로 봤을 땐 사용하지 않는 것 같은데, 추가한 이유가 있을까요?

2024-07-06 16:14 UTC, jjongwa commented on src/main/java/gift/dao/WishDAO.java
> +    }
이 부분도 굳이 setter를 사용하지 않고 이렇게 처리할 수 있을 것 같아요!

```suggestion
    private Wish mapRowToWish(ResultSet rs) throws SQLException {
        return new Wish(
                rs.getString("product_name"),
                rs.getLong("member_id"));
    }
```

2024-07-06 16:14 UTC, jjongwa commented on src/main/java/gift/dto/WishRequest.java
> +}
현재 이 클래스는 사용하지 않고 있네요!

Member와 WishController에서 각각 이런 방식의 dto로 정보를 주고받는 방식으로 리팩토링 해보면 좋을 것 같아요!

2024-07-06 16:14 UTC, jjongwa commented on src/main/java/gift/service/MemberService.java
요 부분도 마찬가지입니다!

```
public class MemberService {
    
    private final MemberDAO memberDAO;
    private final JwtService jwtService;
    
    public MemberService(MemberDAO memberDAO, JwtService jwtService) {
        this.memberDAO = memberDAO;
        this.jwtService = jwtService;
    }
```

2024-07-07 07:54 UTC, sseooh commented on src/main/java/gift/controller/WishController.java
> +    }
Controller에서 예외를 catch하지 않고 service 계층에서 던지도록 하면 예외 처리 로직을 한 곳에서 관리할 수 있을 것 같습니다! 아니면 따로 예외 처리를 담당하는 핸들러를 구현하는 것도 좋을 것 같다고 생각해요. 이번에는 해당 컨트롤러에서 '위시리스트에 담기 성공' 또는 '위시리스트에 담기 실패' 두 가지 결과로만 나온다고 생각을 해서, 예외 처리 로직을 따로 구현하지 않아도 괜찮을 것 같다고 생각했습니다.

예외 처리를 담당하는 핸들러를 따로 구현하는 것이 더 좋은가요??

2024-07-07 07:56 UTC, sseooh commented on src/main/java/gift/domain/Product.java
> +
setter를 제거한 뒤 다시 코드를 실행해보니, product가 사용자가 입력한 값 그대로 저장되지 않고, null 값으로 인식을 하더라구요 🥹

다시 setter를 넣어준 뒤 실행했더니 정상적으로 동작했습니다. 그 이유는 아직 정확하게 모르고 있어서, 좀 더 공부가 필요할 것 같습니다..

2024-07-07 14:31 UTC, jjongwa commented on src/main/java/gift/controller/WishController.java
> +    }
규모에 목적에 따라 다를 것 같아요!

`이번에는 해당 컨트롤러에서 '위시리스트에 담기 성공' 또는 '위시리스트에 담기 실패' 두 가지 결과로만 나온다고 생각을 해서, 예외 처리 로직을 따로 구현하지 않아도 괜찮을 것 같다고 생각했습니다.`

다음과 같이 두 가지 경우만 나온다고 가정하고, 나머지 모든 예외를 하나로 묶는다고 한다면 지금 방식도 나쁘지 않다고 생각합니다!

2024-07-07 14:34 UTC, jjongwa commented on src/main/java/gift/domain/Product.java
> +
`@ModelAttribute` 때문에 그런 것 같네요~! 관련된 키워드는 Java의 Reflection입니다!

2024-07-07 14:53 UTC, jjongwa approved these changes
2주차도 수고 많으셨습니다~! 내일부턴 또 다음 주차가 진행되니 이번주 미션은 여기서 마치도록 할께요!

추가적인 리뷰도 조금 달았으니 확인해주시고, 다음 주차에서 봐요~! 🦖

2024-07-07 14:53 UTC, jjongwa commented on src/main/java/gift/controller/WishController.java
> +    public ResponseEntity<?> addWish(@RequestBody WishRequest wishRequest, @LoginMember Member member) {
요런 부분도 마찬가지로 구체적으로 타입을 명시해 주는게 좋습니다!

```suggestion
    public ResponseEntity<String> addWish(@RequestBody WishRequest wishRequest, @LoginMember Member member) {
```


예를 들어 ProductController에서도

```
public Object deleteProduct(@PathVariable("id") Long id) {
        // 요청받은 id를 가진 상품을 삭제
        productDAO.delete(id);

        return REDIRECT_URL;
    }
```

```
public String deleteProduct(@PathVariable("id") Long id) {
        // 요청받은 id를 가진 상품을 삭제
        productDAO.delete(id);

        return REDIRECT_URL;
    }
```

1번과 2번 중 당연하게 2번을 사용하는 것 처럼요!

2024-07-07 14:53 UTC, jjongwa commented on src/main/java/gift/dao/WishDAO.java
> +    private final JdbcTemplate jdbcTemplate;
지금 존재하는 모든 클래스에 `@Autowired` 는 필요 없습니다~!

2024-07-07 14:53 UTC, jjongwa commented on src/main/java/gift/domain/Product.java
> +
다음 주차도 곧바로 시작하고 하니 간단하게 알려드리자면, 
modelattribute는 해당 객체의 생성자 중 매개변수가 가장 적은 생성자를 기본으로 사용하게 됩니다.
그럼 상품 정보를 불러올 때, 우선 new Product() 로 빈 객체를 불러오게 되고, 그 후에 각각의 필드를 setter로 채워주는 형식입니다.

이를 해결하려면 우선 Product에서 기본 생성자를 제거하고, controlller 단에서는 dto를 통해 아래 레이어와 소통하는 방식이 있어요!


현재 구조에서는 Product라는 클래스가 모든 레이어에서 사용되고 있는데요, 그러다보면 도메인이라는 계층 자체의 의미가 없어지게 됩니다!

지금은 조금 어렵고 이해가 가지 않을지도 모르지만, 결국 setter 사용을 지양하는 습관을 가져가며 구현하다 보면 자연스럽게 체득되게 될 거라고 생각해요! 그래서 앞으로 이러한 연습을 계속 해보는 걸 추천드립니다~!

2024-07-07 14:53 UTC, merged