경북대 BE_김건 2주차 과제(1~3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #361
Opened 2024-07-05 08:35 UTC by gunGeongun

## 과제 진행 소감 
***
이번 2주차 과제를 수행하면서 많은 어려움을 느꼈습니다.
웹 개발 경험이 거의 없는 제 상태에서는 토큰이란건 어떻게 발급하는 것이고 이걸 헤더에 어떻게 담는지  또 이걸 이용해서 어떻게 인증을 수행할 것인지 모든 것이 감이 안잡혀서 막막했습니다. 그렇게 하나하나 다 구글링하며 찾아보고 세션방식 토큰방식 .. stateless .. jwt .. 등등을 학습해나갔습니다. 아직까지도 가볍게 알고있는 느낌이라 시간을 내어 한번 더 깊게 학습해보며 인증 인가 시스템에 대해 알아가보려합니다.
코드를 작성하면서도 하면할수록 점점 코드 구조가 복잡해지는 것 같고 올바른 방향으로 코드를 작성하고있는지에 대한 의구심이 끊임없이 지속되었습니다. 그래서 일단 요구된 기능 구현에 초점을 두고 추후에 리팩토링을 하며 코드 구조를 다듬어가는 방식으로 진행하였습니다. 코드를 PR제출한 뒤에도 주말 동안 멘토님의 리뷰를 통해서든, 스스로 코드를 살펴보고 구조적인 문제를 찾든 계속 코드를 분석하며 학습해나가겠습니다.

## 과제 진행중 궁금한 점
***
1. 현재는 위시리스트 기능을 하는 테이블을 user_gifts에서 userid와 giftid를 참조해서 매핑하는 방식으로 정의하여 사용하고있는데 , 이 방식말고 더 나은 방법이 있는지 궁금합니다. 
2. 지금 파일들이 계속 늘어나 복잡하게되었는데 model 패키지 내부에 gift,user,wish 패키지를 만들어서 model/gift/GiftDao , model/user/UserRequest 와 같이 관리해도 되는지 궁금합니다.

2024-07-05 16:35 UTC, MangKyu requested changes
안녕하세요ㅎㅎ 이번 과제도 고생 많으셨습니다! 수정 필요한 부분들에 대하여 코멘트 남겨드렸습니다! 천천히 수정 작업 진행해주세요:)
이번에도 마찬가지로 질문 주셨던 부분들에 대해 답변 남겨드리겠습니다!

### 위시리스트 테이블
`user_gifts`와 같이 서로 다른 두 테이블의 관계를 맺어주는 테이블은 실무에서도 흔히 사용되는 패턴이며, 올바르게 구성했다고 볼 수 있습니다! 


### 패키지 분리 관련
시스템이 계속해서 진화함에 따라 적합한 아키텍처 패턴이 언제든지 바뀔 수 있습니다! 따라서 건님께서 현재 구조 상으로 model 하위에 gift,user,wish 패키지를 만드는 것이 관리에 용이하다고 느끼시면 그렇게 나누셔도 됩니다!
패키지를 나누는 방법은 너무 다양한데요, 말씀해주신대로도 나눌 수 있고, 또는 dto 관련 클래스들은 별도의 패키지로도 분리하는 방법이 있습니다ㅎㅎ

2024-07-05 16:35 UTC, MangKyu commented on build.gradle
> +    implementation 'javax.xml.bind:jaxb-api:2.3.1'
해당 의존성은 어떠한 사유로 추가되었을까요~?

2024-07-05 16:35 UTC, MangKyu commented on src/main/java/gift/config/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
인터셉터를 시도하신 부분 좋네요! 👍

2024-07-05 16:35 UTC, MangKyu commented on src/main/java/gift/config/AuthInterceptor.java
> +            if (user.isPresent()) {
Optinal.isPresent를 호출하는 것은 잘못된 Optional 활용을 하고 있다는 일종의 신호로 볼 수 있습니다!
올바른 Optional 사용을 위해 [해당 포스팅](https://mangkyu.tistory.com/203) 참고 부탁드립니다ㅎㅎ

2024-07-05 16:35 UTC, MangKyu commented on src/main/java/gift/controller/UserController.java
> +    @Autowired
다른 부분과 마찬가지로, 해당 부분도 일관성 있게 생성자 주입을 사용하는 것이 좋을 것 같습니다ㅎㅎ

2024-07-05 16:35 UTC, MangKyu commented on src/main/java/gift/controller/UserController.java
> +        user.setEmail(userRequest.getEmail());
setter를 이용한 값 할당 보다는 생성자를 통해 값을 할당해주는 것이 어떨까요~?
setter를 열어두게 되면 값의 변경 위치를 추적하기가 여려워질 수 있습니다~

2024-07-05 16:35 UTC, MangKyu commented on src/main/java/gift/controller/WishListController.java
> +    public ResponseEntity<?> getGiftList(HttpServletRequest request) {
다음과 같이도 값을 가져올 수 있습니다ㅎㅎ
```suggestion
    public ResponseEntity<?> getGiftList(@RequestAttribute("user") User user) {
```

2024-07-05 16:35 UTC, MangKyu commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        Map<String, String> errors = new HashMap<>();
에러 필드들 생성해주는 부분 좋네요 👍

2024-07-05 16:35 UTC, MangKyu commented on src/main/java/gift/config/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer{
WebConfig가 2개 있는 것 같습니다! 메인에 있는 것은 지워주세요ㅎㅎ

2024-07-05 16:35 UTC, MangKyu commented on src/main/java/gift/model/UserRepository.java
> +    @Autowired
해당 부분도 생성자 주입을 통해 가져가면 좋을 것 같습니다!

2024-07-05 16:35 UTC, MangKyu commented on src/main/java/gift/model/GiftRequest.java
> +    @isKakao
제약 조건은 크게 2종류로 나눌 수 있는데요~
- 입력 데이터에 따른 유효성
- 비즈니스 정책에 따른 유효성

위의 코드 기준으로는 데이터 유효성과 비즈니스 정책이 혼합되어 있는 것 같습니다ㅎㅎ

참고로 입력 데이터 부분은 애노테이션으로 처리하고, 비즈니스 정책에 대한 부분은 비즈니스 관련 클래스(Product)에 드러나는 것이 좋은 설계인 것 같습니다 ㅎㅎ 비즈니서 정책과 관련된 부분은 코드로 드러내어 우리의 정책을 쉽게 파악할 수 있어야 합니다!

2024-07-05 16:35 UTC, MangKyu commented on src/main/java/gift/validation/IsKakaoValidator.java
> +public class IsKakaoValidator implements ConstraintValidator<isKakao, String> {
애노테이션 기반의 유효성 검사를 시도해분 부분은 좋은 것 같습니다! 다만 이러한 처리는 오히려 비즈니스 정책의 확장을 어렵게 만드는 것 같습니다! 만약 네이버 키워드도 동일한 제약 조건이 추가된다면, 애노테이션과 validator 그리고 gift 수정이 필요합니다!
만약 도메인 정책이 Gift 클래스 안에 녹아져있었다면 정책 확인과 확장 모두 수월할 것 같습니다ㅎㅎ

2024-07-06 10:48 UTC, gunGeongun commented on build.gradle
> +    implementation 'javax.xml.bind:jaxb-api:2.3.1'
javax.xm.bind:jaxb-api:2.3.1 의존성을 추가해준 이유는 저 의존성없이 로그인해서 토큰을 발급받을때
    "status": 500,
    "error": "Internal Server Error",
    "trace": "java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter\r\n\tat io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26)
    위와 같은 오류가 발생하여 검색해서 알아보니 최근 jdk에는 java EE API 가 포함되어있지 않다라고하여 의존성을 추가해주니 문제가 해결되었습니다.

2024-07-06 10:52 UTC, gunGeongun commented on src/main/java/gift/config/AuthInterceptor.java
> +            if (user.isPresent()) {
감사합니다. orElseX()문을 적극 활용해보겠습니다.

2024-07-06 10:56 UTC, gunGeongun commented on src/main/java/gift/controller/UserController.java
> +    @Autowired
다 생성자주입으로 통일시키려고했는데 놓친부분이 있었네요. 감사합니다.

2024-07-06 10:59 UTC, gunGeongun commented on src/main/java/gift/controller/WishListController.java
> +    public ResponseEntity<?> getGiftList(HttpServletRequest request) {
이런 방법도 있었던건 몰랐네요.이게 더 가독성 측면에서 좋은 방법인 것 같습니다!

2024-07-06 10:59 UTC, gunGeongun commented on src/main/java/gift/config/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer{
머지 충돌과정에서 실수로 중복되는 파일들이 몇개 추가되었네요. 수정하겠습니다!

2024-07-06 12:51 UTC, gunGeongun commented on src/main/java/gift/controller/UserController.java
> +        user.setEmail(userRequest.getEmail());
그렇네요 나중에 코드 라인이 더 많아지고 구조가 더 복잡해지면 setter로 값을 세팅하는 방법은 위치 추적이 어려워질 것 같습니다. 습관적으로 setter를 사용하게 되었는데 혹시 setter를 사용하는 적정한 때가 따로 있는지 아니면 그냥 항상 생성자로 값을 세팅해주는 방법이 더 나은건지 궁금합니다.

2024-07-06 13:09 UTC, gunGeongun commented on src/main/java/gift/validation/IsKakaoValidator.java
> +public class IsKakaoValidator implements ConstraintValidator<isKakao, String> {
정규식으로 충분히 해결가능한 검증문이었는데 , 너무 어렵게 접근했던 것 같습니다. 커스텀 애노테이션을 시도해보면서도 굳이? 라는 생각이 들었었는데 말씀해주신대로 확장성에도 애노테이션보단 클래스자체에 표시해주는 것이 좋을 것 같습니다.

2024-07-06 13:13 UTC, gunGeongun commented on src/main/java/gift/model/GiftRequest.java
> +    @isKakao
dto 역할을 하는 GiftRequest와 같은 입력데이터 클래스에는 입력데이터 유효성 검증을 넣고 "카카오 문구는 MD와 협의 후에 사용하세요" 같은 비즈니스 정책 상 유효성 검사는 Gift나 Product같은 비즈니스와 연관된 클래스에도 같이 표기를 해주는게 좋다는 걸로 이해했는데 맞나요?

2024-07-06 15:03 UTC, MangKyu commented on build.gradle
> +    implementation 'javax.xml.bind:jaxb-api:2.3.1'
구버전의 jjwt 라이브러리를 사용하고 계셔서 그런 것 같네요ㅎㅎ;;
일단 이번 과제의 목적은 아니니까 넘어가시죠~

2024-07-06 15:07 UTC, MangKyu commented on src/main/java/gift/controller/UserController.java
> +        user.setEmail(userRequest.getEmail());
저는 기본적으로 setter가 없는 상태로 개발을 진행합니다ㅎㅎ 그러다가 필요해지면 setter가 아닌 의미 있는 이름을 사용합니다! 이렇게하면 무분별한 setter가 아닌, 의미있는 변경을 필요한 지점에서만 가질 수 있습니다!
예를 들어 사용자를 비활성화 처리해야 하는 경우, 
이러한 setter를 통한 변경이 아닌
```java
user.setStatus(UserStatus.DISABLED);
```

다음과 같은 의미있는 메서드, 도메인을 표현하는 메서드를 선언합니다ㅎㅎ
(disable 내부에서 상태를 변경함)
```java
user.disable();
```

가급적 setter를 사용하지 않도록 생성자 주입이나 위와 같은 의미있는 메서드를 사용하는 것이 좋습니다!

2024-07-06 15:07 UTC, MangKyu commented on src/main/java/gift/model/GiftRequest.java
> +    @isKakao
정확하게 이해하셨습니다ㅎㅎ 같이 표현할지 혹은 도메인에만 표현할지는 선택입니다만, 도메인에만 표현해도 충분하지 않을까 생각합니다!

2024-07-06 15:08 UTC, MangKyu commented on src/main/java/gift/validation/IsKakaoValidator.java
> +public class IsKakaoValidator implements ConstraintValidator<isKakao, String> {
그래도 쉽지 않으셨을텐데, 학습 하시면서 많은 도움이 되었을 것 같네요! 고생많으셨습니다ㅎㅎ

2024-07-06 15:32 UTC, MangKyu requested changes

2024-07-06 15:32 UTC, MangKyu commented on src/main/java/gift/controller/WishListController.java
> +            @RequestParam(required = false, defaultValue = "1") int quantity) {
defaultValue 사용 👍

2024-07-06 15:32 UTC, MangKyu commented on src/main/java/gift/model/Gift.java
> +    @Pattern(regexp = "^(?!.*카카오).*$", message = "카카오 문구는 MD와 협의 후 사용가능합니다.")
해당 유효성 검사는 어디서 진행되고 있나요~?
객체가 값을 받아서 생성될 때(생성자) 안에서 처리하는 방법도 있습니다! 도메인 유효성은 이렇게 많이 처리합니다ㅎㅎ

2024-07-06 15:32 UTC, MangKyu commented on src/main/java/gift/service/UserService.java
> +        Optional<User> user = userRepository.findByEmail(email);
Optional이 이러한 형태로 사용된다면, null을 사용하는 것과 다를 바가 없고 오히려 메모리를 사용하여 비효율적일 수 있습니다ㅎㅎ

2024-07-07 06:35 UTC, gunGeongun commented on src/main/java/gift/model/Gift.java
> +    @Pattern(regexp = "^(?!.*카카오).*$", message = "카카오 문구는 MD와 협의 후 사용가능합니다.")
생성자에서 유효성을 검사해주는 방법도있었는데 왜 클래스 멤버변수에 애노테이션으로만 유효성 검사를 하려고했는지 모르겠네요. 일단 생성자 내에서 카카오 문구가 들어간 이름일때는 IllgalArgumentException 을 던져주도록 수정했습니다.

2024-07-07 06:39 UTC, gunGeongun commented on src/main/java/gift/controller/UserController.java
> +        user.setEmail(userRequest.getEmail());
좋은 방법을 배워가네요. 훨씬 가독성이나 유지보수측면에서 좋을 것 같습니다!

2024-07-07 07:15 UTC, gunGeongun commented on src/main/java/gift/service/UserService.java
> +        Optional<User> user = userRepository.findByEmail(email);
코드 여러곳에서 Optional를 남용하고 있었네요.  map 과 orElseGet을 사용하여 수정해보았습니다.

2024-07-07 14:08 UTC, MangKyu approved these changes
조금 더 개선이 필요한 부분들이 있지만, step2는 이쯤 하고 넘어가도록 하죠ㅎㅎ
고생많으셨습니다! 🙇

2024-07-07 14:08 UTC, MangKyu commented on src/main/java/gift/model/Gift.java
> +    private boolean isValidName(String name) {
도메인이 잘 포현되는 것 같네요! 👍

2024-07-07 14:08 UTC, merged

2024-07-07 14:11 UTC, gunGeongun commented on src/main/java/gift/model/Gift.java
> +    private boolean isValidName(String name) {
정성스러운 리뷰 감사합니다. 카테캠 교육과 함께 웹 개발 공부를 시작한 것이라 아직 알아야될 것도 많고 제가 뭘 모르는지도 모르는 경우가 많네요 ㅜ 꾸준히 학습하여 양질의 코드를 작성하도록 노력해보겠습니다. 앞으로 남은 step들도 잘 부탁드립니다!

2024-07-07 14:15 UTC, MangKyu commented on src/main/java/gift/model/Gift.java
> +    private boolean isValidName(String name) {
늦은 시간까지 너무 고생 많으셨습니다ㅎㅎ 학습할 것들도 많고 어려움도 많으실텐데, 어려움이나 궁금한 부분 있으시면 편하게 질문 남겨주세요:)