경북대 BE_배준호 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #363
Opened 2024-07-05 08:36 UTC by BaeJunH0

우선, 미구현 사항이 굉장히 많습니다!
필수 요구 사항 중 
  **위시 리스트에 등록된 상품 목록을 조회할 수 있다.
  위시 리스트에 상품을 추가할 수 있다.
  위시 리스트에 담긴 상품을 삭제할 수 있다.
** 
부분은 다 구현하였으나, Authorization: Bearer token 헤더를 이용하는 부분과 HandlerMethodArgumentResolver를 이용하는 부분은 미구현 상태입니다.
또, 1단계에서 했던 Validation을 적용해야 할 부분도 많이 보입니다 ( UserDTO, WishListDTO )
이외에도 피드백 해주실 부분있으면 마음껏 부탁드립니다..!

2024-07-05 10:52 UTC, BaeJunH0 commented
step 2 질문입니다, 로그인 성공 시 token을 주는 것은 이해를 했는데, 회원가입 시에도 token을 지급해야 하나요??

2024-07-06 06:23 UTC, lsm7179 requested changes
준호님
2,3단계 수고하셨습니다.
Jwt token은 여러회사에서도 당연하게 너무 많이 사용합니다. 꼭 구현해봤으면 좋겠네요.
피드백 남겼으니 조금 더 화이팅해보시죠.🔥👍

궁금하거나 어려운거 있으시면 편하게 DM 주세요.

2024-07-06 06:23 UTC, lsm7179 commented on src/main/java/gift/DTO/ProductDTO.java
> +public class ProductDTO {
약어를 대문자로 쓰는 경우가 있지만 약어만 있는 객체는 다 대문자가 됩니다.
그래서 ProductDto를 많이 쓰곤 합니다.
그리고 해당 Dto는 Request, Response로 나눠서 작업해보세요~
왜 나눠서 하는게 좋을까요?

2024-07-06 06:23 UTC, lsm7179 commented on src/main/java/gift/DTO/Token.java
> +    }
문자열 하나만 있는 객체에 setter가 필요할까요?
객체 생성할때 문자열을 받아서 처리해보세요~

2024-07-06 06:23 UTC, lsm7179 commented on src/main/java/gift/DTO/UserDTO.java
> +    }
사용하지 않는 setter는 지워주세요.

2024-07-06 06:23 UTC, lsm7179 commented on src/main/java/gift/service/UserService.java
> +    }
secretKey를 프로퍼티에서 받아보도록 할까요?

2024-07-06 06:23 UTC, lsm7179 commented on src/main/java/gift/controller/UserController.java
> +        Token savedToken = userService.makeToken(savedUser);
컨트롤러에서 너무 많은걸 하는거 같아요.
그리고 token과 savedToken은 언제 달라지나요?

2024-07-06 06:23 UTC, lsm7179 commented on src/main/java/gift/service/UserService.java
> +    }
토큰을 생성하는 건 userService의 책임일까요?

2024-07-06 06:23 UTC, lsm7179 commented on src/main/java/gift/controller/WishListController.java
> +        return new ResponseEntity<>(list, HttpStatus.OK);
위시리스트 목록이 많아질수록 쿼리를 계속 조회해서 부하가 일어날거 같아요.
상품 목록을 한번에 받아볼순 없을까요?

2024-07-06 06:23 UTC, lsm7179 commented on src/main/java/gift/controller/WishListController.java
> +            @RequestBody Token token
Token을 클라이언트가 탈취당하면 영구적으로 사용할수있을거같아요.
jwt 유효시간을 설정해볼까요?
그리고 header에 받아서 사용할수있게 해볼까요?

2024-07-06 06:23 UTC, lsm7179 commented on src/main/java/gift/domain/WishProduct.java
> +    }
사용자가 이메일을 수정하게되면 위시리스트도 수정해야될거같네요.
userId를 사용해볼까요?

2024-07-06 06:23 UTC, lsm7179 commented on src/main/java/gift/repository/UserRepository.java
> +    }
ddl문에서 id BIGINT GENERATED BY DEFAULT AS IDENTITY로 만들어 자동으로 채워볼까요?

2024-07-08 00:42 UTC, lsm7179 commented
> step 2 질문입니다, 로그인 성공 시 token을 주는 것은 이해를 했는데, 회원가입 시에도 token을 지급해야 하나요??

답변을 안드렸네요.
회사에 의사결정마다 다를수 있습니다.
어떤 곳은 회원가입 후에 로그인을 거치지않고 바로 토큰을 지급해서 로그인처리해줄 수 있습니다.

2024-07-08 10:56 UTC, lsm7179 approved these changes
준호님 2주차 과제 하느라 고생하셨습니다.
피드백은 3주차에 드릴게요.
3주차도 화이팅입니다~!

2024-07-08 10:58 UTC, merged