전남대 BE_나제법_2주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #368
Opened 2024-07-05 08:41 UTC by nove1080

JWT 기반의 회원 식별까지 구현된 상태입니다
위시리스트 기능을 아직 만들지 못하여서 토요일 아침까지 업데이트 하도록 하겠습니다 죄송합니다😭😭

2024-07-07 12:24 UTC, Hongdonggeon requested changes
제법님 미션 구현하느라 수고 많으셨습니다! 
요구사항에 잘 충족해주셨고, 추가로 코드도 깔끔해서 리뷰하기 편했습니다 👍
코멘트들 반영하면서 궁금한 것 있으시면 편하게 DM 주세요!

2024-07-07 12:24 UTC, Hongdonggeon commented on src/main/java/gift/authentication/filter/AuthenticationFilter.java
> +public class AuthenticationFilter extends OncePerRequestFilter {
filter를 이용하셨네요!  인터셉터를 이용하지 않고 filter로 선택하신 이유가 있을까요?
또한 OncePerRequestFilter를 이용하신 이유가 있을까요?

2024-07-07 12:24 UTC, Hongdonggeon commented on src/main/java/gift/authentication/resolver/LoginMemberArgumentResolver.java
> +        String authorization = webRequest.getHeader("Authorization");
이런 헤더명은 상수로 관리해도 좋을 것 같네요

2024-07-07 12:24 UTC, Hongdonggeon commented on src/main/java/gift/authentication/token/Token.java
> +    private String value;
final 변수로 선언해도 좋을 것 같아요

2024-07-07 12:24 UTC, Hongdonggeon commented on src/main/java/gift/domain/vo/Email.java
> +    public static Email from(String email) {
정적팩토리 메서드패턴을 선호하시네요! 정적 팩토리 메서드 패턴을 선호하신 이유가 궁금해요

2024-07-07 12:24 UTC, Hongdonggeon commented on src/main/java/gift/repository/MemberRepository.java
> +            return Optional.empty();
예외 처리후에 emtpy로 반환하는 이유가 있을까요?
optional null로 반환해도 되지 않을까해서요!

2024-07-07 12:24 UTC, Hongdonggeon commented on src/main/resources/application.yml
> +  secretkey: 994e69b6df494d3e5f48fdb32693d5c772cc35a4d4f67cce4323fe256b6caf31b666d21db4b9f974935c7900bce11947edf8e266ef87aaa176db591b220860ff
시크릿키가 github에 이렇게 공개적으로 노출되면 보안에 취약할 것 같은데요. 다른 yml 파일을 만들어서 노출되지 않도록 관리하는게 좋을 것 같아요

2024-07-07 12:24 UTC, Hongdonggeon commented on src/main/java/gift/web/dto/response/wishproduct/UpdateWishProductResponse.java
> +public class UpdateWishProductResponse {
ReadwishProductResponse와 객체 구조가 동일하네요! 
WisthProductResponse와 같이 네이밍 변경하고 공통적으로 사용해도 되지 않을까요?

2024-07-07 12:37 UTC, Hongdonggeon commented
. ArgumentResolver는 무슨 계층에 해당하나요?
ArgumentResolver를 컨트롤러에서 사용되니, 컨트롤러 계층이 가장 잘 어울리지 않을까 생각해요
argumentResolver에서 서비스를 참조할지, repository를 참조할지에 대해서도 물어보셨는데 정말 좋은 고민이라고 생각합니다! 
정답은 없겠지만 argumentResolver가 컨트롤러 계층이 가깝다고 생각이 들어서 service를 참조하는게 더 적절하지 않을까 싶어요

- wishProduct
저는 적절한 판단이었다고 생각해요! 
객체에서 모두 id만 들고 있다면 제법님이 말씀하신 것처럼 조회쿼리가 빈번해질거고 
객체에서 너무 모든 객체를 가지고 있다면 추후에 객체 연관관계를 잘 고려해야 될 거예요 
지금 설계에서 약간의 코멘트를 드리자면,
wishProduct의 product 객체가 사용되고 있는데, member 객체는 사용되고 있지 않고 연관관계의 역할만 해주고 있잖아요
이런 경우에는 wishtProduct 가 memberId 정보만 들고 있어도 됐었을 것 같다는 생각도 들긴하는 것 같아요! (하나의 의견입니다 고민한번 해주시면 좋을 것 같아요)


- 추가로 궁금한 부분인데 현업에서도 API마다 모두 다른 요청,응답 DTO를 만들어서 사용하나요?
이건 케이스마다 다를 것 같아요
모든 api마다 모두 다른 요청 응답 dto를 무조건적으로 만들어야되는 건 아니구요! api가 각각 독립적이라면 따로 dto를 관리하겠지만, 이 미션의
updateProductResponse와 readProductResponse 모두 product 도메인의 정보를 읽어오는거고 객체 구조가 동일하기 때문에 이런건 공통적으로 사용할 수 있을 것 같아요

2024-07-08 06:18 UTC, nove1080 commented on src/main/java/gift/authentication/filter/AuthenticationFilter.java
> +public class AuthenticationFilter extends OncePerRequestFilter {
> filter를 이용하셨네요! 인터셉터를 이용하지 않고 filter로 선택하신 이유가 있을까요? 

사용자 인증에 대해서 식별하는 작업을 filter로 많이 해둔걸 본 적이 있어서 생각없이 구현한 것 같습니다.
그래서 동건님의 코멘트를 보고 `filter`와 `interceptor`에 대해서 좀 찾아보았습니다.

다음은 `jakarta.servlet.Filter`의 주석의 일부입니다.
> Examples that have been identified for this design are 
> 1) Authentication Filters

다음과 같이 인증에 사용하기에 적합하다고 나와있고 사용자 요청에 대한 프로그램 실행 흐름을 보니 실제로 Interceptor 보다 앞에서 동작하기 때문에 인증되지 않은 사용자가 굳이 더 뒷단에서 걸러질 필요는 없다고 생각해보았습니다. 

![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/89574219/9519eb9b-3685-4d91-b31a-9bb91bdf9005)

그런데 제가 생각했을 때는 이런 이유만으로는 interceptor 대신 filter로 인증을 처리하자고 다른 사람을 설득하기에는 명분이 좀 부족한 것 같아서 둘의 차이에 대해 좀 더 공부를 해야할 것 같습니다

> 또한 OncePerRequestFilter를 이용하신 이유가 있을까요?

이것도 습관적으로 OncePerRequestFilter 를 구현해서 만들었습니다.
스프링 MVC 구조에 대해 먼저 공부하고나면 interceptor와 filter의 동작방식의 차이와 filter의 구현체들에 대해서 공부해볼 수 있을 것 같습니다.

p.s. 지금보니 여지껏 좀 생각없이 개발을 했던 것 같네요 ㅜㅜ 앞으로는 무언가를 선택하는 상황이 있을 때 장단을 비교해보고 다른 사람을 설득할 수 있는 수준의 근거를 가지고 생각하고 개발하겠습니다 항상 좋은 고민을 해볼 수 있는 질문을 남겨주셔서 감사합니다:)

2024-07-08 06:21 UTC, nove1080 commented on src/main/java/gift/repository/MemberRepository.java
> +            return Optional.empty();
Optional null로 반환한다는게 무슨 말인지 잘 모르겠습니다 ㅜㅜ

2024-07-08 07:05 UTC, nove1080 commented on src/main/java/gift/domain/vo/Email.java
> +    public static Email from(String email) {
이펙티브 자바라는 책에서 본 내용인데 무작정 public 생성자를 제공하는 습관을 돌아보라고 하여서 정적 팩토리 메서드를 사용해보았습니다. 아직까지 몸으로 느낀 장점은 생성자에 이름을 부여할 수 있다는 장점 밖에 체감하지 못하고 있습니다

2024-07-08 16:18 UTC, Hongdonggeon commented on src/main/java/gift/authentication/filter/AuthenticationFilter.java
> +public class AuthenticationFilter extends OncePerRequestFilter {
항상 제법님은 좋은 고민을 하시는 것 같아요 👍 
사실 Filter와 Interceptor의 역할은 거의 비슷하지만, 제가 아는대로 Filter와 인터셉터의 차이에 대해 말씀드릴게요
큰 차이는 필터는 자바스펙이고 인터셉터는 스프링 스펙이에요 
필스프링 어플리케이션을 셋팅하면 기본적으로 등록되는 필터와 인터셉터들이 있는데요
기본적으로 등록되는 필터와 인터셉터들의 성격을 보면, 필터는 스프링에 종속되지 않은 웹에 관련된 필터들이예요 (인코딩 관련, http 메서드들 서블릿에서 지원되도록 하는 등등 ) 
인터셉터는 (modelAttribute 바인딩하거나 더 스프링에 관련된 기술)
스프링에 종속되지 않은 웹에 관련된 기능은 필터로 구현하는게 좋을 것 같고, 더 스프링에 종속되거나 스프링에 포함된 기술을 연관해 사용하고 싶으면 인터셉터로 구현하는게 좋다고 생각해요

### Filter
- 자바 표준 스펙 
- ServletRequest,ServletResponse를 필터 체이닝 중간에 새로운 객체로 바꿀 수 있다 
- 필터에서 예외가 발생하면 `@ControllerAdvice`에서 처리하지 못한다. (스프링이 아니기 때문) 

### Interceptor
- 스프링이 제공하는 스펙
- ServletRequest,ServletResponse를 필터 체이닝 중간에 새로운 객체로 바꿀 수 없음
- 인터셉터에서 예외가 발생하면 `@ControllerAdvice`에서 처리 가능 (스프링이기 때문)

2024-07-08 16:20 UTC, Hongdonggeon commented on src/main/java/gift/repository/MemberRepository.java
> +            return Optional.empty();
아 그냥 예외처리를 하지않고 Optiona.ofNUllable로 반환해도 되지 않나하는 이야기였어요

2024-07-08 16:47 UTC, Hongdonggeon approved these changes
제법님 안녕하세요! 
미션 수행하시느라 수고 많으셨습니다 :) 
이미 잘하시지만, 이번 미션하면서 정말 많이 성장하신 것 같아요 👍
열심히 학습하고 고민하신 성과가 아닌 가 싶습니다!
저도 제법님 리뷰하면서 많이 배우고 있습니다 
코멘트 반영하신 것 잘 확인했고 approve 할게요 
지금 컨플릭 나는 파일들이 많아서 제법님이 컨플리 해결해주시면 제가 머지해드리겠습니다!

2024-07-08 17:26 UTC, nove1080 commented on src/main/java/gift/repository/MemberRepository.java
> +            return Optional.empty();
```java
Member findMember = jdbcTemplate.queryForObject(sql, getMemberRowMapper(), email.getValue(), password.getValue());
return Optional.ofNullable(findMember);
```
처음에는 저도 코드를 위와 같이 예외처리를 하지 않고 `Optional.ofNullable()` 로 반환하도록 구성했었습니다.
그리고 DB에 없는 회원을 조회하는 테스트를 해보았는데요 

없는 회원을 조회한 경우 `Optional.EMPTY`가 반환되고 정상적으로 프로그램이 실행될 것이라고 기대했는데
`Optional.EMPTY`가 반환되지 않고 `EmptyResultDataAccessException` 이 발생하더라구요

https://stackoverflow.com/questions/10606229/jdbctemplate-query-for-string-emptyresultdataaccessexception-incorrect-result

위 글을 읽어보니 `JdbcTemplate.queryForObject()` 반드시 하나의 결과 행이 포함되지 않으면 예외를 발생시키게 된다고 하더라구요 `jdbcTemplate.query()`를 이용하거나 `try-catch`로 감싸는 방법 중 저는 후자를 선택하였습니다.

그러면 메서드 반환타입에 `Optional` 없앨 수도 있겠네요!

2024-07-08 17:34 UTC, nove1080 commented
> 제법님 안녕하세요! 미션 수행하시느라 수고 많으셨습니다 :) 이미 잘하시지만, 이번 미션하면서 정말 많이 성장하신 것 같아요 👍 열심히 학습하고 고민하신 성과가 아닌 가 싶습니다! 저도 제법님 리뷰하면서 많이 배우고 있습니다 코멘트 반영하신 것 잘 확인했고 approve 할게요 지금 컨플릭 나는 파일들이 많아서 제법님이 컨플리 해결해주시면 제가 머지해드리겠습니다!

아직 다 리뷰를 다 반영하지 못한 것 같기도 하고 코드를 좀 더 리팩토링 해보고 싶어서 내일 안으로 충돌까지 해결해서 다시 리뷰요청을 드려도 괜찮을까요?

2024-07-09 13:53 UTC, Hongdonggeon commented on src/main/java/gift/repository/MemberRepository.java
> +            return Optional.empty();
넵 그렇네요 예외가 발생하지 않는다는 다는건 조회한 데이터가 존재하는거니까 Optional을 없앨 수 있겠네요

2024-07-09 14:01 UTC, Hongdonggeon commented on src/main/java/gift/domain/vo/Email.java
> +    public static Email from(String email) {
흠 또 어떤 장점이 있을까요..
객체를 여러번 만들지 않아도 되는 경우에는 미리 생성해서 정적 팩토리 메서드로 생성해놓은 객체를 반환할 수 도 있을 것 같고, 반환 타입을 인터페이스로 선언해두고 조건에 따라 하위 구현체를 반환할수도 있겠네요

정리하자면 정적 팩토리 메서드는 말 그대로 메서드니까 생성자보다 더 커스텀하게 만들 수 있다는 장점이 있는 것 같네요~

2024-07-09 14:02 UTC, Hongdonggeon commented
> > 제법님 안녕하세요! 미션 수행하시느라 수고 많으셨습니다 :) 이미 잘하시지만, 이번 미션하면서 정말 많이 성장하신 것 같아요 👍 열심히 학습하고 고민하신 성과가 아닌 가 싶습니다! 저도 제법님 리뷰하면서 많이 배우고 있습니다 코멘트 반영하신 것 잘 확인했고 approve 할게요 지금 컨플릭 나는 파일들이 많아서 제법님이 컨플리 해결해주시면 제가 머지해드리겠습니다!
> 
> 아직 다 리뷰를 다 반영하지 못한 것 같기도 하고 코드를 좀 더 리팩토링 해보고 싶어서 내일 안으로 충돌까지 해결해서 다시 리뷰요청을 드려도 괜찮을까요?

리뷰 요청 하신 것 같아서 머지할게요! 
3주차 과제 진행하면서도 리팩토링 계속하시면서 질문 언제든지 주세요! 
머지 할게요 ~

2024-07-09 14:02 UTC, merged