강원대 BE_김송목 2주차 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #371
Opened 2024-07-05 08:43 UTC by kimsongmok

2단계 PR 올려 놓겠습니다. 로그인 부분 구현했습니다!

2024-07-06 06:05 UTC, jaymarystella commented
다음단계부터는 스쿼시된 브랜치 위에서 작업을 부탁드릴게요

2024-07-06 06:05 UTC, jaymarystella requested changes
안녕하세요 송목님
2단계 피드백 남겨두었는데 몇가지 수정해서 다시 요청 남겨주시면 될것같아요.

2024-07-06 06:05 UTC, jaymarystella commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +    return ResponseEntity.status(HttpStatus.FORBIDDEN).body(ex.getMessage());
HTTP 상태코드들에 대해서 대표적인것들을 정리해보시면 좋을것같아요.

2024-07-06 06:05 UTC, jaymarystella commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +    return ResponseEntity.status(HttpStatus.FORBIDDEN).body(ex.getMessage());
그리고 위 상황에서 어떤 응답을 내리면 좋을지 고민해보셔요.

2024-07-06 06:05 UTC, jaymarystella commented on src/main/java/gift/model/Member.java
> +  // Getters and setters
불필요한 주석은 삭제부탁드립니다.

2024-07-06 06:05 UTC, jaymarystella commented on src/main/java/gift/util/JwtUtil.java
> +public class JwtUtil {
테스트코드가 없는데 전체적으로 추가해주신 클래스들에 대해서 최대한 테스트코드를 작성해보시면 좋을 것 같습니다.

2024-07-06 15:38 UTC, kimsongmok commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +    return ResponseEntity.status(HttpStatus.FORBIDDEN).body(ex.getMessage());
1. 400-Bad Request
클라이언트가 잘못된 요청을 보냄을 의미 주로 요청 구문, 메시지 등의 문법 오류로 인한 문제가 해당
2. 401-Unauthorized
요청자는 인증(authentication) 되지 않아 수행할 수 없음을 표현 참고로 401 응답은 Unauthorized 가 아닌 Unauthenticated 가 알맞는 단어이다.
3. 402-Payment Required
나중에 사용될 것을 대비해 예약된 비표준 응답 코드
4. 403-Forbidden
요청자는 승인(autorization)되지 않아 작업을 진행할수 없음 인증 자격(로그인)은 증명되었으나, 회원 등급에 의해 접근 권한이 불충분할때 사용
5. 404-Not Found
클라이언트가 요청한 자원이 존재하지 않음
6. 405-Method Not Allowed
요청이 허용되지 않은 메소드임을 의미 서버에서 해당 요청 HTTP 메소드에 대해 기능을 제한/금지 함
7. 406-Not Acceptable
콘텐츠 협상에 일치하는 것이 없음
8. 407-Proxy Authentication Required
프록시 인증을 요구 401 Unauthorized 와 같으나, 프록시 버전이라고 보면 된다.
9. 408-Request Timeout
요청이 너무 커 처리 시간이 초과되어 서버에서 요청을 처리하지 아니하고 연결을 닫음
10. 409-Conflict
클라이언트의 요청이 서버의 상태와 충돌이 발생 요청 처리 중 비지니스 로직상 불가능하거나 모순이 생긴 경우 사용된다.

이외에도 더 있는것으로 나와있습니다...!
제 생각에는 인증자격(로그인)은 증명 되었으나, 회원등급에 의해 접근 권한이 불충분할때 사용하는 것(403-Forbidden)보다는
인증이 되지 않아 수행 할 수 없음을 표현하는(401-Unathorized)가 더 맞는 것 같습니다!!

2024-07-06 18:33 UTC, kimsongmok commented
멘토님 스쿼시에 대한 이해가 잘 가지 않아서 더 공부해보겠습니다..!

2024-07-07 09:20 UTC, jaymarystella approved these changes
안녕하세요 송목님.
다음주차 미션도 곧 준비하셔야될테니 2단계는 여기서 머지할게요.
3단계 구현하셔서 제출 부탁드릴게요. 그때 부족한 부분들 다시 이야기나눠봐요.
그리고 git은 따로 공부 먼저 하시는걸 추천드릴게요.

2024-07-07 09:20 UTC, merged