강원대 BE_오승규 2주차 과제 (2, 3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #372
Opened 2024-07-05 08:45 UTC by 5win

토큰을 통한 로그인 구현부터 쉽지 않았던 것 같습니다.
기능적 구현으로 시간이 촉박하여 구조에 대해 신경쓰지 못했는데 리팩토링하여 개선하도록 하겠습니다.

2024-07-05 15:01 UTC, jaymarystella requested changes
안녕하세요 승규님.
3단계까지 구현하느라고 고생많으셨습니다.
코멘트 몇가지 남겨두었는데 궁금하신점 있으시면 다시 남겨주세요~

2024-07-05 15:01 UTC, jaymarystella commented on src/main/java/gift/controller/MemberController.java
> +        return ResponseEntity.ok().body(SuccessMessage.REGISTER_MEMBER_SUCCESS_MSG);
컨트롤러내 로직을 전개하기보다 다른 계층을 두어 작업간의 경계를 설정해보면 어떨까요?

2024-07-05 15:01 UTC, jaymarystella commented on src/main/java/gift/controller/MemberController.java
> +        if (!queriedMember.getPassword().equals(member.getPassword())) {
member객체에 비밀번호가 맞는지 질의하는형태로 구현해보면 어떨까요?

(비밀번호 처리에 대해서는 추후에 또 고민해보시기로해요)

2024-07-05 15:01 UTC, jaymarystella commented on src/main/java/gift/controller/MemberController.java
> +    @PostMapping("/member/wishlist/{id}")
path를 전부 이어붙였을때 member라는 단어가 중복되는거같아요. 어떻게 하면 명시적인 url path를 만들어볼수있을까요?

2024-07-05 15:01 UTC, jaymarystella commented on src/main/java/gift/interceptor/JwtInterceptor.java
> +    JwtUtil jwtUtil;
제한자가 없는건 의도하신걸끼요?

2024-07-05 15:01 UTC, jaymarystella commented on src/main/java/gift/interceptor/JwtInterceptor.java
> +public class JwtInterceptor implements HandlerInterceptor {
👍🏼

2024-07-05 15:01 UTC, jaymarystella commented on src/main/java/gift/jwt/JwtUtil.java
> +public class JwtUtil {
테스트코드도 같이 작성해보면 좋을거같아요. 전체적으로 커버리지가 많이 낮아보이는데 부족한 부분들을 채워보면 어떨까요?

2024-07-05 15:01 UTC, jaymarystella commented on src/main/java/gift/controller/MemberController.java
> +public class MemberController {
이번 단계에서 컨트롤러 구조 개선만 하더라도 충분히 많은것을 하실수있을거같아요.

2024-07-05 15:02 UTC, jaymarystella commented
> 그리고 https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/119 에서 주신 피드백 중에 답변을 남긴게 있는데 확인해주시면 감사하겠습니다 :)

혹시 제가 답변이 빠진부분있으면 해당부분 링크부탁드릴게요! 혹은 dm으로 노티주셔도됩니다.

2024-07-07 12:48 UTC, 5win commented
안녕하세요 제이님
피드백 주신 부분 수정하고 예외처리 부분과 테스트코드 부분을 보완했습니다.

저번에 여쭤보지 못한 것과 이번에 생긴 궁굼한 부분 몇가지만 여쭤볼게요 :)
## Service 계층
step1에서 주신 피드백과 이번 피드백에서 서비스 계층에 대해 이야기 하셔서 따로 분리해보았습니다.
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/119#discussion_r1665697472
위 링크가 step1에서 주신 피드백이고 제가 답변을 했었는데 이 답변과 동일한 질문입니다.

일단 구현은 서비스 계층에서 예외를 throw한 뒤 컨트롤러 계층에서 GlobalExceptionHandler를 통해 처리되도록 했습니다.
다른 방법으로는 서비스에서는 boolean으로 반환하고 컨트롤러에서 이에 따라 throw를 하는 방법이 있을거 같습니다.

저는 서비스 계층에서 던지는 것이 더 낫다고 생각이 되는데, 만약 컨트롤러 계층의 ExceptionHandler에 던지고자 하는 예외는 컨트롤러 계층에서 던지는 것도 일관성적인 부분에서는 괜찮을 것 같기도 해서 여쭤봅니다.

음...그리고 지금까지는 전역적인 예외처리기를 컨트롤러 계층의 `@ExceptionHandler`만을 사용해봤는데, 이 밖에 다른 계층에서 사용되는 핸들러도 혹시 있을까요?
## 서비스 계층에서의 유효성 검증
step1 피드백에서 서비스 로직에서도 입력값에 대한 유효성 검증을 하는 것이 좋다고 하셨는데 아직 구현을 하진 못했습니다.
이번 리뷰 남기고 반영해볼 생각입니다. 
컨트롤러 계층에서 사용한 `@Valid` 를 서비스 계층에서도 사용 가능할 것 같은데, 이 방법 외에도 사용해봤으면 하는 방법이 있으실까요?
## DTO
우연히 다른 분들의 PR 리뷰를 보다가 DTO에 대한 이야기를 봤습니다.
컨트롤러에서 @RequestBody로 데이터를 받을 때, DTO를 사용하지 말고 다른 것을 사용하라는 내용으로 기억합니다.
종종 다른 패키지 구조를 보다보면 DTO, Domain, Entity 를 사용하는 것을 볼 수 있었는데 뭔가 다 똑같이 데이터를 저장할 객체를 보관하는 패키지로 생각이되는데 이렇게 나누는 이유가 있을까요?

2024-07-07 12:54 UTC, 5win commented on src/main/java/gift/controller/MemberController.java
> +        return ResponseEntity.ok().body(SuccessMessage.REGISTER_MEMBER_SUCCESS_MSG);
> 컨트롤러내 로직을 전개하기보다 다른 계층을 두어 작업간의 경계를 설정해보면 어떨까요?

반영해보았습니다!
두 개로 나뉜 컨트롤러랑 다르게 서비스는 모두 묶어서 하나의 클래스에 두었습니다.

2024-07-07 12:57 UTC, 5win commented on src/main/java/gift/controller/MemberController.java
> +        if (!queriedMember.getPassword().equals(member.getPassword())) {
> member객체에 비밀번호가 맞는지 질의하는형태로 구현해보면 어떨까요?
처음에 잘못 이해하고 findByEmailAndPassword 를 구현하여 사용했다가 다시 바꿨습니다..ㅎ
DTO 객체에 저장 외에 검증 로직?도 포함하는 경우는 생각 못했네요 

 
> (비밀번호 처리에 대해서는 추후에 또 고민해보시기로해요)
고민해보고자 하는데 혹시 비밀번호 난독화?부분에 대해서 고민해보아야 할까요?

2024-07-07 12:59 UTC, 5win commented on src/main/java/gift/controller/MemberController.java
> +    @PostMapping("/member/wishlist/{id}")
> path를 전부 이어붙였을때 member라는 단어가 중복되는거같아요. 어떻게 하면 명시적인 url path를 만들어볼수있을까요?

고민다가 /members 부분을 제거하여 통일시켰습니다.
또는 wishlist를 따로 컨트롤러로 뺄까도 고민했는데, wishlist도 결국 member에  포함되는 부분이기에 일단 분리하지는 않았습니다.

2024-07-07 13:00 UTC, 5win commented on src/main/java/gift/interceptor/JwtInterceptor.java
> +    JwtUtil jwtUtil;
> 제한자가 없는건 의도하신걸끼요?

빼먹은 것 같네요...수정했습니다!

2024-07-07 13:01 UTC, 5win commented on src/main/java/gift/jwt/JwtUtil.java
> +public class JwtUtil {
> 테스트코드도 같이 작성해보면 좋을거같아요. 전체적으로 커버리지가 많이 낮아보이는데 부족한 부분들을 채워보면 어떨까요?

예외 처리 부분과 테스트코드를 보완하긴 했습니다. 혹시 더 부족해보이는 부분이 있다면 지적해주세요!

2024-07-07 13:04 UTC, 5win commented on src/main/java/gift/dto/Member.java
> +    public Member() {
MockMvc를 사용해 테스트코드를 작성하다보니 기본 생성자가 필요한 것 같더라고요...
제가 아직 MockMvc에 대해 이해하지는 못했지만 혹시 이 방법이 최선일까요?
빈 객체가 만들어질 확률이 있을 것 같기는 한데...일단 테스트를 해보고자 이렇게 바꿨습니다.

2024-07-08 14:14 UTC, jaymarystella commented on src/main/java/gift/controller/MemberController.java
> +        if (!queriedMember.getPassword().equals(member.getPassword())) {
암호화 처리에 대한 내용인데 지금은 신경안쓰셔도 될거같아요!

2024-07-08 14:15 UTC, jaymarystella commented on src/main/java/gift/controller/MemberController.java
> +    @PostMapping("/member/wishlist/{id}")
공통으로 만들어주신 복수형태의 members를 남기고 member를 삭제하는게 좀더 나아보이긴하네요

2024-07-08 14:20 UTC, jaymarystella commented on src/main/java/gift/dto/Member.java
> +    public Member() {
어떤 경우에서 필요했을까요? 기본생성자와 필드접근자가 필요한 상황이셨을거같은데 어느부분이었는지 해당 부분에 코멘트 남겨주세요

2024-07-08 14:22 UTC, jaymarystella commented
> 일단 구현은 서비스 계층에서 예외를 throw한 뒤 컨트롤러 계층에서 GlobalExceptionHandler를 통해 처리되도록 했습니다.
> 다른 방법으로는 서비스에서는 boolean으로 반환하고 컨트롤러에서 이에 따라 throw를 하는 방법이 있을거 같습니다.
> 
> 저는 서비스 계층에서 던지는 것이 더 낫다고 생각이 되는데, 만약 컨트롤러 계층의 ExceptionHandler에 던지고자 하는 예외는 컨트롤러 계층에서 던지는 것도 일관성적인 부분에서는 괜찮을 것 같기도 해서 여쭤봅니다.
> 
> 음...그리고 지금까지는 전역적인 예외처리기를 컨트롤러 계층의 @ExceptionHandler만을 사용해봤는데, 이 밖에 다른 계층에서는 어떤식으로 핸들링하는지 궁금합니다.

boolean반환하여 컨트롤러에서 처리하는 방식은 지양해주시구요, 말씀주신대로 서비스계층에서 throw하는것이 좋습니다. 컨트롤러 계층에서 throw를 하게되면 예외처리에 대한 일관성이 없어집니다. 서비스계층에서밖에 처리할 수 없는 예외상황도 존재하기때문에 산발적으로 로직들이 존재하게 될거에요. 예외를 catch에서 명시적으로 처리하지않는 이상은 exceptionHandler정의로 충분합니다.

2024-07-08 14:24 UTC, jaymarystella commented
> 2. 서비스 계층에서의 유효성 검증
> step1 피드백에서 서비스 로직에서도 입력값에 대한 유효성 검증을 하는 것이 좋다고 하셨는데 아직 구현을 하진 못했습니다.
> 이번 리뷰 남기고 반영해볼 생각입니다.
> 컨트롤러 계층에서 사용한 @Valid 를 서비스 계층에서도 사용 가능할 것 같은데, 이 방법 외에도 사용해봤으면 하는 방법이 있으실까요?

해당애노테이션은 컨트롤러 계층에서만 사용주시고 도메인에 대한 필수 비지니스로직은 도메인 클래스 혹은 서비스계층에서 코드레벨로 구현하시는걸 추천드립니다. 코드를 봤을때 필수도메인로직이 한눈에 보이기도하고 테스트코드 작성할때도 용이하게될거에요.

2024-07-08 14:28 UTC, jaymarystella commented
> 3. DTO
> 우연히 다른 분들의 PR 리뷰를 보다가 DTO에 대한 이야기를 봤습니다.
> 컨트롤러에서 @requestbody로 데이터를 받을 때, DTO를 사용하지 말고 다른 것을 사용하라는 내용으로 기억합니다.
> 종종 다른 패키지 구조를 보다보면 DTO, Domain, Entity 를 사용하는 것을 볼 수 있었는데 뭔가 다 똑같이 데이터를 저장할 객체를 보관하는 패키지로 생각이되는데 이렇게 나누는 이유가 있나요?

똑같이 데이터를 저장하더라도 나눠져있다는건 역할이 다르기 때문입니다. 다음 주차때 각각의 역할에 대해서 한번 정리해보시면 좋을것같아요.

2024-07-08 14:29 UTC, jaymarystella commented
> 4. Custom Exception
> 구현하면서 접한 여러 오류들에 대해 저는 IllegalExcpetion이나 NoSuchArgumentException으로 충분하다고 생각하고 사용했습니다.
> 따로 CustomException을 정의하여 사용하는 이유가 있을까요?
> 만약 기존 예외로는 설명이 부족한 비즈니스 로직 에러와 같은 경우는 따로 커스텀하는게 맞을 것 같다고 생각이 되긴합니다.

간단한 경우는 기존에 있는 예외를 써도 상관이 없습니다. 세분화와 가독성측면에서 사용자정의 예외를 쓴다고 봐주셔도 될거같아요. 같은 illegatlArgumentException이더라도 다르게 처리해야하는 경우가 있다면 custom exception으로 handling하는게 더 간편하겠죠.

2024-07-08 14:30 UTC, jaymarystella commented
> 5. 토큰 검사
> 현재 토큰에 대한 검사를 Interceptor에서만 진행하고 있는데, 서비스 계층에서도 하는게 좋을지 고민입니다.

공통으로 처리를 해주셨기때문에 서비스계층에서는 하지 않으셔도 되겠습니다.

2024-07-08 14:31 UTC, jaymarystella approved these changes
안녕하세요 승규님.
리뷰 반영하느라 고생많으셨어요.
질문주신 부분은 답변 남겨두었는데 부족한 부분이 있다면 다시 말씀주세요~

2024-07-08 14:31 UTC, merged

2024-07-09 13:36 UTC, 5win commented on src/main/java/gift/controller/MemberController.java
> +    @PostMapping("/member/wishlist/{id}")
> 공통으로 만들어주신 복수형태의 members를 남기고 member를 삭제하는게 좀더 나아보이긴하네요

반영하도록 하겠습니다!