부산대 BE_박수빈 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #373
Opened 2024-07-05 08:47 UTC by kuma4188

아직 미완성 입니다...

2024-07-05 17:28 UTC, yoo-jaein requested changes
무수면 코딩...🔥🔥 저도 본받아야겠습니다 😭
step3 고생 많으셨습니다!!
리뷰 코멘트 확인 부탁드려요!

2024-07-05 17:28 UTC, deactivated-user commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok'
롬복을 쓰셨군요! 많은 보일러플레이트 코드를 줄여줘서 도움이 많이 될텐데요.
롬복을 쓸 때 한 가지 주의사항이 있습니다.

```@Getter``` 와 ```@Setter```의 무분별한 사용은 객체의 캡슐화를 해칠 수 있습니다.
 그래서 모든 필드에 대해 자동으로 메서드를 생성하는 것은 가능한 피하고, 필요한 메서드만 명시적으로 작성하는 것이 좋습니다.

2024-07-05 17:28 UTC, deactivated-user commented on src/main/java/gift/jwt/LoginController.java
> +            System.out.println("Generated Token: " + token); // 토큰 출력
System.out.println()로 로그를 출력하고 있네요.
해당 코드를 지우거나, System.out.println() 대신 SLF4J와 Logback 같은 로깅 프레임워크를 사용하는 것을 권장합니다.
프레임워크를 사용하면 이런 장점이 있습니다.

1. 로그 레벨 지정 가능 (DEBUG, INFO, WARN, ERROR 등..)
2. 로그 출력 형식을 바꾸거나 로그를 파일로 내보내는 등 다양한 커스텀 가능
3. println보다 성능이 좋음

2024-07-05 17:28 UTC, deactivated-user commented on src/main/java/gift/service/WishlistServiceImpl.java
> +    private WishlistDTO convertToDTO(Wishlist wishlist) {
엔티티 -> dto 변환하는 코드를 별도 메서드로 잘 분리했네요! 👍

2024-07-05 17:28 UTC, deactivated-user commented on src/main/java/gift/service/WishlistServiceImpl.java
> +            .collect(Collectors.toList());
stream API 👍

2024-07-05 17:28 UTC, deactivated-user commented on src/main/java/gift/user/DataSourceConfiguration.java
> +        populator.addScript(new ClassPathResource("login.sql")); // login.sql 파일을 추가합니다.
login.sql 파일을 별도로 작성하신 이유가 있을까요?

2024-07-05 17:28 UTC, deactivated-user commented on src/main/java/gift/user/SiteUser.java
> +	@Column(unique = true)
제약 조건을 꼼꼼히 달아주셨군요 👍

2024-07-05 17:28 UTC, deactivated-user commented on src/main/java/gift/user/UserService.java
> +		user.setEmail(email);
데이터베이스 수준에서 중복을 이미 체크하고 있지만..
데이터베이스로 요청을 보내기 전 애플리케이션 레벨에서 미리 중복을 체크하면 불필요한 데이터베이스 작업을 줄일 수 있습니다 😀
덤으로 데이터베이스 레벨의 예외가 아니라 조금 더 사용자 친화적인 예외를 던져줄 수 있다는 장점도 있습니다.

2024-07-05 17:28 UTC, deactivated-user commented on src/main/java/gift/jwt/LoginController.java
> +package gift.jwt;
controller 라는 패키지로 옮길까요?

2024-07-05 17:28 UTC, deactivated-user commented on src/main/java/gift/user/UserController.java
> +package gift.user;
이것도 controller 라는 패키지로 옮길까요?

2024-07-05 17:28 UTC, yoo-jaein commented on README.md
> +개인적으로 몇가지 방향성에 대해서 생각해봤습니다.<br>
다양한 고민을 하셨던 흔적이 코드에서도 잘 보여서 좋았습니다!
특히 웹까지 쭉 구현해주셔서 실행해보는게 재미있었어요 😄

그런데 3번 방향성에서 'DB도 만들지 않았고' 이 부분은 어떤걸 말씀하시는걸까요??
처음엔 브라우저 캐시를 이용하신건가 싶었는데 Wishlist를 데이터베이스에 쌓고 있어서 질문드립니다!

2024-07-05 17:28 UTC, yoo-jaein commented on src/main/resources/application.yml
> +      ddl-auto: update
이왕 yml 파일을 만드셨으니 application.properties에 있는 설정 값들도 다 yml로 옮겨볼까요?
아래 야믈 컨버터 사이트를 활용하시면 금방 작업하실거에요.
- https://mageddo.com/tools/yaml-converter 

참고로 현업에서는 properties보다 yml이 가독성이 좋아 더 많이 사용합니다.
- https://velog.io/@lily_younk/application.yml-.properties-차이

2024-07-05 17:28 UTC, yoo-jaein commented on README.md
> +3.  기존의 코드를 이용해서 토큰을 받은 사람만 찜 할수 있는 방식 (확정) <br>
로그인해야 찜 할 수 있다 -> 이 방향이 좋네요

2024-07-05 17:28 UTC, yoo-jaein commented on build.gradle
> +    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity'
이것도 밑에 포함되어있어서 지워도 될 것 같아요

2024-07-05 17:28 UTC, yoo-jaein commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-security'
spring-boot-starter-security가 두 번 포함되어 있습니다!

2024-07-05 17:28 UTC, yoo-jaein commented on src/main/java/gift/SecurityConfig.java
> +				.requestMatchers(new AntPathRequestMatcher("/**")).permitAll()
특정 경로(/api/auth/login, /user/signup)에 대한 permitAll 설정을 하려는 것 같네요!
그런데 requestMatchers(new AntPathRequestMatcher("/**")).permitAll() 이 부분은 모든 요청을 허용한다는 것이기 때문에 이 줄은 제거해도 될 것 같습니다.

2024-07-05 17:28 UTC, yoo-jaein commented on src/main/java/gift/SecurityConfig.java
> +			userService.create("admin", "admin@example.com", "1234");
어드민 계정 정보를 하드코딩하는 대신 application.yml에서 불러오는 것이 더 안전합니다!

2024-07-05 17:28 UTC, yoo-jaein commented on src/main/java/gift/SecurityConfig.java
> +		return http.build();
Spring security 설정을 꼼꼼히 잘 해주셨네요 👍

2024-07-05 17:44 UTC, yoo-jaein requested changes
.

2024-07-08 01:58 UTC, yoo-jaein approved these changes
step3 고생 많으셨습니다!
머지하겠습니다 :)

2024-07-08 01:58 UTC, merged

2024-07-08 02:00 UTC, kuma4188 commented
login.sql 파일을 별도로 작성하신 이유가 있을까요?

그런데 3번 방향성에서 'DB도 만들지 않았고' 이 부분은 어떤걸 말씀하시는걸까요??
처음엔 브라우저 캐시를 이용하신건가 싶었는데 Wishlist를 데이터베이스에 쌓고 있어서 질문드립니다!

답변)
사실 데이터베이스를 저장하는 sql을 만들지 않으면 DB에 저장이 되지 않는줄 알았습니다...ㅎㅎ
그래서 회원정보를 sql로 만들어서 DB를 관리하면 회원정보를 외부에서 가져오거나 , 이전할때 용이할것
같아서 이런 방식을 사용했습니다.
하지만 주말동안 공부해보니 , 로컬에서 DB가 저장된다 라고 하더라구요...ㅎㅎ

# 코드리뷰 받은것들 중에서 간단하게 수정가능한 사항은 수정완료 했습니다.!
-controller 위치 변경
- propertise의 내용을 yml로 이전
-중복된 의존성 삭제
-System.out.println 로그 출력 삭제


리뷰 정말 감사드리고 고생 많으셨습니다!