경북대 BE_안재민 2주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #375
Opened 2024-07-05 08:48 UTC by dkswoals

## 2주차 step2 리뷰 요청 드립니다!

---

## 과제 진행 중 어려웠던 점 + 궁금한 점

- 전체적인 개선점 피드백 부탁 드리겠습니다!!

2024-07-06 07:02 UTC, leaf-upper requested changes
안녕하세요 재민님 2주차 2단계 구현 고생하셨어요~
몇가지 코멘트를 남겨드렸는데요~! 확인 부탁드릴게요
혹시 궁금한게 생기시면 DM이나 코멘트 부탁드려요
고생하셨습니다!

2024-07-06 07:02 UTC, leaf-upper commented on src/main/java/wishlist/controller/AuthController.java
> +            result.rejectValue("email", "", "이미 존재하는 이메일입니다.");
👍👍 중복 이메일 체크하는 부분은 잘 작성해주셨네요.
MethodArgumentNotValid 보다는 별도 예외를 정의해서 던져주셔도 좋을것 같아요

2024-07-06 07:02 UTC, leaf-upper commented on src/main/java/wishlist/model/user/UserDTO.java
> +    private String Email;
- camel case를 지켜주시면 좋을것 같아요~
- 멤버변수는 final 키워드 붙여주시면 좋을것 같아요~!

2024-07-06 07:02 UTC, leaf-upper commented on src/main/java/wishlist/model/user/User.java
> +    private String Email;
User는 ID가 필요 없을까요?

2024-07-06 07:02 UTC, leaf-upper commented on src/main/java/wishlist/service/JwtProvider.java
> +    public JwtProvider(@Value("${jwt.secretKey}") String jwtSecret,
👍 👍

2024-07-06 07:02 UTC, leaf-upper commented on src/main/java/wishlist/service/JwtProvider.java
> +    public boolean validateToken(String token) throws JwtException {
아직 실제로 인증을 수행하는 API는 없는걸까요?

2024-07-06 07:18 UTC, dkswoals commented on src/main/java/wishlist/service/JwtProvider.java
> +    public boolean validateToken(String token) throws JwtException {
앗 해당 기능은 3단계 요구사항이라 일단 구현은 해두었는데 바로 반영시킬까요?

2024-07-06 08:13 UTC, dkswoals commented on src/main/java/wishlist/controller/AuthController.java
> +            result.rejectValue("email", "", "이미 존재하는 이메일입니다.");
반영하였습니다!

2024-07-06 08:13 UTC, dkswoals commented on src/main/java/wishlist/model/user/UserDTO.java
> +    private String Email;
모델 전체 바로 반영하였습니다!

2024-07-06 08:21 UTC, dkswoals commented on src/main/java/wishlist/model/user/User.java
> +    private String Email;
처음엔 이메일과 비밀번호만 필요한 줄 알고 이메일을 pk로 설정하였는데 이메일이 변경되는 경우를 생각하지 못했네요,,
반영하였습니다!

2024-07-06 09:50 UTC, dkswoals commented
## 피드백 반영 후 인증 기능과 wishList 기능까지 반영하였습니다!!

# 2주차 step3 구현 기능 목록 명세

## 구현 기능

-  사용자 별 위시 리스트 기능

1. Wish, WishDTO 구현
2. Wishes 테이블 구현
3. WishListRepository
4. WishListService
5. WishListController
6. AuthInterceptor

## 과제 진행 중 궁금한 점

1. jwt의 페이로드는 쉽게 복호화가 가능해서 민감한 정보를 담으면 안된다 하여 email을 넣고 사용자를 식별하였는데 적절할까요?
2. 인증이 추가된 후부터 페이지 구현이 조금 어려워진 것 같습니다,, 
쿠키나 세션을 사용하지 않고 모든 페이지에서의 요청 헤더에 토큰을 추가하기 위한 좋은 방법이 있을까요? 
(아니면 사실 과제 요구사항에 페이지는 포함되지 않는데 view 없이 진행해도 될까요?)

2024-07-07 08:01 UTC, leaf-upper requested changes
재민님 2주차 2,3단계 고생 많으셨습니다~
몇가지 코멘트를 남겨드렸는데요~ 큰 수정사항은 아니라서, 수정해주시고 
다시 리뷰요청 주시면 어프로브 드리겠습니다.
질문 주신거에 대한 답변도 드릴게요~

**1. jwt의 페이로드는 쉽게 복호화가 가능해서 민감한 정보를 담으면 안된다 하여 email을 넣고 사용자를 식별하였는데 적절할까요?**
JWT는 base64 인코딩만 하고, 이건 암호화는 아니에요~ 디코딩도 바로 가능합니다. JWT는 전자서명이 된 base64 토큰이라고 생각해주시면 좋을것 같아요.
email도 개인정보에 속하는 데이터에요~! 유저를 식별할수 있는 단위는 유저ID를 사용해주시는게 좋을것 같아요.

**2. 인증이 추가된 후부터 페이지 구현이 조금 어려워진 것 같습니다,,
쿠키나 세션을 사용하지 않고 모든 페이지에서의 요청 헤더에 토큰을 추가하기 위한 좋은 방법이 있을까요?
(아니면 사실 과제 요구사항에 페이지는 포함되지 않는데 view 없이 진행해도 될까요?)**
view개발로 인해서, 백엔드 개발진행이 어려우신 상황이라면 view없이 진행해주셔도 될것 같아요~ (과제에도 포함되지 않는 영역이라면요). 서버에서 JWT응답을 주면 쿠키나 세션이나, 프론트쪽에서는 해당 응답을 로컬 스토리지에 캐싱하고 사용할 수 있을것 같아요!

2024-07-07 08:01 UTC, leaf-upper commented on src/main/java/wishlist/config/InterceptorConfig.java
> +            .order(1)
order를 1로 명시해주셨네요.
문제가 있는건 아니지만 혹시 이렇게 설정하신 이유가 있을까요?

2024-07-07 08:01 UTC, leaf-upper commented on src/main/java/wishlist/controller/WishListController.java
> +    @GetMapping("/wishes/add/{id}")
위시리스트 추가에 Get요청이 쓰인것 같아요
더 적절한 Http Method가 있을까요?
api path도 수정해볼수 있을것 같아요

2024-07-07 08:01 UTC, leaf-upper commented on src/main/java/wishlist/exception/CustomException/CustomException.java
> +    public CustomException(ErrorCode errorCode) {
👍 
CustomException을 직접 던지실게 아니라면 추상클래스로 만들어보는건 어떨까요?

2024-07-07 08:01 UTC, leaf-upper commented on src/main/java/wishlist/interceptor/AuthInterceptor.java
> +        String token = authHeader.substring(7);
7은 약간 휴리스틱 한것 같아요 더 좋은 방식으로 토큰을 조회할 수 있는 방식이 있지 않을까요?

2024-07-07 08:01 UTC, leaf-upper commented on src/main/java/wishlist/interceptor/AuthInterceptor.java
> +        request.setAttribute("email", email);
email도 사실 개인정보에 속하는 정보라서, 민감한정보일것 같아요~ 
유저를 식별하는값으로 ID를 사용해주셔도 될것 같습니다.

2024-07-07 08:01 UTC, leaf-upper commented on src/main/java/wishlist/service/WishListService.java
> +    public List<ItemDTO> getList(Long UserId) {
자바 컨벤션에 조금만 더 신경써주시면 좋을것 같아요~

2024-07-07 08:01 UTC, leaf-upper commented on src/test/java/wishlist/controller/ItemControllerTest.java
> +//
TC는 다 주석처리되었네요 혹시 이유가 있을까요?

2024-07-07 09:03 UTC, dkswoals commented on src/main/java/wishlist/config/InterceptorConfig.java
> +            .order(1)
지금은 인터셉터가 하나이기 때문에 명시하지 않아도 괜찮겠지만 이후 인터셉터가 많아질 때를 고려해 명시하였습니다!

2024-07-07 09:04 UTC, dkswoals commented on src/main/java/wishlist/controller/WishListController.java
> +    @GetMapping("/wishes/add/{id}")
바로 반영하겠습니다!

2024-07-07 09:04 UTC, dkswoals commented on src/main/java/wishlist/exception/CustomException/CustomException.java
> +    public CustomException(ErrorCode errorCode) {
좋은거 같아요! 반영하겠습니다!

2024-07-07 09:05 UTC, dkswoals commented on src/main/java/wishlist/interceptor/AuthInterceptor.java
> +        String token = authHeader.substring(7);
반영하겠습니다!

2024-07-07 09:05 UTC, dkswoals commented on src/main/java/wishlist/interceptor/AuthInterceptor.java
> +        request.setAttribute("email", email);
바로 반영하겠습니다!

2024-07-07 09:06 UTC, dkswoals commented on src/test/java/wishlist/controller/ItemControllerTest.java
> +//
이번주차에는 과제 제출기간을 맞추느라 테스트 코드에 신경을 못쓰게 되어 일단 주석처리 해두었습니다,,
다음 주차부터는 좀 더 신경쓰겠습니다,,!

2024-07-07 09:21 UTC, dkswoals commented on src/main/java/wishlist/service/WishListService.java
> +    public List<ItemDTO> getList(Long UserId) {
자꾸 하나씩 빼먹네요,,, 더욱 신경 쓰도록 하겠습니다.
반영하였습니다!

2024-07-07 09:22 UTC, dkswoals commented
주말에도 고생 많으십니다😊
피드백 반영 후 리뷰 요청 드립니다!!

2024-07-07 10:06 UTC, leaf-upper approved these changes
👍 2주차 고생많으셨습니다 재민님~!

2024-07-07 10:06 UTC, merged