경북대 BE_김민주 2주차 과제 (2, 3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #377
Opened 2024-07-05 08:51 UTC by minju26

- step1 브랜치에서 분기하여 만든 브랜치에서 작업했습니다.

2024-07-05 17:05 UTC, gongdongho12 requested changes
> 데이터베이스 테이블에서 pk를 이메일로 해도 괜찮은지

pk를 id로 하는 이유는 이메일은 변경될 수 있는거라 그렇습니다
ex) 학교 이메일 -> 졸업후 삭제 / 회사 이메일 -> 퇴사후 삭제 등
pk는 단일상태를 유지 (auto incresement로 단일 유지) + 나중에 이메일이 변경되더라도 변경되지 않는 고유값 이라 대부분에서 적용하는 방법중 하나입니다

거기에 이메일 중복 방지를 위해 email에는 uniqueKey 정도로 등록할 수 있겠죠?

고생하셨습니다 🏃🏼

2024-07-05 17:05 UTC, gongdongho12 commented on build.gradle
> +//    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
작업하신 흔적으로 보이는데 주석처리한 사유도 남겨주시면 좋을 것 같아요 👀

2024-07-05 17:05 UTC, gongdongho12 commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +    }
번거롭게 설정이 필요한데 잘 쓰이냐는 질문이라고 하면 더 좋게 쓰는 방법은 많다고 말씀드릴 수 있을 것 같구요

다만 한번 이해하고 가기에 한번씩 짚고 가는 방향에선 좋은 학습법이라고 생각합니다

2024-07-05 17:05 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.ok(productService.deleteProduct(productId));
add와 new 등 이번에 깔끔하게 메서드를 명명하신 것 같아요

2024-07-05 17:05 UTC, gongdongho12 commented on src/main/java/gift/controller/WishListController.java
> +    }
@Autowired가 더 짧긴 한데 꼭 생성자로 써셔야 하는 이유가 있었을까요?

2024-07-05 17:05 UTC, gongdongho12 commented on src/main/java/gift/exception/ErrorCode.java
> +    KAKAO_CONTAIN_ERROR(400, HttpStatus.BAD_REQUEST, KAKAO_CONTAIN_ERROR_MSG);
하나에 정리해둔점은 👍🏼 
minor) BAD_REQUEST에 대한 에러 클래스를 만들고 메시지만 교체하는 방법은 어떠세요?

2024-07-05 17:05 UTC, gongdongho12 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
Global이라는 명칭을 가지고 있는데 다른 에러는 처리 못하는 핸들러로 보여지는데 본인이 감지하지 못한 예외를 공통으로 처리할 수 있으면 어떨까요?

2024-07-05 17:05 UTC, gongdongho12 commented on src/main/java/gift/repository/WishListRepository.java
> +    }
한 메서드에 쿼리를 두개 넣지 말구 각각 쪼개서 레포지토리 메서드를 만들고
WishListRepository를 사용하는 WishListService에서 개별 메서드를 두개 합쳐서 selectWishList 라는 메서드를 구현하는게 추후 코드 확장성 측면에서 효율적이지 않을까요?

2024-07-05 17:05 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        if ((product.getName() != null) & (isValidProductName(product.getName()))) {
ProductService에 validation 기능을 넣는 것 보다는 Product 클래스에 Validaiton을 넣는 방법이나 @Valid 등을 사용해서 서비스 단 로직을 깔끔하게 정돈하면 어떨까요?

2024-07-05 17:05 UTC, gongdongho12 commented on src/main/resources/db/schema.sql
> +        FOREIGN KEY (productId) REFERENCES products(id)
외래키로 묶어서 관리하는 방식이군요

2024-07-05 17:05 UTC, gongdongho12 commented on src/main/java/gift/util/ProductNameValidationUtil.java
> +    }
Validation 방향을 분리한 방향은 👍🏼 
직접 객체를 참조해야하는 단점이 있는데 고민 한번 해보시면 좋을 것 같습니다

2024-07-07 15:20 UTC, minju26 commented
> > 데이터베이스 테이블에서 pk를 이메일로 해도 괜찮은지
> 
> pk를 id로 하는 이유는 이메일은 변경될 수 있는거라 그렇습니다 ex) 학교 이메일 -> 졸업후 삭제 / 회사 이메일 -> 퇴사후 삭제 등 pk는 단일상태를 유지 (auto incresement로 단일 유지) + 나중에 이메일이 변경되더라도 변경되지 않는 고유값 이라 대부분에서 적용하는 방법중 하나입니다
> 
> 거기에 이메일 중복 방지를 위해 email에는 uniqueKey 정도로 등록할 수 있겠죠?
> 
> 고생하셨습니다 🏃🏼



> > 데이터베이스 테이블에서 pk를 이메일로 해도 괜찮은지
> 
> pk를 id로 하는 이유는 이메일은 변경될 수 있는거라 그렇습니다 ex) 학교 이메일 -> 졸업후 삭제 / 회사 이메일 -> 퇴사후 삭제 등 pk는 단일상태를 유지 (auto incresement로 단일 유지) + 나중에 이메일이 변경되더라도 변경되지 않는 고유값 이라 대부분에서 적용하는 방법중 하나입니다
> 
> 거기에 이메일 중복 방지를 위해 email에는 uniqueKey 정도로 등록할 수 있겠죠?
> 
> 고생하셨습니다 🏃🏼

오호.. 그렇군요! 완전히 이해되었습니다 감사합니다 :)

2024-07-07 15:22 UTC, minju26 commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +    }
음 그렇군요! 이번 기회에 학습하게 되어서 좋은 것 같아요

2024-07-07 15:25 UTC, minju26 commented on src/main/java/gift/controller/WishListController.java
> +    }
어디선가.. Spring에서는 필드 주입보다 생성자 주입을 권장한다는 이야기를 들어서 생성자로 썼습니다! 질문 해주셔서 어떤점이 다른지, 왜 생성자를 사용하는 것을 권장하는지 학습하게 되었네요 👍

2024-07-07 15:28 UTC, minju26 commented on src/main/java/gift/exception/ErrorCode.java
> +    KAKAO_CONTAIN_ERROR(400, HttpStatus.BAD_REQUEST, KAKAO_CONTAIN_ERROR_MSG);
그러면 혹시 BAD_REQUEST 말고 다른 에러(A)에 대해 처리할 때
BAD_REQUEST에 대한 에러 클래스를 만든 것 처럼, A에러에 대한 클래스를 따로 만들어서 관리해야 할 것 같다는 생각이 듭니다. 맞을까요?
에러 별로 클래스 관리를 하는게 나을지, 에러 코드 클래스에 다양한 에러는 관리할지 고민이 됩니다!

2024-07-07 15:29 UTC, minju26 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
넵! 다양한 예외를 공통으로 처리할 수 있도록 step1 pr에 반영하고, step3 브랜치에 pull 해왔습니다

2024-07-07 15:32 UTC, minju26 commented on src/main/java/gift/service/ProductService.java
> +        if ((product.getName() != null) & (isValidProductName(product.getName()))) {
네! Empty와 길이와 같은 경우에 Product 클래스에 Validation을 넣어서 정돈했습니다.
그런데 이름에 "카카오"가 들어간 경우같이 Validation으로 처리하기 애매한 부분만 남겨두었습니다.

2024-07-07 15:33 UTC, minju26 commented on src/main/resources/db/schema.sql
> +        FOREIGN KEY (productId) REFERENCES products(id)
네 그렇습니다 😊

2024-07-07 15:35 UTC, gongdongho12 commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +    }
@minju26 LoginMemberArgumentResolver 그런데 오류는 아직 못잡으신거죠?

2024-07-07 15:38 UTC, gongdongho12 commented on src/main/java/gift/exception/ErrorCode.java
> +    KAKAO_CONTAIN_ERROR(400, HttpStatus.BAD_REQUEST, KAKAO_CONTAIN_ERROR_MSG);
좋은 의견입니다
그래서 에러 메시지 정리하면서 이 메시지 오류가 어떤 HttpStatus로 사용될지 같이 저장해서 사용하면 어떨까요?

2024-07-07 15:40 UTC, minju26 commented on src/main/java/gift/util/ProductNameValidationUtil.java
> +    }
음!! 유틸리티 클래스라 static 메서드로 구성하고 인스턴스를 생성하지 않고도 메서드를 호출하도록 해보았습니다
객체지향적인 관점에서 테스트, 코드 유지 보수 등이 단점이 될 것 같기도 합니다!

2024-07-07 15:42 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        if ((product.getName() != null) & (isValidProductName(product.getName()))) {
서비스 단은 사실 비지니스 로직이 포함되어있는 부분인데 이걸로 인해서 복잡도가 올라가니까요

2024-07-07 15:43 UTC, merged

2024-07-07 15:43 UTC, minju26 commented on src/main/java/gift/repository/WishListRepository.java
> +    }
오호 안그래도 저 메서드를 작성하면서 뭔가 찝찝한 느낌이 있었습니다 🥹
피드백 해주신 내용을 바탕으로 수정해보도록 하겠습니다 !!

2024-07-07 15:45 UTC, minju26 commented on src/main/java/gift/exception/ErrorCode.java
> +    KAKAO_CONTAIN_ERROR(400, HttpStatus.BAD_REQUEST, KAKAO_CONTAIN_ERROR_MSG);
메세지와 HttpStatus를 같이 저장해서 사용하는 것 좋은 것 같습니다! 피드백 감사합니다 👍

2024-07-07 15:46 UTC, minju26 commented on src/main/java/gift/LoginMemberArgumentResolver.java
> +    }
해결 했습니다!! pr 내용에 **[이슈]** 아래에 작성해뒀습니다 :)

2024-07-07 15:48 UTC, minju26 commented on src/main/java/gift/service/ProductService.java
> +        if ((product.getName() != null) & (isValidProductName(product.getName()))) {
넵 계층 특성이랑 복잡도 등을 고려해서 수정해보도록 하겠습니다!