경북대 BE_김동현 2주차 과제 (2~3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #383
Opened 2024-07-05 08:54 UTC by donghyuun

[구현 중점 사항]
- 회원 가입 및 로그인 기능
- 로그인 시 이메일, id, 만료 시간 등을 포함한 jwt 생성
- 요청 시 권한 확인이 필요한 경우 요청에 포함된 jwt 를 복호화 해 현재 로그인한 유저 정보 반환

2단계 완료, 3단계 진행중입니다.
현재 다소 미비한 상태이므로, 금~토 까지 모두 마무리하고 리뷰 요청드리겠습니다!

2024-07-05 14:55 UTC, MangKyu requested changes
안녕하세요 동현님ㅎㅎ 아직 추가 작업진행중이실 것 같은데, 일단 현재까지의 작업 기준으로 코멘트 한번 남겨드립니다! 천천히 작업 진행해주세요:)
이번에도 마찬가지로 질문 주셨던 부분들에 대해 답변 남겨드리겠습니다!

## 검증 메서드 내부에서 에러 or 값 반환
이것은 요구사항에 따라 다르게 처리하는 것이 좋습니다ㅎㅎ 검증 메서드를 호출할 때 어떤 케이스에서는 검증한 값이 false면 예외를 던져야할 수도 있고, 어떤 경우에는 false를 그대로 활용할 수 있습니다! 따라서 경우에 따라서 처리하는 것이 좋고, 이럴때 네이밍을 잘 가져가는 것이 좋은 것 같습니다!
- 값을 반환하는 경우: isXXX or hasXXX or ...
- 예외를 던지는 경우: validateXXX or XXXOrThrow

2024-07-05 14:55 UTC, MangKyu commented on build.gradle
> +    implementation 'org.projectlombok:lombok'
롬복의 사용을 강사님께서 지양하라고 하셨던 것 같은데요ㅎㅎ 사용은 자제해주시면 좋을 것 같습니다!
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/17094600/05f540fc-a328-4011-9899-50be750edcbf)

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/domain/product/ProductController.java
> +     * @return 결과 메시지, products (상품 목록)
이런게 이제 `구현을 드러내는 주석`의 단점을 보여주는 것 같네요ㅎㅎ
구현이 바뀌면서 문서도 바뀌어야 하는 부분인 것 같아요

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/domain/product/ProductDTO.java
> +    @NotContainsValue(value = "카카오", message = "'{value}' 가 포함된 문구는 담당 MD 와 협의 후 사용 가능합니다.")
제약 조건은 크게 2종류로 나눌 수 있는데요~
- 입력 데이터에 따른 유효성
- 비즈니스 정책에 따른 유효성

위의 코드 기준으로는 데이터 유효성과 비즈니스 정책이 혼합되어 있는 것 같습니다ㅎㅎ

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/domain/product/ProductService.java
> +    private final gift.global.validation.validator validator; // 유효성 검증
```suggestion
    private final validator validator; // 유효성 검증
```

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/domain/user/UserRepository.java
> +public class UserRepository implements UserRepositoryInterface {
해당 UserRepository는 JdbcTemplate을 통한 접근 기술을 제공하고 있어서요ㅎㅎ
구체적인 기술이 클래스에 드러나는 것이 좋을 것 같아요! 다음과 같은 네이밍은 어떨까요?
- 인터페이스: UserRepository
- 구현체: JdbcTemplateUserRepository

UserRepositoryInterface를 사용하는 클라이언트 입장에서는 이게 Interface인지 아닌지가 중요한 정보가 아니라서 굳이 Interface라는 네이밍을 붙여줄 필요는 없어 보입니당

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/domain/user/UserRepository.java
> +        if(count > 1) throw new BusinessException(HttpStatus.INTERNAL_SERVER_ERROR, "서버에 동일한 이름의 회원 2명 이상 존재");
이렇게 처리하면 해당 메서드를 사용하는 클라이언트의 입장에서는 인터페이스에 접근해서 호출하게 될텐데, count가 1보다 큰 경우에 예외가 발생한다는 것은 예상치 못한동작을 정의하는 것 같아요~
이러한 부분이 계속 쌓이면 시스테에 대한 인지 부하를 많이 초래하게 되어서 유지보수가 어려워질 수 있습니다ㅎㅎ

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/global/annotation/NotContainsValueValidator.java
> + * NotContainsValue 어노테이션을 위한 유효성 검사기
해당 부분만 그런 것은 아니고, 코드로 파악할 수 있는 부분에 대해서 주석이 너무 많은 것 같네요ㅎㅎ
좋은 주석은 어떤 것인지 고민해보는 것도 좋을 것 같습니다! [프로그래머의 뇌](https://mangkyu.tistory.com/315)에서 나온 부분 일부 공유해드리겠습니다ㅎㅎ
- 코드 내의 문서화
  - DRY 원칙은 저수준의 지식은 코드에 놔두고, 주석은 고수준의 설명을 위해 아껴두라고 말한다. 
  - 그러지 않으면 지식을 중복하게 되며, 변경할 때마다 매번 코드와 주석 모두를 바꾸어야 한다.
- 코드 내의 주석
  - 주석은 어떤 트레이드 오프나 결정의 이유, 어떤 대안을 버렸는지 등 다른 곳에서 문서화할 수 없는, 바로 프로젝트에서 잘 빠져 나가는 부분들을 문서화하기 위한 완벽한 기회가 된다.

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/global/annotation/NotContainsValueValidator.java
> +public class NotContainsValueValidator implements ConstraintValidator<NotContainsValue, String> {
실무에서는 이렇게 복잡하게 커스텀 애노테이션을 만들어서 처리하지는 않지만
연습 차원에서는 좋은 학습인 것 같습니다 👍

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/global/exception/BusinessException.java
> +    HttpStatus status;
```suggestion
    private final HttpStatus status;
```

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/global/handler/GlobalExceptionHandler.java
> +        List<String> errors = new ArrayList<>();
메시지 생성하는 부분 좋네요 👍

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/global/jwt/JwtAuthorizationArgumentResolver.java
> +        UserInfo currentUser = jwtProvider.getClaim(authorizationHeader);
authorizationHeader가 null인 경우에는 NPE가 발생할 것 같네요~

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/global/validation/validator.java
> +public class validator {
참고로 이러한 클래스, 메서드, 변수 등의 네이밍 변경은 Shift + F6을 누르면 연관된 모든 곳에 일괄변경됩니다!
혹시 모르셨다면 참고 부탁드려요ㅎㅎ
```suggestion
public class Validator {
```

2024-07-05 14:55 UTC, MangKyu commented on src/main/java/gift/global/validation/validator.java
> +    public void validateDuplicateProduct(String name) {
Validtor에 지나치게 많은 부분이 들어가면 어떻게 할지도 고민해보시면 좋을 것 같습니당:)

2024-07-05 14:55 UTC, MangKyu commented
앞에 별도 PR도 올려주신 것 같은데, 여기서 한번에 코멘트 달도록 하겠습니다!

2024-07-05 15:21 UTC, MangKyu commented on src/main/java/gift/domain/product/ProductDTO.java
> +    @NotContainsValue(value = "카카오", message = "'{value}' 가 포함된 문구는 담당 MD 와 협의 후 사용 가능합니다.")
참고로 입력 데이터 부분은 애노테이션으로 처리하고, 비즈니스 정책에 대한 부분은 비즈니스 관련 클래스(Product)에 드러나는 것이 좋은 설계인 것 같습니다 ㅎㅎ 비즈니서 정책과 관련된 부분은 코드로 드러내어 우리의 정책을 쉽게 파악할 수 있어야 합니다!

2024-07-06 05:37 UTC, donghyuun commented on build.gradle
> +    implementation 'org.projectlombok:lombok'
넵 반영하겠습니다!

2024-07-06 05:38 UTC, donghyuun commented on src/main/java/gift/domain/product/ProductController.java
> +     * @return 결과 메시지, products (상품 목록)
저도 그렇게 생각합니다. 수정하겠습니다!

2024-07-06 05:46 UTC, donghyuun commented on src/main/java/gift/domain/product/ProductDTO.java
> +    @NotContainsValue(value = "카카오", message = "'{value}' 가 포함된 문구는 담당 MD 와 협의 후 사용 가능합니다.")
멘토님 말씀을 생각해보았는데,
현재 Product 코드는 id 속성을 가지고 있고, db 저장 시 id 값이 AUTO_INCREASE 로 자동 입력되고 있습니다. 
지금 상황에서 Product 클래스는 db에서 Product 를 조회할 때만 사용되고, 나머지 create, update 등은 productDTO 를 사용하고 있습니다. 따라서 입력값을 검증하려면 productDTO 에서 검증해야하는 상황입니다.

따라서 dto 가 실제로 비즈니스 로직에 사용되고 있는 상태인데, product 클래스에서 비즈니스 정책 관련 제약을 설정하고, dto 에서 해당 제약을 제외시키려면 어떤 식으로 수정하면 좋을지 궁금합니다.

2024-07-06 05:47 UTC, donghyuun commented on src/main/java/gift/domain/user/UserRepository.java
> +public class UserRepository implements UserRepositoryInterface {
인터페이스와 구현체의 개념, 사용법 등을 생각해보았을 때 멘토님이 말씀하신 네이밍이 적절한 것 같습니다. 수정하겠습니다.

2024-07-06 05:48 UTC, donghyuun commented on src/main/java/gift/global/jwt/JwtAuthorizationArgumentResolver.java
> +        UserInfo currentUser = jwtProvider.getClaim(authorizationHeader);
처리했습니다 감사합니다!

2024-07-06 05:49 UTC, donghyuun commented on src/main/java/gift/global/validation/validator.java
> +public class validator {
모르고 있었습니다. 감사합니다 ㅎㅎ

2024-07-06 05:51 UTC, donghyuun commented on src/main/java/gift/global/validation/validator.java
> +    public void validateDuplicateProduct(String name) {
해당 부분에 대해 조원과 얘기를 나누었는데, validatior 내부에 다양한 도메인의 메서드가 들어가게 되면 맡은 책임이 많아지고 가독성도 떨어질 것 같다는 생각이 들었습니다.

또한 저 부분은 db 에 접근하는 부분이고, 특정 도메인과 관련되어 있기 때문에 validator 가 아니라 해당 도메인의 repository 에서 구현하는게 좋을 것 같습니다.

2024-07-06 06:01 UTC, donghyuun commented on src/main/java/gift/global/annotation/NotContainsValueValidator.java
> + * NotContainsValue 어노테이션을 위한 유효성 검사기
메서드들이 많아지고 종종 헷갈리는 경우도 있어서 자세하게 주석을 두었지만, 지금은 의도만 설명하도록 변경하였습니다.
읽기 좋은 코드가 좋은 코드라는 말이 있듯이, 과제를 수행하면서 주석을 사용하지 않고 코드로만 설명이 가능하도록 코드 품질을 높여보겠습니다!

2024-07-06 06:01 UTC, donghyuun commented on src/main/java/gift/global/annotation/NotContainsValueValidator.java
> +public class NotContainsValueValidator implements ConstraintValidator<NotContainsValue, String> {
감사합니다!!

2024-07-06 06:03 UTC, donghyuun commented on src/main/java/gift/global/exception/BusinessException.java
> +    HttpStatus status;
놓치고 있었던 부분이었습니다. 감사합니다!

2024-07-06 06:17 UTC, donghyuun commented
리뷰 반영 사항 중 중점 내용 
1.  주석 간소화
2. 인터페이스, 구현 클래스 네이밍 수정
3. Product 의 서비스 클래스를 서비스 + 리포지토리 클래스로 레이어별 역할 세분화
4. authorization 헤더 NPE 핸들링
5. validation 유효성 검증 시 공통 클래스가 아니라,  관련 도메인 클래스 내에서 처리하도록 수정 
  ex) "validator" 내부에서 product 중복 검증 -> "product repository" 내에 구현
6. 기타 과제 요구사항(장바구니 추가, 조회, 삭제 + 관련 유효성 검증)
7. 롬복 의존성 제거 

질문
Q1
회원 가입 시 이메일 중복 여부를 검사한 후, 통과한 경우에만 회원 가입이 되게 코드를 짰을 때

로그인 시 해당 이메일을 가진 유저 정보를 DB 에서 찾을 때, 유저가 2명 이상 존재하는 경우를 고려해야 하는지 궁금합니다. 라이브 강의에서 옛날엔 레이어별로 개발자가 달라서 다 에러 처리를 해줬다고 하는데,

지금의 경우는 소수의 개발자가 프로세스를 이해하고, 유효성 검사를 적절히 하고 있는데, 모든 레이어에서 에러가 존재할 수 있다고, 문제가 발생할 수 있다고 가정하고 접근해야 하는지 궁금합니다.

- 로그인 과정에서 이메일 중복 검증(회원 가입 시 이미 중복 이메일 검증하는 과정 존재함) -
고려하는 경우
`
public boolean existsByEmail(String email) {
        String sql = "SELECT COUNT(*) FROM users WHERE email = ?";

        Integer count = jdbcTemplate.queryForObject(sql, Integer.class, email);

        if (count > 1) {
            throw new BusinessException(HttpStatus.INTERNAL_SERVER_ERROR,
                "서버에 동일한 이름의 회원 2명 이상 존재");
        }
        if (count == 1) {
            return true;
        }
        return false;
    }
`
고려하지 않는 경우(당연히 하나의 이메일에 하나의 유저만 있다고 가정)
`
public boolean existsByEmail(String email) {
        String sql = "SELECT COUNT(*) FROM users WHERE email = ?";

        Integer count = jdbcTemplate.queryForObject(sql, Integer.class, email);

        if (count == 1) {
            return true;
        }
        return false;
    }
`

2024-07-06 06:26 UTC, donghyuun commented on src/main/java/gift/domain/user/UserRepository.java
> +        if(count > 1) throw new BusinessException(HttpStatus.INTERNAL_SERVER_ERROR, "서버에 동일한 이름의 회원 2명 이상 존재");
말씀이 조금 이해가 되지 않아 질문 드립니다!
시스템에 대한 인지 부하를 초래하게 되는 것에 있어서 위  코드와 어떤 관련이 있는지 궁금합니다!
제가 생각한 바로는
1. 사용자의 인터페이스에서 서버 문제를 확인할 수 있는 것은 옳지 않다 (해당 메시지가 브라우저 화면에 보이게(alert) 작성하였음)
2. 서버가 당연히 일어나지 않아야 할 동작에 대해 핸들링 하는 코드를 작성하는 것은 옳지 않다..? 

위와 같은 말씀이신건가요? 알려주시면 감사하겠습니다!

2024-07-06 17:13 UTC, MangKyu commented
리뷰 반영하시느라 너무 고생 많으셨습니다ㅎㅎ 추가적으로 질문 주신 부분 답변드리겠습니다!
잠금을 이용해 동시성 제어를 하여, 2개 이상의 이메일이 존재하지 않음을 보장할 수 있다면 이를 고려하지 않아도 됩니다!
하지만 저라면 해당 메서드를 작성할 때, 다음과 같이 고려하여 방어적으로 프로그래밍을 할 것 같습니다ㅎㅎ
```java
public boolean existsByEmail(String email) {
        String sql = "SELECT COUNT(*) FROM users WHERE email = ?";
        Integer count = jdbcTemplate.queryForObject(sql, Integer.class, email);
        
        return count >= 1;
```

2024-07-06 17:15 UTC, MangKyu approved these changes
리뷰 반영하시느라 너무 고생 많으셨습니다ㅎㅎ 추가적으로 질문 주신 부분 답변드리겠습니다!
잠금을 이용해 동시성 제어를 하여, 2개 이상의 이메일이 존재하지 않음을 보장할 수 있다면 이를 고려하지 않아도 됩니다!
하지만 저라면 해당 메서드를 작성할 때, 다음과 같이 고려하여 방어적으로 프로그래밍을 할 것 같습니다ㅎㅎ 이를 통해 위에 적었던 메서드 인지 부하도 줄일 수 있습니다!

```java
public boolean existsByEmail(String email) {
        String sql = "SELECT COUNT(*) FROM users WHERE email = ?";
        Integer count = jdbcTemplate.queryForObject(sql, Integer.class, email);
        
        return count >= 1;
```        

비즈니스 정책을 도메인에 표현하는 부분만 반영해주시면 좋을 것 같네요! 👍 
지금 상태로도 괜찮을 것 같아서, 일단 Approve 상태로 변경해두겠습니다ㅎㅎ 천천히 추가 변경 원하시는 부분 있으면 반영해주세요~

2024-07-06 17:15 UTC, MangKyu commented on build.gradle
> +    implementation 'io.jsonwebtoken:jjwt:0.12.6'
최신 버전의 jjwt 라이브러리 사용 👍

2024-07-06 17:15 UTC, MangKyu commented on src/main/java/gift/domain/product/ProductRepository.java
> +    void addProductToCart(Long userId, Long productId);
여기는 데이터 관리를 위한 ProductRepository인데 비즈니스적인 메서드들이 보이는 것 같네요ㅎㅎ
중요하지 않으니 천천히 이러한 기준에 대해서도 생각하고 정리해보시면 좋을 것 같습니다!

2024-07-06 17:15 UTC, MangKyu commented on src/main/java/gift/global/annotation/NotContainsValueValidator.java
> + * NotContainsValue 어노테이션을 위한 유효성 검사기
좋습니다ㅎㅎ 설명해주셔서 감사합니다:)

2024-07-06 17:15 UTC, MangKyu commented on src/main/java/gift/domain/product/ProductDTO.java
> +    @NotContainsValue(value = "카카오", message = "'{value}' 가 포함된 문구는 담당 MD 와 협의 후 사용 가능합니다.")
DTO는 Data Transfer Object의 약자로, 계층 간에 데이터 전달을 위해서 사용됩니다!
따라서 간의 전달이 되었다면 우리의 비즈니스를 나타내는 Product로 변경해줄 필요가 있습니다ㅎㅎ 즉, 다음과 같은 흐름으로 처리되는 것이 바람직하다고 볼 수 있습니다!
1. 클라이언트의 입력을 ProductDTO로 받음
2. 이때 입력 유효성 검사를 처리함
3. 비즈니스 로직 처리(Product 저장, 수정 등) 처리를 위해 Product로 변환함
4. 이때 Product에 대한 비즈니스 유효성 검사를 처리함
5. Product를 기준으로 데이터를 저장 또는 수정함

2024-07-06 17:15 UTC, MangKyu commented on src/main/java/gift/domain/user/UserRepository.java
> +        if(count > 1) throw new BusinessException(HttpStatus.INTERNAL_SERVER_ERROR, "서버에 동일한 이름의 회원 2명 이상 존재");
해당 메서드를 사용하는 사용자의 입장에서는 개수가 1개이든 2개이든 100개이든 상관없이 존재하면 true를 반환할 것이라고 생각할 것입니다! 그런데 1개보다 많다고 에러를 반환하는 것은 해당 메서드를 사용하는 입장에서 기대하지 못한 에러일 것이므로 인지부하를 초래할 수 있습니다:)

2024-07-06 17:15 UTC, MangKyu commented on src/main/java/gift/global/validation/validator.java
> +    public void validateDuplicateProduct(String name) {
repository는 영속성 계층을 나타내는 부분이므로 도메인 내부 즉, product에서 관리하는 방법이 있습니다!
Product 객체의 생성 시점에 검사하게 되면, 모든 Product 객체에 대한 제약 조건을 보장할 수 있을 뿐 아니라 Product 내에서 비즈니스 정책이 관리되므로 훨씬 관리가 용이해질 수 있습니다:)

2024-07-07 02:30 UTC, donghyuun commented on src/main/java/gift/domain/product/ProductRepository.java
> +    void addProductToCart(Long userId, Long productId);
생각해보니 JPA 를 사용했을 때, 엔티티별로 레포지토리를 사용했던 것처럼,
유저별 장바구니 상품도 따로 레포지토리를 만드는게 비즈니스 메서드를 포함시키지 않는 방법인 것 같습니다. 감사합니다!

2024-07-07 12:02 UTC, donghyuun commented
멘토님께서 전날 새벽에 남겨주신 리뷰 사항 및 추가 사항을 반영하였습니다.
- 비즈니스 로직에서는 DTO 를 비즈니스 클래스로 변경하여 사용
- 장바구니 아이템(id, user_id, product_id) 을 도메인으로 가지는 레이어별 클래스 생성 
- DTO 는 입력 데이터 검증을, 비즈니스 클래스는 비즈니스 정책 검증을 하도록 반영

**질문**

**Q1**
Product 생성 시 이름 중복 검사를 하려면 생성자에서 ProductRepository 를 사용하게 되는데 이것이 적절한 방법인지 궁금합니다.
저는 Product 를 생성하기 전에 아래 예시와 같이 유효한 비즈니스 정책값인지 검사 후, 검사를 통과하였을 때 Product 를 생성토록 하였습니다.
따라서 Product 는 항상 비즈니스 정책에 적합한, 유효한 데이터만 가지고 있도록 하였습니다.

예시: 서비스에서 비즈니스 정책 검사 후, Product 를 생성하여 Repository 에 넘겨줌
```
public void createProduct(ProductDTO productDTO) {
        if (productRepository.existsByProductName(productDTO.getName())) {
            throw new BusinessException(HttpStatus.BAD_REQUEST, "해당 이름의 상품이 이미 존재합니다.");
        }

        Product product = productDTO.toProduct();
        productRepository.createProduct(product);
    }
```  

**Q2**
장바구니에 관련된 로직을 따로 빼서 생성하였습니다(CartItemDTO, CartItem, Controller, Service, Repository)
장바구니 테이블은 CART 이며,  내부적으로 ID, 사용자ID, 상품ID 만을 가지고 있습니다.

장바구니 관련 행위에서 사용자 ID는 따로 JWT 를 통해 사용자 ID 값을 추출해서 사용하는 터라 CartItemDTO 가 따로 사용되지 않습니다. 또한, 장바구니는 중간 연결 테이블로서 장바구니 상품 추가 시 사용자 id, 상품 id 만을 저장하는데, 비즈니스 클래스(CartItem)가 필요한지도 궁금합니다.

비즈니스 클래스로 CartItem 을 사용하게 된다면, Repository 에 상품을 추가할 때는 CartItem 을, 상품을 꺼낼 때는 실제 상품인 Product 를 꺼내게 되는데, 들어갈 때와 나올 때의 비즈니스 클래스 객체 타입이 달라 적절한 구현인지 의문이 듭니다. 
그래서 아예 CartItemDTO, CartItem 을 사용하지 않고 있는데, 제가 적절히 구현했는지 멘토님의 의견을 듣고 싶습니다.

2024-07-07 14:35 UTC, MangKyu approved these changes
조금 더 개선이 필요한 부분들이 있지만, step2는 이쯤 하고 넘어가도록 하죠ㅎㅎ
고생많으셨습니다! 🙇마지막으로 질문 남겨주신 부분들 코멘트 남겨드리겠습니다!
(도메인 로직 검사 부분만 추후에 개선하면 좋을 것 같아요! 일단 선머지 하겠습니다)

말씀해주신대로 장바구니를 통한 상품의 조회이기 때문에 최종적으로 상품이 조회되는 것인데요~
이러한 상황이라면 cart를 별도의 도메인(쉽게 얘기하여 패키지)로 분리시킬만한 비즈니스 적인 가치가 있는지를 의사결정할 필요가 있습니다! 현재의 요구사항 기준으로 보았을 때에는 cart를 별도의 패키지로 분리시킬 필요 없이 product라는 도메인 내에서 관리하도록 의사결정해도 괜찮을 것 같습니다ㅎㅎ

2024-07-07 14:35 UTC, MangKyu commented on src/main/java/gift/domain/product/Product.java
> +    @NotContainsValue(value = "카카오", message = "'{value}' 가 포함된 문구는 담당 MD 와 협의 후 사용 가능합니다.")
해당 유효성 검사는 동작하지 않을 것 같은데요ㅎㅎ 자세한 내용은 [해당 포스팅](https://mangkyu.tistory.com/174)을 통해서 참고 부탁드리겠습니다! 혹시 이해가 가지 않으면 말씀해주세요ㅎㅎ
이러한 도메인 객체 내에서의 유효성 검사는 일반적으로 객체의 생성 시점에 진행합니다!

2024-07-07 14:35 UTC, MangKyu commented
혹시 추가적인 궁금증이 또 있다면 언제든지 편하게 질문 남겨주세요:)

2024-07-07 14:35 UTC, merged