전남대 BE_유보민 2주차 과제(Step3)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #385
Opened 2024-07-05 08:55 UTC by rbm0524

아직 3단계 구현을 다 하지 못했습니다. 추후 더 작성하겠습니다. 가능하시다면 HandlerMethodArgumentResolver를 사용하는데 있어 로직의 순서를 알려주실 수 있으신가요? 감이 잡히지 않습니다.

2024-07-06 09:57 UTC, gunom commented
> 아직 3단계 구현을 다 하지 못했습니다. 추후 더 작성하겠습니다. 가능하시다면 HandlerMethodArgumentResolver를 사용하는데 있어 로직의 순서를 알려주실 수 있으신가요? 감이 잡히지 않습니다.

안녕하세요 보민님! HandlerMethodArgumentResolver의 동작 방식에 대해 알기 위해선 스프링에 요청이 들어오는 순서를 알아야합니다. 

1. 클라이언트 요청: 클라이언트가 HTTP 요청을 보냅니다.

2. DispatcherServlet: 스프링의 DispatcherServlet이 요청을 받아 적절한 핸들러로 전달합니다. DispatcherServlet은 모든 HTTP 요청을 받아서 처리하는 프론트 컨트롤러 역할을 합니다.

3. HandlerMapping : DispatcherServlet은 요청을 처리할 수 있는 핸들러를 찾기 위해 여러 HandlerMapping을 조회합니다. HandlerMapping은 요청 URL과 매핑되는 컨트롤러 메서드를 찾는 역할을 합니다.

4. HandlerAdapter : 적절한 핸들러(컨트롤러 메서드)를 찾으면, DispatcherServlet은 해당 핸들러를 실행하기 위해 HandlerAdapter를 사용합니다. HandlerAdapter는 핸들러를 호출하는 방법을 알고 있는 객체입니다.

HandlerAdapter는 Controller를 호출하기 전에, 메서드의 파라미터를 처리하기 위해 여러 HandlerMethodArgumentResolver를 사용합니다.

HandlerMethodArgumentResolver는 supportsParameter 메소드를 통해 해당 파라미터를 지원하는지 체크하고 지원한다면, resolveArgument메소드를 호출하여 지정하고 싶은 파라미터로 변환하는 작업을 수행할 수 있습니다. 이번 3단계에서 생각해본다면 요청이 들어오고 WishListController에 가기 전에 LoginMemberArgumentResolver를 만날 것입니다. WishListController의 parameter중 LoginMember가 있다면, LoginMemberArgumentResolver에서는 supportsParameter를 통해 LoginMember에 대한 파라미터가 있음을 확인하고, resolveArgument 메소드를 호출합니다.
resolverArgument 메소드 내부에서는 LoginMember 파라미터의 내부를 채워줄 로직을 작성하고 리턴하시면, WishListController에서는 LoginMember 객체를 사용할 수 있게 되는 것이죠. 힌트를 드리자면 resolverArgument에서는 WebRequest를 파라미터로 받으므로 Header를 들여다볼 수 있습니다~ 그렇다면 LoginMember 객체를 생성할 정보를 어떤 헤더에서 가져온다면, jwtUtil을 통해 LoginMember 객체를 만들 때 사용할 수 있겠죠?

2024-07-06 09:58 UTC, gunom requested changes
안녕하세요 보민님! 3단계의 Resolver를 사용하는 건 처음 스프링을 배우면 당연하게도 어렵고 이해하기 쉽지 않은 내용입니다! resolver의 동작 순서와 작동하는 과정을 적어놓았으니 보시고 다시한번 도전해봐주세요! 혹시라도 이해안가는 용어나 단어가 있다면 바로 물어봐주세요! 화이팅입니다!

2024-07-07 08:14 UTC, gunom commented
> 2단계에서 JWT를 사용했었지만 3단계를 진행하면서 잘되지 않아 Basic 인증으로 바꿨는데 다시 JWT를 사용하는 것으로 방향을 잡았습니다. 토큰을 발급하고 Decode하고 Cookie에 저장하는 방식으로 구성했습니다. 3단계도 토큰을 사용해 사용자 정보를 추출하고 사용자id에 대한 위시 리스트를 불러오는 것으로 작성했습니다. 잘 작동하는 것 같지만 부족한 부분이 많은 것 같습니다.
> 
> 2단계에서 피드백을 받았던 부분을 시간 부족으로 모두 반영하지는 못했습니다. 그래서 3단계까지 먼저 완료한 후 PR을 보내고 추후 더 수정할 계획입니다. 2단계의 피드백 중 @Qualifer를 왜 사용했냐고 하셨습니다. 이것은 제가 스프링을 다루는데 능숙하지 못해서 직접 Qualifer를 주어서 어떤 Bean을 넣을지 확실하게 해주고 싶어서 그랬습니다. 스프링에 대한 이해도를 높인다면 스스로도 Qualifer를 적절한 상황에서만 사용하게될 것 같습니다.
> 
> > ResponseEntity를 이용해 응답 코드를 함께 반환하고 html에서 json 형태로 받은 것을 보여주는 방식이 더 나은가요? String으로 페이지를 반환하고 model을 통해 사용자에게 보여줄 값을 지정하다보니 요구사항과는 맞지 않는 느낌이 듭니다.
> 
> 제가 이렇게 질문했었습니다. ExceptionHandler를 통해 Controller 외부에서 http 반환을 지정할 수 있고 그렇게 응답 코드를 반환하게 해도 될 것이라 생각합니다. 제가 헷갈렸던 부분은 'ResponseEntity에서 http 응답 코드를 보낼 수 있는데 반환타입이 String이라면 어떻게 응답 코드를 보내지?'라고 생각하여 저렇게 질문했던 것이었습니다. 이렇게 ExceptionHandler를 통해 응답 코드를 보내도록 해도 될까요?
> 
> Step 3에 Step2 부분들까지 수정한 부분들을 push했는데 이전에 열었던 Step2가 merge된 상태가 아닙니다. Step3의 branch를 merge해주신다면 Step2의 branch는 어떻게 하면 될까요?

1. Qualifier는 보통 같은 인터페이스를 구현하는 구현체가 여러 개 존재하는 경우, 특정 구현체를 지정하려고 사용합니다. 저도 스프링을 처음 배울 때, 스프링의 동작방식은 너무 흑마법같아서 쉽게 쉽게 납득이 안갔었습니다. 점점 공부하시면서 이해하는 폭이 넓어지실테니 화이팅하시길 바랍니다!

2. ResponseEntity에 스트링만 담더라도 기본적으로 200의 상태코드를 갖습니다. 추가로 응답코드를 수정하고 싶다면, ResponseEntity에 ok()메소드 혹은 다른 statusCode를 담을 수 있는 메소드들이 존재하므로 반환하는 타입과 무관하게 status코드는 사용할 수 있습니다.

3. 앞으로의 과제는 안내받으신대로 요일마다 마감기한이 생긴 것으로 알고 있습니다. 이번 건은 step3에서 반영사항 확인하고 step2도 머지해드리겠습니다 :)

2024-07-07 08:31 UTC, gunom requested changes
안녕하세요 보민님 3단계 잘해주셨습니다! Resolver의 동작 순서에 대해서는 이해하신 거 같네요! 하지만 조금 더 좋은 사용법으로 바꿀 수 있을 거 같아 코멘트 남겼습니다! 스프링이 처음이라 어려우시겠지만 우선, 클래스의 역할과 책임을 위주로 고민하시면 과제를 수행하실 때 더 좋은 코드로 작성하실 수 있을 거 같아요! 많이 어려우시겠지만 파이팅입니다!
오늘까지 최종적으로 고쳐주시면 해당 코드로 머지할테니 제출기한 여부와 상관없이 한번 원하는 만큼 고쳐보시면 좋을 거 같아요 :)

2024-07-07 08:31 UTC, gunom commented on src/main/java/gift/Annotation/WishListResolverHandlerMethodArgumentResolver.java
> +        return wishListItem;
해당 코드는 WishListItem에 대한 parameter를 바인딩해주는 코드로 보이네요! https://edu.nextstep.camp/s/dGx30MLc/ls/TE5CO37P 강의의 hint를 보면 LoginMember에 대해서 바인딩해주는 모습을 볼 수 있는데, 작성해주신 코드도 요구사항을 만족시키는데는 문제가 없지만, 해당 코드를 User정보가 필요한 다른 컨트롤러에서는 사용하지 못한다는 단점이 존재할 것 같습니다.
또한 WishList와 강하게 결합되다 보니, Header만 참조해도 되는 코드에서 RequestBody까지 확인하는 결합도 생기네요. Resolver의 역할은 parameter를 꺼내오는 코드 중복을 줄이기 위함이 큽니다. 그러므로 조금 더 제네릭하게 사용할 수 있는 user정보만 다루면 다른 컨트롤러에서도 유저정보만 처리할 수 있게 되니 더욱 높은 효율을 보이겠죠?

2024-07-07 08:31 UTC, gunom commented on src/main/java/gift/Controller/UserController.java
> +            Cookie cookie = new Cookie("token", token);
쿠키를 통해 token을 전달하는 방식 아주 좋습니다 👍 해당 쿠키와 관련된 로직을 utils 패키지를 따로 만들어 분리하면 더 좋은 코드가 될 거 같아요!

2024-07-07 08:31 UTC, gunom commented on src/main/java/gift/Controller/UserController.java
> +            String token = jwtUtil.generateToken(authenticatedUser, isAdmin);
isAdmin과 authenticatedUser 모두 userService 내부에 있으니 userService 내부에서 jwtUtil을 사용해보면 어떨까요?

2024-07-07 08:31 UTC, gunom commented on src/main/java/gift/Controller/WishListController.java
> +        Cookie jwtCookie = WebUtils.getCookie(request, "token");
앞서 리뷰한 부분처럼 WishListResolver가 아니라 LoginMemberResolver라면 쿠키에서 token을 통해 user를 얻어오는 부분을 중복없이 사용할 수 있을 거 같아요!

2024-07-07 08:31 UTC, gunom commented on src/main/java/gift/Controller/WishListController.java
> +        return "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
WishListController의 책임이 signingKey를 반환하는 메소드를 가지고 있어야하는지 고민해본다면, WishListController보다 JwtUtils가 들고 있어야 책임이 분명하겠죠 :) 그 코드 내부에서도 @Value나 ConfigurationProperties를 통해 application.properites에서 관리되어야 합니다! 보안을 위해서 말이에요!

2024-07-07 08:32 UTC, gunom commented
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/261 제가 코멘트 남기고 올리지 못한게 있어서 RequestMapping에 대한 코멘트 확인해주시면 감사하겠습니다!

2024-07-07 13:23 UTC, rbm0524 commented on src/main/java/gift/Annotation/WishListResolverHandlerMethodArgumentResolver.java
> +        return wishListItem;
WishList에 대해 따로 Resolver를 작성한 이유는 userId와 product의 정보들을 혼합하여 가지는 객체가 필요하다고 생각해서 그랬습니다. 피드백해주신 내용처럼 User정보가 필요한 다른 Controller에서도 사용하긴 어렵다고 생각이 듭니다. 그렇다면 User에 대한 인증을 처리하기 위해 LoginMemberArgumentResolver를 하나 더 만들어서 처리하는 것이 더 나을까요? 
------
더 생각해보니 Product에 대한 정보는 사용자로부터 숨겨야만 하는 정보는 아닌 것 같습니다. 그래서 토큰을 통해 인증만 한다면 토큰으로부터 userId를 가져오고 제품에 대한 정보는 JSON으로 받아오면 될 것 같은데 이것이 더 정리된 방법인가요?

2024-07-07 13:31 UTC, rbm0524 commented on src/main/java/gift/Annotation/WishListResolverHandlerMethodArgumentResolver.java
> +        return wishListItem;
그리고
<WishList와 강하게 결합되다 보니, Header만 참조해도 되는 코드에서 RequestBody까지 확인하는 결합도 생기네요.
이렇게 말씀해주셨는데 인증이 목적이라면 토큰에서 추출한 userId(또는 식별 가능한 무언가)를 통해 db에서 찾아서 해당 객체를 리턴하게 된다면 결합도도 낮출 수 있을까요? db에 존재하지 않는다면 미인증 사용자가 되니 사용자를 구분할 수 있을 것 같습니다.

2024-07-07 15:00 UTC, gunom commented on src/main/java/gift/Annotation/WishListResolverHandlerMethodArgumentResolver.java
> +        return wishListItem;
1. 네 보민님이 추가로 남겨주신 것과 같이 requestBody로 제품 정보를 받아오면 좋을 거 같습니다!
2. 맞습니다. userId를 UserService에 넘겨 UserRepository에서 찾아오는 것은 Resolver에서 사용하고 RequestBody에 대한 책임은 WishListController가 책임을 지게 되는 것이죠.

2024-07-07 15:01 UTC, gunom commented
@rbm0524 충돌해결해주시면 감사하겠습니다~

2024-07-07 15:05 UTC, gunom commented on src/main/java/gift/Repository/WishListRepository.java
> +        if (currentCount != null && currentCount > quantity) {
이런 비즈니스 로직을 service로 올린다면 repository에 책임이 DB와 상호작용하는 것으로 줄일 수 있을 거 같아요~

2024-07-08 05:50 UTC, rbm0524 commented on src/main/java/gift/Controller/UserController.java
> +            String token = jwtUtil.generateToken(authenticatedUser, isAdmin);
isAdmin과 authenticate는 사용자가 email과 password로 로그인을 할 때
1. 유효한 사용자인지 판단, 인증되었다면 토큰 발급
2. 관리자인지 판단
이렇게 구성했습니다. isAdmin과 findByEmail에서 jwtUtil을 사용하게 되면 토큰 발급 이후에 유효한 사용자인지 검증하게 될 것 같아서 명쾌하게 로직이 짜여지지 않는 것 같습니다.
jwtUtil을 사용하려면 어떤 순서가 좋은가요?

2024-07-08 06:12 UTC, rbm0524 commented on src/main/java/gift/Repository/WishListRepository.java
> +        if (currentCount != null && currentCount > quantity) {
WishListRepository에서 jdbcTemplate을 사용해서 Repository에서 수행하도록 했습니다. 이것이 Service로 올라온다면 Service에서도 jdbcTemplate을 사용해서 count값을 가져와야할 것 같습니다. 제가 짠 코드의 removeWishListItem에서 인자로 받은 WishList 객체는 사용자가 WishList에 담은 수량에서 감소시켜야할 count값을 가지고 있기 때문에  currentCount를 sql문으로 따로 가져와야 합니다.
그러면 Repository의 책임을 Service가 지게 되는데 분기를 정해주는 책임은 Service에서 해야하는 것 같아서 어디에 두는 것이 맞는지 헷갈립니다.

더 생각을 해보았는데 wishlist.html에서 JSON으로 요청을 보낼 때 사용자가 담았던 상품의 수량도 함께 전송할 수 있을 것 같습니다. 그렇다면 Service에서 sql문을 사용하지 않아도 분기를 정해줄 수 있을 것 같습니다. 제가 수정을 한다면 이렇게 수정할 것 같은데 멘토님은 어떻게 수정하실지 궁금합니다.

2024-07-08 14:34 UTC, closed without merging