경북대 BE_박준석 2주차 과제 (2, 3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #387
Opened 2024-07-05 08:56 UTC by Lucerna00

2단계와 3단계의 위시 리스트 조회 및 상품 추가까지 구현하였습니다.
1단계 피드백을 계속 반영하며 예외 처리 및 위시 리스트 상품 수정, 삭제를 빠르게 구현하겠습니다.

Q. 서버에서 토큰을 발급해 주면 클라이언트가 직접 Authorization에 해당 토큰을 넣어 요청하는 방식이 맞는지 궁금합니다.
Q. 패키지를 적절히 나누고 Argument Resolver를 만들어 활용해 보았는데 패키지명이 적절한지,  Argument Resolver를 이렇게 사용하는 것이 맞는지 궁금합니다.

2024-07-05 18:51 UTC, gongdongho12 requested changes
> Q. 서버에서 토큰을 발급해 주면 클라이언트가 직접 Authorization에 해당 토큰을 넣어 요청하는 방식이 맞는지 궁금합니다.

넵 맞습니다 (관련해서 프론트쪽 js 코드도 찾아보시면 도움이될거에요!)
백엔드라고 프론트를 완전히 놓기보다는 실제 사용에 대해 알고 작업하면 많은 도움이 됩니다

> Q. 패키지를 적절히 나누고 Argument Resolver를 만들어 활용해 보았는데, 적절한 패키지명인지와 Argument Resolver를 이렇게 사용하는 것이 맞는지 궁금합니다.

사용 방식은 맞긴합니다! 다만 실제 스프링 시큐리티 사용 예시를 파악해서 좀 더 개선해볼 여지는 보이네요 ㅎㅎ

> Q. ProductDTO로 PUT 할 때 DTO에 있는 id를 활용하지 못한다는 피드백을 받았습니다. 그러면 클라이언트가 입력한 상품 정보에 해당하는 DTO를 따로 만들어 진행하는 것도 하나의 방법일까요? (현재는 PUT 할 때 DTO에는 id 정보가 없습니다.)

어짜피 지금은 API를 직접 만들고 프론트도 전부 만드는 상황이면, id라는 path 없이 그냥 DTO만 보내는 것도 방법인데요
이 부분은 FE와 BE의 작업자가 본인이라는 관점에서 어떤 부분이 편할지 고민해서 진행해주시면 좋을 것 같습니다 (실제 현업에서도 어떤게 좋고 나쁜지 방향을 정하게 될건데 미리 해보는 것 처럼요 😄)

많은 부분 작성해주시느라 고생하셨습니다

2024-07-05 18:51 UTC, gongdongho12 commented on src/main/java/gift/argumentresolver/LoginMemberArgumentResolver.java
> +        String accessToken = authorization.substring(7);
이러면 Authorization 헤더에
`abcded ${token}` 이라도 통과하지 않을까요?

2024-07-05 18:51 UTC, gongdongho12 commented on src/main/java/gift/argumentresolver/LoginMemberArgumentResolver.java
> +        String accessToken = authorization.substring(7);
인증은 사실 보안에 직결되는 부분이자나요
되도록이면 테스트 작성해주시면 좋을 것 같아요

테스트는 주로 **보안, 중요도, 비지니스 로직** 등에 작성합니다!

2024-07-05 18:51 UTC, gongdongho12 commented on src/main/java/gift/dto/ProductDTO.java
> +    @Size(max = 15, message = "상품 이름은 공백을 포함하여 최대 15자까지 입력할 수 있습니다.")
이렇게 사이즈를 지정해줬는데 본인이 작성해준 schema.sql의 사이즈와 일치시켜주는 것도 중요한 것 같습니다

실제 서비스를 할 때, DB의 리소스를 감소시킬 수 있는 부분이니까요

2024-07-05 18:51 UTC, gongdongho12 commented on src/main/java/gift/dto/ProductDTO.java
> +    int price,
int는 음수도 들어갈 수 있는데 가격이 음수면 돈 주고파는 건데 잘 체킹해주셨네요 👍🏼

2024-07-05 18:51 UTC, gongdongho12 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
지금은 이 에러를 상품만 써서 상품으로 작성주신 것 같은데요
MethodArgumentNotValidException 에러 자체에 에러메시지로 detail을 채워주시는게 좋지 않을까요?

2024-07-05 18:51 UTC, gongdongho12 commented on src/main/java/gift/service/MemberService.java
> +    }
내부에 대한 조건을 validation 객체를 상속받거나 Spring Validation Annotation 에서 처리하면 좋지 않을까요?

2024-07-05 18:51 UTC, gongdongho12 commented on src/main/java/gift/service/MemberService.java
> +    }
서비스는 로직 흐름만 이해하게끔요
그래야 본인 말고도 타인이 보았을 때 수정하기 용이하지 않을까요?

2024-07-05 18:51 UTC, gongdongho12 commented on src/main/java/gift/repository/ProductDAO.java
> +public class ProductDAO {
DAO가 Repository에 있는데 패키지명을 한번 고민해보시면 좋을 것 같습니다
실제 타 스프링 프로젝트들을 참고해서 관련 부분 찾아보시면 좋을 것 같아요

2024-07-05 18:51 UTC, gongdongho12 commented on src/main/java/gift/util/JwtProvider.java
> +    public JwtProvider(@Value("${jwt.access_token_expiration_time}") long accessTokenExpirationTime) {
만료 시간을 jwt.access_token_expiration_time로 처리한 부분이 좋네요!

2024-07-05 18:51 UTC, gongdongho12 commented on src/main/java/gift/util/JwtProvider.java
> +    }
이 로직에 대한 테스트 있으면 좋겠죠?

2024-07-05 18:51 UTC, gongdongho12 commented on src/main/java/gift/util/JwtProvider.java
> +    private final long accessTokenExpirationTime;
실제 서비스 하게되면 DB는 고정인데 키가 바뀌는 방식일거고 서버의 인스턴스 수도 늘어나면 각 인스턴스의 인증 체계가 달라질 수 있는데요

저 키를 DB에 1회 넣어주고 로컬 캐시로 참조하는 방향도 있고 아래처럼 properties에 넣는 방법도 있는데

고민해서 적용해보면 좋을 것 같습니다

2024-07-07 03:38 UTC, Lucerna00 commented on src/main/java/gift/argumentresolver/LoginMemberArgumentResolver.java
> +        String accessToken = authorization.substring(7);
Bearer 관련 예외 처리를 추가하였습니다.

테스트는 지금까지 제가 postman으로 했었는데, Mockito에 대해 알아보며 사용해 보겠습니다.

2024-07-07 03:39 UTC, Lucerna00 commented on src/main/java/gift/dto/ProductDTO.java
> +    @Size(max = 15, message = "상품 이름은 공백을 포함하여 최대 15자까지 입력할 수 있습니다.")
schema.sql에서 product name에 대한 타입을 VARCHAR(15)로 수정하였습니다.

2024-07-07 03:43 UTC, Lucerna00 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
getMessage로 detail 내용을 채우면
```
"detail": "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<gift.dto.ProductDTO> gift.controller.ProductController.addProduct(gift.dto.ProductDTO) with 3 errors: [Field error in object 'productDTO' on field 'name': rejected value [카카오%]; codes [Pattern.productDTO.name,Pattern.name,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [productDTO.name,name]; arguments []; default message [name],[Ljakarta.validation.constraints.Pattern$Flag;@39e836b2,^(?!.*카카오).*$]; default message ['카카오'가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있습니다.]] [Field error in object 'productDTO' on field 'price': rejected value [-10]; codes [Positive.productDTO.price,Positive.price,Positive.int,Positive]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [productDTO.price,price]; arguments []; default message [price]]; default message [상품 가격은 양수이어야 합니다.]] [Field error in object 'productDTO' on field 'name': rejected value [카카오%]; codes [Pattern.productDTO.name,Pattern.name,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [productDTO.name,name]; arguments []; default message [name],[Ljakarta.validation.constraints.Pattern$Flag;@39e836b2,^[ㄱ-ㅎㅏ-ㅣ가-힣a-zA-Z0-9 ()\\[\\]+\\-&/_]*$]; default message [한글, 영어, 숫자, 특수 문자 ( ), [ ], +, -, &, /, _ 만 가능합니다.]] "
```
내용이 복잡하고 제가 설정한 object 프로퍼티와 겹치는 내용이 많은데,
따로 메시지를 가공할 필요가 있을까요?
아니면 정말 detail에 대한 내용이니 그대로 둬도 될까요?

2024-07-07 03:45 UTC, Lucerna00 commented on src/main/java/gift/service/MemberService.java
> +    }
커스텀 어노테이션을 만들어 새 비밀번호 확인에 대한 유효성 검사를 하였고,
비밀번호 유효성 검사는 따로 private 메서드를 만들어 중복된 코드를 제거하였습니다.

2024-07-07 03:49 UTC, Lucerna00 commented on src/main/java/gift/repository/ProductDAO.java
> +public class ProductDAO {
DAO와 Repository의 차이점에 대해 잘 모르고 있었습니다.
둘 다 데이터 처리와 관련 있어 혼용해서 사용하였는데,
이번 과정을 통해 DAO는 Data Persistence의 추상화 (테이블 중심으로 추상화)이며
Repository는 도메인 객체 collection의 추상화 (객체 중심으로 추상화)임을 알게 되었습니다.
아직은 크게 와닿지 않아 조금 더 찾아보며 공부하겠습니다.

2024-07-07 03:50 UTC, Lucerna00 commented on src/main/java/gift/util/JwtProvider.java
> +    }
Mockito를 다루어 보며 테스트를 진행하도록 하겠습니다.

2024-07-07 03:56 UTC, Lucerna00 commented on src/main/java/gift/util/JwtProvider.java
> +    private final long accessTokenExpirationTime;
여러 인스턴스에서 키가 달라질 수 있는 점을 고려하지 못했네요..
말씀대로 access_token_expiration_time처럼 properties에 secret key를 넣었습니다.

2024-07-07 04:27 UTC, Lucerna00 commented
피드백을 반영하고 3단계 위시 리스트 상품 수정, 삭제를 구현해 보았습니다.

Q. 위시리스트의 상품(wished product)은 member, product와 foreign key로 연결되어 있습니다. member는 인증 과정을 거치기에 참조 무결성을 지킨다고 생각하지만, 존재하지 않는 상품으로 요청하면 어떻게 예외 처리를 해야 할지 잘 모르겠습니다. 지금은 WishedProduct 서비스에 ProductDAO를 주입하여 productDAO.getProduct를 수행하고 있는데, 이 방법도 맞는지 궁금합니다.

2024-07-07 16:06 UTC, gongdongho12 approved these changes
DAO 개념은 JPA가 적용되었을 떄 의미있는 개념이라 이번 주차에서는 넘어가겠습니다

> Q. 위시리스트의 상품(wished product)은 member, product와 foreign key로 연결되어 있습니다. member는 인증 과정을 거치기에 참조 무결성을 지킨다고 생각하지만, 존재하지 않는 상품으로 요청하면 어떻게 예외 처리를 해야 할지 잘 모르겠습니다. 지금은 WishedProduct 서비스에 ProductDAO를 주입하여 productDAO.getProduct를 수행하고 있는데, 이 방법도 맞는지 궁금합니다.

DB에서 FK로 지정되어있으면 실제 상품이 있어야 연결이 됩니다! 말씀주신 부분은 직접 API에 실행하고 h2-console로 확인해보시면 좋을 것 같습니다

그리고 DAO는 레포지토리가 아니라 JPA가 적용되고 영속성 개념이 들어갈 때 확립될 수 있는 부분입니다
-> 강의는 김영한님의 JPA를 추천드리구요 (홍보 X), 이번 주차에서는 크게 문제짚지 않구 넘어가겠습니다

2024-07-07 16:24 UTC, Lucerna00 commented
3주 차부터 JPA를 다루어볼 거 같은데 열심히 알아보겠습니다.

충돌 해결하였고 매번 늦은 시간까지 피드백 주셔서 감사합니다!

2024-07-08 13:45 UTC, merged