경북대 BE_장우석 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #390
Opened 2024-07-05 08:57 UTC by us4c0d3

2단계 피드백을 아직 받지 못해 step2 브랜치에서 추가적으로 진행했습니다. 다만 아직 기능 개발을 완료하지 못했습니다.

### 3단계 기능 개발

- [x] 사용자 위시리스트 조회
- [ ] 사용자 위시리스트 추가
- [ ] 사용자 위시리스트 수정
- [ ] 사용자 위시리스트 삭제
- [x] 사용자 인증 인터셉터
* 위와 같이 대부분 개발을 덜 한 상태이나 몇 가지 질문이 있습니다.

### 질문 사항

* 패키지 분리를 하긴 했으나 잘 한 것인지 잘 모르겠습니다. 디렉토리가 꽤 많다고 느껴지는데 코드 구조가 복잡해졌을 때 도움이 되는지 궁금합니다.
* 예시코드를 참고하여 `@LoginUser` 어노테이션으로 `userId`를 참조하도록 구현했는데 제대로 했을까요? JWT 형식으로 바꿀 의향이 있는데 이 때도 동일한 방식으로 구현하면 되는지 궁금합니다.
* 더미데이터가 없어 테스트코드를 작성하기 난감한데 schema.sql과 같이 data.sql로 더미데이터를 입력하면 자동적으로 insert되는 것인가요? 이 경우 테스트 코드가 아닐 때, 더미데이터를 insert하지 않도록 하는 방법은 있을까요?

2024-07-06 17:39 UTC, sang5c requested changes
요구사항을 만족하지 못해 request change를 드려요!  
리뷰 내용 읽어보시고 수정해주세요 ;) 

> 패키지 분리를 하긴 했으나 잘 한 것인지 잘 모르겠습니다. 디렉토리가 꽤 많다고 느껴지는데 코드 구조가 복잡해졌을 때 도움이 되는지 궁금합니다.

패키지 분리도 정답이 없습니다. 이렇게도 해보고 저렇게도 해보면서 경험을 쌓으시길 추천드려요.  
리뷰하는 과정에서 읽는데에 충분히 도움되었습니다. 나중에 복잡해지면 더 도움이 될 것 같구요.

> 예시코드를 참고하여 @LoginUser 어노테이션으로 userId를 참조하도록 구현했는데 제대로 했을까요? JWT 형식으로 바꿀 의향이 있는데 이 때도 동일한 방식으로 구현하면 되는지 궁금합니다.  

이 부분은 리뷰 확인해주시고 이해 안가는 부분 있으면 질문해주세요!  

> 더미데이터가 없어 테스트코드를 작성하기 난감한데 schema.sql과 같이 data.sql로 더미데이터를 입력하면 자동적으로 insert되는 것인가요? 이 경우 테스트 코드가 아닐 때, 더미데이터를 insert하지 않도록 하는 방법은 있을까요?  

테스트코드에서 더미데이터를 저장하는 것까지 해볼 순 없을까요?  
지금 단계에선 도움이 될 지 모르겠지만 `Spring Profile` 이라는 키워드로 접근해보시면 됩니다.  
https://www.baeldung.com/spring-profiles
이부분은 글로 남기기엔 조금 긴 이야기가 될 것 같아 간단히 남깁니다. 더 궁금하신 내용은 DM으로 알려주세요!

> controller의 테스트 코드는 어떤식으로 작성하면 좋을지 모르겠습니다. intellj의 http client기능으로 테스트를 하고는 있지만 별도의 테스트코드가 없다보니 바로 테스트를 할 수 없고, 매번 새로운 TC를 추가해야되는 것이 불편한데 다른 방법이 있을까요?

`스프링 부트 통합 테스트` 혹은 `MockMvc` 키워드로 찾아주세요 :)  
https://spring.io/guides/gs/testing-web

> 위시리스트에서 수량 수정을 할 때, 수량(product_count)이 0이 되는 경우 테이블에서 레코드를 삭제하도록 되어있습니다. 이 때, 레코드 삭제를 DB 스키마에서 트리거로 삭제를 할 수 있고, service 혹은 repository 계층에서 삭제 로직을 만들어 db에 업데이트 쿼리를 보내는 방법이 있다고 생각됩니다. 어떤 방법이 권장되고 각각의 장단점이 궁금합니다.

저는 가능한 많은 로직이 애플리케이션 코드에 존재해야 한다고 생각해요.  
데이터베이스에서 제공하는 기능중에 HTTP 요청, 반복문, 함수 정의 까지 수많은 기능이 있습니다.  
이를 활용하면 경우에 따라 쉽고 간단하게 해결되기도 하나, 비즈니스 로직이 여러 곳에 존재하게 되면 관리의 어려움이 있습니다. 코드만 수정했더니 DB에 로직이 숨어있는 경우도 생길 수 있구요.  

가장 우선시해야하는 것은 팀 내 규칙이고, 꼭 필요한지, 코드로 풀어낼 순 없는지, 유지보수가 가능한지 등 다양한 조건을 따지고 나서 선택해야합니다.

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/controller/UserController.java
> +@RequestMapping("/api/members")
API는 /members이지만 컨트롤러는 UserController이네요. 의도하신 내용일까요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/dto/user/UserRequestDto.java
> +    @NotEmpty String password
배운 내용 활용 👍  
`@NotBlank`도 알아보면 좋을 것 같아요.

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/controller/UserController.java
> +    public ResponseEntity<UserResponseDto> login(@RequestBody @Valid UserRequestDto userRequest) {
회원 가입과 로그인 API가 동일한 DTO를 사용하고 있는데 회원 가입에 필요한 값에 사용자 이름이 추가되면 어떻게 될까요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/mapper/UserMapper.java
> +public class UserMapper {
또 새로운 개념이 등장했군요!  
Mapper는 어떤 역할을 수행하나요?  
UserRequestDto, User 또는 UserService에서 해당 과정을 수행할 수 있을 것 같은데  
Mapper가 별도로 존재하면 어떤 장점과 단점이 있을까요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/mapper/UserMapper.java
> +        return new User(null, userRequestDto.email(), userRequestDto.password());
null을 전달하기보다는 생성자 오버로딩을 활용하는 것은 어떨까요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/repository/UserRepository.java
> +        }
Repository의 책임은 어디까지일까 고민해보면 좋겠네요.  
Exception을 발생시키는 것도 Repository의 책임일까요?  

그리고 "Email 주소가 이미 존재하는 경우엔 회원 가입이 불가능하다"는 비즈니스 로직이라고도 볼 수 있지 않을까요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/dto/user/UserResponseDto.java
> +    @Email String email,
ResponseDto에 담긴 Validation은 어떤 역할을 수행하나요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/entity/User.java
> +    @NotEmpty String password
User에서의 Validation은 어떤 역할을 수행하고 있나요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/entity/User.java
> +package gift.entity;
Product는 model인데 User는 entity네요. 어떤 차이가 있을까요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/service/UserService.java
> +            getToken(userRequest.email(), userRequest.password())
user가 아닌 userRequest에서 값을 꺼내는 이유가 있을까요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/service/UserService.java
> +            .encodeToString((email + ":" + password).getBytes());
간단히 알아두시면 좋을 것 같습니다.  
클라이언트가 매번 request마다 basic 인증을 위한 문자열을 만들어 요청하고, 서버는 decode해서 사용해야 합니다.  
서버가 직접 만들어 반환하고 이 값을 클라이언트가 사용하는 방식은 권장되지 않습니다.  

basic인증은 보안이 취약해서 HTTPS를 강제해야 하고, 주로 사용되는 방식은 jwt라 jwt를 사용하는 쪽으로 넘어가셔도 좋을 것 같아요.

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/resolver/LoginUserArgumentResolver.java
> +        String token = getToken(webRequest.getHeader("Authorization"));
Basic 인증 방식을 사용하는 경우 Basic prefix가 붙어야 합니다.  
https://datatracker.ietf.org/doc/html/rfc7617

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/service/UserService.java
> +    private HashMap<String, String> decodeToken(String token) {
간단한 코드라도 return하는 코드라면 Map 사용을 지양하는 편입니다.

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/controller/WishlistController.java
> +@RestController("/api/wishes")
RequestMapping을 의도하셨을까요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/dto/user/UserRequestDto.java
> +public record UserRequestDto(
Product는 RequestDto, ResponseDto 개념이 없는데 User에는 어떤 이유로 생겨났나요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/resolver/LoginUserArgumentResolver.java
> +public class LoginUserArgumentResolver implements HandlerMethodArgumentResolver {
어디에서도 이 resolver를 사용하고있지 않네요. 아래 글을 참고해서 적용해보면 어떨까요?  
https://velog.io/@tjddus0302/Spring-HandlerMethodArgumentResolver

2024-07-06 17:39 UTC, sang5c commented on src/main/resources/schema.sql
> +CREATE TABLE wishlist (
테이블 명과 클래스 명이 무조건 일치해야 하는 것은 아니지만 가능하면 일치해야 한다고 생각합니다.  
WishProductDto / wishes / wishlist 세 가지로 이름을 나눠 사용하는 이유가 있을까요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/entity/User.java
> +public record User(
URL은 /members 인데 여기서는 User라고 호칭하고 있네요. 어떤 이유가 있나요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/controller/WishlistController.java
> +    @PatchMapping
Patch가 사용되었네요! Put과 Patch는 어떤게 다른가요?

2024-07-06 17:39 UTC, sang5c commented on src/main/java/gift/controller/WishlistController.java
> +    public ResponseEntity<List<WishProductDto>> deleteWishlist(
위시리스트의 모든 응답에서 DB 조회를 통해 전체 데이터를 반환하고 있습니다. 의도한 응답이 맞을까요?  
이는 어떤 의도로 응답하고 있나요?

2024-07-07 09:17 UTC, us4c0d3 reviewed
과제에서 요구하는 바 + 예시 코드와 제가 생각하며 개발하는 바(naming 등)가 충돌했을 때, 예시코드를 무비판적으로 받아들이는 경향이 있는 것 같습니다. 그로 인해 코드 일관성이 많이 무너졌다고 생각합니다. 추후 개발 과정에서는 예시 코드를 보더라도 왜 이렇게 짜여있는지 생각해보고, 생각했을 때 이러한 url이 더 맞을 것 같다는 등 정보를 취사선택하여 최대한 깔끔한 코드가 되도록 지향하겠습니다.

코멘트를 단 부분에 관해서, 코드를 수행하는데 있어서 문제가 생기는 부분에 관해서는 대부분 현재 버전에서 수정이 되었고, 명명법, 비즈니스 로직 위치 등 리팩토링이 필요한 부분은 아직 수정되지 않았습니다. 이 부분에 관해서는 금일 내로 리팩토링하여 다시 커밋 후 리뷰 요청을 하겠습니다.

추가로 테스트 부족으로 인해 버그가 많은 코드를 리뷰하시느라 고생한 멘토님 죄송합니다... 차주부터는 `Mockito`를 활용해 controller를 포함하여 최대한 신뢰성 있는 코드를 제출하겠습니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/controller/UserController.java
> +    public ResponseEntity<UserResponseDto> login(@RequestBody @Valid UserRequestDto userRequest) {
현재 요구하는 스펙이 동일해서 동일한 DTO를 사용하였습니다! 그러나 확장성을 고려했을 시 DTO를 분리하는 것이 좋다고 생각합니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/controller/WishlistController.java
> +    @PatchMapping
PUT메서드는 속성의 일부만 요청을 보냈을 때 보내지 않은 속성은 null로 처리되는 것,

PATCH 메서드는 속성의 일부만 요청을 보냈을 때 보내지 않은 속성은 기존 값으로 유지되는 것

이렇게 알고있습니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/controller/WishlistController.java
> +    public ResponseEntity<List<WishProductDto>> deleteWishlist(
네 맞습니다!

그러나 이 코멘트를 보고 다시 생각하게 되었는데, 처음에는 업데이트가 되었을 때, db업데이트 후 wishlist 페이지로 돌아간다고 생각하여 모든 데이터를 반환한다고 시나리오를 생각하였습니다.

하지만 뷰 페이지 상에서 wishlist 페이지로 리디렉션된다면 그 페이지에서 다시 db 조회로 전체 데이터를 반환할 것이므로 필요가 없어질 것 같습니다.

다만, 여기서 질문이 있는데 업데이트의 경우 response를 단순히 성공 message와 `200 OK` 정도의 상태코드만 보내도 되는 것일까요? 아니면 다른 추가적인 정보를 보낼 필요가 있나요?

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/dto/user/UserRequestDto.java
> +public record UserRequestDto(
password의 존재 때문이었습니다. 아직 암호화과정을 거치지는 않았지만, password와 같이 보안이 필요한 정보는 최대한 통신을 적게 해야된다고 생각합니다. 그러다보니 request data와 response data의 필드 정보가 달라지게 되었고, 그렇기 때문에 DTO를 분리할 필요가 생겼습니다.

반면, Product의 경우 request를 할 때와 response를 할 때의 주고 받는 정보에 큰 차이가 없어 하나로 사용했었습니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/dto/user/UserResponseDto.java
> +    @Email String email,
따로 validation에 사용되지는 않지만, 코드 일관성 및 가독성에 도움을 준다고 생각합니다.

validation이 입력값의 유효성 검증을 위해 사용되는 것으로 아는데 response에 validation을 사용하는 경우가 있는지, 있다면 어떻게 사용하는지 궁금합니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/resolver/LoginUserArgumentResolver.java
> +public class LoginUserArgumentResolver implements HandlerMethodArgumentResolver {
현재 버전에서는 WebConfig를 사용해 resolver를 등록했습니다!

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/resolver/LoginUserArgumentResolver.java
> +        String token = getToken(webRequest.getHeader("Authorization"));
과제 요구사항에 Bearer prefix가 있어 무비판적으로 사용한 것 같습니다.

토큰의 타입에 따른 prefix에 대하여 추가로 학습하겠습니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/controller/UserController.java
> +@RequestMapping("/api/members")
과제 예시코드를 따라하다 보니 잘못된 naming이었던 것 같습니다. url을 user로 바꾸겠습니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/controller/WishlistController.java
> +@RestController("/api/wishes")
잘못된 코드입니다! 현재 버전은 수정된 상태입니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/entity/User.java
> +package gift.entity;
entity는 DB 테이블과 매핑되는 객체로 알고있습니다. 현재 Product가 model에 있는 이유는 미니과제를 진행했을 당시 MVC 디자인 패턴을 사용해서 개발을 했었는데, 그 때 DTO 객체들을 model에 저장했었기 때문에 추후 DTO로 리팩토링하기 전 임시로 Product를 model에 넣어뒀습니다. 

그러나 자바에서 model과 entity의 차이에 대해 좀 더 찾아봤는데, 

| **구분**      | **DTO (Data Transfer Object)**                   | **Model**                             | **Entity**                                     |
|---------------|---------------------------------------------------|---------------------------------------|------------------------------------------------|
| **역할**      | 클라이언트의 데이터를 받는 역할                  | 비즈니스 데이터를 담는 역할           | 데이터베이스의 테이블과 스키마를 표현하는 역할 |
| **사용 위치** | 클라이언트와 서버 간 데이터 전송 시 사용          | 애플리케이션 내부 비즈니스 로직에서 사용 | 데이터베이스와의 매핑에 사용                   |
| **노출 여부** | 클라이언트에서 사용하는 것이므로 노출되도 상관없음 | 외부 노출보다는 내부 사용에 적합       | DB 컬럼과 연결되기 때문에 필드명이 노출되면 안됨|
| **특성**      | 데이터 유효성 검증을 포함할 수 있음                | 비즈니스 로직을 반영한 데이터 구조     | 테이블 구조와 직접 매핑, 필드명이 컬럼명과 일치 |
| **예시**      | UserDTO, ProductDTO                              | UserModel, ProductModel               | UserEntity, ProductEntity                       |

이 정도로 찾을 수 있었습니다.

model과 entity의 차이가 아직 좀 헷갈리는데, model의 경우 service 계층 등에서 비즈니스 로직을 통해 데이터를 가공할 때 쓰는 객체이고, entity의 경우 repository 단에서 각 필드가 db 테이블 필드와 1:1로 매핑하여 DB 접근 로직에 직접적으로 사용되는 객체라고 이해하면 되겠습니까?

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/entity/User.java
> +public record User(
> 과제 예시코드를 따라하다 보니 잘못된 naming이었던 것 같습니다. url을 user로 바꾸겠습니다.

위의 코멘트와 동일한 이유입니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/mapper/UserMapper.java
> +        return new User(null, userRequestDto.email(), userRequestDto.password());
그렇게 한다면 이 객체 생성과 같은 방법을 다시 사용할 때 human error 등으로 인해 id data가 삽입될 수 있을 것 같습니다. 그러나 User가 record 객체라 class 형태로 바꾸지 않는 이상 쉽지 않을 것 같습니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/repository/UserRepository.java
> +        }
아직 비즈니스 로직에 대한 개념이 명확히 잡히지 않은 것 같습니다. 예외 처리 로직도 비즈니스 로직이라고 한다면 이 부분은 service 단으로 옮기는 것이 맞는 것 같습니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/service/UserService.java
> +            getToken(userRequest.email(), userRequest.password())
코드를 작성하다 리팩토링 과정에서 누락됐던 것 같습니다! 수정하겠습니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/service/UserService.java
> +            .encodeToString((email + ":" + password).getBytes());
최대한 jwt를 적용해보겠습니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/resources/schema.sql
> +CREATE TABLE wishlist (
기능 개발에 급급하다가 이름을 확실히 정하지 않고 시작해 코드 일관성에 문제가 생긴 것 같습니다. 복수형을 wishes, 단수형을 wish로 통일하겠습니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/service/UserService.java
> +    private HashMap<String, String> decodeToken(String token) {
그렇다면 이 경우에도 dto 등으로 wrapping하여 전달하는 것이 좋은 방법인가요?

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/entity/User.java
> +    @NotEmpty String password
> 따로 validation에 사용되지는 않지만, 코드 일관성 및 가독성에 도움을 준다고 생각합니다.

현재로서는 위 코멘트와 동일한 의미라고 생각합니다. 다만, entity에서의 validation은 추후 db 접근 시의 유효성을 검증해주는 기능이 있는 것으로 알고있습니다.

2024-07-07 09:17 UTC, us4c0d3 commented on src/main/java/gift/mapper/UserMapper.java
> +public class UserMapper {
DTO와 Entity간 변환은 반복적으로 사용한다고 생각합니다. 그렇기 때문에 코드 중복을 줄일 수 있습니다.

그리고 당장은 UserService에서만 사용하고 있지만 RDB의 특징으로 인해 여러 테이블간의 관계가 생기면서 각각의 entity가 필요할 때, 이 mapper 기능을 다른 패키지에서 필요로 할 수 있다고 생각합니다. 

또한, mapper가 아니더라도 다른 전역적으로 사용되어 코드 중복을 줄이는 도구가 생성될 수도 있으므로 gift.util.mapper로 패키지 리팩토링을 진행하겠습니다.

2024-07-07 12:55 UTC, sang5c approved these changes
2주차도 고생하셨습니다!  
남겨주신 질문에 대해서는 정리해서 차주중에 말씀드릴게요~  
3주차도 파이팅입니다 💪

2024-07-07 12:55 UTC, merged

2024-07-07 13:53 UTC, us4c0d3 commented
리팩토링 및 예외처리 완료했습니다! 다만 아직 jwt 적용은 하지 못했습니다.