충남대 BE_김해경 2주차 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #391
Opened 2024-07-05 08:57 UTC by HaegyeongKim01

2024-07-07 06:22 UTC, HaegyeongKim01 commented
conflicts가 발생하여 step3에서 step2로 rebase 시도 했었는데 이 부분에서 좀 꼬여서 일단 write access로 충돌 제거 하였습니다. rebase 방법을 더 공부해보도록 하겠습니다!

2024-07-07 07:19 UTC, Hyeon9mak requested changes
안녕하세요 해경님, 3단계 잘 진행해주셨어요.
간단한 코멘트 남겼으니 확인해주세요!

2024-07-07 07:19 UTC, Hyeon9mak commented on README.md
> +- [ ] 위시 리스트에 상품 제거
👀

2024-07-07 07:19 UTC, Hyeon9mak commented on src/main/java/gift/controller/WishlistController.java
> +    }
HTTP 요청에서 method 는 어떤 역할을 갖는다고 생각하시나요?! 🤔 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET

2024-07-07 07:19 UTC, Hyeon9mak commented on src/main/java/gift/controller/WishlistController.java
> +    }
토큰 추출은 jwt util 을 다루는 다른 객체에게 명령을 보내볼 수 있지 않을까요? 🤔

2024-07-07 07:19 UTC, Hyeon9mak commented on src/main/java/gift/vo/WishProduct.java
> +    private Long productId;
필드명은 memberId 인데, pk 가 email 이라는게 어떤 의미인지 잘 이해하지 못했어요!

2024-07-07 07:19 UTC, Hyeon9mak commented on src/main/resources/db/h2/schema.sql
> +                          product_id BIGINT,
member id 와 product id 도 not null 하게 다룰 수 있지 않을까요?

2024-07-07 07:19 UTC, Hyeon9mak commented on src/main/resources/db/h2/schema.sql
> +                          CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
fk 를 만드는 것과 만들지 않는 것에는 어떤 장단점이 있을까요?

2024-07-08 02:26 UTC, HaegyeongKim01 commented on src/main/resources/db/h2/schema.sql
> +                          CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
fk를 만들면 객체끼리의 연관관계가 생기기 때문에 데이터 무결성이라는 장점과 테이블을 분리하고 FK 하나로 연결 시킬 수 있기에 분리 가능한 장점이 있다고 생각합니다. 그런데 단점은 테이블 구조를 변경하거나 제약이 걸리는 경우가 생기는 단점이 존재합니다. 
추가적으로 찾아보니 테이블 구조 변경, 테스트 데이터를 만드는 것이 불편하다 등의 단점이 있지만 외래키 컬럼에 인텍스를 달아주고 부모 테이블의 PK가 변하지 않도록 디자인 하는 것으로 외래키를 사용하는 것이 더 나으며 성능적인 문제는 없다고 생각할 수 있다고 합니다.

2024-07-08 02:53 UTC, HaegyeongKim01 commented on src/main/java/gift/controller/WishlistController.java
> +    }
아! 실수했습니다! 
위시리스트 조회 - GET
추가 - POST
삭제 - DELETE

2024-07-08 02:54 UTC, HaegyeongKim01 commented on src/main/java/gift/controller/WishlistController.java
> +    }
넵! JwtUtil에서 메소드를 가지도록 변경하였습니다.🙂

2024-07-08 02:59 UTC, HaegyeongKim01 commented on src/main/java/gift/vo/WishProduct.java
> +    private Long productId;
WishProduct의 외래 키(FK)로 Member의 기본 키(PK)를 사용하게 되는데, 이때 memberId가 단순한 숫자(예: 정수, Long)가 아닌 이메일로 사용되고 있음을 설명하고 싶습니다. 필드명을 포괄적으로 하여 데이터베이스 구조가 변경되었을 때 코드의 일관성을 유지하기 위함으로 memberId라고 작성했습니다. 하지만 Member PK가 바뀔 수 있습니다. 만약 Member의 PK 타입이 변경된다면, WishProduct의 해당 필드 타입도 그에 맞춰 변경되어야 하는데 이를 설명하고 싶었습니다.

2024-07-08 13:36 UTC, Hyeon9mak approved these changes
안녕하세요 해경님! 피드백 잘 반영해주셨습니다 👍 
2주차도 고생 많으셨습니다. 간단한 코멘트 남겼으니 확인해주세요.
3주차 미션에서 만나요 😄

2024-07-08 13:36 UTC, Hyeon9mak commented on src/main/java/gift/vo/WishProduct.java
> +    private Long productId;
의도를 이해했습니다!
그렇다면 우선 처음보는 사람도 어떤 형태의 필드인지 이해할 수 있도록 `email` 이라는 명칭을 사용하고, 주석을 통해 pk 임을 드러내 주는건 어떨까요? 😉

2024-07-08 13:36 UTC, Hyeon9mak commented on src/main/resources/db/h2/schema.sql
> +                          CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
여러가지 장단점이 있겠지만 대표적으로 제가 체감한 것은...

#### 장점
- RDB 라는 특성상 데이터 정합성과 관계표현이 가장 중요한데 이것을 잘 드러내준다.
- 테이블을 처음 확인하는 동료 개발자도 테이블간 관계를 바로 파악할 수 있다.
- 데이터가 입력/수정/삭제될 때 정합성을 보장할 수 있다.

#### 단점
- 데이터가 입력/수정/삭제될 때마다 정합성을 검사하므로 다루는 데이터 규모가 커지면 성능상 문제가 생길 수 있다.
- 서비스를 운영하다보면 데이터를 수기로 관리하는 일이 분명 생기는데, 이 때 FK 가 큰 걸림돌이 된다.

와 같은 장단점이 있었습니다.
현재는 규모가 작고, 먼 훗날 자연스럽게 FK 제거를 경험하게 되실테니 지금처럼 FK 를 적극 활용해보시는게 좋겠네요!

2024-07-08 13:37 UTC, merged