강원대 BE_이의찬 2주차 과제(step2)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #396
Opened 2024-07-05 09:02 UTC by ana-raka

# Step2 과제 수행한 결과입니다.
## Step 2 과제 진행 정리입니다.
- step1 때 진행하신 피드백을 일단 반영하였습니다.  
- 주신 피드백 중에 product 객체가 두가지 역할로 사용되고 있다는 피드백 관련하여 DTO와  도메인 객체 두개로 분리하는 작업을 수행하였습니다. 이러한 과정에서 든 궁금증은 이름만 값 객체를 생성하였는데, 나머지 id나 이러한 값 모두 값 객체를 만들어서 관리하는 게 좋은 것인지 궁금합니다. 

- 파일 구조에 대해 찾아보면서 구조를 나누려하였는데 명확한 정답이 없는 느낌이었습니다. 혹시 제가 작성한 파일 구조가 올바른 구조인가요? 어떤 식으로 파일 구조를 구성하는게 좋은 방식인지 궁금합니다.
-> 제가 궁금했던 파일 구조는 그 gift의 하위 패키지로 controller, service, exception 이런 식으로 분리하였는데 이러한 패키지를 생성할 때 어떠한 기준으로 나누는게 좋은지 궁금하였습니다 !
- Step2 진행할 시간이 부족하여 일단 진행한 부분까지만 PR을 하였습니다. 이후에 Step 2를 전부 구현하여 다시 PR하도록 하겠습니다. 감사합니다.
- member 관련하여 추후 구현할 기능을 주석으로  표시하였습니다. 
- 감사합니다 !

2024-07-06 04:17 UTC, pci2676 commented
> * 주신 피드백 중에 product 객체가 두가지 역할로 사용되고 있다는 피드백 관련하여 DTO와  도메인 객체 두개로 분리하는 작업을 수행하였습니다. 이러한 과정에서  상품 이름만 값 객체를 생성하였는데, 나머지 id나 이러한 값 모두 값 객체를 만들어서 관리하는 게 좋은 것인지 궁금합니다

좋은 질문입니다 👍 

다른 값 들도 동일하게 값 객체로 활용할만한 소지가 있다면 값 객체로 활용하는 것이 좋을것 같습니다!

지금은 먼저 도메인 객체로써 활용할 수 있는가를 잘 따져보면 좋을것 같습니다. 😄

2024-07-06 04:18 UTC, pci2676 commented
> * Step2 진행할 시간이 부족하여 일단 진행한 부분까지만 PR 하였습니다. 이후에 Step 2를 전부 구현하여 다시 PR하도록 하겠습니다. 감사합니다.
> * member 관련하여 추후 구현할 기능은 주석으로  표시하였습니다.

일요일까지 코드를 완성해서 보여주시면 되니까 지금 PR에 2단계 3단계를 이어서 작성해주시면 될 것 같습니다.

추가 커밋이 생긴다면 리뷰 요청을 통해 저에게 노티를 주시면 좋을것 같습니다. (제가 이메일만으로는 파악하기 힘들어서요)

2024-07-06 04:19 UTC, pci2676 commented
> * 파일 구조에 대해 찾아보면서 구조를 나누려하였는데 명확한 정답이 없는 느낌이었습니다. 혹시 제가 작성한 파일 구조가 올바른 구조인가요? 어떤 식으로 파일 구조를 구성하는게 좋은 방식인지 궁금합니다.
>   -> 제가 궁금했던 파일 구조는 src/main/java/gift의 하위 패키지로 controller, service, exception 이런 식으로 분리하였는데 이러한 패키지를 생성할 때 어떠한 기준으로 나누는게 좋은지 궁금하였습니다 !

지금 해주신 모습은 MVC 패턴을 적절하게 지킨것으로 보이네요 👍

2024-07-06 04:25 UTC, pci2676 requested changes
조금 더 고려해볼만한 부분에 리뷰를 남겨두었으니 확인해주세요.

리뷰를 보며 이해가 되지 않는 부분이 있다면 멘토링을 신청해주세요

일요일까지 2, 3단계를 구현해주시면 되니 미구현된 부분은 모두 구현해주세요~

2024-07-06 04:25 UTC, pci2676 commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
implementation, runtimeOnly 과 같은 구문이 어떠한 동작을 하는지 알고 계실까요?

잘 모르신다면 찾아보고 정리해보셔도 좋을것 같습니다.

2024-07-06 04:25 UTC, pci2676 commented on src/main/java/gift/controller/MemberController.java
> +        String token = memberService.registerNewMember(member);
controller에는 가능한 적은 로직, 특히 요청과 응답에 대한 스펙만 노출되는것이 좋습니다.

Member를 생성하고 service에 넘기기 보다 dto를 넘겨서 service 내에서 Member를 생성하는 방향으로 개선해보시면 좋을것 같습니다. 😄

2024-07-06 04:25 UTC, pci2676 commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.badRequest().build();
addNewProduct가 실패한다면 boolean으로 false를 내보내고 이러한 값을 확인하여 badRequest를 발생하도록 변경해주셨군요 👍 

이러한 방법도 좋지만

exception을 발생시킨 뒤 handler에서 badRequest응답을 해주는것도 방법이 될 수 있으니 참고해주세요.

2024-07-06 04:25 UTC, pci2676 commented on src/main/java/gift/jwt/JwtUtil.java
> +    String secretKey = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
secretKey가 하드코딩되어 노출되는것은 굉장히 위험합니다.

이를 적절히 숨길수 있는 방법을 찾아보시면 좋을것 같습니다.

2024-07-06 04:25 UTC, pci2676 commented on src/main/java/gift/model/product/ProductName.java
> +    }
ProductName을 값객체로 사용하기 위해 만들어주셨군요 👍 

조금 아쉬운 점은 이 객체에 아무런 도메인 로직이 위치하지 않은것 같습니다.

ProductName에는 여러가지 제약조건이 있는것으로 알고 있습니다. 이러한 조건을 여기에 표현해보시면 좋을것 같습니다!

2024-07-06 04:25 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
>          if (product.amount() >= amount) {
amount를 외부에서 get을 이용해서 비교하지 말고 Product 내부에 메시지를 던지는 방향을 고려해봐주시면 좋을것 같습니다.

boolean 큰가 = product.금액이_더큰가?(amount)

2024-07-07 12:13 UTC, ana-raka commented on src/main/java/gift/jwt/JwtUtil.java
> +    String secretKey = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
수정했습니다 !

2024-07-07 12:13 UTC, ana-raka commented on src/main/java/gift/controller/MemberController.java
> +        String token = memberService.registerNewMember(member);
수정했습니다!

2024-07-07 13:43 UTC, ana-raka commented on src/main/java/gift/service/ProductService.java
>          if (product.amount() >= amount) {
수정하였습니다 !

2024-07-07 13:51 UTC, ana-raka commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
넵! 감사합니다.

2024-07-08 04:58 UTC, pci2676 commented
> * DTO에서 값의 유효성을 검사하는데 값 객체에서 유효성 검사 로직이 한번 더 필요한 이유가 궁금합니다 ..!

DTO는 입력받는 부분에서 사용되는 객체라고 보면 될 것 같습니다.

그러나 값 객체는 비즈니스 가장 내부에 위치한 객체이구요.

다시말해 DTO는 입력받는 부분이 달라지면 새롭게 생성해야할 필요가 있는 객체라고 볼 수 있습니다.

그러면 DTO에만 검증 로직이 위치했을때 올바르지 않은 값을 전달하고 검증로직을 빠뜨린다면 값 객체에는 올바르지 않은 값이 전달될 위험이 있습니다.

따라서 가장 안쪽에서 사용되는 값 객체에서도 한번 더 검증을 해주는 것이 좋습니다. 😄

2024-07-08 05:29 UTC, pci2676 commented
> ```
> 
>     fetch('/wishlist', {
>             method: 'GET',
>             headers: {
>                 'Content-Type': 'application/json',
>                 'Authorization': 'Bearer ' + token
>             },
>         })
>         .then(response => {
>             if (response.ok) {
>                 location.href = '/wishlist';
>             } else {
>                 throw new Error('Failed to retrieve wish list.');
>             }
>         })
> ```
> 
> 
> 
>     
>   
> 
> 
> * 해당 로직을 클라이언트 사이드에서 수행하는 코드를 작성하였는데 페이지가 이동하지 않은 오류가 계속 밞생하였습니다.  문제 해결을 위해 Resolver에서 로깅을 수행한 결과 해당 인중 과정이 두번 진행되는 것을 확인하였습니다.

위와 같이 프론트 코드를 작성하면 `GET /wishlist` 을 수행한 뒤 토큰 없이 `GET /wishlist`을 또 수행하는것으로 보이는것 같은데 아닌가요?

2024-07-08 07:16 UTC, pci2676 commented
> * 마지막으로 저는 현재 DTO랑 실제 도메인 객체를 같은 형태? 로 구현하였는데, DTO는 보다 간결할 수록 좋다고 알고 있습니다. 그 경우에 DTO를 간결하게 할 경우 이를 서비스 레이어에서 처리하는 과정이 좀 더 복잡해지는 느낌이었습니다. 이러한 구현이 복잡해지는 오버헤드에도 DTO를 단순하게 하는 것이 좋은 방식인지 궁금합니다.

DTO에는 지금 별다른 기능이 없는것 같아보이네요. 도메인 객체에는 별다른 비즈니스 로직이 구현되어있지 않은것 같구요. 

지금 DTO의 모습은 평범한 정도인것 같습니다. 

DTO는 딱 데이터 전달에만 목적을 두시는게 좋을것 같아요.

2024-07-08 08:02 UTC, pci2676 approved these changes
답변과 리뷰를 남겨두었으니 확인해주세요.

merge하겠습니다.

2024-07-08 08:02 UTC, pci2676 commented on src/main/java/gift/config/LoginMemberArgumentResolver.java
> +        if (authHeader != null && authHeader.startsWith("Bearer ")) {
authHeader를 나타낼수 있는 객체를 도출후 책임을 부여하면 좋을것 같습니다.

2024-07-08 08:02 UTC, pci2676 commented on src/main/java/gift/config/LoginMemberArgumentResolver.java
> +                if (member != null) {
nullable한 값들 다루어야 한다면 Optional을 사용해보시면 좋을것 같습니다.

2024-07-08 08:02 UTC, pci2676 commented on src/main/java/gift/config/LoginMemberArgumentResolver.java
> +        }
depth가 깊습니다. 컨벤션을 지켜주세요!

2024-07-08 08:02 UTC, pci2676 commented on src/main/java/gift/service/MemberService.java
> +    @Autowired
지금 상황에서 `@Autowired`를 사용하신 이유가 있나요?

2024-07-08 08:02 UTC, pci2676 commented on src/main/java/gift/service/MemberService.java
> +        if (registeredMember != null &&member.getPassword().equals(registeredMember.getPassword())) {
Member에게 책임을 부여해주세요 지금 상태는 dto랑 다를바가 없는것 같습니다!

2024-07-08 08:02 UTC, pci2676 commented on src/main/java/gift/jwt/JwtUtil.java
> +    private String secretKey;
이렇게 사용하는 방법도 있는데 ConfigurationProperties에 대해서도 알아보시면 좋을것 같네요.

2024-07-08 08:02 UTC, merged