충남대 BE_김유겸 2주차 과제 (2단계 ~ 3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #397
Opened 2024-07-05 09:06 UTC by rladbrua0207

3단계도 진행중에 있습니다. 과제제출을 위해 미리 PR올립니다.

2024-07-07 06:06 UTC, Hyeon9mak requested changes
안녕하세요 유겸님! 엄청나게 꼼꼼한 테스트 코드와 함께 잘 진행해주셨어요 👍 👍 
2주차 과제부터는 각 단계별로 나누어 진행하는 것이 권장되기 때문에,
다음 주차부터는 꼭 단계별로 미션을 나누어 진행해주시면 좋을거 같아요 😉 
몇 가지 간단한 코멘트 남겼으니 확인해주세요!

2024-07-07 06:06 UTC, Hyeon9mak commented on src/main/java/gift/config/AuthInterceptor.java
> +        String token = header.substring(7);
앞에 헤더를 자르는 7글자가 어떤 의미를 같는지 상수로 만들고 이름을 부여해주면 더욱 좋겠네요!

2024-07-07 06:06 UTC, Hyeon9mak commented on src/main/java/gift/config/WebConfig.java
> +    }
생성자가 1개뿐일 땐 어노테이션이 생략되어도 되죠~

2024-07-07 06:06 UTC, Hyeon9mak commented on src/main/java/gift/config/WebConfig.java
> +    }
👍

2024-07-07 06:06 UTC, Hyeon9mak commented on src/main/java/gift/member/application/MemberService.java
> +    }
그렇죠! repository 입장에서는 회원이 있는 것도, 없는 것도 정상 동작이죠.
회원 정보가 없으면 예외 상황인 것은 유겸님이 만드신 서비스의 입장이죠!
service 계층에서 예외처리 👍

2024-07-07 06:06 UTC, Hyeon9mak commented on src/main/java/gift/member/application/MemberService.java
> +    }
delete 가 성공했는지, 실패했는지도 알아볼 수 있을까요?

2024-07-07 06:06 UTC, Hyeon9mak commented on src/main/java/gift/member/application/command/MemberUpdateCommand.java
> +public record MemberUpdateCommand(
오호, 별도로 command dto 를 만드신 이유가 궁금해요!

2024-07-07 06:06 UTC, Hyeon9mak commented on src/main/java/gift/member/domain/MemberJDBCRepository.java
> +package gift.member.domain;
repository interface 를 domain 패키지 내부에 두셨군요! 👍 
repository interface 와 jdbc repository 구현체를 domain 패키지에 두신 이유도 궁금합니다.

2024-07-07 06:06 UTC, Hyeon9mak commented on src/main/java/gift/wishlist/application/WishlistService.java
> +                .orElseThrow(() -> new NotFoundException("해당 상품이 존재하지 않습니다."));
요 부분은 각각 private 메서드로 분리해주면, `add` 메서드의 전체 흐름을 파악하는게 더욱 빨라지겠어요!

2024-07-07 06:06 UTC, Hyeon9mak commented on src/main/java/gift/wishlist/application/WishlistService.java
> +        wishlistRepository.addWishlist(wishlist);
Wishlist 에 id 를 전달 받지 않는 생성자를 하나 더 만드는건 어떨까요? 😉

2024-07-07 06:06 UTC, Hyeon9mak commented on src/main/resources/schema.sql
> +                          product_id BIGINT,
NOT NULL 등을 보장해주는 것도 좋겠네요~

2024-07-07 06:06 UTC, Hyeon9mak commented on src/main/resources/schema.sql
> +                          FOREIGN KEY (product_id) REFERENCES product(id)
FK 를 사용하는 것과 사용하지 않는 것에는 어떤 장단점이 있을까요?

2024-07-07 06:06 UTC, Hyeon9mak commented on src/test/java/gift/member/domain/MemberJDBCRepositoryTest.java
> +    }
역시나 꼼꼼한 테스트.. 👍 👍

2024-07-07 11:32 UTC, rladbrua0207 commented on src/main/java/gift/member/application/command/MemberUpdateCommand.java
> +public record MemberUpdateCommand(
presentation계층의 request DTO가 있듯이 application 계층에서도 DTO를 만들어야겠다 라고 생각했다가 DTO관련 네이밍같은걸 찾아보니 command로 네이밍 하는걸 보고 코드가 좀 더 깔끔해지는 거 같아 적용해보았습니다.

2024-07-07 12:17 UTC, rladbrua0207 commented on src/main/java/gift/member/domain/MemberJDBCRepository.java
> +package gift.member.domain;
다른 사람이 한 구조를 참고하였습니다.

DDD에서는 Infrastructure에 repository 구현체를 두고, domain에 repository 인터페이스를 두는데 이거의 변형 으로만 알고있습니다..!

혹시 다른 내용이 있을까요? 아니면 저 개선 될 방향이 있을까요?

2024-07-07 12:30 UTC, rladbrua0207 commented on src/main/resources/schema.sql
> +                          FOREIGN KEY (product_id) REFERENCES product(id)
별 다른 생각 없이 당연히 foreign key를 사용해야 한다고 생각하여 사용하였습니다.

리뷰를 받고 검색해보니 참조 무결성과 테이블간의 관계를 명확히 알 수 있기 떄문이라고 이해했습니다.

위 내용을 본 뒤에 다른 글에서는 사용하지 않는 회사도 많다고하여 신기했습니다.
1. 추가적인 컴퓨팅 리소스 비용 발생.
2. 기존 레거시 데이터의 정합성이 안맞는문제 발생.
3. 개발 시 불편함.

2024-07-07 12:31 UTC, rladbrua0207 commented on src/main/resources/schema.sql
> +                          product_id BIGINT,
적용하겠습니다!

2024-07-07 12:31 UTC, rladbrua0207 commented on src/main/java/gift/wishlist/application/WishlistService.java
> +        wishlistRepository.addWishlist(wishlist);
생성자 체이닝을 통해 적용했습니다!

2024-07-07 12:31 UTC, rladbrua0207 commented on src/main/java/gift/wishlist/application/WishlistService.java
> +                .orElseThrow(() -> new NotFoundException("해당 상품이 존재하지 않습니다."));
감사합니다!

2024-07-07 12:38 UTC, rladbrua0207 commented on src/main/java/gift/member/application/MemberService.java
> +    }
네! 알아볼 수 있습니다.

수정하였습니다!

2024-07-07 12:39 UTC, rladbrua0207 commented on src/main/java/gift/config/WebConfig.java
> +    }
수정했습니다!

2024-07-07 12:39 UTC, rladbrua0207 commented on src/main/java/gift/config/AuthInterceptor.java
> +        String token = header.substring(7);
수정했습니다!

2024-07-07 22:56 UTC, Hyeon9mak approved these changes
안녕하세요 유겸님! 피드백 잘 반영해주셨어요.
패키지 구조가 잘 나뉘어 있어서 코드를 추적하기도 편했고,
유겸님의 의견, 학습하신 내용을 잘 설명해주신 점이 인상적입니다!

요구사항 모두 충족된 것 같아 approve 합니다.
몇 가지 마무리 코멘트 남겼으니 확인해주세요 😄 
다음 주차 미션에서 뵈어요!

2024-07-07 22:56 UTC, Hyeon9mak commented on src/main/java/gift/config/AuthInterceptor.java
> +        String token = header.substring(7);
으잉? 상수로 분리는 잘 해주셨는데 30번 라인은 누락된걸까요? ㅎㅎ

2024-07-07 22:56 UTC, Hyeon9mak commented on src/main/java/gift/member/application/MemberService.java
> +    }
이를 통해 사용자는 없는 회원정보 삭제를 시도했다는 사실을 빠르게 인지할 수 있겠네요 👍 
이런 사소한 배려가 더 나은 서비스를 만들죠.

2024-07-07 22:56 UTC, Hyeon9mak commented on src/main/java/gift/member/application/command/MemberUpdateCommand.java
> +public record MemberUpdateCommand(
👍 계층을 나눈다는 것은 계층간 변화 전파를 막고 싶다는 것이죠.
그를 위해선 각 계층마다 dto 를 분리하는 것이 가장 이상적입니다.
물론 귀찮음 + 모든 상황에서 유지보수 범위가 크게 전파되지 않음 때문에 그냥 통짜로 사용하기도 하지만요 ㅎㅎ

2024-07-07 22:56 UTC, Hyeon9mak commented on src/main/java/gift/member/domain/MemberJDBCRepository.java
> +package gift.member.domain;
맞습니다. DDD 뿐만 아니라 모든 인터페이스는 사용자 측에, 구현체는 실 구현측에 두는 것이 이상적이에요.
사용자 측에 둔다는 것은, 인터페이스가 구현체의 형상을 띄는 것이 아니라 사용자가 원하는 형상을 띄어야한다는 말이에요.
구현체를 똑같이 닮은 형상을 띈다면 사실 인터페이스를 이용할 의미가 상실되죠.

저희는 의존성을 자동으로 주입해주는 spring 을 사용중이기 때문에,
구현체가 근처에 없어도 런타임시 자동으로 의존성을 주입해주는 기능을 적극적으로 활용할 수 있어요.

요런걸 연습한다는 의미로 구현체를 별도 패키지로 분리하여 옮겨주는 것도 좋겠네요 😄

2024-07-07 22:56 UTC, Hyeon9mak commented on src/main/java/gift/wishlist/application/WishlistService.java
> +    }
👍 👍 
add 메서드가 잘 추상화되어 전체적으로 어떤 일이 벌어지는지 한 눈에 보이네요!

2024-07-07 22:56 UTC, Hyeon9mak commented on src/main/java/gift/wishlist/domain/Wishlist.java
> +    }
> 생성자 체이닝을 통해 적용했습니다!

굿! 위아래 배치 순서를 바꿔주면 가독성이 더욱 오르겠네요 😄

2024-07-07 22:56 UTC, Hyeon9mak commented on src/main/resources/schema.sql
> +                          FOREIGN KEY (product_id) REFERENCES product(id)
맞습니다. 👍 💯 
이론적으로 생각한다면 FK 를 사용하는 것이 데이터 정합성도 끌어올리고, 테이블간 관계를 명확히 표현해주므로 
사용하지 않을 이유가 없죠. RDB 는 데이터간 정합성을 맞추는게 최우선이니까요.

그러나 실제 서비스를 운영하다보면 데이터 정합성이 어그러져서 이를 수기로 맞추는 일이 생겨나고,
그럴 때 FK 가 큰 불편함을 초래해요. 또한 데이터에 변경이 생길 때마다 FK 로 인한 테이블간 데이터 확인이 발생하므로
성능상 비용(컴퓨팅 리소스)이 발생하게 됩니다.

...만 요런건 점차 큰 프로젝트를 운영해보시거나, 업무를 시작하시면 바로 알게되시는 내용이므로
현재는 FK 를 잘 사용하는 것에 초점을 맞춰보는게 좋겠네요! 👍 
FK 를 잘 써봐야, 훗날 FK 를 왜 쓰면 안되는지도 명확하게 아실테니까요 😄

2024-07-07 22:56 UTC, merged

2024-07-08 01:06 UTC, rladbrua0207 commented on src/main/java/gift/config/AuthInterceptor.java
> +        String token = header.substring(7);
못보고 넘어갔네요..! 수정하겠습니다!

2024-07-08 13:32 UTC, rladbrua0207 commented on src/main/java/gift/wishlist/domain/Wishlist.java
> +    }
바꿔서 수정하였습니다!

하지만 왜 위아래 배치 순서를 바꿨을때 가독성이 올라가는지 이해를 못했습니다... 왜 가독서이 오르는걸까요?