강원대 BE_오승환 2주차 과제 (2단계 ~ 3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #398
Opened 2024-07-05 09:17 UTC by humpose

조언해주신 부분과 더불어 이번 주차 과제 진행했습니다.
spring이 처음이다 보니 2, 3단계가 많이 어려웠던 것 같습니다.
조언해주시면 최선을 다해 고쳐나가도록 하겠습니다.

2024-07-06 04:26 UTC, pci2676 commented
> ++코치님. 과제 관련 부분은 전부 구현했는데요. 토큰으로 인증 기능을 구현하다보니 로그인 -> 위시리스트 메인 폼
> 으로는 토큰을 잘 전달받아 허가가 되는데, 상품을 추가하는 웹페이지로 갈 때, 토큰이 넘어가지 않아 허가가 나지 않는 것 같습니다.
> 한 번 로그인한 후, 웹페이지에서 상호작용할때마다 토큰을 보내고 허가를 받아야 하는 건가요?
> 만약 그렇다면 계속해서 토큰을 전달하는 더 쉬운 방법이 있을 것 같은데 무엇이 있을까요?(현재는 자바스크립트로 구현하였습니다)

웹 프론트 부분에서 계속해서 토큰을 전달해주어야 합니다..

지금 간단하게 구현할 수 있는것은 프론트 부분에서 발급 된 토큰을 로컬 스토리지에 저장해두고 요청을 보낼때마다 계속해서 전달해주는 방법이 있을것 같습니다.

2024-07-06 04:35 UTC, pci2676 requested changes
개선해볼 부분에 리뷰를 남겨두었으니 확인 후 개선해주세요.

이해가 되지 않는 리뷰가 있다면 멘토링을 신청해주세요.

일요일까지 미구현된 부분을 구현해주시면 되니 참고해주세요.

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/PasswordEncoder.java
> +    }
password를 user가 이미 알고 있는데 matches하는 책임을 user에게 넘겨보면 어떨까요?

PasswordEncoder라는 이름과 matches 책임은 어울리지 않는것 같습니다.

암호의 암/복호화에 대한 책임만 가지면 좋을것 같습니다.

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/WebMvcConfig.java
> +    private JwtInterceptor jwtInterceptor;
다른 bean 주입방법도 있을것 같은데 `@Autowired`를 사용하신 이유가 있을까요?

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/controller/ProductController.java
> +    }
이러한 로직이 이 부분외 다른 부분에서도 사용될 수 있으니 별도의 객체에서 관리하는것도 하나의 방법이 될 수 있습니다.

혹은 dto에서 domain 객체를 주입받아 dto를 생성하는 static 메서드를 두는것도 하나의 방법이 될 수 있습니다.

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/WebMvcConfig.java
> +    private JwtInterceptor jwtInterceptor;
이 부분뿐 아니라 다른 부분들도 많이 사용하고 계시군요!

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/jwt/JwtInterceptor.java
> +                return true;
getHeader를 하여 가져온 String도 하나의 값 객체로 표현하여 지금 interceptor에 노출된 로직을 위치시킬 수 있을것 같습니다.

단위테스트도 작성하기 쉬워질것 같네요.

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/jwt/JwtTokenUtil.java
> +    private static final String SECRET_KEY = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
이 Key가 하드코딩 되어있으면 보안상 굉장히 위험할 것 같습니다.

암호키에 대해 다른 방식으로 관리하는 방법을 고려해보시면 좋을것 같습니다.

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/model/Name.java
> +    }
1. setter를 제거해주세요.
2. 기본생성자가 반드시 필요한가요?

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/model/Product.java
> +    public void setId(Long id) {
setter 제거해주세요.

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/model/User.java
> +    public void setId(Long id) {
setter 제거해주세요

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/model/WishList.java
> +    public void setId(Long id) {
setter제거해주세요.

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/model/WishList.java
> +@Table(name = "wish_lists")
jpa 를 사용하는것은 요구사항이 아닌데요

jpa 없이 구현해주세요~

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/service/UserService.java
> +    private String secretKey = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
여기도 암호화 키가 노출되어있군요

2024-07-06 04:35 UTC, pci2676 commented on src/main/java/gift/service/WishListService.java
> +        if (wishList == null) {
nullable한 객체를 찾는다면 Optional을 사용해보시면 좋을것 같습니다.

2024-07-06 05:45 UTC, humpose commented on src/main/java/gift/WebMvcConfig.java
> +    private JwtInterceptor jwtInterceptor;
배운 주입 방법이 @Autowired 뿐이라서요.. 혹시 더 나은 주입 방법이 있을까요? 
지적해주신 부분은 일단 생성자 주입으로 수정하겠습니다

2024-07-06 05:49 UTC, humpose commented on src/main/java/gift/controller/ProductController.java
> +    }
조언 감사합니다.

2024-07-06 05:56 UTC, humpose commented on src/main/java/gift/jwt/JwtInterceptor.java
> +                return true;
네 수정하겠습니다

2024-07-06 06:04 UTC, humpose commented on src/main/java/gift/PasswordEncoder.java
> +    }
네 알겠습니다

2024-07-06 09:34 UTC, humpose commented on src/main/java/gift/model/WishList.java
> +@Table(name = "wish_lists")
알겠습니다.

2024-07-06 09:42 UTC, humpose commented on src/main/java/gift/service/UserService.java
> +    private String secretKey = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
같이 수정하겠습니다!

2024-07-06 10:04 UTC, humpose commented on src/main/java/gift/service/WishListService.java
> +        if (wishList == null) {
아 그렇군요 적용해보겠습니다

2024-07-06 16:03 UTC, pci2676 commented on src/main/java/gift/WebMvcConfig.java
> +    private JwtInterceptor jwtInterceptor;
다른 주입 방법에 대해 찾아보신것 없으실까요?

2024-07-07 09:06 UTC, pci2676 approved these changes
리뷰를 남겨두었으니 다음 과제를 시작할때 확인하고 적용해주세요.

merge하겠습니다.

2024-07-07 09:06 UTC, pci2676 commented on src/main/java/gift/WebMvcConfig.java
> +    public WebMvcConfig(JwtInterceptor jwtInterceptor){
다른 주입방법에 대해 스스로 찾아보셨으면 좋겠습니다.

찾아보았다면 어떻게 찾아보았는지 어떤 어려움이 있었는지 알려주셔야 제가 도움을 드릴 수 있을것 같네요.

2024-07-07 09:06 UTC, pci2676 commented on src/main/java/gift/controller/WishListController.java
> +            wishList.setProducts(new ArrayList<>());
각 model에 위치한 setter를 제거해달라는 리뷰를 지난번에 남겼는데 모두 반영해주시지 않은것 같네요.

2024-07-07 09:06 UTC, pci2676 commented on src/main/java/gift/jwt/JwtInterceptor.java
> +//        return true;
[컨벤션] 불필요한 주석은 제거해주시는게 좋습니다.

2024-07-07 09:06 UTC, pci2676 commented on src/main/java/gift/jwt/JwtTokenUtil.java
> +            .getBody();
Deprecated된 메서드는 사용하지 않는것이 좋습니다. 이유에 대해 아실까요?

2024-07-07 09:06 UTC, pci2676 commented on src/main/java/gift/jwt/JwtInterceptor.java
> +        if (authorizationHeader.isValid()) {
헤더가 올바르지 않다면 바로 exception을 터트리는 것을 권장드립니다.

헤더를 생성하고 isValid를 호출하지 않으면 헤더 객체가 올바른 상태인지 알 수 없는 채로 사용해야할 것 같습니다.

2024-07-07 09:06 UTC, merged