경북대 BE_권다운 2주차 과제 (2단계 ~ 3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #399
Opened 2024-07-05 09:29 UTC by momnpa333

과제 제출 기간이 촉박해서 코드가 다소 지저분할수 있습니다 ㅜㅜ
몇가지 질문이 있습니다!

회원을 만들때 email을 pk로 두기에는 회원이 탈퇴했을때 다른 회원이 같은 email로 회원가입할때 다소 문제가 발생할것 같아(기록해야 하는 정보 등등) 인조키를 pk로 만들었습니다. 이때 pk를 그냥 int로 하기해는 id가 유추하기 쉽다고 생각하여 uuid 로 생성하여 제작하였는데, pk가 string일 경우 쿼리 조회나 index를 걸게 될 경우 리소스가 많이 낭비된다고 알고 있습니다. user table의 pk를 어떻게 관리하는 것이 좋을까요? 저의 방안은 table은 int를 저장하고 id를 반환할때 string으로 암호화하여 보내는 방식을 생각하긴 했습니다!
인가를 구현할때 기존에는 security에서 authorizeHttpRequests 를 사용하여 구현했었는데, security를 사용하지 않고 구현하려니 쉽지 않았습니다. 생각해낸 방법이 어노테이션을 활용하여 controller의 메서드별로 인가처리를 하였는데 이것이 옳바른 방법인지 궁금합니다.
제코드에서 interceptor에서 인증,인가 모두를 처리하다 보니 코드가 다소 길어졌는데, interceptor를 두개 활용하는게 더 나아보이는데 (인증),(인가) 따로 좋은 생각일까요?
비밀번호를 암호화하여 디비에 저장하였는데, 암호화하는 클래스를 user model안에 이너클래스로 제작하였습니다. 다른 위치가 나아보이는데 어디서 비밀번호 암호화를 하는 것이 좋을까요? 이너클래스로 제작한 이유는 user안에서만 사용하고 암호화 하는 과정을 다른 계층이 모르게 하고 싶었기 때문에 이너클래스로 제작하였습니다.
https://github.com/value 로 환경변수를 가져올때 어느시점에 가져오는지 궁금 합니다. @postconstructor를 쓰는 이유가 궁금합니다.(tokenProvider.java)안의 내용입니다.
마지막으로 패키지를 제대로 나누었는지 궁금합니다. 인터셉터, auth관련 부분을 만들면서 패키지를 어떻게 나누어야하는지 생각해보다가 제출마감기한이 얼마남지 않아 제대로 나누지 못한것 같습니다 ㅜㅜ

2024-07-05 17:32 UTC, MangKyu requested changes
안녕하세요ㅎㅎ 이번 과제도 고생 많으셨습니다! 수정 필요한 부분들에 대하여 코멘트 남겨드렸습니다! 천천히 수정 작업 진행해주세요:)
이번에도 마찬가지로 질문 주셨던 부분들에 대해 답변 남겨드리겠습니다!

### PK에 대하여
말씀해주신대로 데이터베이스의 PK는 거의 대부분 인조키를 활용합니다ㅎㅎ (자세한 내용은 [해당 포스팅 ](https://mangkyu.tistory.com/287)참고해주세요!)
그리고 대부분 Long(데이터베이스 기준 Big Int) 타입을 활용합니다! 유추가 가능한 부분에 대해서는 일반적으로 채번을 다르게 가져기도 합니다! 다만 일반적으로는 SSL 기반의 암호화 통신이 되기 때문에 크게 보안 상의 문제는 없습니다! 만약 노출이 필요하다면, 작성하신 것처럼 노출 가능한 인조키를 별도로 관리하여 해당 키로 노출하기도 합니다ㅎㅎ


### 인가 구현
적절하게 잘 구현해주신 것 같습니다! 크게 문제가 없습니다ㅎㅎ


### 인증, 인가 인터셉터
인증과 인가는 별도의 프로세스입니다! 적어주신 대로 하나의 클래스에서 인가와 인증을 모두 처리한다면 단일 책잉믈 위반한다고도 볼 수 있습니다ㅎㅎ 저라면 두 가지를 분리하여 작성할 것 같네요:)


### 비밀번호 암호화
일단 비밀번호 암호화까지 고려하신 부분 그리고 다른 곳에서는 참조하지 못하도록 범위를 최소화하려고 시도하신 것도 너무 좋은 것 같습니다ㅎㅎ 
시스템이 계속해서 진화함에 따라 적합한 위치와 구성이 언제든지 바뀔 수 있습니다! 따라서 현재 구조 상으로 적합해 보이다면, 이대로 두고 진행하다가 요구사항이 확장됨에 따라 개선하는 방향이 적합해 보입니다!
아마 지금 구조에서 시스템이 계속 발전하여 비밀번호 정책이 고도화 되다 보면 PasswordUtil이 빈으로 등록되고, 특정 이너 클래스에 있기에는 부족한 시점이 올 것입니다! 그러면 그때 서비스로 분리하거나 하는 등의 방식을 취하면 될 것 같습니다ㅎㅎ
접근을 최소화하겠다는 고려를 많이들 못하시는 것 같은데, 이러한 부분까지 고려하여 위치를 결정하는 모습이 훌륭하신 것 같네요!



### @Value의 활용
@Value는 스프링의 모든 빈들이 생성된 이후에, 모든 빈들 중에서 @Value가 있는 필드에 값을 넣어줍니다! 여기서 PostConstruct가 활용된 이유는 @Value를 통해 주입받은 값들을 바탕으로 새로운 값을 생성해야 하기 때문입니다!


### 패키지 분리에 관하여
패키지의 경우 앞서 설명드린 것처럼 현재의 요구사항을 잘 반영할 수 있는 구조면 괜찮습니다! 다만 현재 계층이 안맞는다고 느껴지는 부분이 있는데요~ controller는 특정 요청을 처리하는 레이어을 나타태는 반면에 auth는 인증이라는 하나의 도메인을 나타낸다는 점에서 뎁스가 맞지 않다고 느껴지네요! 추가적으로 Service가 Model에 들어가 있는 부분도 별도의 service 패키지로 빼서 관리하면 좋을 것 같습니다ㅎㅎ


내용이 많아서 온전하게 전달드리지 못한 부분이 있을 것 같은데요, 혹시 이해 안가는 부분 있으면 편하게 질문해주세요ㅎㅎ

2024-07-05 17:32 UTC, MangKyu commented on build.gradle
> +    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
아래 2개의 의존성은 어떠한 이유로 추가된 것일까요~?

2024-07-05 17:32 UTC, MangKyu commented on src/main/java/gift/auth/Auth.java
> +public @interface Auth {
Auth라고 하면 인증(Authentication)인지 인가(Authorization)인지 혼란을 줄 수 있을 것 같아서요~
명확한 네이밍을 사용하는 것이 좋을 것 같습니다!

2024-07-05 17:32 UTC, MangKyu commented on src/main/java/gift/auth/GetLoginInfo.java
> +public @interface GetLoginInfo {
Get과 같은 동사형은 메서드의 네이밍에 사용되므로 LoginInfo로 줄이셔도 될 것 같아요ㅎㅎ
인증된 사용자라는 의미에서 Authenticate라고 해도 괜찮을 것 같네요!
```suggestion
public @interface Authenticate {
```

2024-07-05 17:32 UTC, MangKyu commented on src/main/java/gift/auth/GetLoginInfo.java
> +public @interface GetLoginInfo {
참고로 이러한 클래스, 메서드, 변수 등의 네이밍 변경은 Shift + F6을 누르면 연관된 모든 곳에 일괄변경됩니다!
혹시 모르셨다면 참고 부탁드려요ㅎㅎ

2024-07-05 17:32 UTC, MangKyu commented on src/main/resources/static/sql/data.sql
> +values ('e6c6ba86-328c-4fcf-980c-401a27da1738', 'down', 'test123@test.com',
int를 사용하는 부분과 varcahar를 사용하는 부분이 섞여있네요ㅎㅎ

2024-07-05 17:32 UTC, MangKyu commented on src/main/resources/application.yml
> +jwt.secret: secret!!secret!!secret!!secret!!
yaml 혹은 property 방식 통일하면 좋을 것 같아요!
참고로 저는 이전에는 yaml을 쓰다가 최근에 다시 검색을 용이하게 하기 위해 property 파일로 돌아왔습니다ㅎㅎ

2024-07-05 17:32 UTC, MangKyu commented on src/main/java/gift/validate/ProductNameValidator.java
> +public class ProductNameValidator implements ConstraintValidator<ValidProductName, String> {
제약 조건은 크게 2종류로 나눌 수 있는데요~
- 입력 데이터에 따른 유효성
- 비즈니스 정책에 따른 유효성

코드 기준으로는 데이터 유효성과 비즈니스 정책이 혼합되어 있는 것 같습니다ㅎㅎ
참고로 입력 데이터 부분은 애노테이션으로 처리하고, 비즈니스 정책에 대한 부분은 비즈니스 관련 클래스(Product)에 드러나는 것이 좋은 설계인 것 같습니다 ㅎㅎ 비즈니서 정책과 관련된 부분은 코드로 드러내어 우리의 정책을 쉽게 파악할 수 있어야 합니다!

연습을 위해 활용하시는 것은 괜찮을 것 같습니다~

2024-07-05 17:32 UTC, MangKyu commented on src/main/java/gift/controller/wish/WishController.java
> +        if (wish.isPresent()) {
Optinal.isPresent를 호출하는 것은 잘못된 Optional 활용을 하고 있다는 일종의 신호로 볼 수 있습니다!
올바른 Optional 사용을 위해 [해당 포스팅](https://mangkyu.tistory.com/203) 참고 부탁드립니다ㅎㅎ

2024-07-05 17:32 UTC, MangKyu commented on src/main/resources/static/sql/schema.sql
> +create table `wishes`
라인 관리 깔끕하게 해주셨네요 👍

2024-07-05 17:32 UTC, MangKyu commented on src/main/java/gift/model/wish/Wish.java
> +    Long id;
```suggestion
    private Long id;
```

2024-07-05 17:32 UTC, MangKyu commented on src/main/java/gift/model/user/User.java
> +class PasswordUtil {
직접 비밀번호 암호화까지 신경써주는 모습 좋네요 👍

2024-07-05 17:32 UTC, MangKyu commented on src/main/java/gift/global/CommonExceptionHandler.java
> +@RestControllerAdvice("gift.controller")
RestControllerAdvice를 활용하는 부분 👍

2024-07-05 17:32 UTC, MangKyu commented on src/main/java/gift/controller/wish/WishController.java
> +        var wish = wishDao.findByProductIdAndUserId(request.productId(), loginInfo.userId())
wish 관련된 부분도 서비스 계층을 도입하여 중복을 제거할 수 있겠네요!

2024-07-05 17:32 UTC, MangKyu commented on src/main/java/gift/controller/product/ProductController.java
> +        @RequestParam("page") int page,
페이징 처리 👍 default 값을 넣어주면 클라이언트가 page, size 값을 보내주지 않은 경우에도 방어적으로 대처할 수 있습니다ㅎㅎ

2024-07-05 17:32 UTC, MangKyu commented on src/main/java/gift/auth/interceptor/AuthInterceptor.java
> +        } else if (handler instanceof ResourceHttpRequestHandler) {
해당 부분 분기가 들어간 이유는 무엇인가요~?

2024-07-06 06:10 UTC, momnpa333 commented on build.gradle
> +    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
jwt 만들때 같이 쓸일이 있을줄 알고 추가했었습니다! 바로 삭제하도록 하겠습니다!

2024-07-06 06:12 UTC, momnpa333 commented on src/main/java/gift/auth/Auth.java
> +public @interface Auth {
네이밍 지적 감사합니다! 수정하겠습니다!

2024-07-06 06:14 UTC, momnpa333 commented on src/main/java/gift/auth/GetLoginInfo.java
> +public @interface GetLoginInfo {
감사합니다! 네이밍 변경 하겠습니다!

2024-07-06 06:16 UTC, momnpa333 commented on src/main/resources/static/sql/data.sql
> +values ('e6c6ba86-328c-4fcf-980c-401a27da1738', 'down', 'test123@test.com',
감사합니다 varchar로 모두 수정하겠습니다!

2024-07-06 06:16 UTC, momnpa333 commented on src/main/resources/application.yml
> +jwt.secret: secret!!secret!!secret!!secret!!
아하 그렇군요 감사합니다! 방식은 통일 하겠습니다!

2024-07-06 06:19 UTC, momnpa333 commented on src/main/java/gift/model/user/User.java
> +class PasswordUtil {
하하 감사합니다!!

2024-07-06 06:20 UTC, momnpa333 commented on src/main/java/gift/validate/ProductNameValidator.java
> +public class ProductNameValidator implements ConstraintValidator<ValidProductName, String> {
넵 알겠습니다 전에 말씀하셨던데로 두곳 모두에서 유효성 검사를 하도록 수정하겠습니다.

2024-07-06 06:47 UTC, momnpa333 commented on build.gradle
> +    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
<img width="873" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/assets/82216606/b823130c-dfaa-4639-ad00-4ac9eae11810">

``` // 토큰의 유효성 검증을 수행
    public boolean validateToken(String token) {
        String parsedToken = parseToken(token);
        try {
            Jwts.parserBuilder().setSigningKey(key).build().parseClaimsJws(parsedToken);
            System.out.println("토큰이 유효합니다.");
            return true;
        } catch (io.jsonwebtoken.security.SecurityException | MalformedJwtException e) {
            System.out.println("잘못된 JWT 서명입니다.");
        } catch (ExpiredJwtException e) {
            System.out.println("만료된 JWT 토큰입니다.");
        } catch (UnsupportedJwtException e) {
            System.out.println("지원되지 않는 JWT 토큰입니다.");
        } catch (IllegalArgumentException e) {
            System.out.println("JWT 토큰이 잘못되었습니다.");
        }
        return false;
    }
```
여기서 Jwts.parseBuilder() 등 jwt파싱할때 쓰는 의존성인 것 같습니다!!
어렵네용 ㅜ 일단 의존성은 다시 복구했습니다!

2024-07-06 07:36 UTC, momnpa333 commented on src/main/java/gift/controller/wish/WishController.java
> +        if (wish.isPresent()) {
ifPresent() 를 사용하여 체이닝으로 수정하였습니다. 멘토님께서 의도하신 부분이 이거 맞을까여?

2024-07-06 07:37 UTC, momnpa333 commented on src/main/resources/static/sql/schema.sql
> +create table `wishes`
감사합니다!

2024-07-06 07:37 UTC, momnpa333 commented on src/main/java/gift/model/wish/Wish.java
> +    Long id;
private로 수정하겠습니다!

2024-07-06 07:43 UTC, momnpa333 commented on src/main/java/gift/controller/wish/WishController.java
> +        var wish = wishDao.findByProductIdAndUserId(request.productId(), loginInfo.userId())
강사님께서 이번 과제를 주실때 service layer는 가급적 사용하지 않으셨으면 좋겠다고 하셔서 wish service를 만들지 않고 진행하였습니다! 아마 다음 과제를 진행하면서 layer를 분리하게 되지않을까 생각중입니다! user service는 토큰 생성할때 tokenProvider가 의존성으로 주입이 되어야하는데 controller에서 tokenProvider까지 주입받으면 너무 비대해져서.. userService만 만들어 봤습니다!!

2024-07-06 07:44 UTC, momnpa333 commented on src/main/java/gift/controller/product/ProductController.java
> +        @RequestParam("page") int page,
넵 수정하겠습니다!

2024-07-06 07:54 UTC, momnpa333 commented on src/main/java/gift/auth/interceptor/AuthInterceptor.java
> +        } else if (handler instanceof ResourceHttpRequestHandler) {
preHandle 메서드에서 분기가 나눴는데요! HandlerMethod와 ResourceHttpRequestHandler 두 가지 유형을 따로 처리하기 위해 분기를 나누었습니다! 처음에는 HandlerMethod 핸들러만 처리를 했는데 이렇게 되면 정적 리소스에 대한 인가처리가 되지 않더라구요.. ㅜ ResourceHttpRequestHandler 가 정적리소스 처리를 하는 핸들러라 이 녀석에 대한 처리도 따로 해야해서 분기를 나누었습니다!

2024-07-06 09:43 UTC, momnpa333 commented
말씀해주신 피드백 반영하여 코드 리팩토링완료하였습니다!
리팩토링 과정중 auth패키지를 어떤식으로 처리해야할지 잘 모르겠습니다!

2024-07-06 16:03 UTC, MangKyu approved these changes
리뷰 반영하시느라 너무 고생 많으셨습니다ㅎㅎ
auth 패키지의 경우에는, 현재 다운님의 패키지 구성을 기준으로 `global` 하위가 가장 적합하지 않나 싶네요ㅎㅎ 아마 이렇게 global이 쌓이다 보면 이를 어떻게 세분화할 것인지 또 고민하고 고쳐야하는 순간이 올거에요! 그때 다시 리팩토링하면 좋을 것 같습니다!

참고로 제 개인적으로는 다음과 같은 패키지 구성을 선호합니다.
- app (비즈니스를 다룸)
  - app.user
  - app.wish
  - app.gift
- config (설정)
  - config.web
  - config.database 
  
관련하여 제가 작업했던 [패키지 구성](https://github.com/MangKyu/InterviewSubscription/tree/master/src/main/java/com/mangkyu/employment/interview) 하나 남겨드릴께요! 참고로 저도 해당 구성을 시스템에 맞게 매번 다르게 가져가는 편이니, 하나의 예시 및 참고용으로만 생각해주시면 감사드리겠습니다ㅎㅎ

2024-07-06 16:03 UTC, MangKyu commented on build.gradle
> +    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
과거에는 jjwt 의존성이 1개였는데, 현재를 모듈 별로 분리된 부분 같네요! 👍

2024-07-06 16:03 UTC, MangKyu commented on src/main/java/gift/auth/interceptor/AuthenticationInterceptor.java
> +public class AuthenticationInterceptor implements HandlerInterceptor {
역할을 분리하니 단일 책임 원칙도 준수하고, 코드도 훨씬 깔끔해졌네요 👍

2024-07-06 16:03 UTC, MangKyu commented on src/main/java/gift/controller/product/ProductController.java
> +        @RequestParam(value = "page", required = false, defaultValue = "0") int page,
defaultValue 사용하신 부분 좋네요 👍

2024-07-06 16:03 UTC, MangKyu commented on src/main/java/gift/controller/wish/WishController.java
> +        var wish = wishDao.findByProductIdAndUserId(request.productId(), loginInfo.userId())
아 그렇군요! 제가 착각했나보네요ㅎㅎ 설명해주셔서 감사합니당!

2024-07-06 16:03 UTC, MangKyu commented on src/main/java/gift/model/product/Product.java
> +        ProductNameValidator.isValid(name);
저는 별도의 `ProductNameValidator`를 분리하지 않고 Product 내에서 해당 로직을 갖고 처리하는 것을 선호합니다! 이를 통해 Product 내에서 필요한 비즈니스 정책의 응집도를 높일 수 있었습니다ㅎㅎ
이렇게 별도의 validator를 분리하시는 방법으로도 한번 진행해보시면 좋을 것 같아요! 👍

2024-07-06 16:41 UTC, MangKyu commented on src/main/java/gift/controller/wish/WishController.java
> +        if (wish.isPresent()) {
넵넵 체이닝하는 방식 좋은 것 같습니다!

2024-07-06 17:01 UTC, momnpa333 commented on src/main/java/gift/auth/interceptor/AuthenticationInterceptor.java
> +public class AuthenticationInterceptor implements HandlerInterceptor {
감사합니다!

2024-07-06 17:03 UTC, momnpa333 commented on src/main/java/gift/model/product/Product.java
> +        ProductNameValidator.isValid(name);
product내에서 처리하면 product안의 코드가 길어질까봐 분리했었는데, 다음부터는 안에서 해보도록하겠습니다!

2024-07-06 17:04 UTC, momnpa333 commented
늦은 시간 리뷰해주셔서 정말 감사합니다!! ㅜ.ㅜ 특히 패키지 관련해서 같이 고민해주셔서 감사합니다!

2024-07-06 17:17 UTC, MangKyu commented on src/main/java/gift/model/product/Product.java
> +        ProductNameValidator.isValid(name);
좋습니다ㅎㅎ 일반적으로는 다음과 같은 흐름으로 진행되니 참고 부탁드립니다!
다음과 같은 흐름으로 처리되는 것이 바람직하다고 볼 수 있습니다!
1. 클라이언트의 입력을 DTO로 받음
2. 이때 입력 유효성 검사를 처리함
3. 비즈니스 로직 처리(Product 저장, 수정 등) 처리를 위해 도메인(Product)로 변환함
4. 이때 Product에 대한 비즈니스 유효성 검사를 처리함
5. Product를 기준으로 데이터를 저장 또는 수정함

2024-07-07 14:02 UTC, merged