전남대 BE_박준형 2주차 과제(step2)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #401
Opened 2024-07-05 11:55 UTC by cliant

### 코드를 작성하며 어려웠던 점 

1. JwtUtil 파일을 작성하며 Jwt 버전에 따라 메서드명이 다른 것을 확인했지만 아직 최신 버전의 메서드명으로 고치지 못했습니다.

2. local에서 작성 중이던 step2를 step1의 리뷰를 반영하여 급하게 고치며 옮겨 아직 미완성입니다.. 계속 하여 수정하여 업로드 하겠습니다.

2024-07-06 04:43 UTC, dc-choi requested changes
준형님 2주차 step2 과제 구현하시느라 고생하셨습니다~

자세한 내용은 코멘트에 적어두었습니다. 확인 부탁드려요~!

2024-07-06 04:43 UTC, dc-choi commented on src/main/java/gift/controller/UserController.java
> +@RequestMapping("/members")
공통된 URL 주소는 따로 빼는 부분이 좋았습니다~

2024-07-06 04:43 UTC, dc-choi commented on src/main/java/gift/controller/UserController.java
> +    public ResponseEntity<String> register(@RequestBody UserDto userDto){
`UserDto`의 값이 유효하지 않은 값이 들어오면 어떻게 되나요? 예외처리가 필요해보입니다.

2024-07-06 04:43 UTC, dc-choi commented on src/main/java/gift/controller/UserController.java
> +    public ResponseEntity<String> login(@RequestBody LoginRequest loginRequest){
마찬가지로 `LoginRequest`에 유효하지 않은 값이 있으면 어떻게 될까요? 예외처리가 필요해보입니다.

2024-07-06 04:43 UTC, dc-choi commented on src/main/java/gift/controller/UserController.java
> +        String token = jwtUtil.generateToken(userDto);
이 부분의 로직은 `Service` 레이어에 있어야 한다고 생각합니다. `Controller`의 역할에 맞지 않아 보입니다.

2024-07-06 04:43 UTC, dc-choi commented on src/main/java/gift/controller/UserController.java
> +        String token = jwtUtil.generateToken(userDto);
이 부분의 로직은 Service 레이어에 있어야 한다고 생각합니다. Controller의 역할에 맞지 않아 보입니다.

2024-07-06 04:43 UTC, dc-choi commented on src/main/java/gift/dao/UserDao.java
> +    public Optional<User> findByPassword(String password){
패스워드로만 검증을 진행하는 이유가 궁금합니다. 패스워드가 같은 유저가 있다면 어떻게 처리가 되는지에 대해 고민해보시고 더 나은 방향으로 수정해주시면 감사하겠습니다!

2024-07-06 04:43 UTC, dc-choi commented on src/main/java/gift/exception/InvalidUserException.java
> +public class InvalidUserException extends RuntimeException{
이 부분은 크게 두가지 문제가 있다고 생각합니다.

1. 상품이 유효하지 않고 유저가 유효하지 않은 예외를 따로 처리하게 됩니다. 구현해야하는 기능이 많아짐에 따라 나중에는 도메인에 맞는 예외를 더 추가하게 되는 상황이 온다고 생각합니다.
2. `GlobalExceptionHandler`에서 `InvalidProductException`에 대해서만 예외를 처리하였는데 `InvalidUserException`에 대한 예외가 처리가 되는지에 대한 의문이 있습니다.

공통 커스텀 예외 객체를 만들고 그 안에 메시지에서 구분을 지을 수 있도록 하는 것은 어떨까요?

2024-07-06 04:43 UTC, dc-choi commented on src/main/java/gift/service/UserService.java
> +    public UserDto findByPassword(String password){
위에서 언급한대로 패스워드로만 검증을 진행하는 이유가 궁금합니다. 패스워드가 같은 유저가 있다면 어떻게 처리가 되는지에 대해 고민해보시고 더 나은 방향으로 수정해주시면 감사하겠습니다!

2024-07-06 04:43 UTC, dc-choi commented on src/main/java/gift/util/JwtUtil.java
> +    String secretKey = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
원칙적으로는 secretKey는 외부에 노출이 되면 안됩니다~! 보안에 취약해져요~

2024-07-06 04:43 UTC, dc-choi commented on src/main/java/gift/util/JwtUtil.java
> +                .setSubject(userDto.getEmail())
회원에 권한에 대해서도 생각해볼 필요가 있습니다. 회원에 권한에 대한 부분도 고민해보시고 추가해주시면 될 거 같습니다.

2024-07-06 08:18 UTC, cliant commented on src/main/java/gift/controller/UserController.java
> +    public ResponseEntity<String> register(@RequestBody UserDto userDto){
유효성 검사를 추가하였습니다!

2024-07-06 08:18 UTC, cliant commented on src/main/java/gift/controller/UserController.java
> +        String token = jwtUtil.generateToken(userDto);
service 레이어에서 토근을 발행해 controller로 넘겨주게끔 코드를 변경하였습니다.

2024-07-06 08:19 UTC, cliant commented on src/main/java/gift/dao/UserDao.java
> +    public Optional<User> findByPassword(String password){
이메일과 패스워드 가지고 토큰을 발행 받는다라는 요구사항을 따르기 위해서 했는데 이메일이 좀 더 기본키에 가깝?다는 것을 생각하지 못했던 것 같습니다. findByEmail로 수정하였습니다.

2024-07-06 08:21 UTC, cliant commented on src/main/java/gift/exception/InvalidUserException.java
> +public class InvalidUserException extends RuntimeException{
CustomException란 공통 예외를 만들어 던지게 하고 추후에 예외 처리를 다르게 해야하는 경우가 생기면 message를 기반으로 예외처리를 다르게 구현한다! 라고 이해했는데 맞을까요?

2024-07-06 08:22 UTC, cliant commented on src/main/java/gift/util/JwtUtil.java
> +    String secretKey = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
application.properties에 명시하고 Service파일에서 그 값을 가져와 처리하도록 변경하였습니다.

2024-07-06 08:22 UTC, cliant commented on src/main/java/gift/util/JwtUtil.java
> +                .setSubject(userDto.getEmail())
users 속성에 role을 추가하였습니다.

2024-07-06 08:45 UTC, cliant commented on src/main/java/gift/util/JwtUtil.java
> +                .setSubject(userDto.getEmail())
금요일에 local에서 작업하던 step2를 제출해야겠다는 생각에 step1이 merge되기전에 이 PR을 제출하여 충돌이 발생하는데 혹시 다음 수정 때엔 step2_new라는 branch를 새로 만들어 PR요청을 보내도 될까요?

2024-07-07 03:01 UTC, closed without merging

2024-07-07 03:49 UTC, dc-choi commented on src/main/java/gift/util/JwtUtil.java
> +                .setSubject(userDto.getEmail())
네 그렇게 해주세요~!