경북대 BE_이도훈 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #403
Opened 2024-07-05 15:52 UTC by 2iedo

현재 제출한 코드는 관리자 페이지의 상품 추가/조회/삭제 기능 사용 시 role 이 ADMIN인 경우는 적용하지 않았습니다.
wishlist에 접근할 때 이메일이 일치하고 role이 ADMIN 또는 CONSUMER일 경우(모두 허용) 접근 가능하게 하였습니다.
접근 실패 시 401 Unauthorized 에러를 리턴하도록 구현하였습니다.

2024-07-06 14:15 UTC, khj68 requested changes
전반적으로 과제 요구사항을 잘 구현해주셨습니다.
api path와 if문과 throw의 위치에 대해서 다시 한 번 봐주시면 감사하겠습니다.
고생 많으셨습니다!

2024-07-06 14:15 UTC, khj68 commented on src/main/java/gift/Controller/WishlistController.java
> +@RequestMapping("/wishlist")
RestController의 api path 는 /api/v1 과 같이 명세와 버전으로 시작하는 것을 추천드립니다.

2024-07-06 14:15 UTC, khj68 commented on src/main/java/gift/Controller/WishlistController.java
> +    @PostMapping("/add")
restful api 에 의해 동사가 path에 직접적으로 들어가는 것은 좋지 않습니다.
이런 예시가 좋습니다. POST /api/v1/wishlist
이 때 post 라는 http method로 인해 새로 생성한다는 의미를 담고 있습니다.

2024-07-06 14:15 UTC, khj68 commented on src/main/java/gift/Controller/WishlistController.java
> +    @DeleteMapping("/delete/{name}")
마찬가지로 delete라는 동사를 지워주셔도 좋습니다.

2024-07-06 14:15 UTC, khj68 commented on src/main/java/gift/Controller/WishlistController.java
> +    }
ExceptionHandler는 글로벌하게 한 파일에서 관리하는 것을 추천드립니다.

2024-07-06 14:15 UTC, khj68 commented on src/main/java/gift/Service/ProductService.java
> +        throw new AuthorizedException();
예외 상황을 if문 안으로,
정상적인 상황을 throw 밑으로 두는 방식을 추천드립니다.

2024-07-06 14:15 UTC, khj68 commented on src/main/java/gift/Service/ProductService.java
> +        throw new AuthorizedException();
예외 상황을 if문 안으로,
정상적인 상황을 throw 밑으로 두는 방식을 추천드립니다.

2024-07-06 14:15 UTC, khj68 commented on src/main/java/gift/Service/ProductService.java
> +        throw new AuthorizedException();
예외 상황을 if문 안으로,
정상적인 상황을 throw 밑으로 두는 방식을 추천드립니다.

2024-07-06 14:15 UTC, khj68 commented on src/main/java/gift/Service/ProductService.java
> +        throw new AuthorizedException();
예외 상황을 if문 안으로,
정상적인 상황을 throw 밑으로 두는 방식을 추천드립니다.

2024-07-06 14:17 UTC, khj68 commented
회원별 위시리스트를 만들 때, 회원 별로 위시리스트 데이터베이스를 각각 하나씩 만드는 것과, 전체 큰 데이터베이스 하나에 이메일을 추가해서 구별하는 방법 중 어떤 것을 선택해야할 지 고민입니다. 현재는 큰 데이터베이스 하나에 이메일로 구별을 하여 조회 시 전체 데이터베이스에서 이메일을 기준으로 불러오게 하였습니다.

- 지금과 같이 wishlist라는 테이블을 만들고, 그 안에서 email이나 회원의 id를 fk로써 사용해주시는 방식이 좋습니다. 회원마다 테이블이 추가되면 확장성과 효율성이 크게 저하됩니다. 이는 앞으로 도메인을 설계할 때에도 동일합니다. 하나의 도메인은 하나의 테이블을 갖는다고 생각해주시면 되겠습니다.
고생하셨습니다 :)

2024-07-07 04:25 UTC, 2iedo commented on src/main/java/gift/Controller/WishlistController.java
> +@RequestMapping("/wishlist")
수정했습니다!

2024-07-07 04:25 UTC, 2iedo commented on src/main/java/gift/Controller/WishlistController.java
> +    @PostMapping("/add")
수정했습니다!

2024-07-07 04:25 UTC, 2iedo commented on src/main/java/gift/Controller/WishlistController.java
> +    @DeleteMapping("/delete/{name}")
수정했습니다!

2024-07-07 04:36 UTC, 2iedo commented on src/main/java/gift/Controller/WishlistController.java
> +    }
넵 ExcecptionHandler 클래스 추가했습니다.

2024-07-07 04:36 UTC, 2iedo commented on src/main/java/gift/Service/ProductService.java
> +        throw new AuthorizedException();
수정 완료했습니다!

2024-07-07 04:36 UTC, 2iedo commented on src/main/java/gift/Service/ProductService.java
> +        throw new AuthorizedException();
수정 완료했습니다!

2024-07-07 04:36 UTC, 2iedo commented on src/main/java/gift/Service/ProductService.java
> +        throw new AuthorizedException();
수정 완료했습니다!

2024-07-07 04:36 UTC, 2iedo commented on src/main/java/gift/Service/ProductService.java
> +        throw new AuthorizedException();
수정 완료했습니다!

2024-07-07 05:04 UTC, khj68 requested changes
도훈님, 고생하셨습니다!
풀패키지로 들어간 부분만 확인 부탁드립니다.

2024-07-07 05:04 UTC, khj68 commented on src/main/java/gift/Exception/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler(LoginException.class)
어노테이션이 풀 패키지로 들어간 것 같습니다. 
이 부분 클래스로만 들어갈 수 있게 변경 부탁드립니다.

2024-07-07 06:23 UTC, 2iedo commented on src/main/java/gift/Exception/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler(LoginException.class)
넵 변경했습니다!

2024-07-07 14:30 UTC, merged