충남대 BE_윤정훈 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #405
Opened 2024-07-05 18:42 UTC by yunjunghun0116

현재 구현중이며, 추후 설명 추가 진행하겠습니다!

2024-07-06 10:14 UTC, asebn1 requested changes
정훈님 안녕하세요~
빠른 코드반영 너무 좋습니다 👏👏
몇 가지 코멘트 드렸는데 확인해주세요!

2024-07-06 10:14 UTC, asebn1 commented on README.md
> +
👍 👍

2024-07-06 10:14 UTC, asebn1 commented on src/main/java/gift/config/AuthInterceptor.java
> +}
config의 `AuthInterceptor`가 `AuthService`를 의존하게 되었어요.
어떻게 수정할 수 있을까요?
- `AuthInterceptor`를 `controller/auth/` 패키지에서 관리하면 어떨까요?
- 로그인, 회원가입을 위한 `AuthController`도 만들어볼까요?

2024-07-06 10:14 UTC, asebn1 commented on src/main/java/gift/controller/MemberController.java
>      }
로그인, 회원가입은 `MemberController` 보다 `AuthController`에서 관리되는게 더 자연스러울 것 같아요

2024-07-06 10:14 UTC, asebn1 commented on src/main/java/gift/controller/WishProductController.java
> +    }
코드 통일을 `var`와 직접적인 타입명 중 `var`로 결정하신 이유가 궁금하네요 ㅎㅎ (정답은 없습니다)

2024-07-06 10:14 UTC, asebn1 commented on src/main/java/gift/dto/WishProductResponse.java
> +}
파라미터로 `WishProduct`를 받고있어요
1. dto에서 도메인 계층을 의존해도 괜찮을까요?
2. service용 dto, controller용 dto를 구분지어보면 어떨까요?

2024-07-06 10:14 UTC, asebn1 commented on src/main/java/gift/model/WishProduct.java
> +    }
count만 수정해주고 있어서 `updateCount`가 명확할 것 같아요

2024-07-06 10:14 UTC, asebn1 commented on src/main/java/gift/repository/MemberJDBCRepository.java
> +        return exists;
성능이 개선됐네요 :)

2024-07-06 10:14 UTC, asebn1 commented on src/main/resources/schema.sql
>  );
👍 👍

2024-07-06 10:14 UTC, asebn1 commented on src/test/java/gift/controller/MemberControllerTest.java
>                  .content(objectMapper.writeValueAsString(new RegisterRequest("테스트", "test@naver.com", "testPassword", "MEMBER"))));
꼼꼼한 테스트코드 좋아요 👍

2024-07-06 11:21 UTC, yunjunghun0116 commented on src/main/java/gift/controller/MemberController.java
>      }
로그인, 회원가입 기능은 AuthController에서 관리하고, 이용자의 Name, Email, Password 등의 정보 수정과 같이 이용자의 정보와 관련된 기능을 MemberController에서 관리하는게 더 자연스러울 것 같네요!
감사합니다 :)

2024-07-06 11:29 UTC, yunjunghun0116 commented on src/main/java/gift/controller/WishProductController.java
> +    }
저는 개인적으로 아래와 같이
1. 함수 내부와 같이 지역 변수로 사용되는 경우에만 var를 사용한다.
2. 전역, 함수의 리턴값, 매개변수 등에는 타입을 명시한다.

위 두가지의 기준을 갖고 사용하게 되면 컴파일러가 2번 기준에 의해 타입을 추론할 수 있으며 타입의 길이가 길어지더라도 변수의 타입 부분은 짧게 가져가면서 타입을 명확히 할 수 있을거 같다는 생각으로 var로 통일하게 되었습니다.

개인적으로 var를 남용하게 되면 오히려 코드를 이해하기 어려울 수 있지만 이 부분을 저는 2번 기준과 함께 
타입의 길이가 짧아진 만큼 변수명에서 ex) savedProduct, registerAuth 등과 같이 조금 더 명확하게 의미를 부여해서 코드를 이해하기 쉬운 코드로 작성하자 라는 생각을 갖고 코드를 작성하고 있습니다!

2024-07-06 11:58 UTC, yunjunghun0116 commented on src/main/java/gift/dto/WishProductResponse.java
> +}
DTO는 데이터 전송의 목적만을 갖고 있기에 다른 계층을 의존하면 안된다 생각합니다.
때문에 도메인 계층이 아닌 값을 집어 넣도록 수정해서 개선했습니다!

여기서 궁금한게 하나 생겼습니다!
WishProductResponse에 상품id가 아닌, 상품에 대한 정보를 담아 클라이언트에게 반환을 해주고 싶은데 그러기 위해서는 어쩔수 없이 WishProductResponse는 ProductResponse의 정보를 담아야 할 것 같습니다.

이러한 목적을 갖고 같은 DTO 계층간 의존이 필요한 경우에는 의존을 해도 괜찮을까요?
제 경우 선택지는 현재
1. ProductResponse 대신 productId, productPrice, productName 등의 정보까지 입력을 받는다.
2. ProductResponse를 그대로 가져온다.

라고 생각을 합니다. 

각각의 선택지의 단점은
1. ProductResponse의 필드가 추가될 경우, WishProductResponse도 추가해야하는 경우가 발생하는 등 상품의 필드가 추가되거나 변경될 경우 함께 변경해줘야 한다.
2. WishProductResponse가 ProductResponse에 의존하게 된다.

현재 저는 2번 선택지를 택했고, 그 이유는 객체의 이름에서 나타나듯 WishProductResponse는 어떤 상품이 몇개 추가되었는지가 중요하다 생각해서 Product에 의존할 수밖에 없다고 생각했습니다.

이 부분에 대해서 멘토님은 위와 같은 상황에서 둘 중 어떤 선택지를 고를 것 같고(다른 선택지가 있다면 해당 선택지), 그 이유는 무엇인지가 궁금합니다!

2024-07-06 12:46 UTC, yunjunghun0116 commented on src/main/java/gift/config/AuthInterceptor.java
> +}
+ controller/auth 내부에 AuthInterceptor와 AuthController를 두어 인증 관련 컴포넌트의 관리를 더 쉽게 할 수 있도록 개선해보았습니다!
+ 로그인, 회원가입을 위한 AuthController와 이용자의 정보 수정, 회원 탈퇴 등을 위한 MemberController로 구분하는게 관리 측면에서 좋을 것 같아 둘을 분리해보았습니다! 이에 따라 Service 계층도 AuthService와 MemberService로 분리해 관리하도록 개선해보았습니다.

질문에 대한 답변

AuthService를 의존하게 된 이유는 토큰을 복호화 하여 필요한 member_id, member_role 을 가져오는 로직은 비즈니스 로직이라고 생각하고, Service 계층에 위치하도록 했는데 생각해보니 서비스 토큰값이 동일하면 언제든 같은 값을 반환해줘야 하고, 복호화하는 과정은 비즈니스 로직보다는 토큰(인증) 로직에 가깝다 생각하여 AuthInterceptor로 함수를 이전하고, 의존하지 않도록 수정해보았습니다.

2024-07-06 12:53 UTC, yunjunghun0116 commented on src/main/java/gift/config/AuthInterceptor.java
> +}
추가질문

저는 private 생성자를 통해 인스턴스를 생성하지 못하도록 하고, static 메서드만을 제공하여 외부에서 객체를 생성하지 않고도 기능을 사용할 수 있도록 구현했습니다.

저는 세가지 선택지중 하나를 고려한 것인데
1. getMemberIdWithToken, getMemberRoleWithToken 을 Interceptor 내부에 위치시킨다
- 장점 : 외부에 의존하지 않으면서, 필요한 곳에서만 기능을 수행한다.
- 단점 : Service계층에서의 테스트가 어렵다. 회원가입, 로그인은 token을 반환하고, 이를 복호화해서 memberId와 memberRole을 가져와 확인하는 것이 불가능하기때문이다.

2. 위와 같이 UtilClass로 만들어 작업을 수행한다.
- 장점 : 외부에 의존하지 않으면서 필요한 곳에서 기능을 수행하고, 추가로 테스트 역시 가능하다.
- 단점 : 객체지향적 프로그래밍 보다는 절차지향적 프로그래밍에 가깝다.
- 참고 : https://www.mimul.com/blog/oop-alternative-to-utility-classes/

3. Auth클래스를 만들고 내부 필드로 token, key 를 갖고, 이를 복호화하는 각각의 함수를 해당 클래스 내부에 구현한다.
- 장점 : 객체지향적 프로그래밍에 가깝고, 외부에 의존하지 않는다.
- 단점 : 매 요청마다 객체를 생성한다. 


저는 테스트 로직을 세세히 작성하면서, 의존성은 최소화하고자 2번을 선택해 코드를 구현했습니다.
필요한 경우 위와 같이 구현해도 괜찮은게 맞을까요?
유틸클래스에 대해 비판적인 글이 많아 고민이었습니다.

2024-07-07 15:37 UTC, asebn1 commented on src/main/java/gift/config/AuthInterceptor.java
> +}
테스트만을 위해 private을 public으로 설정하는건 좋지 않다고 생각해요
통합테스트로 진행하거나, 리플렉션을 통해 private을 테스트할 수 있을 것 같아요

2024-07-07 15:46 UTC, asebn1 commented on src/main/java/gift/dto/WishProductResponse.java
> +}
> WishProductResponse는 ProductResponse의 정보를 담아야 할 것 같습니다.
이러한 목적을 갖고 같은 DTO 계층간 의존이 필요한 경우에는 의존을 해도 괜찮을까요?

같은 계층의 dto는 서로 의존해도 문제없다고 생각합니다

> 현재 저는 2번 선택지를 택했고, 그 이유는 객체의 이름에서 나타나듯 WishProductResponse는 어떤 상품이 몇개 추가되었는지가 중요하다 생각해서 Product에 의존할 수밖에 없다고 생각했습니다.
이 부분에 대해서 멘토님은 위와 같은 상황에서 둘 중 어떤 선택지를 고를 것 같고(다른 선택지가 있다면 해당 선택지), 그 이유는 무엇인지가 궁금합니다!

저도 2번이 좋을 것 같아요. 말씀 주신 같은 의견입니다 (ProductResponse의 필드가 추가될 경우, WishProductResponse도 추가해야하는 경우가 발생하는 등 상품의 필드가 추가되거나 변경될 경우 함께 변경해줘야 한다.)

추가로 계층간 의존 방향을 고민해봅시다!
1. Controller 계층에 있는 request dto를 Service 계층에서 의존해도 괜찮을까요?
2. Service 계층에 있는 response dto를 controller 계층에서 의존해도 괜찮을까요?

2024-07-07 15:50 UTC, asebn1 approved these changes
정훈님 안녕하세요~ 이번에도 빠르게 구현해주셨군요 👏👏
잘 구현해주셔서 3단계는 이만 머지하겠습니다 :)

2024-07-07 15:51 UTC, merged