강원대 BE_김병수 2주차 과제(step3)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #406
Opened 2024-07-05 22:29 UTC by GamJaDo

# 어려웠던 점
- 사용자를 구별할 때 토큰으로 어떻게 활용하면 사용자를 찾을 수 있을지를 생각하는 시간이 오래 걸렸습니다.
- 평소에 예외 처리를 잘 하지 않았는데 과제에서는 예외 처리를 신경 써서 하다 보니 실수가 좀 잦았습니다.
- service를 구현할 때 jdbcTemplate을 쓰기 위해 SQL 문을 작성해야 하는 데 복잡한 기능(저의 기준)을 구현해야 할 때 SQL 문을 작성하는 것이 어려웠습니다. -> 계속 공부해서 익숙해지도록 하겠습니다.

2024-07-06 11:50 UTC, jaymarystella requested changes
안녕하세요 병수님.
3단계 구현 고생많으셨습니다.
레이어관련과 테스트코드관련 수정사항들이 있는데요 이부분들 반영만 해주셔도 공수가 많이 들거같아요.
하시다가 어려운점있으시면 말씀주세요.

2024-07-06 11:50 UTC, jaymarystella commented on src/main/java/gift/controller/AdminController.java
> +    @PostMapping("/create")
create라는 단어를 빼면 어떨까요? 이미 PostMapping에 그의미가 들어있다고 생각합니다. 
url 설계를 어떻게 하면 좋을지도 자료조사해보시면 좋을 것 같습니다.

2024-07-06 11:50 UTC, jaymarystella commented on src/main/java/gift/controller/AdminController.java
> +    @DeleteMapping("/delete/{id}")
이 부분도 마찬가지입니다.

2024-07-06 11:50 UTC, jaymarystella commented on src/main/java/gift/controller/AuthController.java
> +        return ResponseEntity.ok(response);
문자열을 넣어서 리턴해주시는 의도가 있으실까요?

2024-07-06 11:50 UTC, jaymarystella commented on src/main/java/gift/controller/AuthController.java
> +        return ResponseEntity.ok(response);
컨트롤러내 복잡한 로직을 다른 레이어로 분리해보시면 좋을거같아요.

2024-07-06 11:50 UTC, jaymarystella commented on src/main/java/gift/controller/WishlistController.java
> +		}
이러한 로직도 서비스내에서 담당하는게 맞을거같습니다. 컨트롤러는 최대한 얇게 유지시켜주세요. 다른 메서드들도 마찬가지입니다.

2024-07-06 11:50 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
>  	private String name;
다른 부분들은 validation이 필요없을까요?

2024-07-06 11:50 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
>  	private String name;
그리고 사용자의 요청을 받는 클래스로써 사용이 되는용도면 괜찮겠지만 추후에 도메인 클래스로 사용한다면 부적절할 수 있는데요 이부분은 지금은 참고만해주세요

2024-07-06 11:50 UTC, jaymarystella commented on src/main/java/gift/service/AuthService.java
> +public class AuthService {
테스트코드가 없는 클래스들에 대해서도 테스트를 작성부탁드려요.

2024-07-06 16:20 UTC, GamJaDo commented on src/main/java/gift/controller/AdminController.java
> +    @PostMapping("/create")
말씀해 주신 것처럼 반영하겠습니다.

2024-07-06 16:20 UTC, GamJaDo commented on src/main/java/gift/controller/AdminController.java
> +    @DeleteMapping("/delete/{id}")
말씀해 주신 것처럼 반영하겠습니다.

2024-07-06 16:28 UTC, GamJaDo commented on src/main/java/gift/controller/AuthController.java
> +        return ResponseEntity.ok(response);
왜 저렇게 적게 되었냐면
nextstep 2단계 - 회원 로그인 부분에서 회원 가입의 Response가 

```json
{
	"token": ""
}
```

형식으로 되어 있었습니다. 그래서 처음에는 저렇게 보내려고 

Map<String, String> response = new HashMap<>();
response.put("token", token);
return ResponseEntity.ok(response);

이렇게 작성하였는데 문제 설명을 읽어보니 로그인 성공시 토큰 발급이여서 바꾸려고 하다가 저 방식 대로 그대로 코드를 수정해서 이런 결과가 나왔던것 같습니다.
현재는
return ResponseEntity.ok("User registered successfully");
이런식으로 처리하도록 변경하였습니다.

2024-07-06 16:31 UTC, GamJaDo commented on src/main/java/gift/controller/AuthController.java
> +        return ResponseEntity.ok(response);
service에서 처리하도록 변경하겠습니다.

2024-07-06 16:31 UTC, GamJaDo commented on src/main/java/gift/controller/WishlistController.java
> +		}
최대한 얇게 유지하도록 하겠습니다.

2024-07-06 16:34 UTC, GamJaDo commented on src/main/java/gift/model/Product.java
>  	private String name;
nextstep '1단계 - 유효성 검사 및 예외 처리'의 기능 요구 사항에서 
- 상품 이름은 공백을 포함하여 최대 15자까지 입력할 수 있다.
- 특수 문자
   - 가능: ( ), [ ], +, -, &, /, _
   - 그 외 특수 문자 사용 불가
- "카카오"가 포함된 문구는 담당 MD와 협의한 경우에만 사용할 수 있다.

라는 요구 사항만 있어 13~15 줄 처럼 작성했던것 같습니다.
다른 부분에서도 validation가 필요한 부분이 있는지 확인 후 추가 하겠습니다.

2024-07-06 16:35 UTC, GamJaDo commented on src/main/java/gift/service/AuthService.java
> +public class AuthService {
네 알겠습니다.

2024-07-06 19:06 UTC, GamJaDo commented on src/main/java/gift/model/Product.java
>  	private String name;
기능 요구 사항에는 없지만 추가하면 더 좋을 부분이 있는 것 같습니다.
price의 값을 음수를 입력 못하게 하는 것이 좋을 것 같습니다.

2024-07-07 09:21 UTC, jaymarystella commented on src/main/java/gift/controller/AuthController.java
> +        return ResponseEntity.ok(response);
응답 클래스를 정의하는것도 방법이니 다음단계때 고려한번해주세요!

2024-07-07 09:22 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
>  	private String name;
넵 유효성 검증은 보수적으로 잘 해주시는게 좋습니다. 더불어서 테스트케이스들도 있으면 좋을것 같습니다.

2024-07-07 09:26 UTC, jaymarystella approved these changes
안녕하세요 병수님.
리뷰 반영하느라 고생많으셨습니다.
테스트케이스들도 여럿 추가해주셨네요. 잘해보셨습니다.
이정도면 머지해도될것같고 다음 미션에서 뵐게요.

2024-07-07 09:26 UTC, jaymarystella commented on src/test/java/gift/test/WishlistTest.java
> +    public void testGetWishlist() {
테스트코드들도 잘 추가해주셨네요~

2024-07-07 09:26 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<String> updateProduct(@PathVariable("id") long id, @Valid @RequestBody Product product
추후에는 String이 아니라 응답 클래스를 정의할 필요성도 생길거같네요.

2024-07-07 09:26 UTC, merged