전남대 BE_서영우 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #408
Opened 2024-07-06 08:15 UTC by westzeroright

2024-07-06 16:16 UTC, pkeugine requested changes
안녕하세요 영우님
리뷰 남겨보았으니 한 번 확인해주시고, 질문에 대한 답변은 댓글로 남겨주세요!

이번 step 에 이전 리뷰들 중 반영되지 않은 것들도 챙겨주시면 좋을 것 같아요.
파이팅입니다! 🔥 🔥 🔥

2024-07-06 16:16 UTC, pkeugine commented on README.md
> +email과 password를 서버로 요청을 보내고 DBD에 일치한 회원이 있는지 확인 후 access token 발급
오타가 있는 것 같아요.
그리고 문서를 조금 더 구체적으로 작성하고, 개발하며 잘 활용해보면 어떨까요?

예를 들어 개발을 시작하기 전에 todo list 처럼 만들어야 할 기능을 나열하고,
commit 을 하면서 하나씩 체크하는거죠.

```markdown
- [x] 이렇게 체크 표시를 사용해볼 수도 있어요
- [ ] 이러면 완료되지 않은 작업을 나타내는거구요
```

2024-07-06 16:16 UTC, pkeugine commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
다른 의존성과는 다르게 이건 버전이 명시되어 있어요.
다른 코드나 글을 참고해서 넣어주셨겠지만, 이 참에 어떤 차이가 있는지 확인해보면 좋을 것 같아요.

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/login/JwtTokenUtil.java
> +    }
위의 방식과는 다르게 `decodeJWT` 는 한 줄에 메서드 체이닝을 해주셨네요. 방식을 비슷하게 유지해보죠!

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/login/JwtTokenUtil.java
> +    public Claims decodeJWT(String token) {
`decodeJWT` 라는 이름을 대중적인 컨벤션에 맞게 수정해보면 좋을 것 같아요.
[google java style guide 라는 컨벤션을](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case) 굉장히 많은 개발자분들이 참고하고 적용하는 편인데,
이 내용을 한 번 확인해보죠.

뭔가 한 번 봤던 리뷰같지 않나요? :)
[제가 한 번 남겼던 적이 있는 내용](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/145#discussion_r1659608078)이네요.
아무래도 리뷰가 짧은 시간동안 많이 생기다보니 놓친 부분이 있을 것 같아 다시 남겨보아요!

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/login/LoginMember.java
> +public @interface LoginMember {
커스텀 어노테이션!
잘 만들어주셨네요. 👍 👍 👍 
`@Retention` 과 `@Target` 은 각각 어떤 내용을 나타내는건가요?
그리고 여기에 들어가는 값들은 `RUNTIME` 과 `PARAMETER` 외에 어떤 것들이 있는지,
각각 무엇을 의미하는지도 알아보죠!

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/login/LoginMember.java
> +            System.out.println("토큰"+token);
값을 출력해서 console 창에서 확인할 수 있도록 해주셨군요 👍 
`System.out.println` 말고 로깅을 적용해보시면 어떨까요?

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/login/LoginMember.java
> +    class LoginMemberArgumentResolver implements HandlerMethodArgumentResolver {
해당 클래스는 어노테이션 안에 두기보단 별도의 자체 파일로 관리해봐도 좋을 것 같아요.

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/member/Member.java
> +    private boolean role;
충분히 필드로 알 수 있는 내용인 것 같으니 주석은 제거해보죠!

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/member/MemberController.java
> +    }
이 메서드는 어떤 용도로 만드셨을까요?

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/product/GlobalExceptionHandler.java
> -
주석 제거 리뷰 반영 👍

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/wishlist/WishlistController.java
> +//        }
주석을 제거하자는 리뷰를 이번 pr 에 반영해주셔서 기분이 좋았는데...
다른 부분에서 생겨서 마음이 아픕니다 ㅠㅜ

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/wishlist/WishlistController.java
> +        }
그래도 예외를 던지고, GlobalExceptionHandler 에서 이를 처리해주는 것은 좋네요 :)

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/wishlist/WishlistDao.java
> +    private final ProductDao productDao;
해당 필드는 어떤 이유로 추가해주신걸까요?
일단 사용하지 않으므로 제거해주죠!

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/wishlist/WishlistDao.java
> +    }
코드가 이렇게 되는건 지양해주세요!

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/wishlist/WishlistController.java
> +@RequestMapping("/api/wishes")
wish 와 wishlist 라는 표현이 함께 사용되고 있는데, 이를 하나로 통일해보면 좋을 것 같아요.

2024-07-06 16:16 UTC, pkeugine commented on src/main/java/gift/member/Member.java
> +    }
이 생성자는 어떠한 이유로 추가되었나요?

2024-07-06 17:20 UTC, pkeugine commented
코멘트가 하나 누락됐네요! 로그아웃 기능도 만들어보도록 하죠 :)

2024-07-07 05:34 UTC, westzeroright commented on README.md
> +email과 password를 서버로 요청을 보내고 DBD에 일치한 회원이 있는지 확인 후 access token 발급
넵 알겠습니다!

2024-07-07 05:38 UTC, westzeroright commented on src/main/java/gift/login/JwtTokenUtil.java
> +    public Claims decodeJWT(String token) {
으악 다시 한 번 정리하겠습니다..

2024-07-07 05:45 UTC, westzeroright commented on src/main/java/gift/member/Member.java
> +    }
엇 분명 필요해서 추가했는데 지워도 오류가 나지 않은 것 같으니 필요가 없는 것 같습니다

2024-07-07 13:17 UTC, westzeroright commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
스프링 부트 Gradle plugin은 스프링 부트 의존성 관리 및 애플리케이션 패키이징을 지원하고 
io.spring.dependency-management 플러그인을 적용하면 사용중인 스프링 부트 버전에 맞는 의존성을 자동으로 가져올 수 있는 것을 확인했습니다. 특별히 버전을 명시해서 사용하는 경우 해당 버전으로 오버라이딩되어 사용된다고 확인하였습니다.

2024-07-07 13:31 UTC, westzeroright commented on src/main/java/gift/login/LoginMember.java
> +public @interface LoginMember {
`@Retention` : 해당 어노테이션을 언제까지 유지할 것인지를 정의하는 부분

- 종류
    - `@Retention(RetentionPolicy.SOURCE)` - 컴파일 이후에도 계속 참조 가능
    - `@Retention(RetentionPolicy.CLASS)`  - 컴파일러가 클래스를 참조할 때까지 유표
    - `@Retention(RetentionPolicy.RUNTIME)` - 컴파일 전까지만 유효

`@Target` : Java compiler가 annotation이 어디에 적용될지 결정하기 위해 사용

```
ElementType.PACKAGE : 패키지 선언
ElementType.TYPE : 타입 선언
ElementType.ANNOTATION_TYPE : 어노테이션 타입 선언
ElementType.CONSTRUCTOR : 생성자 선언
ElementType.FIELD : 멤버 변수 선언
ElementType.LOCAL_VARIABLE : 지역 변수 선언
ElementType.METHOD : 메서드 선언
ElementType.PARAMETER : 전달인자 선언
ElementType.TYPE_PARAMETER : 전달인자 타입 선언
ElementType.TYPE_USE : 타입 선언
```
이렇게 알아보았습니다!

사실 과제 진행 중에 `@Target(ElementType.PARAMETER)` 이 부분을 메서드로 잘못 지정하여 막혔었는데 이번에 공부하게 되어서 좋네요:)

2024-07-07 14:52 UTC, westzeroright commented on src/main/java/gift/login/LoginMember.java
> +    class LoginMemberArgumentResolver implements HandlerMethodArgumentResolver {
원래 따로 클래스 파일이 있었으나 step2 브랜치와 step3 브랜치를 오가며 이런 문제가 발생한 것 같습니다🥲

2024-07-07 14:53 UTC, westzeroright commented on src/main/java/gift/member/MemberController.java
> +    }
제거했습니다..!

2024-07-07 14:53 UTC, westzeroright commented on src/main/java/gift/wishlist/WishlistController.java
> +//        }
ㅜㅜ저도요..😢

2024-07-09 17:01 UTC, westzeroright commented on src/main/java/gift/login/JwtTokenUtil.java
> +    }
반영했습니다!

2024-07-09 17:01 UTC, westzeroright commented on src/main/java/gift/login/JwtTokenUtil.java
> +    public Claims decodeJWT(String token) {
반영했습니다!

2024-07-09 17:01 UTC, westzeroright commented on src/main/java/gift/login/LoginMember.java
> +            System.out.println("토큰"+token);
반영했습니다!

2024-07-09 17:01 UTC, westzeroright commented on src/main/java/gift/login/LoginMember.java
> +    class LoginMemberArgumentResolver implements HandlerMethodArgumentResolver {
반영했습니다!

2024-07-09 17:01 UTC, westzeroright commented on src/main/java/gift/member/Member.java
> +    private boolean role;
반영했습니다!

2024-07-09 17:01 UTC, westzeroright commented on src/main/java/gift/wishlist/WishlistDao.java
> +    private final ProductDao productDao;
반영했습니다!

2024-07-09 17:01 UTC, westzeroright commented on src/main/java/gift/wishlist/WishlistDao.java
> +    }
반영했습니다!

2024-07-09 17:01 UTC, westzeroright commented on src/main/java/gift/wishlist/WishlistController.java
> +@RequestMapping("/api/wishes")
반영했습니다..!

2024-07-09 17:02 UTC, westzeroright commented
> 코멘트가 하나 누락됐네요! 로그아웃 기능도 만들어보도록 하죠 :)

반영했습니다!

2024-07-09 17:02 UTC, westzeroright commented
멘토님 1주차, 2주차 피드백 모두 3주차 0단계 PR에 걸쳐 모두 반영했습니다:)

2024-07-10 13:32 UTC, pkeugine approved these changes
다음 미션 진행중이라 이만 머지하도록 하겠습니다.
리뷰 확인하시느라 고생하셨어요 👍

2024-07-10 13:32 UTC, pkeugine commented
conflict 가 발생하고 있네요.
이 부분 해결해주시면 머지하도록 하겠습니다.

2024-07-13 08:56 UTC, merged