전남대 BE_서지우 2주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #413
Opened 2024-07-06 15:20 UTC by seojiu

step2에서 피드백 주신 
1. 테스트 코드 사용하기
2. 로그아웃 기능 구현하기
3. DTO 사용하기
부분은 아직 반영하지 못했습니다. 열심히 공부해서 차차 반영하도록 하겠습니다.

2024-07-06 17:34 UTC, pkeugine requested changes
안녕하세요 지우님,
미션 잘 진행해주시고 계시네요 👍 
짧은 시간동안 점점 발전하고 있는게 보여요!

몇 가지 리뷰 남겨봤고,
수정 또는 추가해볼만한 요소가 있다고 생각하여 request changes 로 뒀어요.
리뷰 반영해보시고, 질문에 대한 답변은 코멘트로 달아주세요.
답변이 아니어도 아무 코멘트에 댓글로 의견이나 생각 마구 남겨주셔도 좋습니다.

정말 열심히 하시는 모습 멋있어요! 👍 
이번 미션 조금만 더 파이팅해보아요 :) 💪 💪 💪

2024-07-06 17:34 UTC, pkeugine commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
버전을 낮춰주신 이유가 궁금해요!
그리고 다른 의존성은 버전을 명시하지 않는데, 이 세개는 명시되어 있네요. 어떤 차이가 있을까요?

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/JwtUtil.java
>      }
이전에 대화 나누었던 부분 잊지말아주세요!
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/279#discussion_r1666773573

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/Member.java
> +    public Member( Long id, String email, String password ) {
```suggestion
    public Member(Long id, String email, String password) {
```

제가 불필요한 공백 찾는데 강점이 있어요 😂

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/Member.java
> -    }
setter 제거 💯 💯 💯

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/MemberController.java
> +        if(token.equals("NoEmail")){
```suggestion
        if ("NoEmail".equals(token)) {
```
공백...! 전체 프로젝트에 대해 한번씩 다 확인해주시면 좋을 것 같아요.
그리고 if 문 안의 로직을 위와 같이 바꿔보면 어떤 점이 다를까요? 꽤 중요한 내용이니 한 번 고민해보아요.

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/MemberController.java
> +            return new ResponseEntity<>("잘못된 비밀번호 입니다.", HttpStatus.FORBIDDEN);
controller 에서는 예외를 던지고 `GlobalExceptionHandler` 에서 그 예외를 받아 응답을 만들도록 해보면 어떨까요?
`GlobalExceptionHandler` 에 예외 발생시 응답을 내려주는 로직을 모아두는거죠!

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/MemberController.java
> +            return new ResponseEntity<>("잘못된 비밀번호 입니다.", HttpStatus.FORBIDDEN);
발생하는 예외를 세부적으로 구분하여 잘 만들어주셨네요 👍 
그런데 로그인 같은 기능은 특이하게 `세부적인 메시지` 를 클라이언트에게 전달하는게 오히려 안좋을 수도 있어요.
왜냐하면 로그인을 시도하는 사람이 이메일이 틀린건지, 비밀번호가 틀린건지 알 수 있기 때문인데요
그렇기 때문에 로그인에 실패하면 오히려 두루뭉실한 메시지를 전달하고, 실패한 사람이 원인을 찾도록 하는게 아이러니하게 보안상 이점이 있는 케이스랍니다 ㅋㅋㅋ

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/MemberRepository.java
> +        Number newId = simpleJdbcInsert.executeAndReturnKey(parameters);
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/279#discussion_r1666782363
이 코멘트를 참고해서 Number 가 아닌 다른 타입을 사용해보면 좋을 것 같네요.
질문에 대한 답변도 한 번 남겨주세요!

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/Product.java
> -    @Min(value = 0, message = "가격은 0원 이상의 값만 가능합니다.")
> DTO 사용하기 부분은 아직 반영하지 못했습니다.

한 번 반영하고 머지해볼까요?

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/WishListController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
`ResponseEntity.created()` 를 사용해보면 어떨까요?
각 http response 에 대한 메서드들이 많이 만들어져있으니 프로젝트 전체적으로 적용해보면 좋을 것 같아요.

`created` 는 위의 메서드를 사용하시게 되면 추가적으로 넣어줘야 할 내용이 있어요.
이게 어떤 내용인지 알아보시고 한 번 적용해보죠!

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/WishListController.java
> +    @PostMapping("/add")
POST  작업을 하니까 uri 경로에 `/add` 를 넣어주지 않아도 될 것 같아요.
`/remove` 도 동일한 이유로 제거할 수 있겠네요!

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/WishListRepository.java
> +        wishList.setProductId(resultSet.getLong("productId"));
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/279#discussion_r1666780113

제거해주세요!

pr 에서 리뷰를 남기려다가
'이거 이전에 남긴 적이 없을까?' 하는 생각에
이전 pr 을 번갈아가며 확인하며 비교하는 과정이 조금은 힘드네요 🥲 
잘 챙겨주시면 정말 감사하겠습니다.

2024-07-06 17:34 UTC, pkeugine commented on src/main/java/gift/WishListService.java
> +        return wishListRepository.findByMemberId(member.getId());
```suggestion
        Member member = memberRepository.findMemberByEmail(email)
            .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 이메일입니다."));
        return wishListRepository.findByMemberId(member.getId());
```

Optional 은 이렇게도 활용해볼 수 있어요!
위의 코드를 복붙하지 마시고 직접 입력해서 작성해보는 것을 추천드려요 :)
Optional 이 사용되고 있는 프로젝트의 다른 부분들도 변경해보는 걸 도전해볼까요?

2024-07-06 17:34 UTC, pkeugine commented on src/main/resources/schema.sql
> +CREATE TABLE wish_list (
다른 테이블과 마찬가지로 복수형으로 이름을 지어보는건 어떨까요?
아니면 다른 테이블을 단수형으로 지어봐도 좋구요.

2024-07-06 17:34 UTC, pkeugine commented on src/main/resources/schema.sql
> +    FOREIGN KEY (productId) REFERENCES products(id)
foreign key 를 설정해주셨군요! 👍 
어떠한 이유로 추가해주셨나요?

2024-07-06 17:34 UTC, pkeugine commented on src/main/resources/schema.sql
> +);
> 로그아웃 기능 구현하기 부분은 아직 반영하지 못했습니다. 

반영한 뒤에 머지해보면 좋을 것 같아요!
너무 시간이 부족하다면 다음 단계에서는 꼭 해봤으면 하구요.

2024-07-06 17:34 UTC, pkeugine commented on src/main/resources/schema.sql
> +);
> 테스트 코드 사용하기 부분은 아직 반영하지 못했습니다.

이 부분 역시 다음 단계까지는 간단하게라도 도전해보면 좋을 것 같은데,
로그아웃에 시간을 먼저 사용해보시고 남는 시간을 활용해주세요!

2024-07-06 17:34 UTC, pkeugine commented on src/main/resources/schema.sql
> +);
저번주 미션의 PR 3개와 이번주 미션의 이전 PR 들에 제가 질문을 남겨봤었는데요,
그 중 몇가지는 답변을 받지 않은 상태입니다.
나름 기다리고 있어요...!
물음표로 끝나는 코멘트는 답변을 기대하는 코멘트거든요.

구현해주신 방식이나 사용하신 코드에 대한 질문이니 꼭 고민하는 시간을 가져보고 답변을 남겨보면
분명 도움이 많이 될거라 생각해요.

꽤나 많은 내용을 학습하고 있고, 짧은 시간동안 많은 것을 해보느라 고생하시고 있죠 🥲 
하지만 이왕 하는거 제대로 흡수하고 넘어가보아요.
저도 계속 도울게요 :)

2024-07-06 17:34 UTC, pkeugine commented on src/main/resources/schema.sql
> +);
아마 미션을 진행하시다보면 step 1 이 머지되지 않았는데 step 2, step 3 까지 진행하시는 경우가 있을텐데요,
git rebase 기능을 한 번 학습해보시고, step 3 PR 에는 step 2 또는 step 1 때의 커밋이 들어가지 않도록 해보면 좋을 것 같아요!

2024-07-08 06:32 UTC, seojiu commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
deprecated 해결하다가 잘 안 돼서 차라리 버전을 낮춰버렸습니다....
버전이 명시 되지 않은 곳은 io.spring.dependency-management 플러그인에 의해 Spring Boot dependency에 있는 버전을 자동으로 가져와서 생략이 가능하다고 공부했습니다.

2024-07-08 06:50 UTC, seojiu commented on src/main/java/gift/JwtUtil.java
>      }
👌👌

2024-07-08 07:15 UTC, seojiu commented on src/main/java/gift/MemberController.java
> +        if(token.equals("NoEmail")){
token.equals("NoEmail")를 사용할 경우 token이 null일 때 NullPointerException이 발생 할 수 있고, 
if ("NoEmail".equals(token))을 사용할 경우 token이 null이면 false가 반환 됩니다.
null 안정성을 위해서 수정하는게 좋을 것 같습니다. 감사합니다!!

2024-07-08 07:57 UTC, seojiu commented on src/main/java/gift/MemberRepository.java
> +        Number newId = simpleJdbcInsert.executeAndReturnKey(parameters);
수정하겠습니다. 코멘트도 남겼습니다!!

2024-07-08 07:58 UTC, seojiu commented on src/main/java/gift/Product.java
> -    @Min(value = 0, message = "가격은 0원 이상의 값만 가능합니다.")
👌👌

2024-07-08 08:44 UTC, seojiu commented on src/main/java/gift/WishListRepository.java
> +        wishList.setProductId(resultSet.getLong("productId"));
수정하겠습니다!

2024-07-08 09:39 UTC, seojiu commented on src/main/resources/schema.sql
> +    FOREIGN KEY (productId) REFERENCES products(id)
memberId는 members 테이블의 id를 참조하도록 하고,
productId는 products 테이블의 id를 참조하게끔 만들려고 FOREIGN KEY를 사용해봤습니다

2024-07-08 19:49 UTC, seojiu commented on src/main/resources/schema.sql
> +);
공부하겠습니다!!!

2024-07-10 13:25 UTC, pkeugine approved these changes
다음 미션에서 이어서 진행하므로 머지하도록 하겠습니다

2024-07-10 13:26 UTC, merged