강원대 BE_박지희 2주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #416
Opened 2024-07-06 17:35 UTC by peacefullyquietly

2024-07-06 17:41 UTC, peacefullyquietly commented
브랜치 조정 후 다시 PR 넣었습니다!

2024-07-07 08:44 UTC, jaymarystella requested changes
안녕하세요 지희님.
2단계 구현하느라 고생많으셨습니다.
몇가지 코멘트 남겨두었는데 확인 후 의견 및 반영부탁드릴게요

2024-07-07 08:44 UTC, jaymarystella commented on src/main/java/gift/service/JwtUtil.java
> +package gift.service;
> 현재는 JwtUtil 클래스를 서비스 패키지 내에 두었는데 따로 분리 시켜야 하는것인지, 어떤 패키지 하위에 위치해야 하는 것인지 잘 모르겠습니다

util패키지를 따로 만드셔도되는데 지금은 서비스내에서만 사용되니 현상유지도 괜찮다고 생각합니다.

2024-07-07 08:44 UTC, jaymarystella commented on src/main/java/gift/service/JwtUtil.java
> +public class JwtUtil {
전체적으로 테스트코드들이 없는데 추가해보실 수 있으실까요?

2024-07-07 08:44 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +    }
이 부분은 따로 분리하시는게 더 좋을것같아요.

2024-07-07 08:44 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +    private final JwtUtil jwtUtil;
주입받지 않고도 사용이 가능할까요?

2024-07-07 08:44 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +    }
로직을 잘 작성해주셨어요~ 여력이 되시면 optional처리 개선도 해보시면 좋을것같습니다.

2024-07-07 08:44 UTC, jaymarystella commented on src/main/java/gift/controller/MemberController.java
> +        }
컨트롤러 내 로직들을 작성주신 서비스내로 옮기시는것을 추천드립니다. 컨트롤러를 최대한 얇게 유지시켜주세요.

2024-07-07 15:12 UTC, peacefullyquietly commented on src/main/java/gift/service/MemberService.java
> +    }
넵 수정하겠습니다! 혹시 가독성을 위해 분리하는건가요?

2024-07-07 15:18 UTC, peacefullyquietly commented on src/main/java/gift/service/MemberService.java
> +    private final JwtUtil jwtUtil;
음 아니오! 그래서 아래쪽에 생성자로 주입했는데 혹시 그걸 말씀하신게 아닌가요?

2024-07-07 15:18 UTC, peacefullyquietly commented on src/main/java/gift/controller/MemberController.java
> +        }
넵 수정해보겠습니다

2024-07-07 15:18 UTC, peacefullyquietly commented on src/main/java/gift/service/JwtUtil.java
> +package gift.service;
넵 감사합니다

2024-07-08 01:06 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +    private final JwtUtil jwtUtil;
객체생성하지않고 static메서드로도 구현가능해보여서 말씀드렸어요

2024-07-08 01:09 UTC, jaymarystella commented on src/main/java/gift/controller/MemberController.java
> +        return ResponseEntity.ok().body(Collections.singletonMap("message", "Success"));
일전에도 말씀드렸던거같은데 컨트롤러에 로직작성은 최대한 지양해주세요

2024-07-08 01:09 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +    }
말씀주신 측면도있고 service 내부에서만 쓰이는게 아니라면 해당 상태값들은 따로 관리되는게 더 용이합니다. 여러 메세지나 다른 서비스에서도 충분히 이용하는 값으로 보여서요.

2024-07-08 01:22 UTC, jaymarystella approved these changes
안녕하세요 지희님.
구조관련한 부분은 다음 주차시작하기전에 수정부탁드려요.
고생많으셨습니다.

2024-07-08 01:22 UTC, merged