Step3
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #422
Opened 2024-07-07 03:03 UTC by cliant

step2를 금요일에 제출을 위해 merge후 제출하지 않고 step1 에서 branch를 생성하여 PR에 충돌이 생겨 리뷰요청을 할 수 없게 됐습니다... 그래서 새로운 PR에 리뷰를 반영한 step2코드를 추가하고 step3까지 구현하여 제출합니다.

### 코드 작성하면서 어려웠던 점

1. jwtUtil 파일에서 jwts 버전을 확인하였음에도

`The method setClaims(Map<String,?>) from the type JwtBuilder is deprecated`
이러한 메세지가 계속하여 발생하고 있습니다. 혹시 버전 이외에 다른 문제가 있는 것인지 궁금합니다.

### 리뷰시 중점적으로 봐주셨으면 하는 부분
저번처럼 전체적으로 구현되지 않은 부분이나 미흡하다고 판단되는 부분을 지적해주셨으면 합니다. 감사합니다

2024-07-07 05:43 UTC, dc-choi requested changes
안녕하세요 준형님~

과제를 하시면서 실력이 향상되시는거 같아보입니다~!

자세한 내용은 코멘트를 남겼습니다~! 감사합니다~!

2024-07-07 05:43 UTC, dc-choi commented on src/main/java/gift/controller/WishListController.java
> +    @PostMapping("/add")
추가한다는 행위는 이미 POST Method를 통해서 표현하게 됩니다.

restful api에 대해서 다시 고민해주세요.

2024-07-07 05:43 UTC, dc-choi commented on src/main/java/gift/controller/WishListController.java
> +    @DeleteMapping("/delete")
마찬가지로 삭제한다는 행위는 DELETE Method를 통해서 표현하게 됩니다.

restful api에 대해서 다시 고민해주세요.

2024-07-07 05:43 UTC, dc-choi commented on src/main/java/gift/controller/WishListController.java
> +        return new ResponseEntity<>(HttpStatus.CREATED);
`HttpStatus.CREATED`란 무엇인가요? 특별히 사용한 목적이 있나요?

2024-07-07 05:43 UTC, dc-choi commented on src/main/java/gift/controller/WishListController.java
> +        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
`HttpStatus.NO_CONTENT`란 무엇인가요? 특별히 사용한 목적이 있나요?

2024-07-07 05:43 UTC, dc-choi commented on src/main/java/gift/util/JwtUtil.java
> +    public String extractEmail(String token) {
`extractEmail`, `extractRole`, `extractId`로 각 프로퍼티에 대해서 메서드를 나누기 보단 하나의 객체를 반환해주는 것이 추후 유지보수에 더 좋은 코드라고 생각합니다.

자료형이 문제라면 위 `extractAllClaims`에서 변환 후 내려주는건 어떨까요?

2024-07-07 05:43 UTC, dc-choi commented on src/main/java/gift/util/JwtUtil.java
> +    public boolean validateToken(String token, UserDto userDto) {
`Bearer` 인증 방식을 사용하고 있는데 `Bearer`에 대한 부분을 인증하는 것이 누락된 것으로 보입니다.

다시 한번 고민해주세요.

2024-07-07 09:19 UTC, cliant commented on src/main/java/gift/controller/WishListController.java
> +        return new ResponseEntity<>(HttpStatus.CREATED);
1주차에 과제를 진행할 때 클라이언트에게 좀 더 명확한 메세지 전달을 위해 작업에 따라 응답 코드를 다르게 한다는 자료를 참고했던 기억이 있어 사용 했습니다. 다만 그 자료에 대한 기억말곤 다른 특별한 이유가 없어 HttpStatus.OK로 통일하는 것으로 바꿨는데 이 차이에 대해 궁금합니다.

2024-07-07 09:19 UTC, cliant commented on src/main/java/gift/controller/WishListController.java
> +    @PostMapping("/add")
추가적인 경로 없이 /wishlist에서 method만으로 행위를 구분하게끔 변경하였습니다.

2024-07-07 09:19 UTC, cliant commented on src/main/java/gift/util/JwtUtil.java
> +    public String extractEmail(String token) {
변환 후 내려주는 것을 제가 이해하지 못해.. extractEmail, extractRole, extractId을 삭제하고  extractAllClaims로만 처리하도록 하였습니다.

2024-07-07 09:20 UTC, cliant commented on src/main/java/gift/util/JwtUtil.java
> +    public boolean validateToken(String token, UserDto userDto) {
넵! 리뷰 반영하여 수정하였습니다.

2024-07-07 09:26 UTC, cliant commented on src/main/java/gift/util/JwtUtil.java
> +    public boolean validateToken(String token, UserDto userDto) {
추가적으로 토큰 검증을 현재 controller에서 수행하고 있는데 이를 Service 레이어의 역할인 것 같다는 생각이 들었지만 코드중복이 심할 것 같아 우선 controller에서 하도록 하였습니다. 무엇이 나을지 궁금합니다!

2024-07-07 14:22 UTC, dc-choi requested changes
준형님~ 전체적으로 리뷰를 해드렸습니다~!

상세 코멘트를 확인 부탁드립니다~!

질문주신 부분은 gradle을 clean해보고 다시 해보시겠어요?

아마 기존 버전으로 동작하는 것으로 보입니다.

2024-07-07 14:22 UTC, dc-choi commented on src/main/java/gift/controller/UserController.java
> +        String token = userService.generateToken(loginRequest.getPassword());
`generateToken`라는 부분은 login하는 역할의 메서드가 아니라고 생각합니다. 메서드 네이밍에 대해서 조금 더 고민해주세요.

그리고 password로만 로직을 검증하게 되면 잘못된 결과가 나올 수 있다고 생각합니다.

이 부분은 다시 고민해주세요.

2024-07-07 14:22 UTC, dc-choi commented on src/main/java/gift/service/UserService.java
> +    public String generateToken(String password){
`generateToken`에서는 password를 받아오는데 `findByPassword`에서는 `userDao.findByEmail()`로 email에 대한 로직을 검증합니다.

기능 요구사항에 대해서 다시 확인해주세요.

2024-07-07 14:22 UTC, dc-choi commented on src/main/java/gift/util/JwtUtil.java
> +    if (authorizationHeader == null || !authorizationHeader.startsWith("Bearer ")) {
`Bearer`에 대한 인증을 확실하게 처리하는 부분이 좋습니다. 굿!

2024-07-07 14:22 UTC, dc-choi commented on src/main/java/gift/exception/CustomException.java
> +public class CustomException extends RuntimeException{
공통의 에러로 처리하는 부분은 정말 잘한거 같습니다! 굿!

2024-07-07 14:22 UTC, dc-choi commented on src/main/java/gift/exception/GlobalExceptionHandler.java
>          return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
`HttpStatus.BAD_REQUEST`로만 예외가 안 들어올 수 있기 떄문에 발생한 예외의 HTTP Status값으로 처리하는건 어떻게 생각하시나요?

2024-07-07 14:22 UTC, dc-choi commented on src/main/java/gift/service/UserService.java
> +    public UserDto findByPassword(String email){
`findByPassword`라는 메서드의 동작과 일치하지 않습니다.

다시 고민해주세요.

2024-07-07 14:22 UTC, dc-choi commented on src/main/java/gift/controller/WishListController.java
> +    public String extractToken(String authorizationHeader){
`extractToken`은 JWT의 기능으로 보이는데 이 부분에 위치한 이유가 있을까요?

JwtUtil로 빼는게 좋아보입니다.

2024-07-08 01:32 UTC, cliant commented on src/main/java/gift/controller/UserController.java
> +        String token = userService.generateToken(loginRequest.getPassword());
authenticateUser 라는 새로운 메서드를 만들어 로그인 시 사용자 인증 기능을 추가하였습니다!

2024-07-08 01:32 UTC, cliant commented on src/main/java/gift/exception/GlobalExceptionHandler.java
>          return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
CustomException의 인자에 httpStatus를 추가하여 처리하도록 하였습니다

2024-07-08 01:33 UTC, cliant commented on src/main/java/gift/service/UserService.java
> +    public String generateToken(String password){
메서드명을 변경하였습니다.

2024-07-08 01:33 UTC, cliant commented on src/main/java/gift/service/UserService.java
> +    public UserDto findByPassword(String email){
메서드명을 변경하였습니다.

2024-07-08 01:34 UTC, cliant commented on src/main/java/gift/controller/WishListController.java
> +    public String extractToken(String authorizationHeader){
넵! 반영하였습니다.

2024-07-08 02:09 UTC, dc-choi approved these changes
준형님~! step3까지 진행하시느라 고생하셨습니다~!

승인 하도록 하겠습니다! 3주차 과제도 파이팅~!

2024-07-08 02:09 UTC, merged