전남대 BE_박민규 2주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #428
Opened 2024-07-07 09:13 UTC by ps9319

2024-07-07 14:38 UTC, dc-choi requested changes
민규님... 점점 성장하시는 모습이 너무 보기 좋습니다...

딱히 코멘트 드릴 부분이 없네요...

하단 코멘트만 답해주시면 바로 승인하도록 하겠습니다.

민규님이 주신 코멘트에 대해서 답하는 것으로 마무리를 해보도록 하겠습니다.

> step2에서 브랜치를 파서 step3를 파고, 그 step3를 upstream으로 pr날리면 자꾸 conflict가 납니다!... step2 내용이 upstream으로 merge된 것이라서 step2에서 판 step3브랜치에서 작업한 내용으로 upstream으로 pr을 날리면 conflict가 안 나야하는데 왜 자꾸 나느지 모르겠어요.. step2때도 마찬가지로 conflict가 나서 fetch merge해서 conflict를 해결했는데 왜 conflict가 나는지 모르겠습니다.

pull을 어떻게 가져오시는지는 모르겠지만 뭔가 꼬인 부분이 있으신거 같습니다. pull을 해오는 과정에서 다시 확인이 필요할 것으로 보입니다~!

> 제가 WishController에서 LoginUser 어노테이션으로 User를 가져오면서 인증을 구현하고, authService.authorizeUser를 통해 인가를 구현한 것 같은데 이게 잘 한 건가 궁금해요... 인증/인가를 처음 다루다 보니 시간도 오래걸리고 잘 했는지도 잘 모르겠습니다.

이 부분은 인증/인가에 대한 개념이 아직 잡히지 않은 것으로 보입니다. 간단하게 설명드리면 인증과 인가의 차이점은 다음과 같습니다.

인증: 사용자의 신원을 검증 (로그인)
인가: 사용자의 권한을 검증 (관리자만 관리자 기능에 접근)

이정도로 설명을 드릴 수 있을거 같습니다. 개념을 이해하시면 어느정도 이해가 되실 것으로 예상됩니다.

> 그리고 또 인터셉터를 이용해서 인증/인가를 구현하기도 하던데 인터셉터 학습하는데에 너무 어려움을 느껴서 혹시 인터셉터에 대해서 쉽게 설명해주실 수 있나요? ㅠㅠㅠㅠㅠ

이 부분은 Spring의 동작 원리에 대해서 어느정도 이해가 필요할 것으로 보입니다... 간단하게 말씀드리자면 Spring MVC로 접근하기 전 요청과 응답 값에 대한 처리를 할 수 있는 것. 이라고 말씀을 드릴 수 있을거 같네요.

2024-07-07 14:38 UTC, dc-choi commented on src/main/java/gift/config/WebConfig.java
> +    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> resolvers) {
`@LoginUser`가 적용되지 않은 API에 대해서는 어떻게 처리되나요?

2024-07-07 14:38 UTC, dc-choi commented on src/main/java/gift/auth/LoginUserArgumentResolver.java
> +        String role = claims.get("role", String.class);
`role`로 뭔가 동작을 하는 것은 아닌거 같은데 이 부분에서 적용한 이유가 있을까요?

2024-07-07 17:18 UTC, ps9319 commented on src/main/java/gift/config/WebConfig.java
> +    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> resolvers) {
supportsParameter에서 LoginUser라는 어노테이션이 없을 때 false를 반환하므로 addArgumentResolvers가 실행되지 않습니다!.. 그런데 이걸 여쭤보신게 맞는지 모르겠어요..

2024-07-07 17:22 UTC, ps9319 commented on src/main/java/gift/auth/LoginUserArgumentResolver.java
> +        String role = claims.get("role", String.class);
아! 'claims에 role이란 정보가 담겨있으니 일단 추출하자'라고 생각해서 작성했었습니다.
그런데 생각해보니 이걸 저기서 쓰는게 아니라 인가를 처리할 때 반환된 User의 role로 하는거군요!!

2024-07-07 18:19 UTC, ps9319 commented
으헝헝헣엉ㅎ 칭찬 너무 감사합니다!!!!
멘토님께서 말씀해주신 것 외에 상품을 등록할 때 관리자만 등록할 수 있도록 변경도 해보았습니다.

2024-07-08 01:15 UTC, dc-choi commented on src/main/java/gift/config/WebConfig.java
> +    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> resolvers) {
맞습니다~! 정확하게 이해하고 사용하는지 궁금해서 여쭤봤습니다~!

2024-07-08 01:16 UTC, dc-choi approved these changes
수고하셨습니다~! 3주차 과제도 파이팅 하시길!!!

2024-07-08 01:16 UTC, merged