충남대 BE_이택 2주차 과제(step3)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #435
Opened 2024-07-07 12:41 UTC by LeeTaek2T

궁금한 점
[1]commit을 안보이게 하려면 leetaek2T브랜치에서 시작하라고 하셨는데 그러면 과정이 다음과 같이 이뤄지면 될까요?

ex)

fork한 저장소의 leetaek2T브랜치에서 Step1이라는 새로운 브랜치 생성
코드 리뷰가 완료될 시 Step1브랜치를 leeTaek2T브랜치에 병합
fork한 저장소의 leeTaek2T에서 Step2브랜치 생성
...
...

+) step3브랜치를 base branch로 합병을 하려고하는데 DM으로 말씀드린 것처럼 되지가 안하 leetaek2T브랜치로 Step3단계를 병합합니다.. step3도 어떻게 해야 되는지 다시 생각해보겠습니다.

2024-07-07 23:18 UTC, ksy90101 requested changes
고생하셨습니다~
간단한 피드백을 남겼으니 확인해주세요~

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/Controller/UserController.java
> +      return ResponseEntity.notFound().build();
이부분을 예외처리를 통해 예외로 하면 어떨까요?

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/Controller/WishController.java
> +  @PostMapping("/add")
REST API에서 행위는 메서드로 나타내야 합니다.
지금 POST Method를 쓰니 충분히 행위를 나타내고 있으니 add라는 단어를 쓸필요 없어보여요.

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/Controller/WishController.java
> +    return ResponseEntity.ok(addedWishProduct);
리소스가 생성되었다면 201 created라는 응답코드가 어울리는거 같아요~

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/Controller/WishController.java
> +    return ResponseEntity.ok(deletedWishProduct);
삭제가 되었다면 대체 어떤 데이터가 내려갈수 있나요?
삭제가 된 데이터는 실제 없는거니깐 실제 내려줄 데이터가 없어야 하는거 아닌가요?

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/DTO/WishListDto.java
> +  }
생성자에서 인자로 받아야 하는거 아닌가요?
이러면 계속 빈값만 내려가는거 같은데요...

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/LoginUserArgumentResolver.java
> +    if (authorizationHeader == null || !authorizationHeader.startsWith("Bearer ")) {
"Bearer"를 상수로 해두면 어떨까요?

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/LoginUserArgumentResolver.java
> +    String token = authorizationHeader.substring(7);
7이라는 단어는 Bearer를 상수로 하면 length를 쓰면 될거 같아요1

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/DTO/WishListDto.java
> +public class WishListDto {
Java17을 쓰고 있으니 record를 한번 써보면 어떨까요?

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/Repository/WishListDao.java
> +  public ProductDto selectWishProduct(Long id) {
이름이 조금 안어울리는거 같아요.

일단 wishList와 wishProduct는 각각 무엇인지 한번 설명 가능할까요?

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/Service/UserService.java
> +    }
null을 리턴하는게 아니라 예외를 던져서 예외 처리 하면 좋겟네요.

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/Service/UserService.java
> +    if (email.equals(userByEmail.getEmail()) && password.equals(
해당 부분을 user에서 매칭하는지 체크하면 어떨까요?
user 객체에게 메시지를 던지는거죠.

2024-07-07 23:18 UTC, ksy90101 commented on src/main/java/gift/Service/UserService.java
> +    if (email.equals(userByEmail.getEmail()) && password.equals(
아래 jwtService에 메시지를 던져서 체크하는것처럼 말이죠!

2024-07-07 23:18 UTC, ksy90101 commented on src/main/resources/schema.sql
> +CREATE TABLE wishList
장바구니에 담긴 product를 어떻게 알수가 있나요?

2024-07-08 14:29 UTC, LeeTaek2T commented on src/main/java/gift/Controller/UserController.java
> +      return ResponseEntity.notFound().build();
네! 알겠습니다.
그리고 궁금한 것이 있습니다. 예외처리는 어떤 경우에 사용하는게 좋을까요?

2024-07-08 14:29 UTC, LeeTaek2T commented on src/main/java/gift/Controller/WishController.java
> +  @PostMapping("/add")
네 알겠습니다!!

2024-07-08 14:32 UTC, LeeTaek2T commented on src/main/java/gift/Controller/WishController.java
> +    return ResponseEntity.ok(addedWishProduct);
응답코드에 대해 더 공부해보겠습니다!

2024-07-08 14:35 UTC, ksy90101 commented on src/main/java/gift/Controller/UserController.java
> +      return ResponseEntity.notFound().build();
응답코드가 4xx, 5xx로 내려가야 하는 경우는 다 예외 처리한다고 생각하시면 좋을거 같아요~

2024-07-08 15:10 UTC, LeeTaek2T commented on src/main/java/gift/Controller/WishController.java
> +    return ResponseEntity.ok(deletedWishProduct);
해당 메서드는 클라이언트가 삭제를 요청하고 응답으로 어떤 product가 삭제되었는지 알려주는 메서드로 구현하였습니다.
(사용자가 삭제 요청을 하면, 삭제하려고 하는 id를 Controller->Service->dao로 보내고 dao에서 실질적으로 삭제를 하게 하였습니다. 그리고 사용자에게 어떤 product가 삭제되었는지 확인시켜 주기 위하여 ResponseEntity.ok(삭제된 product);로 응답하게 하였습니다.)

멘토님이 말씀해주신 것이 어떤 의도로 말씀해주신 것인지 잘 이해가 안됩니다... 
다시 한 번 설명해주시면 감사하겠습니다!!

2024-07-08 15:15 UTC, LeeTaek2T commented on src/main/java/gift/DTO/WishListDto.java
> +  }
WishListDto를 만들어 놓고 Controller, Service, Dao에서는 List를 새로 선언하여 구현했었네요ㅠㅠㅠㅠ
수정했습니다

2024-07-08 15:19 UTC, LeeTaek2T commented on src/main/java/gift/LoginUserArgumentResolver.java
> +    if (authorizationHeader == null || !authorizationHeader.startsWith("Bearer ")) {
네! 상수명 : TOKEN_TYPE으로 하여 상수로 설정하였습니다

2024-07-08 15:20 UTC, LeeTaek2T commented on src/main/java/gift/LoginUserArgumentResolver.java
> +    String token = authorizationHeader.substring(7);
반영하겠습니다!!

2024-07-08 15:43 UTC, LeeTaek2T commented on src/main/java/gift/DTO/WishListDto.java
> +public class WishListDto {
네! 활용해보겠습니다

2024-07-08 15:55 UTC, LeeTaek2T commented on src/main/java/gift/Repository/WishListDao.java
> +  public ProductDto selectWishProduct(Long id) {
wishList는 product를 담는 장바구니
wishProduct는 사용자가 장바구니에 담은 product
이렇게 생각을 하였습니다.

따라서, selectWishProduct는 장바구니(=wishList)에 담긴 product(=wishProduct)를 갖고 오게 하는 함수로 구현하였습니다.

해당 메서드의 이름을 어떻게 하면 좋을지 멘토님의 의견이 궁금합니다!!
그리고 실무에서 이와 같은 상황이 충분히 일어날 수 있다고 생각합니다. 이럴 때는 메서드에 간단한 주석을 달아두는 것이 좋은 방법일까요?

2024-07-08 15:56 UTC, LeeTaek2T commented on src/main/java/gift/Service/UserService.java
> +    }
네! 수정하겠습니다.
그리고 앞으로 이런 경우엔 예외처리를 하는 식으로 코드를 구현하겠습니다

2024-07-08 15:57 UTC, LeeTaek2T commented on src/main/java/gift/Controller/UserController.java
> +      return ResponseEntity.notFound().build();
지금과 같이 null을 제외하고, 어떤 경우에 예외처리를 하는게 좋을지 궁금합니다!

2024-07-08 16:07 UTC, LeeTaek2T commented on src/main/java/gift/Service/UserService.java
> +    if (email.equals(userByEmail.getEmail()) && password.equals(
말씀하신 부분도 기존의 예외코드를 이용하여 반영하였습니다!

2024-07-08 16:09 UTC, LeeTaek2T commented on src/main/resources/schema.sql
> +CREATE TABLE wishList
WishListDao에서 selectWishList메서드를 통해 장바구니에 담긴 모든 product를 알 수 있고, selectWishProduct메서드를 통해 특정 product의 정보만 따로 가져올 수 있게 하였습니다.

2024-07-09 14:50 UTC, ksy90101 approved these changes
2주차도 고생 많으셨어요~
답글을 달아주셔서 생각을 볼수 있었습니다!
언제든 궁금한게 있다면 DM주세요~
3주차도 같이 홧팅해보시죠!

2024-07-09 14:50 UTC, ksy90101 commented on src/main/java/gift/Controller/UserController.java
> +    return userService.userSignUp(userInfo);
여기도 통일성 있게 ResponseEntity를 쓰면 어떨까요?

2024-07-09 14:50 UTC, ksy90101 commented on src/main/java/gift/Controller/WishController.java
> +      .toUri();
URI.create를 쓰면 쉽게 가능할거 같기도 해요.
이렇게 해도 좋긴 하구요 👍 
명확하긴 하니깐요.

2024-07-09 14:50 UTC, ksy90101 commented on src/main/java/gift/Controller/WishController.java
> +    return ResponseEntity.ok(deletedWishProduct);
2xx코드는 성공이니 이런 경우엔 내려주는게 의미가 없을거 같아요.
따라서 204 noContent를 쓰면 어떨까 해요.

2024-07-09 14:50 UTC, ksy90101 commented on src/main/java/gift/Repository/WishListDao.java
> +  public ProductDto selectWishProduct(Long id) {
그렇다면 여기서 나오는 값은 wishProduct가 아니라 wishList아닌가요?
그래서 말한거였어요.

용어는 굉장히 중요한데요. DAO의 메서드는 대부분 행위 + 리턴값을 조합해서 쓰는거 같아요. 그런 의미에서 여쭤본거였습니다.

2024-07-09 14:50 UTC, ksy90101 commented on src/main/java/gift/Service/UserService.java
> +    if (email.equals(userByEmail.getEmail()) && password.equals(
제가 말한건 user 객체에 matchInfo(?) matchAuthInfo(?)와 같은 메서드로 처리해보면 어떨까 해서 의견을 드린거였어요~
jwtService에서도 메시지를 던져 valid를 체크하는것처럼요!

2024-07-09 14:50 UTC, merged

2024-07-09 17:11 UTC, LeeTaek2T commented on src/main/java/gift/Controller/UserController.java
> +    return userService.userSignUp(userInfo);
네! 반영하겠습니다

2024-07-09 17:11 UTC, LeeTaek2T commented on src/main/java/gift/Controller/WishController.java
> +      .toUri();
URI.create도 시도해보겠습니다!

2024-07-09 17:14 UTC, LeeTaek2T commented on src/main/java/gift/Controller/WishController.java
> +    return ResponseEntity.ok(deletedWishProduct);
아.. noContent가 있었죠...
감사합니다!

2024-07-09 17:16 UTC, LeeTaek2T commented on src/main/java/gift/Repository/WishListDao.java
> +  public ProductDto selectWishProduct(Long id) {
음... 그렇네요
3주차 step1에서 모두 수정하였습니다!

2024-07-09 17:17 UTC, LeeTaek2T commented on src/main/java/gift/Repository/WishListDao.java
> +  public ProductDto selectWishProduct(Long id) {
용어 신경 써서 코드에 반영하겠습니다