충남대 BE_박상우 2주차 과제 (0단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #45
Opened 2024-07-01 06:51 UTC by pswaao88

2024-07-06 02:48 UTC, Hyeon9mak requested changes
안녕하세요 상우님! 1단계 잘 진행해주셨습니다.

> 다른 사람의 코드를 참고하여 작성 후 하나 씩 리뷰하면서 공부하는 방법이 괜찮은 방법인지 의견이 궁금합니다.

사람마다 잘 맞는 공부 방법이 모두 다르죠!
상우님께서는 이 시간을 통해 본인에게 잘 맞는 공부 방법을 찾아나가시면 된다고 생각해요 😄 
간단한 코멘트 남겼으니 확인해주세요~!

2024-07-06 02:48 UTC, Hyeon9mak commented on src/main/java/gift/Exception/ProductExceptionHandler.java
> +        return new ResponseEntity<>(e.getBindingResult().getFieldErrors().getFirst().getDefaultMessage() ,HttpStatus.BAD_REQUEST);
`MethodArgumentNotValidException` 외 다른 예외가 발생하면 어떻게 처리될 수 있을까요?
모든 예외에 대해서 각각의 핸들러를 다 만들어주어야할까요? 😱 
(hint: exception interhitance)

2024-07-06 02:48 UTC, Hyeon9mak commented on src/main/java/gift/Exception/ProductExceptionHandler.java
>  @ControllerAdvice
`@ControllerAdvice` 와 `@RestControllerAdvice` 의 차이는 무엇일까요?

2024-07-06 02:48 UTC, Hyeon9mak commented on src/main/resources/schema.sql
> +);
NOT NULL 등으로 데이터 정합성을 더 고려해주면 좋겠네요~!
특히 email 은 사용자마다 고유해야하지 않을까요?

2024-07-06 02:48 UTC, Hyeon9mak commented on src/main/java/gift/Controller/ProductController.java
>      }
controller, model, service 를 나눈다는 것은 계층별을 명확히 나누어 유지보수시 각 계층별로 코드변화가 전파되는 것을 막고자 함을 말해요.
현재는 `Product` 라는 모델 하나로 모든 영역에 코드 변화를 전파하는 것으로 보이네요.
이를 막아줄 수 있는 방법은 무엇이 있을까요?

2024-07-06 15:38 UTC, pswaao88 commented on src/main/resources/schema.sql
> +);
과제를 진행할 때 sql 테이블을 만드는 것을 신경쓰지 못 한것 같습니다. 데이터 정합성에 대해 다시 한번 더 공부를 하고 sql를 만들 때도 신경쓰도록 하겠습니다!

2024-07-06 15:46 UTC, pswaao88 commented on src/main/java/gift/Exception/ProductExceptionHandler.java
> +        return new ResponseEntity<>(e.getBindingResult().getFieldErrors().getFirst().getDefaultMessage() ,HttpStatus.BAD_REQUEST);
모든 예외에 대해서 핸들러를 만들면 안되는 줄 알고 해당하는 오류만 만들었는데 다른 모든 예외에 대해서 만드는 것은 힘들다고 생각이 됩니다! 그래서 Exception으로 변경하였습니다!

2024-07-06 15:55 UTC, pswaao88 commented on src/main/java/gift/Exception/ProductExceptionHandler.java
>  @ControllerAdvice
과제를 수행할 때 단순하게 @Controller를 썻으니 똑같이 @ControllerAdvice를 써야겠다고 생각을 했었습니다.
찾아본 결과 ControllerAdvice는 단순하게 오류를 처리 할때, RestControllerAdvice는 오류 처리한 후 객체로 리턴을 할 때 쓰인다고 알게 되었습니다!

2024-07-06 16:03 UTC, pswaao88 commented on src/main/java/gift/Controller/ProductController.java
>      }
계층을 나누어 구현을 해서 만족을 하는 줄 알고 있었습니다. Product객체 해당하는 ProductDto를 만들어 해결할 수 있을거 같습니다.

2024-07-07 06:16 UTC, Hyeon9mak approved these changes
안녕하세요 상우님! 피드백 잘 반영해주셨습니다 👍 
다음 단계 진행을 위해서 approve 할게요!
간단히 남긴 코멘트 확인해주세요!

2024-07-07 06:16 UTC, Hyeon9mak commented on src/main/resources/schema.sql
> +    email VARCHAR(255) NOT NULL UNIQUE
😉 👍

2024-07-07 06:16 UTC, Hyeon9mak commented on src/main/java/gift/Exception/ProductExceptionHandler.java
> +        return new ResponseEntity<>(e.getMessage() ,HttpStatus.BAD_REQUEST);
전체 예외에 대해서는 `Exception` 으로 다뤄주고, 별도로 다루고 싶은 예외만 추가로 구현해주면 각각 나누어 핸들링이 가능해요! 👍

2024-07-07 06:16 UTC, Hyeon9mak commented on src/main/java/gift/Exception/ProductExceptionHandler.java
> +        return new ResponseEntity<>(e.getMessage() ,HttpStatus.BAD_REQUEST);
`Exception` 으로 묶어서 다룰 경우 의도치 않게 서버의 중요한 데이터가 사용자에게 노출될 수 있으므로, 커스텀한 에러 메세지를 만들어 사용자에게 전달하는게 보안측면에서 더 좋겠네요!

2024-07-07 06:16 UTC, merged