경북대 BE_안재민 2주차 과제 (0단계)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #5
Opened 2024-07-01 03:49 UTC by dkswoals

2024-07-01 12:20 UTC, leaf-upper requested changes
안녕하세요 재민님~ 1주차에 이어서 2주차도 잘부탁드려요
0단계는 1주차 코드를 그대로 가져오는것이지만
다시한번 봐주셨으면 하는 코드들이 있어서 다시 리뷰드립니다.

2024-07-01 12:20 UTC, leaf-upper commented on src/main/java/gift/Model/Item.java
> +package gift.Model;
package명은 소문자로 작성해주세요~

2024-07-01 12:20 UTC, leaf-upper commented on src/main/java/gift/controller/ItemController.java
> +    private ItemService itemService;
Autowired가 아니라 생성자 주입방식으로 빈주입을 받는게 좋을것 같아요~
추가로 이후 ItemService가 변경되지 않도록 final 키워드도 붙여주시면 좋습니다.

2024-07-01 12:20 UTC, leaf-upper commented on src/main/java/gift/repository/JdbcTemplateRepository.java
> +    public void insert(ItemDTO itemDTO) {
Insert할때는 ItemDto, 조회할때는 Item으로 반환하시는 이유가 궁금한데 
혹시 이유가 있을까요?

2024-07-01 12:20 UTC, leaf-upper commented on src/main/java/gift/service/ItemService.java
> +    //Item 저장 메서드
- 주석은 코드가 수정되었을때, 같이 반영되기 어려운 측면이 있어요
코드만 보더라도 해당 메서드가 무슨동작인지 알수있게끔 해주시면 좋을것 같습니다.
현재는 기능이 거의 없기 때문에 해당 메서드가 어떤 동작인지 알 수 있어서 
주석은 꼭 필요하진 않을것 같아요.

- 데이터를 저장하면 관련 데이터에 대한 PK (ID)가 발번될텐데요, 해당 ID라도 리턴문에 추가해주는건 어떨까요?

2024-07-01 12:20 UTC, leaf-upper commented on src/main/resources/schema.sql
> +    id bigint generated by default as identity,
NOT NULL 제약조건등 필수 컬럼이라고 생각하시는 부분에 대해선 추가해주시면 좋을것 같아요

2024-07-01 12:49 UTC, dkswoals commented on src/main/java/gift/Model/Item.java
> +package gift.Model;
바로 변경하겠습니다!

2024-07-01 12:49 UTC, dkswoals commented on src/main/java/gift/controller/ItemController.java
> +    private ItemService itemService;
바로 변경하겠습니다!

2024-07-01 13:46 UTC, dkswoals commented on src/main/java/gift/repository/JdbcTemplateRepository.java
> +    public void insert(ItemDTO itemDTO) {
사용자에게 Item을 입력을 받은 후 db에 저장될 때 까지 ItemDTO에 id의 쓰임이 없다고 판단하여 ItemDTO에 id 속성을 두지 않고 그대로 db로 저장하고자 하였습니다.
하지만 반대로 생각해보니 저 DTO는 id가 없는 상태의 item만 담을 수 있어 역할이 한정된 dto가 되어버리는군요,,

사용자의 상품 입력이 db에 저장될 때까지 id가 할당되지 않는데 id 속성이 필요한가? 와 
그렇다고 id 정보가 존재하는 객체가 필요할 때 dto를 냅두고 다른 객체를 사용하는건 비효율적이지 않나,, 라는 생각 사이에서 고민이 됩니다.
  
내가 이 객체를 어떠한 의도로 쓰고 있지? 라는 고민을 좀 더 해봐야 할 거 같습니다.

2024-07-01 13:59 UTC, dkswoals commented on src/main/java/gift/service/ItemService.java
> +    //Item 저장 메서드
변경하겠습니다!

2024-07-01 14:00 UTC, dkswoals commented on src/main/resources/schema.sql
> +    id bigint generated by default as identity,
넵 적용시키겠습니다!

2024-07-01 22:45 UTC, dkswoals commented
피드백 반영 하였습니다.

2024-07-02 05:18 UTC, dkswoals commented on src/main/java/gift/Model/Item.java
> +package gift.Model;
피드백 반영하였습니다!

2024-07-02 05:21 UTC, dkswoals commented
step0 피드백 반영 하였습니다!

2024-07-02 14:23 UTC, leaf-upper approved these changes
👍 고생하셨습니다 재민님 다음단계 진행 부탁드립니다!

2024-07-02 14:23 UTC, merged