경북대BE_안용진_2주차 과제(step0)
kakao-tech-campus-2nd-step2/spring-gift-wishlist pull request #74
Opened 2024-07-01 11:40 UTC by sapsalian

멘토님께서 해주신 피드백을 반영하여 리팩토링 해 보았습니다.

## 수정한 사항
- schema.sql로 자동 스키마 설정하도록 수정
- 필드 기반 빈 주입에서, 생성자 기반 빈 주입으로 변경
- Rest 요청을 처리하는 모든 메서드가 일관적으로 ResponseEntity를 반환하도록 변경
- Exception.class 를 처리하는 예외 핸들러를 두어, 미처 생각지 못했던 예외가 발생했을 때 처리할 수 있도록 변경

## 앞으로 반영할 사항
- id가 애플리케이션에서 생성되는 것이 아닌, 데이터 베이스에서 자동으로 할당되도록 변경하기
- Exception.class를 처리하는 예외 핸들러에 예외 로깅 기능 추가하기

2024-07-01 12:49 UTC, leaf-upper requested changes
안녕하세요 용진님
1주차에 이어 2주차도 잘부탁드려요~ 0단계에서 몇가지 코멘트를 더 작성하였는데요~
관련해서 공부해보시고 코드에 반영해주시면 좋을것 같습니다.

2024-07-01 12:49 UTC, leaf-upper commented on src/main/java/gift/Application.java
> +    JdbcTemplate jdbcTemplate;
이부분은 사용되지 않는 코드인것 같아요~ 
제거해두시면 좋을것 같습니다.

2024-07-01 12:49 UTC, leaf-upper commented on src/main/java/gift/controller/AdminController.java
> +    private ProductDAO productDAO;
이부분도 생성자 기반으로 빈주입을 받을수 있지 않을까요?
final 키워드도 붙이면 더욱 좋을것 같아요~

2024-07-01 12:49 UTC, leaf-upper commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        // 여기서 로깅
주석은 꼭 필요한곳에서 사용해주시면 좋을것 같아요.
여기서 로깅을 이후에 해야한다는것을 표시하려면
TODO와 관련된 Prefix를 붙여두시면 좋을것 같습니다.

2024-07-01 12:49 UTC, leaf-upper commented on src/main/java/gift/repository/ProductDAO.java
> +    JdbcTemplate jdbcTemplate;
이부분도 생성자 기반 빈주입 + final 키워드 + private 접근제어자 붙여볼 수 있지 않을까요?

2024-07-01 12:49 UTC, leaf-upper commented on src/main/java/gift/repository/ProductDAO.java
> +    private long idTraker = 1;
id는 데이터베이스에서 고유해야하는 값인데, 해당 값은 멀티스레드 환경에서 안전하지 못한것 같아요~
다른 방식을 고민해주시면 좋을것 같습니다.

2024-07-01 12:49 UTC, leaf-upper commented on src/main/java/gift/repository/ProductDAO.java
> +    public ProductRecord[] getAllRecords() {
배열보다는 리스트 자료구조가 더 범용성이 좋을것 같아요~

2024-07-01 12:49 UTC, leaf-upper commented on src/main/java/gift/repository/ProductDAO.java
> +    public ProductRecord addNewRecord(ProductRecord product, long id) throws DuplicateKeyException {
이렇게 중복을 체크하더라도, 멀티스레드 환경에서는 안전하지 못할것 같아요.
병렬성을 좀더 고민해보시면 좋을것 같습니다.

2024-07-01 12:49 UTC, leaf-upper commented on src/main/resources/schema.sql
> +CREATE TABLE products(id long, name VARCHAR(255), price INT, imageUrl TEXT(65535));
데이터베이스에서 ID는 PK로 사용되고, PK는 정말 중요한 역할을 해서, 꼭 공부해보시면 좋을것 같습니다.
추가로 데이터베이스에서 설정할 수 있는 다양한 제약조건이 존재하는데 그중 NOT NULL 제약조건도 한번 봐주시면 좋을것 같아요.

2024-07-02 03:01 UTC, sapsalian commented on src/main/java/gift/Application.java
> +    JdbcTemplate jdbcTemplate;
앗 그렇네요! 수정하도록 하겠습니다!

2024-07-02 03:03 UTC, sapsalian commented on src/main/java/gift/controller/AdminController.java
> +    private ProductDAO productDAO;
엇 그러네요, 빈 주입을 받는 다른 부분도 모두 변경했어야 하는데. 수정토록 하겠습니다!

2024-07-02 03:03 UTC, sapsalian commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        // 여기서 로깅
아하 그렇군요! TODO prefix를 사용하겠습니다!

2024-07-02 03:04 UTC, sapsalian commented on src/main/java/gift/repository/ProductDAO.java
> +    JdbcTemplate jdbcTemplate;
넵! 수정하겠습니다!

2024-07-02 03:04 UTC, sapsalian commented on src/main/java/gift/repository/ProductDAO.java
> +    private long idTraker = 1;
데이터베이스에서 id를 생성하도록 변경하겠습니다!

2024-07-02 03:22 UTC, sapsalian commented
- 사용하지 않는 코드 제거
- 필드 주입 사용하는 모든 부분 생성자 주입으로 변경
- 주석 Todo prefix 사용
- 배열 대신 리스트 자료구조 사용
- id 데이터베이스에서 생성하도록 변경

2024-07-02 14:27 UTC, leaf-upper approved these changes
고생하셨습니다~ 용진님
다음단계 진행 부탁드릴게요!

2024-07-02 14:28 UTC, merged